### DISCUSSION TITLE
米家全能扫拖机器人M30 Pro 分区清扫卡片分享

### DISCUSSION THREAD

**Discussion by al-one** [al-one/hass-xiaomi-miot#2225] [Show and tell]
<img width="483" alt="xiaomi.vacuum.c107" src="https://github.com/user-attachments/assets/a3f388ca-eea6-4afe-b85b-e16d37f71ba3">

------

1. 获取[`M30 Pro`](https://home.miot-spec.com/s/xiaomi.vacuum.c107)的房间ID
   - 在米家扫地机页面上滑创建自定义清洁，并选中所有房间
   - 在HA中查看此设备的`信息`实体的`vacuum.user_define_sweep_cfg`属性
    ```yaml
    vacuum.user_define_sweep_cfg: {"user_labels":[{"id":1733936025,"name":"客厅日常","v":1,"mop":[4],"room_ids":[3,6,9],"user_cfg":[]}]}
    ```

2. 新增 `input_text` 辅助元素
   - [⚙️ 配置](https://my.home-assistant.io/redirect/config) > 设备与服务 > [🧩 辅助元素](https://my.home-assistant.io/redirect/helpers) > ➕创建辅助元素 > 文本
   <img width="300" alt="xiaomi_vacuum_roomids" src="https://github.com/user-attachments/assets/da6d8277-c6f4-44a7-8a85-863de051a652">

3. 新建脚本
   - [⚙️ 配置](https://my.home-assistant.io/redirect/config) > 🤖自动化与场景 > [脚本](https://my.home-assistant.io/redirect/scripts) > ➕创建脚本
   - 建议名称 `xiaomi_vacuum_room_select`
    ```yaml
    alias: 扫拖机器人 选择房间
    icon: mdi:robot-vacuum
    sequence:
      - variables:
          roomids: |-
            {%- set rid = roomid|int(0) %}
            {%- set ids = states(input) %}
            {%- if ids is not match('\[.*\]') %}
            {%-   set ids = '[]' %}
            {%- endif %}
            {%- set ids = ids|from_json %}
            {%- set has = rid in ids %}
            {%- set ids = ids | reject('equalto', rid) | list %}
            {%- if not has %}
            {%-   set ids = ids + [rid] %}
            {%- endif %}
            {{- ids|to_json }}
      - action: input_text.set_value
        data:
          entity_id: "{{ input }}"
          value: "{{ roomids }}"
      - alias: 关联设备
        if:
          - condition: state
            entity_id: button.xiaomi_c107_xxxx_info # 扫地机的任意实体ID
            state: ""
          - condition: state
            entity_id: input_text.xiaomi_vacuum_roomids # 辅助元素实体ID
            state: ""
        then: []
    fields:
      input:
        name: 房间ID实体
        default: input_text.xiaomi_vacuum_roomids # 辅助元素实体ID
        required: true
        selector:
          entity: {}
      roomid:
        required: true
        default: 1
        selector:
          number:
            min: 1
            max: 100
            step: 1
    ```

4. 安装前端卡片插件
   - [mushroom](https://my.home-assistant.io/redirect/hacs_repository/?owner=piitaya&repository=lovelace-mushroom)
   - [button-card](https://my.home-assistant.io/redirect/hacs_repository/?owner=custom-cards&repository=button-card)
   - [config-template-card](https://my.home-assistant.io/redirect/hacs_repository/?owner=iantrich&repository=config-template-card)
   - 安装后按提示重载前端

5. 配置`button-card`模版
   - 参考 #226 
   - ⚙ 编辑仪表盘 > 原始配置编辑器
   - <img width="600" src="https://user-images.githubusercontent.com/4549099/140305446-7a6a8422-1c69-4a04-b632-137b99d4e33a.png">
    ```yaml
    button_card_templates:
      more_info:
        tap_action:
          action: more-info
        double_tap_action:
          action: more-info
        hold_action:
          action: more-info
      tap_toggle:
        tap_action:
          action: toggle
      double_toggle:
        double_tap_action:
          action: toggle
      hold_toggle:
        hold_action:
          action: toggle

      homekit_card:
        template: more_info
        size: 100%
        show_state: true
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 15px
          grid:
            - grid-template-areas: '"i" "l" "n" "s"'
            - padding: .5em .5em .5em 1em
          img_cell:
            - width: 50%
            - padding-bottom: .5em
            - justify-self: start
          icon:
            - color: gray
          name:
            - color: '#fff'
            - justify-self: start
          state:
            - color: gray
            - justify-self: start
            - font-size: .9em
          label:
            - color: gray
            - justify-self: start
            - font-size: .8em
        extra_styles: |
          @keyframes blink2 {
            000% { opacity: 1; }
            050% { opacity: .3; }
            100% { opacity: 1; }
          }

      homekit_sensor:
        template: homekit_card

      homekit_switch:
        template: homekit_card
        state:
          - id: state_on
            value: 'on'
            styles:
              card:
                - font-weight: bold
                - background-color: rgba(255,255,255,0.7)
              icon:
                - color: '#ff9f09'
              name:
                - color: '#000'
          - id: state_off
            value: 'off'
        tap_action:
          action: toggle

      vacuum_room:
        template: homekit_switch
        variables:
          roomid: 0
          checked: |
            [[[
              return function(rid) {
                return 0
                || entity.state.indexOf(rid+',') >= 0
                || entity.state.indexOf(rid+']') >= 0;
              }
            ]]]
        show_state: false
        state:
          - id: state_on
            operator: template
            value: |
              [[[ return variables.checked(variables.roomid) ]]]
        tap_action:
          action: call-service
          service: script.xiaomi_vacuum_room_select # 脚本ID
          service_data:
            input: '[[[ return entity.entity_id ]]]'
            roomid: '[[[ return variables.roomid ]]]'
    ```

6. 新增卡片
    ```yaml
    type: vertical-stack
    cards:
      - type: grid
        square: true
        columns: 3
        cards:
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids # 辅助元素ID
            name: 走廊
            icon: mdi:piano
            variables:
              roomid: 3
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 主卧
            icon: mdi:bed-double
            variables:
              roomid: 4
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 主卧
            icon: mdi:bed-double
            variables:
              roomid: 4
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 客厅
            icon: mdi:sofa
            variables:
              roomid: 6
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 次卧
            icon: mdi:bed
            variables:
              roomid: 5
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 次卧
            icon: mdi:bed
            variables:
              roomid: 5
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 客厅
            icon: mdi:table-chair
            variables:
              roomid: 6
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 卫生间
            icon: mdi:toilet
            variables:
              roomid: 9
          - type: custom:button-card
            template: vacuum_room
            entity: input_text.xiaomi_vacuum_roomids
            name: 厨房
            icon: mdi:food-turkey
            variables:
              roomid: 7
      - type: grid
        square: false
        columns: 3
        cards:
          - type: custom:config-template-card
            variables:
              STATE: states['input_text.xiaomi_vacuum_roomids']
            entities:
              - ${STATE.entity_id}
            card:
              type: custom:mushroom-template-card
              primary: 分区清扫
              secondary: ${STATE.state} # 显示房间ID
              icon: mdi:border-bottom
              layout: horizontal
              multiline_secondary: false
              tap_action:
                action: perform-action
                perform_action: xiaomi_miot.call_action
                data:
                  entity_id: button.xiaomi_c107_xxxx_info # 扫地机的info/vacuum实体
                  siid: 2
                  aiid: 16
                  params:
                    - ${STATE.state}
          - type: custom:mushroom-select-card
            entity: select.xiaomi_c107_xxxx_mode
            secondary_info: none
            primary_info: none
            icon: mdi:fan
            layout: horizontal
            icon_type: none
          - type: custom:mushroom-select-card
            entity: select.xiaomi_c107_xxxx_sweep_mop_type
            primary_info: none
            secondary_info: none
            icon_type: none
            icon: mdi:robot-vacuum
            layout: horizontal
          - type: custom:config-template-card
            variables:
              STATE: states['button.xiaomi_c107_xxxx_info']
            entities:
              - ${STATE.entity_id}
            card:
              type: custom:mushroom-template-card
              primary: 打开米家
              secondary: ""
              icon: mdi:apple
              icon_color: teal
              tap_action:
                action: url
                url_path: ${STATE.attributes.app_link}
              layout: horizontal
              fill_container: true
          - type: custom:mushroom-entity-card
            entity: button.xiaomi_c107_xxxx_pause_sweeping
            name: 暂停清扫
            layout: horizontal
            secondary_info: none
            tap_action:
              action: toggle
            icon: mdi:motion-pause
            icon_color: accent
          - type: custom:mushroom-entity-card
            entity: button.xiaomi_c107_xxxx_start_charge
            name: 开始回充
            layout: horizontal
            secondary_info: none
            tap_action:
              action: toggle
            icon: mdi:home-battery
            icon_color: cyan
      - type: entities
        entities:
          - entity: vacuum.xiaomi_c107_xxxx_robot_cleaner
          - entity: sensor.xiaomi_c107_xxxx_status
          - entity: sensor.xiaomi_c107_xxxx_battery_level
    ```
