### DISCUSSION TITLE
Xiaomi camera/doorbell Recording and Notify / 摄像头或门铃录像并通知

### DISCUSSION THREAD

**Discussion by al-one** [al-one/hass-xiaomi-miot#2449] [Show and tell]
![xiaomi miot doorbell](https://github.com/user-attachments/assets/90e8cbcd-5005-4e91-81d6-26f07ca71fd0)

### 🔔 Prerequisites:
- Enable `Home surveillance` in the Mi Home app
- Your camera/doorbell has been integrated into HA via this component
- A camera entity has been created and screenshots can be seen in HA

### 📚 Guides:
1. Add the script for saving the video recording / 添加保存录像脚本
```yaml
# configuration.yaml
shell_command:
  # other commands ...
  save_xiaomi_video: |
    bash -c '
      mp4="{{ name|default('latest') }}.mp4"
      dir="{{ dir|default('/media/camera',true) }}"
      mkdir -p "$dir" && cd "$dir"
      script=/config/custom_components/xiaomi_miot/scripts/save_xiaomi_video.sh
      if [ -f "$script" ]; then
        bash "$script" "{{ url }}" "$mp4"
      else
        ffmpeg -y -i "{{ url }}" -c copy "$mp4"
      fi
      ls *.mp4 | sort | head -n -{{ keep|default(100) }} | xargs rm -vf
      if [ -n "{{ img }}" ]; then
        curl -o "{{ name|default('latest') }}.jpg" "{{ img }}"
        ls *.jpg | sort | head -n -{{ keep|default(100) }} | xargs rm -vf
      fi
    '
```
> 由于小米摄像机/门铃看家助手提供的hls流在通过ffmpeg转换成mp4时会出错，仅能保存第一个切片(5秒内)，因此提供了`save_xiaomi_video.sh`脚本，该脚本会逐个转换每个ts切片最后拼接成完整mp4，该脚本已随着`v1.0.17`版本一起发布了。

2. Restart Home Assistant / 重启 Home Assistant

3. Import [blueprint](https://github.com/al-one/hass-xiaomi-miot/blob/master/blueprints/automation/camera-recording-notify.yaml) / 导入蓝图
    - [基础版: 仅支持通知到手机](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgitee.com%2Fal-one%2Fhass-xiaomi-miot%2Fraw%2Fmaster%2Fblueprints%2Fautomation%2Fcamera-recording-notify-phone.yaml)
    - [进阶版: 支持通知到任何服务](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgitee.com%2Fal-one%2Fhass-xiaomi-miot%2Fraw%2Fmaster%2Fblueprints%2Fautomation%2Fcamera-recording-notify.yaml)

4. Create automation via blueprint / 通过蓝图创建自动化
    ```yaml
    # Example of notify to a phone
    action: notify.mobile_app_your_iphone
    data:
      title: '{{ camera_device_name }}'
      message: '{{ event }} 🔋{{ battery }}'
      data:
        image: "{{ img_path }}"
        video: "{{ mp4_path }}"
        url: /config/devices/device/{{ camera_device_id }}
        actions:
          - action: URI
            title: 打开米家
            uri: "{{ state_attr(camera_info_id,'app_link') }}"
          - action: none
            title: 我知道了
        push:
          tag: "{{ camera_entity_id }}"
          sound:
            name: default
            critical: "{{ 1 if 'Bell' in motion_video_type else 0 }}"
            volume: 0.3
    ```
    <img width="800" alt="image" src="https://github.com/user-attachments/assets/aa072f56-e093-403f-9d6f-5f3154e02269">
