### ISSUE TITLE
FAQ - 常见问题

### ISSUE THREAD

**Issue by al-one** [al-one/hass-xiaomi-miot#100]

**Comment by al-one** [comment]
❓️ 支持哪些设备？是否支持XX型号？
🙋 本插件是通过miot-spec规范接入设备的，因此是通过设备所提供的服务(`service`)对其提供支持。比如一个风扇灯设备，在其型号对应的spec中定义了灯、风扇两个服务，本插件则会根据这两个服务及其属性(`property`)、方法(`action`)将设备集成到HA中。查看目前已支持的设备服务请[点击这里](https://github.com/al-one/hass-xiaomi-miot/#supported-devices)。

**Comment by al-one** [comment]
❓️ 账号集成还是token集成？
🙋 账号集成通过小米云获取该账号下的所有设备，并可通过筛选型号、WiFi等批量将符合条件的设备集成到HA，该方式集成的设备会默认使用云端模式，即所有读写操作都通过小米云，但是可以通过添加自定义属性`miot_local`使其在局域网读写。token集成可以将在局域网环境下支持miot-spec协议的设备接入HA。

**Comment by al-one** [comment]
❓️ 为什么XX型号的设备需要开启云端模式？如何开启？

---

🙋 由于部分设备使用的是旧版的miio协议，在局域网环境下无法通过miot-spec协议读写数据，但是却可以在小米云端使用miot-spec协议，因此此类设备需要开启云端模式后才可以正常接入。

🙋 开启云端模式的具体方法：
- 使用账号集成
    - 账号集成的设备默认已开启云端模式
- 使用token集成
    > [⚙️ 配置](https://my.home-assistant.io/redirect/config) > [🧩 集成](https://my.home-assistant.io/redirect/integrations) > Xiaomi Miot Auto > 选项 > ☑️ 开启云端模式

**Comment by al-one** [comment]
❓️ 怎样为一个实体添加自定义属性？

---

🙋 添加自定义属性有以下两种方式：

1. 通过HomeAssistant界面添加（[官方说明](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui)）
    - [⚙️ 配置](https://my.home-assistant.io/redirect/config) > 🖌 自定义 （如果在配置页底部找不到`自定义`入口，需要进入[个人资料](https://my.home-assistant.io/redirect/profile)页开启`高级模式`）
    - 首次配置自定义属性，你可能还需要在配置文件`configuration.yaml`中加入以下代码：
      ```yaml
      homeassistant:
        customize: !include customize.yaml
      ```
    - 在`自定义`页面，选择需要添加属性的实体
    - 选择要覆盖的属性，选择`Other`
    - 填入属性名(`Attribute name`)、属性值(`Attribute value`)
    - 保存并等待片刻后生效
2. 通过YAML添加
    - 在你的HA目录下找到`customize.yaml`，如果没有该文件请先创建
    - 按照以下格式添加自定义属性：
      ```yaml
      sensor.your_entity_id:
        attribute_name: attribute_value
      ```
    - [⚙️ 配置](https://my.home-assistant.io/redirect/config) > [服务控制](https://my.home-assistant.io/redirect/server_controls) > 配置重载：`位置和自定义`

添加自定义属性只要是为了扩展功能和解决不同型号的设备对miot-spec及HA的兼容问题，查阅目前本插件支持的自定义属性请[点击这里](https://github.com/al-one/hass-xiaomi-miot/blob/master/README_zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AE%9E%E4%BD%93)。

**Comment by al-one** [comment]
❓️ 如何翻译实体的选项文本？

---

🙋 通过本插件集成的设备实体，比如风扇的预设模式等选项可能为英文，这是因为设备厂家在定义miot-spec协议的时候填写的是英文。而本插件在https://github.com/al-one/hass-xiaomi-miot/commit/921fc033810ddb21d06444c6d5e25125e2a5898e 中支持翻译这些选项文本，目前可通过配置`configuration.yaml`实现，具体方法如下：
1. 使用插件默认的翻译词库
    ```yaml
    xiaomi_miot:
      language: zh # 目前仅支持翻译到中文，且只支持扫地机、洗衣机，将随着版本升级陆续完善
    ```
2. 扩展自己的翻译词库示例
    ```yaml
    xiaomi_miot:
      translations:
        # 全局词库，对所有实体生效
        'idle': '空闲'
        'busy': '工作中'
        # 指定风扇模式的词典
        'fan.mode':
          'Straight Wind': '直吹模式'
          'Natural Wind': '自然风'
        # 指定洗衣机烘干模式的词典
        'washer.drying_level':
          'moist': '微湿'
          'extra': '特干'
    ```

**Comment by al-one** [comment]
❓️ 如何使用**小爱同学**播放文本(TTS)和执行语音命令？

---

🙋 通过本插件接小爱音响后会生成一个`media_player`实体，该实体可以控制播放暂停、调节音量和静音等，更多的功能需要通过[HA服务](https://my.home-assistant.io/redirect/developer_services)去调用，比如本插件为小爱提供了[`xiaomi_miot.intelligent_speaker`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.intelligent_speaker)服务可以实现TTS和执行语音命令。
- 播放文本(TTS)
  ```yaml
  service: xiaomi_miot.intelligent_speaker
  data:
    entity_id: media_player.xiaoai_x08c_d135
    text: 你好
    execute: false # 不执行，朗读text文本
  ```
- 执行语音命令
  ```yaml
  service: xiaomi_miot.intelligent_speaker
  data:
    entity_id: media_player.xiaoai_x08c_d135
    text: 开灯
    execute: true # 执行text命令
    silent: false # 是否静默执行，为true时小爱将在执行命令后无反馈
  ```
> 部分小米电视(支持小爱同学)也可用此服务执行语音命令，但是由于协议限制，无法TTS

**Comment by al-one** [comment]
❓️ 如何在HA查看摄像头实体回放(看家助手)视频？

---

🙋 本插件在[v0.4版本](https://github.com/al-one/hass-xiaomi-miot/releases/tag/v0.4.0b0)中添加了对**摄像头**、**猫眼**及**可视门铃**的回放视频支持，原理是通过米家接口获取设备的最后一个看家助手视频。目前猫眼、可视门铃更新插件后即可直接看到画面，而摄像头设备需要[添加自定义属性](#issuecomment-864678774)`use_motion_stream: true`才可启用回放，另外还有一个自定义属性`sub_motion_stream: true`是单独生成一个`camera`实体来显示回放，两个属性选其一。
由于小米云端视频文件编码的问题，部分型号摄像头的回放视频仍然无法播放，你可以尝试为主实体[添加自定义属性](#issuecomment-864678774)`motion_stream_slice: -1`，经测试此方法可能会显示一个静止的视频画面，原因未知。
```yaml
# customize.yaml
camera.your_entity_id:
  use_motion_stream: true # 在主实体开启回放，猫眼默认已开启
  sub_motion_stream: true # 为回放视频单独生成一个camera实体
  motion_stream_slice: -1 # 视频切片文件索引，-1表示最后一个切片文件，0表示第一个
```

**Comment by al-one** [comment]
❓️ 为什么设备状态会有延迟？如何减小延迟？

---

🙋 延迟通常是指通过米家APP或物理按键等操作设备后，设备在HA中的实体状态要等几秒甚至十几秒后才会更新。原因是本插件目前主要是通过轮询的方式获取设备状态，通俗的讲就是每个几十秒去刷新一次状态。在token方式集成时，这个时长是可以直接修改的(添加集成和修改集成选项均可)，目前默认是30秒。而通过账号集成时，由于一个集成配置会对应多个设备，因此无法统一配置，需要为每个设备实体添加[自定义属性](#issuecomment-864678774)`interval_seconds`来修改轮询时长：
```yaml
# customize.yaml
sensor.your_entity_id:
  interval_seconds: 20 # 轮询时长(秒)
```
一般情况下，对于开关、灯、环境传感器等设备，我们推荐使用默认轮询时长即可，过于频繁的请求状态可能会使设备负载过高，且大部分请求是无意义的。
对于人体传感器、门磁、无线开关类设备，它们的状态通常为瞬时状态(即：事件)，部分型号支持获取最后一次事件触发的时间，且默认轮询时长为15秒，对于无法获取最后触发事件的设备，即使修改轮询时间到1秒，也可能无法获取正确的状态。因此此类设备通过本插件集成后不太推荐用于触发实时自动化，仅适合作为如几分钟无人移动关灯这类自动化的条件。如果需要实时更新状态，推荐使用[多模网关](https://home.miot-spec.com/?q=lumi.gateway.mgl03)配合[XiaomiGateway3](https://github.com/AlexxIT/XiaomiGateway3)集成。
另外还有一种延迟，比如在HA打开某个实体开关后，几秒内开关回弹到操作前的状态，然而实际上已经操作成功，并在一分钟内实体状态又恢复到实际状态。这种情况通常发生在小米账号(云端)接入的设备，具体原因是操作后指令发送给设备后HA会立即请求新的状态，而这个时候设备还未将新的状态同步到小米云端，导致获取到操作之前的状态，一分钟后HA重新获取到实际的状态。目前本插件针对这种情况已经做了优化，大部分设备已不会出现，如果你的设备有出现，请[提交issue](https://github.com/al-one/hass-xiaomi-miot/issues/new/choose)。
