### ISSUE TITLE
Xiaomi Mi Mop 1C (dreame.vacuum.mc1808) remote function

### ISSUE THREAD

**Issue by LukasMendez** [al-one/hass-xiaomi-miot#1001]
### Device model / 设备型号

[dreame.vacuum.mc1808](https://home.miot-spec.com/s/dreame.vacuum.mc1808)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.1.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi. I have a Xiaomi Mi Mop (Mi 1C) Robot Vacuum. 

I've added them successfully to Home Assistant using your integration. However I simply can't find any documentation on how `xiaomi_miot.send_command` and  `xiaomi_miot.call_action` works? How do I know which parameters that I can specify? Where do I find the list of supported methods? 

In your example you are making a start-clean action, but is there a list of functions I can use with my device? 

Apart from that what I'm actually trying to achieve is the possibility to remote control my vacuum, so that I can get it out of its dock without having to manually open the app and do so. 

In the Xiaomi app I currently have this view: 

![image](https://user-images.githubusercontent.com/43059840/212673751-b95bbe35-f99f-427e-8845-fd43817e1764.png)

But I'm not entirely sure if this is possible with your integration. 

Hope you can guide me in the right direction. 

### Entity attributes / 实体属性
```yaml
fan_speed_list: 安静, 标准, 中档, 强力
battery_level: 94
battery_icon: mdi:battery-90
fan_speed: 标准
model: dreame.vacuum.mc1808
lan_ip: 192.168.87.162
mac_address: 7C:25:DA:5C:0B:FE
entity_class: MiotVacuumEntity
exclude_miot_services: consumable, annoy, remote, time
exclude_miot_properties: delete_timer, clean_info, map_view, frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-mc1808:1
vacuum.fault: 0
vacuum.status: 1
audio.volume: 75
audio.voice_packets: ES
clean.work_mode: 2
clean.area: 
clean.timer: 85-0-1662058057-12:00-0000010-1-1-0,21-1-1662354096-13:00-0111100-1-1-0
clean.mode: 1
clean.water_box: 1
clean.total_clean_time: 4426
clean.total_clean_times: 108
clean.total_clean_area: 2875
clean.clean_log_start_time: 1661530887
clean.button_led: 0
clean.task_done: 0
brush_left_time-28-1: 73
brush_life_level-28-2: 36
filter.filter_life_level: 15
filter.filter_left_time: 23
brush_cleaner.brush_left_time: 173
brush_cleaner.brush_life_level: 57
battery.charging_state: 2
state_updater: lan
vacuum.status_desc: Sweeping
sub_entities: vacuum-3.status-2, filter-27.filter_life_level-1, filter-27.filter_left_time-2, battery-2.battery_level-1, battery-2.charging_state-2, brush_cleaner-26.brush_left_time-1, brush_cleaner-26.brush_life_level-2, brush_cleaner-28.brush_left_time-1, brush_cleaner-28.brush_life_level-2
friendly_name: Consuela Robot Cleaner
supported_features: 13048
```

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/dreame.vacuum.mc1808

![xiaomi miot dreame.vacuum.mc1808](https://user-images.githubusercontent.com/4549099/212876002-35d7e394-b198-43e3-b82f-d698159e56db.png)

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_mc1808_entity_id
  siid: 21 # remote
  aiid: 1  # start-remote
  params:
    - '90' # piid: 1 - deg
    - '10' # piid: 2 - speed
  throw: true # throw result to HA notifications
```

I'm not sure what the specific `params` are, maybe it can be obtained through the [MiHome APP modified by vevs](https://github.com/al-one/hass-xiaomi-miot/issues/114#issuecomment-868721912).
