### ISSUE TITLE
智能摄像机云台版pro无画面

### ISSUE THREAD

**Issue by xiaowuap** [al-one/hass-xiaomi-miot#1003]
### Device model / 设备型号

[chuangmi.camera.ipc021](https://home.miot-spec.com/s/chuangmi.camera.ipc021)

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

不显示视频
![image](https://user-images.githubusercontent.com/44547885/212807939-ebdcbf05-b96b-4894-99c9-01ebc658fffe.png)

### Entity attributes / 实体属性
```yaml
access_token: a阿巴阿巴 
model_name: chuangmi.camera.021a04 
brand: chuangmi 
frontend_stream_type: hls 
model: chuangmi.camera.021a04 
lan_ip: 10.10.10.71 
mac_address: 阿巴阿巴 
entity_class: MiotCameraEntity 
home_room: 小吴的家 客厅 
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-021a04:3 
camera_control.on: true 
camera_control.image_rollover: 0 
camera_control.night_shot: 2 
camera_control.wdr_mode: true 
glimmer_full_color-2-6: true 
camera_control.recording_mode: 0 
camera_control.motion_tracking: false 
camera_control.time_watermark: true 
bluetooth.bluetooth_switch: true 
stream_status-8-9: 1 
stream_status-7-9: 1 
motion_detection: false 
motion_detection.alarm_interval: 5 
detection_sensitivity-5-3: 1 
motion_detection_start_time-5-4: 00:00:00 
motion_detection_end_time-5-5: 23:59:00 
memory_card_management.status: 0 
storage_total_space-4-2: 31440896 
storage_free_space-4-3: 32768 
storage_used_space-4-4: 31408128 
indicator_light.on: true 
state_updater: cloud 
sub_entities: motion_detection-5.motion_detection-1, indicator_light-3, camera_control-2.on-1, motion_event miot_action_result:  did: '1023800849' miid: 0 siid: 7 aiid: 1 code: 0 out:   - >-     https://cn02.livestreaming.io.mi.com/hlstranscoder/阿巴阿巴A_H265transH264/playlist.m3u8 exe_time: 0 withLatency: 0  
stream_http_status: 403 
stream_http_reason: Forbidden 
stream_address: https://cn02.livestreaming.io.mi.com/hlstranscoder/阿巴阿巴A_H265transH264/playlist.m3u8 
expire_at: 2023-01-17 12:08:31.162070 
miot_error: null 
entity_picture: /api/camera_proxy/camera.chuangmi_021a04_4400_camera_control?token=阿巴阿巴1 
friendly_name: 客厅摄像头 Camera Control 
supported_features: 3
```
