### ISSUE TITLE
小米电视无法关机和获取电源状态

### ISSUE THREAD

**Issue by wqhqq1** [al-one/hass-xiaomi-miot#1006]
### Device model / 设备型号

media_player.xiaomi_v1_f71f_play_control

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2022.7.7

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米电视其他按键可用，唯独不能关机
获取不到封面截图和开机状态

### Entity attributes / 实体属性

source_list: TV, DTMB, AV, HDMI 1, HDMI 2
model: xiaomi.tv.v1
lan_ip: ---
mac_address: ---
entity_class: MitvMediaPlayerEntity
home_room: William的家 大厅
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-v1:2
6095_state: false
remote_control.state_playing: false
speaker.volume: 18
speaker.mute: false
television.input_control: 3
state_updater: cloud
sub_entities: keycodes, speaker-4.volume-1
miot_action_result: 
did: mitv.1b1e600762f5f72dcf2e224c7718c686:1944456133b44c2b90b82dd9ea516586
miid: 0
siid: 6
aiid: 1
code: 0
exe_time: 8
net_cost: 40
ot_cost: 15
otlocalts: 1674104238423704
_oa_rpc_cost: 66
withLatency: 0

remote_control.state_playing.error: -704042011 Device offline
speaker.volume.error: -704042011 Device offline
speaker.mute.error: -704042011 Device offline
television.input_control.error: -704042011 Device offline
device_class: tv
friendly_name: 客厅的小米电视 Play Control
supported_features: 20365
bind_xiaoai: media_player.xiaomi_lx05_c947_play_control
xiaoai_silent: true
interval_seconds: 1
cloud_delay_update: 1

### Home Assistant Logs / 系统日志

Updating xiaomi_miot switch took longer than the scheduled update interval 0:00:01

**Comment by Cookie987** [comment]
我也有同样的问题：
### Device model / 设备型号
xiaomi.tv.rmi1

### Component version / 插件版本
0.7.5

### HA core version / HA版本
2023.1.5

### Integrated mode / 集成方式
Automatic (自动模式)

### Entity attributes / 实体属性
```yml
source_list:
  - TV
  - DTMB
  - AV
  - HDMI 1
  - HDMI 2
model: xiaomi.tv.rmi1
lan_ip: 192.168.0.2
mac_address: [MAC地址]
entity_class: MitvMediaPlayerEntity
home_room: Cookie987的家 客厅
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-rmi1:1
6095_state: false
speaker.volume: 6
speaker.mute: false
television.input_control: 1
state_updater: cloud
sub_entities:
  - keycodes
  - speaker-4.volume-1
  - message_router-5.post-1
device_class: tv
friendly_name: Cookie987的电视 Play Control
supported_features: 20365
```
### Home Assistant Logs / 系统日志
Update of media_player.xiaomi_rmi1_531c_play_control is taking over 10 seconds

Cookie987的电视(xiaomi.tv.rmi1): Got MiioException while fetching the state: Unable to discover the device 192.168.0.2, mapping: {'speaker.volume': {'siid': 4, 'piid': 1}, 'speaker.mute': {'siid': 4, 'piid': 2}, 'television.input_control': {'siid': 2, 'piid': 1}}, max_properties: 7/3 

>出现上面的日志时电视刚关
