### ISSUE TITLE
米家空气净化器 4 Lite缺少空气质量属性

### ISSUE THREAD

**Issue by lovedreamland** [al-one/hass-xiaomi-miot#1009]
### Device model / 设备型号

[zhimi.airpurifier.rma1](https://home.miot-spec.com/s/zhimi.airpurifier.rma1)

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

zhimi.airpurifier.rma1
这个缺少空气质量属性，米家里面有这个属性，但是我看miot里面又没有，不知道能增加不。
zhimi.airp.rma2
这个正常，两空气净化器都是一个东西。
搞不懂买了两个版本还给弄的不一样

### Entity attributes / 实体属性

无实体

**Comment by al-one** [comment]
提供[实体属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by lovedreamland** [comment]
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-rma2:1
air-quality	Air Quality	uint8
0 - Excellent
1 - Good
2 - Moderate
3 - Poor
4 - Heavy Pollution
5 - Hazardous

这两个其实是一个东西，但是那个老的miot里面的文档却没有写到这个属性，实际上是有这个属性的，不知道是不是文档没有更新的原因。

**Comment by al-one** [comment]
`air-quality`属性在[`zhimi.airpurifier.rma1`](https://home.miot-spec.com/spec/zhimi.airpurifier.rma1)的规格中没有定义。请尝试添加以下配置：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    zhimi.airpurifier.rma1:
      extend_miot_specs:
        - iid: 3
          properties:
            - iid: 3
              type: urn:miot-spec-v2:property:air-quality
              format: uint8
              access: [read,notify]
              value-list:
                - {value: 0, description: Excellent}
                - {value: 1, description: Good}
                - {value: 2, description: Moderate}
                - {value: 3, description: Poor}
                - {value: 4, description: 'Heavy Pollution'}
                - {value: 5, description: Hazardous}
```
