### ISSUE TITLE
米家智能插座2蓝牙网关版功率显示错误

### ISSUE THREAD

**Issue by DavisDcan** [al-one/hass-xiaomi-miot#101]
![图片](https://user-images.githubusercontent.com/50225646/121114032-9dc27e80-c845-11eb-9b12-993b2371cb5d.png)
应为**1726.46**watt，而不是**172,46**watt（注意一个是小数点，一个是逗号，而且标注位置也不正确）
不知道其他带功率显示的产品是否有此问题

**Comment by al-one** [comment]
```json
{
    "property":"electric-power",
    "desc":"Electric Power",
    "access":"read,notify",
    "format":"uint32",
    "unit":"watt",
    "value-range":[
        0,
        6553500,
        1
    ]
}
```
功率的数值及单位均来自设备的[miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:2)协议，该设备功率属性的定义如上。
逗号是由HA对数值显示的格式化，如果不需要可以进入[个人资料](https://my.home-assistant.io/redirect/profile/)修改`数字格式`。
如果想更改功率的小数位，可以使用[template sensor](https://www.home-assistant.io/integrations/template#state-based-template-sensors)：
```yaml
template:
  - sensor:
      - name: "chuangmi_212a01_electric_power"
        device_class: "power"
        unit_of_measurement: "kW"
        state: >
          {% set pow = states('sensor.re_shui_qi_switch_electric_power') | float %}
          {{ (pow / 1000) | round(2) }}
```
