### ISSUE TITLE
Mi Fresh Air Ventilator C1-80 (zhimi.airfresh.ua1) becomes unavailable 10 minutes after being turned on

### ISSUE THREAD

**Issue by Shurik85** [al-one/hass-xiaomi-miot#1015]
### Device model / 设备型号

[zhimi.airfresh.ua1](https://home.miot-spec.com/s/zhimi.airfresh.ua1)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.1.7

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Mi Fresh Air Ventilator C1-80 (zhimi.airfresh.ua1) becomes unavailable 10 minutes after being turned on

<img width="196" alt="C1-80" src="https://user-images.githubusercontent.com/78793454/216408387-9bfc0bf1-4a55-496e-8589-0c1867f2d137.png">

### Entity attributes / 实体属性

preset_modes: 
percentage: null
percentage_step: 33
preset_mode: null
model: zhimi.airfresh.ua1
lan_ip: 192.168.0.159
mac_address: 7C:C2:94:EF:7B:D9
entity_class: MiotFanEntity
miot_type: urn:miot-spec-v2:device:air-fresh:0000A012:zhimi-ua1:1
air_fresh.on: false
air_fresh.fault: 0
air_fresh.fan_level: 1
air_fresh.heater: false
1号直流电机_每分钟转速-8-1: 0
2号直流电机_每分钟转速-8-2: 0
custom_serveice.temperature: 5.9
indicator_light.brightness: 0
alarm: true
physical_controls_locked: false
filter.filter_used_time: 702
filter.filter_life_level: 100
state_updater: lan
sub_entities: air_fresh-2.heater-6, alarm-6.alarm-1, filter-4.filter_used_time-1, filter-4.filter_life_level-2, physical_controls_locked-5.physical_controls_locked-1, indicator_light-7, custom_serveice-8.temperature-5
friendly_name: Mi_Fresh_Air_Ventilator_C1-80 Air Fresh
supported_features: 1

### Home Assistant Logs / 系统日志

Mi_Fresh_Air_Ventilator_C1-80(zhimi.airfresh.ua1): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'air_fresh.on': {'siid': 2, 'piid': 1}, 'air_fresh.fault': {'siid': 2, 'piid': 2}, 'air_fresh.fan_level': {'siid': 2, 'piid': 5}, 'air_fresh.heater': {'siid': 2, 'piid': 6}, '1号直流电机_每分钟转速-8-1': {'siid': 8, 'piid': 1}, '2号直流电机_每分钟转速-8-2': {'siid': 8, 'piid': 2}, 'custom_serveice.temperature': {'siid': 8, 'piid': 5}, 'indicator_light.brightness': {'siid': 7, 'piid': 3}, 'alarm': {'siid': 6, 'piid': 1}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 2}}, max_properties: 6/12

**Comment by al-one** [comment]
Try service and find result in HA notifications:

```yaml
service: xiaomi_miot.get_properties
data:
  entity_id: fan.zhimi_ua1_xxxx
  mapping:
    - siid: 2
      piid: 1
    - siid: 2
      piid: 5
    - siid: 2
      piid: 6
    - siid: 5
      piid: 1
    - siid: 6
      piid: 1
    - siid: 7
      piid: 3
  throw: true
```
