### ISSUE TITLE
Mi Smart Led reacts to changes really slow.

### ISSUE THREAD

**Issue by woci** [al-one/hass-xiaomi-miot#1020]
### Device model / 设备型号

yeelink.light.ceiling22

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.1.7

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

After interval_seconds is set to 1 second the state change method is still slow. The trigger is called only after 1 sec, due to this, the light is in the previous state, but the wall switch/button on the screen has already been pressed. Would it be possible to go under 1 sec and give the value in milliseconds?

### Entity attributes / 实体属性

min_color_temp_kelvin: 2597
max_color_temp_kelvin: 6097
min_mireds: 164
max_mireds: 385
effect_list: Day, Night
supported_color_modes: brightness, color_temp, onoff
model: yeelink.light.ceiling22
lan_ip: 192.168.50.134
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceiling22:1
light.on: false
light.brightness: 1
light.color_temperature: 2700
light.mode: 2
light.flex_switch: true
light.off_delay_time: 0
state_updater: lan
sub_entities: light-2.off_delay_time-102
friendly_name: Mi Smart LED Ceiling Light Light
supported_features: 39
interval_seconds: 1

**Comment by al-one** [comment]
Add [automation](https://my.home-assistant.io/redirect/automations/) to update specified properties of a device:
```yaml
alias: xiaomi miot get properties
description: xiaomi miot get properties
mode: single
trigger:
  - platform: time_pattern
    seconds: /1
    id: s1
condition: []
action:
  - if:
      - condition: trigger
        id: s1
    then:
      - service: xiaomi_miot.get_properties
        data:
          entity_id: light.yeelink_ceiling22_xxxx_light
          update_entity: true
          mapping:
            - siid: 2
              piid: 1
      - delay:
          milliseconds: 500
      - service: xiaomi_miot.get_properties
        data:
          entity_id: light.yeelink_ceiling22_xxxx_light
          update_entity: true
          mapping:
            - siid: 2
              piid: 1
```
> But this is not recommended, frequent requests to the device may cause the device to go offline.
