### ISSUE TITLE
deerma.humidifier.jsq2w water shortage fault

### ISSUE THREAD

**Issue by agav85** [al-one/hass-xiaomi-miot#1021]
### Device model / 设备型号

deerma.humidifier.jsq2w

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

I have integrated deerma.humidifier.jsq2w using the device type jsq5 spec to provide proper handling of modes:

xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq2w:
      exclude_miot_services: null
      miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq5:1

But custom sensors are not available (Xiaomi Miot custom water-shortage-fault, Xiaomi Miot custom the-tank-filed):
<img width="363" alt="Settings – Home Assistant 2023-02-09 09-37-30" src="https://user-images.githubusercontent.com/64617538/217719234-13a2eb51-8770-4b3f-8224-93a7893fc933.png">

### Entity attributes / 实体属性

<img width="1351" alt="config" src="https://user-images.githubusercontent.com/64617538/217720409-0becc397-fd54-43aa-a8cf-1d6b5be0fc91.png">

**Comment by al-one** [comment]
Try this configuration:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq2w:
      exclude_miot_services: null
      binary_sensor_properties: water_shortage_fault,the_tank_filed
      miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq5:1
```

**Comment by al-one** [comment]
Does it work ?

**Comment by theodorx7** [comment]
> Does it work ?

Yes! The configuration works perfectly with the humidifier model derma.humidifier.**jsqm**
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsqm:1

Surely this configuration will also work for the **jsq2w** model


```
device_customizes:
  deerma.humidifier.jsqm:
    exclude_miot_services: null
    binary_sensor_properties: water_shortage_fault
    miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsqm:1
```




![Screenshot_1](https://user-images.githubusercontent.com/99128059/223485829-f61c2963-6945-4208-91aa-b8e2faeeb6b5.png)
![Screenshot_2](https://user-images.githubusercontent.com/99128059/223485847-146ebe81-4252-4b3b-8b25-ee23b8c5d92f.png)

**Comment by agav85** [comment]
Sorry for the delay with the response.
I see them now available and set to Off value.
But I didn't catch them being changed to On.

Am I right that the meaning of them as follows:
- water-shortage is up when we are out of water and humidifier stops.
- the-tank-filed - ? Don't know the meaning.

**Comment by theodorx7** [comment]
> Am I right that the meaning of them as follows:
> 
> * water-shortage is up when we are out of water and humidifier stops.
> * the-tank-filed - ? Don't know the meaning.

water-shortage:
tank full - off
tank empty - on

the-tank-filed:
the tank is installed on the device - off
the tank is removed from the device - on

**Comment by agav85** [comment]
Thank you. I will report back. Not sure if the status changes when the event takes place.

**Comment by kajarit** [comment]
> Hello, the solution above is almost good, but it doesn't work for the "Fan Level" and it swaps the water shortage and tank removal errors, as these are reversed for the two devices.
> 
> The following solution will work:
> 
> ```
> xiaomi_miot:
>   device_customizes:
>     deerma.humidifier.jsq2w:
>       exclude_miot_services: null
>       binary_sensor_properties: the_tank_filed,water_shortage_fault
>       miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1
> ```

With this jsq2w miot type: `miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1`
- modes are not correct
- water_shortage_fault is unavailable
- the_tank_filed is unavailable

**Comment by kajarit** [comment]
> > Does it work ?
> 
> It works for me with this: 
> Notes:
> * but these two are swapped: `water_shortage_fault` <-> `the_tank_filed`
>   if I remove the tank, `water_shortage_fault` turns on

Apart from swapped, actually the `the_tank_filed` sensor won't change to true when the device runs out of water (remember that this sensor should reflect water tank detached, but as it's swapped `water_shortage_fault` turns on when I remove the tank)

**Comment by v1k70rk4** [comment]
> Ezzel a jsq2w miot típussal: `miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1`
> 
> * A módok nem megfelelőek
> * water_shortage_fault nem érhető el
> * the_tank_filed nem érhető el

Hi,

I have this humidifier running in both of my apartments and it works perfectly with this setting. I recommend you remove the dehumidifier from Home Assistant and copy the following code into the configuration.yaml file:
```
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq2w:
      exclude_miot_services: none
      binary_sensor_properties: the_tank_filed,water_shortage_fault
      miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1
```

Then restart Home Assistant and add it to HA with the IP address and token. Wait for 30-40 seconds and then it should appear correctly.

![image](https://github.com/al-one/hass-xiaomi-miot/assets/120401244/fc77ee23-be31-4964-87be-999475342efa)
