### ISSUE TITLE
空气净化器缺少提示音开关

### ISSUE THREAD

**Issue by wxhbts** [al-one/hass-xiaomi-miot#1028]
### Device model / 设备型号

[zhimi.airpurifier.v6](https://home.miot-spec.com/s/zhimi.airpurifier.v6)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.2.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

空气净化器缺少提示音开关

### Entity attributes / 实体属性
```yaml
preset_modes: Auto, Sleep, Favorite
percentage: null
percentage_step: 33
preset_mode: Sleep
model: zhimi.airpurifier.v6
lan_ip: 10.10.10.8
mac_address: 34:CE:00:F7:E1:8B
entity_class: MiotFanEntity
home_room: 家 卧室
exclude_miot_services: button, filter_time, rfid, others
exclude_miot_properties: average_aqi_cnt, aqi_zone, sensor_state, aqi_goodh, aqi_runstate, aqi_state, motor_strong, motor_high, motor_med, motor_med_l, motor_low, motor_silent, motor_favorite, motor_set_speed
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-v6:1
aqi: 212
bright: 0
motor1_speed: 0
motor2_speed: 0
purify_volume: 320919
air_purifier.on: false
air_purifier.fan_level: 1
air_purifier.mode: 1
favorite_fan_level-8-1: 0
physical_controls_locked: false
alarm: false
indicator_light.on: false
filter.filter_life_level: 59
filter.filter_used_time: 1405
environment.relative_humidity: 53
environment.pm2_5_density: 212
environment.temperature: 13.5
state_updater: lan
sub_entities: air_purifier-2.on-1, air_purifier_favorite-8.favorite_fan_level-1, environment-3.relative_humidity-1, environment-3.pm2_5_density-2, environment-3.temperature-3, filter-4.filter_life_level-1, filter-4.filter_used_time-2, physical_controls_locked-7.physical_controls_locked-1, indicator_light-5
friendly_name: 米家空气净化器
supported_features: 9
```

### Home Assistant Logs / 系统日志

2023-02-15 07:24:56.016 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-02-15 07:25:28.857 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.chuangmi_212a01_fafa_electric_current (<class 'custom_components.xiaomi_miot.sensor.MiotSensorSubEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('current') it is using; expected one of ['A', 'mA']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-02-15 07:25:28.865 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.chuangmi_212a01_fafa_voltage (<class 'custom_components.xiaomi_miot.sensor.MiotSensorSubEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('voltage') it is using; expected one of ['mV', 'V']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by al-one** [comment]
已添加，请更新至master分支，或等待下个发布版。

**Comment by wxhbts** [comment]
经测试 此开关无效 手动在米家中打开提示音开关 状态中永久alarm: false

**Comment by al-one** [comment]
请在开发者工具中执行此服务，并检查HA左侧边栏通知中的结果。
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: fan.zhimi_v6_xxxx_entity_id
  method: get_prop
  params: [buzzer]
  throw: true
```

**Comment by wxhbts** [comment]
经检查无此服务/实体

**Comment by al-one** [comment]
实体改成你自己的呀。

**Comment by wxhbts** [comment]
当然修改了  就是没有这个实体 -。-

**Comment by al-one** [comment]
截图

**Comment by wxhbts** [comment]
![QQ截图20230221102721.png](https://s2.loli.net/2023/02/21/axrfsklbwJoqWLF.png)

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: fan.zhimi_v6_e18b_air_purifier
  method: get_prop
  params: [buzzer]
  throw: true
```
