### ISSUE TITLE
Feature Request: local mode support for yeelink.bhf_light.v11(米家智能浴霸)

### ISSUE THREAD

**Issue by manymuch** [al-one/hass-xiaomi-miot#1031]
### Device model / 设备型号

[yeelink.bhf_light.v11](https://home.miot-spec.com/s/yeelink.bhf_light.v11)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.2.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

can not control the light entity over local

|  yeelink.bhf_light.v11     |  heater | light  |
|  ---     |  ----  | ----  |
| cloud | works| works|
| local  | wokrs  | fails |

#### cloud mode
```yaml
hvac_modes:
  -hvac_modes 'off'
  - dry
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes:
  - level1
  - level2
preset_modes:
  - Defog
  - Other
  - 'off'
current_temperature: null
fan_mode: level1
hvac_action: 'off'
preset_mode: 'off'
model: yeelink.bhf_light.v11
lan_ip: [192.168.0.115](http://192.168.0.115/)
mac_address: 68:AB:BC:B2:B4:12
entity_class: MiotClimateEntity
home_room: xxx
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v11:1
ptc_bath_heater.mode: 0
ptc_bath_heater.blow: false
ptc_bath_heater.heating: false
ptc_bath_heater.ventilation: false
ptc_bath_heater.heat_level: 1
ptc_bath_heater.off_delay: false
ptc_bath_heater.off_delay_time: 0
yl_bath_heater.light_delayoff.error: '-704030013 Property is not readable'
yl_bath_heater.bath_delayoff.error: '-704030013 Property is not readable'
light.on: false
light.mode: 0
light.brightness: 100
state_updater: cloud
sub_entities:
  - Defog
  - Other
  - ptc_bath_heater-3.blow-2
  - ptc_bath_heater-3.heating-3
  - ptc_bath_heater-3.ventilation-4
  - ptc_bath_heater-3.off_delay-6
  - light-2
friendly_name: 浴霸
supported_features: 24
```
#### local mode
```yaml
hvac_modes:
  - 'off'
  - dry
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes:
  - level1
  - level2
preset_modes:
  - Defog
  - Other
  - 'off'
current_temperature: null
fan_mode: level1
hvac_action: 'off'
preset_mode: 'off'
model: yeelink.bhf_light.v11
lan_ip: [192.168.0.115](http://192.168.0.115/)
mac_address: 68:AB:BC:B2:B4:12
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v11:1
ptc_bath_heater.mode: 0
ptc_bath_heater.blow: false
ptc_bath_heater.heating: false
ptc_bath_heater.ventilation: false
ptc_bath_heater.heat_level: 1
ptc_bath_heater.off_delay: false
ptc_bath_heater.off_delay_time: 0
yl_bath_heater.light_delayoff.error: '-4003 Property/Action/Event does not exist'
yl_bath_heater.bath_delayoff.error: '-4004 Other internal errors'
light.on.error: '-4004 Other internal errors'
light.mode.error: '-4004 Other internal errors'
light.brightness.error: '-4004 Other internal errors'
state_updater: lan
sub_entities:
  - Defog
  - Other
  - ptc_bath_heater-3.blow-2
  - ptc_bath_heater-3.heating-3
  - ptc_bath_heater-3.ventilation-4
  - ptc_bath_heater-3.off_delay-6
friendly_name: 浴霸local PTC Bath Heater
supported_features: 24
```
