### ISSUE TITLE
米家立式空调

### ISSUE THREAD

**Issue by wxhbts** [al-one/hass-xiaomi-miot#1034]
### Device model / 设备型号

[xiaomi.aircondition.mc7](https://home.miot-spec.com/s/xiaomi.aircondition.mc7)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.2.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家立式空调缺少空调提示音开关和湿度传感器信息 App上看是有温度和湿度的

### Entity attributes / 实体属性
```yaml
hvac_modes: cool, heat, dry, fan_only, auto, off
min_temp: 16
max_temp: 31
target_temp_step: 0.5
fan_modes: 自动, 一档, 二档, 三档, 四档, 五档, 六档, 七档
swing_modes: off, vertical, horizontal, both
current_temperature: 11.6
temperature: 26
fan_mode: 自动
hvac_action: off
swing_mode: off
aux_heat: off
model: xiaomi.aircondition.mc7
lan_ip: 10.10.10.44
mac_address: 5C:E5:0C:3F:45:A9
entity_class: MiotClimateEntity
home_room: 家 客厅
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-mc7:1
air_conditioner.on: false
air_conditioner.mode: 2
target_temperature-2-4: 26
air_conditioner.eco: false
air_conditioner.heater: false
air_conditioner.dryer: true
air_conditioner.sleep_mode: false
enhance.fan_percent: 101
enhance.timer: 0,0,0,0
maintenance.clean: 0,0,0,0
maintenance.examine: none
indicator_light.on: false
alarm: false
environment.temperature: 11.6
fan_control.fan_level: 0
fan_control.horizontal_swing: false
fan_control.vertical_swing: false
state_updater: lan
sub_entities: environment-4.temperature-7, indicator_light-6, air_conditioner-2.eco-7, air_conditioner-2.heater-9, air_conditioner-2.dryer-10, air_conditioner-2.sleep_mode-11
friendly_name: 空调 空调
supported_features: 105
```

### Home Assistant Logs / 系统日志

无

**Comment by al-one** [comment]
请在[开发者工具](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.get_properties)中执行下面的服务，并从HA通知中获取结果。
```yaml
service: xiaomi_miot.get_properties
data:
  entity_id: climate.xiaomi_mc7_xxxx_air_conditioner
  mapping:
    - {siid: 11, piid: 1}
    - {siid: 11, piid: 2}
    - {siid: 11, piid: 3}
    - {siid: 11, piid: 4}
    - {siid: 11, piid: 5}
    - {siid: 11, piid: 6}
  throw: true
```

**Comment by al-one** [comment]
检查有无[日志](https://my.home-assistant.io/redirect/logs)

**Comment by al-one** [comment]
@wxhbts  实体ID替换成你自己的

**Comment by wxhbts** [comment]
没有犯这个低级错误 HA 还是无通知 无日志.
`service: xiaomi_miot.get_properties
data:
  entity_id: climate.xiaomi_mc7_45a9_air_conditioner
  mapping:
    - {siid: 11, piid: 1}
    - {siid: 11, piid: 2}
    - {siid: 11, piid: 3}
    - {siid: 11, piid: 4}
    - {siid: 11, piid: 5}
    - {siid: 11, piid: 6}
  throw: true`

**Comment by wxhbts** [comment]
@al-one 能否先更新提示音

**Comment by al-one** [comment]
提示音实体已添加，请再执行这个服务：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.xiaomi_mc7_45a9_air_conditioner
  method: get_properties
  params:
    - {did: miot, siid: 11, piid: 1}
    - {did: miot, siid: 11, piid: 2}
    - {did: miot, siid: 11, piid: 3}
    - {did: miot, siid: 11, piid: 4}
    - {did: miot, siid: 11, piid: 5}
    - {did: miot, siid: 11, piid: 6}
  throw: true
```

**Comment by wxhbts** [comment]
`[{'did': 'miot', 'siid': 11, 'piid': 1, 'code': -4003}, {'did': 'miot', 'siid': 11, 'piid': 2, 'code': -4003}, {'did': 'miot', 'siid': 11, 'piid': 3, 'code': -4003}, {'did': 'miot', 'siid': 11, 'piid': 4, 'code': -4003}, {'did': 'miot', 'siid': 11, 'piid': 5, 'code': -4003}, {'did': 'miot', 'siid': 11, 'piid': 6, 'code': -4003}]` 提示音以正常使用

**Comment by wxhbts** [comment]
![IMG_1398](https://user-images.githubusercontent.com/12943818/222273554-bc2c1ffc-38f5-4b24-9020-067fa2ecd607.PNG)

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.xiaomi_mc7_45a9_air_conditioner
  method: get_properties
  params:
    - {did: miot, siid: 11, piid: 2}
  throw: true
```

**Comment by wxhbts** [comment]
`[{'did': 'miot', 'siid': 11, 'piid': 2, 'code': -4003}] `

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.get_token
data:
  name: xiaomi.aircondition.mc7
```
通过上面的服务找到设备`did`，然后填入下面的服务并执行：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.xiaomi_mc7_45a9_air_conditioner
  method: get_properties
  params:
    - {did: '空调did', siid: 11, piid: 2}
  throw: true
```
