### ISSUE TITLE
请问如何设置扫地机器人水量？

### ISSUE THREAD

**Issue by chikehe** [al-one/hass-xiaomi-miot#1047]
在机器人状态中能看到：
>water_box_mode: 202

是水量设置，请问要如何通过服务进行设置？

```
fan_speed_list:
  - Silent
  - Basic
  - Strong
  - Full Speed
battery_level: 97
battery_icon: mdi:battery
fan_speed: null
model: roborock.vacuum.a11
lan_ip: 192.168.1.11
mac_address: 64:90:C1:18:F0:77
entity_class: MiotRoborockVacuumEntity
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:roborock-a11:1
vacuum.status: 2
vacuum.mode: 5
state_updater: lan
vacuum.status_desc: Sweeping
props:
  msg_ver: 2
  msg_seq: 4641
  state: 18
  battery: 97
  clean_time: 435
  clean_area: 9495000
  error_code: 0
  map_present: 1
  in_cleaning: 3
  in_returning: 0
  in_fresh_state: 0
  lab_status: 1
  water_box_status: 1
  fan_power: 105
  dnd_enabled: 0
  map_status: 3
  is_locating: 0
  lock_status: 0
  water_box_mode: 202
  distance_off: 0
  water_box_carriage_status: 1
  mop_forbidden_enable: 1
  main_brush_work_time: 244708
  side_brush_work_time: 244708
  filter_work_time: 244708
  filter_element_work_time: 890747
  sensor_dirty_time: 92
  fan_mode: 105
clean_area: 9.5
clean_time: 7.2
sub_entities:
  - props:clean_area
  - props:clean_time
  - vacuum-2.status-1
  - battery-3.battery_level-1
friendly_name: 石头 auto Robot Cleaner
supported_features: 13052

```

**Comment by al-one** [comment]
所有的石头扫拖机器人都可以使用下面的服务控制水量：
```yaml
service: vacuum.send_command
data:
  entity_id: vacuum.rockrobo_a11_xxxx
  command: set_water_box_custom_mode
  params:
    # 200 # 关闭即仅扫地
    # 201 # 轻揉擦
    - 202 # 标准擦
    # 203 # 强力擦
    # 204 # 自定义
```
