### ISSUE TITLE
fan.set_direction not working for dmaker.fan.p39

### ISSUE THREAD

**Issue by ryan13mt** [al-one/hass-xiaomi-miot#1058]
[dmaker.fan.p39](https://home.miot-spec.com/s/dmaker.fan.p39) is working with all the features apart from the set_direction. The device makes a beep when receiving this command but nothing else happens.

**Comment by al-one** [comment]
Show me debug [logs](https://my.home-assistant.io/redirect/logs) after you set direction.
```yaml
# configuration.yaml
logger:
  default: warning
  logs:
    custom_components.xiaomi_miot.fan: debug
```
