### ISSUE TITLE
Roborock G10 stopped working

### ISSUE THREAD

**Issue by abaozang** [al-one/hass-xiaomi-miot#1060]
### Device model / 设备型号

[roborock.vacuum.a29](https://home.miot-spec.com/s/roborock.vacuum.a29)

### Component version / 插件版本

0.7.7

### HA core version / HA版本

2023.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I'm not able to control roborock g10 anymore. The log says access denied. However, I am able to call roborock "find me" within this integration, while the entity status remains unknown. Functions like start cleaning, stop cleaning don't work anymore.

I've deleted the entity from home assistant, reset the vacuum and integrated it again with Xiaomi mimt but still nothing helped.

### Entity attributes / 实体属性
```yaml
fan_speed_list: Silent, Basic, Strong, Full Speed, Mop Only, Custom
battery_level: null
battery_icon: mdi:battery-unknown
fan_speed: Strong
model: roborock.vacuum.a29
lan_ip: 192.168.4.31
mac_address: B0:4A:39:28:1E:E2
entity_class: MiotRoborockVacuumEntity
home_room: 默认家庭 卧室
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:roborock-a29:1
vacuum.status: null
vacuum.fault: null
vacuum.mode: 103
vacuum.water_level: 203
vacuum.mop_mode: 300
filter.filter_life_level: 44
brush_life_level-10-2: 58
brush_cleaner.brush_life_level: 72
state_updater: lan
props: 
main_brush_work_time: 300787
side_brush_work_time: 300787
filter_work_time: 300787
filter_element_work_time: 0
sensor_dirty_time: 72689
strainer_work_times: 84
cleaning_brush_work_times: 103
fan_mode: 103
water_level: 203
mop_mode: 300

sub_entities: props:clean_area, props:clean_time, vacuum-2.status-1, vacuum-2.water_level-102, vacuum-2.mop_mode-103, filter-11.filter_life_level-1, battery-3.battery_level-1, brush_cleaner-9.brush_life_level-2, brush_cleaner-10.brush_life_level-2
miot_action_error: 1
miot_action_result: null
friendly_name: Roborock G10 Robot Cleaner
supported_features: 13052
```

### Home Assistant Logs / 系统日志

2023-03-16 20:44:11.740 WARNING (SyncWorker_6) [custom_components.xiaomi_miot.vacuum] Roborock G10(roborock.vacuum.a29): Call miot action {'did': '465737644', 'siid': 2, 'aiid': 1, 'in': []} failed: {'code': -10002, 'message': 'access denied'}
2023-03-16 20:44:12.041 ERROR (SyncWorker_19) [custom_components.xiaomi_miot.core.miio2miot] roborock.vacuum.a29: Got MiioException: {'code': -10002, 'message': 'access denied'} while get_status([])
2023-03-16 20:44:17.060 ERROR (SyncWorker_8) [custom_components.xiaomi_miot.core.miio2miot] roborock.vacuum.a29: Got MiioException: {'code': -10002, 'message': 'access denied'} while get_status([])
