### ISSUE TITLE
Toilet lid reacts too slowly the first time

### ISSUE THREAD

**Issue by christianeuropa** [al-one/hass-xiaomi-miot#1061]
### Device model / 设备型号

zhimi.toilet.sa1

### Component version / 插件版本

0.7.7

### HA core version / HA版本

2023.3.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I created an automation with the toilet lid using the xiaomi_miot.send_command service.

This is my yaml code:

```
service: xiaomi_miot.send_command
data:
  throw: false
  entity_id: binary_sensor.zhimi_sa1_d226_toilet
  method: set_cover
  params: "on"
```

This works so far, but the "first" time it always takes up to 5-10s until the command is implemented and the lid opens. If I then call the function again, it goes faster.
Can it be that the toilet seat is put to sleep and reacts more slowly the first time? And if so, could this be changed?

### Entity attributes / 实体属性

binary_sensor.zhimi_sa1_d226_toilet

### Home Assistant Logs / 系统日志

nothing
