### ISSUE TITLE
xiaomi_miot.intelligent_speaker对小米电视media_player.xiaomi_****_play_control不起作用

### ISSUE THREAD

**Issue by longavailable** [al-one/hass-xiaomi-miot#1072]
您好，在Developer Tools → Services中测试`xiaomi_miot.intelligent_speaker`，发现如下问题：

```yaml
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaomi_eaffh1_3d40_play_control  # 小爱音箱或小米电视entity id
  text: 厨房燃气热水器已打开，将在45分钟后自动关闭
  execute: false
  silent: false
  throw: false
```

当实体是小爱音箱设备时，运行正常，小爱音箱可以正常读出文本。

当实体是小米电视时，则不能正常运行，提醒的是“在你的厨房没有找到可以被控制的燃气热水器...” 或者“这个设备不能这么操作”。
