### ISSUE TITLE
customize 的內容不起效果

### ISSUE THREAD

**Issue by fishredleung** [al-one/hass-xiaomi-miot#1092]
### Device model / 设备型号

[lumi.acpartner.mcn04](https://home.miot-spec.com/s/lumi.acpartner.mcn04)

### Component version / 插件版本

0.7.7

### HA core version / HA版本

2023.4.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

已在customize.yml 添加以下內容, 並在configuration.yml 內設定了include customize.yml 但是配置內容沒有效果

```
cover.syi_sy1_2260_airer: 
 motor_reverse: true
 
climate.lumi_mcn04_c28c_air_conditioner:
  hvac_modes:
  - auto
  - cool
  - dry
  - fan_only
  - 'off'
  min_temp: 17
  max_temp: 25`

media_player.xiaomi_dso1h1_fdd2_play_control:
turn_off_screen: true   # 关闭电视/投影时发送熄屏指令
sources_via_apps: 桌面 # 将电视内的APP添加到输入源列表
```
試過在configuration 內添加:
```
xiaomi_miot: # 此行在配置文件中只能出现一次
  device_customizes:
    cover.syi_sy1_2260_airer: 
        motor_reverse: true
 
    climate.lumi_mcn04_c28c_air_conditioner:
        hvac_modes:
        - auto
        - cool
        - dry
        - fan_only
        - 'off'
        min_temp: 17
        max_temp: 25
media_player.xiaomi_dso1h1_fdd2_play_control:
turn_off_screen: true   # 关闭电视/投影时发送熄屏指令
sources_via_apps: 桌面 # 将电视内的APP添加到输入源列表
```

一樣不行

### Entity attributes / 实体属性

climate.lumi_mcn04_c28c_air_conditioner
media_player.xiaomi_dso1h1_fdd2_play_control
cover.syi_sy1_2260_airer
