### ISSUE TITLE
Help me! I've got errors for Clothes Dryer (uvfive.dryer.panda)

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#1106]
### Device model / 设备型号

[uvfive.dryer.panda](https://home.miot-spec.com/s/uvfive.dryer.panda)

### Component version / 插件版本

1.3.1

### HA core version / HA版本

2023.4.6

### Integrated mode / 集成方式

Token

### The problem / 问题详情

I've got errors : (uvfive.dryer.panda): Got MiioException while fetching the state: Unable to discover the device 192.168.xx.xxx, mapping: {'clothes_dryer.fault': {'siid': 2, 'piid': 1}, 'clothes_dryer.on': {'siid': 2, 'piid': 2}, 'clothes_dryer.status': {'siid': 2, 'piid': 3}, 'clothes_dryer.mode': {'siid': 2, 'piid': 4}, 'clothes_dryer.left_time': {'siid': 2, 'piid': 5}, 'clothes_dryer.drying_time': {'siid': 2, 'piid': 6}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'alarm': {'siid': 3, 'piid': 1}}, max_properties: 10/9

https://home.miot-spec.com/spec/uvfive.dryer.panda

### Entity attributes / 实体属性
```yaml
friendly_name: Dryer Clothes Dryer Status
supported_features: 0
model: uvfive.dryer.panda
lan_ip: 192.168.31.239
mac_address: B4:60:ED:BF:BC:2A
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:clothes-dryer:0000A06D:uvfive-panda:1
state_property: clothes_dryer.status
clothes_dryer.fault: 0
clothes_dryer.on: false
clothes_dryer.status: 0
clothes_dryer.mode: 0
clothes_dryer.left_time: 0
clothes_dryer.drying_time: 30
physical_controls_locked: true
indicator_light.on: true
alarm: true
state_updater: lan
sub_entities:
  - clothes_dryer-2.left_time-5
  - clothes_dryer-2.on-2
  - indicator_light-4.on-1
  - clothes_dryer-2.drying_time-6
  - clothes_dryer-2.mode-4
  - physical_controls_locked-5.physical_controls_locked-1
  - indicator_light-4
clothes_dryer.status_desc: IDLE
```

### Home Assistant Logs / 系统日志

(uvfive.dryer.panda): Got MiioException while fetching the state: Unable to discover the device 192.168.xx.xxx, mapping: {'clothes_dryer.fault': {'siid': 2, 'piid': 1}, 'clothes_dryer.on': {'siid': 2, 'piid': 2}, 'clothes_dryer.status': {'siid': 2, 'piid': 3}, 'clothes_dryer.mode': {'siid': 2, 'piid': 4}, 'clothes_dryer.left_time': {'siid': 2, 'piid': 5}, 'clothes_dryer.drying_time': {'siid': 2, 'piid': 6}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'alarm': {'siid': 3, 'piid': 1}}, max_properties: 10/9
