### ISSUE TITLE
Help me! Fan not propertly mapping (dmaker.fan.p45)

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#1107]
### Device model / 设备型号

[dmaker.fan.p45](https://home.miot-spec.com/s/dmaker.fan.p45)

### Component version / 插件版本

1.3.1

### HA core version / HA版本

2023.4.6

### Integrated mode / 集成方式

Token

### The problem / 问题详情

![miot](https://user-images.githubusercontent.com/44431640/235363546-c9c9d452-dfec-4bb7-99c9-cfd4096ddc82.jpg)

https://home.miot-spec.com/spec/dmaker.fan.p45

Greetings!
Please help with the fan. There are no modes and speeds. Service parameters and properties, off-delay-time are also not present.

### Entity attributes / 实体属性
```yaml
preset_modes:
  - Straight Wind
  - Natural Wind
  - Sleep
friendly_name: Вентилятор Fan
supported_features: 11
oscillating: true
percentage: 71
percentage_step: 1
preset_mode: Sleep
model: dmaker.fan.p45
lan_ip: 192.168.31.8
mac_address: 68:AB:BC:C0:4B:3C
entity_class: MiotFanEntity
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p45:1
fan.on: false
fan.fan_level: 1
fan.mode: 2
fan.horizontal_swing: true
horizontal_swing_included_angle-2-5: 90
dm_service.speed_level: 71
dm_service.natural_list: a_b_c_d_e_f_g_h
dm_service.natural_e: 81ea5b9a4e490031_360_360_360_360_360_16
dm_service.natural_f: 81ea5b9a4e490032_360_360_360_360_360_16
dm_service.natural_g: 81ea5b9a4e490033_360_360_360_360_360_16
dm_service.natural_h: 81ea5b9a4e490034_360_360_360_360_360_16
off_delay_time: 0
physical_controls_locked: true
alarm: true
indicator_light.on: true
state_updater: lan
sub_entities:
  - off_delay_time-3.off_delay_time-1
  - fan-2.horizontal_swing_included_angle-5
  - physical_controls_locked-7.physical_controls_locked-1
  - indicator_light-4
```

### Home Assistant Logs / 系统日志

2023-04-30 20:33:35.697 INFO (MainThread) [custom_components.xiaomi_miot.fan] Вентилятор(dmaker.fan.p45): Initializing miot device with mapping: {'fan.on': {'siid': 2, 'piid': 1}, 'fan.fan_level': {'siid': 2, 'piid': 2}, 'fan.mode': {'siid': 2, 'piid': 3}, 'fan.horizontal_swing': {'siid': 2, 'piid': 4}, 'horizontal_swing_included_angle-2-5': {'siid': 2, 'piid': 5}, 'dm_service.speed_level': {'siid': 8, 'piid': 1}, 'dm_service.natural_list': {'siid': 8, 'piid': 5}, 'dm_service.natural_e': {'siid': 8, 'piid': 6}, 'dm_service.natural_f': {'siid': 8, 'piid': 7}, 'dm_service.natural_g': {'siid': 8, 'piid': 8}, 'dm_service.natural_h': {'siid': 8, 'piid': 9}, 'off_delay_time': {'siid': 3, 'piid': 1}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}}
