### ISSUE TITLE
米家智能直流变频循环扇 落地式 缺少垂直摆动实体

### ISSUE THREAD

**Issue by 1105169500** [al-one/hass-xiaomi-miot#1116]
### Device model / 设备型号

[dmaker.fan.p28](https://home.miot-spec.com/s/dmaker.fan.p28)

### Component version / 插件版本

0.7.8

### HA core version / HA版本

2023.5.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![4](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/f8689659-9891-49ee-8c2d-f88fc8f52768)
如下图所示 这款风扇支持上下摇头 我在产品文档中也发现有一个 vertical-swing参数 我该如何添加它
![1](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/70d5d4c9-1c12-4dc4-bba1-0d210bfd77ea)
![2](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/6e29e60f-624c-4c83-b8c8-41fed2fc1b01)
![3](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/22928a1e-82d6-4fbb-bc8a-11f31bf5b251)

### Entity attributes / 实体属性
```yaml
preset_modes: Straight Wind, Natural Wind, Smart, Sleep
oscillating: true
percentage: 9
percentage_step: 1
preset_mode: Straight Wind
model: dmaker.fan.p28
lan_ip: 192.168.31.30
mac_address: 68:AB:BC:21:01:CC
entity_class: MiotFanEntity
home_room: 我的家庭 客厅
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p28:1
fan.on: false
fan.fan_level: 2
fan.mode: 0
fan.horizontal_swing: true
horizontal_swing_included_angle-2-5: 60
fan.vertical_swing: false
vertical_swing_included_angle-2-8: 60
dm_service.speed_level: 9
dm_service.swing_all: false
dm_service.off_to_center: true
off_delay_time: 0
environment.temperature: 24.3
environment.relative_humidity: 70
physical_controls_locked: false
alarm: true
indicator_light.on: true
state_updater: lan
sub_entities: off_delay_time-3.off_delay_time-1, fan-2.horizontal_swing_included_angle-5, environment-9.temperature-1, environment-9.relative_humidity-2, physical_controls_locked-7.physical_controls_locked-1, indicator_light-4
friendly_name: 米家空气循环风扇 Fan
supported_features: 11
```
