### ISSUE TITLE
小米新风机 c1新风开启后，设备灯光也会随之开启

### ISSUE THREAD

**Issue by Kevin6872** [al-one/hass-xiaomi-miot#1130]
### Device model / 设备型号

[zhimi.airfresh.ua1](https://home.miot-spec.com/s/zhimi.airfresh.ua1)

### Component version / 插件版本

0.7.8

### HA core version / HA版本

2023.04.1

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

设定新风机灯光为关闭状态下，打开小米新风机 c1的Air Fresh实体时，homeassistant 的Indicator Light实体也会随Air Fresh实体打开，此时会显示亮度为百分之1，但此时无论是在米家 app 的设备灯光中，还是新风机实际灯光状态都是关闭状态。此时如果手动关闭Indicator Light实体，Air Fresh实体也会关闭。如果手动关闭Air Fresh实体，Indicator Light实体有概率一起关闭，也有概率将Air Fresh实体重新打开。

### Entity attributes / 实体属性
```yaml
preset_modes: []
percentage: null
percentage_step: 33
preset_mode: null
model: zhimi.airfresh.ua1
lan_ip: 192.168.5.133
mac_address: 5C:E5:0C:DF:1C:EC
entity_class: MiotFanEntity
exclude_miot_services:
  - custom_serveice
miot_type: urn:miot-spec-v2:device:air-fresh:0000A012:zhimi-ua1:1
air_fresh.on: false
air_fresh.fault: 0
air_fresh.fan_level: 3
air_fresh.heater: false
indicator_light.brightness: 1
alarm: false
physical_controls_locked: false
filter.filter_used_time: 26487
filter.filter_life_level: 90
state_updater: lan
sub_entities:
  - air_fresh-2.heater-6
  - alarm-6.alarm-1
  - filter-4.filter_used_time-1
  - filter-4.filter_life_level-2
  - physical_controls_locked-5.physical_controls_locked-1
  - indicator_light-7
friendly_name: 新风机 Air Fresh
supported_features: 1
```

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:2497
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 04:03:09 (4 occurrences)
Last logged: 04:24:37

新风机(zhimi.airfresh.ua1): Set miot property {'did': '318856305', 'siid': 2, 'piid': 6, 'value': True} failed, result: {'did': '318856305', 'siid': 2, 'piid': 6, 'code': -4004}
新风机(zhimi.airfresh.ua1): Set miot property {'did': '318856305', 'siid': 2, 'piid': 6, 'value': False} failed, result: {'did': '318856305', 'siid': 2, 'piid': 6, 'code': -4004}
Xiaomi Miot(zhimi.airfresh.ua1): Set miot property {'did': 'prop.2.6', 'siid': 2, 'piid': 6, 'value': True} failed, result: {'did': 'prop.2.6', 'siid': 2, 'piid': 6, 'code': -4004}
Xiaomi Miot(zhimi.airfresh.ua1): Set miot property {'did': 'prop.2.6', 'siid': 2, 'piid': 6, 'value': False} failed, result: {'did': 'prop.2.6', 'siid': 2, 'piid': 6, 'code': -4004}
