### ISSUE TITLE
米家智能直流变频循环扇 落地式 无法调节风速

### ISSUE THREAD

**Issue by Edaaaaa** [al-one/hass-xiaomi-miot#1136]
### Device model / 设备型号

[dmaker.fan.p28](https://home.miot-spec.com/s/dmaker.fan.p28)

### Component version / 插件版本

0.7.8

### HA core version / HA版本

2022.7.7

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家智能直流变频循环扇 落地式 无法调节风速
调用调剂风速提示     调用服务 fan/set_percentage 失败
<img width="1920" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/9294974/87f9f087-4658-465c-b23d-17a07ca79025">

我个人分析原因如下, 小米这款风扇的 的调节风速参数应该为 fan_stepless_speed 而不是  fan_speed (实体属性)

下图是文档里的对应的参数

<img width="946" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/9294974/fa5033e8-4236-4aac-87a5-fc0c0b50f39c">

### Entity attributes / 实体属性
```yaml
preset_modes: Straight Wind, Natural Wind, Smart, Sleep
oscillating: false
percentage: 0
percentage_step: 1
preset_mode: Straight Wind
model: dmaker.fan.p28
firmware_version: 2.2.2
hardware_version: RTL8720C
fan_switch_status: true
fan_speed: 1
fan_mode: 0
fan_oscillate: false
fan_horizontal_swing_included_angle: 150
fan_vertical_swing_included_angle: 90
fan_stepless_speed: 15
indicator__switch_status: false
physical_c_physical_controls_locked: false
environmen_temperature: 27.5
environmen_relative_humidity: 65
state_value: true
friendly_name: Mijia Smart Standing Air Circulation Fan
supported_features: 11
```
