### ISSUE TITLE
How do you execute actions?

### ISSUE THREAD

**Issue by fokcuk** [al-one/hass-xiaomi-miot#114]
I have successfully added Viomi vacuum cleaner and it worked great - pulled all the options in.
But how do you execute actions? I want to do defined room cleaning and under actions I have the following:

## Actions ##
siid 4: aiid 7 Reset map: in: [] -> out: []
siid 4: aiid 10 Calibration: in: [] -> out: []
siid 4: aiid 11 Reset the usage time of the specified consumables: in: [35] -> out: []
**siid 4: aiid 13 Choose room to clean: in: [36, 37, 38] -> out: []**

The one in bold is the one I want to execute. 36, 37, 38 are defined by
siid 4: piid: 36 (clean-room-mode): (uint8, unit: none) (acc: ['write'])
{'value': 0,'description':'Global'}
{'value': 1,'description':'Along the edge'}
siid 4: piid: 37 (clean-room-oper): (uint8, unit: none) (acc: ['write'])
{'value': 0,'description':'stop'}
{'value': 1,'description':'Start'}
{'value': 2,'description':'Pause'}
siid 4: piid: 38 (clean-room-ids): (string, unit: none) (acc: ['write'])

Any assistance would be much appreciated

**Comment by al-one** [comment]
Please provide the vacuum device model/urn and entity [state attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by fokcuk** [comment]
This is what I have:
urn:miot-spec-v2:device:vacuum:0000A006:viomi-v18:1

And these are the attributes that got pulled in:

Attributes
Model
viomi.vacuum.v18
Lan IP
192.168.1.124
MAC address
5c:6b:d7:17:04:fb
Firmware version
1.6.2_2251
Hardware version
-
Entity class
MiotVacuumEntity
Miot type
urn:miot-spec-v2:device:vacuum:0000A006:viomi-v18:1
Vacuum.status
4
Vacuum.fault
0
Vacuum.wdr mode
0
Vacuum.door state
3
Vacuum.contact state
0
Vacuum.mute
2
Vacuum.sweep type
0
Vacuum.mode
0
Voice.target voice
error
Voice.cur voice
girl_en
Voice.download status
0
Voice.download progress
100
Voice.voice url.error
-4003
Voice.voice mdfive.error
-4003
Map.map type
1
Map.map ID
1
Map.map name
error
Map.lang.error
-4003
Map.arrange room ids.error
-4003
Map.target room ID.error
-4003
Map.split points.error
-4003
Map.room name.error
-4003
Map.cur cleaning path
0123
Map.map list
[["2021/06/25/6153637412/378451326_084644151.bkmap","2021/06/25/6153637412/378451326_084643762.record",1624512315,"Map1",1]]
Map.oper result
0123
Map.auto area ID
0
Point zone.target point
0,0
Point zone.zone points.error
-4003
Point zone.restrict points.error
-4003
Order.order ID.error
-4003
Order.enable.error
-4003
Order.day.error
-4003
Order.hour.error
-4003
Order.minute.error
-4003
Order.repeat.error
-4003
Order.clean way.error
-4003
Order.suction.error
-4003
Order.water.error
-4003
Order.twice clean.error
-4003
Order.mapid.error
-4003
Order.room count.error
-4003
Order.room data.error
-4003
Order.dnd enable
0
Order.dnd start hour
22
Order.dnd start minute
0
Order.dnd end hour
6
Order.dnd end minute
0
Order.dnd timezone
0
Order.timestamp
0
Order.orderdata
Viomi vacuum.repeat state
0
Viomi vacuum.remember state
1
Viomi vacuum.mop route
1
Viomi vacuum.side brush life
98
Viomi vacuum.side brush hours
178
Viomi vacuum.main brush life
99
Viomi vacuum.main brush hours
358
Viomi vacuum.hypa life
98
Viomi vacuum.hypa hours
178
Viomi vacuum.mop life
100
Viomi vacuum.mop hours
180
Viomi vacuum.direction.error
-4003
Viomi vacuum.suction grade
0
Viomi vacuum.water grade
1
Viomi vacuum.map num
0
Viomi vacuum.time zone
-28800
Viomi vacuum.clean start time
0
Viomi vacuum.clean use time
20
Viomi vacuum.clean area
0
Viomi vacuum.clean map url
00000
Viomi vacuum.clean mode
0
Viomi vacuum.clean way
0
Viomi vacuum.cur lang
en
Viomi vacuum.cur map ID
1624512315
Viomi vacuum.cur map url
curMapUrl
Viomi vacuum.last update time
0
Viomi vacuum.consumable index.error
-4003
Viomi vacuum.clean room mode.error
-4003
Viomi vacuum.clean room oper.error
-4003
Viomi vacuum.clean room ids.error
-4003
Viomi vacuum.has map
1
Viomi vacuum.has newmap
0
Viomi vacuum.dust collection
0
Battery.battery level
100
State updater
lan
Sub entities
battery-3.battery_level-1

**Comment by al-one** [comment]
No properties related to the room-ids were found.

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.your_vacuum_id
  siid: 4
  aiid: 13
  params:
    - 0 # Global
    - 1 # Start
    - xx,yy,zz # Room IDs
```

Maybe you can get room-ids via MiHome mod by [@vevsvevs](https://github.com/custom-components/ble_monitor/issues/7#issuecomment-595874419)
  1. Down apk from [СКАЧАТЬ ВЕРСИЮ 6.x.x](https://www.kapiba.ru/2017/11/mi-home.html)
  2. Create folder `/sdcard/vevs/logs/` ⚠️
  3. Find the token from `vevs/logs/miio/xxxxxx.txt`

There is a more recommended method:
> Use this component to work with [Xiaomi Cloud Map Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor) and [Lovelace Xiaomi Vacuum Map card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card).

**Comment by fokcuk** [comment]
great! Will give it a go. So in HA I can use similar format to set_attributes and get_attributes as well?

**Comment by fokcuk** [comment]
I tried to use Xiaomi Cloud map extractor but it fails to do anything

**Comment by fokcuk** [comment]
I just used the modified app - really good info.
But I still cannot get it to work. This is what I see in the logs when I send vacuum to clean room:
{"params":{"did":"378451326","siid":4,"aiid":13,"in":[0,1,"3"]}} /miotspec/action
where "did" is my device ID. 
Do I understand it correctly that it is a cloud only command? Is there a way to send it via the cloud?

**Comment by al-one** [comment]
> great! Will give it a go. So in HA I can use similar format to set_attributes and get_attributes as well?

This component will get all readable properties, so you can get the desired properties from the entity state properties.

About set_attributes:
```yaml
service: xiaomi_miot.set_property
data:
  entity_id: vacuum.your_vacuum_id
  field: vacuum.mode
  value: 3 # Strong

# Or

service: xiaomi_miot.set_miot_property
data:
  entity_id: vacuum.your_vacuum_id
  siid: 2
  piid: 19
  value: 0 # Silent
```

**Comment by al-one** [comment]
> Call miot action to Viaomi S9 Vacuum Robot Cleaner ({'did': '378451326', 'siid': 4, 'aiid': 13, 'in': [0, 1, '1']}) failed: {'code': -9999, 'message': 'user ack timeout'}

The error code `-9999` in the logs, so your device may not support the execute actions in the local area network. Customize the entity attribute `miot_cloud_action: true` can only use the cloud when execute action.

```yaml
# customize.yaml
vacuum.viaomi_s9_vacuum_robot_cleaner:
  miot_cloud_action: true
```
> **Recommended** [Customization Using The UI](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui)

If you are using token to integrate, you need to configure the account password in `configuration.yaml` before using the cloud mode:
```yaml
# configuration.yaml
xiaomi_miot:
  username: xiaomi_username
  password: xiaomi_password
  # server_country: cn # location of xiaomi cloud: cn(default), de, i2, ru, sg, us
```

If you are using an account to integrate, you do not need to configure the account password in yaml.

**Comment by fokcuk** [comment]
Finally got it to work! Thank you for your support!

**Comment by blakadder** [comment]
not related to the issue but does anyone have a clue what "wdr mode" is?

**Comment by al-one** [comment]
> not related to the issue but does anyone have a clue what "wdr mode" is?

[Wide Dynamic Range Mode](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:miot-spec-v2:property:wdr-mode:00000088)

**Comment by fhold** [comment]
I can't get my dreame D9 Max to do room cleaning. 
When i call this:

```
service: xiaomi_miot_raw.call_action
entity_id: vacuum.ayo
data:
  siid: 4
  aiid: 13
  params:
    - 0
    - 1
    - 2
```

i get the following error:
`
Aufrufen des Diensts xiaomi_miot_raw.call_action. extra keys not allowed @ data['params']. Got None`
