### ISSUE TITLE
gosund | 电小酷 CP5

### ISSUE THREAD

**Issue by wang-peak** [al-one/hass-xiaomi-miot#1140]
### Device model / 设备型号

[cuco.plug.cp5d](https://home.miot-spec.com/s/cuco.plug.cp5d)

### Component version / 插件版本

0.7.9

### HA core version / HA版本

2023.5.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

可用，不可用，来回变

### Entity attributes / 实体属性
```yaml
device_class: outlet
friendly_name: 客厅插排 总控
supported_features: 0
model: cuco.plug.cp5d
lan_ip: 192.168.31.117
mac_address: 10:B7:13:EE:BF:5D
entity_class: MiotSwitchEntity
home_room: 音无结弦的家 客厅
exclude_miot_services: indicator_light
miot_type: urn:miot-spec-v2:device:outlet:0000A002:cuco-cp5d:1
switch.on: false
custome.off_memory: true
custome.off_manager: 1
physical_controls_locked: false
state_updater: lan
sub_entities: physical_controls_locked-8.physical_controls_locked-1
```

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.switch
Source: custom_components/xiaomi_miot/__init__.py:1384
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 16:20:36 (330 occurrences)
Last logged: 18:30:36

客厅插排(cuco.plug.cp5d): Got MiioException while fetching the state: Unable to discover the device 192.168.31.117, mapping: {'switch-5.on': {'siid': 5, 'piid': 1}}, max_properties: 6/1
客厅插排(cuco.plug.cp5d): Got MiioException while fetching the state: Unable to discover the device 192.168.31.117, mapping: {'switch-3.on': {'siid': 3, 'piid': 1}}, max_properties: 6/1
客厅插排(cuco.plug.cp5d): Got MiioException while fetching the state: Unable to discover the device 192.168.31.117, mapping: {'switch-7.on': {'siid': 7, 'piid': 1}}, max_properties: 6/1
客厅插排(cuco.plug.cp5d): Got MiioException while fetching the state: Unable to discover the device 192.168.31.117, mapping: {'switch-6.on': {'siid': 6, 'piid': 1}}, max_properties: 6/1
客厅插排(cuco.plug.cp5d): Got MiioException while fetching the state: Unable to discover the device 192.168.31.117, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'custome.off_memory': {'siid': 9, 'piid': 1}, 'custome.off_manager': {'siid': 9, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}}, max_properties: 7/4

########

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:749
First occurred: 16:20:36 (203 occurrences)
Last logged: 18:30:36

Update of switch.cuco_cp5d_bf5d_switch_2 is taking over 10 seconds
Update of switch.cuco_cp5d_bf5d_switch_3 is taking over 10 seconds
Update of switch.cuco_cp5d_bf5d_usb_switch_status is taking over 10 seconds
Update of switch.cuco_cp5d_bf5d_switch is taking over 10 seconds
Update of switch.cuco_cp5d_bf5d_switch_5 is taking over 10 seconds
