### ISSUE TITLE
小米空气净化器4缺少负离子，提示音的开关，显示屏亮度的调节选项

### ISSUE THREAD

**Issue by Kevin6872** [al-one/hass-xiaomi-miot#1142]
### Device model / 设备型号

[zhimi.airp.mp4](https://home.miot-spec.com/s/zhimi.airp.mp4)

### Component version / 插件版本

0.7.9

### HA core version / HA版本

2023.04.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米空气净化器4缺少负离子，提示音的开关，显示屏亮度的调节选项

### Entity attributes / 实体属性
```yaml
preset_modes:
  - Auto
  - Sleep
  - Favorite
  - Manual
percentage: 33
percentage_step: 33
preset_mode: Sleep
model: zhimi.airp.mp4
lan_ip: 192.168.5.182
mac_address: 68:AB:BC:6A:FF:34
entity_class: MiotFanEntity
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mp4:1
air_purifier.on: true
air_purifier.fault: 0
air_purifier.mode: 1
air_purifier.fan_level: 1
air_purifier.anion: false
rfid.rfid_tag: 91:f:a3:c2:4e:50:4
rfid.rfid_factory_id: 0:0:4a:44
rfid.rfid_product_id: '0:0:31:36'
rfid.rfid_time: '0:22:9:15'
rfid.rfid_serial_num: '0:13:52:73'
aqi.purify_volume: 7856
aqi.average_aqi: 2
aqi.aqi_state: 0
aqi.aqi_updata_heartbeat: 250
custom_service.moto_speed_rpm: 448
custom_service.favorite_speed: 1900
custom_service.motor_set_speed: 450
custom_service.favorite_level: 11
custom_service.buttom_door: false
custom_service.reboot_cause: 1
custom_service.manual_level: 1
custom_service.ic_error_count: 0
screen.brightness: 0
physical_controls_locked: false
alarm: false
filter.filter_life_level: 98
filter.filter_used_time: 100
filter.filter_left_time: 141
environment.relative_humidity: 56
environment.pm2_5_density: 3
environment.temperature: 24.5
state_updater: lan
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.pm2_5_density-4
  - environment-3.temperature-7
  - filter-4.filter_life_level-1
  - filter-4.filter_used_time-3
  - filter-4.filter_left_time-4
  - physical_controls_locked-8.physical_controls_locked-1
friendly_name: 米家空气净化器 Air Purifier
supported_features: 9
```
