### ISSUE TITLE
Room cleaning with dreame-r2210:1米家免洗扫拖机器人 2 Pro

### ISSUE THREAD

**Issue by vvoolfie** [al-one/hass-xiaomi-miot#1149]
### Device model / 设备型号

dreame.vacuum.r2210

### Component version / 插件版本

0.7.9

### HA core version / HA版本

2023.5.2

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Hello! I tried to follow other issues to setup specific room cleaning in Home Assistant for my [米家免洗扫拖机器人 2 Pro](https://home.miot-spec.com/s/dreame.vacuum.r2210) without any success. Tried local and online, nothing helps

Log record from Vevs app:
```
 -> {"id":10022,"method":"action","params":{"did":"1054384524","siid":4,"aiid":1,"in":[{"piid":1,"value":18},{"piid":10,"value":"{\"selects\":[[1,1,3,2,1]]}"}]}}
2023-06-08 20:35:57 <- {"code":0,"exe_time":11,"id":10022,"message":"ok","net_cost":244,"ot_cost":1,"otlocalts":1686224157631277,"result":{"aiid":1,"code":0,"did":"1054384524","out":[],"siid":4}}
```

This one works fine:
```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_r2210_9d68_robot_cleaner_2
  siid: 4
  aiid: 1
```
This is did not work:

```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_r2210_9d68_robot_cleaner_2
  siid: 2
  aiid: 3
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[1,1,3,2,1]]}'
```

```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_r2210_9d68_robot_cleaner_2
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[1,1,3,2,1]]}'
```

```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_r2210_9d68_robot_cleaner_2
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: "{\"selects\":[[1,1,3,2,1]]}"
```

Miot action result
Online:
{'did': '1054384524', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': -704220025, 'exe_time': 0, 'withLatency': 0}

Offline:
{'did': '1054384524', 'siid': 4, 'aiid': 1, 'code': -1}

### Entity attributes / 实体属性

fan_speed_list: Silent, Basic, Strong, Full Speed
battery_level: 95
battery_icon: mdi:battery
fan_speed: Full Speed
model: dreame.vacuum.r2210
lan_ip: 192.168.11.108
mac_address: 70:C9:32:09:9D:68
entity_class: MiotVacuumEntity
home_room: Дом пользователя Илья Коридор
exclude_miot_services: consumable, annoy, remote, time
exclude_miot_properties: delete_timer, clean_info, map_view, frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-r2210:1
vacuum.status: 2
vacuum.fault: 0
vacuum.mode: 3
vacuum.dry_left_time: 0
mop.mop_life_level: 93
mop.mop_left_time: 74
clean_logs.first_clean_time: 1681553052
clean_logs.total_clean_time: 759
clean_logs.total_clean_times: 54
clean_logs.total_clean_area: 714
audio.volume: 100
audio.voice_packet_id: EN
audio.voice_change_state: {\"id\":\"\",\"state\":\"idle\",\"progress\":0}
do_not_disturb.enable: true
do_not_disturb.start_time: 22:00
do_not_disturb.end_time: 09:00
vacuum_extend.work_mode: 17
vacuum_extend.cleaning_time: 2
vacuum_extend.cleaning_area: 3
vacuum_extend.cleaning_mode: 3
vacuum_extend.mop_mode: 2
vacuum_extend.waterbox_status: 1
vacuum_extend.task_status: 0
break_point_restart-4-11: 1
vacuum_extend.carpet_press: 1
vacuum_extend.serial_number: 44044/BFACWF3PQ02897
vacuum_extend.clean_rags_tip: 0
vacuum_extend.keep_sweeper_time: 0
vacuum_extend.faults: 0
vacuum_extend.nation_matched: unknown
vacuum_extend.relocation_status: 0
filter.filter_life_level: 91
filter.filter_left_time: 137
brush_left_time-10-1: 187
brush_life_level-10-2: 93
brush_cleaner.brush_left_time: 287
brush_cleaner.brush_life_level: 95
battery.charging_state: 2
state_updater: lan
vacuum.status_desc: Idle
sub_entities: vacuum-2.status-1, filter-11.filter_life_level-1, filter-11.filter_left_time-2, battery-3.battery_level-1, battery-3.charging_state-2, brush_cleaner-9.brush_left_time-1, brush_cleaner-9.brush_life_level-2, brush_cleaner-10.brush_left_time-1, brush_cleaner-10.brush_life_level-2
miot_action_error: -1
miot_action_result: 
did: '1054384524'
siid: 4
aiid: 1
code: -1

friendly_name: kor_robot Robot Cleaner
supported_features: 13048

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:68
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 17:45:21 (60 occurrences)
Last logged: 20:47:50

Request xiaomi api: miotspec/prop/get {'params': [{'did': '392223896', 'siid': 2, 'piid': 1}, {'did': '392223896', 'siid': 2, 'piid': 2}, {'did': '392223896', 'siid': 2, 'piid': 4}, {'did': '392223896', 'siid': 2, 'piid': 5}, {'did': '392223896', 'siid': 2, 'piid': 7}, {'did': '392223896', 'siid': 4, 'piid': 1}, {'did': '392223896', 'siid': 4, 'piid': 3}, {'did': '392223896', 'siid': 4, 'piid': 4}, {'did': '392223896', 'siid': 4, 'piid': 5}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '245936043', 'siid': 2, 'piid': 2}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '358699611', 'siid': 2, 'piid': 1}, {'did': '358699611', 'siid': 2, 'piid': 2}, {'did': '358699611', 'siid': 2, 'piid': 4}, {'did': '358699611', 'siid': 2, 'piid': 5}, {'did': '358699611', 'siid': 2, 'piid': 7}, {'did': '358699611', 'siid': 4, 'piid': 1}, {'did': '358699611', 'siid': 4, 'piid': 3}, {'did': '358699611', 'siid': 4, 'piid': 4}, {'did': '358699611', 'siid': 4, 'piid': 5}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '1054384524', 'siid': 2, 'piid': 1}, {'did': '1054384524', 'siid': 2, 'piid': 2}, {'did': '1054384524', 'siid': 2, 'piid': 3}, {'did': '1054384524', 'siid': 2, 'piid': 5}, {'did': '1054384524', 'siid': 18, 'piid': 1}, {'did': '1054384524', 'siid': 18, 'piid': 2}, {'did': '1054384524', 'siid': 12, 'piid': 1}, {'did': '1054384524', 'siid': 12, 'piid': 2}, {'did': '1054384524', 'siid': 12, 'piid': 3}, {'did': '1054384524', 'siid': 12, 'piid': 4}, {'did': '1054384524', 'siid': 7, 'piid': 1}, {'did': '1054384524', 'siid': 7, 'piid': 2}, {'did': '1054384524', 'siid': 7, 'piid': 3}, {'did': '1054384524', 'siid': 5, 'piid': 1}, {'did': '1054384524', 'siid': 5, 'piid': 2}, {'did': '1054384524', 'siid': 5, 'piid': 3}, {'did': '1054384524', 'siid': 4, 'piid': 1}, {'did': '1054384524', 'siid': 4, 'piid': 2}, {'did': '1054384524', 'siid': 4, 'piid': 3}, {'did': '1054384524', 'siid': 4, 'piid': 4}, {'did': '1054384524', 'siid': 4, 'piid': 5}, {'did': '1054384524', 'siid': 4, 'piid': 6}, {'did': '1054384524', 'siid': 4, 'piid': 7}, {'did': '1054384524', 'siid': 4, 'piid': 11}, {'did': '1054384524', 'siid': 4, 'piid': 12}, {'did': '1054384524', 'siid': 4, 'piid': 14}, {'did': '1054384524', 'siid': 4, 'piid': 16}, {'did': '1054384524', 'siid': 4, 'piid': 17}, {'did': '1054384524', 'siid': 4, 'piid': 18}, {'did': '1054384524', 'siid': 4, 'piid': 19}, {'did': '1054384524', 'siid': 4, 'piid': 20}, {'did': '1054384524', 'siid': 11, 'piid': 1}, {'did': '1054384524', 'siid': 11, 'piid': 2}, {'did': '1054384524', 'siid': 10, 'piid': 1}, {'did': '1054384524', 'siid': 10, 'piid': 2}, {'did': '1054384524', 'siid': 9, 'piid': 1}, {'did': '1054384524', 'siid': 9, 'piid': 2}, {'did': '1054384524', 'siid': 3, 'piid': 1}, {'did': '1054384524', 'siid': 3, 'piid': 2}]} failed, response: None
