### ISSUE TITLE
可以将小爱同学Pro添加的 红外设备添加吗？

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#116]
我家里有一些红外设备，是通过小爱同学Pro添加的。

这些设备可以被识别并添加吗？

**Comment by al-one** [comment]
暂时不支持红外虚拟设备，但是可以通过小爱执行语音命令控制红外设备。对于有些小爱不支持的按键，可以在米家添加手动场景并开始小爱控制。

```yaml
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaoai_entity_id
  text: 打开电视
  execute: true
  silent: true
```

**Comment by weiyideai520** [comment]
好的吧，我还想成要是能添加的话，那 homekit 就可以直接显示了

**Comment by al-one** [comment]
主要是红外设备无法获取状态，想在Homekit显示可以使用template switch等。

**Comment by weiyideai520** [comment]
> 暂时不支持红外虚拟设备，但是可以通过小爱执行语音命令控制红外设备。对于有些小爱不支持的按键，可以在米家添加手动场景并开始小爱控制。
> 
> ```yaml
> service: xiaomi_miot.intelligent_speaker
> data:
>   entity_id: media_player.xiaoai_entity_id
>   text: 打开电视
>   execute: true
>   silent: true
> ```

我想请教一下
我要添加一个窗帘（cover）
目前可以直接通过小爱同学说：“打开窗帘”，“关闭窗帘”，“暂停窗帘”，进行控制。
那么我要转换成 hass 上设备（能被homekit识别），我应该怎么设置？

有没有类似的案列模板呀？我学习一下

**Comment by al-one** [comment]
```yaml
# configuration.yaml
cover:
  - platform: template
    # https://www.home-assistant.io/integrations/cover.template
    covers:
      xiaoai_ir_curtain:
        device_class: curtain
        friendly_name: 窗帘
        optimistic: true # https://www.home-assistant.io/integrations/cover.template/#optimistic
        open_cover:
          service: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaoai_entity_id
            text: 打开窗帘
            execute: true
            silent: true
        close_cover:
          service: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaoai_entity_id
            text: 关闭窗帘
            execute: true
            silent: true
        stop_cover:
          service: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaoai_entity_id
            text: 暂停窗帘
            execute: true
            silent: true
```
