### ISSUE TITLE
Miot_action_result

### ISSUE THREAD

**Issue by Drealine** [al-one/hass-xiaomi-miot#1172]
Hi,
How can I get the value from miot_action_result in automation after call service and throw result ?
I can use the attribute entity of the parent but if some automations are called at the same time, it give me some false results when read the attribute. 
Tk a lot!

**Comment by al-one** [comment]
You must know that the HA service has no return value (maybe the official is [trying to support it](https://github.com/home-assistant/core/pull/89839#issuecomment-1475524527)). So this component uses events to publish the result of the service:

```yaml
description: Example of obtaining miot action result
mode: queued
max: 10
trigger:
  - platform: state
    entity_id:
      - input_button.action
    id: miot_action
    alias: When button been pressed
  - platform: event
    event_type: xiaomi_miot.call_miot_action
    event_data:
      # filter this event
      entity_id: sensor.your_miot_entity_id
      siid: 2
      aiid: 1
    id: miot_event
    alias: When the action event is fired
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: miot_action
        sequence:
          - service: xiaomi_miot.call_action
            data:
              entity_id: sensor.your_miot_entity_id
              siid: 2
              aiid: 1
              params: []
              throw: false
      - conditions:
          - condition: trigger
            id: miot_event
        sequence:
          - service: system_log.write
            data:
              level: warning
              message: "{{ trigger.event.data }}"
```
