### ISSUE TITLE
小米电视media_player项关机按钮会让电视离线

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [al-one/hass-xiaomi-miot#1181]
### Device model / 设备型号

[xiaomi.tv.esh1](https://home.miot-spec.com/s/xiaomi.tv.esh1)

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.06.02

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

当点击media_player项的开关按钮时，会导致电视关机(off)而不是待机(idle)，令home assistant无法和电视沟通。手机app (`com.xiaomi.mitv.phone.assistant`) 也无响应。解决方法只有使用实体蓝牙遥控或者红外遥控。

值得注意的是在播放电视的时候，`media_player.xiaomi_esh1_2c95_play_control`状态是`idle`，关机后是`off`。估计应该改为`playing`和`idle`

### Entity attributes / 实体属性

播放中：
```yaml
source_list:
  - ATV
  - DTV
  - AV
  - HDMI 1
  - HDMI 2
  - HDMI 3
volume_level: 0.23
is_volume_muted: false
app_id: com.xiaomi.mitv.tvplayer
app_name: 模拟电视
source: DTV
model: xiaomi.tv.esh1
lan_ip: 192.168.1.143
mac_address: 04:7A:0B:2F:2C:95
entity_class: MitvMediaPlayerEntity
home_room: 我的家 客廳
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-esh1:2
6095_state: true
speaker_mode.is_on: false
remote_control.state_playing: false
no_disturb: false
no_disturb.enable_time_period: ''
speaker.volume: 23
speaker.mute: false
television.input_control: 2
television.sleep_mode: false
state_updater: lan
sub_entities:
  - keycodes
  - speaker_mode-8.is_on-1
  - speaker-4.volume-1
  - message_router-5.post-1
  - apps
capture: >-
  http://192.168.1.143:6095/request?action=getResource&name=screenCapture&timestamp=1687868731616&opaque=f57db3389419acb9daa455da940ffe35b6bc1f4e
capture_token: deMH97WiXvVwaWVO
app_current: 模拟电视 - com.xiaomi.mitv.tvplayer
app_page: com.xiaomi.mitv.tvplayer.dtmb.DTMBActivity
miot_action_result:
  did: '440410519'
  miid: 0
  siid: 7
  aiid: 1
  code: -704083036
  exe_time: 0
  withLatency: 0
miot_action_error: '-704083036 Device operation timeout'
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.xiaomi_esh1_2c95_play_control?token=177e5507b368761bfe87728bbbbfa1337fd8427058d8a67aa0486821824cafc0&cache=6f84d289c82e5039
friendly_name: Mi Smart TV Play Control
supported_features: 20365
```
待机中：
```yaml
source_list:
  - ATV
  - DTV
  - AV
  - HDMI 1
  - HDMI 2
  - HDMI 3
model: xiaomi.tv.esh1
lan_ip: 192.168.1.143
mac_address: 04:7A:0B:2F:2C:95
entity_class: MitvMediaPlayerEntity
home_room: 我的家 客廳
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-esh1:2
6095_state: false
speaker_mode.is_on: true
remote_control.state_playing: false
no_disturb: false
no_disturb.enable_time_period: ''
speaker.volume: 23
speaker.mute: false
television.input_control: 1
television.sleep_mode: false
state_updater: lan
sub_entities:
  - keycodes
  - speaker_mode-8.is_on-1
  - speaker-4.volume-1
  - message_router-5.post-1
  - apps
capture: >-
  http://192.168.1.143:6095/request?action=getResource&name=screenCapture&timestamp=1687868822280&opaque=640f42520a5ff277032bc0a0190fd058d72619a8
capture_token: MRkPD61JwO5qTWQB
app_current: 模拟电视 - com.xiaomi.mitv.tvplayer
app_page: com.xiaomi.mitv.tvplayer.dtmb.DTMBActivity
miot_action_result:
  did: '440410519'
  miid: 0
  siid: 7
  aiid: 1
  code: -704083036
  exe_time: 0
  withLatency: 0
miot_action_error: '-704083036 Device operation timeout'
device_class: tv
friendly_name: Mi Smart TV Play Control
supported_features: 20365
```

### Home Assistant Logs / 系统日志

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.media_player
Source: custom_components/xiaomi_miot/__init__.py:1384
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 8:11:41 PM (2 occurrences)
Last logged: 8:29:40 PM

Mi Smart TV(xiaomi.tv.esh1): Got MiioException while fetching the state: Unable to discover the device 192.168.1.143, mapping: {'speaker_mode.is_on': {'siid': 8, 'piid': 1}, 'remote_control.state_playing': {'siid': 7, 'piid': 1}, 'no_disturb': {'siid': 9, 'piid': 1}, 'no_disturb.enable_time_period': {'siid': 9, 'piid': 2}, 'speaker.volume': {'siid': 4, 'piid': 1}, 'speaker.mute': {'siid': 4, 'piid': 2}, 'television.input_control': {'siid': 2, 'piid': 1}, 'television.sleep_mode': {'siid': 2, 'piid': 2}}, max_properties: 9/8
```

**Comment by SodaWithoutSparkles** [comment]
暂时解决方法：加一个按钮处理`speaker_mode.is_on`状态
```
- platform: template
  switches:
    tv_is_on:
      friendly_name: TV
      unique_id: 358c10f4-16b5-4cd8-91d3-4c92e5777dee
      value_template: "{{ not state_attr('media_player.xiaomi_esh1_2c95_play_control','speaker_mode.is_on') }}"
      turn_on:
        service: switch.turn_off
        target:
          entity_id: switch.xiaomi_esh1_2c95_is_on
      turn_off:
        service: switch.turn_on
        target:
          entity_id: switch.xiaomi_esh1_2c95_is_on
      icon_template: >-
        {% if not state_attr('media_player.xiaomi_esh1_2c95_play_control','speaker_mode.is_on') %}
          mdi:television
        {% else %}
          mdi:television-off
        {% endif %}

```
