### ISSUE TITLE
米家智能鱼缸 缺少水泵挡位实体 提示音开关实体

### ISSUE THREAD

**Issue by 1105169500** [al-one/hass-xiaomi-miot#1186]
### Device model / 设备型号

[hfjh.fishbowl.m100](https://home.miot-spec.com/s/hfjh.fishbowl.m100)

### Component version / 插件版本

	0.7.10

### HA core version / HA版本

2023.6.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![水泵](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/d9743ef2-20d0-492a-a506-85345fcdf063)
![提示音](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/6d2b8132-22b5-438a-8466-bb2d665815ec)
您好，上面2张图为米家智能鱼缸的插件文档，其中米家鱼缸的水泵有3个等级 1 2 3档，还有提示音的开关，希望能加入插件中。
另外还有一个小问题如下图  water-pump参数为关闭水泵开关 但在插件中关闭，鱼缸并不会关闭水泵 插件又自动跳回开启
![123](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/e6399e0e-1b9b-45cb-b07d-4d1b254478f3)

### Entity attributes / 实体属性
```yaml
device_class: switch
icon: mdi:fishbowl
friendly_name: 米家智能鱼缸 Fish Tank
supported_features: 0
model: hfjh.fishbowl.m100
lan_ip: 192.168.31.120
mac_address: 68:AB:BC:E6:4A:52
entity_class: MiotSwitchEntity
home_room: 我的家庭 客厅
miot_type: urn:miot-spec-v2:device:fish-tank:0000A0A2:hfjh-m100:1
fish_tank.on: true
fish_tank.water_pump: true
fish_tank.pump_flux: 2
fish_tank.temperature: 30
fish_tank.water_pump_status: 2
exception_card.trigger_status: 0
no_reminder_status-12-3: 0
temperature_warn_on-9-3: true
temperature_warn_min-9-4: 25
temperature_warn_max-9-5: 30
no_disturb_custom.repeat_cycle: 127
light_status_on-8-4: true
light_status_mode-8-5: 0
light_status_bright-8-6: 1
light_status_flow-8-7: 0
pump_status_on-8-8: true
pump_status_flux-8-9: 0
no_disturb_working-8-10: false
feeder_custom.feeder_status: 0
feeder_custom.today_feeded_num: 3
feeder_custom.feed_protect_on: true
feeder_custom.protect_status: 0
pump_custom.temperature_status: 1
pump_custom.pump_current: value
light_custom.light_mode_list: 16724753-hfjh_nmg-4,14279679-hfjh_xlg-5,16777215-hfjh_white-3,7,0,1,2
light_custom.light_edit_on: false
light_water_use_time-4-4: 0
light_custom.light_edit_color: 255
light_custom.light_edit_bright: 100
physical_controls_locked: true
light.on: false
light.mode: 3
light.brightness: 16
light.flow_speed_level: 2
indicator_light.on: true
alarm: false
filter-11.filter_life_level: 49
filter-11.filter_left_time: 2131
filter.filter_life_level: 99
filter.filter_left_time: 2157
no_disturb: false
no_disturb.enable_time_period: 09:00:00-21:00:00
state_updater: lan
sub_entities: fish_tank-2.feeding_measure-5, fish_tank-2.temperature-4, fish_tank-2.water_pump-2, filter-10.filter_life_level-1, filter-10.filter_left_time-2, filter-11.filter_life_level-1, filter-11.filter_left_time-2, physical_controls_locked-16.physical_controls_locked-1, indicator_light-14
```
