### ISSUE TITLE
米家MX射频控制器接入异常

### ISSUE THREAD

**Issue by tgai** [al-one/hass-xiaomi-miot#1197]
### Device model / 设备型号

[wfxx.motor.ycmkq](https://home.miot-spec.com/s/wfxx.motor.ycmkq)

### Component version / 插件版本

0.7.10

### HA core version / HA版本

core-2023.7.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

这个是个MX射频控制器，用在米家中是支持控制的，集成ha后，一个是缺少遥控模式和学习模式的控制，其二是开始 关闭 暂停都无法使用

### Entity attributes / 实体属性
```yaml
model: wfxx.motor.ycmkq
lan_ip: 192.168.3.74
mac_address: 64:9E:31:36:FA:A9
entity_class: MiotCoverEntity
home_room: 浮生若梦的家 卧室
miot_type: urn:miot-spec-v2:device:motor-controller:0000A01D:wfxx-ycmkq:1
motor_controller.fault: 0
wfxx.key_set_flag: 0
wfxx.keyone_sta: 2
wfxx.keytwo_sta: 2
wfxx.keythree_sta: 1
wfxx.keyfour_sta: 2
wfxx.reset: false
state_updater: cloud
device_class: shade
friendly_name: 幕布
supported_features: 11
```

### Home Assistant Logs / 系统日志

2023-07-09 01:37:47.969 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-09 01:38:47.589 WARNING (MainThread) [custom_components.xiaomi_miot] None device in xiaomi cloud: 328361222@qq.com
2023-07-09 01:38:47.606 WARNING (MainThread) [custom_components.xiaomi_miot] None device in xiaomi cloud: 328361222@qq.com
2023-07-09 01:39:20.717 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.zhimi_ua2_605c_pm10_density (<class 'custom_components.xiaomi_miot.sensor.MiotSensorSubEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('pm10') it is using; expected one of ['µg/m³']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-07-09 18:01:29.554 ERROR (SyncWorker_0) [custom_components.xiaomi_miot.cover] Motor control value is invalid for MX RF controller Motor Controller
2023-07-09 18:01:42.105 ERROR (SyncWorker_0) [custom_components.xiaomi_miot.cover] Motor control value is invalid for MX RF controller Motor Controller
2023-07-09 18:05:46.406 ERROR (SyncWorker_5) [custom_components.xiaomi_miot.cover] Motor control value is invalid for MX RF controller Motor Controller
2023-07-09 18:06:48.421 ERROR (SyncWorker_2) [custom_components.xiaomi_miot.cover] Motor control value is invalid for MX RF controller Motor Controller

**Comment by hugeng1979** [comment]
我也一样的问题，应该是我们买了同一款USB的射频遥控器。我在米家APP上是可以正常使用的，就是集成的HA后，看着是集成进来了，但是在HA点上升、停止、下降没有用。

设备信息
wfxx.motor.ycmkq
制造商：wfxx
固件：2.0.3_0002@RTL8720C

**Comment by zhwryan** [comment]
我也遇到同样的问题，有人可以解决吗，感恩

**Comment by stevehsinwang** [comment]
我也遇到同样的问题，默认的操作没有对应到按键上

**Comment by mivansaka** [comment]
请问有人解决了吗？

**Comment by dotecxy** [comment]
同问一下这种升降指令发什么

**Comment by al-one** [comment]
我已经为该设备添加了一些实体，但是我不确定它们的作用。请自己尝试，有可能会导致配对消失。
尝试master分支。
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by dotecxy** [comment]
> 我已经为该设备添加了一些实体，但是我不确定它们的作用。请自己尝试，有可能会导致配对消失。 尝试master分支。
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

我已经获取到了米家mx射频设备的数据了
siid=3,value=2
开门 piid=2
关门 piid=3
锁 piid=4
暂停 piid=5

**Comment by al-one** [comment]
```yaml
action: select.select_option
data:
  entity_id: select.wfxx_ycmkq_xxxx_keyone_sta
  option: Set
```
