### ISSUE TITLE
Aqara人体传感器永远是触发状态

### ISSUE THREAD

**Issue by firesunCN** [al-one/hass-xiaomi-miot#120]
可以正确识别到aqara和小米的人体传感器，但是状态永远是触发，实际上边上没人
通过小米多功能网关连接的Aqara人体传感器

型号：
lumi.sensor_motion.aq2
lumi.sensor_motion.v2

**Comment by al-one** [comment]
暂不支持绿米的人体传感器。

**Comment by al-one** [comment]
新的提交：https://github.com/al-one/hass-xiaomi-miot/commit/06388138d0c3c12770dbe6c4fe48b02c867caa72 已支持绿米人体传感器，请更新后体验。
另外支持两个自定义属性：
```yaml
binary_sensor.lumi_motion_sensor_entity_id:
  interval_seconds: 15 # 刷新状态的频率(秒)
  motion_timeout: 60  # 检测到移动后的有效时长(秒)，即读取到的最后移动时间后60秒清除触发状态
```
