### ISSUE TITLE
fan.set_percentage 0 会执行关闭然后立刻启动

### ISSUE THREAD

**Issue by Necroneco** [al-one/hass-xiaomi-miot#1212]
### Device model / 设备型号

[dmaker.fan.p8](https://home.miot-spec.com/s/dmaker.fan.p8) （很多同类风扇都有这个问题）

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.7.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![image](https://github.com/al-one/hass-xiaomi-miot/assets/6160048/e2c37987-7500-4e3e-9c9c-359ed594eb7b)

在 HA 2023.4 新版的 Fan 界面上点击关闭，会执行关闭然后立刻启动

观察日志发现，似乎内部调用的是 `fan.set_percentage(0)`

看 `FanEntity` 的代码，它在 `percentage == 0` 的时候先执行了 `async_turn_off` 然后再调用了组件的 `set_percentage`

而 `MiotFanEntity` 的 `set_percentage` 会走到 `turn_on` 的开头，判断 `if not self.is_on:` 就先打开电源...

```python
class FanEntity(ToggleEntity):
    ...
    async def async_set_percentage(self, percentage: int) -> None:
        """Set the speed of the fan, as a percentage."""
        if percentage == 0:
            await self.async_turn_off()  # <-- 1: 关闭
        await self.hass.async_add_executor_job(self.set_percentage, percentage)  # <-- 2: percentage is 0
    ...
```
https://github.com/home-assistant/core/blob/3b501fd2d7495b0336a5e254dc0c508daec189a1/homeassistant/components/fan/__init__.py#L199C1-L203C80

```python
class MiotFanEntity(MiotToggleEntity, FanEntity):
    ...
    def set_percentage(self, percentage: int):
        return self.turn_on(percentage=percentage)  # <-- 3: percentage is 0
    ...
    def turn_on(self, speed=None, percentage=None, preset_mode=None, **kwargs):
        ret = False
        if not self.is_on:
            ret = self.set_property(self._prop_power, True)  # <-- 4: 打开
        if self._prop_percentage:
            ...
        elif self._prop_speed:
            ...
        ...
    ...
```
https://github.com/al-one/hass-xiaomi-miot/blob/15a626678ef64624b557f83b88bdbf8d7880798d/custom_components/xiaomi_miot/fan.py#L143C1-L176C19

### Entity attributes / 实体属性
```yaml
preset_modes:
  - Straight Wind
  - Sleep
oscillating: true
percentage: 33
percentage_step: 33
preset_mode: Straight Wind
model: dmaker.fan.p8
lan_ip: 
mac_address: 
entity_class: MiotFanEntity
home_room: 
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p8:2
fan.on: true
fan.fan_level: 1
fan.horizontal_swing: true
fan.mode: 0
fan.off_delay_time: 0
fan.alarm: false
fan.brightness: true
indicator_light.on: true
alarm: false
physical_controls_locked: false
state_updater: lan
sub_entities:
  - fan-2.horizontal_swing-3
  - fan-2.alarm-11
  - alarm-4.alarm-1
  - fan-2.off_delay_time-10
  - physical_controls_locked-3.physical_controls_locked-1
  - indicator_light-5
friendly_name: 米家落地扇 Fan
supported_features: 11
```

### Home Assistant Logs / 系统日志

米家落地扇 Fan 已开启 由服务触发 fan.set_percentage
22:25:56 - 19分钟前 - 
米家落地扇 Fan 已关闭 由服务触发 fan.set_percentage
22:25:56 - 20分钟前 -
