### ISSUE TITLE
Xiaomi Mijia Pipi

### ISSUE THREAD

**Issue by DivanX10** [al-one/hass-xiaomi-miot#1228]
### Device model / 设备型号

[dreame.light.r2229](https://home.miot-spec.com/s/dreame.light.r2229)

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.7.3

### Integrated mode / 集成方式

Token

### The problem / 问题详情

[Parameters of the lamp dream.light.r2229](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:light:0000A001:dreame-r2229:1)

There are some parameters in the lamp settings, but there is no mood selection, no enable/disable interactive gestures. How do I add this?

![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/aefedad8-9fee-4015-a56b-6b5bbe225517)
![1690416122144](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/80bb0aea-4c13-49c6-932e-a911d6a318c9)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/818e1aea-014c-4abf-b792-a1077c695061)

### Entity attributes / 实体属性
```yaml
min_color_temp_kelvin: 2702
max_color_temp_kelvin: 5714
min_mireds: 175
max_mireds: 370
effect_list:
  - Night Light
  - Warmth
  - Computer
  - Office
  - Entertainment
  - None
supported_color_modes:
  - brightness
  - color_temp
  - onoff
color_mode: color_temp
brightness: 76
color_temp_kelvin: 4000
color_temp: 250
hs_color:
  - 26.812
  - 34.87
rgb_color:
  - 255
  - 205
  - 166
xy_color:
  - 0.421
  - 0.364
effect: None
model: dreame.light.r2229
lan_ip: 192.168.1.57
mac_address: CC:B5:D1:EC:CA:56
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:light:0000A001:dreame-r2229:1
light.on: true
light.mode: 0
light.brightness: 30
light.color_temperature: 4000
robot_related.faluts: ''
robot_related.lighting_switch: 0
robot_related.work_mode: 0
interaction.interaction_switch: 1
interaction.interaction_gesture: 0
interaction.flow_switch: 1
timer.timer_zone: Europe/Moscow
timer.timer_info: ''
timer.timer_delay_switch: 0
timer.timer_delay_value: 15
timer.delay_left_value: 0
light_motion.light_motion_list: >-
  0-1-6auY5YW0;1-1-5oOK6K62;2-1-5Y6M5oG2;3-1-5oSk5oCS;4-1-5oKy5Lyk;5-1-5oGQ5oOn;6-1-552h6KeJ5Lit;7-1-5omT5oub5ZG8;8-1-6KOF5q27;9-1-54Gv5YWJ6IieMQ==;10-1-54Gv5YWJ6IieMg==;11-1-55yo55y8;12-1-54K55aS0;13-1-5pGH5aS0
character.mood: 3
character.birthday: 2023-7-26
character.personality: 2
state_updater: lan
friendly_name: Mijia PIPI Desk Lamp Light
supported_features: 4
```

### Home Assistant Logs / 系统日志

2023-07-27 02:51:27.859 DEBUG (MainThread) [custom_components.xiaomi_miot.light] Mijia PIPI Desk Lamp(dreame.light.r2229): Got new state: {'light.on': True, 'light.mode': 0, 'light.brightness': 1, 'light.color_temperature': 4000, 'robot_related.faluts': '', 'robot_related.lighting_switch': 1, 'robot_related.work_mode': 0, 'interaction.interaction_switch': 1, 'interaction.interaction_gesture': 0, 'interaction.flow_switch': 1, 'timer.timer_zone': 'Europe/Moscow', 'timer.timer_info': '', 'timer.timer_delay_switch': 0, 'timer.timer_delay_value': 15, 'timer.delay_left_value': 0, 'light_motion.light_motion_list': '0-1-6auY5YW0;1-1-5oOK6K62;2-1-5Y6M5oG2;3-1-5oSk5oCS;4-1-5oKy5Lyk;5-1-5oGQ5oOn;6-1-552h6KeJ5Lit;7-1-5omT5oub5ZG8;8-1-6KOF5q27;9-1-54Gv5YWJ6IieMQ==;10-1-54Gv5YWJ6IieMg==;11-1-55yo55y8;12-1-54K55aS0;13-1-5pGH5aS0', 'character.mood': 6, 'character.birthday': '2023-7-26', 'character.personality': 2, 'state_updater': 'lan'}

2023-07-27 02:51:57.983 DEBUG (MainThread) [custom_components.xiaomi_miot.light] Mijia PIPI Desk Lamp(dreame.light.r2229): Got new state: {'light.on': True, 'light.mode': 0, 'light.brightness': 1, 'light.color_temperature': 4000, 'robot_related.faluts': '', 'robot_related.lighting_switch': 1, 'robot_related.work_mode': 0, 'interaction.interaction_switch': 1, 'interaction.interaction_gesture': 0, 'interaction.flow_switch': 1, 'timer.timer_zone': 'Europe/Moscow', 'timer.timer_info': '', 'timer.timer_delay_switch': 0, 'timer.timer_delay_value': 15, 'timer.delay_left_value': 0, 'light_motion.light_motion_list': '0-1-6auY5YW0;1-1-5oOK6K62;2-1-5Y6M5oG2;3-1-5oSk5oCS;4-1-5oKy5Lyk;5-1-5oGQ5oOn;6-1-552h6KeJ5Lit;7-1-5omT5oub5ZG8;8-1-6KOF5q27;9-1-54Gv5YWJ6IieMQ==;10-1-54Gv5YWJ6IieMg==;11-1-55yo55y8;12-1-54K55aS0;13-1-5pGH5aS0', 'character.mood': 3, 'character.birthday': '2023-7-26', 'character.personality': 2, 'state_updater': 'lan'}

2023-07-27 02:52:29.160 DEBUG (MainThread) [custom_components.xiaomi_miot.light] Mijia PIPI Desk Lamp(dreame.light.r2229): Got new state: {'light.on': True, 'light.mode': 0, 'light.brightness': 1, 'light.color_temperature': 4000, 'robot_related.faluts': '', 'robot_related.lighting_switch': 1, 'robot_related.work_mode': 0, 'interaction.interaction_switch': 1, 'interaction.interaction_gesture': 0, 'interaction.flow_switch': 1, 'timer.timer_zone': 'Europe/Moscow', 'timer.timer_info': '', 'timer.timer_delay_switch': 0, 'timer.timer_delay_value': 15, 'timer.delay_left_value': 0, 'light_motion.light_motion_list': '0-1-6auY5YW0;1-1-5oOK6K62;2-1-5Y6M5oG2;3-1-5oSk5oCS;4-1-5oKy5Lyk;5-1-5oGQ5oOn;6-1-552h6KeJ5Lit;7-1-5omT5oub5ZG8;8-1-6KOF5q27;9-1-54Gv5YWJ6IieMQ==;10-1-54Gv5YWJ6IieMg==;11-1-55yo55y8;12-1-54K55aS0;13-1-5pGH5aS0', 'character.mood': 3, 'character.birthday': '2023-7-26', 'character.personality': 2, 'state_updater': 'lan'}

**Comment by al-one** [comment]
Try master branch.

**Comment by DivanX10** [comment]
Super, it works

![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/e61a5f14-1f9c-43c5-989e-a122885a2520)

Can I also add launching templates in the mood? That's how I can run prepared mood templates, as well as run my own

```
service: xiaomi_miot.call_action
data:
  entity_id: light.dreame_r2229_ca56_light
  siid: 5
  aiid: 2
  params: 15
```

![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/b6a13a48-8ef9-4321-b094-bad42f72cd61)

**Comment by DivanX10** [comment]
An error was made in the lamp control.  In MiHome there is a button to turn on and off the lamp (look at the second screenshot and the number 1) and there is a button to turn on the light (look at the second screenshot and the number 2). In the Home Assistant, turning the lamp on and off does not work correctly. If you turn off the lamp, the lamp turns off completely and stops responding to gestures and touches. If you turn on the light, the lamp turns on and begins to respond to gestures and touches. The robot-related lighting_switch switch turns the light on and off and does not control the brightness and temperature of the light. It should be the other way around.  The robot-related lighting_switch switch should turn off the lamp completely and turn on the lamp, and the light button turns on and off the light, and also adjusts the brightness and temperature of the light, but when the light is turned off, it does not turn off the lamp completely, but only the lamp

![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/9cce9a13-130e-425b-8428-8d8c823e3232)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/51e90b94-4ca7-480b-ba0a-31ecd120ffb2)

**Comment by Nikita7x** [comment]
@DivanX10 have you managed to custom home assistant integration to the lamp gestures?

Currently the lamp can recognise gestures with your hand "one ☝🏻", "two ✌️", "three" and execute automation in Mi Home. I really want to know is it possible to make it run home assistant automation? I'm currently using this plugin and I seems like it doesn't change anything in lamp's parameters when I execute these gestures.

**Comment by DivanX10** [comment]
> @DivanX10 have you managed to custom home assistant integration to the lamp gestures?
> 
> Currently the lamp can recognise gestures with your hand "one ☝🏻", "two ✌️", "three" and execute automation in Mi Home. I really want to know is it possible to make it run home assistant automation? I'm currently using this plugin and I seems like it doesn't change anything in lamp's parameters when I execute these gestures.

I can try it if you tell me how to run it.  I do not see in this parameter table what you are asking me about or I do not know what to look at

**Comment by Nikita7x** [comment]
@DivanX10 
> I can try it if you tell me how to run it.  I do not see in this parameter table what you are asking me about or I do not know what to look at

To find a gesture recognition feature, open Mi Home -> Choose lamp -> Press "..." and there select "Automation". Tap the "+" button and select this lamp, there you will see that it can trigger automation with three different gestures. 

![image](https://github.com/al-one/hass-xiaomi-miot/assets/77989743/758390d1-dcf0-4ffb-9f84-402a4c873232)

**Comment by DivanX10** [comment]
> @DivanX10
> 
> > I can try it if you tell me how to run it.  I do not see in this parameter table what you are asking me about or I do not know what to look at
> 
> To find a gesture recognition feature, open Mi Home -> Choose lamp -> Press "..." and there select "Automation". Tap the "+" button and select this lamp, there you will see that it can trigger automation with three different gestures.
> 
> ![image](https://user-images.githubusercontent.com/77989743/273824932-758390d1-dcf0-4ffb-9f84-402a4c873232.png)

I know that. That's not what I asked. Look at this [table](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:light:0000A001:dreame-r2229:1) with parameters. I don’t see here that it is possible to launch 3 variants of gestures. But there is a list of gestures that can be launched
![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/4d6bf270-23fb-4db9-b61c-055886ece980)



For example, to launch a character we use these parameters
![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/c8939f35-026f-4ea7-9337-cf095ecb5048)


Mood greet
```
service: xiaomi_miot.call_action
data:
  entity_id: light.dreame_r2229_ca56_light
  siid: 5
  aiid: 2
  params: 7
```


triumphant mood
```
service: xiaomi_miot.call_action
data:
  entity_id: light.dreame_r2229_ca56_light
  siid: 5
  aiid: 2
  params: 7
```

That's why I ask. Do you know how to launch the gestures you need based on the table with parameters? I don't see the examples I need to do what you're asking me to do.

![image](https://github.com/al-one/hass-xiaomi-miot/assets/64090632/39cf0778-d15d-4c7c-8f91-68b19eb3309e)
