### ISSUE TITLE
VRF网关下设备无法本地控制

### ISSUE THREAD

**Issue by iapYang** [al-one/hass-xiaomi-miot#1237]
### Device model / 设备型号

[090615.aircondition.ktf](https://home.miot-spec.com/s/090615.aircondition.ktf)

### Component version / 插件版本

0.7.10

### HA core version / HA版本

20230503.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

尝试断网后，无法在本地控制VRF设备
ha报错提示
_调用服务 climate/set_hvac_mode 失败_

### Entity attributes / 实体属性
```yaml
hvac_modes:
  - cool
  - heat
  - dry
  - fan_only
  - auto
  - 'off'
min_temp: 16
max_temp: 32
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
current_temperature: null
temperature: 22
fan_mode: auto
hvac_action: 'off'
model: 090615.aircondition.ktf
lan_ip: ''
mac_address: 
entity_class: MiotClimateEntity
home_room: 
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:090615-ktf:1
air_conditioner.on: false
air_conditioner.mode: 0
air_conditioner.fault: 0
target_temperature-2-4: 22
setmode.roomtemp: 26
fan_control.fan_level: 0
state_updater: cloud
sub_entities:
  - air_conditioner-2.on-1
friendly_name:
supported_features: 9
```
