### ISSUE TITLE
set_miot_property converting string into array for the value field

### ISSUE THREAD

**Issue by bfg100k** [al-one/hass-xiaomi-miot#1246]
In my script I am making the service call using the value of a variable input_text.viomi_s9_script_helper that contains x,y coordinates as a string. When it runs, the value is getting converted into an array instead. How can I force it to use it as a string instead?

```
 service: xiaomi_miot.set_miot_property
 data:
   entity_id: vacuum.viomi_v18_155a_robot_cleaner
   siid: 6
   piid: 1
   value: '{{ states(''input_text.viomi_s9_script_helper'')|string }}'
```

Log shows

```
2023-08-08 12:28:01.238 WARNING (SyncWorker_4) [custom_components.xiaomi_miot.vacuum] Viomi S9(viomi.vacuum.v18): Set miot property {'did': '378455517', 'siid': 6, 'piid': 1, 'value': (0.596, -0.431)} failed: No response from the device
```

When I hardcode the entry for value, it works as expected.
```
 service: xiaomi_miot.set_miot_property
 data:
   entity_id: vacuum.viomi_v18_155a_robot_cleaner
   siid: 6
   piid: 1
   value: 0.676,-0.217
```

Log shows

```
2023-08-08 12:19:50.069 DEBUG (SyncWorker_14) [custom_components.xiaomi_miot.vacuum] Viomi S9(viomi.vacuum.v18): Set miot property {'did': '378455517', 'siid': 6, 'piid': 1, 'value': '0.676,-0.217'}, result: {'code': 0, 'did': '378455517', 'piid': 1, 'siid': 6}
```

**Comment by bfg100k** [comment]
So I've been trying to resolve this issue by using various workarounds found on the net regarding how to force HA to use string instead of other types but had no success. I did a little digging into the code of this component and found that if I make the following change in the file ```__init__.py```, it works! @al-one, any reason why value has to be ```cv.match_all``` instead of ```cv.string```?

```
    'set_miot_property': {
        'method': 'async_set_miot_property',
        'schema': XIAOMI_MIIO_SERVICE_SCHEMA.extend(
            {
                vol.Optional('did'): cv.string,
                vol.Required('siid'): int,
                vol.Required('piid'): int,
                vol.Required('value'): cv.match_all, <-- change to cv.string
                vol.Optional('throw', default=False): cv.boolean,
            },
        ),
    },
```

**Comment by al-one** [comment]
Try:
```yaml
 service: xiaomi_miot.set_miot_property
 data: |-
    {{ {
      'entity_id': 'vacuum.viomi_v18_155a_robot_cleaner',
      'siid': 6,
      'piid': 1,
      'value': states('input_text.viomi_s9_script_helper')|string,
    } }}
```
