### ISSUE TITLE
Add demist option for yeelink.mirror.bm1

### ISSUE THREAD

**Issue by hACKrus** [al-one/hass-xiaomi-miot#1250]
### Device model / 设备型号

[yeelink.mirror.bm1](https://home.miot-spec.com/s/yeelink.mirror.bm1)

### Component version / 插件版本

	0.7.11

### HA core version / HA版本

2023.8.1

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

Please add Demist switch
![Screenshot_20230811-145012_Mi Home](https://github.com/al-one/hass-xiaomi-miot/assets/12397874/49335a3f-c004-477f-b5ed-b9a65afeb7eb)

### Entity attributes / 实体属性
```yaml
min_color_temp_kelvin: 2702
max_color_temp_kelvin: 6097
min_mireds: 164
max_mireds: 370
supported_color_modes:
  - brightness
  - color_temp
  - onoff
model: yeelink.mirror.bm1
lan_ip: 192.168.2.112
mac_address: 5C:E5:0C:35:3D:86
entity_class: MiotLightEntity
home_room: H0m3 Ванная
miot_type: urn:miot-spec-v2:device:mirror:0000A063:yeelink-bm1:1
light.on: false
light.brightness: 1
light.color_temperature: 2700
state_updater: cloud
friendly_name: Зеркало Light
supported_features: 32
```
