### ISSUE TITLE
What am i doing wrong with my xiaomi vacuum b106eu

### ISSUE THREAD

**Issue by rolfberkenbosch** [al-one/hass-xiaomi-miot#1255]
Hi there,

I have a problem to select a specific room to vacuum. I have the following vacuum: https://home.miot-spec.com/spec/xiaomi.vacuum.b106eu

I have tried the following, first i need to have the 
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_b106eu_26ba_robot_cleaner
  siid: 10 # map
  aiid: 1 # get-map-list
  throw: true
```

The response is:
```yaml
out:
  - piid: 4
    value: "[{\"name\":\"Benedenn\",\"id\":1691863236,\"cur\":true}]"
code: 0
```

Next i need the room id's, so i tried the following:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_b106eu_26ba_robot_cleaner
  siid: 10 # map
  aiid: 13 # get-map-room-list
  params:
    - pidd: 2 #cur-map-id
      value: 1691863236 # id from name 'Benedenn'
  throw: true
```

But i got nothing back, see:
```yaml
code: 0
```

What am i missing ?
