### ISSUE TITLE
REST API请求缓慢

### ISSUE THREAD

**Issue by Yorkzero** [al-one/hass-xiaomi-miot#1275]
使用小米多模网关2接入一个开关

使用`api/services/switch/toggle`切换开关状态，灯亮灭很及时，wss事件反馈也很快，就是REST API请求响应很慢，基本6秒左右才返回响应。

我创建了两个虚拟开关对比，虚拟开关的响应基本在毫秒级。

```yaml
input_boolean:
  test_button:
    name: test_button
    icon: mdi:car
  test_button2:
    name: test_button2
    icon: mdi:car
```

请问开发者有什么头绪吗？
