### ISSUE TITLE
云米热水器 实时温度无法获取，设定温度自动变为0度

### ISSUE THREAD

**Issue by Gamingvin** [al-one/hass-xiaomi-miot#1279]
https://home.miot-spec.com/s/viomi.waterheater.e1

![image](https://github.com/al-one/hass-xiaomi-miot/assets/65865707/a7452e85-45d1-49e4-853b-d892c61036c4)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/65865707/ffd142d4-f9e7-4885-9e9b-cbf7d6247aa2)

**Comment by Gamingvin** [comment]
![image](https://github.com/al-one/hass-xiaomi-miot/assets/65865707/d90031e9-8070-4d56-9478-3846232c99fb)
属性

**Comment by al-one** [comment]
设备未返回正确的温度值，[执行下面的服务命令](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)并观察返回：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_8aee_water_heater
  method: get_prop
  params: [targetTemp]
  throw: true
```

**Comment by Gamingvin** [comment]
![image](https://github.com/al-one/hass-xiaomi-miot/assets/65865707/3f6841ae-e28b-4d9e-bec1-905c9cc2c3e3)
通知中结果
Miio command result
[0]

**Comment by al-one** [comment]
以前是否正常？尝试给设备断电几分钟吧

**Comment by Gamingvin** [comment]
这次重装了，重装了之后的状态就是这样。以前qq有找你，记得是米家分享给你然后写了个sensor获取到的温度，这个忘了写个帖记录下来

**Comment by Gamingvin** [comment]
大佬，我重新试了新的代码
开发者工具-实体 属性如下：
min_temp: 30
max_temp: 75
operation_list: Normal, Heat, Delay
current_temperature: 2
temperature: 0
target_temp_high: 75
target_temp_low: 30
operation_mode: Normal
model: viomi.waterheater.e1
lan_ip: 192.168.2.55
mac_address: ***
entity_class: MiotWaterHeaterEntity
home_room: 默认家庭 浴室
miot_type: urn:miot-spec-v2:device:water-heater:0000A02A:viomi-e1:1
water_heater.temperature: 2
water_heater.status: 2
water_heater.on: true
water_heater.water_level: 2
water_heater.mode: 0
state_updater: lan
sub_entities: water_heater-2.on-4
friendly_name: 热水器设置

用你给的代码改了一下
service: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_8aee_water_heater
  method: get_prop
  params: [water_heater.temperature]
  throw: true

返回结果是
Miio command result
[2, 0, 49, 50, 0, 40, 0, 1, 20, 23]

米家中设置的是目标50度，真实温度是49度。
希望能对这个问题有相关，感谢大佬

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_8aee_water_heater
  method: get_prop
  params: []
  throw: true
```
