### ISSUE TITLE
[FAQ]红外风扇或者其他平台绑定到米家的风扇如何通过本插件接入HA？

### ISSUE THREAD

**Issue by al-one** [al-one/hass-xiaomi-miot#128]
1. 首先你得有一个通过本插件接入HA的小爱
2. 新建一个开关辅助元素：`input_boolean.xiaoai_fan_state`
3. 配置文件加入下面的YAML
```yaml
# configuration.yaml
fan:
  - platform: template
    fans:
      xiaoai_fan:
        friendly_name: "小爱风扇"
        value_template: "{{ states('input_boolean.xiaoai_fan_state') }}"
        percentage_template: 0
        preset_mode_template: ""
        oscillating_template: false
        speed_count: 3
        preset_modes:
          - 直吹风
          - 自然风
        turn_on:
          - service: xiaomi_miot.intelligent_speaker
            data:
              entity_id: media_player.xiaoai_entity_id # 改成你的小爱实体ID
              text: 打开风扇
              execute: true
              silent: true
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.xiaoai_fan_state
        turn_off:
          - service: xiaomi_miot.intelligent_speaker
            data:
              entity_id: media_player.xiaoai_entity_id # 改成你的小爱实体ID
              text: 关闭风扇
              execute: true
              silent: true
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.xiaoai_fan_state
        set_percentage:
          service: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaoai_entity_id # 改成你的小爱实体ID
            text: "风扇风速调到{{ percentage }}"
            execute: true
            silent: true
        set_preset_mode:
          service: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaoai_entity_id # 改成你的小爱实体ID
            text: "风扇模式切换为{{ preset_mode }}"
            execute: true
            silent: true
        set_oscillating:
          service: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaoai_entity_id
            text: "{{ '风扇摇头' if oscillating else '风扇停止摇头' }}"
            execute: true
            silent: true
```
