### ISSUE TITLE
Remote control (Manual mode) on ijai.vacuum.v15 [xiaomi Mop 2 pro]

### ISSUE THREAD

**Issue by Bharath-Springboard** [al-one/hass-xiaomi-miot#1295]
I want to control the robot manually. 

I Basically wrote a script to move the robot to predefined steps ->  forward, right and forward towards dustbin as a reminder to clean it.

So, I Changed "Robot Cleaner Sweep Type" to "Remote" and then executed the below service as per the [spec](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:ijai-v3:1) 

```
service: xiaomi_miot.set_miot_property
data:
  entity_id: vacuum.ijai_v15_3bec_robot_cleaner
  siid: 7
  piid: 16
  value: 1
```

It is working, But the robot only moves **1 step** and then **stops** without me issuing the stop command. 
So, when i call the service above in a loop for 4 times so that robot can move 4 steps forward, it moves, then stops, then moves again and then stops and then moves.....it is not a continuous motion.

Via the Mi Home app, it moves continuously when we hold the forward button and stops only when we release it.

Is there a way to ensure the robot can move more fluidly without stopping and going in between?

Thanks in advance.
