### ISSUE TITLE
在无法连接 api.io.mi.com 的状态下，使用米家智能插座 2的插座的开关手动开关插座，开关状态无法同步至 HA

### ISSUE THREAD

**Issue by Kevin6872** [al-one/hass-xiaomi-miot#1306]
### Device model / 设备型号

[chuangmi.plug.212a01](https://home.miot-spec.com/s/chuangmi.plug.212a01)

### Component version / 插件版本

0.7.12

### HA core version / HA版本

2023.08.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

在无法连接 api.io.mi.com 的状态下，使用米家智能插座 2的插座的开关手动开关插座，开关状态无法同步至 HA，但设备功率等传感器信息可以正常同步

### Entity attributes / 实体属性
```yaml
model: chuangmi.plug.212a01
entity_class: MiotSwitchEntity
miot_type: urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:3
switch.on: true
switch.temperature: 43
switch.working_time: 30
functions_enable.power_enable: true
functions_enable.over_power: 2500
imilab_timer.on_duration: 0
imilab_timer.off_duration: 0
imilab_timer.countdown: 0
imilab_timer.task_switch: false
imilab_timer.countdown_info: false
power_consumption: 100
electric_current-5-2: 5
power_consumption.voltage: 220
electric_power-5-6: 4071
power_consumption.surge_power: 2500
indicator_light.on: false
state_updater: lan
power_cost_today: 104917
power_cost_month: 104917
sub_entities:
  - power_cost_today
  - power_cost_month
  - switch-2.temperature-6
  - power_consumption-5.power_consumption-1
  - power_consumption-5.electric_current-2
  - power_consumption-5.voltage-3
  - power_consumption-5.electric_power-6
  - power_consumption-5.surge_power-7
  - indicator_light-3
device_class: outlet
friendly_name: 米家智能插座 2 Switch
supported_features: 0
```
