### ISSUE TITLE
Aqara 空调伴侣 P3 本地模式

### ISSUE THREAD

**Issue by Kevin6872** [al-one/hass-xiaomi-miot#1307]
我希望 aqara 空调伴侣 P3 可以支持本地控制，抓取了该设备的miio日志，不知道是否可以
[374481477.txt](https://github.com/al-one/hass-xiaomi-miot/files/12570101/374481477.txt)

**Comment by al-one** [comment]
尝试一下[服务命令](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)，并获取结果：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.lumi_acn05_xxxx_air_conditioner
  method: get_prop
  params: [power, mode, tar_temp, fan_level, ver_swing, load_power]
  throw: true
```
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.lumi_acn05_xxxx_air_conditioner
  method: get_prop
  params: [power]
  throw: true
```
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.lumi_acn05_xxxx_air_conditioner
  method: get_model_and_state
  params: []
  throw: true
```
