### ISSUE TITLE
解除power_consumption属性/服务的排除

### ISSUE THREAD

**Issue by keniji** [al-one/hass-xiaomi-miot#1318]
### Device model / 设备型号

[cuco.plug.cp5prd](https://home.miot-spec.com/s/cuco.plug.cp5prd)

### Component version / 插件版本

0.7.12

### HA core version / HA版本

2023.9.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

缺少用于显示设备当前功率的实体，尝试参考 https://github.com/al-one/hass-xiaomi-miot/issues/600 加入：
```yaml
xiaomi_miot:
  device_customizes:
    'cuco.plug.*':
      sensor_attributes:
        - power_consumption
```
但无果，发现设备已有实体的属性中包含：
```
exclude_miot_services: power_consumption, device_setting, use_ele_alert
```
所以是不是需要把排除项移除才可以？谢谢！

### Entity attributes / 实体属性
```yaml
model: cuco.plug.cp5prd
lan_ip: x.x.x.x
mac_address: XX:XX:XX:XX:XX:XX
entity_class: MiotSwitchEntity
home_room: 上海
exclude_miot_services: power_consumption, device_setting, use_ele_alert
miot_type: urn:miot-spec-v2:device:outlet:0000A002:cuco-cp5prd:1
switch.on: true
usb_cyc.cyc_status: false
usb_cyc.data_values: 
alert.overload: true
alert.temperature_high_ci: true
alert.temperature_high_ai: true
indicator_light.on: true
indicator_light.mode: false
indicator_light.start_time: 1380
indicator_light.end_time: 420
physical_controls_locked: true
state_updater: lan
power_cost_today: 1.756
power_cost_month: 2.372
sub_entities: power_cost_today, power_cost_month, physical_controls_locked-8.physical_controls_locked-1, indicator_light-12
device_class: outlet
friendly_name: Switch
supported_features: 0
```

**Comment by keniji** [comment]
Hi,
  我注意到了 #763，目前使用自定义配置覆盖获取了需要的功率信息：
```
xiaomi_miot:
  device_customizes:
    'cuco.plug.*':
      exclude_miot_services: device_setting,use_ele_alert
      exclude_miot_properties: power_consumption,electric_current,voltage
```
稍后我就先关闭此issue了，感谢！
