### ISSUE TITLE
Service set_miot_property and deerma.humidifier.jsq

### ISSUE THREAD

**Issue by RomchikL** [al-one/hass-xiaomi-miot#1344]
Hello!

For my humidifier (deerma.humidifier.jsq) the service "xiaomi_miot.set_miot_property" do not work properly.
E.g. I tryed to use this code to change the target humidity:
```
service: xiaomi_miot.set_miot_property
data:
  entity_id: humidifier.deerma_jsq_befb_humidifier
  siid: 3
  piid: 1
  value: 50
```
but I get the error "Invalid JSON in response"
```
Unable to serialize to JSON. Bad data found at $.result.response.result={'did': 'prop.3.1', 'siid': 3, 'piid': 1, 'code': -4004}(<class 'custom_components.xiaomi_miot.core.miot_spec.MiotResult'>
```
At the same time the service "xiaomi_miot.set_property" works with the filed "humidifier.target_humidity"
