### ISSUE TITLE
风扇童锁功能 switch 变为 lock

### ISSUE THREAD

**Issue by LiYanan2004** [al-one/hass-xiaomi-miot#1354]
风扇型号是：[zhimi-sa1](https://home.miot-spec.com/spec/zhimi.fan.sa1)

里面有一个童锁功能，希望能够把 switch 改成 lock，手动改类型的话状态是反转过来的。

<img width="325" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/37542129/b332309b-4ffc-4620-8d51-a6a0292e30b0">

有什么办法可以反转下这个状态吗？属性是：physical-controls-locked

**Comment by ABUAIJUTIE** [comment]
这个属于 Home Assistant 的问题，建议新建一个 Template 
```
lock:
  - platform: template
    name: 风扇童锁
    unique_id: fan_child_lock
    value_template: "{{ is_state('switch.fan_child_lock', 'on') }}"
    lock:
      service: switch.turn_on
      target:
        entity_id: switch.fan_child_lock
    unlock:
      service: switch.turn_off
      target:
        entity_id: switch.fan_child_lock
```
