### ISSUE TITLE
get_properties 服务传入多个 siid piid 对时出错

### ISSUE THREAD

**Issue by ABUAIJUTIE** [al-one/hass-xiaomi-miot#1367]
### 输入：
```
service: xiaomi_miot.get_properties
data:
  entity_id: sensor.washer
  mapping:
    - siid: 3
      piid: 6
    - siid: 3
      piid: 1
```

### 结果：
```
other_action.stroke: 2
other_action.appoint_time.error: "-4004 Other internal errors"
```
这可能就是 #1359  这个 issue 的原因
