### ISSUE TITLE
Selecting vacuum mode Viomi v8

### ISSUE THREAD

**Issue by RackerCRO** [al-one/hass-xiaomi-miot#1396]
Can't change vacuum mode for Xiaomi Mop-P to sweep, sweep-mop or just mop. Tried setting value "Miio.is mop" to 0 but it won't allow me. Only option I can change is fan speed.

device model:  viomi.vacuum.v8
component version: 0.7.13
HA core version: 2023.11.2

Thank you.

**Comment by codyc1515** [comment]
Same issue for `xiaomi.vacuum.b112`.

**Comment by d13g0m0nt3s** [comment]
Same for Xiaomi.vacum.b112gl

**Comment by Guergeiro** [comment]
Does the following code work if you call the service?
```yaml
# https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:viomi-v8:1  
service: xiaomi_miot.call_action
data:
  throw: false
  entity_id: vacuum.viomi_v8_2ba6_robot_cleaner
  siid: 2
  aiid: 3
```

**Comment by d13g0m0nt3s** [comment]
> Does the following code work if you call the service?
> 
> ```yaml
> # https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:viomi-v8:1  
> service: xiaomi_miot.call_action
> data:
>   throw: false
>   entity_id: {vacuum.viomi_v8 entidy}
>   siid: 2
>   aiid: 3
> ```

Yes, the vacuum begins to sweep. Is posible to change to mop? Thansk

**Comment by D0NY3NK0** [comment]
> Can't change vacuum mode for Xiaomi Mop-P to sweep, sweep-mop or just mop. Tried setting value "Miio.is mop" to 0 but it won't allow me. Only option I can change is fan speed.
> 
> device model: viomi.vacuum.v8 component version: 0.7.13 HA core version: 2023.11.2
> 
> Thank you.

Same here, (same vacuum, Mop P) `vacuum.viomi_v8_da80_robot_cleaner`.
Does not seem to work by spec: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:viomi-v8:1

**Comment by Melaxx19** [comment]
Trying to find solution as well.

**Comment by Twisted7ech** [comment]
Following with b112 as well

**Comment by xumixu** [comment]
I'm a newbie trying to set up my viomi_v8 by google and copy pasting.

[Just found out that the mop mode can be changed by this:](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/187#discussioncomment-2523970)
```yaml
service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: "[[entity_id]]"
        command: set_mode_withroom
        params: "[ XX, [[repeats]], 1, [[selection_unwrapped]] ]|[[jsonify]]"
```
where XX is:
0 for vacuum
1 for mop + vacuum
2 for borders only
3 for only mopping

I'm using "vacuum_platform: al-one/hass-xiaomi-miot"

This guys made a card/menu for selecting the mode but it doesn't work : https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/758

Maybe someone more knowledgable can mix both things to make it work.
