### ISSUE TITLE
deerma.humidifier.jsq2w missing property: current_humidity

### ISSUE THREAD

**Issue by kajarit** [al-one/hass-xiaomi-miot#1417]
### Device model / 设备型号

[deerma.humidifier.jsq2w](https://home.miot-spec.com/s/deerma.humidifier.jsq2w)

### Component version / 插件版本

0.7.13

### HA core version / HA版本

2023.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The "_environment.relative_humidity_" **attribute** should be presented as "_current_humidity_" so the official humidity card would display the value as intended.
Now:
<img width="560" alt="miot_humi_actual" src="https://github.com/al-one/hass-xiaomi-miot/assets/31929264/f2e0d5d1-eb7e-446d-a8ac-07a50d1d56bc">

Would look like this if the **attribute** "_current_humidity_" were provided:
<img width="566" alt="miot_humi_with_current" src="https://github.com/al-one/hass-xiaomi-miot/assets/31929264/18264f06-cb33-46db-9b12-bc51fc51f834">

### Entity attributes / 实体属性
```yaml
min_humidity: 40
max_humidity: 80
available_modes: Off, Level1, Level2, Level3, Humidity
device_class: humidifier
friendly_name: Xiaomi Smart Humidifier 2
supported_features: 1
humidity: 60
mode: Humidity
model: deerma.humidifier.jsq2w
lan_ip: 192.168.x.x
mac_address: 64:xx:xx:xx:x:8A
entity_class: MiotHumidifierEntity
home_room: Home Living room
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq5:1
humidifier.on: true
humidifier.fault: 0
humidifier.fan_level: 4
humidifier.target_humidity: 60
custom.water_shortage_fault: false
custom.the_tank_filed: false
indicator_light.on: true
alarm: true
environment.relative_humidity: 55
environment.temperature: 23
state_updater: lan
sub_entities: humidifier-2.fault-2, custom-7.water_shortage_fault-1, custom-7.the_tank_filed-2, alarm-5.alarm-1, environment-3.relative_humidity-1, environment-3.temperature-7, indicator_light-6
```
