### ISSUE TITLE
Xiaomi Humidifier 3

### ISSUE THREAD

**Issue by RykovDC** [al-one/hass-xiaomi-miot#1420]
### Device model / 设备型号

[zhimi.humidifier.ca6](https://home.miot-spec.com/s/zhimi.humidifier.ca6)

### Component version / 插件版本

2.2.6_0043

### HA core version / HA版本

2023.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hello! I purchased Smartmi Humidifier 3. In the Home Assistant, the water level is constantly displayed at 1%. Although the status in MiHome is as shown in the screenshot. Can you help me?
![IMG_6719](https://github.com/al-one/hass-xiaomi-miot/assets/139807719/bb00e27b-cda1-45fb-8370-5e4b76ebcc51)
![IMG_6721](https://github.com/al-one/hass-xiaomi-miot/assets/139807719/61df3658-18f9-44d4-867d-9f4f9cf03ef9)
![IMG_6720](https://github.com/al-one/hass-xiaomi-miot/assets/139807719/58bee4ec-5d30-468a-984b-641d571a3936)

### Entity attributes / 实体属性
```yaml
min_humidity: 30
max_humidity: 60
available_modes:
  - "Off"
  - Fav
  - Auto
  - Sleep
humidity: 60
mode: Fav
model: zhimi.humidifier.ca6
lan_ip: 192.168.1.75
mac_address: C8:5C:CC:40:2E:22
entity_class: MiotHumidifierEntity
home_room: Гассия 21, 311 Спальня
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:zhimi-ca6:1
humidifier.on: true
humidifier.fault: 0
humidifier.fan_level: 0
humidifier.target_humidity: 60
humidifier.water_level: 1
humidifier.automatic_air_drying: true
humidifier.status: 2
other.actual_speed: 1100
other.country_code: 44
other.clean: false
other.self_clean_percent: 0
other.pump_state: false
other.pump_cnt: 1614
physical_controls_locked: false
screen.brightness: 2
alarm: true
environment.temperature: 25
environment.relative_humidity: 59
state_updater: cloud
sub_entities:
  - humidifier-2.water_level-7
  - other-7.actual_speed-1
  - alarm-4.alarm-1
  - other-7.clean-5
  - screen-5.brightness-2
  - environment-3.temperature-7
  - environment-3.relative_humidity-9
  - physical_controls_locked-6.physical_controls_locked-1
device_class: humidifier
friendly_name: Увлажнитель 2
supported_features: 1
```
