### ISSUE TITLE
Help with custom translation config

### ISSUE THREAD

**Issue by mrskycriper** [al-one/hass-xiaomi-miot#1424]
Hello, I'm having some troubles with translating humidifier mode to friendly names.
One of the attribute values is shown as "Off" instead of Off and doesn't seem to be targetable as a name for translation

Attribute in question:
```yaml
available_modes:
  - "Off"
  - Low # was Level1
  - Medium # was Level2
  - High # was Level3
  - Auto # was Humidity
```

Translation config:
```yaml
xiaomi_miot:
  translations:
    "Off": 'None'
    Level1: 'Low'
    Level2: 'Medium'
    Level3: 'High'
    Humidity: 'Auto'
```

I've also tried labeling it as `Off` and `\"Off\"` but nothing happens after reloading.
