### ISSUE TITLE
viomi.fridge.x4冰箱 Freezing Chamber Target Temperature 不可用

### ISSUE THREAD

**Issue by qq610368720** [al-one/hass-xiaomi-miot#1426]
### Device model / 设备型号

[viomi.fridge.x4](https://home.miot-spec.com/s/viomi.fridge.x4)

### Component version / 插件版本

0.7.13

### HA core version / HA版本

2023.12.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

viomi.fridge.x4冰箱 Freezing Chamber Target Temperature 不可用
![微信截图_20231214113815](https://github.com/al-one/hass-xiaomi-miot/assets/51961126/0ecfcede-2661-409b-8c47-46545230739a)

### Entity attributes / 实体属性
```yaml
number.viomi_x4_c399_target_temperature
min: 2
max: 8
step: 1
mode: auto
entity_class: MiotNumberSubEntity
parent_entity_id: sensor.viomi_x4_c399_refrigerating_chamber
service_description: Refrigerating Chamber
property_description: Target Temperature
target_temperature-3-2: 4
unit_of_measurement: °C
device_class: temperature
icon: mdi:coolant-temperature
friendly_name: 冰箱 Refrigerating Chamber Target Temperature
supported_features: 0
----------------------------
number.viomi_x4_c399_target_temperature_2
min: -23
max: -15
step: 1
mode: auto
unit_of_measurement: °C
device_class: temperature
icon: mdi:coolant-temperature
friendly_name: 冰箱 Freezing Chamber Target Temperature
supported_features: 0
------------------------
sensor.viomi_x4_c399_freezing_chamber
state_class: measurement
model: viomi.fridge.x4
lan_ip: 192.168.11.79
mac_address: 50:ec:50:b7:c3:99
entity_class: MiotSensorEntity
home_room: 904 厨房
miot_type: urn:miot-spec-v2:device:fridge:0000A00F:viomi-x4:1
state_property: fridge_chamber-4.temperature
fridge_chamber-4.temperature: -19
target_temperature-4-2: -18
fridge.mode: 0
state_updater: cloud
unit_of_measurement: °C
device_class: temperature
friendly_name: 冰箱 Freezing Chamber Temperature
supported_features: 0
------------------------------
sensor.viomi_x4_c399_refrigerating_chamber
state_class: measurement
model: viomi.fridge.x4
lan_ip: 192.168.11.79
mac_address: 50:ec:50:b7:c3:99
entity_class: MiotSensorEntity
home_room: 904 厨房
miot_type: urn:miot-spec-v2:device:fridge:0000A00F:viomi-x4:1
state_property: fridge_chamber.temperature
fridge_chamber.temperature: 7
target_temperature-3-2: 4
fridge_chamber.on: true
fridge.mode: 0
state_updater: cloud
sub_entities: fridge_chamber-3.on-3, fridge_chamber-3.target_temperature-2, fridge_chamber-4.target_temperature-2
unit_of_measurement: °C
device_class: temperature
friendly_name: 冰箱 Refrigerating Chamber Temperature
supported_features: 0
------------------------------------
switch.viomi_x4_c399_switch_status
entity_class: MiotSwitchSubEntity
parent_entity_id: sensor.viomi_x4_c399_refrigerating_chamber
service_description: Refrigerating Chamber
property_description: Switch Status
fridge_chamber.on: true
icon: mdi:power
friendly_name: 冰箱 Refrigerating Chamber Switch Status
supported_features: 0
```

### Home Assistant Logs / 系统日志

风扇(dmaker.fan.p9): Got MiioException while fetching the state: Unable to discover the device 192.168.31.89, mapping: {'fan.on': {'siid': 2, 'piid': 1}, 'fan.fan_level': {'siid': 2, 'piid': 2}, 'fan.mode': {'siid': 2, 'piid': 4}, 'fan.horizontal_swing': {'siid': 2, 'piid': 5}, 'fan.horizontal_angle': {'siid': 2, 'piid': 6}, 'fan.alarm': {'siid': 2, 'piid': 7}, 'fan.off_delay_time': {'siid': 2, 'piid': 8}, 'fan.brightness': {'siid': 2, 'piid': 9}, 'fan.speed_level': {'siid': 2, 'piid': 11}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'alarm': {'siid': 4, 'piid': 1}, 'physical_controls_locked': {'siid': 3, 'piid': 1}}, max_properties: 6/12
11:42:49 – (ERROR) Xiaomi Miot Auto (自定义集成) - 消息首次出现在 09:29:46，显示了 267 次
加湿器(deerma.humidifier.mjjsq): Got MiioException while fetching the state: Unable to discover the device 192.168.11.71, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fan_level': {'siid': 2, 'piid': 2}, 'humidifier.target_humidity': {'siid': 2, 'piid': 3}, 'humidifier.water_status': {'siid': 2, 'piid': 102}, 'humidifier.tank_status': {'siid': 2, 'piid': 103}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'alarm': {'siid': 4, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 2}}, max_properties: 10/9
11:42:28 – (ERROR) Xiaomi Miot Auto (自定义集成) - 消息首次出现在 09:29:47，显示了 134 次
扫地机器人(roborock.vacuum.t6): Got MiioException while fetching the state: Unable to discover the device 192.168.31.174, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.mode': {'siid': 2, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}}, max_properties: 10/3
11:42:28 – (ERROR) Xiaomi Miot Auto (自定义集成) - 消息首次出现在 09:29:47，显示了 134 次
Setup of vacuum platform xiaomi_miot is taking over 10 seconds.
11:06:23 – (WARNING) 扫地机 - 消息首次出现在 09:29:52，显示了 2 次
Setup of humidifier platform xiaomi_miot is taking over 10 seconds.
11:06:23 – (WARNING) 加湿器
Request xiaomi api: user/get_user_device_data {'did': 'lumi.158d0005449d62', 'key': 'device_log', 'type': 'prop', 'time_start': 1702262627, 'time_end': 1702521887, 'limit': 1} failed, response: None
10:43:58 – (WARNING) Xiaomi Miot Auto (自定义集成)
