### ISSUE TITLE
mmgg.pet_waterer.s1 excess space bar

### ISSUE THREAD

**Issue by Dambo-nn** [al-one/hass-xiaomi-miot#1427]
### Device model / 设备型号

[mmgg.pet_waterer.s1](https://home.miot-spec.com/s/mmgg.pet_waterer.s1)

### Component version / 插件版本

0.7.13

### HA core version / HA版本

2023.12.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

mmgg.pet_waterer.s1:
 select.mmgg_s1_cd87_mode - excess space bar
![20231214_134358](https://github.com/al-one/hass-xiaomi-miot/assets/74897892/ae3d5427-160e-4231-a8aa-882f4596e1ef)

![20231214_114019](https://github.com/al-one/hass-xiaomi-miot/assets/74897892/9d5b097f-93cb-47f4-b38d-b0f956e5dc74)

### Entity attributes / 实体属性
```yaml
options:
  - Common
  - "Smart "
entity_class: MiotSelectSubEntity
parent_entity_id: switch.mmgg_s1_cd87_pet_drinking_fountain
service_description: Pet Drinking Fountain
property_description: Mode
pet_drinking_fountain.mode: 2
icon: mdi:menu
friendly_name: Поилка (Муся) Pet Drinking Fountain Mode
supported_features: 0
```

**Comment by al-one** [comment]
![mmgg.pet_waterer.s1 miot spec](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/98287b45-f688-4a9e-9ecb-6c5be3c43d2e)

It is defined by the device manufacturer, and you can resolve it through the following configuration:
```yaml
# configuration.yaml
xiaomi_miot:
  translations:
    pet_drinking_fountain.mode:
      'smart ': Smart
```
