### ISSUE TITLE
请问为什么我设置了 ignore_offline: true还是会通知Devices offline

### ISSUE THREAD

**Issue by kl79613** [al-one/hass-xiaomi-miot#1429]
<img width="2073" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/60849742/381f00c2-b8ec-4829-b169-29d8069f672e">
如图所示,是哪里没设置对吗

**Comment by al-one** [comment]
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    '*.plug.*':
      ignore_offline: true
    '*.fan.*':
      ignore_offline: true
```
