### ISSUE TITLE
米家晾衣架下降按钮不能点击

### ISSUE THREAD

**Issue by hubeiyaowenping** [al-one/hass-xiaomi-miot#1468]
### Device model / 设备型号

hyd.airer.znlyj5 制造商：hyd 固件：2.2.1

### Component version / 插件版本

0.7.14

### HA core version / HA版本

2023.12.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家晾衣架 上升/停止/开关灯按钮正常，但下降按钮呈灰色，不能点击

米家app控制下降后，homeassitant 里可以通过按钮实现上升 和停止。

### Entity attributes / 实体属性

[cover.hyd_znlyj5_37a8_airer](http://192.168.0.147:8123/developer-tools/state#)
小米晾衣架 Airer

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:209
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 14:12:04 (1 occurrences)
Last logged: 14:12:04

Request xiaomi api: scene/history {'home_id': 478001120365, 'uid': 2340764230, 'owner_uid': 2340764230, 'command': 'history', 'limit': 15} failed, response: None

**Comment by zonzlee** [comment]
这个链接中有修复此问题的方法 https://github.com/al-one/hass-xiaomi-miot/issues/1203

**Comment by Arnie97** [comment]
已通过 9086158 修复

**Comment by Uiisland** [comment]
我这里还是不行，可以点击上升，开灯，但不能点击下降
Xiaomi Miot版本：1.1.2
HA版本：
安装方式 Home Assistant OS
Core 2026.2.1
Supervisor 2026.02.1
Operating System 17.0
Frontend 20260128.6

Button.info
Mijia Smart Clothes Drying Rack
Model
hyd.airer.znlyj4
Did
583150097
MAC
CC:B5:D1:22:01:F1
Lan IP
192.168.31.51
App link
mihome://device?uid=1455425977&did=583150097
Miot type
urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj4:2
Available
true
Updater
local
Airer.current position
1
Airer.status.error
-4004 Other internal errors
Converters
button.info, light.light.on, cover.airer.motor_control, airer.status, airer.motor_control, airer.current_position
```yaml
sensor_properties: left_time
switch_properties: uv
select_properties: mode,dryer
chunk_coordinators:
  - interval: 16
    props: status,current_position,target_position
  - interval: 21
    props: light.on
  - interval: 26
    props: dryer,drying_level,uv
number_properties: drying_time
exclude_miot_properties: motor_control
cover_position_mapping:
  '0': 50
  '1': 100
  '2': 0
```
