### ISSUE TITLE
Water Level sensor for zhimi.humidifier.ca4 shows incorrect values

### ISSUE THREAD

**Issue by sviperz** [al-one/hass-xiaomi-miot#1484]
### Device model / 设备型号

zhimi.humidifier.ca4

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.1.1

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

When fully loaded with water Mi Home app shows 100% water level while HA integration shows 120%.

![image](https://github.com/al-one/hass-xiaomi-miot/assets/11470610/4daddd38-1956-4c09-a69c-eeef4f879c23)

Tried to fix using template, but it's not just like 120 - 20 = 100, the formula is not linear over the whole 100-0% interval.

### Entity attributes / 实体属性

```yaml
min_humidity:` 30
max_humidity: 80
available_modes:
  - "Off"
  - Auto
  - Level1
  - Level2
  - Level3
current_humidity: 45
humidity: 60
mode: Level1
model: zhimi.humidifier.ca4
lan_ip: 192.168.1.201
mac_address: EC:4D:3E:69:16:93
entity_class: MiotHumidifierEntity
home_room: Cave Living Room
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:zhimi-ca4:2
humidifier.on: true
humidifier.fault: 0
humidifier.fan_level: 1
humidifier.target_humidity: 60
humidifier.water_level: 120
humidifier.speed_level: 550
humidifier.dry: false
humidifier.use_time: 8784480
humidifier.button_pressed: 1
other.actual_speed: 554
other.power_time: 2071401
other.country_code: 7
other.clean: false
physical_controls_locked: false
screen.brightness: 1
alarm: true
environment.temperature: 23.5
environment.relative_humidity: 45
environment.fahrenheit: 74.2
state_updater: lan
sub_entities:
  - humidifier-2.water_level-7
  - other-7.actual_speed-1
  - humidifier-2.dry-8
  - alarm-4.alarm-1
  - other-7.clean-5
  - humidifier-2.speed_level-11
  - screen-5.brightness-2
  - environment-3.temperature-7
  - environment-3.relative_humidity-9
  - physical_controls_locked-6.physical_controls_locked-1
device_class: humidifier
friendly_name: Humidifer Humidifier
supported_features: 1
```
