### ISSUE TITLE
dreame.vacuum.mc1808 impossible to launch via script because of formatting issues

### ISSUE THREAD

**Issue by StarterCraft** [al-one/hass-xiaomi-miot#1506]
### Device model / 设备型号

dreame.vacuum.mc1808

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.1.1

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

A script is used to implement repeated zone cleaning with the `dreame.vacuum.mc1808`. As far as I know, this vacuum requires piid `21` (mapping data for zone & area cleaning) is required to be a **minified JSON string**. Unfortunately, when the template is rendered, it always rebuilds the string into an object, which results in the `result: false` response from the vacuum. I haven't found a way to force piid `21` value to a string.

Script part with the issue:
```yaml
- variables:
  begin: "{{states('sensor.pill_battery_level')}}"
  returned: ""
- service: xiaomi_miot.call_action
  metadata: {}
  data:
    entity_id: vacuum.pill
    siid: 18
    aiid: 1
    params:
      - piid: 1
        value: 18
      - piid: 21
        value: >-
          {{"{\"selects\": ["}}{% for item in selected
          %}{{"["}}{{item}},1,{{fan_speed}},{{mop_intensity}},1{{"]"}}{%
          if not loop.last %},{% endif %} {% endfor %}{{"]}"}}
    force_params: true
  response_variable: returned
```
Running frame:
```yaml
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    entity_id: vacuum.pill
    siid: 18
    aiid: 1
    params:
      - piid: 1
        value: 18
      - piid: 21
        value:
          selects:
            - - 9 #it is seen that the JSON is converted into an object
              - 1
              - 1
              - 3
              - 1
    force_params: true
  target: {}
running_script: false
child_id:
  domain: automation
  item_id: '1705398519976'
  run_id: 50aeec24e54fa28cfbfc30a2397e5cc7
```
Vacuum refuses to work:
```yaml
returned:
  result: false
```

### Entity attributes / 实体属性

```yaml
Model: dreame.vacuum.mc1808
Lan IP: 192.168.0.153
MAC address: AC:64:CF:A5:B0:19
Entity class: MiotVacuumEntity
Exclude miot services: consumable, annoy, remote, time
Exclude miot properties: delete_timer, clean_info, map_view, frame_info
Miot type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-mc1808:1
Vacuum.fault: 0
Vacuum.status: 6
Audio.volume: 9
Audio.voice packets: RU
Clean.work mode: 6
Clean.area:
Clean.timer: 77-1-1705236796-06:00-1111111-1-1-0
Clean.mode: 1
Clean.water box: 0
Clean.total clean time: 2 126
Clean.total clean times: 121
Clean.total clean area: 1 507
Clean.clean log start time: 1 696 502 266
Clean.button led: 0
Clean.task done: 1
Brush left time-28-1: 139
Brush life level-28-2: 69
Filter.filter life level: 59
Filter.filter left time: 89
Brush cleaner.brush left time: 239
Brush cleaner.brush life level: 79
Battery.charging state: 1
State updater: lan
Vacuum.status desc: Charging
Sub entities: vacuum-3.status-2, filter-27.filter_life_level-1, filter-27.filter_left_time-2, battery-2.battery_level-1, battery-2.charging_state-2, brush_cleaner-26.brush_left_time-1, brush_cleaner-26.brush_life_level-2, brush_cleaner-28.brush_left_time-1, brush_cleaner-28.brush_life_level-2
Miot action error: -1
Miot action result: 
 did: action-18-1
 siid: 18
 aiid: 1
 code: -1
```
