### ISSUE TITLE
新风机的PM2.5无法在 homekit 中显示

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#153]
新风机PM25信息如下：
-----------
environment.pm2_5_density: 3
parent_entity_id: climate.xin_feng_ji_air_fresh
unit_of_measurement: µg/m³
friendly_name: 新风机 Environment PM2.5 Density
supported_features: 0
-----------

------自定义模板都可以显示----------
sensor:
  - platform: template
    sensors:
      pm25_jiujiao:
        friendly_name: "PM2.5"
        value_template: "{{ states('sensor.xin_feng_ji_environment_pm2_5_density') }}"
        unit_of_measurement: "µg/m³"
        unique_id: pm25_jiujiao

**Comment by al-one** [comment]
你还可以通过[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)自动添加子实体：
```yaml
# customize.yaml
domain.parent_entity_id:
  sensor_properties: pm2_5_density,temperature
```
