### ISSUE TITLE
适配xjx.toilet.relax的miio中的冲水功能出现问题

### ISSUE THREAD

**Issue by nesror** [al-one/hass-xiaomi-miot#1536]
### Device model / 设备型号

[xjx.toilet.relax](https://home.miot-spec.com/s/xjx.toilet.relax)

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.2.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

在miot_specs_extend增加：
```javascript
"xjx.toilet.relax": [
    {
      "iid": 5,
      "actions": [
        {
          "iid": 1,
          "type": "urn:miot-spec-v2:action:flush-on",
          "description": "Flush",
          "in": [],
          "out": []
        }
      ]
    }
  ]
```
在miio2miot_specs中增加action.5.1：
```python
'xjx.toilet.relax': {
        'extend_model': 'xjx.toilet.pro',
        'miio_specs': {
            'prop.2.1': {'prop': 'seating'},
            'prop.2.2': {'prop': 'status_bubbleshield', 'setter': 'set_bubble', 'set_template': '{{ [value|int] }}'},
            'prop.3.1': {'prop': 'status_seatheat', 'setter': 'work_seatheat', 'set_template': '{{ [value|int] }}'},
            'prop.3.2': {'prop': 'seat_temp', 'setter': 'set_seat_temp'},
            'prop.4.1': {'prop': 'status_led', 'setter': 'work_night_led', 'set_template': '{{ [value|int] }}'},
            'action.5.1': {'setter': 'flush_on'},
        },
    },
```
无法出现冲水的action实体，需要怎么处理

### Entity attributes / 实体属性
```yaml
model: xjx.toilet.relax
lan_ip: 192.168.31.144
mac_address: 64:90:C1:D3:55:40
entity_class: MiotToiletEntity
home_room: Nestor的家 主卫
miot_type: urn:miot-spec-v2:device:toilet:0000A02E:xjx-relax:1
toilet.seating_state: false
toilet.deodorization: null
night_light.on: null
seat.heating: null
seat.heat_level: null
state_updater: lan
state_property: toilet.seating_state
sub_entities: night_light-4, heat_level
icon: mdi:toilet
friendly_name: 马桶 Toilet
supported_features: 0
```
