### ISSUE TITLE
Missing night mode in bedside lamp

### ISSUE THREAD

**Issue by Santanachia** [al-one/hass-xiaomi-miot#1549]
### Device model / 设备型号

yeelink.light.bslamp1

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.2.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Xiaomi bedside lamp 1 has a night mode. It has a prdefined light temperature and a brightness lower than the lowest that can be set normally.
This mode is not available in this integration.
In the [Yeelight](https://www.home-assistant.io/integrations/yeelight) integration, it is available as a separate switch

### Entity attributes / 实体属性

```yaml
min_color_temp_kelvin: 1700
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 588
effect_list:
  - Color
  - Day
supported_color_modes:
  - brightness
  - color_temp
  - hs
  - onoff
effect: null
color_mode: null
brightness: null
color_temp_kelvin: null
color_temp: null
hs_color: null
rgb_color: null
xy_color: null
model: yeelink.light.bslamp1
lan_ip: 192.168.100.122
mac_address: 78:11:DC:91:8E:97
entity_class: MiotLightEntity
home_room: Zaciszna Sypialnia
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-bslamp1:2
light.on: false
light.brightness: 3
light.color: 16750592
light.color_temperature: 2702
light.mode: 2
light.saturability: 100
state_updater: lan
friendly_name: Lampka nocna Light
supported_features: 36
```
