### ISSUE TITLE
Ainice三体场景传感器 ainice.sensor_occupy.3b 实时触发

### ISSUE THREAD

**Issue by al-one** [al-one/hass-xiaomi-miot#1558]
本插件最近适配了[Ainice三体场景传感器`ainice.sensor_occupy.3b`](https://home.miot-spec.com/s/ainice.sensor_occupy.3b)，默认的更新频率为10秒，然而实际使用中，这个频率会产生挺大的延迟，这里有一种可以通过HA自动化实时触发的方法。

添加自动化：
```yaml
description: 三体传感器每秒更新
mode: single
trigger:
  - platform: time_pattern
    seconds: /1 # 每秒执行一次
condition: []
action:
  - service: xiaomi_miot.get_properties
    data:
      entity_id: sensor.ainice_3b_xxxx_occupancy_sensor # 换成你的三体传感器实体ID
      mapping:
        - {siid: 2, piid: 1}  # current_occupied
        - {siid: 2, piid: 2}  # total_occupied
        - {siid: 2, piid: 5}  # a_occupied
        - {siid: 2, piid: 8}  # b_occupied
        - {siid: 2, piid: 11} # c_occupied
        - {siid: 2, piid: 14} # d_occupied
        - {siid: 2, piid: 17} # e_occupied
      update_entity: true
```
