### ISSUE TITLE
This entity is no longer being provided by the xiaomi_miot integration.

### ISSUE THREAD

**Issue by fixsssator** [al-one/hass-xiaomi-miot#1580]
### Device model / 设备型号

[mmgg.feeder.inland](https://home.miot-spec.com/s/mmgg.feeder.inland)

### Component version / 插件版本

0.7.16

### HA core version / HA版本

2024.3.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

After updating to core-2024.1.0b2, Pet Feeder Feeding Measure button do not work.
The button are locked. There is a message in the integration:
This entity is no longer being provided by the xiaomi_miot integration. If the entity is no longer in use, delete it in settings.

### Entity attributes / 实体属性
```yaml
model: mmgg.feeder.inland
lan_ip: 192.168.31.220
mac_address: 7C:C2:94:74:18:C4
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-inland:1
state_property: pet_feeder.fault
pet_feeder.fault.error: -4004 Other internal errors
pet_feeder.pet_food_left_level.error: -4004 Other internal errors
devicecontrolserve.led_control.error: -4004 Other internal errors
factory_result-9-11: 1,2,3,6,1
devicecontrolserve.contrycode.error: -4004 Other internal errors
clearnserve.cleantime.error: -4004 Other internal errors
keyserve.key_stat.error: -4004 Other internal errors
feedplanserve.feedplan_contr.error: -4004 Other internal errors
feedplanserve.feddplan_string: 1,2,3,6,0
feedserve.outfood_num.error: -4004 Other internal errors
feedserve.outfood_id.error: -4004 Other internal errors
feedserve.foodstatus.error: -4004 Other internal errors
feedserve.outletstatus.error: -4004 Other internal errors
feedserve.doorstatus.error: -4004 Other internal errors
desiccant.desiccant_left_time.error: -4004 Other internal errors
state_updater: lan
friendly_name: Xiaomi Pet Feeder Pet Feeder Device Fault
supported_features: 0
```

### Home Assistant Logs / 系统日志

2024-03-15 00:51:55.391 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.mmgg_inland_18c4_pet_feeder is taking over 10 seconds
