### ISSUE TITLE
小爱音响play control conversation实体获取小爱语音的问题反馈

### ISSUE THREAD

**Issue by yzjleo** [al-one/hass-xiaomi-miot#1600]
今早发现由小爱语音触发的热水循环突然自己启动了，查了一下，发现小爱音响play control conversation实体莫名其妙的在早上7：30获取到了几个之前已经发生过的小爱语音，导致了流程触发。
尝试把xiaomi_miot升级到了最新的0.7.17，问题还是依旧（附件截图11：32分就是升级后的）
小米中枢网关版本：3.1.0_0051
小爱音响本版：小爱音响pro  软件：1.88.51
HA版本：2023.11.2
![微信截图_20240327115503](https://github.com/al-one/hass-xiaomi-miot/assets/123380398/e9082b9d-17a5-4232-821d-c0dc680f2016)
![微信截图_20240327122235](https://github.com/al-one/hass-xiaomi-miot/assets/123380398/6c9cc2da-3c7c-4719-82fc-d275d969f8ff)
![微信截图_20240327115755](https://github.com/al-one/hass-xiaomi-miot/assets/123380398/a7a24ceb-7167-42f9-b43f-a989734154ae)
![微信截图_20240327115840](https://github.com/al-one/hass-xiaomi-miot/assets/123380398/94f5fa58-84b9-4eeb-b392-6bf9980f68f4)

**Comment by yzjleo** [comment]
![微信截图_20240327123013](https://github.com/al-one/hass-xiaomi-miot/assets/123380398/c8ba5273-2036-49d1-9d4e-2461fbc6a529)
![微信截图_20240327123042](https://github.com/al-one/hass-xiaomi-miot/assets/123380398/64fb9295-3cf0-4cd3-9957-a965373c6535)

**Comment by yzjleo** [comment]
![微信截图_20240327123538](https://github.com/al-one/hass-xiaomi-miot/assets/123380398/3b7babe6-f213-456f-a14a-386c7e2e4f00)

**Comment by al-one** [comment]
轮询失败、重启HA都有可能导致实体状态变化，保险起见，你应该判断`conversation`实体的`timestamp`属性。
```yaml
condition:
  - condition: template
    value_template: |
      {{ (trigger.to_state|default(0)) and as_timestamp(now()) -
      as_timestamp(trigger.to_state.attributes.timestamp) < 60 }}
      {# 限制60秒内的对话 #}
```
- #537
