### ISSUE TITLE
小米空气净化器4proH 实体功能缺失

### ISSUE THREAD

**Issue by charleypeng** [al-one/hass-xiaomi-miot#1601]
### Device model / 设备型号

[xiaomi.airp.va4](https://home.miot-spec.com/s/xiaomi.airp.va4)

### Component version / 插件版本

0.7.17

### HA core version / HA版本

2024.3.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

设备是小米空气净化器4proH，请问是否可以集成负离子/uv灯的开关？ 谢谢

### Entity attributes / 实体属性

无实体

### Home Assistant Logs / 系统日志

无

**Comment by charleypeng** [comment]
用ai生成了一个，不知道有没有错
```yaml
switch:
  - platform: template
    switches:
      air_purifier_uv:
        value_template: "{{ is_state_attr('fan.xiaomi_va4_9e74_air_purifier', 'air_purifier.uv', true) }}"
        turn_on:
          service: fan.set_speed
          data:
            entity_id: fan.xiaomi_va4_9e74_air_purifier
            speed: 'on'
        turn_off:
          service: fan.set_speed
          data:
            entity_id: fan.xiaomi_va4_9e74_air_purifier
            speed: 'off'
```
