### ISSUE TITLE
小米电视（xiaomi.tv.v1）无法获取状态，一直显示为“未知”

### ISSUE THREAD

**Issue by chenjiezb** [al-one/hass-xiaomi-miot#1618]
### Device model / 设备型号

xiaomi.tv.v1

### Component version / 插件版本

0.7.17

### HA core version / HA版本

2024.4.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

使用的是瀚思彼岸论坛上的冬瓜haos系统，安装在cm311-1a上。随着最近系统和插件升级，发现小米电视的Play Control实体状态不能随电视的开关状态更新了，一直为“未知/unknown”。而相同版本的系统及插件，在VMware中的官方haos上运行正常。

### Entity attributes / 实体属性
```yaml
source_list:
  - TV
  - DTMB
  - AV
  - HDMI 1
  - HDMI 2
volume_level: 0.09
is_volume_muted: false
app_id: com.xiaomi.tv.gallery
app_name: 时尚画报
source: TV
model: xiaomi.tv.v1
lan_ip: 192.168.10.64
mac_address: [mac]
entity_class: MitvMediaPlayerEntity
home_room: 客厅
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-v1:2
6095_state: true
remote_control.state_playing: true
speaker.volume: 9
speaker.mute: false
television.input_control: 1
state_updater: cloud
capture: >-
  http://192.168.10.64:6095/request?action=getResource&name=screenCapture&timestamp=1712217597918&opaque=2a2b07cb1b02820cf00a9c6e77c5a0e70eae7c3c
capture_token: uYcGFcqyqLh01dB0
app_current: 时尚画报 - com.xiaomi.tv.gallery
app_page: com.xiaomi.tv.gallery.view.ScreenSaverActivity
sub_entities:
  - apps
  - keycodes
  - speaker-4.volume-1
  - message_router-5.post-1
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.xiaomi_v1_fff0_play_control?token=0f44c2e8d2b88a091dae7866384d408852908a0acdb53206c87eafc80e6b318f&cache=c59bc2e0cd08a874
friendly_name: 小米电视 Play Control
supported_features: 20365
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志: custom_components.xiaomi_miot.core.xiaomi_cloud
来源: custom_components/xiaomi_miot/core/xiaomi_cloud.py:217
集成: Xiaomi Miot Auto (文档, 问题)
首次发生: 15:58:37 (4 全部发生)
上次记录: 16:06:37

Request xiaomi api: https://api2.mina.mi.com/remote/ubus {'deviceId': 'c66d8c27-e9ad-4a42-9ba3-a17d823d57c0', 'path': 'mediaplayer', 'method': 'player_get_play_status', 'message': '{}'} failed, response: None
Request xiaomi api: https://api2.mina.mi.com/remote/ubus {'deviceId': 'c7b7a6cf-52de-4fb8-998b-7c8cff7c0831', 'path': 'mediaplayer', 'method': 'player_get_play_status', 'message': '{}'} failed, response: None
Request xiaomi api: https://api2.mina.mi.com/remote/ubus {'deviceId': '39361b07-6360-4df1-a71d-85f18c5b0a41', 'path': 'mediaplayer', 'method': 'player_get_play_status', 'message': '{}'} failed, response: None
