### ISSUE TITLE
Can I join the wake-up state of Xiaoai speakers?

### ISSUE THREAD

**Issue by wozas123** [al-one/hass-xiaomi-miot#167]
There is a wake-up state in the MI HOME APP automation condition
Can this function be added if there is no service place?

**Comment by al-one** [comment]
Get `siid`/`aiid` of action `wake-up` from `https://home.miot-spec.com/spec?model=xiaomi.wifispeaker.your-model`.
Call action via HA service [`xiaomi_miot.call_action`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.call_action), example for [`xiaomi.wifispeaker.lx04`](https://home.miot-spec.com/spec?model=xiaomi.wifispeaker.lx04):
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: media_player.xiaoai_lx04_xxxx
  siid: 5 # siid of service intelligent-speaker
  aiid: 2 # aiid of action wake-up
  params:
    - Hello
```
