### ISSUE TITLE
小米风扇1x升级版没有控制风速档位的实体

### ISSUE THREAD

**Issue by zichenw** [al-one/hass-xiaomi-miot#1691]
### Device model / 设备型号

[dmaker.fan.p5c](https://home.miot-spec.com/s/dmaker.fan.p5c)

### Component version / 插件版本

0.7.18

### HA core version / HA版本

2024.2.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![chrome_XzdR7ExooT](https://github.com/al-one/hass-xiaomi-miot/assets/19666814/4d835cc2-1ab0-482e-b569-b83f1f8f08c4)

### Entity attributes / 实体属性
```yaml
preset_modes:
  - Straight Wind
  - Natural Wind
oscillating: true
percentage: 100
percentage_step: 1
preset_mode: Natural Wind
model: dmaker.fan.p5c
lan_ip: 192.168.0.38
mac_address: 64:9E:31:25:11:02
entity_class: MiotFanEntity
home_room: 我的家 卧室
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p5c:1
fan.on: true
fan.fan_level: 2
fan.mode: 1
fan.horizontal_swing: true
horizontal_swing_included_angle-2-5: 120
fan.status: 0
dm_service.speed_level: 100
dm_service.natural_list: a_b_c_d_e_f_g_h_i_j_k_l
dm_service.natural_e: 81ea5b9a4e490031_360_360_360_360_360_16
dm_service.natural_f: 81ea5b9a4e490032_360_360_360_360_360_16
dm_service.natural_g: 81ea5b9a4e490033_360_360_360_360_360_16
dm_service.natural_h: 81ea5b9a4e490034_360_360_360_360_360_16
off_delay_time: 0
physical_controls_locked: false
alarm: false
indicator_light.on: true
state_updater: lan
sub_entities:
  - fan-2.horizontal_swing-4
  - alarm-5.alarm-1
  - off_delay_time-3.off_delay_time-1
  - fan-2.horizontal_swing_included_angle-5
  - fan-2.turn_left-2
  - fan-2.turn_right-3
  - dm_service-8.toggle_mode-1
  - dm_service-8.loop_gear-2
  - physical_controls_locked-7.physical_controls_locked-1
  - indicator_light-4
miot_action_result:
  did: "656862462"
  siid: 2
  aiid: 3
  code: 0
friendly_name: 小米风扇1X Fan
supported_features: 11
```
