### ISSUE TITLE
小米人在传感器缺少光照实体

### ISSUE THREAD

**Issue by FlyRenxing** [al-one/hass-xiaomi-miot#1700]
### Device model / 设备型号

[xiaomi.sensor_occupy.03](https://home.miot-spec.com/s/xiaomi.sensor_occupy.03)

### Component version / 插件版本

0.7.18

### HA core version / HA版本

2024.5.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米人在传感器缺少光照实体。
在该设备的Xiaomi Human Presence Sensor Occupancy Sensor Status传感器中包含Occupancy sensor.illumination属性可作为实体。希望添加适配。
经测试以下配置可自定义实体：
``` yaml
template: 
    sensors:
      xiaomi_03_baf0_occupancy_sensor_illumination:
        friendly_name: "小米人在传感器-亮度"
        unit_of_measurement: 'lx'
        value_template: "{{ state_attr('sensor.xiaomi_03_baf0_occupancy_sensor', 'occupancy_sensor.illumination') }}"
        unique_id: "32b33778a2614be0a3290f81afdeaba4"
```
<img width="560" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/21098184/32844547-0e41-4f47-9f7c-012e40cad6a4">

### Entity attributes / 实体属性

无实体

### Home Assistant Logs / 系统日志

无需日志
