### ISSUE TITLE
小爱音箱play control conversation传感器实体，可以做成一个服务以供主动调用获取最新值吗

### ISSUE THREAD

**Issue by xy3777** [al-one/hass-xiaomi-miot#1703]
我现在弄了个自动化，触发后需要获取小爱音箱最新的对话，研究了下play control conversation，好像是从云端获取的，需要token、cookie，自己写脚本登陆来获取好麻烦，Request xiaomi API好像改不了请求域，小爱音箱的请求域和其它米家iot接口不在同一个域。要是能把play control conversation也做成一个服务可以主动调用就好了，还请大佬帮忙看看，是否可以加，或者还有没有其他好办法，谢谢

**Comment by GreenYi** [comment]
你有没有解决办法？我也在找类似的方法

**Comment by al-one** [comment]
- #1906

这篇教程里有主动更新的例子。

```yaml
action: homeassistant.update_entity
target:
  entity_id: sensor.xiaomi_x08c_xxxx_conversation
```
