### ISSUE TITLE
viomi.waterheater.e1 不显示当前温度和水位

### ISSUE THREAD

**Issue by Gamingvin** [al-one/hass-xiaomi-miot#1707]
### Device model / 设备型号

[viomi.waterheater.e1](https://home.miot-spec.com/s/viomi.waterheater.e1)

### Component version / 插件版本

0.7.18 

### HA core version / HA版本

2024.6.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

不显示当前温度和水位。当前温度为 0 ，目标温度为0，水位没有显示
尝试按照https://github.com/al-one/hass-xiaomi-miot/issues/375
升级到master分支，不显示；尝试修改init.py，device_customizes.py，不能启动，只能回退。
开发者工具→服务：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_8aee_water_heater
  method: get_prop
  params:
    - targetTemp
    - waterTemp
    - washStatus
    - hotWater
    - modeType
```
返回结果
```yaml
result:
  - 0
  - 0
  - 37
  - 50
  - 0
  - 20
  - 0
  - 1
  - 20
  - 23
```

对应米家显示
![微信图片_20240612121009](https://github.com/al-one/hass-xiaomi-miot/assets/65865707/cfc7003c-9d31-47bf-96be-64a11b0cf842)

### Entity attributes / 实体属性
```yaml
min_temp: 30
max_temp: 75
operation_list: Normal, Heat, Delay
current_temperature: 0
temperature: 0
target_temp_high: 75
target_temp_low: 30
operation_mode: Normal
model: viomi.waterheater.e1
lan_ip: 192.168.2.55
mac_address: 5C:E5:0C:09:8A:EE
entity_class: MiotWaterHeaterEntity
home_room: 默认家庭 浴室
miot_type: urn:miot-spec-v2:device:water-heater:0000A02A:viomi-e1:1
water_heater.temperature: 0
water_heater.status: 0
water_heater.on: false
water_heater.water_level: 0
water_heater.mode: 0
state_updater: lan
friendly_name: 热水器 状态
supported_features: 3
```

### Home Assistant Logs / 系统日志

无关于热水器的日志
