### ISSUE TITLE
摄像头(chuangmi.camera.021a04)获取不到流地址

### ISSUE THREAD

**Issue by TioaChan** [al-one/hass-xiaomi-miot#173]
根据此issus中的说明 https://github.com/al-one/hass-xiaomi-miot/issues/166 检查我的摄像头属性时发现无流地址 

```
access_token: *
brand: chuangmi
motion_detection: true
model: chuangmi.camera.021a04
lan_ip: *
mac_address: *
firmware_version: 4.1.6_0309
hardware_version: ''
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-021a04:3
miot_action_result:
  did: '1022939757'
  miid: 0
  siid: 7
  aiid: 1
  code: -704220035
  exe_time: 0
  net_cost: 0
  ot_cost: 0
  otlocalts: 0
  oa_cost: 0
  _oa_rpc_cost: 0
miot_action_error: '-704220035 Action parameter error'
stream_address: ''
expire_at: '2021-09-02 16:20:35.727145'
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: false
glimmer_full_color-2-6: false
camera_control.recording_mode: 0
camera_control.motion_tracking: true
camera_control.time_watermark: true
bluetooth.bluetooth_switch.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
stream_status-8-9: 1
stream_status-7-9: 1
motion_detection.alarm_interval: 5
detection_sensitivity-5-3: 1
motion_detection_start_time-5-4: '00:00:00'
motion_detection_end_time-5-5: '23:59:59'
memory_card_management.status: 4
storage_total_space-4-2: 31145984
storage_free_space-4-3: 49152
storage_used_space-4-4: 31096832
indicator_light.on: false
state_updater: cloud
sub_entities:
  - camera_control.on
  - motion_detection-5.motion_detection-1
  - indicator_light-3
friendly_name: 摄像头 Camera Control
entity_picture: *
supported_features: 3

```

**Comment by al-one** [comment]
请问该问题解决了吗？

**Comment by TioaChan** [comment]
> 请问该问题解决了吗？

你好，目前摄像头的情况是，点卡摄像头camera_control实体，有米家有通知用户xxx于x时x分在带屏音响上观看摄像头视频，但会一直处于视频缓冲的转圈圈动画

查看HA日志如下：
```
2021-09-09 09:36:38 WARNING (MainThread) [custom_components.xiaomi_miot.camera] 摄像头 Camera Control: camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1630546598000, 'isContinue': True}, 'description': '成功', 'ts': 1631151246415}
2021-09-09 09:36:38 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream https://cn01.livestreaming.io.mi.com/hlstranscoder/*****/playlist.m3u8
2021-09-09 09:37:33 WARNING (MainThread) [custom_components.xiaomi_miot.camera] 摄像头 Camera Control: camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1630546653000, 'isContinue': True}, 'description': '成功', 'ts': 1631151301333}
```
尝试在浏览器打开此链接，提示403错误

**Comment by TioaChan** [comment]
此时状态属性如下：
```
access_token: *
brand: chuangmi
motion_detection: true
model: chuangmi.camera.021a04
lan_ip: *
mac_address: *
firmware_version: 4.1.6_0309
hardware_version: ''
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-021a04:3
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: false
glimmer_full_color-2-6: false
camera_control.recording_mode: 0
camera_control.motion_tracking: true
camera_control.time_watermark: true
bluetooth.bluetooth_switch.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
stream_status-8-9: 1
stream_status-7-9: 1
motion_detection.alarm_interval: 5
detection_sensitivity-5-3: 1
motion_detection_start_time-5-4: '00:00:00'
motion_detection_end_time-5-5: '23:59:59'
memory_card_management.status: 4
storage_total_space-4-2: 31145984
storage_free_space-4-3: 49152
storage_used_space-4-4: 31096832
indicator_light.on: false
state_updater: cloud
sub_entities:
  - camera_control.on
  - motion_event
  - motion_detection-5.motion_detection-1
  - indicator_light-3
miot_action_result:
  did: '1022939757'
  miid: 0
  siid: 7
  aiid: 1
  code: 0
  out:
    - >-
      https://cn02.livestreaming.io.mi.com/hlstranscoder/*/playlist.m3u8
miot_error: null
stream_http_status: 404
stream_http_reason: Not Found
stream_address: >-
  https://cn02.livestreaming.io.mi.com/hlstranscoder/*/playlist.m3u8
expire_at: '2021-09-09 09:45:07.434045'
friendly_name: 摄像头 Camera Control
entity_picture: >-
  /api/camera_proxy/camera.chuangmi_021a04_1671_camera_control?token=*
supported_features: 3
```
