### ISSUE TITLE
小米智能家庭面板里的小爱同学没有我对小爱说的指令这个实体

### ISSUE THREAD

**Issue by zhuzhuani** [al-one/hass-xiaomi-miot#1733]
### Device model / 设备型号

xiaomi.controller.86v1

### Component version / 插件版本

最新

### HA core version / HA版本

最新

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

小米智能家庭面板里的小爱同学在MIOT里,没有我对小爱说的指令这个实体,有什么办法弄出来吗
别的小爱同学比如PRO啦  还有那种带屏幕的 可以获取到我对小爱说的指令  这样我可以在NR中做流程  但是小米智能家庭面板他智能让这个设备TTS说话 没法获取我对他说的指令 有解决方案吗

### Entity attributes / 实体属性

无实体

### Home Assistant Logs / 系统日志

无

**Comment by SodaWithoutSparkles** [comment]
你得看一下在developer tools里面能不能看到相关的state attributes

没有的话就没办法了。只可以每一种语音情况都用小爱训练教一次，然后用米家场景转发给另外一只小爱，再从新的小爱那边处理。

技术上是可以分辨出是句子是转发的还是自己的。我现在也在做。

**Comment by al-one** [comment]
需要在小爱音箱APP中找到该设备，并且可以在APP中按到对话记录才可以。

**Comment by zhuzhuani** [comment]
> 需要在小爱音箱APP中找到该设备，并且可以在APP中按到对话记录才可以。

明白了 那确实不可以 在小爱音箱APP中是找不到这款设备的~

**Comment by xspeed1989** [comment]
> 需要在小爱音箱APP中找到该设备，并且可以在APP中按到对话记录才可以。

米家里面有对话记录

**Comment by al-one** [comment]
1. 先找到面板设备的`did`
2. 调用服务获取小爱ID
    ```yaml
    action: xiaomi_miot.request_xiaomi_api
    data:
      entity_id: media_player.xiaomi_86v1_xxxx
      api: /smarthome/product/panel/plugin/devices
      sid: xiaomiio
      method: POST
      data:
        did: "100913777" # 设备did
    ```
3. 调用服务获取面板设备信息
    ```yaml
    action: xiaomi_miot.request_xiaomi_api
    data:
      entity_id: media_player.xiaomi_86v1_xxxx
      api: https://api2.mina.mi.com/admin/smart_panel/device_info
      sid: micoapi
      method: GET
      data:
        deviceId: 9f9efdd8-6b6e-4f08-ae3b-a509857e7d40 # 小爱ID
    ```
