### ISSUE TITLE
米家落地扇风速和摆头为什么不能集成在一个选项内

### ISSUE THREAD

**Issue by xzajyjs** [al-one/hass-xiaomi-miot#1743]
### Device model / 设备型号

dmaker.fan.p8

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

1. 如图所示，电风扇速度和摆头能否合成一个实体？类似于空调伴侣中的风速、温度和模式集成在同一个里。
2. 另外，如何添加操控电扇后的提示音？
3. 此外，在电风扇风速的配件设置中，有摆动这个选项，但是为什么不会在控制界面中显示呢？
![IMG_6073](https://github.com/al-one/hass-xiaomi-miot/assets/25580455/86986c2c-0f92-459b-a26f-6c1c6e564369)
![IMG_6074](https://github.com/al-one/hass-xiaomi-miot/assets/25580455/0450caa9-0c6e-44c0-8e13-bde47a611e67)

### Entity attributes / 实体属性

```
preset_modes: 
oscillating: false
percentage: 33
percentage_step: 33
preset_mode: Straight Wind
model: dmaker.fan.p8
lan_ip: 192.168.31.172
mac_address: 7C:C2:94:9E:00:2B
entity_class: MiotFanEntity
home_room: xxxx
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p8:2
fan.on: true
fan.fan_level: 1
fan.horizontal_swing: false
fan.mode: 0
fan.off_delay_time: 0
fan.alarm: false
fan.brightness: true
indicator_light.on: true
alarm: false
physical_controls_locked: false
state_updater: lan
sub_entities: fan-2.horizontal_swing-3, fan-2.alarm-11, alarm-4.alarm-1, fan-2.off_delay_time-10, physical_controls_locked-3.physical_controls_locked-1, indicator_light-5
friendly_name: 电风扇
supported_features: 3
```

**Comment by SodaWithoutSparkles** [comment]
我也附议。现在暂时写了一个这样的UI

```
type: vertical-stack
cards:
  - type: tile
    entity: fan.fan1
    show_entity_picture: false
    vertical: false
    hide_state: false
    state_content: percentage
    features:
      - type: fan-speed
      - type: fan-preset-modes
        style: dropdown
        preset_modes:
          - Normal
          - Nature
  - type: conditional
    conditions:
      - condition: state
        entity: input_boolean.fan_fan1_oscillation
        state: 'on'
    card:
      features:
        - style: slider
          type: numeric-input
      type: tile
      entity: number.feng_shan_oscillation_angle
      show_entity_picture: false
      vertical: false
      hide_state: true
      icon_tap_action:
        action: call-service
        service: input_boolean.toggle
        target:
          entity_id: input_boolean.fan_fan1_oscillation
  - type: conditional
    conditions:
      - condition: state
        entity: input_boolean.fan_fan1_oscillation
        state: 'off'
    card:
      type: horizontal-stack
      cards:
        - type: tile
          entity: input_boolean.fan_fan1_oscillation
          tap_action:
            action: call-service
            service: fan.set_direction
            target:
              entity_id: fan.fan1
            data:
              direction: reverse
          icon_tap_action:
            action: call-service
            service: fan.set_direction
            target:
              entity_id: fan.fan1
            data:
              direction: reverse
          name: Left
          icon: mdi:arrow-left-thick
          hide_state: true
        - type: tile
          entity: input_boolean.fan_fan1_oscillation
          name: ' '
          hide_state: false
          state_content: state
          tap_action:
            action: toggle
          icon_tap_action:
            action: toggle
          icon: mdi:arrow-oscillating-off
        - type: tile
          entity: input_boolean.fan_fan1_oscillation
          tap_action:
            action: call-service
            service: fan.set_direction
            target:
              entity_id: fan.fan1
            data:
              direction: forward
          icon_tap_action:
            action: call-service
            service: fan.set_direction
            target:
              entity_id: fan.fan1
            data:
              direction: forward
          name: Right
          icon: mdi:arrow-right-thick
          hide_state: true
```
