### ISSUE TITLE
请问怎么每天重载一次设备？

### ISSUE THREAD

**Issue by jifengmm** [al-one/hass-xiaomi-miot#176]
我发现时间长了不重载，设备的状态的显示和米家App的不一致，不知道什么原因，手动重载一下就行了，我想弄成自动的，比如每天凌晨2点重载一次

**Comment by al-one** [comment]
可以通过HA服务：[`homeassistant.reload_config_entry`](https://my.home-assistant.io/redirect/developer_call_service/?service=homeassistant.reload_config_entry) 来重载集成配置：
```yaml
service: homeassistant.reload_config_entry
target:
  entity_id: sensor.xiaomi_miot_entity_id # 任意属于该集成配置的实体ID
```
> [官方文档](https://www.home-assistant.io/integrations/homeassistant#service-homeassistantreload_config_entry)
