### ISSUE TITLE
Missing property for Lydsto S1

### ISSUE THREAD

**Issue by ShinigamiJ** [al-one/hass-xiaomi-miot#1767]
### Device model / 设备型号

[Lydsto S1](https://home.miot-spec.com/s/zhimi.vacuum.xa3)

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.07

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Unable to get room ids for device https://home.miot-spec.com/s/zhimi.vacuum.xa3:
```yaml
service: xiaomi_miot.get_properties
data:
  entity_id: vacuum.zhimi_xa3_e2f9_robot_cleaner
  mapping:
    - siid: 2
      piid: 12
  throw: true
```
```yaml
result:
  room_ids.error: "-4003 Property/Action/Event does not exist"
```
Same thing goes for maps, cannot do anything within siid 11. I even connected to cloud in configuration.yaml, but nothing changed.
Unrelated question, what is attribute  Custom.clean area ? Can it be used to control which area to clean?
I'd like to get the map once and then send id to the vacuum locally which room to clean, and which map to use.

### Entity attributes / 实体属性

Custom.clean area
room_ids
map
