### ISSUE TITLE
智能窗帘失效 babai.curtain.lsxf83

### ISSUE THREAD

**Issue by GavinIves** [al-one/hass-xiaomi-miot#1774]
### Device model / 设备型号

[babai.curtain.lsxf83](https://home.miot-spec.com/s/babai.curtain.lsxf83)

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.7.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

窗帘无法控制了
```yaml
device_class: curtain
friendly_name: 窗帘 窗帘
supported_features: 15
model: babai.curtain.lsxf83
lan_ip: 10.123.3.7
mac_address: B8:50:D8:F7:9F:B4
entity_class: MiotCoverEntity
home_room: 大笨猪的家 次卧
miot_type: urn:miot-spec-v2:device:curtain:0000A00C:babai-lsxf83:1
curtain.fault: 0
curtain.target_position.error: "-4004 Other internal errors"
curtain.mode.error: "-4004 Other internal errors"
curtain.current_position.error: "-4004 Other internal errors"
curtain.speed_level.error: "-4004 Other internal errors"
state_updater: lan
```

此错误来自自定义集成。

日志记录器: miio.miioprotocol
来源: custom_components/xiaomi_miot/__init__.py:695
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 03:07:04 (1213 次总计出现)
上次记录: 13:13:22

Got error when receiving: timed out

貌似最新版的ha不兼容

### Entity attributes / 实体属性
```yaml
device_class: curtain
friendly_name: 窗帘 窗帘
supported_features: 15
model: babai.curtain.lsxf83
lan_ip: 10.123.3.7
mac_address: B8:50:D8:F7:9F:B4
entity_class: MiotCoverEntity
home_room: 大笨猪的家 次卧
miot_type: urn:miot-spec-v2:device:curtain:0000A00C:babai-lsxf83:1
curtain.fault: 0
curtain.target_position.error: "-4004 Other internal errors"
curtain.mode.error: "-4004 Other internal errors"
curtain.current_position.error: "-4004 Other internal errors"
curtain.speed_level.error: "-4004 Other internal errors"
state_updater: lan
```

**Comment by SodaWithoutSparkles** [comment]
试试参考 #1790 的方法

```
service: xiaomi_miot.get_properties
data:
  entity_id: cover.REPLACE_ME
  mapping:
    - siid: 2
      piid: 3
    - siid: 1
      piid: 5
  update_entity: true
```
