### ISSUE TITLE
Câmera muito action error "The number of action parameters does not match"

### ISSUE THREAD

**Issue by Zeunas** [al-one/hass-xiaomi-miot#179]
Since version 0.4.0 was released I've been getting the below error for my camera, same thing happens with v0.4.1. 

```yaml
miot_action_result:
  did: '76304307'
  miid: 0
  siid: 4
  aiid: 1
  code: -704220025
stream_address: ''
expire_at: '2021-09-09 20:38:28.428118'
miot_error: null
miot_action_error: '-704220025 The number of action parameters does not match'
motion_video_latest
```

After restarting home assistant the 1st stream address works fine but once it refreshes I get the above error.
