### ISSUE TITLE
lumi.acpartner.mcn02 空调无法使用climate.turn_on服务打开空调

### ISSUE THREAD

**Issue by fireinice** [al-one/hass-xiaomi-miot#1792]
### Device model / 设备型号

lumi.acpartner.mcn02 

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.6.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

使用turn_on服务启动空调后，hass显示空调已启动，但是空调没有反应。如果使用set_hvacs_mode 服务，可以正常启动空调

### Entity attributes / 实体属性

```yaml
hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: auto, low, medium, high
swing_modes: off, vertical
current_temperature: null
temperature: 17
fan_mode: auto
hvac_action: off
swing_mode: vertical
model: lumi.acpartner.mcn02
entity_class: MiotClimateEntity
home_room: 我家 卧室
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:lumi-mcn02:1
air_conditioner.on: false
air_conditioner.mode: 0
target_temperature-2-3: 17
electric_power-5-1: 1
fan_control.fan_level: 0
fan_control.vertical_swing: true
state_updater: lan
power_cost_today: 2783
power_cost_month: 6225
sub_entities: power_cost_today, power_cost_month, power_consumption-5.electric_power-1
friendly_name: 米家空调伴侣 Air Conditioner
supported_features: 425
```

### Home Assistant Logs / 系统日志

hass  | 2024-08-02 19:58:17.965 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
hass  | 2024-08-02 19:58:17.965 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
hass  | 2024-08-02 19:58:17.967 INFO (SyncWorker_19) [custom_components.xiaomi_miot.core.miio2miot] lumi.acpartner.mcn02: Set miio prop via miot: ['prop.2.1', 'set_power', ['on']]
hass  | 2024-08-02 19:58:19.025 INFO (SyncWorker_8) [custom_components.xiaomi_miot.core.miio2miot] lumi.acpartner.mcn02: Got miio props for miot: {'power': 'on', 'mode': 'auto', 'tar_temp': 17, 'fan_level': 'auto_fan', 'ver_swing': 'on', 'load_power': 1.0}
