### ISSUE TITLE
Automatic filter_left_time Update Issue with mmgg.pet_waterer.wi11

### ISSUE THREAD

**Issue by sakirsek** [al-one/hass-xiaomi-miot#1797]
### Device model / 设备型号

mmgg.pet_waterer.wi11

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.7.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

I am experiencing an issue with the mmgg.pet_waterer.wi11 device in the Xiaomi Miot integration of Home Assistant. Specifically, the filter_left_time attribute does not update automatically. When I manually reload the integration from /integrations/integration/xiaomi_miot, the correct data appears, but it does not update automatically afterward.

### Entity attributes / 实体属性

```yaml
entity_class: MiotSensorSubEntity
parent_entity_id: switch.mmgg_wi11_dc7d_pet_drinking_fountain
service_description: Filter
property_description: Filter Left Time
updated_time: "2024-08-05T13:47:02.140939+03:00"
filter.filter_left_time: 11
unit_of_measurement: days
friendly_name: CatWater Filter Left Time
supported_features: 0
```

### Home Assistant Logs / 系统日志

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:764
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: July 31, 2024 at 01:52:40 (2 occurrences)
Last logged: 13:47:02

Platform xiaomi_miot does not generate unique IDs. ID [deleted]-filter-3.filter_left_time-1 is already used by sensor.mmgg_wi11_dc7d_filter_left_time - ignoring sensor.mmgg_wi11_dc7d_filter_left_time
