### ISSUE TITLE
小爱静默执行仍然回答指令。。。。

### ISSUE THREAD

**Issue by Tao173** [al-one/hass-xiaomi-miot#180]
如题，小爱play，功能tts正常，执行命令正常，但是回复执行结果（看看设备状态吧），不能静默执行，服务已经确认打开静默选项，第一次可以静默，之后的操作都会回复。

**Comment by al-one** [comment]
如果是通过HA开发者工具执行的语音命令，在界面勾选并打开`execute`和`silent`后，建议切换到yaml模式再执行，我发现HA通过界面执行服务时，部分选中的开关会不生效。
```yaml
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaoai_entity_id
  text: 开灯
  execute: true
  silent: true # 需要静默执行请确保silent为true
```
