### ISSUE TITLE
dmaker.fan.p28长期以来大量制造错误日志

### ISSUE THREAD

**Issue by will-huang9531** [al-one/hass-xiaomi-miot#1800]
### Device model / 设备型号

dmaker.fan.p28

### Component version / 插件版本

0.7.17

### HA core version / HA版本

2023.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

“米家智能直流变频循环扇落地式”，每天都会制造大量的错误日志（error log），我有数台此循环扇均出现此情况，恳请阿龙大佬修复 @al-one 

### Entity attributes / 实体属性

```yaml
preset_modes: Straight Wind, Natural Wind, Smart, Sleep
oscillating: false
percentage: 35
percentage_step: 1
preset_mode: Straight Wind
model: dmaker.fan.p28
lan_ip: 192.168.50.59
mac_address: 64:9E:31:33:DE:49
entity_class: MiotFanEntity
home_room: 苏州-石湖天玺 书房
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p28:1
fan.on: true
fan.fan_level: 2
fan.mode: 0
fan.horizontal_swing: false
horizontal_swing_included_angle-2-5: 120
fan.vertical_swing: false
vertical_swing_included_angle-2-8: 90
dm_service.speed_level: 35
dm_service.swing_all: false
dm_service.off_to_center: true
off_delay_time: 0
environment.temperature: 26.2
environment.relative_humidity: 59
physical_controls_locked: false
alarm: false
indicator_light.on: true
state_updater: lan
sub_entities: fan-2.horizontal_swing-4, fan-2.vertical_swing-7, alarm-5.alarm-1, off_delay_time-3.off_delay_time-1, dm_service-8.swing_updown_manual-2-0, dm_service-8.swing_updown_manual-2-1, dm_service-8.swing_updown_manual-2-2, dm_service-8.swing_lr_manual-3-0, dm_service-8.swing_lr_manual-3-1, dm_service-8.swing_lr_manual-3-2, dm_service-8.back_to_center-9, fan-2.horizontal_swing_included_angle-5, fan-2.vertical_swing_included_angle-8, environment-9.temperature-1, environment-9.relative_humidity-2, physical_controls_locked-7.physical_controls_locked-1, indicator_light-4
dm_service.back_to_center: true
dm_service.swing_lr_manual: 2
friendly_name: 书房电风扇 Fan
supported_features: 11
```

### Home Assistant Logs / 系统日志

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:698
First occurred: 00:21:19 (17 occurrences)
Last logged: 04:26:49

Update for fan.dmaker_p28_de49_fan fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1414, in async_update
    results = await self.hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 702, in get_properties_for_mapping
    return self.get_properties(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str
