### ISSUE TITLE
Desiccant value 0 is always displayed

### ISSUE THREAD

**Issue by alex2beard** [al-one/hass-xiaomi-miot#1807]
### Device model / 设备型号

xiaomi.feeder.pi2001

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.7.1

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Data on the remaining life of the dryer (desiccant) is not displayed. The value 0 is always displayed.
```
desiccant.desiccant_left_level: 0
desiccant.desiccant_left_time: 0
```

### Entity attributes / 实体属性

```yaml
friendly_name: Xiaomi Smart Pet Feeder 2 Pet Feeder Food Stuck Status
supported_features: 0
model: xiaomi.feeder.pi2001
lan_ip: 10.0.1.XX
mac_address: XX:XX:XX:XX:XX:XX
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:xiaomi-pi2001:1
state_property: pet_feeder.status
pet_feeder.fault: 0
pet_feeder.pet_food_left_level: 0
target_feeding_measure-2-7: 2
pet_feeder.status: 0
pet_feeder-2.food_out_status: 0
add_meal_notify_status-2-13: 0
pet_feeder-2.food_heap_status: 0
pet_feeder.eaten_food_measure: 0
pet_feeder-2.eaten_food_measure: 0
eaten_food_measure-2-22: 6
eaten_food_measure-2-23: 0
pet_feeder-2.status: 0
pet_feeder-2.status-28: 0
pet_feeder-2.status-29: 50
pet_feeder-2.status-31: 0
pet_feeder-2.status-32: 0
feeder_schedule-5-1: "[1,04350301,18000301]"
add_meal_state-5-3: 1
plan_process_display-5-4: 0
food_intake_rate-5-5: 10
food_intake_state-5-6: 0
max_schcdule_num-5-7: 35
schedule_state-5-8: 1
add_meal_cycle-5-10: 12
food_out_progress-5-11: 100
compensate_switch-5-12: 1
prevent_accumulation-5-14: 1
schedule_progress-5-15: 50
add_meal_triggertime-5-16: 12
desiccant.desiccant_left_level: 0
desiccant.desiccant_left_time: 0
battery_level: 0
physical_controls_locked: false
physical_controls_locked.mode: 0
state_updater: lan
sub_entities:
  - battery-4.battery_level-1
  - physical_controls_locked-3.physical_controls_locked-1
pet_feeder.status_desc: Normal
```
