### ISSUE TITLE
小米电视状态未知，实体不全，控制缺失

### ISSUE THREAD

**Issue by shuaiger** [al-one/hass-xiaomi-miot#1808]
### Device model / 设备型号

xiaomi.tv.mih1

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.8.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

1、小米电视media_player.xiaomi_mih1_05e3_play_control，状态显示unknown，无法判断电视当前状态；
2、实体不全，如选择信号源，按论坛这个贴https://bbs.hassbian.com/forum.php?mod=redirect&goto=findpost&ptid=22208&pid=545494，添加代码后，可出现信号源select，希望修改一下。
3、play control keycodes那，只有一个power，点了是关机，没有开机选项。
4、play control app_current好像不全，这个”模拟电视 - com.xiaomi.mitv.tvplayer“没有。
谢谢！

### Entity attributes / 实体属性

```yaml
source_list: ATV, DTV, AV, HDMI 1, HDMI 2, HDMI 3
volume_level: 0.23
is_volume_muted: false
app_id: com.xiaomi.mitv.tvplayer
app_name: 模拟电视
source: HDMI 3
model: xiaomi.tv.mih1
lan_ip: 192.168.1.*
mac_address: ***
entity_class: MitvMediaPlayerEntity
home_room: 客厅
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-mih1:1
6095_state: true
speaker_mode.is_on: false
remote_control.state_playing: true
no_disturb: false
no_disturb.enable_time_period: 
speaker.volume: 23
speaker.mute: false
television.input_control: 6
television.sleep_mode: false
state_updater: cloud
capture: http://192.168.1.***
capture_token: *
app_current: 模拟电视 - com.xiaomi.mitv.tvplayer
app_page: com.xiaomi.mitv.tvplayer.ExternalSourceActivity
device_class: tv
entity_picture: **
friendly_name: *的小米电视 S Pro 75 Mini LED Play Control
supported_features: 20365
sub_entities: apps, keycodes, speaker_mode-8.is_on-1, speaker-4.volume-1, message_router-5.post-1
```
