### ISSUE TITLE
米家智能插座2（蓝牙网关版）间歇性无法连接

### ISSUE THREAD

**Issue by JerryLF7** [al-one/hass-xiaomi-miot#1809]
### Device model / 设备型号

chuangmi.plug.212a01

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.8.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

实体间歇性不可用，大概几十秒后自动恢复连接
已在路由器端设置静态IP
![image](https://github.com/user-attachments/assets/1c529389-3e50-4168-adf1-1716832c5984)

### Entity attributes / 实体属性

```yaml
model: chuangmi.plug.212a01
lan_ip: 192.168.5.130
entity_class: MiotSwitchEntity
miot_type: urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:3
switch.on: false
switch.temperature: 37
switch.working_time: 0
functions_enable.power_enable: true
functions_enable.over_power: 2500
imilab_timer.on_duration: 0
imilab_timer.off_duration: 0
imilab_timer.countdown: 0
imilab_timer.task_switch: false
imilab_timer.countdown_info: false
power_consumption: 100
electric_current-5-2: 5
power_consumption.voltage: 220
electric_power-5-6: 0
power_consumption.surge_power: 2500
indicator_light.on: true
state_updater: lan
power_cost_today: 41535
power_cost_month: 5355435
sub_entities: power_cost_today, power_cost_month, switch-2.temperature-6, power_consumption-5.electric_current-2, power_consumption-5.voltage-3, power_consumption-5.electric_power-6, power_consumption-5.surge_power-7, indicator_light-3
device_class: outlet
friendly_name: Desktop Switch
supported_features: 0
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.switch
来源: custom_components/xiaomi_miot/__init__.py:1432
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 2024年8月11日 14:28:06 (253 次总计出现)
上次记录: 09:22:09

Desktop(chuangmi.plug.212a01): Got MiioException while fetching the state: No response from the device, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'switch.temperature': {'siid': 2, 'piid': 6}, 'switch.working_time': {'siid': 2, 'piid': 7}, 'functions_enable.power_enable': {'siid': 7, 'piid': 1}, 'functions_enable.over_power': {'siid': 7, 'piid': 2}, 'imilab_timer.on_duration': {'siid': 4, 'piid': 1}, 'imilab_timer.off_duration': {'siid': 4, 'piid': 2}, 'imilab_timer.countdown': {'siid': 4, 'piid': 3}, 'imilab_timer.task_switch': {'siid': 4, 'piid': 4}, 'imilab_timer.countdown_info': {'siid': 4, 'piid': 5}, 'power_consumption': {'siid': 5, 'piid': 1}, 'electric_current-5-2': {'siid': 5, 'piid': 2}, 'power_consumption.voltage': {'siid': 5, 'piid': 3}, 'electric_power-5-6': {'siid': 5, 'piid': 6}, 'power_consumption.surge_power': {'siid': 5, 'piid': 7}, 'indicator_light.on': {'siid': 3, 'piid': 1}}, max_properties: 7/16
Desktop(chuangmi.plug.212a01): Got MiioException while fetching the state: Unable to discover the device 192.168.5.130, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'switch.temperature': {'siid': 2, 'piid': 6}, 'switch.working_time': {'siid': 2, 'piid': 7}, 'functions_enable.power_enable': {'siid': 7, 'piid': 1}, 'functions_enable.over_power': {'siid': 7, 'piid': 2}, 'imilab_timer.on_duration': {'siid': 4, 'piid': 1}, 'imilab_timer.off_duration': {'siid': 4, 'piid': 2}, 'imilab_timer.countdown': {'siid': 4, 'piid': 3}, 'imilab_timer.task_switch': {'siid': 4, 'piid': 4}, 'imilab_timer.countdown_info': {'siid': 4, 'piid': 5}, 'power_consumption': {'siid': 5, 'piid': 1}, 'electric_current-5-2': {'siid': 5, 'piid': 2}, 'power_consumption.voltage': {'siid': 5, 'piid': 3}, 'electric_power-5-6': {'siid': 5, 'piid': 6}, 'power_consumption.surge_power': {'siid': 5, 'piid': 7}, 'indicator_light.on': {'siid': 3, 'piid': 1}}, max_properties: 7/16
NUC(cuco.plug.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.5.131, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'switch.default_power_on_state': {'siid': 2, 'piid': 2}, 'switch.fault': {'siid': 2, 'piid': 3}, 'power_limit_ext.power_ext': {'siid': 15, 'piid': 1}, 'charge_prt_ext.power': {'siid': 14, 'piid': 1}, 'charge_prt_ext.protect_time': {'siid': 14, 'piid': 2}, 'on_off_count': {'siid': 12, 'piid': 1}, 'on_off_count.temperature': {'siid': 12, 'piid': 2}, 'over_use_ele_alert.on': {'siid': 10, 'piid': 1}, 'over_use_ele_alert.over_ele_day': {'siid': 10, 'piid': 2}, 'over_ele_month-10-3': {'siid': 10, 'piid': 3}, 'max_power_limit.on': {'siid': 9, 'piid': 1}, 'max_power_limit.power': {'siid': 9, 'piid': 2}, 'quick_countdown.on': {'siid': 8, 'piid': 1}, 'quick_countdown.duration': {'siid': 8, 'piid': 2}, 'quick_countdown.left_time': {'siid': 8, 'piid': 3}, 'cycle.status': {'siid': 5, 'piid': 1}, 'cycle.data_value': {'siid': 5, 'piid': 2}, 'charging_protection.on': {'siid': 4, 'piid': 1}, 'charging_protection.power': {'siid': 4, 'piid': 2}, 'protect_time-4-3': {'siid': 4, 'piid': 3}, 'indicator_light-3.mode': {'siid': 3, 'piid': 2}, 'indicator_light-3.start_time': {'siid': 3, 'piid': 3}, 'indicator_light-3.end_time': {'siid': 3, 'piid': 4}, 'indicator_light.on': {'siid': 13, 'piid': 1}, 'power_consumption': {'siid': 11, 'piid': 1}, 'electric_power-11-2': {'siid': 11, 'piid': 2}, 'physical_controls_locked': {'siid': 7, 'piid': 1}}, max_properties: 10/28
Water Heater(cuco.plug.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.5.133, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'switch.default_power_on_state': {'siid': 2, 'piid': 2}, 'switch.fault': {'siid': 2, 'piid': 3}, 'power_limit_ext.power_ext': {'siid': 15, 'piid': 1}, 'charge_prt_ext.power': {'siid': 14, 'piid': 1}, 'charge_prt_ext.protect_time': {'siid': 14, 'piid': 2}, 'on_off_count': {'siid': 12, 'piid': 1}, 'on_off_count.temperature': {'siid': 12, 'piid': 2}, 'over_use_ele_alert.on': {'siid': 10, 'piid': 1}, 'over_use_ele_alert.over_ele_day': {'siid': 10, 'piid': 2}, 'over_ele_month-10-3': {'siid': 10, 'piid': 3}, 'max_power_limit.on': {'siid': 9, 'piid': 1}, 'max_power_limit.power': {'siid': 9, 'piid': 2}, 'quick_countdown.on': {'siid': 8, 'piid': 1}, 'quick_countdown.duration': {'siid': 8, 'piid': 2}, 'quick_countdown.left_time': {'siid': 8, 'piid': 3}, 'cycle.status': {'siid': 5, 'piid': 1}, 'cycle.data_value': {'siid': 5, 'piid': 2}, 'charging_protection.on': {'siid': 4, 'piid': 1}, 'charging_protection.power': {'siid': 4, 'piid': 2}, 'protect_time-4-3': {'siid': 4, 'piid': 3}, 'indicator_light-3.mode': {'siid': 3, 'piid': 2}, 'indicator_light-3.start_time': {'siid': 3, 'piid': 3}, 'indicator_light-3.end_time': {'siid': 3, 'piid': 4}, 'indicator_light.on': {'siid': 13, 'piid': 1}, 'power_consumption': {'siid': 11, 'piid': 1}, 'electric_power-11-2': {'siid': 11, 'piid': 2}, 'physical_controls_locked': {'siid': 7, 'piid': 1}}, max_properties: 10/28
NAS(cuco.plug.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.5.132, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'switch.default_power_on_state': {'siid': 2, 'piid': 2}, 'switch.fault': {'siid': 2, 'piid': 3}, 'power_limit_ext.power_ext': {'siid': 15, 'piid': 1}, 'charge_prt_ext.power': {'siid': 14, 'piid': 1}, 'charge_prt_ext.protect_time': {'siid': 14, 'piid': 2}, 'on_off_count': {'siid': 12, 'piid': 1}, 'on_off_count.temperature': {'siid': 12, 'piid': 2}, 'over_use_ele_alert.on': {'siid': 10, 'piid': 1}, 'over_use_ele_alert.over_ele_day': {'siid': 10, 'piid': 2}, 'over_ele_month-10-3': {'siid': 10, 'piid': 3}, 'max_power_limit.on': {'siid': 9, 'piid': 1}, 'max_power_limit.power': {'siid': 9, 'piid': 2}, 'quick_countdown.on': {'siid': 8, 'piid': 1}, 'quick_countdown.duration': {'siid': 8, 'piid': 2}, 'quick_countdown.left_time': {'siid': 8, 'piid': 3}, 'cycle.status': {'siid': 5, 'piid': 1}, 'cycle.data_value': {'siid': 5, 'piid': 2}, 'charging_protection.on': {'siid': 4, 'piid': 1}, 'charging_protection.power': {'siid': 4, 'piid': 2}, 'protect_time-4-3': {'siid': 4, 'piid': 3}, 'indicator_light-3.mode': {'siid': 3, 'piid': 2}, 'indicator_light-3.start_time': {'siid': 3, 'piid': 3}, 'indicator_light-3.end_time': {'siid': 3, 'piid': 4}, 'indicator_light.on': {'siid': 13, 'piid': 1}, 'power_consumption': {'siid': 11, 'piid': 1}, 'electric_power-11-2': {'siid': 11, 'piid': 2}, 'physical_controls_locked': {'siid': 7, 'piid': 1}}, max_properties: 10/28

---
此错误来自自定义集成。

日志记录器: miio.miioprotocol
来源: custom_components/xiaomi_miot/__init__.py:695
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 2024年8月11日 14:28:06 (171 次总计出现)
上次记录: 09:22:09

Got error when receiving: timed out
