### ISSUE TITLE
米家空调指示灯亮度多余

### ISSUE THREAD

**Issue by firedevel** [al-one/hass-xiaomi-miot#1814]
### Device model / 设备型号

xiaomi.airc.rr3r00

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2023.11.2

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

空调指示灯无亮度调整功能，可集成却有亮度选项

### Entity attributes / 实体属性

```yaml
supported_color_modes: brightness
color_mode: brightness
brightness: 69
indicator_light.on: true
indicator_light.brightness: 27
friendly_name: 空调指示灯
supported_features: 0
```

### Home Assistant Logs / 系统日志

无有关日志
