### ISSUE TITLE
空调伴侣Pro无法添加空调状态开关按钮

### ISSUE THREAD

**Issue by HenryRou** [al-one/hass-xiaomi-miot#1816]
### Device model / 设备型号

lumi.acparter.mcn04

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.8.1

### Integrated mode / 集成方式

Token

### The problem / 问题详情

空调伴侣Pro参考 #908 创建一个air_conditioner.on的开关，在编辑Configuration.yaml后按照添加开关流程重载xiaomi_miot_auto的yaml配置以及重启ha都没有出现空调状态开关的entity，但在同样操作后，另一个小米空调伴侣2lumi.acparter.mcn02则可以生成开关
Configuration.yaml配置如下

(井号) Loads default set of integrations. Do not remove.
default_config:

(井号) Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

xiaomi_miot:
  device_customizes:
    lumi.acpartner.mcn04:
      switch_properties: air_conditioner.on

### Entity attributes / 实体属性

```yaml
实体:climate.lumi_mcn04_58bc_air_conditioner
hvac_modes:
  - auto
  - cool
  - heat
  - dry
  - fan_only
  - "off"
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
swing_modes:
  - "off"
  - vertical
current_temperature: 29.6
temperature: 27
fan_mode: auto
hvac_action: "off"
swing_mode: "off"
model: lumi.acpartner.mcn04
lan_ip: *.*.*.*
mac_address: ****
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:air-condition-outlet:0000A045:lumi-mcn04:1
air_conditioner.on: false
air_conditioner.mode: 2
air_conditioner.fault: 0
target_temperature-3-4: 27
indicator_light: 1
indicator_light.effective_time: 1376277
ac_function.brand_id: 202
ac_function.remote_id: 4646
ac_function.ac_mode: 1
ac_function.ac_type: 2
ac_function.ac_ctrl_range: >-
  {"models":[{"mode":0,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1,2,3,4,5],"type":2},{"mode":1,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1,2,3,4,5],"type":2},{"mode":2,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1,2,3,4,5],"type":2},{"mode":4,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1,2,3,4,5],"type":2}]}
ac_function.ac_state: P1_M2_T27_S0_D1
ac_function.quick_cool_enable: false
ac_function.quick_cool_time: 10
ac_function.quick_cool_status: 0
ac_function.sleep_cfg: "[0]"
ac_function.sleep_status: 0
power_consumption: 438.686
electric_power-7-2: 0
power_consumption-7-3: 0
electric_power-7-4: 0
fan_control.fan_level: 0
fan_control.vertical_swing: false
state_updater: lan
sub_entities:
  - ac_function-8.quick_cool_enable-8
  - indicator_light-9.indicator_light-1
  - ac_function-8.ac_mode-4
  - power_consumption-7.electric_power-2
  - power_consumption-7.electric_power-4
friendly_name: ***
supported_features: 425
```
