### ISSUE TITLE
升级到0.4.2后，水侵报警设备状态不能获取

### ISSUE THREAD

**Issue by ideatechfr** [al-one/hass-xiaomi-miot#182]
model: [lumi.flood.bmcn01](https://home.miot-spec.com/s/lumi.flood.bmcn01)
lan_ip: 
mac_address: 54:EF:44:E3:BC:C8
firmware_version: 1.1.1_0016
hardware_version: 
entity_class: LumiBinarySensorEntity
miot_type: urn:miot-spec-v2:device:submersion-sensor:0000A024:lumi-bmcn01:1
state_property: submersion_state-2-1
submersion_state-2-1: null
battery.battery_level: 100
state_updater: cloud
sub_entities: battery-3.battery_level-1
friendly_name: 厨房水浸 Submersion Sensor
supported_features: 0
device_class: moisture

![截屏2021-09-14 10 11 42](https://user-images.githubusercontent.com/37808758/133220899-128f91b1-18b2-4b56-bc8e-e68f672bed17.png)

**Comment by al-one** [comment]
请检查下米家APP中该设备的最后一条日志是否是3天之前的，建议给该实体[添加自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)：
```yaml
binary_sensor.lumi_bmcn01_entity_id:
  time_start_offset: -8640000 # 获取进100天的数据
```

**Comment by ideatechfr** [comment]
米家app里的日志是空的，所以不确定是什么时间的。刚刚在配置里添加自定义属性后也不能获取到设备状态

**Comment by al-one** [comment]
请执行HA服务[`xiaomi_miot.get_device_data`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.get_device_data)，并从HA左边通知中获取结果：
```yaml
service: xiaomi_miot.get_device_data
data:
  entity_id: binary_sensor.lumi_bmcn01_entity_id
  type: prop
  key: device_log
  time_start: 0
```

**Comment by ideatechfr** [comment]
获取到结果：
`{'code': 0, 'message': 'ok', 'result': []}`

**Comment by al-one** [comment]
该设备所属的网关方便通过米家共享一下给我吗？ID：143050915

**Comment by ideatechfr** [comment]
多模网关已经共享给你了

**Comment by al-one** [comment]
由于子设备没法单独共享，只能连网关一起共享。不过虽然网关是有了，但是看不到子设备。

**Comment by ideatechfr** [comment]
我共享设备给你，也麻烦一起看看温湿度的更新 
感谢！@

**Comment by al-one** [comment]
[小米水浸卫士](https://home.miot-spec.com/s/lumi.flood.bmcn01) 已修复，请更新到master。

**Comment by ideatechfr** [comment]
感谢！请问自定义属性是否要保留，如果保留的话这个属性条件这样写是否正确

> # xiaomi miot
xiaomi_miot: # 此行在配置文件中只能出现一次
  device_customizes:
    binary_sensor.lumi_bmcn01_entity_id:
      time_start_offset: -8640000 # 获取进100天的数据# 注意本行前面有六个空格

**Comment by al-one** [comment]
这个写法的是错的！

https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774 教程中的方法1、2是以实体ID为目标，配置的自定义属性只对目标实体有效。而方法3是以设备型号为目标，配置的自定义属性对本插件下所有指定型号有效。

`device_customizes`属于方法3的配置项，不应以实体ID作为目标，格式如下：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    lumi.flood.bmcn01:
      time_start_offset​: ​-8640000
```
