### ISSUE TITLE
蓝盒子智能床缺少实体

### ISSUE THREAD

**Issue by zhuzhuani** [al-one/hass-xiaomi-miot#1836]
### Device model / 设备型号

[iot.bed.upone](https://home.miot-spec.com/s/iot.bed.upone)

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.8.2

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

目前只有一个BLUEBOX electric bed Bed Device Fault实体
从https://home.miot-spec.com/spec/iot.bed.upone 这个网站来看 应该还有个mode 然后在custom中应该有些别的东西,比如灯 还有控制升降的
![PixPin_2024-08-26_10-00-44](https://github.com/user-attachments/assets/46760bd2-da73-4a0a-8840-765db968c112)

![PixPin_2024-08-26_10-00-00](https://github.com/user-attachments/assets/189c58b1-56a2-434b-9620-cc6b5af20750)

### Entity attributes / 实体属性

```yaml
model: iot.bed.upone
lan_ip: 10.0.0.60
mac_address: C4:93:BB:EA:84:32
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:bed:0000A06A:iot-upone:1
state_property: bed.fault
bed.fault: 0
bed.mode: 5
custom.light_conrtol: 0
custom.light_bright: 0
custom.memory_one_state: 0
custom.memory_two_state: 0
state_updater: cloud
bed.fault_desc: No Faults
friendly_name: BLUEBOX electric bed Bed Device Fault
supported_features: 0
```
