### ISSUE TITLE
米家空调伴侣2 更新后无法正确显示空调信息

### ISSUE THREAD

**Issue by xiakeng** [al-one/hass-xiaomi-miot#1837]
### Device model / 设备型号

lumi.acpartner.mcn02

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.8.3

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

已经尝试过重现添加integration

目前空调状态为制冷27度，但是仪表盘显示的不对
![image](https://github.com/user-attachments/assets/c961f85f-933e-48e2-8d42-6e9aaebf4343)

### Entity attributes / 实体属性

```yaml
hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: auto, low, medium, high
swing_modes: off, vertical
current_temperature: null
temperature: 27
fan_mode: auto
hvac_action: fan
swing_mode: off
model: lumi.acpartner.mcn02
lan_ip: 192.168.10.23
mac_address: 7C:C2:94:44:C2:26
entity_class: MiotClimateEntity
home_room: 我的家庭 客厅
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:lumi-mcn02:1
air_conditioner.on: true
air_conditioner.mode: 4
target_temperature-2-3: 27
electric_power-5-1: 1238.76
match_state-4-1: 0
ac_work_mode-4-2: 0
ac_state-4-3: P0_M0_T27_S0_D2
fan_control.fan_level: 0
fan_control.vertical_swing: false
state_updater: cloud
power_cost_today: 11044
power_cost_month: 452257
friendly_name: 客厅空调 Air Conditioner
supported_features: 425
sub_entities: power_cost_today, power_cost_month, power_consumption-5.electric_power-1
```

### Home Assistant Logs / 系统日志

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:370
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 4:55:34 PM (6 occurrences)
Last logged: 4:55:34 PM

Entity xiaomi_miot.lumi_mcn02_a8de_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Entity xiaomi_miot.lumi_mcn02_a8de_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) implements HVACMode(s): auto, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Entity xiaomi_miot.lumi_mcn02_c226_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Entity xiaomi_miot.lumi_mcn02_c226_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Entity xiaomi_miot.lumi_mcn02_c226_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) implements HVACMode(s): auto, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
