### ISSUE TITLE
No home map from the Xiaomi app available in Home Assistant

### ISSUE THREAD

**Issue by Ark88888** [al-one/hass-xiaomi-miot#1844]
### Device model / 设备型号

Xiaomi Robot Vacuum X10

### HA core version / HA版本

2024.8.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

All sensors and functionalities integrated seamlessly, but I can't set cleaning for a specific room because it seems that the map hasn't been downloaded from the Xiaomi app. How can I resolve this? (Model: Xiaomi Robot Vacuum X10 recognized by MIOT as an Dreame.vacuum.r2209)

### Entity attributes / 实体属性

```yaml
fan_speed_list:
  - Silent
  - Basic
  - Strong
  - Full Speed
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: Strong
model: dreame.vacuum.r2209
lan_ip: 192.168.33.6
mac_address: 8C:D0:B2:5F:C0:72
entity_class: MiotVacuumEntity
home_room: Dom 8255858181 Biuro
exclude_miot_services:
  - consumable
  - annoy
  - remote
  - time
exclude_miot_properties:
  - delete_timer
  - clean_info
  - map_view
  - frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-r2209:1
vacuum.status: 13
vacuum.fault: 0
vacuum.mode: 2
collect_dust.auto_collect: 1
collect_dust.clean_times: 1
collect_dust.dust_enable: 1
clean_logs.first_clean_time: 1718618277
clean_logs.total_clean_time: 1473
clean_logs.total_clean_times: 44
clean_logs.total_clean_area: 1189
audio.volume: 75
audio.voice_packet_id: EN
audio.voice_change_state: "{\\\"id\\\":\\\"\\\",\\\"state\\\":\\\"idle\\\",\\\"progress\\\":0}"
map.mult_map_info: >-
  {"object_name":"8255858181/1064746424/9","md5":"9fdf513d6dd6e8bb63ea3a05c5a2cbbe"}
do_not_disturb.enable: true
do_not_disturb.start_time: "22:00"
do_not_disturb.end_time: "08:00"
vacuum_extend.work_mode: 14
vacuum_extend.cleaning_time: 0
vacuum_extend.cleaning_area: 0
vacuum_extend.cleaning_mode: 2
vacuum_extend.mop_mode: 3
vacuum_extend.waterbox_status: 1
vacuum_extend.task_status: 0
break_point_restart-4-11: 1
vacuum_extend.carpet_press: 0
vacuum_extend.serial_number: 40198/BFACWF4QT00008
vacuum_extend.clean_rags_tip: 0
vacuum_extend.keep_sweeper_time: 0
vacuum_extend.faults: "0"
vacuum_extend.nation_matched: unknown
vacuum_extend.relocation_status: 0
filter.filter_life_level: 83
filter.filter_left_time: 125
brush_left_time-10-1: 175
brush_life_level-10-2: 87
brush_cleaner.brush_left_time: 275
brush_cleaner.brush_life_level: 91
battery.charging_state: 1
state_updater: lan
vacuum.status_desc: Charging Completed
sub_entities:
  - vacuum-2.status-1
  - filter-11.filter_life_level-1
  - filter-11.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-9.brush_left_time-1
  - brush_cleaner-9.brush_life_level-2
  - brush_cleaner-10.brush_left_time-1
  - brush_cleaner-10.brush_life_level-2
friendly_name: Xiaomi Robot Vacuum X10 Robot Cleaner
supported_features: 13048
```
