### ISSUE TITLE
空气净化器有多余的不可管理的实体

### ISSUE THREAD

**Issue by Necroneco** [al-one/hass-xiaomi-miot#1845]
### Device model / 设备型号

zhimi.airp.ua1

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.8.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![Snipaste_2024-09-04_14-03-46](https://github.com/user-attachments/assets/53220c53-1be8-42ca-9eb3-1e948887ecfd)

会多出4个不可管理的传感器，且正常的实体会有 `_2` 后缀

尝试删除 `custom_components/xiaomi_miot/core/device_customizes.py` 文件第 1905 行后一切正常

```diff
    '*.airpurifier.*': {
        'main_miot_services': 'air_purifier',
        'switch_properties': 'alarm.alarm,anion,uv',
-       'sensor_properties': 'relative_humidity,pm2_5_density,temperature,filter_life_level',
    },
```

请帮忙看一下是什么问题

### Entity attributes / 实体属性

```yaml
preset_modes: Auto, Sleep, Favorite, Manual
percentage: 100
percentage_step: 33
preset_mode: Auto
model: zhimi.airp.ua1
lan_ip: 10.1.0.120
mac_address: 68:AB:BC:69:2B:E5
entity_class: MiotFanEntity
home_room: 新高苑 家
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-ua1:3
air_purifier.on: true
air_purifier.fault: 0
air_purifier.mode: 0
air_purifier.fan_level: 3
air_purifier.plasma: true
air_purifier.uv: true
motor_rpm_current-9-1: 600
aqi_update_heartbeat-9-4: 300
screen_bright_level-9-12: 2
custom_service.favorite_square: 8~13,9~16,11~19,14~24,17~29,19~34,24~42,26~45,29~51,35~60,37~63,42~71,44~75,48~81,52~90
custom_service.hcho_sn: 2217-21
filter_time_debug-9-15: 157
lcd_firmware_version-9-16: 0
particle_abnormal_on-9-17: true
custom_service.hcho_standard: 2
air_purifier_favorite.fan_level: 14
screen.on: true
physical_controls_locked: false
alarm: false
filter.filter_life_level: 93
filter.filter_used_time: 2768
filter.filter_left_time: 32272
filter-4.filter_life_level: 90
filter-4.filter_used_time: 2768
filter-4.filter_left_time: 23512
filter-4.filter_life_level-11: 85
filter-4.filter_used_time-12: 2768
filter-4.filter_left_time-13: 14752
environment.relative_humidity: 57
environment.temperature: 28
environment.air_quality: 0
environment.pm2_5_density: 2
environment.pm10_density: 1
environment.hcho_density: 0.028
environment.pm2_5: 2
state_updater: lan
sub_entities: environment-3.relative_humidity-1, environment-3.temperature-2, environment-3.pm2_5_density-4, filter-4.filter_life_level-1, filter-4.filter_life_level-8, filter-4.filter_life_level-11, air_purifier-2.on-1, air_purifier-2.uv-7, alarm-6.alarm-1, environment-3.air_quality-3, environment-3.pm10_density-5, environment-3.hcho_density-6, filter-4.filter_used_time-3, filter-4.filter_left_time-4, filter-4.filter_used_time-9, filter-4.filter_left_time-10, filter-4.filter_used_time-12, filter-4.filter_left_time-13, physical_controls_locked-8.physical_controls_locked-1
friendly_name: 米家全效空气净化器 Ultra Air Purifier
supported_features: 57
```
