### ISSUE TITLE
小米自然风pro空调缺少用电数据实体

### ISSUE THREAD

**Issue by YosenFree** [al-one/hass-xiaomi-miot#1846]
### Device model / 设备型号

[xiaomi.airc.r34r00](https://home.miot-spec.com/s/xiaomi.airc.r34r00)

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.7.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米的自然风pro空调，接入后没有功率，日用电，月用电等实体数据，只有截图里这些实体。恳求大佬添加！！！
![image](https://github.com/user-attachments/assets/b2e78fcc-77d9-4352-935c-ec1448085ef9)

### Entity attributes / 实体属性

```yaml
hvac_modes: cool, heat, dry, fan_only, auto, off
min_temp: 16
max_temp: 31
target_temp_step: 0.5
min_humidity: 0
max_humidity: 100
fan_modes: auto, level1, level2, level3, level4, level5, level6, level7, level8
swing_modes: off, vertical, horizontal, both
current_temperature: 31
temperature: 28
current_humidity: 59
humidity: 0
fan_mode: level1
hvac_action: off
swing_mode: horizontal
model: xiaomi.airc.r34r00
lan_ip: 192.168.2.237
mac_address: E8:4A:54:8C:DB:66
entity_class: MiotClimateEntity
home_room: xxx家 书房
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-r34r00:2
air_conditioner.on: false
air_conditioner.mode: 2
air_conditioner.fault: 0
target_temperature-2-4: 28
air_conditioner.eco: false
air_conditioner.heater: false
air_conditioner.dryer: true
air_conditioner.sleep_mode: false
air_conditioner.soft_wind: false
air_conditioner.target_humidity: 0
air_conditioner.favorite_on: false
air_conditioner.favorite_type: 0
like_mode.user_defined_mode: 0
like_mode.recommend_mode: 0
like_mode.always_favorite_on: false
single_smart_scene.auto_cooling: false,28.0,26.0
automatic_heating-16-2: false,24.0,26.0
single_smart_scene.auto_dry: false,70,55
run_dark_sleep-16-10: false
flag_bit.fault_value: 4
machine_state.indoor_pipe_temp: 28.6
machine_state.indoor_fan_speed: 0
real_heater_switch-12-4: 0
realindoor_fan_lever-12-5: 0
lightactivated_level-12-6: 0
machine_state.outdoor_temp: 28
machine_state.outdoor_pipe_temp: 25
outdoor_exhaust_temp-12-9: 40.6
machine_state.outdoor_fan_lever: 0
compressor_frequency-12-11: 0
fourway_valve_switch-12-12: false
outdoor_mach_current-12-13: 0
outdoor_mach_voltage-12-14: 233
machine_state.expansion_valve: 480
longitude_latitude-12-16: 0
machine_state.version: 0009,V0021,V0006,V0015,0009,V0021,V0006,V0015
external_serial_no-12-23: 60469/KG34A4710027
machine_state.bk_serial_no: 00000/00IDU0000000,KBE3S/410C46S00034
machine_state.module_temp: 41.8
enhance.fan_percent: 1
enhance.timer: 0
enhance.sleep_diy: false
enhance.secondpart_of_hswing: false
enhance.humidity_range: 40-70
enhance.tp_and_humidity: 30.5
enhance.room_size: 2
enhance.maxfan_select: false
enhance.room_select: false
maintenance.clean: 0,100,1,1
maintenance.examine: none
maintenance.running_duration: 12.7
maintenance.clean_process: 55
electricity.time_count: 489
electricity.electricity_info: false
filter-22.filter_life_level: 101
filter.filter_life_level: 101
power_consumption: 4.77
indicator_light.on: true
indicator_light.brightness: 0
alarm: true
environment.temperature: 31
environment.relative_humidity: 59
fan_control.fan_level: 1
fan_control.horizontal_swing: true
fan_control.vertical_swing: false
vertical_swing_included_angle-3-6: 0
state_updater: lan
sub_entities: environment-4.temperature-7, environment-4.relative_humidity-9, filter-21.filter_life_level-1, filter-22.filter_life_level-1, indicator_light-6, air_conditioner-2.eco-7, air_conditioner-2.heater-9, air_conditioner-2.dryer-10, air_conditioner-2.sleep_mode-11, air_conditioner-2.soft_wind-12, air_conditioner-2.favorite_on-19
friendly_name: 米家空调 自然风Pro Air Conditioner
supported_features: 429
```
