### ISSUE TITLE
小米oled 电视 interval 属性设定无效

### ISSUE THREAD

**Issue by kongxrc2023** [al-one/hass-xiaomi-miot#1850]
### Device model / 设备型号

xiaomi.tv.oledh1

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.8.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

通过修改configuration.yaml 和customize.yaml的方法对设备xiaomi.tv.oledh1的实体media_player.xiaomi_oledh1_c528_play_control和select.xiaomi_oledh1_c528_app_current增加了修改轮询时间的参数interval,并且设定interval=1 ，通过测试发现，设定完成重启HA后，开发者工具→状态里面这两个实体的interval参数添加成功，但是实际测试轮询时间为20s（修改前为30s）。

### Entity attributes / 实体属性

```yaml
source_list: ATV, DTV, AV, HDMI 1, HDMI 2, HDMI 3
volume_level: 0.35
is_volume_muted: false
app_id: com.mygithub0.tvbox0.osdX
app_name: xxx
source: ATV
model: xiaomi.tv.oledh1
lan_ip: 192.168.31.54
mac_address: 40:24:b2:29:c5:28
entity_class: MitvMediaPlayerEntity
home_room: xxx
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-oledh1:1
6095_state: false
speaker_mode.is_on: false
speaker.volume: 35
speaker.mute: false
television.input_control: 1
state_updater: cloud
capture: http://192.168.31.54:6095/request?action=getResource&name=screenCapture&timestamp=1725582571717&opaque=93f533b56ae6ee39e6d9e2acaacdb4001267cb76
capture_token: n5h2YNhC4fknoV8i
app_current: xxx - com.mygithub0.tvbox0.osdX
app_page: com.github.tvbox.osc.ui.activity.LivePlayActivity
sub_entities: apps, keycodes, speaker_mode-8.is_on-1, speaker-4.volume-1, message_router-5.post-1
television.input_control.error: -704042011 Device offline
device_class: tv
entity_picture: /api/media_player_proxy/media_player.xiaomi_oledh1_c528_play_control?token=3980c91f5334ea2c5ff4cd69e58cd0ad71725bfe166f5d54f9fe927802fc359f&cache=e3636ceb9da8fa4a
friendly_name: xxx的电视 Play Control
supported_features: 20365
interval_seconds: 1


options: 云视听小电视 - com.xiaodianshi.tv.yst, Marine Aquarium PRO - com.acrodea.fish, Magic iPerf - com.nextdoordeveloper.miperf.miperf, 相册 - com.mitv.gallery, xxx - com.mygithub0.tvbox0.osdX, 天气 - com.xiaomi.tweather, 超清动态壁纸TV版 - com.dangbei.screensaver.sights, 当贝播放器 - com.dangbei.lerad.videoposter, 当贝桌面 - com.dangbei.tvlauncher, 悠享直播 - com.audiovisual.live, 设置 - com.xiaomi.mitv.settings, 当贝市场 - com.dangbeimarket, 电视管家 - com.xiaomi.mitv.tvmanager, OK影视 - com.fongmi.android.tv, 幻彩随影 - com.xiaomi.mitv.light, 屏幕检测专家 - com.hw.screentest, 日历 - com.xiaomi.mitv.calendar, 小爱同学 - com.xiaomi.voicecontrol, 小白文件管理器 - com.xiaobaifile.tv, KTV - com.lycoo.lancy.ktv, 时尚画报 - com.xiaomi.tv.gallery, xxx - com.aesq.zb, LM Ultimate - com.wolf.lmu, 玩机手册 - com.xiaomi.mitv.handbook, 定时提醒 - com.mitv.alarmcenter, 视频头条 - com.duokan.videodaily, YouTube - com.amazon.firetv.youtube, 无线投屏 - com.xiaomi.mitv.smartshare
entity_class: SelectSubEntity
parent_entity_id: media_player.xiaomi_oledh1_c528_play_control
app_current: xxx - com.mygithub0.tvbox0.osdX
friendly_name: xxx Play Control app_current
supported_features: 0
interval_seconds: 1
```
