### ISSUE TITLE
可以为小米空调伴侣增加播放铃声的功能么

### ISSUE THREAD

**Issue by zcr268** [al-one/hass-xiaomi-miot#1854]
### Device model / 设备型号

lumi.acpartner.v2

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.9.1

### Integrated mode / 集成方式

Automatic (自动模式)

### Entity attributes / 实体属性

```yaml
hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 17
max_temp: 30
target_temp_step: 1
fan_modes: auto, low, medium, high
swing_modes: off, vertical
current_temperature: null
temperature: 26
fan_mode: high
hvac_action: off
swing_mode: off
model: lumi.acpartner.v2
lan_ip: 192.168.2.22
mac_address: 7C:49:EB:AD:60:B0
entity_class: MiotClimateEntity
home_room: 北京家 客厅
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:lumi-v2:1
air_conditioner.on: false
air_conditioner.mode: 1
target_temperature-2-3: 26
fan_control.fan_level: 3
fan_control.vertical_swing: false
state_updater: lan
electric_power: 0.5
power_cost_today: 0
power_cost_month: 0
sub_entities: electric_power, power_cost_today, power_cost_month
friendly_name: 空调插座 Air Conditioner
supported_features: 425
```
