### ISSUE TITLE
Mi Vacuum 1S (roborock.vacuum.m1s) don't react on segment cleaning buttons provided by integration

### ISSUE THREAD

**Issue by Sirse** [al-one/hass-xiaomi-miot#1855]
Mi Vacuum 1S (roborock.vacuum.m1s) don't react on segment cleaning buttons provided by integration 

custom_components.xiaomi_miot.vacuum
custom_components/xiaomi_miot/__init__.py:1030

Mi Vacuum 1S(roborock.vacuum.m1s): Send miio command: app_segment_clean([{'segments': [17], 'repeat': 1}]) failed: {'code': -10000, 'message': 'data for segment is not a number'}
Mi Vacuum 1S(roborock.vacuum.m1s): Send miio command: app_segment_clean([{'segments': [20], 'repeat': 1}]) failed: {'code': -10000, 'message': 'data for segment is not a number'}

**Comment by Sirse** [comment]
> Hello @Sirse,
> 
> did you manage to solve it?
> 
> Thanks

Unfortunately, no

**Comment by al-one** [comment]
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: vacuum.viomi_m1s_xxxx_robot_cleaner
  method: app_segment_clean
  params: [17]
```

Does it wotk ?
