### ISSUE TITLE
camera.chuangmi_039a04_94a7_camera_control can't get the stream video

### ISSUE THREAD

**Issue by Cocosms** [al-one/hass-xiaomi-miot#1866]
### Device model / 设备型号

camera.chuangmi_039a04_94a7

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.9.2

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

Keep getting the error:
Error requesting stream: camera.chuangmi_039a04_94a7_camera_control does not support play stream service

Have tried to enable home surveillance, but still can't get the image.

Also, below is my customization.yaml config:
camera.chuangmi_039a04_94a7_camera_control:
  miot_cloud: true
  video_attribute: 2
  keep_streaming: true
  use_motion_stream: true
  sub_motion_stream: true 
  motion_stream_slice: -1

### Entity attributes / 实体属性

```yaml
access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
model_name: chuangmi.camera.039a04
brand: chuangmi
frontend_stream_type: hls
model: chuangmi.camera.039a04
lan_ip: 192.168.0.103
mac_address: 78:DF:72:25:94:A7
entity_class: MiotCameraEntity
home_room: Белый дом Прихожая
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-039a04:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 2
camera_control.motion_tracking: false
camera_control.local_storage: true
imi_alarm.alarm_clocks: 
imi_alarm.alarm_clocks_key: 
imi_alarm.baby_wake_switch: false
imi_alarm.baby_sleep_area: 
imi_alarm.babycry_switch: false
stream_status-10-9: 1
stream_status-9-9: 1
motion_detection: true
motion_detection.alarm_interval: 10
detection_sensitivity-5-3: 0
motion_detection_start_time-5-4: 00:00:00
motion_detection_end_time-5-5: 23:59:00
memory_card_management.status: 1
storage_total_space-4-2: 1024
storage_free_space-4-3: 0
storage_used_space-4-4: 1024
indicator_light.on: true
state_updater: cloud
sub_entities: memory_card_management-4.status-1, memory_card_management-4.storage_free_space-3, memory_card_management-4.storage_used_space-4, camera_control-2.on-1, camera_control-2.wdr_mode-5, camera_control-2.glimmer_full_color-6, camera_control-2.motion_tracking-8, indicator_light-3.on-1, motion_detection-5.motion_detection-1, camera_control-2.image_rollover-2, motion_detection-5.alarm_interval-2, camera_control-2.night_shot-3, camera_control-2.recording_mode-7, motion_detection-5.detection_sensitivity-3, indicator_light-3, motion_event
entity_picture: /api/camera_proxy/camera.chuangmi_039a04_94a7_camera_control?token=xxxxxxxxxxxxxxxxxxxxxxxx
friendly_name: Умная камера Camera Control
supported_features: 3
miot_cloud: true
video_attribute: 2
keep_streaming: true
use_motion_stream: true
sub_motion_stream: true
motion_stream_slice: -1
```

### Home Assistant Logs / 系统日志

Регистратор: homeassistant.components.camera
Источник: components/camera/__init__.py:892
интеграция: Камера (документация, проблемы)
Первое сообщение: 17 сентября 2024 г. в 22:48:38 (5 сообщений)
Последнее сообщение: 02:01:07

Error requesting stream: camera.chuangmi_039a04_94a7_camera_control does not support play stream service
