### ISSUE TITLE
Adjusting Screen/Light options in Mi Air Purifier 3C

### ISSUE THREAD

**Issue by Kalindro** [al-one/hass-xiaomi-miot#1868]
### Device model / 设备型号

zhimi.airp.mb4a

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.9.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

How can I edit screen brightness? I see it's in entity attributes and miot-spec, but I see no such entity it is in.
Is there any way to modify it just as any other entity?
https://home.miot-spec.com/spec/zhimi.airp.mb4a
![Screenshot 2024-09-18 202353](https://github.com/user-attachments/assets/9d272eeb-82b4-4276-99f4-e38e60b9a742)
![image](https://github.com/user-attachments/assets/2cd57885-e970-4b1b-bc3d-3b1207cd47b3)

### Entity attributes / 实体属性

```yaml
preset_modes: Auto, Sleep, Favorite
preset_mode: Sleep
model: zhimi.airp.mb4a
lan_ip: 192.168.10.12
mac_address: 58:B6:23:72:AE:FE
entity_class: MiotFanEntity
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb4a:1
air_purifier.on: true
air_purifier.fault: null
air_purifier.mode: 1
custom_service.moto_speed_rpm: 388
custom_service.miio_lib_version: Jerry Yang . Ver: 1.9.6. Date: Jul 18 2021. Time: 11:48:10.
custom_service.favorite_speed: 2000
aqi_updata_heartbeat-9-4: 0
physical_controls_locked: false
screen.brightness: 3
alarm: true
filter.filter_life_level: 2
filter.filter_used_time: 3441
environment.pm2_5_density: 11
state_updater: lan
sub_entities: environment-3.pm2_5_density-4, filter-4.filter_life_level-1, air_purifier-2.on-1, alarm-6.alarm-1, custom_service-9.favorite_speed-3, filter-4.filter_used_time-3, physical_controls_locked-8.physical_controls_locked-1
friendly_name: Mi Air Purifier 3C Air Purifier
supported_features: 56
```
