### ISSUE TITLE
請問有對SCISHARE 咖啡機的支援嗎？

### ISSUE THREAD

**Issue by Godfrey548** [al-one/hass-xiaomi-miot#187]
現時只可以把他加入到HA當中，但未能控制他制作咖啡，謝謝你！

**Comment by al-one** [comment]
设备：[心想智能胶囊咖啡机](https://home.miot-spec.com/s/scishare.coffee.s1102)
该设备的[miot-spec](https://home.miot-spec.com/spec/scishare.coffee.s1102)规格中仅提供了状态属性及开关属性。如想控制制作咖啡，需要你自行抓取设备miio方法及参数，通过HA服务[`xiaomi_miot.send_command`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)执行：
```yaml
service: xiaomi_miot.send_command
data:
  method: miio_method
  params:
    - params
```
