### ISSUE TITLE
Room cleaning settings for ijai.vacuum.v18

### ISSUE THREAD

**Issue by dirkackermann** [al-one/hass-xiaomi-miot#1872]
### Device model / 设备型号

ijai.vacuum.v18

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.9.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I am unable to perform room cleaning with that model. I can do start normal cleaning without specific rooms without issues via service calls. 

Based on the specs of the vacuum in the link [here](https://home.miot-spec.com/spec/ijai.vacuum.v18), the preferred settings seemed to be SIID: 7, AIID: 3, and then followed by the room ids in params or alternatively SIID: 2, AIID: 7, following again by the room ids in params. 

On issue is that I do not have the rooms IDs but I tried countless numbers and none work. The vacuum is basically doing nothing. 
I tried to get the room ids via the modified MiHome App from Vevs but somehow when I log in, it does not show my devices which are linked to the account (app is too old?). Xiaomi vacuum map extractor unfortunately does not work with this model. 

I like the vacuum but without automating room cleaning, it is not very useful. Appreciate any help. Thanks. 

### Entity attributes / 实体属性

```yaml
fan_speed_list:
  - Slient
  - Standard
  - Medium
  - Turbo
battery_level: 67
battery_icon: mdi:battery-charging-60
fan_speed: Medium
model: ijai.vacuum.v18
lan_ip: 192.168.0.12
mac_address: cc:b5:d1:d4:01:bc
entity_class: MiotVacuumEntity
home_room: My home Kitchen
exclude_miot_services:
  - order
exclude_miot_properties:
  - zone_points
  - restrict_points
  - target_point
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:ijai-v18:1
vacuum.status: 4
vacuum.fault: 2103
vacuum.mode: 0
vacuum.sweep_type: 0
vacuum.on: "[1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1]"
disturb.dnd_enable: 1
disturb.dnd_start_hour: 23
disturb.dnd_start_minute: 0
disturb.dnd_end_hour: 9
disturb.dnd_end_minute: 0
disturb.multi_prop_dnd: "[1,23,0,9,0]"
map.remember_state: 1
map.cur_map_id: 1722152130
map.map_num: 1
map.cur_cleaning_path: null
map.build_map: 0
map.has_new_map: 0
sweep.repeat_state: 0
sweep.door_state: 3
sweep.cloth_state: 0
sweep.suction_state: 2
sweep.water_state: 2
sweep.mop_route: 1
sweep.side_brush_life: 79
sweep.side_brush_hours: 143
sweep.main_brush_life: 89
sweep.main_brush_hours: 323
sweep.hypa_life: 79
sweep.hypa_hours: 143
sweep.mop_life: 92
sweep.mop_hours: 167
sweep.time_zone: -7200
sweep.cur_lang: en_US
sweep.cleaning_time: 57
sweep.cleaning_area: 39
sweep.dirt_recognize: 0
sweep.pet_recognize: 0
sweep.ai_recognize: 0
sweep.carpet_booster: 0
sweep.multi_prop_vacuum: >-
  [0,3,0,2,2,1,-7200,57,39.8,0,"en_US","396932SD2208A06549","zh_CN",3,-1,0,0,1,2,1]
sweep.tank_shake: 1
sweep.shake_shift: 2
sweep.map_encrypt: 1
alarm: false
alarm.volume: 0
state_updater: lan
vacuum.status_desc: Charging
sub_entities:
  - vacuum-2.status-1
  - sweep-7.side_brush_life-8
  - sweep-7.main_brush_life-10
  - sweep-7.hypa_life-12
  - sweep-7.mop_life-14
  - alarm-4.alarm-1
  - sweep-7.repeat_state-1
  - vacuum-2.mode-4
  - vacuum-2.sweep_type-8
  - sweep-7.water_state-6
  - battery-3.battery_level-1
miot_action_result:
  code: 0
miot_action_error: "1"
friendly_name: Mijia Robot Vacuum-Mop 3C Robot Cleaner
supported_features: 12539
```

**Comment by al-one** [comment]
Try:
```yaml
action: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_c107_f5b1_robot_cleaner
  siid: 10 # map
  aiid: 13 # get-map-room-list
  params:
    - 1722152130 # cur-map-id
```
