### ISSUE TITLE
请求增加xiaomi.bhf_light.v1的本地模式支持

### ISSUE THREAD

**Issue by will-huang9531** [al-one/hass-xiaomi-miot#1883]
### Device model / 设备型号

xiaomi.bhf_light.v1

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2023.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

目前本设备仅支持云端模式，请求添加该设备的本地模式

### Entity attributes / 实体属性

```yaml
hvac_modes: off, dry
min_temp: 25
max_temp: 45
target_temp_step: 1
fan_modes: low, high
preset_modes: Defog, Quick Defog, Quick Heat, Other, off
swing_modes: off, vertical
current_temperature: null
temperature: 30
fan_mode: high
hvac_action: off
preset_mode: off
swing_mode: vertical
model: xiaomi.bhf_light.v1
lan_ip: ////
mac_address: ////
entity_class: MiotClimateEntity
home_room: ////
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:xiaomi-v1:1
ptc_bath_heater.mode: 0
ptc_bath_heater.blow: false
ptc_bath_heater.heating: false
ptc_bath_heater.ventilation: false
ptc_bath_heater.heat_level: 1
ptc_bath_heater.off_delay: false
ptc_bath_heater.off_delay_time: 0
target_temperature-3-8: 30
remote_delay_off_time-3-9: 15
ptc_bath_heater.room_size: 0
alarm: false
delay-7.delay: false
delay-7.delay_time: 0
delay-7.delay_remain_time: 0
delay: false
delay.delay_time: 0
delay.delay_remain_time: 0
fan_control.vertical_swing: true
fan_control.vertical_angle: 90
fan_control.fan_level: 3
fan_control-5.fan_level: 1
light.on: false
light.mode: 0
light.brightness: 100
light.default_power_on_state: 2
light.night_light_switch: true
state_updater: cloud
sub_entities: ptc_bath_heater-3.off_delay_time-7, Defog, Quick Defog, Quick Heat, Other, ptc_bath_heater-3.blow-2, ptc_bath_heater-3.heating-3, ptc_bath_heater-3.ventilation-4, ptc_bath_heater-3.off_delay-6, light-2
light.enable_time_period: 00:00:00-06:00:00
friendly_name: 浴霸 PTC Bath Heater
supported_features: 57
```
