### ISSUE TITLE
xiaomi.derh.13l becomes unavailable several times a day.

### ISSUE THREAD

**Issue by limitless00net** [al-one/hass-xiaomi-miot#1887]
### Device model / 设备型号

[xiaomi.derh.13l](https://home.miot-spec.com/s/xiaomi.derh.13l)

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.9.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

This device becomes unavailable several times a day.

### Entity attributes / 实体属性

```yaml
min_humidity: 30
max_humidity: 70
available_modes: Off, Smart, Sleep, Clothes Drying
current_humidity: 44
humidity: 50
mode: Off
model: xiaomi.derh.13l
lan_ip: 192.168.1.45
mac_address: 68:AB:BC:1F:9B:3E
entity_class: MiotHumidifierEntity
home_room: Home Hajin Room
miot_type: urn:miot-spec-v2:device:dehumidifier:0000A02D:xiaomi-13l:1
dehumidifier.on: false
dehumidifier.fault: 0
dehumidifier.mode: 1
dehumidifier.target_humidity: 50
dm_service.dry_after_off: true
dm_service.dry_left_time: 0
dm_service.is_warming_up: false
delay: false
delay.delay_time: 0
delay.delay_remain_time: 0
physical_controls_locked: false
indicator_light.on: true
indicator_light.mode: 2
alarm: true
environment.relative_humidity: 44
environment.temperature: 26.8
state_updater: lan
sub_entities: environment-3.relative_humidity-1, environment-3.temperature-2, physical_controls_locked-6.physical_controls_locked-1, indicator_light-5
device_class: dehumidifier
friendly_name: 하진이방 제습기
supported_features: 1
```

### Home Assistant Logs / 系统日志

HR Dehumidifier(xiaomi.derh.13l): Got MiioException while fetching the state: Unable to discover the device 192.168.1.45, mapping: {'dehumidifier.on': {'siid': 2, 'piid': 1}, 'dehumidifier.fault': {'siid': 2, 'piid': 2}, 'dehumidifier.mode': {'siid': 2, 'piid': 3}, 'dehumidifier.target_humidity': {'siid': 2, 'piid': 5}, 'dm_service.dry_after_off': {'siid': 7, 'piid': 1}, 'dm_service.dry_left_time': {'siid': 7, 'piid': 2}, 'dm_service.is_warming_up': {'siid': 7, 'piid': 3}, 'delay': {'siid': 8, 'piid': 1}, 'delay.delay_time': {'siid': 8, 'piid': 2}, 'delay.delay_remain_time': {'siid': 8, 'piid': 3}, 'physical_controls_locked': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'indicator_light.mode': {'siid': 5, 'piid': 2}, 'alarm': {'siid': 4, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 2}}, max_properties: 8/16

Get xiaomi scene history for 1586447051 212001001052 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}
Get xiaomi scene history for 1586447051 212001068441 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}

light.dmaker_22ht_e319_indicator_light (<class 'custom_components.xiaomi_miot.light.MiotLightSubEntity'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
light.xiaomi_13l_9b3e_indicator_light (<class 'custom_components.xiaomi_miot.light.MiotLightSubEntity'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

[home-assistant_xiaomi_miot_2024-10-09T01-01-16.463Z.log](https://github.com/user-attachments/files/17300741/home-assistant_xiaomi_miot_2024-10-09T01-01-16.463Z.log)

**Comment by al-one** [comment]
Try:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    xiaomi.derh.13l:
      chunk_properties: 1
```
