### ISSUE TITLE
cuco wp5 power status switch too slow.

### ISSUE THREAD

**Issue by fq33578** [al-one/hass-xiaomi-miot#1888]
### Device model / 设备型号

cuco.plug.wp5

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.10.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The Switch Power Status From Off Change to on,
Triggered about 10s~30s,It;s too slow.
My Automation config are theese:
```
alias: 當螢幕開啟-開啟書房燈
description: Turns the garage door switch off as soon as it is turned on
triggers:
  - entity_id:
      - switch.cuco_wp5_4551_switch
    from: "off"
    to: "on"
    trigger: state
    for:
      hours: 0
      minutes: 0
      seconds: 1
actions:
  - entity_id: switch.3f_shu_fang_deng
    action: switch.turn_on

```

![image](https://github.com/user-attachments/assets/80c9dfde-aed2-4b87-8969-9accc7a5efda)

### Entity attributes / 实体属性

```yaml
model: cuco.plug.wp5
entity_class: MiotSwitchEntity
home_room: CN林品心的家 3F
miot_type: urn:miot-spec-v2:device:outlet:0000A002:cuco-wp5:1
switch.on: true
state_updater: cloud
device_class: outlet
friendly_name: 3F電腦螢幕 Switch
supported_features: 0
```

### Home Assistant Logs / 系统日志

[home-assistant_2024-10-10T11-49-09.921Z.log](https://github.com/user-attachments/files/17327499/home-assistant_2024-10-10T11-49-09.921Z.log)
