### ISSUE TITLE
[Enhancement request] Support for scale using the miot protocol. Xiaomi Body Composition Scale S400 (yunmai.scales.ms104)

### ISSUE THREAD

**Issue by v1k70rk4** [al-one/hass-xiaomi-miot#1889]
Hello,

I have a development request. The new scale no longer broadcasts the measured values, but instead displays the data in the MiHome app.

The name of the product is Xiaomi Body Composition Scale S400 (yunmai.scales.ms104).  
Miot description: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:scale:0000A07D:yunmai-ms104:1

I would greatly appreciate it if you could look into this. If I can help with testing or anything else, I'm at your disposal.

Viktor

**Comment by al-one** [comment]
All properties do not have read permissions.

```yaml
{
    "iid": 2,
    "type": "urn:miot-spec-v2:service:scale:0000786B:yunmai-ms104:1",
    "description": "Scale",
    "properties": [
        {
            "iid": 1,
            "type": "urn:miot-spec-v2:property:unit:000001E0:yunmai-ms104:1",
            "description": "Unit",
            "format": "uint8",
            "access": [], # All properties do not have read permissions.
            "value-list": [
                {
                    "value": 1,
                    "description": "Kilogram"
                },
                {
                    "value": 2,
                    "description": "Pound"
                }
            ],
            "source": 3,
            "gatt-access": [
                "read",
                "write"
            ]
        },
        {
            "iid": 2,
            "type": "urn:miot-spec-v2:property:heart-rate-detection:000001DF:yunmai-ms104:1",
            "description": "Heart Rate Detection",
            "format": "bool",
            "access": [],
            "source": 3,
            "gatt-access": [
                "read",
                "write"
            ]
        },
        {
            "iid": 3,
            "type": "urn:miot-spec-v2:property:current-time:00000098:yunmai-ms104:1",
            "description": "Current Time",
            "format": "uint32",
            "access": [],
            "value-range": [
                0,
                4294967295,
                1
            ],
            "source": 3,
            "gatt-access": [
                "read",
                "write"
            ]
        }
    ]
}
```
