### ISSUE TITLE
No entity with water level sensor in humidifier

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [al-one/hass-xiaomi-miot#1902]
### Device model / 设备型号

[deerma.humidifier.jsq2w](https://home.miot-spec.com/s/deerma.humidifier.jsq2w)

### Component version / 插件版本

0.7.21

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The device does not indicate the level of water in the tank. The device has a sensor that measures this, as it sends a low water level notification through the Mi Home app.

### Entity attributes / 实体属性

```yaml
min_humidity: 40
max_humidity: 70
available_modes: Off, None, Constant Humidity
current_humidity: 45
humidity: 60
mode: Off
model: deerma.humidifier.jsq2w
lan_ip: [CENSORED]
mac_address: [CENSORED]
entity_class: MiotHumidifierEntity
home_room: [CENSORED]
exclude_miot_services: custom
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1
humidifier.on: false
humidifier.fault: 0
humidifier.fan_level: 1
humidifier.target_humidity: 60
humidifier.status: 1
humidifier.mode: 0
indicator_light.on: true
alarm: true
environment.relative_humidity: 45
environment.temperature: 26
state_updater: cloud
sub_entities: alarm-5.alarm-1, environment-3.relative_humidity-1, environment-3.temperature-7, indicator_light-6, humidifier.fan_level
device_class: humidifier
friendly_name: Nawilżacz Humidifier
supported_features: 1
```
