### ISSUE TITLE
米家喂食器2干燥盒实体数据异常

### ISSUE THREAD

**Issue by scythk** [al-one/hass-xiaomi-miot#1911]
### Device model / 设备型号

xiaomi.feeder.pi2001

### Component version / 插件版本

0.7.21

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![image](https://github.com/user-attachments/assets/aa56d96e-a342-4521-87ec-61017dc7c1d6)
![124ce358dd07be2a7ae5c1975434b64](https://github.com/user-attachments/assets/0800b42a-8b12-4a45-9112-a666508695a7)

### Entity attributes / 实体属性

```yaml
sensor.xiaomi_pi2001_6c35_desiccant_left_level 喂食器 Desiccant Left Level 0
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.xiaomi_pi2001_6c35_pet_feeder
service_description: Desiccant
property_description: Desiccant Left Level
updated_time: 2024-10-31T18:45:24.829741+08:00
desiccant.desiccant_left_level: 0
battery_level: false
unit_of_measurement: %
friendly_name: 喂食器 Desiccant Left Level
supported_features: 0

sensor.xiaomi_pi2001_6c35_desiccant_left_time 喂食器 Desiccant Left Time 0
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.xiaomi_pi2001_6c35_pet_feeder
service_description: Desiccant
property_description: Desiccant Left Time
updated_time: 2024-10-31T18:45:24.839398+08:00
desiccant.desiccant_left_time: 0
battery_level: false
unit_of_measurement: days
friendly_name: 喂食器 Desiccant Left Time
supported_features: 0
```
