### ISSUE TITLE
米家空调 巨能省Pro 缺少用电数据实体

### ISSUE THREAD

**Issue by hamkido** [al-one/hass-xiaomi-miot#1914]
### Device model / 设备型号

xiaomi.airc.r24r00

### Component version / 插件版本

0.7.21

### HA core version / HA版本

2024.10.2

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

power_consumption

### Entity attributes / 实体属性

```yaml
hvac_modes: cool, heat, dry, fan_only, auto, off
min_temp: 16
max_temp: 31
target_temp_step: 0.5
min_humidity: 0
max_humidity: 100
fan_modes: auto, level1, level2, level3, level4, level5, level6, level7, level8
swing_modes: off, vertical
current_temperature: 25
temperature: 26
current_humidity: 62
humidity: 0
fan_mode: level3
hvac_action: heating
swing_mode: off
model: xiaomi.airc.r24r00
lan_ip: 192.168.65.207
mac_address: E8:4A:54:91:56:30
entity_class: MiotClimateEntity
home_room: xxxx
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-r24r00:2
air_conditioner.on: true
air_conditioner.mode: 5
air_conditioner.fault: 0
target_temperature-2-4: 26
air_conditioner.eco: false
air_conditioner.heater: true
air_conditioner.dryer: false
air_conditioner.sleep_mode: false
air_conditioner.target_humidity: 0
unstraight_blowing-2-15: false
air_conditioner.favorite_on: false
air_conditioner.favorite_type: 0
like_mode.user_defined_mode: 0
like_mode.recommend_mode: 0
like_mode.always_favorite_on: false
single_smart_scene.auto_cooling: false,28.0,26.0
automatic_heating-16-2: false,24.0,26.0
single_smart_scene.auto_dry: false,70,55
run_dark_sleep-16-10: false
flag_bit.fault_value: 4
machine_state.indoor_pipe_temp: 44.1
machine_state.indoor_fan_speed: 890
real_heater_switch-12-4: 0
realindoor_fan_lever-12-5: 3
lightactivated_level-12-6: 0
machine_state.outdoor_temp: 16
machine_state.outdoor_pipe_temp: 14
outdoor_exhaust_temp-12-9: 60.5
machine_state.outdoor_fan_lever: 3
compressor_frequency-12-11: 31.5
fourway_valve_switch-12-12: true
outdoor_mach_current-12-13: 2.5
outdoor_mach_voltage-12-14: 233
machine_state.expansion_valve: 187
longitude_latitude-12-16: 0
machine_state.version: 0010,V0021,V0011,V0033,0010,V0021,V0011,V0033
external_serial_no-12-23: 26380/KG24C44C5065
machine_state.bk_serial_no: 00000/00IDU0000000,KBE3S/410C44051617
machine_state.module_temp: 36.7
enhance.fan_percent: 24
enhance.timer: 0
enhance.sleep_diy: false
enhance.secondpart_of_hswing: false
enhance.humidity_range: 40-70
enhance.room_size: 4
enhance.maxfan_select: false
enhance.like_diy: false
enhance.room_select: false
maintenance.clean: 0,100,1,1
maintenance.examine: none
maintenance.running_duration: 764.5
electricity.time_count: 60
electricity.electricity_info: false
filter-22.filter_life_level: 101
filter.filter_life_level: 101
power_consumption: 18.01
indicator_light.on: true
indicator_light.brightness: 0
alarm: true
environment.temperature: 25
environment.relative_humidity: 62
fan_control.fan_level: 3
fan_control.vertical_swing: false
vertical_swing_included_angle-3-6: 8
state_updater: lan
sub_entities: power_consumption-20.power_consumption-1, environment-4.temperature-7, environment-4.relative_humidity-9, filter-21.filter_life_level-1, filter-22.filter_life_level-1, indicator_light-6, air_conditioner-2.eco-7, air_conditioner-2.heater-9, air_conditioner-2.dryer-10, air_conditioner-2.sleep_mode-11, air_conditioner-2.un_straight_blowing-15, air_conditioner-2.favorite_on-19
friendly_name: Power Saving Pro Air Conditioner 1.5HP Level 1+ Energy Efficiency Air Conditioner
supported_features: 429
```
