### ISSUE TITLE
佛山照明V1智能浴霸只能控制灯光，不能控制其他选项

### ISSUE THREAD

**Issue by meteorkin** [al-one/hass-xiaomi-miot#1916]
### Device model / 设备型号

[giot.bhf_light.v1ibhw](https://home.miot-spec.com/s/giot.bhf_light.v1ibhw)

### Component version / 插件版本

0.7.21

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

通过账号集成或局域网集成都能识别到该设备，添加完毕后会添加1个设备和一个实体

实体能开关浴霸的主灯，但无法控制其他属性（比如夜灯、风扇、取暖灯）
在实体属性中能看到夜灯开关报错的信息 light.night_light_switch.error: "-4003 Property/Action/Event does not exist"
<img width="426" alt="浴霸错误" src="https://github.com/user-attachments/assets/732664ca-becb-49b7-a4cb-474fb708bf44">

但在米家app中是能看到并可控制更多选项的
![mijia](https://github.com/user-attachments/assets/e35556ba-61e2-4b7a-b671-a4ca7b8d7607)

### Entity attributes / 实体属性

```yaml
supported_color_modes:
  - onoff
color_mode: null
model: giot.bhf_light.v1ibhw
lan_ip: 192.168.0.44
mac_address: B8:50:D8:71:FF:7C
entity_class: MiotLightEntity
home_room: 6763909128 Bathroom
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:giot-v1ibhw:1
light.on: false
light.night_light_switch.error: "-4003 Property/Action/Event does not exist"
state_updater: lan
friendly_name: 卫生间浴霸 Light
supported_features: 0
```

### Home Assistant Logs / 系统日志

2024-11-02 01:38:43.902 DEBUG (MainThread) [custom_components.xiaomi_miot.light] V1 Intelligent Bath Heater(WiFi)(giot.bhf_light.v1ibhw): Got new state: {'light.on': False, 'light.night_light_switch.error': '-4003 Property/Action/Event does not exist', 'state_updater': 'lan'}
