### ISSUE TITLE
邦先生C1无法上升

### ISSUE THREAD

**Issue by 0uzu0** [al-one/hass-xiaomi-miot#1922]
### Device model / 设备型号

[mrbond.airer.m1t](https://home.miot-spec.com/s/mrbond.airer.m1t)

### Component version / 插件版本

0.7.21

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

此型号晾衣机在系统集成里上升按钮为灰色，且行程状态点击无效

### Entity attributes / 实体属性

```yaml
晾衣机 Airer：cover.mrbond_m1t_fa9d_airer
current_position: 100
model: mrbond.airer.m1t
lan_ip: 192.168.110.111
mac_address: 54:48:E6:67:FA:9D
entity_class: MiotCoverEntity
home_room: 我的家庭 阳台
miot_type: urn:miot-spec-v2:device:airer:0000A00D:mrbond-m1t:1
airer.fault: 0
airer.current_position: 0
airer.status: 3
airer.mode: 81
airer-2.current_position: 0
airer.on: 1
airer.target_position: 61
light.on: false
state_updater: cloud
friendly_name: 晾衣机 Airer
supported_features: 15
airer.motor_control: 2
```

### Home Assistant Logs / 系统日志

晾衣机(mrbond.airer.m1t): Set miot property {'did': '360043528', 'siid': 2, 'piid': 2, 'value': 2} failed, result: {'did': '360043528', 'iid': '0.2.2', 'siid': 2, 'piid': 2, 'code': -704220043, 'exe_time': 0}
