### ISSUE TITLE
请再次关注 #1762  问题

### ISSUE THREAD

**Issue by hzonz** [al-one/hass-xiaomi-miot#1925]
### Device model / 设备型号

[hyd.airer.znlyj5](https://home.miot-spec.com/s/hyd.airer.znlyj5)
[xjx.toilet.relaxp](https://home.miot-spec.com/s/xjx.toilet.relaxp)

### Component version / 插件版本

0.7.22

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

请关注 #1762 问题，此次更新设备（hyd.airer.znlyj5） ，无法正确控制晾衣架，请回退到之前版本，之前版本能正确控制此设备，无需更改。

请再次完善设备（xjx.toilet.relaxp)

    'xjx.toilet.relaxp': {
        'sensor_properties': 'status,bubble-level',
        'switch_properties': 'status_seatheat,status_led,auto_led,flush_setting,statys_bubbleshield,'
                             'status_seat,status_cover,auto_seat_close,auto_cover_close,status_microw_seat,'
                             'status_microw_cover,status_footin_seat,status_footin_cover',
        'select_properties': 'seat_temp',
        'button_actions': 'stop_working,flush_work,start_foam,clean_work',

![屏幕截图_4-11-2024_23130_10 10 12 12](https://github.com/user-attachments/assets/50cdc6f3-f43c-4261-9cab-fb647b222bfe)

### Entity attributes / 实体属性

```yaml
current_position: 0
model: hyd.airer.znlyj5
lan_ip: 10.10.12.109
mac_address: CC:B5:D1:37:8F:2D
entity_class: MiotCoverEntity
home_room: 阳台
exclude_miot_properties:
  - motor_control
miot_type: urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj5:2
airer.fault: 0
airer.current_position: 1
airer.status: 0
light.on: false
state_updater: lan
airer.motor_control: 0
device_class: shade
friendly_name: 阳台晾衣架 晾衣架
supported_features: 11
```
