### ISSUE TITLE
v1.0.0b0下fawad.airrtc.30015的climate实体不可用，Updater为none

### ISSUE THREAD

**Issue by rumianoesa** [al-one/hass-xiaomi-miot#1926]
### Device model / 设备型号

fawad.airrtc.30015

### Component version / 插件版本

1.0.0b0

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

v1.0.0b0下fawad.airrtc.30015的climate实体不可用，信息实体可用，Updater为none
v0.7.22下climate实体正常可用，Updater为local

### Entity attributes / 实体属性

```yaml
Info
卧室空调
Model
fawad.airrtc.30015
Did

MAC

Lan IP
192.168.0.85
App link

Available
true
Updater
none
Updated at
Converters
info
Customizes
switch_properties: air_conditioner.on
exclude_miot_services: thermostat_vrf
```

**Comment by rumianoesa** [comment]
v1.0.0b0下使用Cloud (云端模式)，climate实体正常可用
请求对fawad.airrtc.30015添加Local (本地模式)支持

**Comment by al-one** [comment]
更新 v1 分支后再试。
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=v1 bash -
```

**Comment by rumianoesa** [comment]
更新v1.0.0b1后climate实体变为可用，但信息实体中显示的Updater仍然为none
可发送指令控制设备，但无法获取设备的实时状态

Entity attributes / 实体属性
```yaml
hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 32
target_temp_step: 0.5
fan_modes: auto, quiet, level1, level2, level3, level4, level5
preset_modes: 模式, 模式, 模式, off
current_temperature: 0
temperature: 0
fan_mode: null
hvac_action: off
preset_mode: off
model: fawad.airrtc.30015
lan_ip: 192.168.0.85
mac_address:
home_room: 家 卧室
entity_class: MiotClimateEntity
exclude_miot_services: thermostat_vrf
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:fawad-30015:1
friendly_name: 卧室空调 温控器
supported_features: 409
```
