### ISSUE TITLE
No vision in chuangmi.camera.029a02

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [al-one/hass-xiaomi-miot#1931]
### Device model / 设备型号

[chuangmi.camera.029a02](https://home.miot-spec.com/s/chuangmi.camera.029a02)

### Component version / 插件版本

0.7.22

### HA core version / HA版本

2024.11.0

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

There is no video from the camera. When I open the device, I get a notification from the app that someone is using the camera, while there is no vision in HA.
<img width="600" alt="obraz" src="https://github.com/user-attachments/assets/da7f12a8-2d69-4b7e-afeb-f16696f440c2">

### Entity attributes / 实体属性

```yaml
access_token: [CENSORED]
model_name: chuangmi.camera.029a02
brand: chuangmi
frontend_stream_type: hls
model: chuangmi.camera.029a02
lan_ip: [CENSORED]
mac_address: [CENSORED]
entity_class: MiotCameraEntity
home_room: Tychy Sypialnia
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-029a02:2
miot_action_result: 
did: '372015442'
miid: 0
siid: 7
aiid: 1
code: -704220025
exe_time: 0
withLatency: 0

miot_action_error: -704220025 The number of action parameters does not match
stream_address: 
expire_at: 2024-11-07 19:24:16.678596
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 1
camera_control.motion_tracking: false
camera_control.time_watermark: true
speaker.volume: 100
stream_status-8-9: 1
stream_status-7-9: 1
motion_detection: true
motion_detection.alarm_interval: 10
detection_sensitivity-5-3: 0
motion_detection_start_time-5-4: 00:00:00
motion_detection_end_time-5-5: 23:59:00
memory_card_management.status: 0
storage_total_space-4-2: 1880
storage_free_space-4-3: 40
storage_used_space-4-4: 1840
indicator_light.on: true
state_updater: cloud
sub_entities: memory_card_management-4.status-1, memory_card_management-4.storage_free_space-3, memory_card_management-4.storage_used_space-4, camera_control-2.on-1, camera_control-2.wdr_mode-5, camera_control-2.glimmer_full_color-6, camera_control-2.motion_tracking-8, camera_control-2.time_watermark-9, indicator_light-3.on-1, motion_detection-5.motion_detection-1, camera_control-2.image_rollover-2, motion_detection-5.alarm_interval-2, camera_control-2.night_shot-3, camera_control-2.recording_mode-7, motion_detection-5.detection_sensitivity-3, indicator_light-3, motion_event
entity_picture: /api/camera_proxy/camera.chuangmi_029a02_d9bb_camera_control?token=[CENSORED]
friendly_name: Mi 360° 2K Camera Control
supported_features: 3
```
