### ISSUE TITLE
Device or entity unavailable

### ISSUE THREAD

**Issue by luyumenq** [al-one/hass-xiaomi-miot#1933]
### Device model / 设备型号

devcea.light.ls2307

### Component version / 插件版本

0.7.22

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

宜家兼容的806流明彩色球泡灯经常显示断开连接

### Entity attributes / 实体属性

```yaml
min_color_temp_kelvin: 2702
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 370
effect_list:
  - Nonescene
  - Night
  - Warmth
  - Reading
  - Sleep Aid
  - Weak Up
  - Color
supported_color_modes:
  - color_temp
friendly_name: 餐桌灯 白光
supported_features: 4
```

### Home Assistant Logs / 系统日志

日志记录器: custom_components.xiaomi_miot.light
来源: custom_components/xiaomi_miot/__init__.py:1455
集成: Xiaomi Miot Auto ([文档](https://github.com/al-one/hass-xiaomi-miot), [问题](https://github.com/al-one/hass-xiaomi-miot/issues))
首次出现: 2024年11月7日 23:31:20 (996 次总计出现)
上次记录: 15:47:17

餐桌灯(devcea.light.ls2307): Got MiioException while fetching the state: Unable to discover the device 192.168.31.97, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'light.flex_switch': {'siid': 2, 'piid': 5}, 'setting.ac_status': {'siid': 3, 'piid': 1}, 'setting.power_on_state': {'siid': 3, 'piid': 2}, 'setting.turn_on_state': {'siid': 3, 'piid': 3}, 'setting.default_brightness': {'siid': 3, 'piid': 4}, 'setting.default_temperature': {'siid': 3, 'piid': 5}, 'setting.sleep_aid_time': {'siid': 3, 'piid': 7}, 'setting.custom_sleep_aid': {'siid': 3, 'piid': 8}, 'setting.initial_brightness': {'siid': 3, 'piid': 9}, 'setting.initial_temperature': {'siid': 3, 'piid': 10}, 'setting.wake_up_time': {'siid': 3, 'piid': 11}, 'setting.custom_weak_up': {'siid': 3, 'piid': 12}, 'setting.final_brightness': {'siid': 3, 'piid': 13}, 'setting.final_temperature': {'siid': 3, 'piid': 14}, 'setting.gradient_duration_on': {'siid': 3, 'piid': 17}, 'setting.gradient_duration_of': {'siid': 3, 'piid': 18}, 'setting.gradient_duration_aj': {'siid': 3, 'piid': 19}, 'setting.colorful_set': {'siid': 3, 'piid': 22}, 'ambient_light.color': {'siid': 4, 'piid': 1}, 'ambient_light.mode': {'siid': 4, 'piid': 2}}, max_properties: 8/24
