### ISSUE TITLE
领普 s2dw3 开关文本输入中文后，无法正常显示中文

### ISSUE THREAD

**Issue by wemos** [al-one/hass-xiaomi-miot#1938]
### Device model / 设备型号

linp.switch.s2dw3

### Component version / 插件版本

0.7.22

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

在文本框中输入任意中文后，面板上无法正常显示中文，显示的是该中文的UTF-8编码。

输入：

![103bf484-b92d-4f05-8928-fbe1b8c591a5](https://github.com/user-attachments/assets/5d766b8c-4cfe-4f9f-8cc0-3aff35a81618)

显示：

![fd434175-5e23-4cd4-ab44-73e39f16c548](https://github.com/user-attachments/assets/7e1423a5-afdf-4ef7-a358-ef4fb4f3e4fb)

### Entity attributes / 实体属性

```yaml
model: linp.switch.s2dw3
lan_ip: 192.168.1.134
mac_address: CC:DC:B2:13:BB:95
entity_class: MiotSwitchEntity
home_room: 2楼
miot_type: urn:miot-spec-v2:device:switch:0000A003:linp-s2dw3:2:0000D042
switch.on: false
switch.mode: 1
switch.default_power_on_state: 0
vd_panel_a.text_a: 40
vd_panel_a.text_b: \u5173\u95ed
vd_panel_a.text_c: 
vd_panel_a.text_s: 
vd_motor_b.target_position: 0
vd_motor_a.target_position: 50
vd_thmst_b.on: false
vd_thmst_b.target_temperature: 27
vd_thmst_b.mode: 0
vd_thmst_b.fan_level: 0
vd_thmst_a.on: true
vd_thmst_a.target_temperature: 28
vd_thmst_a.mode: 0
vd_thmst_a.fan_level: 3
vd_light_c.on: false
vd_light_c.brightness: 50
vd_light_c.color_temperature: 4000
vd_light_c.color: 16777215
vd_light_c.color_mode: 0
vd_light_b.on: false
vd_light_b.brightness: 50
vd_light_b.color_temperature: 4000
vd_light_a.on: false
vd_light_a.brightness: 50
vd_light_a.color_temperature: 4000
vendor.city: 101210707
vendor.screen_saver: false
vendor.night_mode: true
vendor.night_mode_start: 75600
vendor.night_mode_over: 32400
vendor.sensitivity: 2
vendor.occupy: true
vendor.relay_lock: false
vendor.access_token: V3_kZ75QTO7aCxDODnttZgidqduaF0mZWDp4ApdljXU77Myi6pbGc3jTlrqs2NbU6jzQr-u2LKIA7lWz2-1agM4m_MoeRqqqIJEl6av9iqo436lC8tTe9TccNM15Lo5uqQ8BDtooknTHj2GM72TcKAGKA
vendor.refresh_token: R3_Tzk4LK4M0iuJ_FFtnxNyu1UYjRaKAC2Wpe_KKzxK9G9C73jhXGKgmxjWotcvgMGTz67K2HlSiBd6uy4OUkolQ_mdKOw8dBI6cpDUhO_VIGmKJdtrtb5OBrZt5AEwcZzIpjweeQZa8dylRBkcwRlLNV9uExURcGkEeo7hNAf68-O7Z4BICytbMNyy61Ue5BSf
vendor.time_fmt: 0
vendor.ss_brightness: 20
vendor.rotate: false
screen_set.screen_a: 75,1,自定义面板,1
screen_set.screen_b: 0
screen_set.screen_c: 
screen_set.screen_d: 
screen_set.screen_e: 
screen_set.screen_f: 
screen_set.theme: 
screen_set.names: ,,,,,,,,,,,,,,,
screen_set.theme_cfg: 10,291,10,266,3,15,10,234,3,164,0,0,0,0,3
screen_set.scene_a: 
screen_set.scene_b: 
screen_set.screen_g: 
screen_set.screen_h: 
screen_set.screen_ss: 
screen.brightness: 65
screen.auto_screen_off: true
screen.auto_screen_brightness: true
screen.auto_screen_off_time: 2
screen.on: true
state_updater: lan
sub_entities: screen-10.auto_screen_off-4, screen-10.auto_screen_brightness-5, screen-10.on-7, vendor-12.night_mode-3, screen-10.brightness-2, vd_light_a-13.brightness-2, vd_light_b-14.brightness-2, vd_light_c-15.brightness-2, switch-2.mode-2, switch-2.default_power_on_state-5, switch-3.mode-2, switch-4.mode-2, screen-10.auto_screen_off_time-6, screen_set-11.screen_switch-16, vendor-12.sensitivity-6, vd_thmst_a-16.mode-3, vd_thmst_b-17.mode-3, vd_panel_a-20.text_a-1, vd_panel_a-20.text_b-2, vd_panel_a-20.text_c-3, vd_panel_a-20.text_s-4, vendor-12.reboot-2, vd_light_a-13, vd_light_b-14, vd_light_c-15
device_class: switch
friendly_name: Linptech Touch Screen Switch S2 First Switch Service
supported_features: 0
```
