### ISSUE TITLE
智能墙壁插座不可用

### ISSUE THREAD

**Issue by xiaowuap** [al-one/hass-xiaomi-miot#1940]
### Device model / 设备型号

zimi.plug.zncz01

### Component version / 插件版本

1.0.0.0b1

### HA core version / HA版本

2024.4.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

整个设备不可用，提示“插件已不再提供实体xxx”
![image](https://github.com/user-attachments/assets/6e85f163-bdbe-4a7c-95a9-91fb51003e4d)

### Entity attributes / 实体属性

```yaml
restored: true
state_class: measurement
device_class: power
friendly_name: 服务器_网络 功率
supported_features: 0
unit_of_measurement: W
```
