### ISSUE TITLE
米家智能插座2蓝牙网关版功率显示不正常

### ISSUE THREAD

**Issue by JianxinORG76LBITCVECF6L** [al-one/hass-xiaomi-miot#1959]
### Device model / 设备型号

chuangmi.plug.212a01

### Component version / 插件版本

0.7.23(latest)，数个版本前开始存在问题

### HA core version / HA版本

2024.10.3

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

设备当前功率显示异常，显示值为实际值的1%。希望更正。实体属性中提供的功率值是正确的，但是显示值不正确，除此之外该设备没有被正确汉化

### Entity attributes / 实体属性

```yaml
state_class: measurement
entity_class: MiotSensorSubEntity
parent_entity_id: switch.chuangmi_212a01_03cd_switch
service_description: Power Consumption
property_description: Electric Power
updated_time: "2024-11-19T14:10:38.560266+08:00"
electric_power-5-6: 137
unit_of_measurement: W
device_class: power
friendly_name: Mi Smart Power Plug 2 (Wi-Fi and Bluetooth Gateway) Power Consumption Electric
supported_features: 0
```

### Home Assistant Logs / 系统日志

2024-11-19 13:50:03.253 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-19 13:50:06.105 WARNING (MainThread) [custom_components.xiaomi_miot.sensor] Get xiaomi scene history for 454409156 310001047052 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}
2024-11-19 13:57:21.849 WARNING (MainThread) [custom_components.xiaomi_miot.sensor] Get xiaomi scene history for 454409156 310001047052 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}
2024-11-19 13:58:48.595 WARNING (MainThread) [custom_components.xiaomi_miot.sensor] Get xiaomi scene history for 454409156 310001047052 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}
2024-11-19 13:59:08.112 WARNING (MainThread) [custom_components.xiaomi_miot.sensor] Get xiaomi scene history for 454409156 310001047052 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}
