### ISSUE TITLE
soocare.toothbrush.1501 和yunmi.scales.ms103 无法正常接入ha

### ISSUE THREAD

**Issue by WillionFe** [al-one/hass-xiaomi-miot#1970]
### Device model / 设备型号

soocare.toothbrush.1501 和yunmi.scales.ms103

### Component version / 插件版本

0.7.24

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

1、soocare.toothbrush.1501 小米电动牙刷T501可以接入，但无法获取电量数据，显示如下：
传感器
 
Battery Level
不可用
 
Battery Level event
start
 
Battery Level timestamp
1970-01-01T08:00:00+08:00
2、yunmi.scales.ms103 小米体脂秤S400无法接入

### Entity attributes / 实体属性

```yaml
1、sensor.soocare_1501_5500_battery
unavailable
状态属性：
state_class: measurement
unit_of_measurement: "%"
device_class: battery
friendly_name: Mi Smart Electric Toothbrush T501 Battery Level
supported_features: 0
2、yunmi.scales.ms103 无实体
```

### Home Assistant Logs / 系统日志

[home-assistant_2024-11-24T06-39-12.599Z.log](https://github.com/user-attachments/files/17892229/home-assistant_2024-11-24T06-39-12.599Z.log)
