### ISSUE TITLE
090615.curtain.ws9856 双电机始终有一个无法连接

### ISSUE THREAD

**Issue by k186** [al-one/hass-xiaomi-miot#1975]
### Device model / 设备型号

090615.curtain.ws9856

### Component version / 插件版本

0.7.24

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

梦幻帘电机，小米APP 上能正常操作，同步后 左电机无法通过HA 设置，电机状态显示离线，
![image](https://github.com/user-attachments/assets/c9882b57-b4d7-4e13-b358-c4c0870e0710)
![image](https://github.com/user-attachments/assets/34c1e706-e7bf-48e1-9791-f7585a9eac6a)

### Entity attributes / 实体属性

```yaml
current_position: 0
model: 090615.curtain.ws9856
lan_ip: 192.168.3.4
mac_address: 94:C9:60:24:40:7D
entity_class: MiotCoverEntity
home_room: 客厅
exclude_miot_properties:
  - motor_control
miot_type: urn:miot-spec-v2:device:curtain:0000A00C:090615-ws9856:1
curtain.fault.error: "-704083036 Device operation timeout"
curtain.mode.error: "-704083036 Device operation timeout"
curtain.current_position: 0
curtain.target_position: 16
curtain.motor_reverse.error: "-704083036 Device operation timeout"
state_updater: cloud
sub_entities:
  - curtain-2.motor_reverse-8
  - curtain-2.mode-5
curtain.motor_control: 1
device_class: curtain
friendly_name: 窗帘左 Curtain
supported_features: 15
```

### Home Assistant Logs / 系统日志

2024-11-25 20:38:19.642 WARNING (MainThread) [homeassistant.helpers.entity] Update of cover.090615_ws9856_407d_curtain is taking over 10 seconds

日志里面全是超时信息
