### ISSUE TITLE
加热毛巾架设备不可用[jyf.tow_w.ts03]

### ISSUE THREAD

**Issue by z-henry** [al-one/hass-xiaomi-miot#1976]
### Device model / 设备型号

[jyf.tow_w.ts03](https://home.miot-spec.com/s/jyf.tow_w.ts03)

### Component version / 插件版本

0.7.24

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

从继承中添加加热毛巾架后，一直显示实体不可用  

![wechat_2024-11-26_103951_744](https://github.com/user-attachments/assets/dce9c61b-58fb-4c23-a279-23a8f0f1f57d)

### Entity attributes / 实体属性

```yaml
cover.jyf_ts03_7a23_airer
friendly_name: Drying towel rack Airer
supported_features: 11

switch.jyf_ts03_7a23_towel_rack
device_class: switch
friendly_name: Drying towel rack Towel Rack
supported_features: 0
```

### Home Assistant Logs / 系统日志

Drying towel rack(jyf.tow_w.ts03): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'airer.fault': {'siid': 4, 'piid': 1}, 'airer.left_time': {'siid': 4, 'piid': 10}, 'towel_rack.on': {'siid': 2, 'piid': 1}, 'towel_rack.mode': {'siid': 2, 'piid': 2}, 'towel_rack.target_temperature': {'siid': 2, 'piid': 5}, 'towel_rack.temperature': {'siid': 2, 'piid': 6}}, max_properties: 8/6

**Comment by wolfit50** [comment]
遇到同样的问题

**Comment by al-one** [comment]
尝试添加以下配置:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    jyf.tow_w.ts03:
      chunk_properties: 1
```

**Comment by z-henry** [comment]
感谢回复，按要求修改后依旧不可用，并且提示报错

> 此错误来自自定义集成。
> 
> 日志记录器: custom_components.xiaomi_miot.cover
> 来源: custom_components/xiaomi_miot/__init__.py:1455
> 集成: Xiaomi Miot Auto (文档, 问题)
> 首次出现: 10:59:12 (10 次总计出现)
> 上次记录: 11:08:31
> 
> Drying towel rack(jyf.tow_w.ts03): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'airer.fault': {'siid': 4, 'piid': 1}, 'airer.left_time': {'siid': 4, 'piid': 10}, 'towel_rack.on': {'siid': 2, 'piid': 1}, 'towel_rack.mode': {'siid': 2, 'piid': 2}, 'towel_rack.target_temperature': {'siid': 2, 'piid': 5}, 'towel_rack.temperature': {'siid': 2, 'piid': 6}}, max_properties: 1/6

**Comment by wolfit50** [comment]
走云端可以用
```
# configuration.yaml
xiaomi_miot:
  device_customizes:
    jyf.tow_w.ts03:
      auto_cloud: true
```
