### ISSUE TITLE
青萍空气检测仪2所有传感器不可用

### ISSUE THREAD

**Issue by NightWatchMiro11** [al-one/hass-xiaomi-miot#1980]
### Device model / 设备型号

cgllc.airm.cgs2

### Component version / 插件版本

0.7.24

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

青萍空气检测仪2所有传感器不可用

### Entity attributes / 实体属性

```yaml
sensor.cgllc_cgs2_a36a_battery_level

Qingping Air Monitor 2 Battery Level
unavailable	restored: true
state_class: measurement
device_class: battery
friendly_name: Qingping Air Monitor 2 Battery Level
supported_features: 0
unit_of_measurement: %

sensor.cgllc_cgs2_a36a_charging_state

Qingping Air Monitor 2 Battery Charging State
1	friendly_name: Qingping Air Monitor 2 Battery Charging State
supported_features: 0
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.cgllc_cgs2_a36a_environment
service_description: Battery
property_description: Charging State
updated_time: 2024-11-28T01:25:48.848316+08:00
battery_level: 100
battery.charging_state: 1


sensor.cgllc_cgs2_a36a_co2_density

Qingping Air Monitor 2 Environment CO2 Density
unavailable	restored: true
state_class: measurement
device_class: carbon_dioxide
icon: mdi:molecule-co2
friendly_name: Qingping Air Monitor 2 Environment CO2 Density
supported_features: 0
unit_of_measurement: ppm

sensor.cgllc_cgs2_a36a_environment

Qingping Air Monitor 2 Environment Relative Humidity
unavailable	state_class: measurement
device_class: humidity
friendly_name: Qingping Air Monitor 2 Environment Relative Humidity
supported_features: 0
unit_of_measurement: %

sensor.cgllc_cgs2_a36a_pm10_density

Qingping Air Monitor 2 Environment PM10 Density
unavailable	restored: true
device_class: pm10
friendly_name: Qingping Air Monitor 2 Environment PM10 Density
supported_features: 0
unit_of_measurement: µg/m³

sensor.cgllc_cgs2_a36a_pm25_density

Qingping Air Monitor 2 Environment PM2.5 Density
unavailable	restored: true
state_class: measurement
device_class: pm25
icon: mdi:air-filter
friendly_name: Qingping Air Monitor 2 Environment PM2.5 Density
supported_features: 0
unit_of_measurement: µg/m³

sensor.cgllc_cgs2_a36a_temperature

Qingping Air Monitor 2 Environment Temperature
unavailable	restored: true
state_class: measurement
device_class: temperature
friendly_name: Qingping Air Monitor 2 Environment Temperature
supported_features: 0
unit_of_measurement: °C

sensor.cgllc_cgs2_a36a_tvoc_density

Qingping Air Monitor 2 Environment TVOC Density
unavailable	restored: true
state_class: measurement
friendly_name: Qingping Air Monitor 2 Environment TVOC Density
supported_features: 0
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: homeassistant
来源: custom_components/xiaomi_miot/sensor.py:521
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 00:57:53 (581 次总计出现)
上次记录: 01:48:48

Error doing job: Task exception was never retrieved (None)
Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1056, in _async_update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 544, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/sensor.py", line 521, in native_value
    if not prop.range_min() <= val <= prop.range_max():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'str'
