### ISSUE TITLE
viomi.waterheater.e1无法开关，看不到状态

### ISSUE THREAD

**Issue by github180556** [al-one/hass-xiaomi-miot#1984]
### Device model / 设备型号

viomi.waterheater.e1

### Component version / 插件版本

0.7.24

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![捕获3](https://github.com/user-attachments/assets/13bd3112-83e7-434b-a84d-eef9842da948)

### Entity attributes / 实体属性

```yaml
switch.viomi_e1_90a7_switch_status
unavailable 	
icon: mdi:water-boiler
friendly_name: 热水 Water Heater Switch Status
supported_features: 0
```

### Home Assistant Logs / 系统日志

日志记录器: custom_components.xiaomi_miot.core.miio2miot
来源: custom_components/xiaomi_miot/core/miio2miot.py:83
集成: Xiaomi Miot Auto ([文档](https://github.com/al-one/hass-xiaomi-miot), [问题](https://github.com/al-one/hass-xiaomi-miot/issues))
首次出现: 19:41:20 (53 次总计出现)
上次记录: 19:50:08
viomi.waterheater.e1: Got MiioException: {'code': -9998, 'message': 'user ack invalid'} while get_prop(['washStatus', 'velocity', 'waterTemp', 'targetTemp', 'errStatus', 'hotWater', 'needClean', 'modeType', 'appointStart', 'appointEnd'])

**Comment by github180556** [comment]
2024.3.1 0.7.19正常使用
![捕获4](https://github.com/user-attachments/assets/6a1205c4-91b8-4aef-ba15-2940cd0db353)

**Comment by al-one** [comment]
在[开发者工具 > 动作](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)中分别执行以下动作，并反馈结果。
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_90a7_water_heater
  method: get_prop
  params: [waterTemp]
```
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_90a7_water_heater
  method: get_prop
  params: [waterTemp, washStatus]
```
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_90a7_water_heater
  method: get_prop
  params: [all]
```
