### ISSUE TITLE
实体不再具有状态类

### ISSUE THREAD

**Issue by sasukebinbin** [al-one/hass-xiaomi-miot#1986]
### Device model / 设备型号

zhimi.airpurifier.ma2

### Component version / 插件版本

0.7.24

### HA core version / HA版本

20241106.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

系统曾为“小米空净2S Filter Life Level” (sensor.zhimi_airpurifier_ma2_filter_life_remaining) 生成过统计数据，但是由于其不再具有状态类，因而无法再跟踪其长期统计数据。
在此实体具有支持的状态类之前，无法生成统计数据。
如果状态类之前是由集成提供的，则这种情况有可能是错误。请报告问题。
如果之前您自行设置了状态类，请进行更正。 [可以在开发者文档中找到各种状态类以及它们的合适使用时间。](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
如果状态类已经永久移除，您可能想要从数据库中删除它的长期统计数据。
您是否想要从数据库中永久删除“sensor.zhimi_airpurifier_ma2_filter_life_remaining”的长期统计数据 ？

### Entity attributes / 实体属性

```yaml
entity_class: MiotSensorSubEntity
parent_entity_id: fan.zhimi_airpurifier_ma2
service_description: Filter
property_description: Filter Life Level
updated_time: 2024-12-01T22:59:47.288008+08:00
filter.filter_life_level: 60
unit_of_measurement: %
icon: mdi:percent
friendly_name: 小米空净2S Filter Life Level
supported_features: 0
```
