### ISSUE TITLE
小米watch color 2手表传感器无法正常获取数据

### ISSUE THREAD

**Issue by ZhaiSoul** [al-one/hass-xiaomi-miot#1987]
### Device model / 设备型号

midr.watch.k63

### Component version / 插件版本

0.7.25

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![Screenshot_2024-12-03-03-45-18-247_io homeassistant companion android](https://github.com/user-attachments/assets/12661f22-5af2-4c31-bae3-bed5e36ac22d)

目前是否还支持小米watch color 2呢？添加了设备后传感器依然是未知，是需要开启手表的WiFi吗？

### Entity attributes / 实体属性

```yaml
model: midr.watch.k63
lan_ip: ""
mac_address: 44:27:F3:47:E1:24
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:watch:0000A07C:midr-k63:1
state_property: vital_signs.heart_rate
vital_signs.heart_rate.error: "-704090001 Device does not exist"
vital_signs.respiratory_rate.error: "-704090001 Device does not exist"
battery_level.error: "-704090001 Device does not exist"
battery.charging_state.error: "-704090001 Device does not exist"
battery.voltage.error: "-704090001 Device does not exist"
motion_data.current_step_count.error: "-704090001 Device does not exist"
current_calorie_consumption-4-2.error: "-704090001 Device does not exist"
motion_data.current_distance.error: "-704090001 Device does not exist"
watch.on.error: "-704090001 Device does not exist"
watch.status.error: "-704090001 Device does not exist"
watch.fault.error: "-704090001 Device does not exist"
watch.longitude.error: "-704090001 Device does not exist"
watch.latitude.error: "-704090001 Device does not exist"
watch.current_address.error: "-704090001 Device does not exist"
state_updater: cloud
unit_of_measurement: bpm
icon: mdi:heart-pulse
friendly_name: Xiaomi Watch Color 2    Vital Signs Heart Rate
supported_features: 0
```
