### ISSUE TITLE
translations not work after update to v0.4.5

### ISSUE THREAD

**Issue by boyphongsakorn** [al-one/hass-xiaomi-miot#199]
i translations from chinese to english this is work in v0.4.4
but after update to v0.4.5
translations from chinese to english is not working

**Comment by al-one** [comment]
Show me your translation config.

**Comment by boyphongsakorn** [comment]
> Show me your translation config.

xiaomi_miot:
  translations:
    mode:
      静音: "silent"
      标准: "basic"
      自动: "auto"
      低档: "low"
      中档: "medium"
      高档: "high"
      强力: "strong"
    fan_level:
      静音: "silent"
      标准: "basic"
      自动: "auto"
      低档: "low"
      中档: "medium"
      高档: "high"
      强力: "strong"

this config work in v0.4.4

**Comment by al-one** [comment]
Please upgrade to commit: https://github.com/al-one/hass-xiaomi-miot/commit/d15f369dd33f126d4e87dc9bee8c63a76491ce53 and try again.

**Comment by shummo** [comment]
HI. I need some helmp with the translating.
I have a chuangmi.remote.h102c01 IR remote. I have configured some controller under MI HOME app (TV remote / speaker/ climate).

The Climate controller translated  good. But the others not. There are lot's of chinese characters: 
The IR Remote attibutes looks like this:

```
model: chuangmi.remote.h102c01
lan_ip: 192.168.1X.XX
mac_address: 40:X:X:X:X:11
firmware_version: 2.0.6_0001
hardware_version: ''
entity_class: MiotRemoteEntity
state_updater: none
ir_devices:
  - did: ir.1466911367289286656
    name: Air Conditioner Remote Control
    keys: []
  - did: ir.1466911668759097346
    name: TV Remote Control
    keys:
      - id: 1
        name: POWER
        display_name: 电源
      - id: 10032
        name: SmartTv
        display_name: SmartTv
      - id: 10033
        name: Subtitle
        display_name: Subtitle
      - id: 101
        name: '9'
        display_name: '9'
      - id: 10110
        name: Format
        display_name: Format
      - id: 106
        name: MUTE
        display_name: 静音
      - id: 111
        name: INPUT
        display_name: 信号源
      - id: 1112
        name: OPTIONS
        display_name: 选项
      - id: 116
        name: BACK
        display_name: 返回
      - id: 121
      ...

```
The IR remote SUB device attributes looks like this.   

`options: 电源, SmartTv, Subtitle, 9, Format, 静音, 信号源, 选项, 返回, EXIT, 交替, HOMEPAGE, 快退, 播放, 快进, 录音, 停止, 暂停, 鼠标, 列表, 信息, 红, 绿, 蓝, 黄, 流光溢彩, 3D, 比例调整, GUIDE, 调整, 智能电视, 流声溢彩, 流光幻彩, 功能列表, 确认, 频道+, SET, 频道-, TV, 菜单, 上, 下, NAVIGATE_LEFT, 右, 音量+, 音量-, 0, 1, RETURN, Source, 2, 3, 4, 帮助, 5, 6, 7, 图文, 8 entity_class: SelectSubEntity parent_entity_id: remote.imi_remote_2 friendly_name: TV Remote Control supported_features: 0`


I tried to translate it in configuration.yaml like this:
```
xiaomi_miot:
  translations:
    # Global dictionary
    电源: 'POWER'
```

I already tried the following format:
    '电源': 'POWER'
    电源: 'POWER'

**Comment by al-one** [comment]
@shummo Added in https://github.com/al-one/hass-xiaomi-miot/commit/57a963060ccfe9d6237f5f15b96dcd05b102a103, upgrade to master branch and try:
```yaml
xiaomi_miot:
  translations:
    ir_devices:
      '电源': POWER
```
