### ISSUE TITLE
米家新风机一直保持打开状态

### ISSUE THREAD

**Issue by Young1223** [al-one/hass-xiaomi-miot#1990]
# Device model / 设备型号
[dmaker.airfresh.t2017](https://home.miot-spec.com/s/dmaker.airfresh.t2017)

# Component version / 插件版本
0.7.24/0.7.25

# HA core version / HA版本
2024.10.2

# Integrated mode / 集成方式
Automatic (自动模式)

# The problem / 问题详情

更新了v0.7.24和v0.7.25后，新风机开关（fan.dmaker_t2017_xxxx_air_fresh）一直显示开启，手动关闭之后立刻又会自动开启，但机器本身还是关闭状态，退回到0.7.23就一切正常

**Comment by al-one** [comment]
提供debug日志。
- https://github.com/al-one/hass-xiaomi-miot/issues/500#debug

**Comment by Young1223** [comment]
[home-assistant_xiaomi_miot_2024-12-03T11-04-55.576Z.log](https://github.com/user-attachments/files/17991792/home-assistant_xiaomi_miot_2024-12-03T11-04-55.576Z.log)

更新到最新的还是一样的状况，如果米家提前把新风机打开，在ha里手动关闭，新风机可以正常关闭，但是开关还是会回到开启的状态

**Comment by Young1223** [comment]
> 提供debug日志。
> 
> * [登录失败/没有实体等常见问题解决办法 #500 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/500#debug)

![Uploading 开关状态.gif…]()

**Comment by ympchuan** [comment]
问题相同

**Comment by Young1223** [comment]
删除了新风机之后再添加，新风机直接显示不出来了……检查了日志，没有跟新风机相关的信息

**Comment by Young1223** [comment]
局域网添加的话新风机状态一直显示关闭，也无法通过ha打开新风机实体

**Comment by cbdoglolz** [comment]
同样问题，暂时用另外个单独添加使用

**Comment by al-one** [comment]
尝试master分支。
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

并通过开发者工具执行以下动作后反馈结果:
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: fan.dmaker_t2017_ed3a_air_fresh
  method: get_prop
  params: [power]
```
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: fan.dmaker_t2017_ed3a_air_fresh
  method: get_prop
  params: ['power', 'mode', 'pm25', 'co2', 'temperature_outside', 'favourite_speed', 'control_speed', 'ptc_on', 'ptc_status', 'child_lock', 'sound', 'display']
```
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: fan.dmaker_t2017_ed3a_air_fresh
  method: get_prop
  params: ['filter_intermediate', 'filter_inter_day', 'filter_efficient', 'filter_effi_day', 'ptc_level', 'screen_direction']
```
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: fan.dmaker_t2017_ed3a_air_fresh
  method: get_prop
  params: ['power', 'mode', 'pm25', 'co2', 'temperature_outside', 'favourite_speed', 'control_speed', 'ptc_on', 'ptc_status', 'child_lock', 'sound', 'display', 'filter_intermediate', 'filter_inter_day', 'filter_efficient', 'filter_effi_day', 'ptc_level', 'screen_direction']
```
