### ISSUE TITLE
六口插座，能识别，但不能控制

### ISSUE THREAD

**Issue by star2k** [al-one/hass-xiaomi-miot#1991]
### Device model / 设备型号

电小酷米家只能排插分控插座-iot.plug.pw6u1

### Component version / 插件版本

1.0.1

### HA core version / HA版本

20241106.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

能识别，但无法控制，开关均为灰色
![image](https://github.com/user-attachments/assets/709191c7-bb9e-49f3-a800-68fca4cc3973)

### Entity attributes / 实体属性

```yaml
button.iot_pw6u1_c3f5_info
----------------------------
info: 中心光路控制
model: iot.plug.pw6u1
did: 847696112
mac: E8:4A:54:C2:C3:F5
lan_ip: 192.168.2.174
app_link: mihome://device?uid=37085878&did=847696112
miot_type: urn:miot-spec-v2:device:outlet:0000A002:iot-pw6u1:1:0000D032
available: false
home_room: 默认家庭 中心机房
icon: mdi:information-off
updater: none
updated_at: 
converters: info, switch.on, switch-7.on, switch-8.on, switch-9.on, switch-10.on, switch-13.on, indicator_light.on, electric_power-3-2, electric_current-3-4, power_consumption.voltage
customizes: 
{}

miot_error: Unable to discover the device 192.168.2.174
device_class: update
friendly_name: 中心光路控制 信息
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.device.iot.plug.pw6u1
来源: custom_components/xiaomi_miot/core/device.py:720
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 13:46:50 (59 次总计出现)
上次记录: 14:20:40

Got MiioException while fetching the state: Unable to discover the device 192.168.2.174, mapping: {'custom.indicator_set': {'siid': 14, 'piid': 1}, 'custom.circle_task_one': {'siid': 14, 'piid': 2}, 'custom.circle_task_two': {'siid': 14, 'piid': 3}, 'custom.circle_task_three': {'siid': 14, 'piid': 4}, 'custom.circle_task_four': {'siid': 14, 'piid': 5}, 'custom.circle_task_five': {'siid': 14, 'piid': 6}, 'custom.circle_task_six': {'siid': 14, 'piid': 7}, 'custom.circle_task_usb': {'siid': 14, 'piid': 8}, 'custom.child_lock': {'siid': 14, 'piid': 9}, 'sixth_switch.on': {'siid': 12, 'piid': 1}, 'fifth_switch.on': {'siid': 11, 'piid': 1}, 'switch-13.on': {'siid': 13, 'piid': 1}, 'switch-10.on': {'siid': 10, 'piid': 1}, 'switch-9.on': {'siid': 9, 'piid': 1}, 'switch-8.on': {'siid': 8, 'piid': 1}, 'switch-7.on': {'siid': 7, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'power_consumption': {'siid': 3, 'piid': 1}, 'electric_power-3-2': {'siid': 3, 'piid': 2}, 'power_consumption_accumulate_way-3-3': {'siid': 3, 'piid': 3}, 'electric_current-3-4': {'siid': 3, 'piid': 4}, 'power_consumption.voltage': {'siid': 3, 'piid': 5}, 'switch.on': {'siid': 2, 'piid': 1}, 'switch.default_power_on_state': {'siid': 2, 'piid': 2}, 'switch.fault': {'siid': 2, 'piid': 3}}, max_properties: 9/25
