### ISSUE TITLE
9am升降桌部分实体不可用

### ISSUE THREAD

**Issue by HoganChou** [al-one/hass-xiaomi-miot#1992]
### Device model / 设备型号

[nineam.desk.hoo01](https://home.miot-spec.com/s/nineam.desk.hoo01)

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

1.0以后的版本中，设备目标高度和桌子控制功能两个实体全部不可用。0.7+版本的则正常可以调用

1.0.0+版本设备界面
![1.0.0+版本](https://s1.locimg.com/2024/12/03/bcbebb80ba86f.png)
0.7+版本设备界面
![0.7+版本](https://s1.locimg.com/2024/12/03/d186b4556fe10.png)

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 升降桌 信息
info: 升降桌
model: nineam.desk.hoo01
did: "475793955"
mac: EC:4D:3E:8D:B0:19
lan_ip: 192.168.11.14
app_link: mihome://device?uid=xxxx&did=475793955
miot_type: urn:miot-spec-v2:device:table:0000A068:nineam-hoo01:1
available: true
home_room: Hogan's Home 卧室
updater: local
updated_at: "2024-12-03 14:22:59.377079+08:00"
converters:
  - info
  - table.motor_control-0
  - standing_desk.moving_status
  - standing_desk.current_height
  - standing_desk.fault
  - standing_desk.lock_status
  - desk_reminder.on
  - standing_desk.target_height
  - standing_desk.stand_height
  - standing_desk.sit_height
  - desk_reminder.interval
  - standing_desk.desk_control
  - desk_reminder.mode
customizes:
  button_properties: motor_control,reset
  switch_properties: on,lock_status
  select_properties: mode,desk_control
  number_properties: interval,altitude,target_height,stand_height,sit_height,target_position
  state_property: standing_desk.moving_status
  sensor_properties: current_height,fault,moving_status
desk_reminder.interval: 45
desk_reminder.mode: 5
desk_reminder.on: false
standing_desk.lock_status: true
standing_desk.moving_status: 1
standing_desk.current_height: 1201
standing_desk.fault: 0
standing_desk.stand_height: 1200
standing_desk.sit_height: 720
```
