### ISSUE TITLE
石头机器人S5在更新1.01版本之后，部分实体消失了

### ISSUE THREAD

**Issue by LUOZEYUE** [al-one/hass-xiaomi-miot#1995]
### Device model / 设备型号

roborock.vacuum.s5

### Component version / 插件版本

1.01

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

部分实体消失了，比如那个点一下就启动机器人的石头。我删除重新添加也不行。现在只有如图几个实体。
![屏幕截图 2024-12-03 172908](https://github.com/user-attachments/assets/fe08238e-cf34-4489-8478-32df693a231d)

### Entity attributes / 实体属性

```yaml
info: null
model: roborock.vacuum.s5
did: "74457781"
mac: 78:11:DC:81:E4:47
lan_ip: 192.168.31.176
app_link: mihome://device?uid=42198941&did=74457781
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:roborock-s5:1
available: true
home_room: 我爱我家 客厅
icon: mdi:information
updater: local
updated_at: "2024-12-03 17:23:30.635021+08:00"
converters:
  - info
  - battery_level
  - vacuum.status
  - props:clean_area
  - props:clean_time
  - brush_life_level
customizes:
  sensor_attributes: props:clean_area,props:clean_time,brush_life_level
  sensor_properties: vacuum.status
  select_properties: water_level,mop_mode
battery_level: 100
vacuum.status: 3
battery.charging_state: 1
vacuum.mode: 104
device_class: update
friendly_name: 扫地机器人 信息
```

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.vacuum
来源: helpers/entity_platform.py:728
集成: 扫地机 (文档, 问题)
首次出现: 17:16:14 (1 次总计出现)
上次记录: 17:16:14

xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 291, in async_update
    await self.device.dispatch(self.device.encode({'props': props}))
TypeError: object NoneType can't be used in 'await' expression
