### ISSUE TITLE
青萍动作和环境光传感器光照度实体消失了

### ISSUE THREAD

**Issue by hanzibeichen** [al-one/hass-xiaomi-miot#1997]
### Device model / 设备型号

cgllc.motion.cgpr1

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

插件更新到1.0.1版本之后，青萍动作和环境光传感器（cgllc.motion.cgpr1），光照度实体消失了，无法使用，删除重新添加也不行，重新下载1.0.1集成也不行。更新1.0.1版本之前的0.7.25，是可以使用的。

### Entity attributes / 实体属性

```yaml
info: 客厅青萍传感器
model: cgllc.motion.cgpr1
did: blt.3.1jh2istbc4k00
mac: 58:2D:34:61:05:BC
lan_ip: ""
app_link: mihome://device?uid=16319620&did=blt.3.1jh2istbc4k00
miot_type: urn:miot-spec-v2:device:motion-sensor:0000A014:cgllc-cgpr1:1
available: true
home_room: 北辰的家庭 客厅
icon: mdi:information
updater: cloud
updated_at: "2024-12-03 18:04:59.357937+08:00"
converters:
  - info
  - battery_level
customizes: {}
battery_level: 84
motion_sensor.illumination: 0
no_motion_duration-2-2: 10
device_class: update
friendly_name: 客厅青萍传感器 信息
```
