### ISSUE TITLE
v1.0.* broke yeelink.curtain.ctmt2 support 

### ISSUE THREAD

**Issue by almirus** [al-one/hass-xiaomi-miot#2001]
### Device model / 设备型号

yeelink.curtain.ctmt2

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

The new version of the integration broke curtain support:

The operating mode selection is no longer available.
Statuses, such as open/closed curtains, are no longer displayed.
A phantom device has appeared.

![image](https://github.com/user-attachments/assets/fb346e9b-38db-4fb9-8c06-2f487fe5a324)

### Entity attributes / 实体属性

```yaml
For real device
device_class: curtain
friendly_name: Шторы гостиная Curtain
supported_features: 15

For phantom device
restored: true
device_class: curtain
friendly_name: Xiaomi Miot Штора
supported_features: 15
```
