### ISSUE TITLE
小米智能养生壶更新后无法使用

### ISSUE THREAD

**Issue by azir12345** [al-one/hass-xiaomi-miot#2004]
### Device model / 设备型号

[chunmi.health_pot.a1](https://home.miot-spec.com/s/chunmi.health_pot.a1)

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.11.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

更新前水壶可以使用，更新后无论什么按键都异常，提示无法执行动作“select/select_option” 。 Unable to discover the device 192.168.1.164

### Entity attributes / 实体属性

```yaml
info: Mi Smart Multi-functional Kettle
model: chunmi.health_pot.a1
did: "646078826"
mac: DC:ED:83:D0:36:EF
lan_ip: 192.168.1.164
app_link: mihome://device?uid=xxxx&did=646078826
miot_type: urn:miot-spec-v2:device:health-pot:0000A051:chunmi-a1:3
available: true
home_room: 宿舍 宿舍
icon: mdi:information
updater: local
updated_at: "2024-12-04 02:36:26.282958+08:00"
converters:
  - info
  - health_pot.status
  - health_pot.fault
  - health_pot.cancel_cooking
  - health_pot.start_cook
customizes:
  button_actions: cancel_cooking
  select_actions: start_cook
health_pot.status: 1
health_pot.fault: 0
custom.menu_id: 8
custom.cook_total_time: 180
custom.left_time: 0
custom.temperature: 27
custom.kw_left_time: 0
custom.kw_temperature: 45
custom.ctrl_temperature: 45
custom.auto_keepwarm: 1
custom.recipe_type: 0
custom.power_value: 10
custom.pre_left_time: 0
custom.custom_save_flag: 0
custom.cook_mode: 6
custom.kw_total_time: 25
custom.cook_time_dif: 0
custom.power_total: 0
custom.power_cur_pos: 0
custom.p_cur_pos_time: 0
custom.cur_left_time: 0
health_pot.left_time: 0
miot_error: Unable to discover the device 192.168.1.164
health_pot.cancel_cooking: null
device_class: update
friendly_name: Mi Smart Multi-functional Kettle 信息
```

### Home Assistant Logs / 系统日志

日志记录器: custom_components.xiaomi_miot.core.device.chunmi.health_pot.a1
来源: custom_components/xiaomi_miot/core/device.py:720
集成: Xiaomi Miot Auto ([文档](https://github.com/al-one/hass-xiaomi-miot), [问题](https://github.com/al-one/hass-xiaomi-miot/issues))
首次出现: 02:24:03 (11 次总计出现)
上次记录: 02:34:56

Got MiioException while fetching the state: Unable to discover the device 192.168.1.164, mapping: {'custom.menu_id': {'siid': 5, 'piid': 1}, 'custom.cook_total_time': {'siid': 5, 'piid': 2}, 'custom.left_time': {'siid': 5, 'piid': 3}, 'custom.temperature': {'siid': 5, 'piid': 4}, 'custom.kw_left_time': {'siid': 5, 'piid': 5}, 'custom.kw_temperature': {'siid': 5, 'piid': 6}, 'custom.ctrl_temperature': {'siid': 5, 'piid': 7}, 'custom.auto_keepwarm': {'siid': 5, 'piid': 8}, 'custom.recipe_type': {'siid': 5, 'piid': 9}, 'custom.power_value': {'siid': 5, 'piid': 10}, 'custom.pre_left_time': {'siid': 5, 'piid': 11}, 'custom.custom_save_flag': {'siid': 5, 'piid': 12}, 'custom.cook_mode': {'siid': 5, 'piid': 18}, 'custom.kw_total_time': {'siid': 5, 'piid': 24}, 'custom.cook_time_dif': {'siid': 5, 'piid': 27}, 'custom.power_total': {'siid': 5, 'piid': 31}, 'custom.power_cur_pos': {'siid': 5, 'piid': 32}, 'custom.p_cur_pos_time': {'siid': 5, 'piid': 33}, 'custom.cur_left_time': {'siid': 5, 'piid': 36}, 'health_pot.status': {'siid': 2, 'piid': 1}, 'health_pot.fault': {'siid': 2, 'piid': 2}, 'health_pot.left_time': {'siid': 2, 'piid': 4}}, max_properties: 8/22
