### ISSUE TITLE
更新1.0.1后扫地机器人部分实体没了

### ISSUE THREAD

**Issue by int2147483647** [al-one/hass-xiaomi-miot#2005]
### Device model / 设备型号

rockrobo.vacuum.v1

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.11.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

扫地机器人控制按钮和部分传感器不可用,显示不在提供该实体

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 扫地机器人 信息
info: null
model: rockrobo.vacuum.v1
did: 
mac: 
lan_ip: 
app_link: 
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:rockrobo-v1:1
available: true
home_room: 家 客厅
updater: local
updated_at: 2024-12-04 10:10:21.417381+08:00
converters: info, battery_level, vacuum.status, props:clean_area, props:clean_time
customizes: 
sensor_attributes: props:clean_area,props:clean_time
sensor_properties: vacuum.status
extend_miot_specs:
  - iid: 2
    properties:
      - iid: 2
        value-range:
          - 10
          - 100
          - 10

battery_level: 87
vacuum.status: 3
battery.charging_state: 1
vacuum.speed_level: 60
```

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.vacuum
来源: helpers/entity_platform.py:728
集成: 扫地机 ([文档](https://www.home-assistant.io/integrations/vacuum), [问题](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vacuum%22))
首次出现: 10:09:19 (2 次总计出现)
上次记录: 10:12:36

xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 291, in async_update
    await self.device.dispatch(self.device.encode({'props': props}))
TypeError: object NoneType can't be used in 'await' expression
