### ISSUE TITLE
Problems with model ijai.vacuum.v19

### ISSUE THREAD

**Issue by CommanderRedYT** [al-one/hass-xiaomi-miot#2007]
### Device model / 设备型号

ijai.vacuum.v19

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I cannot get the ijai.vacuum.v19 to work. It will always answer with `Unable to discover the device`. I tried all the things I found from other people with this model, but nothing is working.

### Entity attributes / 实体属性

```yaml
info: Xiaomi Robot Vacuum-Mop 2S
model: ijai.vacuum.v19
did: <did>
mac: <my-mac-address>
lan_ip: 192.168.0.161
app_link: mihome://device?uid=<uid>&did=<did>
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:ijai-v19:1
available: false
home_room: Dahoam
icon: mdi:information-off
updater: none
updated_at: 
converters: info, battery_level, vacuum.status, sweep.side_brush_life, sweep.main_brush_life, sweep.hypa_life, sweep.mop_life, vacuum.on, alarm, sweep.repeat_state, vacuum.mode, vacuum.sweep_type, sweep.water_state
customizes: 
sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
switch_properties: vacuum.on,repeat_state,alarm
select_properties: mode,sweep_type,water_state
exclude_miot_services: order
exclude_miot_properties: zone_points,restrict_points,target_point

miot_error: Unable to discover the device 192.168.0.161
device_class: update
friendly_name: Xiaomi Robot Vacuum-Mop 2S Info
```

### Home Assistant Logs / 系统日志

2024-12-04 09:13:05.467 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-04 09:13:14.550 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.ijai.vacuum.v19] Got MiioException while fetching the state: Unable to discover the device 192.168.0.161, mapping: {'disturb.dnd_enable': {'siid': 12, 'piid': 1}, 'disturb.dnd_start_hour': {'siid': 12, 'piid': 2}, 'disturb.dnd_start_minute': {'siid': 12, 'piid': 3}, 'disturb.dnd_end_hour': {'siid': 12, 'piid': 4}, 'disturb.dnd_end_minute': {'siid': 12, 'piid': 5}, 'disturb.multi_prop_dnd': {'siid': 12, 'piid': 7}, 'map.remember_state': {'siid': 10, 'piid': 1}, 'map.cur_map_id': {'siid': 10, 'piid': 2}, 'map.map_num': {'siid': 10, 'piid': 3}, 'map.cur_cleaning_path': {'siid': 10, 'piid': 5}, 'map.build_map': {'siid': 10, 'piid': 14}, 'map.has_new_map': {'siid': 10, 'piid': 19}, 'sweep.repeat_state': {'siid': 7, 'piid': 1}, 'sweep.door_state': {'siid': 7, 'piid': 3}, 'sweep.cloth_state': {'siid': 7, 'piid': 4}, 'sweep.suction_state': {'siid': 7, 'piid': 5}, 'sweep.water_state': {'siid': 7, 'piid': 6}, 'sweep.mop_route': {'siid': 7, 'piid': 7}, 'sweep.side_brush_life': {'siid': 7, 'piid': 8}, 'sweep.side_brush_hours': {'siid': 7, 'piid': 9}, 'sweep.main_brush_life': {'siid': 7, 'piid': 10}, 'sweep.main_brush_hours': {'siid': 7, 'piid': 11}, 'sweep.hypa_life': {'siid': 7, 'piid': 12}, 'sweep.hypa_hours': {'siid': 7, 'piid': 13}, 'sweep.mop_life': {'siid': 7, 'piid': 14}, 'sweep.mop_hours': {'siid': 7, 'piid': 15}, 'sweep.time_zone': {'siid': 7, 'piid': 20}, 'sweep.cur_lang': {'siid': 7, 'piid': 21}, 'sweep.cleaning_time': {'siid': 7, 'piid': 22}, 'sweep.cleaning_area': {'siid': 7, 'piid': 23}, 'sweep.dirt_recognize': {'siid': 7, 'piid': 35}, 'sweep.pet_recognize': {'siid': 7, 'piid': 36}, 'sweep.ai_recognize': {'siid': 7, 'piid': 42}, 'sweep.carpet_booster': {'siid': 7, 'piid': 44}, 'sweep.multi_prop_vacuum': {'siid': 7, 'piid': 45}, 'sweep.tank_shake': {'siid': 7, 'piid': 48}, 'sweep.shake_shift': {'siid': 7, 'piid': 50}, 'sweep.map_encrypt': {'siid': 7, 'piid': 55}, 'alarm': {'siid': 4, 'piid': 1}, 'alarm.volume': {'siid': 4, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 9}}, max_properties: 10/46
