### ISSUE TITLE
升级1.0.1后易来浴霸预设全部模式名称变成“模式”两个中文，无法区分不同模式，且无法控制

### ISSUE THREAD

**Issue by chenvd** [al-one/hass-xiaomi-miot#2010]
### Device model / 设备型号

[yeelink.bhf_light.v6](https://home.miot-spec.com/s/yeelink.bhf_light.v6)

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

从0.7.25升级到1.0.1后，易来浴霸的预设从英文变成了中文，除了off以外，其他模式全部都是“模式”两个中文，没有区分不同的模式，并且切换模式无效。即原来的“Ventilate”, "Defog"这些模式，升级后都变成了“模式”两个字，并且切换模式无效。或者也可以考虑升级后默认不翻译这些属性。谢谢

![iShot_2024-12-05_08 51 46](https://github.com/user-attachments/assets/0338d60e-1385-41bf-b777-99fe93ae72f9)

![iShot_2024-12-05_09 00 23](https://github.com/user-attachments/assets/eede9518-a604-4e33-9669-c46edb9ac885)

![iShot_2024-12-05_09 01 15](https://github.com/user-attachments/assets/dbdcd154-2ec7-4a81-9445-4c3d22aa5cb5)

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 浴霸 信息
info: 浴霸
model: yeelink.bhf_light.v6
did: 
mac: 
lan_ip: 
app_link: 
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v6:2
available: true
home_room: 我的家 卫生间
updater: local
updated_at: 2024-12-05 09:01:09.830304+08:00
converters: info, light.on, light.brightness, light.mode, ptc_bath_heater.temperature, target_temperature-3-2, ptc_bath_heater.heat_mode, ptc_bath_heater.cold_mode, ptc_bath_heater.vent_mode
customizes: 
sensor_properties: temperature
switch_properties: heating,blow,ventilation
select_properties: heat_mode,cold_mode,vent_mode
number_properties: target_temperature,off_delay_time
extend_miot_specs:
  - iid: 3
    properties:
      - iid: 1
        value-list:
          - value: 0
            description: Idle
          - value: 1
            description: Fan
          - value: 2
            description: Heat
          - value: 3
            description: Ventilate
          - value: 4
            description: Dry
          - value: 5
            description: Defog
          - value: 6
            description: Quick Heat
          - value: 7
            description: Quick Defog
      - iid: 101
        type: urn:miot-spec-v2:property:fan-level
        format: uint8
        access:
          - read
          - write
        value-list:
          - value: 1
            description: Low
          - value: 3
            description: High
      - iid: 111
        type: urn:miot-spec-v2:property:heat-mode
        format: uint8
        access:
          - read
          - write
        value-list:
          - value: 0
            description: 'Off'
          - value: 1
            description: Low
          - value: 2
            description: High
      - iid: 112
        type: urn:miot-spec-v2:property:cold-mode
        format: uint8
        access:
          - read
          - write
        value-list:
          - value: 0
            description: 'Off'
          - value: 1
            description: Low
          - value: 3
            description: High
      - iid: 113
        type: urn:miot-spec-v2:property:vent-mode
        format: uint8
        access:
          - read
          - write
        value-list:
          - value: 0
            description: 'Off'
          - value: 1
            description: Low
          - value: 3
            description: High

target_temperature-3-2: 35
ptc_bath_heater.temperature: 24
ptc_bath_heater.heat_mode: prop_err
ptc_bath_heater.cold_mode: prop_err
ptc_bath_heater.vent_mode: prop_err
light.on: false
light.mode: 1
method: set_properties
params: 
- siid: 2
  piid: 3
  did: ''
  value: 255

ptc_bath_heater.mode: 0
ptc_bath_heater.fan_level: 1
light.brightness: 100
```
