### ISSUE TITLE
米家空气净化器 4 Lite 空气质量显示为数字无法翻译成中文

### ISSUE THREAD

**Issue by FreeFlying0** [al-one/hass-xiaomi-miot#2013]
### Device model / 设备型号

zhimi.airp.rma3

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

在之前的版本中 空气质量返回值为英文，可以通过翻译成中文，但1.0.0之后返回值为数字无法翻译成中文。
![image](https://github.com/user-attachments/assets/79861eb2-b1d5-4412-bc00-1da10432bd14)

![image](https://github.com/user-attachments/assets/bf6fb360-7999-4031-8224-3e8f18fa41e6)

### Entity attributes / 实体属性

```yaml
info: Xiaomi Smart Air Purifier 4 Lite
model: zhimi.airp.rma3
did: "*"
mac: *
lan_ip: *
app_link: mihome://device?uid=*&did=*
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-rma3:1
available: true
home_room:  卧室
icon: mdi:information
updater: local
updated_at: "2024-12-05 11:37:35.248726+08:00"
converters:
  - info
  - physical_controls_locked
  - filter.filter_life_level
  - filter.filter_used_time
  - filter.filter_left_time
  - environment.relative_humidity
  - environment.pm2_5_density
  - environment.temperature
  - environment.air_quality
  - custom_service.moto_speed_rpm
  - alarm
  - screen.brightness
customizes:
  switch_properties: alarm
  sensor_properties: moto_speed_rpm
  select_properties: brightness
  number_properties: air_purifier_favorite.fan_level
custom_service.moto_speed_rpm: 0
physical_controls_locked: false
screen.brightness: 0
alarm: true
filter.filter_life_level: 91
filter.filter_used_time: 322
filter.filter_left_time: 132
environment.relative_humidity: 69
environment.pm2_5_density: 53
environment.temperature: 13
environment.air_quality: 2
aqi.aqi_updata_heartbeat: 300
filter_used_time_dbg-9-2: 322
air_purifier_favorite.fan_level: 4
air_purifier.on: false
air_purifier.fault: 0
air_purifier.mode: 0
device_class: update
friendly_name: 空气净化器 信息
```
