### ISSUE TITLE
Temperature no longer available after update to HA 2024.12.0

### ISSUE THREAD

**Issue by xmicky** [al-one/hass-xiaomi-miot#2016]
### Device model / 设备型号

miaomiaoce.sensor_ht.t2

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

After December system 2024.12.0 upgrade temperature no longer available. Humidity is available
Applies to both types of sensor I use:
miaomiaoce.sensor_ht.t2
cgllc.sensor_ht.dk2

### Entity attributes / 实体属性

```yaml
info: Campervan Temperature
model: miaomiaoce.sensor_ht.t2
did: blt.3.1b5havcik5g01
mac: A4:C1:38:6B:D3:71
lan_ip: 
app_link: mihome://device?uid=6261124586&did=blt.3.1b5havcik5g01
miot_type: urn:miot-spec-v2:device:temperature-humidity-sensor:0000A00A:miaomiaoce-t2:1
available: true
home_room: 196 Study
icon: mdi:information
updater: cloud
updated_at: 2024-12-05 13:42:12.556478+00:00
converters: info, temperature-2-1, relative_humidity-2-2, battery_level
customizes: 
{}

battery_level: 100
temperature-2-1: 13
relative_humidity-2-2: 90
device_class: update
friendly_name: Campervan Temperature Info
```
