### ISSUE TITLE
小米门窗传感器2 光照度实体不可用

### ISSUE THREAD

**Issue by hanzibeichen** [al-one/hass-xiaomi-miot#2017]
### Device model / 设备型号

isa.magnet.dw2hl

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

插件更新到1.0.1版本之后，小米门窗传感器2 （isa.magnet.dw2hl），光照度实体不可用，重新下载1.0.1集成也不行。更新1.0.1版本之前的0.7.25，是可以使用的。

### Entity attributes / 实体属性

```yaml
info: 门窗传感器
model: isa.magnet.dw2hl
did: blt.3.1h3p7ha1ock00
mac: E4:AA:EC:92:7D:7D
lan_ip: 36.60.84.90
app_link: mihome://device?uid=16319620&did=blt.3.1h3p7ha1ock00
miot_type: urn:miot-spec-v2:device:magnet-sensor:0000A016:isa-dw2hl:1
available: true
home_room: 北辰的家庭 车库
icon: mdi:information
updater: cloud
updated_at: "2024-12-05 21:49:49.818393+08:00"
converters:
  - info
  - battery_level
customizes: {}
battery_level: 100
magnet_sensor.illumination: 1
magnet_sensor.contact_state: true
device_class: update
friendly_name: 门窗传感器 信息
```

### Home Assistant Logs / 系统日志

![1733407259098](https://github.com/user-attachments/assets/8af4ddeb-a3d4-4c92-8260-628c2cfc2d7b)
