### ISSUE TITLE
Mi Crossover Range Hood S1

### ISSUE THREAD

**Issue by fanyan1026** [al-one/hass-xiaomi-miot#2027]
### Device model / 设备型号

[Mi Crossover Range Hood S1](https://home.miot-spec.com/s/viomi.hood.v5)

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

本地集成失败，自动集成可以，集成后是离线状态

### Entity attributes / 实体属性

```yaml
info: Mi Crossover Range Hood S1
model: viomi.hood.v5
did: "473614111"
mac: EC:4D:3E:6C:6D:15
lan_ip: 192.168.0.88
app_link: mihome://device?uid=xxxx&did=473614111
miot_type: urn:miot-spec-v2:device:hood:0000A01B:viomi-v5:1
available: false
home_room: 1101 厨房
icon: mdi:information-off
updater: none
updated_at: ""
converters:
  - info
  - light.on
customizes: {}
miot_error: Unable to discover the device 192.168.0.88
device_class: update
friendly_name: Mi Crossover Range Hood S1 信息
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.device.viomi.hood.v5
来源: custom_components/xiaomi_miot/core/device.py:720
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 12:55:19 (741 次总计出现)
上次记录: 19:05:47

Got MiioException while fetching the state: Unable to discover the device 192.168.0.88, mapping: {'function.power_on_light': {'siid': 9, 'piid': 1}, 'function.power_off_light': {'siid': 9, 'piid': 2}, 'function.clean_remine_on': {'siid': 9, 'piid': 3}, 'function.clean_remine_time': {'siid': 9, 'piid': 4}, 'function.cruise_on': {'siid': 9, 'piid': 5}, 'function.holiday_on': {'siid': 9, 'piid': 6}, 'function.holiday_cycle': {'siid': 9, 'piid': 7}, 'function.holiday_start_time': {'siid': 9, 'piid': 8}, 'function.holiday_duration': {'siid': 9, 'piid': 9}, 'function.delay_time': {'siid': 9, 'piid': 10}, 'function.gestures': {'siid': 9, 'piid': 11}, 'bluetooth.status': {'siid': 7, 'piid': 1}, 'bluetooth.light_on': {'siid': 7, 'piid': 2}, 'stove.battery_life': {'siid': 6, 'piid': 3}, 'stove.work_remine_time': {'siid': 6, 'piid': 4}, 'stove.left_status': {'siid': 6, 'piid': 5}, 'stove.right_status': {'siid': 6, 'piid': 6}, 'stove.stove_bind': {'siid': 6, 'piid': 7}, 'fan_control.fan_level': {'siid': 10, 'piid': 2}, 'light.on': {'siid': 5, 'piid': 1}, 'hood.fault': {'siid': 2, 'piid': 1}, 'hood.on': {'siid': 2, 'piid': 2}, 'hood.off_delay_time': {'siid': 2, 'piid': 4}, 'hood.off_delay': {'siid': 2, 'piid': 5}, 'hood.countdown_time': {'siid': 2, 'piid': 7}}, max_properties: 9/25
