### ISSUE TITLE
chuangmi.camera.ipc009 Can't start stream

### ISSUE THREAD

**Issue by NitayRabi** [al-one/hass-xiaomi-miot#2028]
### Device model / 设备型号

chuangmi.camera.ipc009

### HA core version / HA版本

chuangmi.camera.ipc009

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Cannot start stream (works in Mi Home)

### Entity attributes / 实体属性

```yaml
access_token: XXXX
model_name: chuangmi.camera.ipc009
brand: chuangmi
frontend_stream_type: hls
stream_address: ""
expire_at: "2024-12-06 14:53:32.798216"
stream_status-3-1: 1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: false
glimmer_full_color-2-6: true
camera_control.recording_mode: 3
camera_control.motion_tracking: false
state_updater: cloud
motion_video_time: "2024-12-06 13:53:58.708000"
motion_video_type: ObjectMotion
motion_video_latest:
  startDuration: 0
  cut: false
  offset: 0
  isCloud: false
  isRead: false
  videoStoreId: FREE_HOME_SUR_DEFAULT_STORE_ID
  eventType: ObjectMotion
  expireTime: 1733576038708
  isAlarm: true
  isShowImg: false
  location: aws
  imgStoreId: FREE_HOME_SUR_DEFAULT_STORE_ID
  fileId: >-
   XXX
  extraInfo: "0"
entity_picture: >-
  /api/camera_proxy/camera.chuangmi_ipc009_5d57_camera_control_2?token=XXX
friendly_name: Video camera Camera Control
supported_features: 3
video_attribute: 2
```

### Home Assistant Logs / 系统日志

Video camera(chuangmi.camera.ipc009): Get miot camera stream error from cloud: {'did': '263657598', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': 0, 'out': ['https://de18.livestreaming.io.mi.com/hlstranscoder/XXX/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
Video camera(chuangmi.camera.ipc009): Get miot camera stream error from cloud: {'did': '263657598', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': 0, 'out': ['https://de24.livestreaming.io.mi.com/hlstranscoder/XXX/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
Video camera(chuangmi.camera.ipc009): Get miot camera stream error from cloud: {'did': '263657598', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': 0, 'out': ['https://de11.livestreaming.io.mi.com/hlstranscoder/XXX/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
Video camera(chuangmi.camera.ipc009): Get miot camera stream error from cloud: {'did': '263657598', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': 0, 'out': ['https://de15.livestreaming.io.mi.com/hlstranscoder/XXX/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
Video camera(chuangmi.camera.ipc009): Get miot camera stream error from cloud: {'did': '263657598', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': 0, 'out': ['https://de16.livestreaming.io.mi.com/hlstranscoder/XXX/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
