### ISSUE TITLE
小爱触屏音箱的“执行指令”发送指令无反馈

### ISSUE THREAD

**Issue by MarcPolaris** [al-one/hass-xiaomi-miot#2029]
### Device model / 设备型号

xiaomi.wifispeaker.lx04

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

插件更新到1.0.1版本之后，小爱触屏音箱执行指令变成静态静默执行（xiaomi.wifispeaker.lx04），执行文本命令之后小爱无回应，不清楚是否执行成功，集成里删除重新添加也不行，重新下载1.0.2集成也不行。更新1.0.1版本之前的0.7.25，是正常的。

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 小爱触屏音箱 信息
info: 小爱触屏音箱
model: xiaomi.wifispeaker.lx04
did: "636651219"
mac: D4:DA:21:47:92:CA
lan_ip: 192.168.2.151
app_link: mihome://device?uid=xxxx&did=636651219
miot_type: urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx04:2
available: true
home_room: 北辰的家庭 工作室
updater: cloud
updated_at: "2024-12-06 22:31:31.888056+08:00"
converters:
  - info
  - intelligent_speaker.sleep_mode
  - intelligent_speaker.wake_up
  - clock.stop_alarm
  - intelligent_speaker.play_text
  - intelligent_speaker.execute_text_directive
customizes:
  switch_properties: on,sleep_mode,no_disturb
  button_actions: wake_up,play_music,tv_switchon,stop_alarm
  text_actions: play_text,execute_text_directive
intelligent_speaker.sleep_mode: false
intelligent_speaker.audio_id: "2213425565914056351"
microphone.mute: false
speaker.volume: 20
speaker.mute: true
intelligent_speaker.execute_text_directive:
  - 关闭显示器挂灯
  - 0
```
