### ISSUE TITLE
Lights no longer have "Transition" option.

### ISSUE THREAD

**Issue by joaommarques** [al-one/hass-xiaomi-miot#2030]
The transition option when turning on a light is no longer available since version 1.0

**Comment by joaommarques** [comment]
@al-one Thank you for your answer.
How do I transition from 100% to 30% brightness. I use this a lot in my automations.

**Comment by al-one** [comment]
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: light.yeelink_xxxx
  method: set_bright
  params: [30, smooth, 1000]
```
