### ISSUE TITLE
Entity fan.deerma_jsq2w_7146_fan_level does not set FanEntityFeature

### ISSUE THREAD

**Issue by himi420** [al-one/hass-xiaomi-miot#2032]
### Device model / 设备型号

deerma.humidifier.jsq2w (Xiaomi Smart Humidifier 2)

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

WARNING (MainThread) [homeassistant.components.fan] Entity fan.deerma_jsq2w_7146_fan_level (<class 'custom_components.xiaomi_miot.fan.MiotModesSubEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

### Entity attributes / 实体属性

```yaml
info: Xiaomi Smart Humidifier 2
model: deerma.humidifier.jsq2w
did: 658787650
mac: 64:9E:31:42:71:46
lan_ip: 192.168.1.186
app_link: mihome://device?uid=2908978183&did=658597650
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1
available: true
home_room: Living room
icon: mdi:information
updater: local
updated_at: 2024-12-06 22:17:39.201634+01:00
converters: info, indicator_light.on, environment.relative_humidity, environment.temperature, humidifier.fault, custom.the_tank_filed, custom.water_shortage_fault, alarm
customizes: 
chunk_properties: 6
exclude_miot_properties: humi_sensor_fault,temp_sensor_fault,overwet_protect,overtop_humidity
binary_sensor_properties: water_shortage_fault,the_tank_filed
sensor_properties: fault
switch_properties: alarm
exclude_miot_services: null

custom.the_tank_filed: false
custom.water_shortage_fault: false
indicator_light.on: true
alarm: true
environment.relative_humidity: 63
environment.temperature: 23
humidifier.fault: 0
custom.overwet_protect_on: true
humidifier.on: true
humidifier.fan_level: 1
humidifier.target_humidity: 60
humidifier.status: 2
humidifier.mode: 0
device_class: update
friendly_name: Xiaomi Smart Humidifier 2 Info
```

### Home Assistant Logs / 系统日志

2024-12-06 22:05:39.307 WARNING (MainThread) [homeassistant.components.fan] Entity fan.deerma_jsq2w_7146_fan_level (<class 'custom_components.xiaomi_miot.fan.MiotModesSubEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

2024-12-06 22:05:39.307 WARNING (MainThread) [homeassistant.components.fan] Entity fan.deerma_jsq2w_7146_fan_level (<class 'custom_components.xiaomi_miot.fan.MiotModesSubEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
