### ISSUE TITLE
米家新风机300缺少辅热实体

### ISSUE THREAD

**Issue by 389377616** [al-one/hass-xiaomi-miot#2033]
### Device model / 设备型号

dmaker.airfresh.t2017

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家新风机300缺少辅热实体，没办法控制辅热的开关

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 新风机 信息
info: 新风机
model: dmaker.airfresh.t2017
did: 437081636
mac: B4:60:ED:2B:E9:79
lan_ip: 192.168.1.26
app_link: mihome://device?uid=125847622&did=437081636
miot_type: urn:miot-spec-v2:device:air-fresh:0000A012:dmaker-t2017:2
available: true
home_room: 虎哥的家庭 卧室
updater: local
updated_at: 2024-12-07 08:21:50.615055+08:00
converters: info, physical_controls_locked, filter.filter_life_level, filter.filter_left_time, filter-5.filter_life_level, filter-5.filter_left_time, environment.pm2_5_density, environment.temperature, environment.co2_density
customizes: 
{}

physical_controls_locked: false
filter-5.filter_life_level: 75
filter-5.filter_left_time: 135
filter.filter_life_level: 50
filter.filter_left_time: 45
environment.pm2_5_density: 999
environment.temperature: 13
environment.co2_density: 1000
alarm: false
screen.on: true
air_fresh_favorite.fan_level: 12
air_fresh.on: true
air_fresh.mode: 1
air_fresh.heater: false
air_fresh.heat_level: 2
```
