### ISSUE TITLE
The device is unavailable.

### ISSUE THREAD

**Issue by Andrusha55** [al-one/hass-xiaomi-miot#2035]
### Device model / 设备型号

dmaker.humidifier.p2

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

My humidifier constantly becomes unavailable, even though it is turned on. This has been happening since version 1.0.0 up to 1.0.2. I rolled back to version 0.7.25, and everything works fine there.
![IMG_5949](https://github.com/user-attachments/assets/9438a7f1-8871-4b70-896a-13ee35d7ded0)

### Entity attributes / 实体属性

```yaml
min_humidity: 40
max_humidity: 70
available_modes:
  - "Off"
  - Constant Humidity
  - Sleep
  - Strong
current_humidity: 43
humidity: 60
mode: Strong
model: dmaker.humidifier.p2
lan_ip: 192.168.1.54
mac_address: B4:60:ED:C5:34:FC
entity_class: MiotHumidifierEntity
home_room: Мой дом Спальня
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:dmaker-p2:2
humidifier.on: true
humidifier.fault: 0
humidifier.mode: 2
humidifier.target_humidity: 60
dm_service.off_delay_time: 0
dm_service.water_status: 0
dm_service.water_level: 4
dm_service.over_wet_protect: false
dm_service.fan_dry_time: 0
filter.filter_life_level: 89
screen.on: false
screen.brightness: 1
physical_controls_locked: false
alarm: false
environment.relative_humidity: 43
environment.temperature: 20.5
state_updater: lan
sub_entities:
  - humidifier-2.fault-2
  - dm_service-7.water_level-3
  - dm_service-7.fan_dry_time-5
  - screen-8.on-1
  - dm_service-7.over_wet_protect-4
  - dm_service-7.off_delay_time-1
  - dm_service-7.loop_mode-1
  - environment-3.relative_humidity-1
  - environment-3.temperature-7
  - filter-9.filter_life_level-1
  - physical_controls_locked-6.physical_controls_locked-1
device_class: humidifier
friendly_name: Увлажнитель Humidifier
supported_features: 1
```

### Home Assistant Logs / 系统日志

7 декабря 2024 г.

Увлажнитель Humidifier  изменяет состояние на "Недоступно" действием Увлажнитель: Задать влажность
07:05:15 - 1 минуту назад - Andrey

Увлажнитель Humidifier  включается
07:03:34 - 3 минуты назад

Увлажнитель Humidifier  изменяет состояние на "Недоступно"
06:49:42 - 17 минут назад

Увлажнитель Humidifier  изменяет состояние на "Недоступно"
06:44:34 - 22 минуты назад

Увлажнитель Humidifier  включается
06:43:34 - 23 минуты назад
