### ISSUE TITLE
unable to clean single room with S20+

### ISSUE THREAD

**Issue by lucasabba** [al-one/hass-xiaomi-miot#2037]
Hi,
I'm trying to clean a single room (ID 3) with my Xiaomi S20+.

**HA version: 2024.12.1 (same problem with older version)
hass-xiaomi-miot version: latest available
Xiaomi model: Xiaomi S20+**

I tried the following action, but the robot starts cleaning all rooms:

```
data:
  entity_id: vacuum.xiaomi_b108gl_c0c0_robot_cleaner_2
  siid: 2
  aiid: 3
  params:
    - "3"
    - 0
    - 1
action: xiaomi_miot.call_action


```
Any idea?

**Comment by jumate** [comment]
I have figured out how to send the robot to a room.

From miot specs: 
https://home.miot-spec.com/spec/xiaomi.vacuum.b108gl

ssid: 2
aid:13
params: ["{\"room\":[5]}"]

![imagen](https://github.com/user-attachments/assets/3fb8a4b6-3bd7-4743-80c7-32c9948122e9)

**Comment by jumate** [comment]
For S20+

*** Set up rooms cleaning ***
action: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_b108gl_ca95_robot_cleaner
  siid: 2
  aiid: 10
  params:
    - "{\"room_attrs\":[{\"id\":8,\"room_name\":\"Alex\",\"fan_level\":2,\"water_level\":1,\"clean_mode\":1,\"clean_times\":1,\"mop_mode\":0,\"on\":true}]}"

*** Start custom cleaning***
action: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_b108gl_ca95_robot_cleaner
  siid: 6
  aiid: 7
  params: [ ]

**Comment by Mykls1** [comment]
[dreame.vacuum.p2009.json](https://github.com/user-attachments/files/18470277/dreame.vacuum.p2009.json) Can someone make a json file with scripts for s20+ similar to this file? For mi home vevs version scenaries

**Comment by suskozaver** [comment]
did anyone figure out why Clean times is ignored?

![Image](https://github.com/user-attachments/assets/1ff4d05e-f8eb-440d-8483-4a99a9f3551d)

**Comment by stoutouloutou** [comment]
Hello,
Thank you for your help !

I'm trying to do the same thing on a xiaomi S10+, refering to 
[its specs](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:dreame-r2211o:1)

```
 - action: xiaomi_miot.call_action
    metadata: {}
    data:
      siid: 2
      aiid: 3
      params: ["{\"room\":[5]}"]
      entity_id: vacuum.dreame_r2211o_robot_cleaner
```

but it doesn't work : nothing happens.
The "start-sweep action" AIID 1 works, so I thing the "params" section is incorrect... 
I tried several thing as params:
```
params: [5] (with several numbers...)
params: ["{\"room\":[ ]}"]
```

without any success...
Does anyone have an idea what I could try ?
Thanks!
