### ISSUE TITLE
更新1.0.2后加湿器dmaker.humidifier.p2间歇性不可用 

### ISSUE THREAD

**Issue by icceey** [al-one/hass-xiaomi-miot#2038]
### Device model / 设备型号

[dmaker.humidifier.p2](https://home.miot-spec.com/s/dmaker.humidifier.p2)

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

更新到1.0.2之后，加湿器间歇性不可用，不能通过HA开启/关闭/更改模式/设置目标湿度，但它的传感器之类的数据是一直可用的，此前用的插件版本是0.7.24

从HA的历史能看出来间歇性不可用：
![image](https://github.com/user-attachments/assets/8e6a508a-a81e-4bad-a077-809d43fdd75e)

不可用时的设备详情：
![image](https://github.com/user-attachments/assets/8a79641f-1be7-4a32-bce0-472c323227c0)

### Entity attributes / 实体属性

```yaml
info: Mijia Smart Evaporative Humidifier 2
model: dmaker.humidifier.p2
did: 548381151
mac: 68:AB:BC:41:81:5F
lan_ip: 192.168.5.148
app_link: mihome://device?uid=xxxx&did=548381151
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:dmaker-p2:2
available: true
home_room: 家 主卧
icon: mdi:information
updater: local
updated_at: 2024-12-07 17:06:33.039277+08:00
converters: info, physical_controls_locked, filter.filter_life_level, environment.relative_humidity, environment.temperature, humidifier.fault, dm_service.water_level, dm_service.fan_dry_time, screen.on, dm_service.over_wet_protect, dm_service.off_delay_time, dm_service.loop_mode
customizes: 
button_actions: loop_mode
sensor_properties: fault,water_level,fan_dry_time
switch_properties: over_wet_protect,screen.on
number_properties: off_delay_time

dm_service.off_delay_time: 0
dm_service.water_level: 8
dm_service.over_wet_protect: true
dm_service.fan_dry_time: 0
filter.filter_life_level: 92
screen.on: true
physical_controls_locked: false
environment.relative_humidity: 33
environment.temperature: 22.5
humidifier.fault: 0
dm_service.water_status: 0
screen.brightness: 1
alarm: false
humidifier.on: true
humidifier.mode: 2
humidifier.target_humidity: 52
miot_error: Unable to parse message payload
device_class: update
friendly_name: Mijia Smart Evaporative Humidifier 2 信息
```

### Home Assistant Logs / 系统日志

日志记录器: custom_components.xiaomi_miot.core.device.dmaker.humidifier.p2
来源: custom_components/xiaomi_miot/core/device.py:720
集成: Xiaomi Miot Auto ([文档](https://github.com/al-one/hass-xiaomi-miot), [问题](https://github.com/al-one/hass-xiaomi-miot/issues))
首次出现: 14:02:26 (105 次总计出现)
上次记录: 16:01:54

Got MiioException while fetching the state: Unable to parse message payload, mapping: {'dm_service.off_delay_time': {'siid': 7, 'piid': 1}, 'dm_service.water_status': {'siid': 7, 'piid': 2}, 'dm_service.water_level': {'siid': 7, 'piid': 3}, 'dm_service.over_wet_protect': {'siid': 7, 'piid': 4}, 'dm_service.fan_dry_time': {'siid': 7, 'piid': 5}, 'filter.filter_life_level': {'siid': 9, 'piid': 1}, 'screen.on': {'siid': 8, 'piid': 1}, 'screen.brightness': {'siid': 8, 'piid': 2}, 'physical_controls_locked': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 4, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}, 'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.mode': {'siid': 2, 'piid': 3}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}}, max_properties: 8/16
