### ISSUE TITLE
Missing Color Temperature Entity for yeelink.light.ceiling20 

### ISSUE THREAD

**Issue by daniel4999** [al-one/hass-xiaomi-miot#2039]
### Device model / 设备型号

Yeelight

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Since the last update, the entity for changing the color temperature of the lamp yeelink.light.ceiling20 has disappeared in Home Assistant. Currently, I can only control the RGB ambient light around the lamp but cannot adjust the main light's color temperature.

Device Details
Device Model: Yeelight Ceiling Lamp (yeelink.light.ceiling20)
Firmware Version: 2.1.7_0030
Component Version: Xiaomi Miot Auto (latest, 7.x)
HA Core Version: 2024.12.1
Integration Mode: Automatic (out-of-box)

Expected Behavior
The integration should expose an entity for adjusting the main light's color temperature in addition to the RGB ambient light control.

### Entity attributes / 实体属性

```yaml
info: Ceiling light
model: yeelink.light.ceiling20
did: 359242518
mac: 54:48:E6:5B:C1:AB
lan_ip: 192.168.1.165
app_link: mihome://device?uid=1545943782&did=359242518
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceiling20:1
available: true
home_room: Default family group Living Room
icon: mdi:information
updater: local
updated_at: 2024-12-07 10:31:57.235586+01:00
converters: info, light.on, light.brightness, light.color_temperature, light.mode, ambient_light.on, ambient_light.brightness, ambient_light.color_temperature, ambient_light.color, light.off_delay_time
customizes: 
number_properties: off_delay_time
switch_properties: bg_on
extend_miot_specs: yeelink.light.ceiling4

ambient_light.on: false
method: set_properties
params: 
- siid: 200
  piid: 202
  did: '359242518'
  value: 255
- siid: 2
  piid: 2
  did: '359242518'
  value: 255

ambient_light.color_temperature: 4685
ambient_light.color: 14128895
light.on: false
light.color_temperature: 5200
light.mode: 1
light.off_delay_time: 0
ambient_light.brightness: 100
light.brightness: 100
device_class: update
friendly_name: Ceiling light Info
```
