### ISSUE TITLE
人体传感器2的光照识别不可用

### ISSUE THREAD

**Issue by XieBrok** [al-one/hass-xiaomi-miot#2040]
### Device model / 设备型号

lumi.motion.bmgl01

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.10.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![25C4ABF4-B73F-4D51-BA21-BC6508B1A753](https://github.com/user-attachments/assets/204e32e8-9463-4c3a-b7a6-dbc767fc6ad7)由0.7.25更新至1.0.2后人体传感器的光照识别不可用

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: Mi Motion Sensor 2 信息
info: Mi Motion Sensor 2
model: lumi.motion.bmgl01
did: blt.3.1b8vhlaioe000
mac: 54:EF:44:C0:A6:F7
lan_ip: 
app_link: mihome://device?uid=2504950400&did=blt.3.1b8vhlaioe000
miot_type: urn:miot-spec-v2:device:motion-sensor:0000A014:lumi-bmgl01:1
available: true
home_room: 咸阳 卧室
updater: none
updated_at: 
converters: info, battery_level, motion_sensor.illumination, no_motion_duration-2-2, trigger_at, light_strong
customizes: 
sensor_properties: illumination,no_motion_duration
interval_seconds: 15
motion_timeout: 60
use_ble_object: true
sensor_attributes: trigger_at
binary_sensor_attributes: light_strong
extend_miot_specs:
  - iid: 2
    properties:
      - iid: 1
        type: urn:miot-spec-v2:property:illumination
        unit: lx
        value-list:
          - value: 1
            description: '0'
          - value: 2
            description: '100'
```
