### ISSUE TITLE
支持 VRF 空调内机本地控制

### ISSUE THREAD

**Issue by hjkcai** [al-one/hass-xiaomi-miot#2043]
接 #1237，我成功通过 python-miio 控制了 VRF 空调子设备

首先通过 `miiocli cloud` 查询到设备信息

```
== VRF Central Air-Con Gateway (Device online ) ==
        Model: 090615.gateway.ac10
        Token: 813c493c6fad11af255ef64ce55c56e2
        IP: 192.168.50.104 (mac: 84:46:93:E8:97:7E)
        DID: 827601753
        Locale: cn
        Sub devices:
                客厅空调
                        DID: proxy.827601753.00001
                        Model: 090615.aircondition.ktp
                客卧空调
                        DID: proxy.827601753.00002
                        Model: 090615.aircondition.ktp
                主卧空调
                        DID: proxy.827601753.00003
                        Model: 090615.aircondition.ktp
                书房空调
                        DID: proxy.827601753.00004
                        Model: 090615.aircondition.ktp
        Other fields:
                extra: {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '2.2.6_1008', 'needVerifyCode': 0, 'isPasswordEncrypt': 0}
                password:
                pid: 0
                permitLevel: 16
                reset_flag: 0
                adminFlag: 1
                show_mode: 1
                family_id: 0
                p2p_id:
                pd_id: 16704
                shareFlag: 0
                latitude: 0.0
                longitude: 0.0
                uid: ----------
```

然后运行 `raw_command`，将虚拟设备的 `did` 以字符串的形式传入：

```bash
miiocli -dd genericmiot \
  --ip 192.168.50.104 \
  --token 813c493c6fad11af255ef64ce55c56e2 \
  raw_command \
  action \
  '{"did":"proxy.827601753.00001","siid":2,"aiid":1,"in":[]}' #	air-conditioner:toggle

miiocli -dd genericmiot \
  --ip 192.168.50.104 \
  --token 813c493c6fad11af255ef64ce55c56e2 \
  raw_command \
  set_properties \
  '[{"did":"proxy.827601753.00001","siid":2,"piid":4,"value":16}]' # air-conditioner:target-temperature
```

上面的命令均成功执行，观察米家 App 成功切换了设备状态。说明通过直接指定 `did` 的方式就可以控制 VRF 空调子设备。

希望可以将该通信模式集成到 hass-xiaomi-miot 中，谢谢！
