### ISSUE TITLE
更新设备列表无法排除，也无法同步新设备

### ISSUE THREAD

**Issue by hanzibeichen** [al-one/hass-xiaomi-miot#2051]
### Device model / 设备型号

xiaomi.wifispeaker.lx04

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

更新设备列表，设备连接模式不管是自动·本地还是云端，都无法更新设备，选择排除模式中，然后勾选设备，提交之后设备还在集成内，无法排除，反之包含也是一样情况，无法同步新设备进入集成。

### Entity attributes / 实体属性

```yaml
info: 小爱触屏音箱
model: xiaomi.wifispeaker.lx04
did: "636651219"
mac: D4:DA:21:47:92:CA
lang_ip: 192.168.2.221
app_link: mihome://device?uid=16319620&did=636651219
miot_type: urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx04:2
available: true
home_room: 北辰的家庭 工作室
icon: mdi:information
updater: local
updated_at: "2024-12-11 17:54:54.222404+08:00"
converters:
  - info
  - intelligent_speaker.sleep_mode
  - intelligent_speaker.wake_up
  - clock.stop_alarm
  - intelligent_speaker.play_text
  - intelligent_speaker.execute_text_directive
customizes:
  switch_properties: on,sleep_mode,no_disturb
  button_actions: wake_up,play_music,tv_switchon,stop_alarm
  text_actions: play_text,execute_text_directive
  auto_cloud: true
  ignore_offline: true
  miot_local: true
  miot_cloud: true
  miot_cloud_write: true
  miot_cloud_action: true
  check_lan: true
  unreadable_properties: true
intelligent_speaker.sleep_mode.error: "-4003 Property/Action/Event does not exist"
intelligent_speaker.audio_id.error: "-4003 Property/Action/Event does not exist"
microphone.mute.error: "-4003 Property/Action/Event does not exist"
speaker.volume.error: "-4003 Property/Action/Event does not exist"
speaker.mute.error: "-4003 Property/Action/Event does not exist"
device_class: update
friendly_name: 小爱触屏音箱 信息
```
