### ISSUE TITLE
领普人在传感器ES3响应速度很慢，米家正常，大概慢5~10秒

### ISSUE THREAD

**Issue by bloodmao1** [al-one/hass-xiaomi-miot#2052]
### Device model / 设备型号

linp.sensor_occupy.es2

### HA core version / HA版本

1.0..2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

领普人在传感器ES3响应速度很慢，米家正常，大概慢5~10秒

### Entity attributes / 实体属性

```yaml
occupancy_sensor
```

**Comment by suddy** [comment]
也有同样的问题，米家里面支持linp.sensor_occupy.es2（实际是es3）本地模式自动化，似乎是插件还没支持，如果强制置顶local模式，es3所有的传感器和不可用，不知道这个信息对排查是否有帮助

**Comment by hanzibeichen** [comment]
es3 有人持续时长实体 sensor.linp_es2_dea0_has_someone_duration  不可用

**Comment by v0id24** [comment]
I viewed home-assistant Developer tools.
And I noticed that the data is updated exactly every 10 seconds (updated_at).
There is config field
```yaml
chunk_coordinators:
  - interval: 10
```
It looks like xiaomi-miot get data via polling, and mi-home get data via events subscription

**Comment by UPWNothing** [comment]
> I viewed home-assistant Developer tools. And I noticed that the data is updated exactly every 10 seconds (updated_at). There is config field
> 
> chunk_coordinators:
>   - interval: 10
> It looks like xiaomi-miot get data via polling, and mi-home get data via events subscription

I tried to customize the configuration:
```
customizes:
  sensor_properties: illumination,has_someone_duration,no_one_duration
  chunk_coordinators:
    - interval: 2
      props: occupancy_status,has_someone_duration,no_one_duration
```

However, it turned out that the actual interval is still 10 sec.
