### ISSUE TITLE
Missing entity sensor.mmgg_fi1_xxx

### ISSUE THREAD

**Issue by velisiska** [al-one/hass-xiaomi-miot#2053]
### Device model / 设备型号

[mmgg.feeder.fi1](https://home.miot-spec.com/s/mmgg.feeder.fi1)

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12.2

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

The entity `sensor.mmgg_fi1_a02d_pet_feeder` is missing from Home Assistant. This sensor was previously used to control the feeding schedule for my pet feeder. Without it, the automation that relies on this entity no longer functions as intended.

```yaml
- action: xiaomi_miot.set_miot_property
  data:
    piid: 5
    siid: 5
    entity_id: sensor.mmgg_fi1_a02d_pet_feeder
    value: "{{ (trigger.to_state.state == 'on') | iif('1', '0') }}"
```

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: Xiaomi Smart Pet Food Feeder Info
info: Xiaomi Smart Pet Food Feeder
model: mmgg.feeder.fi1
did: "468056631"
mac: EC:4D:3E:17:A0:2D
lan_ip: 192.168.50.6
app_link: mihome://device?uid=xxxx&did=468056631
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-fi1:1
available: true
home_room: ""
updater: local
updated_at: "2024-12-12 09:14:40.682357+01:00"
converters:
  - info
  - indicator_light.on
  - pet_feeder.fault
  - pet_feeder.pet_food_left_level
  - desiccant.desiccant_left_time
  - feedserve.outfood_num
  - clearnserve.cleantime
  - feedserve.outletstatus
  - feedserve.doorstatus
  - keyserve.key_stat
  - pet_feeder.pet_food_out
  - desiccant.reset_desiccant_life
  - clearnserve.resetclean
customizes:
  chunk_properties: 1
  button_actions: pet_food_out,resetclean,reset_desiccant_life
  binary_sensor_properties: outletstatus,doorstatus
  sensor_properties: fault,pet_food_left_level,outfood_num,cleantime,desiccant_left_time
  number_properties: key_stat,indicator_light.on
  select_actions: pet_food_out
  exclude_miot_properties: >-
    outfood_id,contrycode,feddplan_string,factory_result,phon_time_zonefeedplan_hour,feedplan_min,feedplan_unit,feedplan_stat,feedplan_id,getfeedplan_num
clearnserve.cleantime: 14
keyserve.key_stat: 1
feedserve.outfood_num: 5
feedserve.outletstatus: 0
feedserve.doorstatus: 0
desiccant.desiccant_left_time: 30
indicator_light.on: 1
pet_feeder.fault: 0
pet_feeder.pet_food_left_level: 0
feedplanserve.feedplan_contr: 1
```
