### ISSUE TITLE
小米电暖器模式中的“关闭”无法使用, 米家app的状态无法同步

### ISSUE THREAD

**Issue by dlutwy** [al-one/hass-xiaomi-miot#2056]
### Device model / 设备型号

zhimi.heater.ma2

### Component version / 插件版本

~~1.0.3~~ 1.0.4 也一样

### HA core version / HA版本

2023.10.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![image](https://github.com/user-attachments/assets/2bd9fc9a-0078-4d7d-b539-2ffcbf6e54cf)
1. 在这个转盘打开自动，设备会被开启，在HA 调整温度能同步到米家，但是米家修改温度同步不到HA
2. 在此转盘中选择关闭，无法关闭设备

其实这个设备没有模式，只有制暖和关，我不知道怎么修复它。谢谢

### Entity attributes / 实体属性

```yaml
hvac_modes:
  - auto
  - 'off'
min_temp: 18
max_temp: 28
target_temp_step: 1
current_temperature: 16.9
temperature: 24
hvac_action: 'off'
private_service.hw_enable: false
private_service.use_time: 276090
indicator_light.brightness: 0
alarm: true
physical_controls_locked: false
environment.temperature: 16.9
countdown.countdown_time: 0
heater.on: false
heater.fault: 0
heater.target_temperature: 24
state_updater: local
friendly_name: 电暖器 Heater
supported_features: 1
```
