### ISSUE TITLE
新版本集成翻译混乱问题

### ISSUE THREAD

**Issue by hanzibeichen** [al-one/hass-xiaomi-miot#2057]
### Device model / 设备型号

bean.switch.blns3

### Component version / 插件版本

1.0.4

### HA core version / HA版本

2024.12.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

集成1.0.4版本翻译有点问题，所有的开关（bean.switch.blns3）按键都无法同步米家设置的名称了，现在显示“客厅开关 开关左键 左键”，“客厅开关 开关中键 中键”，“客厅开关 开关右键 右键”，无法辨别是哪个灯，而且翻译的过于复杂，重复。
智能插座（giot.plug.v6shsm）无法同步米家设置的名称，现在显示开关，米家设置的名称是”饮水机“
智能通断器（ lemesh.switch.sw0a04）无法同步米家设置的名称，现在显示开关，米家设置的名称是”吸顶灯“
易来显示器挂灯（yeelink.light.lamp15）无法同步米家设置的名称，现在显示开关，和背光开关，这个米家显示的是屏幕灯，和氛围灯。
0.7.24之前的翻译就很好，开关各个按键会直接显示米家里面开关按键对应的命名，
<img width="1003" alt="截屏2024-12-12 23 01 50" src="https://github.com/user-attachments/assets/1f26a1c2-0afd-4d46-85e0-a293a4b6eae7" />
<img width="938" alt="截屏2024-12-12 22 59 55" src="https://github.com/user-attachments/assets/222c132b-82fe-4f32-99e0-bc75e160f052" />
<img width="693" alt="截屏2024-12-12 23 10 58" src="https://github.com/user-attachments/assets/ab21e93f-88f8-4e92-851d-0a7d4ba9fe13" />
<img width="875" alt="截屏2024-12-12 23 12 51" src="https://github.com/user-attachments/assets/decb5ddc-b906-422b-ab63-4ea229336a23" />
<img width="889" alt="截屏2024-12-12 23 14 19" src="https://github.com/user-attachments/assets/d1ea9a44-bcb1-4d4f-9b4e-aea4e5a913d6" />

### Entity attributes / 实体属性

```yaml
info: 客厅开关
model: bean.switch.blns3
did: "1116094059"
mac: 84:46:93:83:AD:C1
lan_ip: ""
app_link: mihome://device?uid=16319620&did=1116094059
miot_type: urn:miot-spec-v2:device:switch:0000A003:bean-blns3:1:0000C810
available: true
home_room: xx的家庭 客厅
icon: mdi:information
updater: cloud
updated_at: "2024-12-12 23:27:05.329135+08:00"
converters:
  - info
  - switch.on
  - switch-3.on
  - switch-4.on
customizes: {}
switch-4.on: false
switch-3.on: false
switch.on: false
switch_off_bk.backlight: true
switch_off_bk.on_led_off: false
switch_off_bk.sw_timer_off: 0
switch_off_bk.key_clicks_en: false
switch_off_bk.pwr_on_bits: 0
switch_off_bk.sw_timer_off_time: 5
switch_off_bk.switch_mutex: 0
switch_off_bk.key_relay_map: 131328
switch_off_bk.sw_flex_off_time: 3
switch_off_bk.sw_mode: 0
switch-4.mode: 0
switch-3.mode: 0
switch.mode: 0
device_class: update
friendly_name: 客厅开关 信息
```
