### ISSUE TITLE
Camera chuangmi.camera.ipc019e idle, no image

### ISSUE THREAD

**Issue by h3nrytan** [al-one/hass-xiaomi-miot#206]
No image showing on camera. State idle.

State:
```yaml
access_token: xxx
brand: chuangmi
model: chuangmi.camera.ipc019e
lan_ip: xxx
mac_address: xxx
firmware_version: 3.5.8_0166
hardware_version: ''
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc019e:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: false
glimmer_full_color-2-6: true
camera_control.recording_mode: 3
camera_control.motion_tracking: false
state_updater: cloud
sub_entities:
  - camera_control.on
friendly_name: Camera - Lounge
entity_picture: >-
  /api/camera_proxy/camera.lounge?token=xxx
supported_features: 1
video_attribute: 1
miot_cloud: true
keep_streaming: true
```
Log Warning: 
CCTV Camera Control: camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1633331947000, 'isContinue': True}, 'description': '成功', 'ts': 1633936747321}
