### ISSUE TITLE
小米智能墙壁插座Pro xiaomi.plug.mcn003 

### ISSUE THREAD

**Issue by ympchuan** [al-one/hass-xiaomi-miot#2065]
### Device model / 设备型号

xiaomi.plug.mcn003 

### Component version / 插件版本

1.0.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

**xiaomi.plug.mcn003** 没有日功耗、年功耗信息

<img width="668" alt="截屏2024-12-13 13 19 22" src="https://github.com/user-attachments/assets/d043e7ff-58f7-40f9-a3e6-509970fcec63" />

**xiaomi.plug.mcn001** 有功耗信息
<img width="670" alt="截屏2024-12-13 13 19 41" src="https://github.com/user-attachments/assets/e5790606-330d-4b83-a20a-1349b745a9d5" />

### Entity attributes / 实体属性

```yaml
button.xiaomi_mcn003_info

info: 小米智能墙壁插座Pro
model: xiaomi.plug.mcn003
did: 1089491909
mac: B8:50:D8:13:91:F6
lan_ip: 
app_link: mihome://device?uid=6325918&did=1089491909
miot_type: urn:miot-spec-v2:device:outlet:0000A002:xiaomi-mcn003:1:0000C816
available: true
home_room: 我的家
icon: mdi:information
updater: cloud
updated_at: 2024-12-13 13:50:28.834373+08:00
converters: info, switch.on, indicator_light.on, physical_controls_locked, electric_power-3-6
customizes: 
{}

physical_controls_locked: false
indicator_light.on: false
electric_power-3-6: 28
switch.on: true
power_consumption: 583.93
power_consumption_accumulation_way-3-7: false
switch.default_power_on_state: 0
switch.fault: 0
device_class: update
friendly_name: 小米智能墙壁插座Pro 信息
```
