### ISSUE TITLE
Pet Feeder 2 most entities are missing

### ISSUE THREAD

**Issue by simonepsp** [al-one/hass-xiaomi-miot#2073]
### Device model / 设备型号

[xiaomi.feeder.iv2001](https://home.miot-spec.com/s/xiaomi.feeder.iv2001)

### Component version / 插件版本

1.0.4

### HA core version / HA版本

2024.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

As title says most entities are not showing in HA, despite being correctly fetched (see attributes). I've tried adding the devices in Automatic, cloud and local modes.

All I'm trying to do is dispense a defined number of food portions

![CleanShot 2024-12-14 at 16 13 22@2x](https://github.com/user-attachments/assets/3c502416-6162-452c-8474-6c846aef0d19)

Please let me know if I can provide you with any additional info.
Thank you.

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: Pet Food Feeder Info
info: Pet Food Feeder
model: xiaomi.feeder.iv2001
did: 644118908
mac: REDACTED
lan_ip: 10.10.10.188
app_link: mihome://device?uid=140091472&did=644118908
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:xiaomi-iv2001:1
available: true
home_room: Home Living room
updater: local
updated_at: 2024-12-14 16:14:47.360972+02:00
converters: info, pet_feeder.status, physical_controls_locked, battery_level
customizes: 
{}

battery_level: false
physical_controls_locked: true
pet_feeder.status: 0
feeder_schedule-5-1: [0]
add_meal_state-5-3: 0
plan_process_display-5-4: 0
food_intake_rate-5-5: 10
food_intake_state-5-6: 0
max_schcdule_num-5-7: 35
schedule_state-5-8: 0
add_meal_cycle-5-10: 8
food_out_progress-5-11: 100
compensate_switch-5-12: 1
prevent_accumulation-5-14: 1
schedule_progress-5-15: 0
add_meal_triggertime-5-16: 0
device_timezone-5-17: 7200
desiccant.desiccant_left_level: 0
desiccant.desiccant_left_time: 0
physical_controls_locked.mode: 0
pet_feeder.fault: 0
pet_feeder.pet_food_left_level: 0
target_feeding_measure-2-7: 1
pet_feeder-2.food_out_status: 0
add_meal_notify_status-2-13: 0
pet_feeder-2.food_heap_status: 0
pet_feeder.eaten_food_measure: 0
pet_feeder-2.eaten_food_measure: 0
eaten_food_measure-2-22: 0
eaten_food_measure-2-23: 0
pet_feeder-2.status: 0
pet_feeder-2.status-28: 0
pet_feeder-2.status-29: 0
pet_feeder-2.status-31: 0
pet_feeder-2.status-32: 0
```

**Comment by al-one** [comment]
Add support in v1.0.5

**Comment by simonepsp** [comment]
Thank you! most entities are now displayed however there are still 2 issues:
- The "Food out" button only dispenses ONE portion, despite the "Target feeding measure" being set to 4
- Some entities, like "eaten food measure" are displayed as 0

![CleanShot 2024-12-15 at 08 57 41@2x](https://github.com/user-attachments/assets/79468122-4870-4f63-984e-db3b1788c7f0)

Do you have any solution to this?
Thanks a lot

**Comment by al-one** [comment]
> The "Food out" button only dispenses ONE portion, despite the "Target feeding measure" being set to 4

This component can only feed one serving when the button is pressed once.

> Some entities, like "eaten food measure" are displayed as 0

<img width="418" alt="image" src="https://github.com/user-attachments/assets/8859da30-c4de-4d4b-add9-b3645b9adf15" />

**Comment by Wh1terat** [comment]
@al-one 
> This component can only feed one serving when the button is pressed once.

The miot spec for the action `pet-food-out` expects piid 8 (`feed-measure`) as the argument rather than piid 9 (`target-feed-measure`) - but no read or write access for piid 8.

```yaml
feeding_measure.error: "-4001 Property is not readable"
```

I tried to override the miot spec for the action to take piid 7 as input but there was no food outputted (nor any error raised)

```json
  "xiaomi.feeder.iv2001": [ 
    {
      "iid": 2,
      "actions": [
        {
          "iid": 1,
          "in": [7],
          "out": []
        }
      ]
    }
  ],
```

Am I misunderstanding it?

It seems the standard react plugin is somehow using piid 8

```js
      FEEDING_MEASURE: {
        did: _miot.Device.deviceID,
        siid: 2,
        piid: 8
      },
```

```js
        return new Promise(function (resolve, reject) {
          var params = [(0, _objectSpread2.default)({}, _SpecMap.SpecMap.PET_FEEDER_ACTION_SPEC_PARAMS.PET_FOOD_OUT, {
            in: [(0, _objectSpread2.default)({}, _SpecMap.SpecMap.PET_FEEDER_SPEC_PARAMS.FEEDING_MEASURE, {
              value: amount
            })]
          })];
```

Without the miot_specs_extend addition, can still manually pass values in:

```yaml
action: xiaomi_miot.call_action
data:
  entity_id: button.xiaomi_iv2001_63c1_pet_food_out
  siid: 2
  aiid: 1
  params: 
   - 2
```
