### ISSUE TITLE
小米空调防直吹功能无响应，小米空气净化器1无响应

### ISSUE THREAD

**Issue by xiw321** [al-one/hass-xiaomi-miot#2076]
### Device model / 设备型号

zhimi.airpurifier.v3；xiaomi.aircondition.m9

### Component version / 插件版本

1.05

### HA core version / HA版本

2024.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米空调防直吹功能无响应，小米空气净化器1无响应

### Entity attributes / 实体属性

```yaml
info: 客厅的空气净化器
model: zhimi.airpurifier.v3
did: "699160"
mac: 64:09:80:28:B2:8B
lan_ip: 192.168.123.27
app_link: mihome://device?uid=1292637602&did=699160
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-v3:1
available: true
home_room: 客厅
icon: mdi:information
updater: none
updated_at: ""
converters:
  - info
  - indicator_light.on
  - physical_controls_locked
  - filter.filter_life_level
  - filter.filter_left_time
  - environment.pm2_5_density
  - air_purifier.on
  - alarm
customizes:
  switch_properties: air_purifier.on,alarm.alarm,anion,uv
  sensor_properties: illumination,motor_speed
  speed_property: favorite_level,favorite_fan_level
  number_properties: favorite_level,favorite_fan_level
  exclude_miot_services: button,filter_time,rfid,others
  exclude_miot_properties: >-
    average_aqi_cnt,aqi_zone,sensor_state,aqi_goodh,aqi_runstate,aqi_state,motor_strong,motor_high,motor_med,motor_med_l,motor_low,motor_silent,motor_favorite,motor_set_speed
  auto_cloud: true
  main_miot_services: air_purifier
  miot_cloud: true
device_class: update
friendly_name: 客厅的空气净化器 信息
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.device.zhimi.airpurifier.v3
来源: helpers/update_coordinator.py:379
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 09:01:49 (57 次总计出现)
上次记录: 09:16:49

Unexpected error fetching 64:09:80:28:b2:8b-d09ce7240a4b13ae4bbc86e45240938e-miot_status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 631, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2733, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: float division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 461, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 763, in update_miot_status
    results = await self.miio2miot.async_get_miot_props(self.local, mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 112, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        partial(self.get_miot_props, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 135, in get_miot_props
    val = tpl.render({
        'value': val,
    ...<5 lines>...
        'description': prop.list_description(val) if prop.value_list else None,
    })
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 599, in render
    ).result()
      ~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 68, in run_callback
    future.set_result(callback(*args))
                      ~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ZeroDivisionError: float division by zero
