### ISSUE TITLE
峥果卷帘门控制器无法正确识别状态

### ISSUE THREAD

**Issue by hanzibeichen** [al-one/hass-xiaomi-miot#2077]
### Device model / 设备型号

zinguo.motor.mk01

### Component version / 插件版本

1.0.5

### HA core version / HA版本

2024.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

峥果卷帘门控制器无法正确识别状态，卷帘门实际状态是已关闭，但是集成一直显示“正在关闭”，反之卷帘门实际状态是已打开，但是集成一直显示“正在打开”，直到下一次操作卷帘门才会集成里才会变动状态。下面是刚刚测试记录，麻烦大佬看看能不能处理，谢谢。
09:20:21 用米家APP开门到一半，09:20:23米家里点击了“停”按钮，此时集成里面显示已打开。09:22:41米家APP点击“开”，然后集成里一直显示“正在打开”，无法切换到已打开状态。09:35:03米家APP点击“关”，此后集成一直显示“正在关闭”无法切换到已关闭状态。
![截屏2024-12-15 09 41 拷贝](https://github.com/user-attachments/assets/5a64be68-d9c9-46e9-8c34-0a6220f34d84)

### Entity attributes / 实体属性

```yaml
info: 卷帘门
model: zinguo.motor.mk01
did: "705926074"
mac: D4:F0:EA:4A:C9:FD
lan_ip: 192.168.2.214
app_link: mihome://device?uid=16319620&did=705926074
miot_type: urn:miot-spec-v2:device:motor-controller:0000A01D:zinguo-mk01:1
available: true
home_room: xx的家庭 车库
icon: mdi:information
updater: local
updated_at: "2024-12-15 09:12:04.358965+08:00"
converters:
  - info
customizes: {}
block_sensor.id: 1348
block_sensor.name: 左
block_sensor-6.id: 11396
block_sensor-6.name: 右
device_set.block_type: 2
device_set.block_devicealarm: 1
device_set.block_alarm: 0
device_set.unclosed_set: 0
device_set.unclosed_devicealarm: 0
device_set.unclosed_alarm: 0
remoter.id: 5675
remoter.name: 随意贴
remoter-3.id: 7257
remoter-3.name: A
remoter-3.id-6: 7216
remoter-3.name-7: B
remoter-3.id-8: 0
remoter-3.name-9: ""
remoter-3.id-10: 0
remoter-3.name-11: ""
remoter-3.id-12: 0
remoter-3.name-13: ""
remoter-3.id-14: 0
remoter-3.name-15: ""
remoter-3.id-16: 0
remoter-3.name-17: ""
remoter-3.id-18: 0
remoter-3.name-19: ""
remoter-3.id-20: 0
remoter-3.name-21: ""
remoter-3.id-22: 0
remoter-3.name-23: ""
remoter-3.id-24: 0
remoter-3.name-25: ""
remoter-3.id-26: 0
remoter-3.name-27: ""
remoter-3.id-28: 0
remoter-3.name-29: ""
remoter-3.id-30: 0
remoter-3.name-31: ""
remoter-3.id-32: 0
remoter-3.name-33: ""
remoter-3.id-34: 0
remoter-3.name-35: ""
remoter-3.id-36: 0
remoter-3.name-37: ""
remoter-3.id-38: 0
remoter-3.name-39: ""
remoter-3.id-40: 0
remoter-3.name-41: ""
motor_controller.fault: 0
motor_controller.status: 2
motor_controller.mode: 1
state_updater: local
device_class: update
friendly_name: 卷帘门 信息
```
