### ISSUE TITLE
Missing options for Smart Cool and Hot Fan Heater

### ISSUE THREAD

**Issue by Fullpage12** [al-one/hass-xiaomi-miot#2093]
### Device model / 设备型号

dmaker.fan.p23

### Component version / 插件版本

1.0.5

### HA core version / HA版本

2024.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

There are many missing options like cooling mode, the screenshot below shows that I’m in heating mode even though it’s actually in cooling mode. I hope an option to select cooling mode and even detect it is added. Thank you
![IMG_5377](https://github.com/user-attachments/assets/44b8aa80-09a6-4a66-ad1f-bc3828f4eac5)

### Entity attributes / 实体属性

```yaml
button.dmaker_p23_6a87_info

in fo: Xiaomi Smart Cool and Hot Fan Heater
model: dmaker.fan.p23
did: "752493878"
mac: redacted
lan_ip:redacted
app_link: redacted
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p23:1
available: true
home_room: 8175539496 Room
icon: mdi:information
updater: local
updated_at: "2024-12-17 13:44:03.072081+07:00"
converters:
  - info
  - indicator_light.on
  - physical_controls_locked
  - environment.temperature
  - environment.relative_humidity
  - fan.horizontal_swing
  - alarm
  - dm_service.off_delay_time
customizes:
  button_actions: turn_left,turn_right
  number_properties: off_delay_time
  switch_properties: alarm,horizontal_swing,vertical_swing
  number_select_properties: >-
    horizontal_swing_included_angle,horizontal_angle,vertical_swing_included_angle,vertical_angle
dm_service.off_delay_time: 0
indicator_light.on: false
alarm: false
fan.horizontal_swing: true
environment.relative_humidity: 57.5
environment.temperature: 22.1
physical_controls_locked: false
state_updater: local
dm_service.speed_level: 60
dm_service.symmetrical_swing: false
dm_service.left_angle: 120
dm_service.right_angle: 30
fan.on: true
fan.fan_level: 6
fan.mode: 1
heater.on: true
heater.fault: 0
heater.mode: 0
heater.target_temperature: 22
heater.heating: false
miot_error: No response from the device
device_class: update
friendly_name: Xiaomi Smart Cool and Hot Fan Heater Info
```
