### ISSUE TITLE
Entities of mmgg.pet_waterer.wi11 unavailable

### ISSUE THREAD

**Issue by gio-dzilla** [al-one/hass-xiaomi-miot#2101]
### Device model / 设备型号

mmgg.pet_waterer.wi11

### Component version / 插件版本

1.0.5

### HA core version / HA版本

2024.12.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

For the past week or so various entities of the mmgg.pet_waterer.wi11 are constantly unavailable. I already tried to uninstall the integration and install it again, reload the configuration, force renew device, customise device but without results. 

### Entity attributes / 实体属性

```yaml
device_class: update
model: mmgg.pet_waterer.wi11
did: 467551316
app_link: mihome://device?uid=8204553151&did=467551316
miot_type: urn:miot-spec-v2:device:pet-drinking-fountain:0000A067:mmgg-wi11:1
available: true
updater: none
updated_at: 
converters: info, pet_drinking_fountain.on, indicator_light.on, filter.filter_left_time, pet_drinking_fountain.fault, remain_clean_time, no_water_flag.no_water_time, no_water_flag, no_water_flag.pump_block_flag, no_water_flag.lid_up_flag, pet_drinking_fountain.mode, filter.reset_filter_life, remain_clean_time.reset_clean_time
customizes: 
binary_sensor_properties: no_water_flag,pump_block_flag,lid_up_flag
button_actions: reset_filter_life,reset_clean_time
sensor_properties: remain_clean_time,fault,filter_left_time,no_water_time
select_properties: mode
interval_seconds: '60'
chunk_properties: '1'
```

### Home Assistant Logs / 系统日志

nothing in the logs
