### ISSUE TITLE
entities mmgg.feeder.fi1 unavailable

### ISSUE THREAD

**Issue by gio-dzilla** [al-one/hass-xiaomi-miot#2102]
### Device model / 设备型号

mmgg.feeder.fi1

### Component version / 插件版本

1.0.5

### HA core version / HA版本

core-2024.12.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

For the past week or so various entities of the mmgg.feeder.fi1 are constantly unavailable. I already tried to uninstall the integration and install it again, reload the configuration, force renew device, customise device but without results. 

Something weird about this issue is that sometimes I was able to get the entities to go live again by editing the entity ID. For example if I edit an entity id from: sensor.food_level to: sensor.food_level_1, as soon as I click 'Save' the state changes from unavailable to normal. This works with sensor. entities and binary_sensor., but not with light.

### Entity attributes / 实体属性

```yaml
device_class: update
model: mmgg.feeder.fi1
did: 413813025
app_link: mihome://device?uid=8204553151&did=413813025
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-fi1:1
available: true
updater: none
updated_at: 
converters: info, indicator_light.on, pet_feeder.fault, pet_feeder.pet_food_left_level, desiccant.desiccant_left_time, feedserve.outfood_num, clearnserve.cleantime, feedserve.outletstatus, feedserve.doorstatus, keyserve.key_stat, pet_feeder.pet_food_out, desiccant.reset_desiccant_life, clearnserve.resetclean
customizes: 
chunk_properties: '1'
button_actions: pet_food_out,resetclean,reset_desiccant_life
binary_sensor_properties: outletstatus,doorstatus
sensor_properties: fault,pet_food_left_level,outfood_num,cleantime,desiccant_left_time
number_properties: key_stat,indicator_light.on
exclude_miot_properties: >-
  outfood_id,contrycode,feddplan_string,factory_result,phon_time_zonefeedplan_hour,feedplan_min,feedplan_unit,feedplan_stat,feedplan_id,getfeedplan_num
interval_seconds: '30'
```

### Home Assistant Logs / 系统日志

nothing in the logs
