### ISSUE TITLE
针对“Commit 05d196d——add miio2miot for zhimi.aircondition.v1”的问题反馈：本地接入的智米空调模式不可调节

### ISSUE THREAD

**Issue by Hugh696** [al-one/hass-xiaomi-miot#2107]
### Device model / 设备型号

[zhimi.aircondition.v1](https://home.miot-spec.com/s/zhimi.aircondition.v1)

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.12.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

1. 空调只能开关，不能选择模式，无法执行动作“climate/set_hvac_mode” 。 'NoneType' object has no attribute 'is_success'，详细日志见下文；
2. 室外温湿度没了，原来云端有的现在也不可用了；
3. 风速对应问题：低中高档对应123档，45档调不了，https://home.miot-spec.com/spec/ 中亦缺失45档；
4. 显示屏亮度调节不可用，此问题一直都有，类型应为uint8，范围: 0 ~ 7 ，步长: 1；
5. 可不可以加上音量调节和上下扫风的角度调节。

### Entity attributes / 实体属性

```yaml
1. 空调实体：climate.zhimi_v1_e2cd_air_conditioner_2
hvac_modes: cool, heat, dry, fan_only, auto, off
min_temp: 16
max_temp: 32
target_temp_step: 0.1
fan_modes: 自动, 低档, 中档, 高档
swing_modes: off, vertical, horizontal, both
current_temperature: 15.1
temperature: 20
current_humidity: 38
fan_mode: 自动
hvac_action: off
swing_mode: off
indicator_light.brightness: 3
alarm.volume: 71
environment.temperature: 15.1
outdoor_temperature-4-2: 15.1
environment.relative_humidity: 38
outdoor_relative_humidity-4-4: 38
fan_control.fan_level: 0
fan_control.horizontal_swing: false
fan_control.vertical_swing: false
fan_control.vertical_angle: 0
air_conditioner.on: false
air_conditioner.mode: 4
target_temperature-2-3: 20
air_conditioner.sleep_mode: false
air_conditioner.heater: false
state_updater: local
friendly_name: 智米空调 Air Conditioner
supported_features: 425

2. 室外温湿度实体：sensor.zhimi_v1_e2cd_outdoor_temperature
restored: true
state_class: measurement
device_class: temperature
friendly_name: 次卧空调 Environment Outdoor Temperature
supported_features: 0
unit_of_measurement: °C

sensor.zhimi_v1_e2cd_outdoor_relative_humidity
restored: true
state_class: measurement
device_class: humidity
friendly_name: 次卧空调 Environment Outdoor Relative Humidity
supported_features: 0
unit_of_measurement: %

3. 风速实体：select.zhimi_v1_e2cd_fan_level_2
options: 自动, 低档, 中档, 高档 //yaml中启用了翻译功能
friendly_name: 智米空调 Fan Control Fan Level
fan_control.fan_level: 0

4. 显示屏亮度实体：light.zhimi_v1_e2cd_brightness
supported_color_modes: brightness
friendly_name: 智米空调 Indicator Light Brightness
supported_features: 0
color_mode: brightness
brightness: 109.28571428571428
indicator_light.brightness: 3 //这里与米家中设置的亮度一致
```

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API (文档, 问题)
首次出现: 11:37:48 (10 次总计出现)
上次记录: 11:51:54

[548005098496] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 807, in async_handle_set_hvac_mode_service
    await self.async_set_hvac_mode(hvac_mode)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 815, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/climate.py", line 393, in set_hvac_mode
    return self.set_preset_mode(mode)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/xiaomi_miot/climate.py", line 453, in set_preset_mode
    return self.set_property(self._prop_mode, val)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1191, in set_property
    return self.device.set_property(field, value)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 971, in set_property
    result = self.set_miot_property(siid, piid, value)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1010, in set_miot_property
    if not result.is_success:
           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_success'
