### ISSUE TITLE
风扇开/关有延迟

### ISSUE THREAD

**Issue by fixedid** [al-one/hass-xiaomi-miot#2109]
### Device model / 设备型号

zhimi.fan.fa1

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.12.4

### Integrated mode / 集成方式

Local (本地模式)

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 风扇 Info
info: 风扇
model: zhimi.fan.fa1
did: 
mac: EC:4D:3E:0E:7F:BD
lan_ip: 192.168.1.20
app_link: 
miot_type: urn:miot-spec-v2:device:fan:0000A005:zhimi-fa1:2
available: true
home_room: 
updater: local
updated_at: 2024-12-19 13:37:59.626976+08:00
custom_service.timing: 0
custom_service.h_swing_back: false
custom_service.v_swing_back: false
stepless_fan_level-5-10: 1
physical_controls_locked: false
current_physical_control_lock-6-2.error: -4005 Property value error
fan.on: false
fan.fan_level: 1
fan.horizontal_swing: true
fan.vertical_swing: false
fan.horizontal_angle: 30
fan.vertical_angle: 30
fan.mode: 0
fan.status: 1
fan.fault: 0
fan.brightness: 1
fan.alarm: false
converters: button.info, switch.physical_controls_locked, switch.fan.horizontal_swing, switch.fan.vertical_swing, switch.fan.alarm, number.fan.horizontal_angle, number.fan.vertical_angle
customizes: 
button_actions: turn_left,turn_right
number_properties: horizontal_angle,vertical_angle,off_delay
switch_properties: anion,alarm,horizontal_swing,vertical_swing

state_updater: local
```

### Home Assistant Logs / 系统日志

[home-assistant_xiaomi_miot_2024-12-19T05-26-38.320Z.log](https://github.com/user-attachments/files/18193062/home-assistant_xiaomi_miot_2024-12-19T05-26-38.320Z.log)
