### ISSUE TITLE
更新到 1.0.5 版本后，lumi.acpartner.mcn04 的 10A 插座功率实体丢失

### ISSUE THREAD

**Issue by Zkdc** [al-one/hass-xiaomi-miot#2111]
### Device model / 设备型号

lumi.acpartner.mcn04

### Component version / 插件版本

1.0.5

### HA core version / HA版本

2024.12.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

在更新到 1.0.5 版本后，lumi.acpartner.mcn04 的 10A 插座的功率实体丢失。今天更新了1.0.6版本后所有的电量统计也不可用了，所以回到了1.0.4版本，1.0.4版本的 10A 插座的功率正常。（实体属性是1.0.5版本中复制的）

### Entity attributes / 实体属性

```yaml
info: Mi Smart Air Conditioner Controller Pro
model: lumi.acpartner.mcn04
did: "*********"
mac: *********
lan_ip: *********
app_link: mihome://device?uid=*********&did=*********
miot_type: urn:miot-spec-v2:device:air-condition-outlet:0000A045:lumi-mcn04:1
available: true
home_room: *********
icon: mdi:information
updater: local
updated_at: "2024-12-19 17:31:50.549063+08:00"
converters:
  - info
  - electric_power-7-2
  - air_conditioner.on
  - ac_function.quick_cool_enable
  - indicator_light
  - fan_control.fan_level
  - ac_function.ac_mode
  - power_cost_today
  - power_cost_month
  - power_cost_today_2
  - power_cost_month_2
customizes:
  sensor_attributes: power_cost_today,power_cost_month,power_cost_today_2,power_cost_month_2
  select_properties: fan_level,ac_mode
  miio_cloud_props: []
  miio_cloud_props_template: lumi_acpartner_electric_power
  stat_power_cost_type: stat_day_v3
  stat_power_cost_key: 7.1,7.3
  auto_cloud: true
  interval_seconds: 60
  chunk_properties: 8
  switch_properties: on,quick_cool_enable,indicator_light
  configuration_entities: ac_mode,indicator_light
  chunk_coordinators:
    - interval: 10
      props: on,mode,target_temperature,fan_level,electric_power
electric_power-7-2: 779
fan_control.fan_level: 1
air_conditioner.on: true
electric_power-7-4: 0
air_conditioner.mode: 1
target_temperature-3-4: 23
state_updater: local
ac_function.ac_mode: 1
ac_function.quick_cool_enable: false
indicator_light.error: "-704220043 Property value error"
indicator_light.effective_time.error: "-704220043 Property value error"
ac_function.brand_id.error: "-704220043 Property value error"
ac_function.remote_id.error: "-704220043 Property value error"
ac_function.ac_type.error: "-704220043 Property value error"
ac_function.ac_ctrl_range.error: "-704220043 Property value error"
ac_function.ac_state: P0_M1_T23_S1_D1
ac_function.quick_cool_time.error: "-704220043 Property value error"
ac_function.quick_cool_status: 0
ac_function.sleep_cfg.error: "-704220043 Property value error"
ac_function.sleep_status: 0
power_consumption: 1385.549
power_consumption-7-3: 0.119
fan_control.vertical_swing: false
air_conditioner.fault.error: "-704220043 Property value error"
power_cost_today: 1.301
power_cost_month: 48.618
power_cost_today_2: 0
power_cost_month_2: 0.118
device_class: update
friendly_name: *********
```
