### ISSUE TITLE
1.0.6版本米家智能显示器挂灯1S开关不可用

### ISSUE THREAD

**Issue by fakeuniversal** [al-one/hass-xiaomi-miot#2113]
### Device model / 设备型号

yeelink.light.lamp22

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.3.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

1.0.6版本米家智能显示器挂灯1S开关不可用
![image](https://github.com/user-attachments/assets/96dac1cf-8e50-443d-9ffe-a8275b12e0a0)

### Entity attributes / 实体属性

```yaml
min_color_temp_kelvin: 2700
max_color_temp_kelvin: 6500
min_mireds: 153
max_mireds: 370
effect_list: Reading, Office, Leisure, Warmth, Computer
supported_color_modes: color_temp
friendly_name: 左侧台灯
supported_features: 4
```

### Home Assistant Logs / 系统日志

没有相关日志
