### ISSUE TITLE
Side Brush Left Time entity "unknown"

### ISSUE THREAD

**Issue by havlejan** [al-one/hass-xiaomi-miot#2116]
### Device model / 设备型号

roidmi.vacuum.v60

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Side Brush Left Time entity "unknown"

### Entity attributes / 实体属性

```yaml
Entity:  sensor.roidmi_v60_ea3d_brush_left_time_2
State:  unknown
Attributes:
unit_of_measurement: minutes
friendly_name: ROIDMI EVE Side Brush Left Time
brush_left_time-12-1: 12000
```

### Home Assistant Logs / 系统日志

no errors in log
