### ISSUE TITLE
Missing entity on device mike.bhf_light.2

### ISSUE THREAD

**Issue by anhnvme** [al-one/hass-xiaomi-miot#2186]
### Device model / 设备型号

[mike.bhf_light.2](https://home.miot-spec.com/s/mike.bhf_light.2)

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

This device have swing mode but i dont see it on Device page.
And some selector is not showing
<img width="922" alt="image" src="https://github.com/user-attachments/assets/4aba6742-8451-4be8-b6ed-3685fcc63d8c" />

Please refer https://home.miot-spec.com/spec/mike.bhf_light.2 it's have swing mode

### Entity attributes / 实体属性

```yaml
info: Smart Bath Pro (AI version) YB-007
model: mike.bhf_light.2
did: 
mac: Bxxxxxxx
lan_ip: 10.0.0.xxxx
app_link: 
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:mike-2:1
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2024-12-23 15:01:30.461592+07:00
fan_control.horizontal_swing: false
ptc_bath_heater.mode: false
ptc_bath_heater.heating: true
ptc_bath_heater.blow: true
ptc_bath_heater.ventilation: false
ptc_bath_heater-3.mode: true
ptc_bath_heater-3.mode-12: true
light.on: false
converters: button.info, light.light.on, switch.ptc_bath_heater.heating, switch.ptc_bath_heater.blow, switch.ptc_bath_heater.ventilation, select.ptc_bath_heater.mode, select.ptc_bath_heater-3.mode, select.ptc_bath_heater-3.mode-12
customizes: 
sensor_properties: temperature
switch_properties: heating,blow,ventilation,dryer
select_properties: mode
number_properties: target_temperature,off_delay_time

state_updater: local
device_class: update
friendly_name: Smart Bath Pro (AI version) YB-007 Info
```
