### ISSUE TITLE
Magnet Sensor isa.magnet.dw2hl door opening detection unreliable

### ISSUE THREAD

**Issue by Elger9** [al-one/hass-xiaomi-miot#2189]
### Device model / 设备型号

 isa.magnet.dw2hl

### Component version / 插件版本

1.0.4

### HA core version / HA版本

2024.12.3

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

Open/close detection is unreliable. There is a delay of up to 30 seconds. Quick opening and closing in a short interval is not detected at all.

### Entity attributes / 实体属性

```yaml
info: Doors
model: isa.magnet.dw2hl
did: blt.4.1jtv0qs15gc00
mac: E4:AA:EC:53:3D:8B
lan_ip: 
app_link: mihome://device?uid=8170731025&did=blt.4.1jtv0qs15gc00
miot_type: urn:miot-spec-v2:device:magnet-sensor:0000A016:isa-dw2hl:1
available: true
home_room: My home
icon: mdi:information
updater: cloud
updated_at: 2024-12-23 18:52:23.264339+01:00
converters: info, battery_level, magnet_sensor.illumination, magnet_sensor.contact_state
customizes: 
binary_sensor_properties: contact_state
sensor_properties: illumination

battery_level: 100
magnet_sensor.illumination: 2
magnet_sensor.contact_state: true
battery_level.error: -704220043 Property value error
device_class: update
friendly_name: Doors Info
```
