### ISSUE TITLE
After update yeelink.light.ceiling5 unable to Night mode in automations and scenes

### ISSUE THREAD

**Issue by exiom-xyz** [al-one/hass-xiaomi-miot#2193]
### Device model / 设备型号

yeelink.light.ceiling5

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.12.1

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

After a recent update, sadly I don’t know the previous working version I was on, 
the “Night” effect no longer works in scenes and automations, however manually selecting “Night” effect in the dashboard still works.

Despite the scene YAML having `effect: Day` and `light.mode: 2`, it toggles `effect` to Night but does not toggle `light mode` to 1 and then shortly after `effect` will go back to Day.

Please let me know if I need to provide anything to diagnose the issue.

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: Master Bedroom Light Info
info: Bedroom Light
model: yeelink.light.ceiling5
did: 131833522
mac: 04:CF:8C:8F:0D:E0
lan_ip: 10.0.3.14
app_link: mihome://device?uid=237943445&did=131833522
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceiling5:1
available: true
home_room: Home Bedroom
updater: local
updated_at: 2024-12-24 20:14:03.083700+08:00
light.on: true
light.brightness: 100
light.mode: 1
light.color_temperature: 2702
light.flex_switch: false
light.off_delay_time: 0
converters: button.info, light.light.on, light.brightness, light.color_temperature, light.mode, number.light.off_delay_time
customizes: 
number_properties: off_delay_time
switch_properties: bg_on
extend_miot_specs: yeelink.light.ceiling1
```
