### ISSUE TITLE
Xiaomi Robot Vacuum Info became unavailable

### ISSUE THREAD

**Issue by erich0600** [al-one/hass-xiaomi-miot#2194]
### Device model / 设备型号

xiaomi.vacuum.d109gl

### Component version / 插件版本

1.0.6

### HA core version / HA版本

core-2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Cannot show entities, but was fine a few hours ago.

### Entity attributes / 实体属性

```yaml
info: Xiaomi Robot Vacuum
model: xiaomi.vacuum.d109gl
did: 1144197024
mac: CC:4D:75:1C:A2:96
lan_ip: 192.168.50.179
app_link: mihome://device?uid=1593007098&did=1144197024
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:xiaomi-d109gl:1
available: false
home_room: Living room
icon: mdi:information-off
updater: none
updated_at: 
converters: button.info, switch.physical_controls_locked, sensor.filter.filter_life_level, sensor.filter.filter_left_time, sensor.brush_cleaner.brush_life_level, sensor.brush_cleaner.brush_left_time, sensor.brush_life_level-13-1, sensor.brush_left_time-13-2, sensor.battery_level, sensor.battery.voltage, sensor.battery.charging_state
customizes: 
{}

miot_error: No response from the device
state_updater: null
device_class: update
friendly_name: Xiaomi Robot Vacuum Info
```

### Home Assistant Logs / 系统日志

This error originated from a custom integration.

Logger: miio.miioprotocol
Source: custom_components/xiaomi_miot/core/device.py:1305
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 10:19:40 AM (22 occurrences)
Last logged: 10:30:21 AM

Got error when receiving: timed out

Logger: custom_components.xiaomi_miot.core.device.xiaomi.vacuum.d109gl
Source: custom_components/xiaomi_miot/core/device.py:836
integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 10:19:40 AM (22 occurrences)
Last logged: 10:30:21 AM

Got MiioException while fetching the state: No response from the device, mapping: {'custom.updata_difference': {'siid': 20, 'piid': 3}, 'dust_bag.dust_bag_life_level': {'siid': 19, 'piid': 1}, 'dust_bag.dust_bag_left_time': {'siid': 19, 'piid': 2}, 'detergent_left_level-18-1': {'siid': 18, 'piid': 1}, 'detergent_self_delivery-18-2': {'siid': 18, 'piid': 2}, 'detergent_self_delivery_level-18-3': {'siid': 18, 'piid': 3}, 'voice_management.target_voice': {'siid': 15, 'piid': 1}, 'voice_management.cur_voice': {'siid': 15, 'piid': 2}, 'download_status-15-3': {'siid': 15, 'piid': 3}, 'download_progress-15-4': {'siid': 15, 'piid': 4}, 'filter.filter_life_level': {'siid': 14, 'piid': 1}, 'filter.filter_left_time': {'siid': 14, 'piid': 2}, 'brush_life_level-13-1': {'siid': 13, 'piid': 1}, 'brush_left_time-13-2': {'siid': 13, 'piid': 2}, 'brush_cleaner.brush_life_level': {'siid': 12, 'piid': 1}, 'brush_cleaner.brush_left_time': {'siid': 12, 'piid': 2}, 'no_disturb': {'siid': 11, 'piid': 1}, 'no_disturb.enable_time_period': {'siid': 11, 'piid': 2}, 'no_disturb.current_no_disturb': {'siid': 11, 'piid': 3}, 'vacuum_map.map_obj_name': {'siid': 10, 'piid': 1}, 'vacuum_map.trajectory_obj_name': {'siid': 10, 'piid': 2}, 'vacuum_map.clean_record': {'siid': 10, 'piid': 3}, 'vacuum_map.vacuum_position': {'siid': 10, 'piid': 4}, 'vacuum_map.map_management': {'siid': 10, 'piid': 5}, 'vacuum_map.current_map_id': {'siid': 10, 'piid': 6}, 'vacuum_map.carpet_obj_name': {'siid': 10, 'piid': 7}, 'vacuum_map.map_3d_info': {'siid': 10, 'piid': 9}, 'vacuum_map.map_switch_method': {'siid': 10, 'piid': 10}, 'vacuum_map.map_upload_stop': {'siid': 10, 'piid': 11}, 'map_upload_stop_action_result-10-12': {'siid': 10, 'piid': 12}, 'vacuum_map.backup_map_list': {'siid': 10, 'piid': 13}, 'vacuum_map.restore_map_result': {'siid': 10, 'piid': 14}, 'mop.mop_life_level': {'siid': 9, 'piid': 1}, 'mop.mop_left_time': {'siid': 9, 'piid': 2}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'current_physical_control_lock-5-2': {'siid': 5, 'piid': 2}, 'alarm': {'siid': 4, 'piid': 1}, 'alarm.volume': {'siid': 4, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}, 'battery.voltage': {'siid': 3, 'piid': 3}, 'vacuum.vacuum_frameware_version': {'siid': 2, 'piid': 1}, 'vacuum.status': {'siid': 2, 'piid': 2}, 'vacuum.fault': {'siid': 2, 'piid': 3}, 'vacuum.sweep_mop_type': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 5}, 'vacuum.cleaning_area': {'siid': 2, 'piid': 6}, 'vacuum.cleaning_time': {'siid': 2, 'piid': 7}, 'vacuum.clean_times': {'siid': 2, 'piid': 8}, 'vacuum.mode': {'siid': 2, 'piid': 9}, 'vacuum.mop_water_output_level': {'siid': 2, 'piid': 10}, 'vacuum.mop_status': {'siid': 2, 'piid': 11}, 'vacuum.zone_ids': {'siid': 2, 'piid': 12}, 'vacuum.restricted_sweep_areas': {'siid': 2, 'piid': 13}, 'vacuum.restricted_walls': {'siid': 2, 'piid': 14}, 'vacuum.room_information': {'siid': 2, 'piid': 16}, 'vacuum.last_clean_time': {'siid': 2, 'piid': 17}, 'base_station_working_status-2-18': {'siid': 2, 'piid': 18}, 'vacuum.order_clean': {'siid': 2, 'piid': 19}, 'vacuum.carpet_boost': {'siid': 2, 'piid': 20}, 'vacuum.carpet_avoidance': {'siid': 2, 'piid': 21}, 'vacuum.carpet_display': {'siid': 2, 'piid': 22}, 'vacuum.sweep_break_switch': {'siid': 2, 'piid': 23}, 'vacuum.sleep_status': {'siid': 2, 'piid': 25}, 'vacuum.location_status': {'siid': 2, 'piid': 26}, 'vacuum.map_complete_dialog': {'siid': 2, 'piid': 27}, 'vacuum.enable_mop_wash': {'siid': 2, 'piid': 28}, 'vacuum.frequency_mop_wash': {'siid': 2, 'piid': 29}, 'water_output_for_washing_mop-2-30': {'siid': 2, 'piid': 30}, 'vacuum.drying_time': {'siid': 2, 'piid': 31}, 'vacuum.auto_dust_arrest': {'siid': 2, 'piid': 32}, 'vacuum.dust_arrest_frequency': {'siid': 2, 'piid': 33}, 'vacuum.auto_mop_dry': {'siid': 2, 'piid': 34}, 'vacuum.auto_water_change': {'siid': 2, 'piid': 35}, 'vacuum.use_detergent': {'siid': 2, 'piid': 36}, 'vacuum.exit_remote_dialog': {'siid': 2, 'piid': 38}, 'vacuum.current_cleaning_config': {'siid': 2, 'piid': 40}, 'vacuum.user_define_sweep_cfg': {'siid': 2, 'piid': 42}, 'vacuum.user_define_sweep_id': {'siid': 2, 'piid': 43}, 'vacuum.water_check_list': {'siid': 2, 'piid': 53}, 'vacuum.water_check_status': {'siid': 2, 'piid': 54}, 'vacuum.sweep_furniture': {'siid': 2, 'piid': 57}, 'vacuum.carpet_object': {'siid': 2, 'piid': 58}, 'vacuum.detergent_self_delivery': {'siid': 2, 'piid': 59}, 'mop_water_output_level_no_tank-2-60': {'siid': 2, 'piid': 60}, 'frequency_mop_wash_no_tank-2-61': {'siid': 2, 'piid': 61}, 'auto_water_change_installed-2-62': {'siid': 2, 'piid': 62}, 'vacuum.fault_ids': {'siid': 2, 'piid': 66}, 'vacuum.action_result': {'siid': 2, 'piid': 67}, 'vacuum.plugin_info_remind': {'siid': 2, 'piid': 70}, 'detergent_depletion_reminder-2-71': {'siid': 2, 'piid': 71}, 'vacuum.notice': {'siid': 2, 'piid': 72}, 'vacuum.carpet_cleaning_method': {'siid': 2, 'piid': 73}, 'vacuum.sweep_route': {'siid': 2, 'piid': 74}, 'obstacle_avoidance_strategy-2-75': {'siid': 2, 'piid': 75}, 'vacuum.carpet_deep_cleaning': {'siid': 2, 'piid': 76}, 'vacuum.carpet_discriminate': {'siid': 2, 'piid': 77}, 'vacuum.sweep_carpet_first': {'siid': 2, 'piid': 78}, 'vacuum.mop_outer_swing': {'siid': 2, 'piid': 79}, 'mop_outer_swing_frequency-2-80': {'siid': 2, 'piid': 80}, 'frequency_mop_wash_by_time-2-81': {'siid': 2, 'piid': 81}, 'auto_dust_arrest_power_level-2-82': {'siid': 2, 'piid': 82}, 'vacuum.worry_free_clean_mode': {'siid': 2, 'piid': 83}, 'wash_mop_water_temperature-2-84': {'siid': 2, 'piid': 84}}, max_properties: 10/104
