### ISSUE TITLE
配置 lumi.acpartner.mcn04 后日志中频繁出现 user ack timeout 报错

### ISSUE THREAD

**Issue by keniji** [al-one/hass-xiaomi-miot#2195]
### Device model / 设备型号

lumi.acpartner.mcn04

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

通过集成配置型号为`lumi.acpartner.mcn04`的`米家空调伴侣Pro 万能遥控板`后，日志中频繁出现报错（从`09:58:55`到`14:28:00`已出现414 次）。

### Entity attributes / 实体属性

```yaml
info: 次卧空调伴侣
model: lumi.acpartner.mcn04
did: 53259XXXX
mac: XX:XX:XX:XX:XX:XX
lan_ip: X.X.X.X
app_link: mihome://device?uid=3585XXXX&did=53259XXXX
miot_type: urn:miot-spec-v2:device:air-condition-outlet:0000A045:lumi-mcn04:1
available: true
home_room: 上海 次卧
icon: mdi:information
updater: local
updated_at: 2024-12-25 14:30:55.135470+08:00
electric_power-7-2: 0
electric_power-7-4: 0
fan_control.fan_level: 1
air_conditioner.on: false
air_conditioner.mode: 1
target_temperature-3-4: 22
indicator_light.error: -704220043 Property value error
indicator_light.effective_time.error: -704220043 Property value error
ac_function.brand_id.error: -704220043 Property value error
ac_function.remote_id.error: -704220043 Property value error
ac_function.ac_mode.error: -704220043 Property value error
ac_function.ac_type.error: -704220043 Property value error
ac_function.ac_ctrl_range.error: -704220043 Property value error
ac_function.ac_state: P1_M1_T22_S1_D1
ac_function.quick_cool_enable.error: -704220043 Property value error
ac_function.quick_cool_time.error: -704220043 Property value error
ac_function.quick_cool_status: 0
ac_function.sleep_cfg.error: -704220043 Property value error
ac_function.sleep_status: 0
power_consumption: 746.611
power_consumption-7-3: 8.362
fan_control.vertical_swing: false
air_conditioner.fault.error: -704220043 Property value error
power_cost_today: 0
power_cost_month: 17.142
power_cost_today_2: 0.014
power_cost_month_2: 0.443
converters: button.info, sensor.electric_power-7-2, switch.air_conditioner.on, switch.ac_function.quick_cool_enable, switch.indicator_light, select.fan_control.fan_level, select.ac_function.ac_mode, sensor.power_cost_today, sensor.power_cost_month, sensor.power_cost_today_2, sensor.power_cost_month_2
customizes: 
sensor_attributes: power_cost_today,power_cost_month,power_cost_today_2,power_cost_month_2
select_properties: fan_level,ac_mode
miio_cloud_props: []
miio_cloud_props_template: lumi_acpartner_electric_power
stat_power_cost_type: stat_day_v3
stat_power_cost_key: 7.1,7.3
auto_cloud: true
interval_seconds: 60
chunk_properties: 8
switch_properties: on,quick_cool_enable,indicator_light
configuration_entities: ac_mode,indicator_light
chunk_coordinators:
  - interval: 10
    props: on,mode,target_temperature,fan_level,electric_power

state_updater: local
device_class: update
friendly_name: 次卧空调伴侣 Info
```

### Home Assistant Logs / 系统日志

2024-12-25 14:26:33.835 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2024-12-25 14:26:33.836 WARNING (MainThread) [custom_components.xiaomi_miot.core.device.lumi.acpartner.mcn04] Got MiioException while fetching the state: Unable to recover failed command, mapping: {'indicator_light': {'siid': 9, 'piid': 1}, 'indicator_light.effective_time': {'siid': 9, 'piid': 2}, 'ac_function.brand_id': {'siid': 8, 'piid': 2}, 'ac_function.remote_id': {'siid': 8, 'piid': 3}, 'ac_function.ac_mode': {'siid': 8, 'piid': 4}, 'ac_function.ac_type': {'siid': 8, 'piid': 5}, 'ac_function.ac_ctrl_range': {'siid': 8, 'piid': 6}, 'ac_function.ac_state': {'siid': 8, 'piid': 7}, 'ac_function.quick_cool_enable': {'siid': 8, 'piid': 8}, 'ac_function.quick_cool_time': {'siid': 8, 'piid': 9}, 'ac_function.quick_cool_status': {'siid': 8, 'piid': 10}, 'ac_function.sleep_cfg': {'siid': 8, 'piid': 11}, 'ac_function.sleep_status': {'siid': 8, 'piid': 12}, 'power_consumption': {'siid': 7, 'piid': 1}, 'power_consumption-7-3': {'siid': 7, 'piid': 3}, 'fan_control.vertical_swing': {'siid': 4, 'piid': 4}, 'air_conditioner.fault': {'siid': 3, 'piid': 3}}, max_properties: 8/17
2024-12-25 14:26:34.852 INFO (MainThread) [custom_components.xiaomi_miot.core.device.lumi.acpartner.mcn04] Device updated: {'sensor.electric_power-7-2': 1, 'select.fan_control.fan_level': 'Low', 'switch.air_conditioner.on': False, 'only_info': False}
