### ISSUE TITLE
雷士吸顶灯开关状态异常 

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [al-one/hass-xiaomi-miot#2204]
### Device model / 设备型号

leishi.light.eps127

### Component version / 插件版本

1.0.6

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

雷士吸顶灯开关状态异常。灯关着的时候 HA认为灯还是开的。

可能由于converter 错误输入了 `light.light.on` 而非 `light.on`

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 饭厅灯 Info
info: 饭厅灯
model: leishi.light.eps127
did: "846044617"
mac: <redacted>
lan_ip: 192.168.0.25
app_link: mihome://device?uid=<redacted>&did=846044617
miot_type: urn:miot-spec-v2:device:light:0000A001:leishi-eps127:3
available: true
home_room: 我的家 飯廳
updater: local
updated_at: "2024-12-26 18:47:39.582741+08:00"
mode_setting.wake_up_time: 10
mode_setting.wake_up_brightness: 70
mode_setting.sleep_aid_time: 10
mode_setting.light_pattern: 0
mode_setting.hard_ver: 6
mode_setting.user_save: false
mode_setting.follow_the_mian: true
ambient_light.on: false
ambient_light.mode: 1
ambient_light.flow_speed_level: 1
light.on: true
light.mode: 0
light.brightness: 100
light.color_temperature: 3608
light.flex_switch: true
light.sleep_aid_mode: false
light.wake_up_mode: false
light.default_power_on_state: 0
light.enable_time_period: 10
light.night_light_switch: false
converters:
  - button.info
  - light.light.on
  - light.brightness
  - light.color_temperature
  - light.mode
  - light.ambient_light.on
  - ambient_light.mode
  - switch.light.flex_switch
customizes:
  number_properties: off_delay_time
  switch_properties: flex_switch,wind_reverse
  exclude_miot_services: scenes,scene,scens,remote
  exclude_miot_properties: default.user_save,professional_setting.delay
  select_properties: default.default
  light_services: light.on
```

**Comment by al-one** [comment]
> light.on: true

设备返回的状态就是开着

**Comment by SodaWithoutSparkles** [comment]
灯现在是关掉的

```
mode_setting.wake_up_time: 10
mode_setting.wake_up_brightness: 70
mode_setting.sleep_aid_time: 10
mode_setting.light_pattern: 0
mode_setting.hard_ver: 6
mode_setting.user_save: false
mode_setting.follow_the_mian: true
ambient_light.on: false
ambient_light.mode: 1
ambient_light.flow_speed_level: 1
light.on: false
light.mode: 0
light.brightness: 6
light.color_temperature: 4350
light.flex_switch: true
light.sleep_aid_mode: false
light.wake_up_mode: false
light.default_power_on_state: 0
light.enable_time_period: 10
light.night_light_switch: false
converters:
  - button.info
  - light.light.on
  - light.brightness
  - light.color_temperature
  - light.mode
  - light.ambient_light.on
  - ambient_light.mode
  - switch.light.flex_switch
customizes:
  number_properties: off_delay_time
  switch_properties: flex_switch,wind_reverse
  exclude_miot_services: scenes,scene,scens,remote
  exclude_miot_properties: default.user_save,professional_setting.delay
  select_properties: default.default
  light_services: light.on
device_class: update
```

**Comment by al-one** [comment]
light 实体属性

**Comment by SodaWithoutSparkles** [comment]
light 实体属性，现在灯是关的

```yaml
min_color_temp_kelvin: 3000
max_color_temp_kelvin: 5700
min_mireds: 175
max_mireds: 333
effect_list:
  - Auto
  - Reading
  - Night
  - Tv
  - Warmth
  - Winter
  - Summer
supported_color_modes:
  - color_temp
effect: Auto
color_mode: color_temp
brightness: 255
color_temp_kelvin: 3608
color_temp: 277
hs_color:
  - 27.072
  - 42.477
rgb_color:
  - 255
  - 196
  - 147
xy_color:
  - 0.445
  - 0.372
light.color_temperature: 3608
light.on: true
light.mode: 0
light.brightness: 100
friendly_name: Dining Room Light
supported_features: 4
```

**Comment by al-one** [comment]
1. 开启[调试日志](https://github.com/al-one/hass-xiaomi-miot/issues/500#debug)
2. 在米家开关灯，每次操作等待半分钟
3. 关闭调试并下载日志
4. 提交日志

**Comment by SodaWithoutSparkles** [comment]
> 1. 开启[调试日志](https://github.com/al-one/hass-xiaomi-miot/issues/500#debug)
> 2. 在米家开关灯，每次操作等待半分钟
> 3. 关闭调试并下载日志
> 4. 提交日志

调试日志里面有太多东西，感觉不太安全。

而且可以确定可以通过 `Xiaomi Miot Auto: Get Properties` 获取正确的开关灯状态的：

```yaml 
action: xiaomi_miot.get_properties
data:
  entity_id: button.leishi_eps127_90ce_info
  mapping:
    - siid: 2
      piid: 1
```

```yaml
light.on: false
```

米家开灯，`light.on` 会变为true。反之亦然。
