### ISSUE TITLE
更新后扫地机器人viomi.vacuum.v7缺失两个实体 s_area/s_time

### ISSUE THREAD

**Issue by ptbsare** [al-one/hass-xiaomi-miot#2212]
### Device model / 设备型号

viomi.vacuum.v7

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2025.1 beta 

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

viomi.vacuum.v7 更新后扫地机器人viomi.vacuum.v7缺失两个entity sensor.viomi_v7_4c26_miio_s_area sensor.viomi_v7_4c26_miio_s_time
0.7.x 正常
更新后出现
与#1579 类似

### Entity attributes / 实体属性

```yaml
略
```

### Home Assistant Logs / 系统日志

更新后扫地机器人viomi.vacuum.v7缺失两个entity sensor.viomi_v7_4c26_miio_s_area sensor.viomi_v7_4c26_miio_s_time

**Comment by ptbsare** [comment]
为不可用状态，并非集成不提供
```
model: viomi.vacuum.v7
app_link: ""
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:viomi-v7:2
available: true
home_room: ""
vacuum.status: 6
vacuum.mode: 1
viomi_vacuum.main_brush_life: 63
viomi_vacuum.side_brush_life: 26
viomi_vacuum.hypa_life: 26
viomi_vacuum.mop_life: 0
battery_level: 100
state_updater: local
vacuum.status_desc: Charging
miio.run_state: 5
miio.mode: 0
miio.err_state: 2105
miio.battary_life: 100
miio.box_type: 3
miio.mop_type: 0
miio.s_time: 65
miio.s_area: 51.39
miio.suction_grade: 1
miio.water_grade: 12
miio.remember_map: 1
miio.has_map: 1
miio.is_mop: 0
miio.has_newmap: 1
clean_area: 51.39
clean_time: 65
converters:
  - button.info
  - sensor.battery_level
  - sensor.vacuum.status
  - sensor.viomi_vacuum.main_brush_life
  - sensor.viomi_vacuum.side_brush_life
  - sensor.viomi_vacuum.hypa_life
  - sensor.viomi_vacuum.mop_life
  - select.vacuum.mode
  - button.vacuum.start_sweep
  - button.vacuum.stop_sweeping
  - button.vacuum.start_sweep_mop
  - button.vacuum.start_mop
  - button.vacuum.pause_sweeping
  - button.battery.start_charge
  - sensor.miio.s_area
  - sensor.miio.s_time
customizes:
  binary_sensor_properties: mop_status
  sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
  select_properties: mode,sweep_mop_type,sweep_type,clean_times
  number_properties: volume
  button_actions: >-
    start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
  configuration_entities: reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
  chunk_coordinators:
    - interval: 10
      props: status,cleaning_area,cleaning_time,charging_state
      notify: true
    - interval: 15
      props: mode,sweep_mop_type,sweep_type,clean_times
  sensor_attributes: miio.s_area,miio.s_time
device_class: update
friendly_name: 客厅扫地机器人 信息

```
![Screenshot_2024-12-29-18-26-06-291_com android chrome](https://github.com/user-attachments/assets/e8db5482-1835-4014-ab64-7e0d86fff986)
