### ISSUE TITLE
minij.washer.v5 更新后缺失target_water_level entity

### ISSUE THREAD

**Issue by ptbsare** [al-one/hass-xiaomi-miot#2213]
### Device model / 设备型号

[minij.washer.v5](https://home.miot-spec.com/s/minij.washer.v5)

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2025.1 beta

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

minij.washer.v5 更新后缺失target_water_level entity
0.7.x 正常

### Entity attributes / 实体属性

```yaml
alarm.volume: 30
physical_controls_locked: false
washer.on: false
washer.status: 1
washer.mode: 1
washer.left_time: 69
washer.spin_speed: 1000
washer.target_temperature: 30
washer.target_water_level: 3
washer.rinsh_times: 2
washer.drying_level: 4
converters:
  - button.info
  - sensor.washer.status
  - switch.physical_controls_locked
  - sensor.washer.left_time
  - switch.washer.on
  - select.washer.mode
  - select.washer.rinsh_times
  - select.washer.drying_level
  - select.washer.spin_speed
  - select.washer.target_temperature
  - button.washer.start_wash
  - button.washer.pause
customizes:
  button_actions: start_wash,pause,stop_washing
  sensor_properties: fault,run_status,left_time,door_state
  switch_properties: on,sleep_mode,steam_sterilization,ai_mode,high_water_switch,one_click_wash
  select_properties: mode,drying_level,rinsh_times,drying_degree
  number_select_properties: target_temperature,spin_speed,soak_time,wash_time,drying_time
```
```


### Home Assistant Logs / 系统日志

_No response_
