### ISSUE TITLE
1.0.7灯具不可用问题部分修复，但仍有部分灯具不可用，

### ISSUE THREAD

**Issue by CNNNHp** [al-one/hass-xiaomi-miot#2226]
### Device model / 设备型号

lemesh.light.wy0c15、qdhkl.aircondition.b23

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2024.2.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

1.0.7灯具不可用问题部分修复，但仍有部分灯具不可用，空调状态返回时间延迟很长，过去的版本开关空调状态大概3秒钟可以同步，1.0.7版本空调状态反应时间有bug。

### Entity attributes / 实体属性

```yaml
button.lemesh_wy0c15_1c65_info
餐边柜灯带 信息
unknown	info: 餐边柜灯带
model: lemesh.light.wy0c15
did: 1100397945
mac: 8C:D0:B2:72:1C:65
lan_ip: 
app_link: mihome://device?uid=2764650445&did=1100397945
miot_type: urn:miot-spec-v2:device:light:0000A001:lemesh-wy0c15:1:0000C802
available: true
home_room: 博翠山 餐厅
icon: mdi:information
updater: cloud
updated_at: 2024-12-28 22:35:17.309074+08:00
light.on: true
light.brightness: 100
light.color_temperature: 5165
light.mode: 0
remote.remote_ltype: 0
remote.remote_htype: 0
remote.remote_a: 0
remote.remote_b: 0
remote.remote_c: 0
remote.remote_d: 0
remote.remote_e: 0
remote.remote_f: 0
remote.remote_g: 0
remote.remote_h: 0
default.user_save: 0
default.dimming: 0
default.night_switch: 0
default.fade_time: 4408131
default.lowest_brightness: 1
default.lock_state: 842137608
default.light_mode_one: 342123521
default.light_mode_two: 335569921
default.light_mode_three: 338846721
default.light_mode_four: 335544577
default.sleep_config: 20510
default.wake_config: 5255710
light.flex_switch: false
light.default_power_on_state: 0
converters: button.info, light.light.on, light.brightness, light.color_temperature, light.mode
customizes: 
number_properties: off_delay_time
switch_properties: init_power_opt,fan_init_power_opt
chunk_coordinators:
  - interval: 10
    props: on,brightness,color_temperature,color,mode

device_class: update
friendly_name: 餐边柜灯带 信息
light.lemesh_wy0c15_1c65_switch_status
餐边柜灯带 灯光 开关
unavailable	min_color_temp_kelvin: 2700
max_color_temp_kelvin: 6500
min_mireds: 153
max_mireds: 370
effect_list: 色温模式, 日光, 月光（夜间）模式, 温馨, 电视模式（影院模式）, 阅读模式, 电脑模式, 会客模式, 娱乐模式, 清晨唤醒, 黄昏明亮, 夜晚助眠
supported_color_modes: color_temp
friendly_name: 餐边柜灯带 灯光 开关
supported_features: 4
```
