### ISSUE TITLE
Roidmi EVE Plus v1.0.x not working

### ISSUE THREAD

**Issue by pkoutsovasilis** [al-one/hass-xiaomi-miot#2227]
### Device model / 设备型号

roidmi.vacuum.v60

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

[Here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406#discussioncomment-10630221) is my card config. With v0.7.25 everything is working fine, but with v1.0.7 almost nothing works 😄 

### Entity attributes / 实体属性

```yaml
state with v0.7.25 (last working version)


fan_speed_list:
  - Silent
  - Basic
  - Strong
  - Full Speed
  - Sweep
battery_level: 91
battery_icon: mdi:battery-charging-100
fan_speed: Strong
model: roidmi.vacuum.v60
lan_ip: 192.168.32.102
mac_address: 30:49:50:90:8c:2d
entity_class: MiotVacuumEntity
exclude_miot_services: null
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:roidmi-v60:3
vacuum.status: 6
vacuum.fault: 0
vacuum.mode: 3
vacuum.sweep_type: 0
vacuum.on: 1
sweep.sweep_mode: 0
custom.mop: 0
custom.work_station_freq: 0
custom.timing: "{\"tz\":2,\"tzs\":7200}"
custom.clean_area: 0
custom.uid: "1596858527"
custom.auto_boost: 0
custom.forbid_mode: "{\"time\":[79200,43200,0],\"tz\":2,\"tzs\":7200}"
custom.water_level: 3
custom.total_clean_time: 1450446
custom.total_clean_areas: 13999
custom.clean_counts: 555
custom.clean_time: 35
custom.double_clean: 1
custom.edge_sweep: 0
custom.led_switch: 1
custom.lidar_collision: 1
custom.station_key: 1
custom.station_led: 1
custom.current_audio: girl_en
custom.progress: file not exist !!!
custom.station_type: 102
custom.voice_conf: file not exist !!!
brush_left_time-15-1: 710
brush_life_level-15-2: 39
brush_left_time-12-1: 10910
brush_life_level-12-2: 90
brush_cleaner.brush_left_time: 16910
brush_cleaner.brush_life_level: 93
filter.filter_life_level: 87
filter.filter_left_time: 7910
speaker.volume: 30
speaker.mute: 0
battery.charging_state: 1
state_updater: lan
vacuum.status_desc: Charging
miot_action_result:
  did: "558399571"
  miid: 0
  siid: 3
  aiid: 1
  code: 0
  exe_time: 52
  net_cost: 51
  ot_cost: 8
  otlocalts: 1735398488888724
  _oa_rpc_cost: 115
  withLatency: 0
sub_entities:
  - filter-10.filter_life_level-1
  - filter-10.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-11.brush_left_time-1
  - brush_cleaner-11.brush_life_level-2
  - brush_cleaner-12.brush_left_time-1
  - brush_cleaner-12.brush_life_level-2
  - brush_cleaner-15.brush_left_time-1
  - brush_cleaner-15.brush_life_level-2
friendly_name: Jason Robot Cleaner
supported_features: 12539
miot_local: true
miot_cloud: false
miot_cloud_action: true
```
```


### Home Assistant Logs / 系统日志

```
homeassistant  | 2024-12-28 15:00:16.145 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
homeassistant  | 2024-12-28 15:00:16.145 WARNING (SyncWorker_10) [custom_components.xiaomi_miot.core.device.roidmi.vacuum.v60] Call miot action {'did': '558399571', 'siid': 14, 'aiid': 1, 'in': [2, '{"mapId":1666280717,"segmentId":[6]}']} failed: Unable to recover failed command
homeassistant  | 2024-12-28 15:00:25.442 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: timed out
homeassistant  | 2024-12-28 15:00:25.443 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.roidmi.vacuum.v60] Got MiioException while fetching the state: No response from the device, mapping: {'custom.clean_area': {'siid': 8, 'piid': 7}, 'custom.water_level': {'siid': 8, 'piid': 11}, 'custom.clean_time': {'siid': 8, 'piid': 19}, 'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}}, max_properties: 6/6
homeassistant  | 2024-12-28 15:00:26.148 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.roidmi_v60_8c2d_robot_cleaner is taking over 10 seconds
homeassistant  | 2024-12-28 15:00:26.795 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
homeassistant  | 2024-12-28 15:00:26.795 WARNING (SyncWorker_6) [custom_components.xiaomi_miot.core.device.roidmi.vacuum.v60] Call miot action {'did': '558399571', 'siid': 8, 'aiid': 1, 'in': []} failed: Unable to recover failed command
homeassistant  | 2024-12-28 15:00:52.396 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
homeassistant  | 2024-12-28 15:00:52.396 WARNING (SyncWorker_6) [custom_components.xiaomi_miot.core.device.roidmi.vacuum.v60] Call miot action {'did': '558399571', 'siid': 14, 'aiid': 1, 'in': [2, '{"mapId":1666280717,"segmentId":[6]}']} failed: Unable to recover failed command
homeassistant  | 2024-12-28 15:00:54.654 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
homeassistant  | 2024-12-28 15:00:54.654 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
homeassistant  | 2024-12-28 15:00:54.655 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.roidmi.vacuum.v60] Got MiioException while fetching the state: Unable to recover failed command, mapping: {'custom.mop': {'siid': 8, 'piid': 1}, 'custom.auto_boost': {'siid': 8, 'piid': 9}, 'custom.double_clean': {'siid': 8, 'piid': 20}, 'custom.edge_sweep': {'siid': 8, 'piid': 21}, 'custom.led_switch': {'siid': 8, 'piid': 22}, 'custom.lidar_collision': {'siid': 8, 'piid': 23}, 'speaker.mute': {'siid': 9, 'piid': 2}}, max_properties: 7/7
homeassistant  | 2024-12-28 15:00:54.658 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
homeassistant  | 2024-12-28 15:00:54.659 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.roidmi.vacuum.v60] Got MiioException while fetching the state: Unable to recover failed command, mapping: {'custom.clean_area': {'siid': 8, 'piid': 7}, 'custom.water_level': {'siid': 8, 'piid': 11}, 'custom.clean_time': {'siid': 8, 'piid': 19}, 'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}}, max_properties: 6/6
homeassistant  | 2024-12-28 15:00:54.661 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.roidmi.vacuum.v60] Got MiioException while fetching the state: Unable to recover failed command, mapping: {'sweep.sweep_mode': {'siid': 14, 'piid': 1}, 'custom.work_station_freq': {'siid': 8, 'piid': 2}, 'custom.timing': {'siid': 8, 'piid': 6}, 'custom.uid': {'siid': 8, 'piid': 8}, 'custom.forbid_mode': {'siid': 8, 'piid': 10}, 'custom.total_clean_time': {'siid': 8, 'piid': 13}, 'custom.total_clean_areas': {'siid': 8, 'piid': 14}, 'custom.clean_counts': {'siid': 8, 'piid': 18}, 'custom.station_key': {'siid': 8, 'piid': 24}, 'custom.station_led': {'siid': 8, 'piid': 25}, 'custom.current_audio': {'siid': 8, 'piid': 26}, 'custom.progress': {'siid': 8, 'piid': 28}, 'custom.station_type': {'siid': 8, 'piid': 29}, 'custom.voice_conf': {'siid': 8, 'piid': 30}, 'speaker.volume': {'siid': 9, 'piid': 1}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}, 'vacuum.fault': {'siid': 2, 'piid': 2}}, max_properties: 9/18
```

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by pkoutsovasilis** [comment]
Hey 👋 sorry for the delay, I just tried `v1.0.8` and the issues persist:
* after waiting a bit I realised that the commands like change clean times, carpet auto-pressure mode, etc. are executed but they are really really slow to finish.
* room cleaning still nevers succeeds

as before, restoring to the older `v0.7.25` resolves all of the issues

**Comment by Rgokcay** [comment]
> Ana dalı deneyin.
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

0.7.25 versiyonda herşey çok hızlı tepki veriyor ama 1.0.7 ve sonrasıda çok yavaş tepki veriyor seçeneklerinin süpürgeye iletilmesi 2 dakika sürüyor

**Comment by pkoutsovasilis** [comment]
@al-one anything more I could extract to help resolve this bug? 🙂

**Comment by pkoutsovasilis** [comment]
just tested with `v1.0.9` and the issue persists. 🙂

**Comment by pkoutsovasilis** [comment]
just tested with `v1.0.12` and the issue persists. 🙂

**Comment by Rgokcay** [comment]
V0.7.25 versiyonuna dönmek daha iyi sorun devam ediyor

**Comment by pkoutsovasilis** [comment]
fiddling around more with this I see this error in the logs

```
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
homeassistant  |     self.data = await self._async_update_data()
homeassistant  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
homeassistant  |     return await self.update_method()
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/xiaomi_miot/core/device.py", line 530, in _update
homeassistant  |     result = await self.update_miot_status(mapping)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/xiaomi_miot/core/device.py", line 873, in update_miot_status
homeassistant  |     res = await self.local.async_get_properties_for_mapping(
homeassistant  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |     ...<3 lines>...
homeassistant  |     )
homeassistant  |     ^
homeassistant  |   File "/config/custom_components/xiaomi_miot/core/device.py", line 1386, in async_get_properties_for_mapping
homeassistant  |     return await self.hass.async_add_executor_job(
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |     ...<6 lines>...
homeassistant  |     )
homeassistant  |     ^
homeassistant  |   File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
homeassistant  |     result = self.fn(*self.args, **self.kwargs)
homeassistant  |   File "/config/custom_components/xiaomi_miot/core/device.py", line 1379, in get_properties_for_mapping
homeassistant  |     return self.get_properties(
homeassistant  |            ~~~~~~~~~~~~~~~~~~~^
homeassistant  |         properties,
homeassistant  |         ^^^^^^^^^^^
homeassistant  |         property_getter='get_properties',
homeassistant  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |         max_properties=max_properties,
homeassistant  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |     )
homeassistant  |     ^
homeassistant  |   File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 240, in get_properties
homeassistant  |     values.extend(self.send(property_getter, _props[:max_properties]))
homeassistant  |                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
homeassistant  |     return self._protocol.send(
homeassistant  |            ~~~~~~~~~~~~~~~~~~~^
homeassistant  |         command, parameters, retry_count, extra_parameters=extra_parameters
homeassistant  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |     )
homeassistant  |     ^
homeassistant  |   File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
homeassistant  |     self.__id = payload["id"]
homeassistant  |                 ~~~~~~~^^^^^^
homeassistant  | TypeError: byte indices must be integers or slices, not str
```

**Comment by pkoutsovasilis** [comment]
just tested `v1.0.13` and the issue still persists 🙂

**Comment by al-one** [comment]
Try master branch again.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by pkoutsovasilis** [comment]
the issue is still there with v1.0.15. One observation I did is that with v0.7.25 I see the following

In the firmware it says `(lan)` and most entities on the right are disabled which is correct since I have the following

```
homeassistant:
    customize:
      vacuum.roidmi_v60_8c2d_robot_cleaner:
        exclude_miot_services: null
        miot_local: true         # Force to read and write data in LAN
        miot_cloud: false        # Enable miot cloud for entity (read, write, action)
        # miot_cloud_write: true  # (Optional) Enable miot cloud (only write)
        miot_cloud_action: true  # (Optional) Enable miot cloud (only action)
```

<img width="667" alt="Image" src="https://github.com/user-attachments/assets/47e1bdf6-8769-413f-b1fd-f350e2875fae" />

where on v1.0.15 I see the wifi icon instead of `(lan)` and most of the entities on the right enabled.

<img width="663" alt="Image" src="https://github.com/user-attachments/assets/87af041e-a5e6-4fe6-93a0-f6e6a73204f3" />

Also the following logs which make me suspect that this isn't using local mode on `v1.0.15`?! 🤔 

```
homeassistant  | 2025-03-21 23:00:00.906 WARNING (MainThread) [custom_components.xiaomi_miot.core.xiaomi_cloud] Error while decrypting response of request to https://de.api.io.mi.com/app/scene/history :internal server err
homeassistant  | 2025-03-21 23:00:00.907 WARNING (MainThread) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request xiaomi api: scene/history {'home_id': {redacted}, 'uid': {redacted}, 'owner_uid': {redacted}, 'command': 'history', 'limit': 15} failed, response: internal server err
```
