### ISSUE TITLE
ViomiSE cant read some attributes when defining sensors 

### ISSUE THREAD

**Issue by kodifan** [al-one/hass-xiaomi-miot#223]
Helo
I recently discovered this integration i want test it a little more (before that I was using Viomi Robot Vacuum Cleaner SE (V-RVCLM21A) integration). I added this integration using HACS (so latest available ). Vacuum has been added without problems (screen attached). I can start cleaning, change fan settings, all is working as expected. 
![viomise](https://user-images.githubusercontent.com/7819312/139104464-755a6341-46b8-4db3-90a4-09fe920bc78c.png)
But for this old integration i had configured a set of sensors (like consumable statistics or last area cleaned etc.)
Unfortunately not all are working with this integrations. 

Those are all attributes that I can read from developers settings:
```yaml
entity_class: MiotViomiVacuumEntity
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:viomi-v19:2
vacuum.status: 4
vacuum.fault: 2105
vacuum.wdr_mode: 0
vacuum.door_state: 3
vacuum.contact_state: 0
vacuum-2.contact_state: 11
vacuum-2.contact_state-16: 9
vacuum.mute: 7
vacuum.sweep_type: 0
vacuum.mode: 2
voice.target_voice: 
voice.cur_voice: 
voice.download_status: 0
voice.download_progress: 0
voice.voice_url.error: -4001 Property is not readable
voice.voice_mdfive.error: -4001 Property is not readable
map.map_type: 0
map.map_id: 0
map.new_map_oper.error: -4001 Property is not readable
map.map_name: map_1
map.lang.error: -4001 Property is not readable
map.arrange_room_ids.error: -4001 Property is not readable
map.target_room_id.error: -4001 Property is not readable
map.split_points.error: -4001 Property is not readable
map.room_name.error: -4001 Property is not readable
point_zone.target_point: [1100,1100]
point_zone.zone_points.error: -4001 Property is not readable
point_zone.restrict_points.error: -4001 Property is not readable
point_zone.pause_type.error: -4001 Property is not readable
order.order_id.error: -4001 Property is not readable
order.enable.error: -4001 Property is not readable
order.day.error: -4001 Property is not readable
order.hour.error: -4001 Property is not readable
order.minute.error: -4001 Property is not readable
order.repeat.error: -4001 Property is not readable
order.clean_way.error: -4001 Property is not readable
order.suction.error: -4001 Property is not readable
order.water.error: -4001 Property is not readable
order.twice_clean.error: -4001 Property is not readable
order.mapid.error: -4001 Property is not readable
order.room_count.error: -4001 Property is not readable
order.room_data.error: -4001 Property is not readable
order.dnd_enable: 1
order.dnd_start_hour: 22
order.dnd_start_minute: 0
order.dnd_end_hour: 8
order.dnd_end_minute: 0
order.dnd_timezone: -7200
order.timestamp: 0
viomi_vacuum.repeat_state: 0
viomi_vacuum.remember_state: 1
viomi_vacuum.has_map: 1
viomi_vacuum.has_newmap: 0
viomi_vacuum.mop_route: 0
viomi_vacuum.side_brush_life: 81
viomi_vacuum.side_brush_hours: 147
viomi_vacuum.main_brush_life: 90
viomi_vacuum.main_brush_hours: 327
viomi_vacuum.hypa_life: 81
viomi_vacuum.hypa_hours: 147
viomi_vacuum.mop_life: 91
viomi_vacuum.mop_hours: 164
viomi_vacuum.direction.error: -4001 Property is not readable
viomi_vacuum.suction_grade: 2
viomi_vacuum.water_grade: 1
viomi_vacuum.consumable_index: 0
viomi_vacuum.clean_room_ids: 
viomi_vacuum.clean_room_mode: 0
viomi_vacuum.clean_room_oper: 0
viomi_vacuum.map_num: 2
viomi_vacuum.time_zone: -7200
viomi_vacuum.clean_start_time: 0
viomi_vacuum.clean_use_time: 0
viomi_vacuum.clean_area: 0
viomi_vacuum.clean_map_url: 
viomi_vacuum.clean_mode: 0
viomi_vacuum.clean_way: 0
viomi_vacuum.cur_lang: pl
viomi_vacuum.cur_map_id: 1625227368
battery.battery_level: 100
state_updater: lan
miio.props: 
sub_entities: battery-3.battery_level-1
friendly_name: Viomi SE Robot Cleaner
supported_features: 13048
```

Only few are working (like status or battery) others configured according to above attributes are either faulty in the logs or throws 0 or nothing not a real value. 
Also some seem to have correct values in non making sense a attributes (like last cleaned area and last cleaned time values are populated to  `vacuum-2.contact_state: 11` and `vacuum-2.contact_state-16: 9` not to `viomi_vacuum.clean_use_time: 0` and
`viomi_vacuum.clean_area: 0`. And still cannot read even from those `vacuum-2.contact_state` attributes. 

So the question is :  Im I doing something wrong or this vacuum is still poorly implemented and have to wait for next release to fix it ?
