### ISSUE TITLE
izq.sensor_occupy.trio 出现两个光照度传感器 其中一个状态为未知

### ISSUE THREAD

**Issue by ptbsare** [al-one/hass-xiaomi-miot#2231]
### Device model / 设备型号

[izq.sensor_occupy.trio](https://home.miot-spec.com/s/izq.sensor_occupy.trio)

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2025.1 beta 

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

![Screen Shot 2024-12-29 at 11 47 35](https://github.com/user-attachments/assets/fe2c4309-5b34-4150-85f8-c61681467238)

### Entity attributes / 实体属性

```yaml
app_link: 
miot_type: urn:miot-spec-v2:device:occupancy-sensor:0000A0BF:izq-trio:2
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2024-12-29 11:39:37.673853+08:00
occupancy_config.bio_sensitive: 100
shadow_tracking-3-2: true
switch_sensor.status: 0
switch_sensor-6.status: 0
switch_sensor-6.status-3: 0
switch_sensor-6.status-4: 0
switch_sensor-6.status-5: 0
switch_sensor-6.status-6: 0
indicator_light.on: true
occupancy_status-2-1: 0
occupancy_sensor.illumination: 29
state_updater: local
switch_sensor.status_desc: NoShow
converters: button.info, sensor.occupancy_status-2-1, light.indicator_light.on, sensor.occupancy_sensor.illumination, sensor.illumination, switch.shadow_tracking-3-2, number.occupancy_config.bio_sensitive, button.occupancy_config.led_toggle, button.occupancy_config.find_device
customizes: 
sensor_properties: occupancy_status,illumination
number_properties: bio_sensitive
switch_properties: indicator_light,shadow_tracking
button_actions: led_toggle,find_device

device_class: update

friendly_name: 主卧卫生间人在传感器 信息
```
```


### Home Assistant Logs / 系统日志

_No response_
