### ISSUE TITLE
小米智能晾衣机PRO hyd.airer.pro 无法控制设备，老版本没问题

### ISSUE THREAD

**Issue by rpeng6** [al-one/hass-xiaomi-miot#2252]
### Device model / 设备型号

[hyd.airer.pro](https://home.miot-spec.com/s/hyd.airer.pro)

### Component version / 插件版本

10.7

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

晾衣架在老版本上开灯升降都能控制，在1.0.7上无法控制了

### Entity attributes / 实体属性

```yaml
target2current_position: true
airer.status: 3
airer.motor_control: null
device_class: awning
friendly_name: Smart Clothes Drying Rack Airer
supported_features: 11

Attribute
target2current_position: true
airer.status: 3
airer.motor_control: null
device_class: awning
friendly_name: Smart Clothes Drying Rack Airer
supported_features: 11
```
