### ISSUE TITLE
zhimi.heater.nb1 unsupported "Return to middle" after update

### ISSUE THREAD

**Issue by lokkyua** [al-one/hass-xiaomi-miot#2255]
### Device model / 设备型号

[zhimi.heater.nb1](https://home.miot-spec.com/s/zhimi.heater.nb1)

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi! After update got unsupported Smartmi fan heater "Return to middle" attribute. I'm not sure which integration method I used. What additional information should I provide?

### Entity attributes / 实体属性

```yaml
switch.zhimi_nb1_18de_return_to_middle
Smartmi fan heater Return to middle

state:unavailable

restored: true
icon: mdi:format-horizontal-align-center
friendly_name: Smartmi fan heater Return to middle
supported_features: 0
```
