### ISSUE TITLE
UVFive lamp missing power switch in 1.x.x versions

### ISSUE THREAD

**Issue by Sergmasharov** [al-one/hass-xiaomi-miot#2257]
### Device model / 设备型号

uvfive.s_lamp.slmap2

### Component version / 插件版本

works on 0.7.25

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

After update to any 1.0.x version there is no Xiaomi Miot Germicidal Lamp Switch Status (not provided). I cant power on\off device
Downgrade to 0.7.25 solve problem

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: Xiaomi Miot Info
info: Xiaomi Miot
model: uvfive.s_lamp.slmap2
did: 
mac: 
lan_ip: 192.168.1.32
app_link: 
miot_type: urn:miot-spec-v2:device:germicidal-lamp:0000A09E:uvfive-slmap2:1
available: true
home_room: 
updater: local
updated_at: 2024-12-30 19:33:05.186171+04:00
radar.radar_on: false
physical_controls_locked: false
germicidal_lamp.fault: 0
germicidal_lamp.on: false
germicidal_lamp.status: 1
germicidal_lamp.target_time: 28
germicidal_lamp.left_time: 0
converters: button.info, switch.physical_controls_locked, sensor.germicidal_lamp.left_time, switch.radar.radar_on, number.germicidal_lamp.target_time
customizes: 
sensor_properties: left_time
switch_properties: uv,radar_on,lighting.on
number_properties: target_time

state_updater: local
germicidal_lamp.status_desc: Idle
```

### Home Assistant Logs / 系统日志

no errors
