### ISSUE TITLE
小米路由器AX3000T无法获取数据

### ISSUE THREAD

**Issue by wozjs5** [al-one/hass-xiaomi-miot#2258]
### Device model / 设备型号

xiaomi.router.rd03

### Component version / 插件版本

1.0.7

### HA core version / HA版本

20241127.8

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

路由去无法获取设备连接数，上传下载速度等信息
![screenshot_2024-12-31_15-09-13](https://github.com/user-attachments/assets/210abac3-375c-4107-963a-7015db8bdd82)

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 小米AX3000T 信息
info: 小米AX3000T
model: xiaomi.router.rd03
did: 864111000
mac: 58:ea:1f:0a:1d:65
lan_ip: 192.168.1.4
app_link: mihome://device?uid=2206344267&did=864111000
miot_type: urn:miot-spec-v2:device:router:0000A036:xiaomi-rd03:1
available: true
home_room: 润杰经典 主卧
updater: cloud
updated_at: 2024-12-31 15:10:18.091981+08:00
router.download_speed.error: -704030013 Property is not readable
router.upload_speed.error: -704030013 Property is not readable
router.connected_device_number.error: -704030013 Property is not readable
converters: button.info, sensor.router.download_speed, sensor.router.upload_speed, sensor.router.connected_device_number
customizes: 
{}
```

### Home Assistant Logs / 系统日志

Got MiioException while fetching the state: Unable to discover the device 192.168.1.67, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 5}}, max_properties: 4/4
Got MiioException while fetching the state: Unable to discover the device 192.168.1.67, mapping: {'yl_light.save_state': {'siid': 3, 'piid': 1}, 'yl_light.delay_time': {'siid': 3, 'piid': 2}, 'yl_light.delay_off_enable': {'siid': 3, 'piid': 4}, 'yl_light.double_click_enable': {'siid': 3, 'piid': 6}, 'yl_light.double_click': {'siid': 3, 'piid': 7}, 'yl_light.long_press_enable': {'siid': 3, 'piid': 8}, 'yl_light.scene_mode': {'siid': 3, 'piid': 9}, 'yl_light.long_press_one': {'siid': 3, 'piid': 13}, 'yl_light.long_press_two': {'siid': 3, 'piid': 14}, 'yl_light.long_press_three': {'siid': 3, 'piid': 15}, 'yl_light.work_minutes': {'siid': 3, 'piid': 16}, 'yl_light.break_minutes': {'siid': 3, 'piid': 17}, 'yl_light.pomodoro_enable': {'siid': 3, 'piid': 18}, 'yl_light.mode_one_bright': {'siid': 3, 'piid': 19}, 'yl_light.mode_one_ct': {'siid': 3, 'piid': 20}, 'yl_light.mode_two_bright': {'siid': 3, 'piid': 21}, 'yl_light.mode_two_ct': {'siid': 3, 'piid': 22}, 'yl_light.mode_three_bright': {'siid': 3, 'piid': 23}, 'yl_light.mode_three_ct': {'siid': 3, 'piid': 24}, 'yl_light.mode_four_bright': {'siid': 3, 'piid': 25}, 'yl_light.mode_four_ct': {'siid': 3, 'piid': 26}, 'yl_light.ble_paired_mac': {'siid': 3, 'piid': 27}, 'light.default_power_on_state': {'siid': 2, 'piid': 4}}, max_properties: 8/23
