### ISSUE TITLE
Please add for refrigerator midjd6.fridge.s16 objects 'select_properties': 'mode'

### ISSUE THREAD

**Issue by MikhailTeddy** [al-one/hass-xiaomi-miot#2259]
### Device model / 设备型号

[midjd6.fridge.s16](https://home.miot-spec.com/s/midjd6.fridge.s16)

### Component version / 插件版本

v1.0.7

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Token

### The problem / 问题详情

This model has buttons in the application for presetting modes: "Smart", "Quick coolling", "Quick frozen", "Holiday" and for the adjustable drawer: "Premium", "Maternal-infant Products", "Zero Degree"

In my device_customizes.py file, I made the following entries, now I can select presets in HA as in the application.

'midjd6.fridge.s16': {
'select_properties': 'mode',
},

### Entity attributes / 实体属性

```yaml
select.midjd6_s16_mode
options:
  - None
  - Smart
  - Quick Cooling
  - Quick Frozen
  - Holiday
fridge.mode: 1
friendly_name: Xiaomi refrigerator Fridge Mode

select.midjd6_s16_mode_2
options:
  - Premium
  - Maternal-infant Products
  - Zero Degree
fridge_chamber-6.mode: 0
friendly_name: Xiaomi refrigerator Change Cabin Mode
```
