### ISSUE TITLE
Please add szxzh.diffuser.v03

### ISSUE THREAD

**Issue by wisemars** [al-one/hass-xiaomi-miot#2260]
### Device model / 设备型号

szxzh.diffuser.v03

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Please add the device support "Intelligent aromatic diffuser of the V series" (szxzh.diffuser.v03)

### Entity attributes / 实体属性

```yaml
info: Intelligent Aroma Diffuser V Series
model: szxzh.diffuser.v03
did: blt.3.1jut6lo2c4k01
mac: C0:3F:3C:02:D9:5E
lan_ip: 178.129.60.114
app_link: mihome://device?uid=236514570&did=blt.3.1jut6lo2c4k01
miot_type: urn:miot-spec-v2:device:diffuser:0000A01E:szxzh-v03:1
available: true
home_room: My Appartment Bathroom
icon: mdi:information
updater: none
updated_at: 
converters: button.info
customizes: 
{}

device_class: update
friendly_name: Intelligent Aroma Diffuser V Series Info
```
