### ISSUE TITLE
Cooker chunmi.cooker.wy3 working not stable

### ISSUE THREAD

**Issue by anhnvme** [al-one/hass-xiaomi-miot#2263]
### Device model / 设备型号

chunmi.cooker.wy3

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2024.12.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Device not stable. It show unknow then show state every 5 second. I think sould modify update time
On version 1.0.3 still working fine.
<img width="306" alt="image" src="https://github.com/user-attachments/assets/fdd75792-a2bc-43c4-aa05-d1599b46feb6" />
<img width="575" alt="image" src="https://github.com/user-attachments/assets/5db15cca-01ec-45ba-a37c-4704bf9eb5e1" />

### Entity attributes / 实体属性

```yaml
info: Xiaomi Smart Rice Cooker 3L
model: chunmi.cooker.wy3
did: 532864132
mac: xxxxxxxxxx
lan_ip: 192.168.x.xx
app_link: mihome://device?uid=1677330987&did=532864132
miot_type: urn:miot-spec-v2:device:cooker:0000A00B:chunmi-wy3:3
available: true
home_room: SweetHome Kitchen
icon: mdi:information
updater: local
updated_at: 2025-01-02 09:38:37.025070+07:00
cooker.status: 1
custom.menu_id: 2
custom.cook_total_time: 30
custom.left_time: 3744
custom.keepwarm_time: 36
custom.auto_keepwarm_flag: true
custom.recipe_type: 0
custom.pre_left_time: 0
custom.rice_type: 1
custom.taste: 0
custom.no_pan_flag: 0
self_check.self_check_results: Don't get me ,I am parameter,doge!
self_check.manual_check_results: 0
cooker.fault: 0
converters: button.info, sensor.cooker.status, cooker.fault, sensor.custom.left_time, button.cooker.cancel_cooking, select.cooker.start_cook
customizes: 
sensor_properties: temperature,left_time
switch_properties: on,auto_keep_warm
button_actions: pause,cancel_cooking
select_actions: start_cook
chunk_coordinators:
  - interval: 10
    props: on,status

device_class: update
friendly_name: Xiaomi Smart Rice Cooker 3L Info
```

### Home Assistant Logs / 系统日志

2025-01-02 09:36:06.801 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Update miot status: {'use_local': [True, True, <MiotDevice: 192.168.1.42 (token: d382eedef8c877fa9e66c4178222239b)>], 'use_cloud': [False, False, None], 'mapping': {'custom.menu_id': {'siid': 3, 'piid': 1}, 'custom.cook_total_time': {'siid': 3, 'piid': 2}, 'custom.left_time': {'siid': 3, 'piid': 3}, 'custom.keepwarm_time': {'siid': 3, 'piid': 4}, 'custom.auto_keepwarm_flag': {'siid': 3, 'piid': 5}, 'custom.recipe_type': {'siid': 3, 'piid': 6}, 'custom.pre_left_time': {'siid': 3, 'piid': 7}, 'custom.rice_type': {'siid': 3, 'piid': 8}, 'custom.taste': {'siid': 3, 'piid': 9}, 'custom.no_pan_flag': {'siid': 3, 'piid': 21}, 'self_check.self_check_results': {'siid': 4, 'piid': 2}, 'self_check.manual_check_results': {'siid': 4, 'piid': 3}, 'cooker.fault': {'siid': 2, 'piid': 2}}}
2025-01-02 09:36:07.022 INFO (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Device updated: {'sensor.custom.left_time': 3744, 'cooker.fault': 'No Faults', 'only_info': False}
2025-01-02 09:36:07.022 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] sensor.chunmi_wy3_1a84_status: Entity state updated: None
2025-01-02 09:36:07.022 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] sensor.chunmi_wy3_1a84_left_time_2: Entity state updated: 3744
2025-01-02 09:36:07.023 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.chunmi_wy3_1a84_info_2: Entity state updated: Xiaomi Smart Rice Cooker 3L
2025-01-02 09:36:07.023 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Finished fetching 7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-miot_status data in 0.223 seconds (success: True)
2025-01-02 09:36:07.023 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Xiaomi Smart Rice Cooker 3L(chunmi.cooker.wy3): Coordinator updated: ['7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-miot_status', <custom_components.xiaomi_miot.core.miot_spec.MiotResults object at 0x7fcc2ff8f690>]
2025-01-02 09:36:14.959 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Update miot status: {'use_local': [True, True, <MiotDevice: 192.168.1.42 (token: d382eedef8c877fa9e66c4178222239b)>], 'use_cloud': [False, False, None], 'mapping': {'cooker.status': {'siid': 2, 'piid': 1}}}
2025-01-02 09:36:15.022 INFO (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Device updated: {'sensor.cooker.status': 'idle', 'only_info': False}
2025-01-02 09:36:15.022 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] sensor.chunmi_wy3_1a84_status: Entity state updated: idle
2025-01-02 09:36:15.023 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.chunmi_wy3_1a84_info_2: Entity state updated: Xiaomi Smart Rice Cooker 3L
2025-01-02 09:36:15.023 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Finished fetching 7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-chunk_1 data in 0.065 seconds (success: True)
2025-01-02 09:36:15.023 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Xiaomi Smart Rice Cooker 3L(chunmi.cooker.wy3): Coordinator updated: ['7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-chunk_1', <custom_components.xiaomi_miot.core.miot_spec.MiotResults object at 0x7fcc365c5390>]
2025-01-02 09:36:24.959 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Update miot status: {'use_local': [True, True, <MiotDevice: 192.168.1.42 (token: d382eedef8c877fa9e66c4178222239b)>], 'use_cloud': [False, False, None], 'mapping': {'cooker.status': {'siid': 2, 'piid': 1}}}
2025-01-02 09:36:25.133 INFO (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Device updated: {'sensor.cooker.status': 'idle', 'only_info': False}
2025-01-02 09:36:25.133 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] sensor.chunmi_wy3_1a84_status: Entity state updated: idle
2025-01-02 09:36:25.134 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.chunmi_wy3_1a84_info_2: Entity state updated: Xiaomi Smart Rice Cooker 3L
2025-01-02 09:36:25.134 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Finished fetching 7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-chunk_1 data in 0.176 seconds (success: True)
2025-01-02 09:36:25.134 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Xiaomi Smart Rice Cooker 3L(chunmi.cooker.wy3): Coordinator updated: ['7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-chunk_1', <custom_components.xiaomi_miot.core.miot_spec.MiotResults object at 0x7fcc34288280>]
2025-01-02 09:36:34.960 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Update miot status: {'use_local': [True, True, <MiotDevice: 192.168.1.42 (token: d382eedef8c877fa9e66c4178222239b)>], 'use_cloud': [False, False, None], 'mapping': {'cooker.status': {'siid': 2, 'piid': 1}}}
2025-01-02 09:36:35.064 INFO (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Device updated: {'sensor.cooker.status': 'idle', 'only_info': False}
2025-01-02 09:36:35.065 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] sensor.chunmi_wy3_1a84_status: Entity state updated: idle
2025-01-02 09:36:35.065 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.chunmi_wy3_1a84_info_2: Entity state updated: Xiaomi Smart Rice Cooker 3L
2025-01-02 09:36:35.065 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.chunmi.cooker.wy3] Finished fetching 7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-chunk_1 data in 0.106 seconds (success: True)
2025-01-02 09:36:35.065 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Xiaomi Smart Rice Cooker 3L(chunmi.cooker.wy3): Coordinator updated: ['7c:c2:94:dd:1a:84-01JATCRK00FWSHVS9HRC4NJ2FF-chunk_1', <custom_components.xiaomi_miot.core.miot_spec.MiotResults object at 0x7fcc34288910>]
