### ISSUE TITLE
vacuum: Warning logs in HA beta

### ISSUE THREAD

**Issue by gieljnssns** [al-one/hass-xiaomi-miot#2266]
### Device model / 设备型号

roborock.vacuum.a15

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2025.1.0b5

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

There is a warning whit this device and the new beta

### Entity attributes / 实体属性

```yaml
info: Claptrap
model: roborock.vacuum.a15
did: 
mac: B0:4A:39:40:3B:25
lan_ip: 192.168.79.60
app_link: 
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:roborock-a15:1
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-01-02 09:16:50.920440+01:00
vacuum.status: 8
vacuum.mode: 102
filter.filter_life_level: 38
brush_life_level-10-2: 53
brush_cleaner.brush_life_level: -7
battery_level: 100
vacuum.fault: 0
vacuum.water_level: 203
vacuum.mop_mode: 300
state_updater: local
vacuum.status_desc: Charging
props: 
msg_ver: 2
msg_seq: 3775
state: 8
battery: 100
clean_time: 2805
clean_area: 44467500
error_code: 0
map_present: 1
in_cleaning: 0
in_returning: 0
in_fresh_state: 1
lab_status: 3
water_box_status: 0
fan_power: 102
dnd_enabled: 0
map_status: 3
is_locating: 0
lock_status: 0
water_box_mode: 203
water_box_carriage_status: 0
mop_forbidden_enable: 0
adbumper_status:
  - 0
  - 0
  - 0
water_shortage_status: 0
dock_type: 0
dust_collection_status: 0
auto_dust_collection: 1
mop_mode: 300
debug_mode: 0
dock_error_status: 0
unsave_map_reason: 0
unsave_map_flag: 0
main_brush_work_time: 1160846
side_brush_work_time: 337331
filter_work_time: 337331
filter_element_work_time: 0
sensor_dirty_time: 337331
dust_collection_work_times: 0
fan_mode: 102
water_level: 203

clean_area: 44.5
clean_time: 46.8
room_mapping: 
- - 20
  - '439001050952'
  - 20
- - 21
  - '439001050811'
  - 21
- - 22
  - '439001050810'
  - 22
- - 16
  - '439001050813'
  - 16
- - 17
  - '439001050815'
  - 17
- - 18
  - '439001050814'
  - 18
- - 19
  - '439001050812'
  - 19

converters: button.info, sensor.filter.filter_life_level, sensor.brush_cleaner.brush_life_level, sensor.brush_life_level-10-2, sensor.battery_level, sensor.vacuum.status, select.vacuum.water_level, select.vacuum.mop_mode, button.vacuum.start_sweep, button.vacuum.stop_sweeping, button.vacuum.start_mop, button.vacuum.start_sweep_mop, button.battery.start_charge, button.identify.identify, sensor.props:clean_area, sensor.props:clean_time
customizes: 
binary_sensor_properties: mop_status
sensor_properties: vacuum.status
select_properties: water_level,mop_mode
number_properties: volume
button_actions: >-
  start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
configuration_entities: reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
chunk_coordinators:
  - interval: 10
    props: status,cleaning_area,cleaning_time,charging_state
    notify: true
  - interval: 15
    props: mode,sweep_mop_type,sweep_type,clean_times
sensor_attributes: props:clean_area,props:clean_time

device_class: update
friendly_name: Claptrap Info
```

### Home Assistant Logs / 系统日志

```
Detected that custom integration 'xiaomi_miot' is setting state directly. Entity xiaomi_miot.roborock_a15_3b25_robot_cleaner (<class 'custom_components.xiaomi_miot.vacuum.MiotRoborockVacuumEntity'>) should implement the 'activity' property and return its state using the VacuumActivity enum at custom_components/xiaomi_miot/vacuum.py, line 70: async_add_entities(entities, update_before_add=True). This will stop working in Home Assistant 2026.1, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
```
