### ISSUE TITLE
Device showing unavailable. 

### ISSUE THREAD

**Issue by reesion** [al-one/hass-xiaomi-miot#227]
Hi 

I have a device [zhimi.heater.nb1](https://home.miot-spec.com/s/zhimi.heater.nb1) and it is showing unavailable. 

I can confirm the device is responding via the xiaomi app. 

Any idea what would have caused this?

**Comment by al-one** [comment]
This model of heater supports the local miot protocol, did you integrate it with ip/token?
If the entity state is `unavailable`, an error/warning log should be generated. Please check if there is any [logs](https://my.home-assistant.io/redirect/logs) related to the device.

**Comment by reesion** [comment]
How do i do that? 

I tried adding the below to customize.yaml but getting error

```
xiaomi_miot:
  device_customizes:
    'zhimi.heater.nb1':
      miot_local: true
```
