### ISSUE TITLE
地暖温控器温度无法获取，显示0摄氏度，1.0.6及以前版本正常

### ISSUE THREAD

**Issue by uronn** [al-one/hass-xiaomi-miot#2275]
### Device model / 设备型号

suittc.airrtc.wk168

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![image](https://github.com/user-attachments/assets/b6d524f5-3e7d-4981-8fae-015274363f62)

### Entity attributes / 实体属性

```yaml
state_class: measurement
unit_of_measurement: °C
device_class: temperature
friendly_name: 客厅地暖 温度
```
