### ISSUE TITLE
部分设备信息变为未知，设备状态不能刷新

### ISSUE THREAD

**Issue by 123sensen** [al-one/hass-xiaomi-miot#2282]
### Device model / 设备型号

lemesh.light.wy0c08

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2024.4.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

部分蓝牙mash设备接入后不能同步设备状态，日志信息提示变为未知。
通过ha可以更改设备状态并同步至米家，反之不行。
![屏幕截图 2025-01-05 020421](https://github.com/user-attachments/assets/d6e51330-809b-4c09-a095-e2d3f80dfd65)

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 书房灯 信息
info: 书房灯
model: lemesh.light.wy0c08
did: "1092874159"
mac: EC:4D:3E:03:CB:54
lan_ip: fd00:0:5:e005::1d
app_link: mihome://device?uid=2191685502&did=1092874159
miot_type: urn:miot-spec-v2:device:light:0000A001:lemesh-wy0c08:1:0000C802
available: true
home_room: 三木的家庭 榻榻米
updater: cloud
updated_at: "2025-01-05 09:46:06.676325+08:00"
light.on: false
light.brightness: 8
light.color_temperature: 3292
light.mode: 0
remote.remote_switch: 1
remote.remote_ltype: 0
remote.remote_htype: 0
remote.remote_a: 0
remote.remote_b: 0
remote.remote_c: 0
remote.remote_d: 0
remote.remote_e: 0
remote.remote_f: 0
remote.remote_g: 0
remote.remote_h: 0
default: 0
default.light_save: 0
default.dimming: 0
default.inteligent_switch: 1
default.night_switch: 0
converters:
  - button.info
  - light.light.on
  - light.brightness
  - light.color_temperature
  - light.mode
customizes:
  number_properties: off_delay_time,light_on_gradient_time,light_off_gradient_time
  switch_properties: flex_switch,night_light_switch
  button_actions: toggle
  chunk_coordinators:
    - interval: 10
      props: on,brightness,color_temperature,color,mode
```

### Home Assistant Logs / 系统日志

[home-assistant_xiaomi_miot_2025-01-04T18-06-24.522Z.log](https://github.com/user-attachments/files/18308950/home-assistant_xiaomi_miot_2025-01-04T18-06-24.522Z.log)
