### ISSUE TITLE
Unsupported customize entity: number for air_purifier_favorite.fan_level

### ISSUE THREAD

**Issue by garry0garry** [al-one/hass-xiaomi-miot#2284]
### Device model / 设备型号

zhimi.airp.rma3

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Home Assistant 2025.1.0
Xiaomi Miot Auto 1.0.8

Xiaomi Smart Air Purifier 4 Lite
zhimi.airp.rma3
Firmware: 2.2.6_0033 🛜 

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.device.zhimi.airp.rma3
Source: custom_components/xiaomi_miot/core/device.py:442
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 8:35:05 PM (1 occurrences)
Last logged: 8:35:05 PM

Unsupported customize entity: number for air_purifier_favorite.fan_level
```

### Entity attributes / 实体属性

```yaml
info: Xiaomi Smart Air Purifier 4 Lite
model: zhimi.airp.rma3
did: xxx
mac: xxx
lan_ip: xxx
app_link: mihome://device?uid=xxx
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-rma3:1
available: true
icon: mdi:information
updater: local
updated_at: 2025-01-06 20:52:04.752470+03:00
aqi.aqi_updata_heartbeat: 300
custom_service.moto_speed_rpm: 420
filter_used_time_dbg-9-2: 3
physical_controls_locked: false
screen.brightness: 2
alarm: true
environment.relative_humidity: 25
environment.pm2_5_density: 2
environment.temperature: 22
environment.air_quality: 0
air_purifier.fault: 0
air_purifier_favorite.fan_level: 14
air_purifier.on: true
air_purifier.mode: 0
filter.filter_life_level: 100
filter.filter_used_time: 3
filter.filter_left_time: 145
converters: button.info, fan.air_purifier.on, air_purifier.on, air_purifier.mode, switch.alarm, switch.physical_controls_locked, sensor.filter.filter_life_level, sensor.filter.filter_left_time, sensor.filter.filter_used_time, sensor.environment.temperature, sensor.environment.relative_humidity, sensor.environment.pm2_5_density, sensor.environment.air_quality, sensor.custom_service.moto_speed_rpm, select.screen.brightness
customizes: 
switch_properties: alarm
sensor_properties: moto_speed_rpm
chunk_coordinators:
  - interval: 10
    props: on,mode,fan_level
  - interval: 300
    props: filter_life_level,filter_left_time,filter_used_time
select_properties: brightness
number_properties: air_purifier_favorite.fan_level

device_class: update
friendly_name: Xiaomi Smart Air Purifier 4 Lite Info
```
