### ISSUE TITLE
FutureWarning: functools.partial will be a method descriptor in future Python versions

### ISSUE THREAD

**Issue by garry0garry** [al-one/hass-xiaomi-miot#2287]
### Device model / 设备型号

zhimi.airp.rma3

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/xiaomi_miot/core/converters.py:4
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 12:52:55 PM (1 occurrences)
Last logged: 12:52:55 PM

/usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior Bool = partial(_str2bool)
```

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: Xiaomi Smart Air Purifier 4 Lite Info
info: Xiaomi Smart Air Purifier 4 Lite
model: zhimi.airp.rma3
did: xxx
mac: xxx
lan_ip: xxx
app_link: mihome://device?uid=xxx&did=xxx
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-rma3:1
available: true
updater: local
updated_at: 2025-01-07 13:04:32.145112+03:00
air_purifier_favorite.fan_level: 14
air_purifier.on: true
air_purifier.mode: 0
filter.filter_life_level: 100
filter.filter_used_time: 20
filter.filter_left_time: 145
aqi.aqi_updata_heartbeat: 300
custom_service.moto_speed_rpm: 420
filter_used_time_dbg-9-2: 20
physical_controls_locked: false
screen.brightness: 2
alarm: true
environment.relative_humidity: 24
environment.pm2_5_density: 1
environment.temperature: 22
environment.air_quality: 0
air_purifier.fault: 0
converters: button.info, fan.air_purifier.on, air_purifier.on, air_purifier.mode, switch.alarm, switch.physical_controls_locked, sensor.filter.filter_life_level, sensor.filter.filter_left_time, sensor.filter.filter_used_time, sensor.environment.temperature, sensor.environment.relative_humidity, sensor.environment.pm2_5_density, sensor.environment.air_quality, sensor.custom_service.moto_speed_rpm, select.screen.brightness
customizes: 
switch_properties: alarm
sensor_properties: moto_speed_rpm
chunk_coordinators:
  - interval: 10
    props: on,mode,fan_level
  - interval: 300
    props: filter_life_level,filter_left_time,filter_used_time
select_properties: brightness
number_properties: air_purifier_favorite.fan_level
```
