### ISSUE TITLE
ijai.vacuum.v3 - Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}

### ISSUE THREAD

**Issue by jonyrh** [al-one/hass-xiaomi-miot#2288]
### Device model / 设备型号

[ijai.vacuum.v3](https://home.miot-spec.com/s/ijai.vacuum.v3) (fw 4.3.3_0054@Linux)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.1

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Always errors in logs

### Entity attributes / 实体属性

```yaml
model: ijai.vacuum.v3
did: 

lan_ip: 192.168.0.19
app_link: 
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:ijai-v3:2
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-01-07 19:32:28.922830+05:00
sweep.cleaning_time: 22
sweep.cleaning_area: 14
vacuum.status: 4
vacuum.mode: 2
vacuum.sweep_type: 0
disturb.dnd_enable: 1
disturb.dnd_start_hour: 22
disturb.dnd_start_minute: 0
disturb.dnd_end_hour: 6
disturb.dnd_end_minute: 30
disturb.multi_prop_dnd: [1,22,0,6,30]
map.remember_state: 1
map.cur_map_id: 1722596557
map.map_num: 1
sweep.repeat_state: 0
sweep.suction_state: 0
sweep.water_state: 2
sweep.mop_route: 1
sweep.side_brush_life: 0
sweep.side_brush_hours: 1
sweep.main_brush_life: 50
sweep.main_brush_hours: 181
sweep.hypa_life: 0
sweep.hypa_hours: 1
sweep.mop_life: 0
sweep.mop_hours: 1
sweep.time_zone: -18000
sweep.cur_lang: ru_RU
sweep.multi_prop_vacuum: [0,3,1,0,2,1,-18000,22,14.5,0,"ru_RU","334702602212B08378","en_US",6,-1,0,0,1,2,1]
sweep.tank_shake: 1
sweep.shake_shift: 2
sweep.map_encrypt: 1
alarm: 1
alarm.volume: 0
battery_level: 100
vacuum.fault: 2105
vacuum.on: [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]
state_updater: local
vacuum.status_desc: Заряжается
converters: button.info, switch.alarm, number.alarm.volume, sensor.battery_level, sensor.vacuum.status, sensor.sweep.side_brush_life, sensor.sweep.main_brush_life, sensor.sweep.hypa_life, sensor.sweep.mop_life, switch.vacuum.on, switch.sweep.repeat_state, select.vacuum.mode, select.vacuum.sweep_type, select.sweep.water_state, button.vacuum.start_sweep, button.vacuum.stop_sweeping, button.vacuum.start_only_sweep, button.vacuum.start_sweep_mop, button.vacuum.start_mop, button.battery.start_charge
customizes: 
binary_sensor_properties: mop_status
sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
select_properties: mode,sweep_type,water_state
number_properties: volume
button_actions: >-
  start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
configuration_entities: reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
chunk_coordinators:
  - interval: 10
    props: status,cleaning_area,cleaning_time,charging_state
    notify: true
  - interval: 15
    props: mode,sweep_mop_type,sweep_type,clean_times
switch_properties: vacuum.on,repeat_state,alarm
exclude_miot_services: order
exclude_miot_properties: zone_points,restrict_points,target_point

device_class: update
friendly_name: Mi Robot Info
```

### Home Assistant Logs / 系统日志

2025-01-07 18:52:07.422 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}

2025-01-07 18:52:07.424 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.ijai.vacuum.v3] Got MiioException while fetching the state: Unable to recover failed command, mapping: {'disturb.dnd_enable': {'siid': 12, 'piid': 1}, 'disturb.dnd_start_hour': {'siid': 12, 'piid': 2}, 'disturb.dnd_start_minute': {'siid': 12, 'piid': 3}, 'disturb.dnd_end_hour': {'siid': 12, 'piid': 4}, 'disturb.dnd_end_minute': {'siid': 12, 'piid': 5}, 'disturb.multi_prop_dnd': {'siid': 12, 'piid': 7}, 'map.remember_state': {'siid': 10, 'piid': 1}, 'map.cur_map_id': {'siid': 10, 'piid': 2}, 'map.map_num': {'siid': 10, 'piid': 3}, 'map.cur_cleaning_path': {'siid': 10, 'piid': 5}, 'map.build_map': {'siid': 10, 'piid': 14}, 'map.has_new_map': {'siid': 10, 'piid': 19}, 'sweep.repeat_state': {'siid': 7, 'piid': 1}, 'sweep.door_state': {'siid': 7, 'piid': 3}, 'sweep.cloth_state': {'siid': 7, 'piid': 4}, 'sweep.suction_state': {'siid': 7, 'piid': 5}, 'sweep.water_state': {'siid': 7, 'piid': 6}, 'sweep.mop_route': {'siid': 7, 'piid': 7}, 'sweep.side_brush_life': {'siid': 7, 'piid': 8}, 'sweep.side_brush_hours': {'siid': 7, 'piid': 9}, 'sweep.main_brush_life': {'siid': 7, 'piid': 10}, 'sweep.main_brush_hours': {'siid': 7, 'piid': 11}, 'sweep.hypa_life': {'siid': 7, 'piid': 12}, 'sweep.hypa_hours': {'siid': 7, 'piid': 13}, 'sweep.mop_life': {'siid': 7, 'piid': 14}, 'sweep.mop_hours': {'siid': 7, 'piid': 15}, 'sweep.time_zone': {'siid': 7, 'piid': 20}, 'sweep.cur_lang': {'siid': 7, 'piid': 21}, 'sweep.multi_prop_vacuum': {'siid': 7, 'piid': 45}, 'sweep.tank_shake': {'siid': 7, 'piid': 48}, 'sweep.shake_shift': {'siid': 7, 'piid': 50}, 'sweep.map_encrypt': {'siid': 7, 'piid': 55}, 'alarm': {'siid': 4, 'piid': 1}, 'alarm.volume': {'siid': 4, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.on': {'siid': 2, 'piid': 9}}, max_properties: 9/37
