### ISSUE TITLE
zhimi.airpurifier.mb3 reset_filter_life not working

### ISSUE THREAD

**Issue by Trteich** [al-one/hass-xiaomi-miot#2292]
### Device model / 设备型号

[zhimi.airpurifier.mb3](https://home.miot-spec.com/s/zhimi.airpurifier.mb3)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi. Faced issue with zhimi.airpurifier.mb3. I've added
```
zhimi.airpurifier.mb3:
    button_actions: reset_filter_life
```

to device_customizes, but pressing 'Reset Filter Life' button throws error

### Entity attributes / 实体属性

```yaml
fan.gostinaia_ochistitel_vozdyha:
preset_modes: Auto, Sleep, Favorite, None
friendly_name: Гостиная очиститель воздуха
supported_features: 57
percentage: 33
percentage_step: 33.333333333333336
preset_mode: Favorite
speed_list: Level1, Level2, Level3
air_purifier.on: true
air_purifier.mode: 2
air_purifier.fan_level: 1
```

### Home Assistant Logs / 系统日志

2025-01-08 20:06:20.897 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.zhimi.airpurifier.mb3] Device write failed: [DeviceError({'code': -9998, 'message': 'user ack invalid'}), {'button.filter.reset_filter_life': None}, {'method': 'action', 'param': {'did': '307549972', 'siid': 4, 'aiid': 1, 'in': []}}]
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_miot/core/device.py", line 715, in async_write
    result = await self.local.async_send(method, param)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1376, in async_send
    return await self.hass.async_add_executor_job(partial(self.send,*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 275, in _handle_error
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -9998, 'message': 'user ack invalid'}
