### ISSUE TITLE
云移电动开窗器显示关闭状态有误

### ISSUE THREAD

**Issue by yun59t2** [al-one/hass-xiaomi-miot#2293]
### Device model / 设备型号

[yyunyi.wopener.yylt](https://home.miot-spec.com/s/yyunyi.wopener.yylt)

### Component version / 插件版本

2.2.8

### HA core version / HA版本

2024.12.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

无法显示关闭状态，当窗户关闭时，要么只能显示“3%”，要么一直显示“正在关闭”。与米家app里的状态不同。

### Entity attributes / 实体属性

```yaml
cover.window属性：
current_position: 0
model: yyunyi.wopener.yylt
lan_ip: 192.168.8.79
mac_address: 7C:C2:94:BF:6B:03
entity_class: MiotCoverEntity
miot_type: urn:miot-spec-v2:device:window-opener:0000A043:yyunyi-yylt:1
window_opener.fault: 0
window_opener.target_position: 0
window_opener.current_position: 0
window_opener.speed_level: 1
window_opener.status: 2
extend.rains_remind: true
extend.rains_stop: true
extend.wind_direction_mode: 0
extend.window_direction: 1
extend.rains_stop_open: false
extend.route_located: true
state_updater: cloud
window_opener.motor_control: 2
friendly_name: 主卧窗户
supported_features: 15
```
