### ISSUE TITLE
米家电饭煲较 0.x 版本缺少部分实体

### ISSUE THREAD

**Issue by littlesky87** [al-one/hass-xiaomi-miot#2294]
### Device model / 设备型号

[chunmi.cooker.normal2](https://home.miot-spec.com/s/chunmi.cooker.normal2)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家电饭煲在 1.x 版本的集成中缺少了之前 0.x 版本中的部分实体，如图片所示，缺少了 cooker_status 的 switch，以及 start_cook 的 button，新版本中这两个实体以标记为「集成“xiaomi_miot”不再提供此实体」，希望可以加回来。
<img width="680" alt="截屏2025-01-09 14 27 46" src="https://github.com/user-attachments/assets/d27d518d-8b44-4aae-b8c7-2a6b75086f69" />

### Entity attributes / 实体属性

```yaml
info: 电饭煲
model: chunmi.cooker.normal2
did: 61680690
mac: 34:CE:00:xx:xx:xx
lan_ip: 192.168.xxx.xxx
app_link: mihome://device?uid=xxxxx&did=61680690
miot_type: urn:miot-spec-v2:device:cooker:0000A00B:chunmi-normal2:1
available: true
home_room: 光谷188 厨房
icon: mdi:information
updater: cloud
updated_at: 2025-01-09 14:32:06.997572+08:00
cooker.status: 1
converters: button.info, sensor.cooker.status, button.cooker.cancel_cooking, select.cooker.start_cook
customizes: 
sensor_properties: temperature,left_time
switch_properties: on,auto_keep_warm
button_actions: pause,cancel_cooking
select_actions: start_cook
chunk_coordinators:
  - interval: 10
    props: on,status

device_class: update
friendly_name: 电饭煲 信息
```
