### ISSUE TITLE
suittc.airrtc.wk168 current_temperature 值变成了 0

### ISSUE THREAD

**Issue by geminiwen** [al-one/hass-xiaomi-miot#2295]
### Device model / 设备型号

[suittc.airrtc.wk168](https://home.miot-spec.com/s/suittc.airrtc.wk168)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.1

### Integrated mode / 集成方式

Automatic (自动模式)

### Entity attributes / 实体属性

```yaml
hvac_modes: heat, off
min_temp: 2
max_temp: 85
target_temp_step: 1
preset_modes: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, off
current_temperature: 0
temperature: 30
preset_mode: null
thermostat.on: true
thermostat.fan_level: 1
thermostat.mode: 9
thermostat.target_temperature: 30
state_updater: local
icon: mdi:radiator
friendly_name: 水暖 Thermostat
supported_features: 401
```
