### ISSUE TITLE
轮询时间修改

### ISSUE THREAD

**Issue by rugal7699** [al-one/hass-xiaomi-miot#2296]
由于缩短轮询时间可能会造成设备负载过高，是否有action可以用于修改轮询时间，方便设定自动化让设备在作动时和闲置时设定不同的轮询时间，减少设备负担。

**Comment by al-one** [comment]
1. 暂无动作(服务)可以修改轮训，也无计划支持
2. 可通过自定义选项`interval_seconds`增加设备默认的轮询时长
3. 再通过自动化更新指定的属性，参考 (#1558)
4. v1版本支持通过自定义选项`chunk_coordinators`实现分组轮询
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    brand.device.model: # 设备型号
      chunk_coordinators:
        - interval: 30 # 秒
          props: on,mode
        - interval: 60
          props: temperature,humidity
```
