### ISSUE TITLE
请教一下大佬，为啥自动化中的小爱音箱不支持HA的模版表达式

### ISSUE THREAD

**Issue by XieBrok** [al-one/hass-xiaomi-miot#2298]
```yaml
alias: 上传速度获取
description: ""
triggers:
  - entity_id:
      - sensor.xiaomi_l05c_d93e_conversation
    to: 上传速度
    trigger: state
actions:
  - target:
      entity_id: sensor.wireless_dual_band_router_tl_wdr5620_upload_speed
    action: homeassistant.update_entity
    data: {}
  - delay: "00:00:02"
  - variables:
      upload_speed_message: >
        当前的上传速度是 {{
        states('sensor.wireless_dual_band_router_tl_wdr5620_upload_speed') |
        float }} 兆字节每秒。
  - device_id: 1fec7c9ed38454d5fed3f5c8fba85dc0
    domain: text
    entity_id: f6550d332f8f4896f2d6fa916374aaac
    type: set_value
    value: "{{ upload_speed_message }}"
```

![image](https://github.com/user-attachments/assets/482f0e5c-4cd9-4a30-9139-60b43d70ae1f)
![image](https://github.com/user-attachments/assets/7aed57cb-4712-42cc-958d-4c0ac7dca1c3)

最后小爱音箱设置朗读文本的值时无法读取变量。
GPT给出的解释是
`米家插件不支持 Home Assistant 的模板表达式（{{ ... }}），因此音箱直接将模板字符串作为普通文本朗读。`
是我没写好YAML吗

**Comment by al-one** [comment]
最后一步用动作(服务):
```yaml
action: text.set_value
data:
  entity_id: text.xiaomi_xxxx_xxxx_play_text
  value: "{{ upload_speed_message }}"
```

**Comment by XieBrok** [comment]
OK，谢谢大佬

**Comment by Vector-Cross** [comment]
能再详细一点吗，比如贴一个能正确执行的配置全文

**Comment by XieBrok** [comment]
`
alias:` 上传速度获取
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.xiaomi_l05c_d93e_conversation
    to: "上传速度"  # 触发条件
actions:
  # 更新上传速度传感器的数据
  - service: homeassistant.update_entity
    target:
      entity_id: sensor.wireless_dual_band_router_tl_wdr5620_upload_speed

  # 等待传感器数据更新完成
  - delay: "00:00:02"

  # 使用模板渲染最终的文本
  - service: input_text.set_value
    target:
      entity_id: input_text.upload_message  # 提前定义的input_text实体
    data:
      value: >
        当前的上传速度是 {{
        "%.2f" % (states('sensor.wireless_dual_band_router_tl_wdr5620_upload_speed') | float)
        }} 兆字节每秒。

  # 将渲染后的内容直接传递给音箱
  - service: text.set_value
    target:
      entity_id: text.xiaomi_xxxx_xxxx_play_text  # 替换为小爱音箱的实体ID
    data:
      value: "{{ states('input_text.upload_message') }}"  # 获取预渲染的纯文本
mode: single
`

这样应该就行，替换一下实体就能用

**Comment by Vector-Cross** [comment]
调整了一下，这样搞定了，感谢大佬支持
```
alias: 查看水质
description: ""
triggers:
  - entity_id: sensor.xiaomi_lx05_084e_conversation
    to: 查看水质
    trigger: state
actions:
  - target:
      entity_id: 0f79723f3ac4e19a12fdb973a33ae87c
    action: homeassistant.update_entity
    data: {}
  - delay: "00:00:02"
  - variables:
      pattern_message: |
        家里净水器DTS是：{{ states('sensor.210006730837668_out_tds') | int }} 。
  - target:
      entity_id: 0f79723f3ac4e19a12fdb973a33ae87c
    data:
      value: "{{ pattern_message }}"
    action: text.set_value
mode: single

```
