### ISSUE TITLE
yeelink.bhf_light.v10浴霸换气、加热、吹风实体不可用

### ISSUE THREAD

**Issue by micturkey** [al-one/hass-xiaomi-miot#2302]
### Device model / 设备型号

yeelink.bhf_light.v10

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

浴霸换气、加热、吹风实体不可用
日志检查并未有明显错误，
按 https://github.com/al-one/hass-xiaomi-miot/issues/1257 检查并开启云端模式后也无效

### Entity attributes / 实体属性

```yaml
均为unavailable，例如
unavailable 	restored: true
icon: mdi:wind-turbine
friendly_name: 浴霸吹风
supported_features: 0
```

### Home Assistant Logs / 系统日志

日志检查无明显异常，且过大，无法上传
