### ISSUE TITLE
温控器无法查看实时温度显示为0

### ISSUE THREAD

**Issue by komawh** [al-one/hass-xiaomi-miot#2305]
### Device model / 设备型号

suittc.airrtc.wk168

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

前几个版本更新之后温控器的实时温度就没有显示了，米家APP中能正常显示，温度控制是正常的，在米家APP中设置后HA能同步，在HA中设置米家也能同步，通讯应该是正常的，就是实时温度为0。5个温控器都一样的问题。

### Entity attributes / 实体属性

```yaml
climate.suittc_wk168_491e_thermostat
客厅地暖 Thermostat
heat	hvac_modes: heat, off
min_temp: 2
max_temp: 85
target_temp_step: 1
preset_modes: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, off
current_temperature: 0
temperature: 20
preset_mode: null
thermostat.on: true
thermostat.fan_level: 1
thermostat.mode: 1
thermostat.target_temperature: 20
state_updater: local
friendly_name: 客厅地暖 Thermostat
supported_features: 401
```

### Home Assistant Logs / 系统日志

日志记录器: custom_components.xiaomi_miot.core.device.suittc.airrtc.wk168
来源: custom_components/xiaomi_miot/core/device.py:868
集成: Xiaomi Miot Auto ([文档](https://github.com/al-one/hass-xiaomi-miot), [问题](https://github.com/al-one/hass-xiaomi-miot/issues))
首次出现: 2025年1月10日 01:29:04 (30553 次总计出现)
上次记录: 11:33:06

Got MiioException while fetching the state: No response from the device, mapping: {'custom_program.mon_pro': {'siid': 3, 'piid': 1}, 'custom_program.tue_pro': {'siid': 3, 'piid': 2}, 'custom_program.wed_pro': {'siid': 3, 'piid': 3}, 'custom_program.thur_pro': {'siid': 3, 'piid': 4}, 'custom_program.fri_pro': {'siid': 3, 'piid': 5}, 'custom_program.sat_pro': {'siid': 3, 'piid': 6}, 'custom_program.sun_pro': {'siid': 3, 'piid': 7}, 'thermostat.temperature': {'siid': 2, 'piid': 5}}, max_properties: 8/8
Got MiioException while fetching the state: Unable to discover the device 192.168.1.121, mapping: {'thermostat.on': {'siid': 2, 'piid': 1}, 'thermostat.fan_level': {'siid': 2, 'piid': 2}, 'thermostat.mode': {'siid': 2, 'piid': 3}, 'thermostat.target_temperature': {'siid': 2, 'piid': 4}}, max_properties: 4/4
Got MiioException while fetching the state: No response from the device, mapping: {'thermostat.on': {'siid': 2, 'piid': 1}, 'thermostat.fan_level': {'siid': 2, 'piid': 2}, 'thermostat.mode': {'siid': 2, 'piid': 3}, 'thermostat.target_temperature': {'siid': 2, 'piid': 4}}, max_properties: 4/4
Got MiioException while fetching the state: Unable to discover the device 192.168.1.132, mapping: {'thermostat.on': {'siid': 2, 'piid': 1}, 'thermostat.fan_level': {'siid': 2, 'piid': 2}, 'thermostat.mode': {'siid': 2, 'piid': 3}, 'thermostat.target_temperature': {'siid': 2, 'piid': 4}}, max_properties: 4/4
Got MiioException while fetching the state: Unable to recover failed command, mapping: {'custom_program.mon_pro': {'siid': 3, 'piid': 1}, 'custom_program.tue_pro': {'siid': 3, 'piid': 2}, 'custom_program.wed_pro': {'siid': 3, 'piid': 3}, 'custom_program.thur_pro': {'siid': 3, 'piid': 4}, 'custom_program.fri_pro': {'siid': 3, 'piid': 5}, 'custom_program.sat_pro': {'siid': 3, 'piid': 6}, 'custom_program.sun_pro': {'siid': 3, 'piid': 7}, 'thermostat.temperature': {'siid': 2, 'piid': 5}}, max_properties: 8/8
