### ISSUE TITLE
更新v1.0.8后，插座无法自动更新状态

### ISSUE THREAD

**Issue by 114514thD** [al-one/hass-xiaomi-miot#2307]
### Device model / 设备型号

sensor.cuco_v3_db43

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2024.3.3

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

更新至1.0.8之后插座状态无法自动更新，包括switch.cuco_v3_db43_switch_status、sensor.cuco_v3_db43_electric_power、sensor.cuco_v3_db43_power_cost_today等，调用homeassistant.update_entity服务可以刷新

### Entity attributes / 实体属性

```yaml
info: 卫生间热水器
model: cuco.plug.v3
did: *****
mac: *****
lan_ip: 192.168.1.157
app_link: mihome://device?uid=*****&did=*****
miot_type: urn:miot-spec-v2:device:outlet:0000A002:cuco-v3:2
available: true
home_room: ***** 卫生间
icon: mdi:information
updater: cloud
updated_at: 2025-01-16 11:54:00.772302+08:00
electric_power-11-2: 0
switch.on: false
power_limit_ext.power_ext: 2500
charge_prt_ext.power: 2
charge_prt_ext.protect_time: 5
on_off_count: 0
on_off_count.temperature: 29
over_use_ele_alert.on: false
over_use_ele_alert.over_ele_day: 3
over_ele_month-10-3: 80
max_power_limit.on: false
max_power_limit.power: 2500
quick_countdown.on: false
quick_countdown.duration: 1
quick_countdown.left_time: 0
cycle.status: false
cycle.data_value: 30;30;7,1,2,3,4,5,6;0;1439;0
charging_protection.on: false
charging_protection.power: 2
protect_time-4-3: 5
indicator_light-3.mode: false
indicator_light-3.start_time: 1320
indicator_light-3.end_time: 600
indicator_light.on: false
power_consumption: 1
physical_controls_locked: false
switch.default_power_on_state: 0
switch.fault: 0
power_cost_today: 77
power_cost_month: 4496
converters: button.info, switch.switch.on, light.indicator_light.on, indicator_light-3.mode, switch.physical_controls_locked, sensor.electric_power-11-2, sensor.power_cost_today, sensor.power_cost_month
customizes: 
chunk_coordinators:
  - interval: 10
    props: switch.on,electric_power
parallel_updates: 3
sensor_attributes: power_cost_today,power_cost_month
stat_power_cost_key: '11.1'

device_class: update
friendly_name: 卫生间热水器 信息
```

### Home Assistant Logs / 系统日志

2025-01-16 10:49:41.248 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] sensor.cuco_v3_db43_electric_power: Entity state updated: 0
2025-01-16 10:49:41.250 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] switch.cuco_v3_db43_switch_status: Entity state updated: False
2025-01-16 10:49:41.256 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.cuco_v3_db43_info: Entity state updated: 卫生间热水器

2025-01-16 10:49:41.267 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.cuco.plug.v3] Update miot status: {'use_local': [False, False, None], 'use_cloud': [True, True, None], 'mapping': {'power_limit_ext.power_ext': {'siid': 15, 'piid': 1}, 'charge_prt_ext.power': {'siid': 14, 'piid': 1}, 'charge_prt_ext.protect_time': {'siid': 14, 'piid': 2}, 'on_off_count': {'siid': 12, 'piid': 1}, 'on_off_count.temperature': {'siid': 12, 'piid': 2}, 'over_use_ele_alert.on': {'siid': 10, 'piid': 1}, 'over_use_ele_alert.over_ele_day': {'siid': 10, 'piid': 2}, 'over_ele_month-10-3': {'siid': 10, 'piid': 3}, 'max_power_limit.on': {'siid': 9, 'piid': 1}, 'max_power_limit.power': {'siid': 9, 'piid': 2}, 'quick_countdown.on': {'siid': 8, 'piid': 1}, 'quick_countdown.duration': {'siid': 8, 'piid': 2}, 'quick_countdown.left_time': {'siid': 8, 'piid': 3}, 'cycle.status': {'siid': 5, 'piid': 1}, 'cycle.data_value': {'siid': 5, 'piid': 2}, 'charging_protection.on': {'siid': 4, 'piid': 1}, 'charging_protection.power': {'siid': 4, 'piid': 2}, 'protect_time-4-3': {'siid': 4, 'piid': 3}, 'indicator_light-3.mode': {'siid': 3, 'piid': 2}, 'indicator_light-3.start_time': {'siid': 3, 'piid': 3}, 'indicator_light-3.end_time': {'siid': 3, 'piid': 4}, 'indicator_light.on': {'siid': 13, 'piid': 1}, 'power_consumption': {'siid': 11, 'piid': 1}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'switch.default_power_on_state': {'siid': 2, 'piid': 2}, 'switch.fault': {'siid': 2, 'piid': 3}}}
