### ISSUE TITLE
topwit.bhf_light.rz01 温度不可用

### ISSUE THREAD

**Issue by earlzz** [al-one/hass-xiaomi-miot#2311]
### Device model / 设备型号

topwit.bhf_light.rz01

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

topwit.bhf_light.rz01 温度不可用

### Entity attributes / 实体属性

```yaml
sensor.topwit_rz01_xxx_temperature
次卫浴霸开关 温度
unavailable	state_class: measurement
unit_of_measurement: °C
device_class: temperature
friendly_name: 浴霸开关 温度
```
