### ISSUE TITLE
Light Ceiling not reporting status

### ISSUE THREAD

**Issue by romanr** [al-one/hass-xiaomi-miot#2313]
### Device model / 设备型号

[yeelink.light.ceiling22](https://home.miot-spec.com/s/yeelink.light.ceiling22)

### Component version / 插件版本

Firmware: 2.1.7_0041@esp32

### HA core version / HA版本

latest

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

I have it added successfully, but the status is always reported as "on". This was working fine with old package "Xiaomi for yeelink".

Same problem when installed as Auto, Local, Cloud.

Also when it's configured it adds " Light Switch Status" to the name, must be an error.

### Entity attributes / 实体属性

```yaml
min_color_temp_kelvin: 2600
max_color_temp_kelvin: 6100
min_mireds: 163
max_mireds: 384
effect_list: Day, Night
supported_color_modes: color_temp
effect: Day
color_mode: color_temp
brightness: 28.05
color_temp_kelvin: 2702
color_temp: 370
hs_color: 28.391, 65.659
rgb_color: 255, 167, 88
xy_color: 0.524, 0.388
light.on: false
light.color_temperature: 2702
light.mode: 1
light.brightness: 11
friendly_name: Ceiling light Light Switch Status
supported_features: 4


config

brightness_for_on: '5'
main_miot_services: light-2
miot_local: true
number_properties: off_delay_time
switch_properties: bg_on
button_actions: toggle
chunk_coordinators:
- interval: 10
 props: on,brightness,color_temperature,color,mode
```

### Home Assistant Logs / 系统日志

the only error in logs:

```
[{"at":"dev","dev_con_state":false,"error":-2,"methodDesc":"","note":"device offline","t":0,"target":"4xxx24","targetDesc":"Ceiling light","targetModel":"yeelink.light.ceiling22"}],"name":"Ceiling light-Schedule","time":1736975223,"userSceneId":2xxxx00},{"from":"timeout","identify":"prop.2.1.true.false","msg":[{"at":"dev","dev_con_state":false,"error":0,"methodDesc":"","note":"ok","t":0,"target":"4xxx24","targetDesc":"Office Ceiling light","targetModel":"yeelink.light.ceiling22"}]
```

logs;
```
[36m2025-01-19 02:17:31.611 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.ceiling22] Update miot status: {'use_local': [True, True, <MiotDevice: x.x.x (token: xxx)>], 'use_cloud': [False, False, False], 'mapping': {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}}}[0m
[32m2025-01-19 02:17:31.637 INFO (SyncWorker_4) [custom_components.xiaomi_miot.core.miio2miot] yeelink.light.ceiling22: Got miio props for miot: {'power': 'off', 'bright': '11', 'ct': '2702', 'delayoff': '0', 'active_mode': '0', 'smart_switch': '0', 'nl_br': '0'}[0m
[32m2025-01-19 02:17:31.640 INFO (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.ceiling22] Device updated: {'number.light.off_delay_time': 0, 'only_info': False}[0m
[36m2025-01-19 02:17:31.641 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] number.yeelink_ceiling22_de96_off_delay_time_2: Entity state updated: 0[0m
[36m2025-01-19 02:17:31.642 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.yeelink_ceiling22_de96_info_2: Entity state updated: Ceiling [0m
[36m2025-01-19 02:17:31.642 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.ceiling22] Finished fetching x.x.x:96-miot_status data in 0.043 seconds (success: True)[0m
[36m2025-01-19 02:17:31.642 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Ceiling (yeelink.light.ceiling22): Coordinator updated: ['x.x.x:96-miot_status', <custom_components.xiaomi_miot.core.miot_spec.MiotResults object at 0xfffxxx>][0m
[32m2025-01-19 02:17:31.685 INFO (SyncWorker_7) [custom_components.xiaomi_miot.core.miio2miot] yeelink.light.ceiling22: Got miio props for miot: {'power': 'off', 'bright': '11', 'ct': '2702', 'delayoff': '0', 'active_mode': '0', 'smart_switch': '0', 'nl_br': '0'}[0m
[32m2025-01-19 02:17:31.703 INFO (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.ceiling22] Device updated: {'light.light.on': False, 'light.brightness': 28.05, 'light.color_temperature': 2702, 'light.mode': 'Day', 'only_info': False}[0m
[36m2025-01-19 02:17:31.704 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] light.yeelink_ceiling22_de96_switch_status: Entity state updated: False[0m
[36m2025-01-19 02:17:31.705 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.yeelink_ceiling22_de96_info_2: Entity state updated: Ceiling [0m
[36m2025-01-19 02:17:31.705 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.ceiling22] Finished fetching x.x.x:96-chunk_1 data in 0.094 seconds (success: True)[0m
[36m2025-01-19 02:17:31.706 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Ceiling (yeelink.light.ceiling22): Coordinator updated: ['x.x.x:96-chunk_1', <custom_components.xiaomi_miot.core.miot_spec.MiotResults object at 0xfffxxx>][0m

```

**Comment by al-one** [comment]
I have the same model of lighting, and it works normally.

**Comment by romanr** [comment]
It doesn't work in HA, while it works fine in Xiaomi Home app. 
Removed and added again many times. 

I [created the PR](https://github.com/al-one/hass-xiaomi-miot/pull/2331) because it seemed to work using  wrong access methods with Ceiling lights. 

And you can see other users report similar problems with ceilign lights in #2283, #2561

**Comment by al-one** [comment]
Try config:
```yaml
xiaomi_miot:
  device_customizes:
    yeelink.light.ceiling22:
      chunk_properties: 1
```
