### ISSUE TITLE
Missing Light bulb

### ISSUE THREAD

**Issue by mfjooste** [al-one/hass-xiaomi-miot#2318]
### Device model / 设备型号

yeelink.light.mono6

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Missing full functionality for the yeelink.light.mono6 bulb, such as colour temperature and brightness controls.

### Entity attributes / 实体属性

```yaml
supported_color_modes: brightness
friendly_name: Light: MB 1 Switch Status
supported_features: 0
color_mode: null
brightness: null
light.on: false
light.brightness: 50
```
