### ISSUE TITLE
Notification offline in HA and log even ignore_offline is tru

### ISSUE THREAD

**Issue by antoweb** [al-one/hass-xiaomi-miot#2319]
### Device model / 设备型号

careli.fryer.maf02

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

A device configured with custom ignore_offline = true continue to notificate to HA that is offline and in log
2025-01-21 11:24:59.309 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.careli.fryer.maf02] Got MiioException while fetching the state: Unable to discover the device 192.168.1.246, mapping: {'air_fryer.status': {'siid': 2, 'piid': 1}, 'air_fryer.target_time': {'siid': 2, 'piid': 3}, 'air_fryer.target_temperature': {'siid': 2, 'piid': 4}, 'air_fryer.left_time': {'siid': 2, 'piid': 5}}, max_properties: 4/4

### Entity attributes / 实体属性

```yaml
info: Xiaomi Miot
model: careli.fryer.maf02
did: 
mac: 58:B6:23:57:CC:EB
lan_ip: 192.168.1.246
app_link: 
miot_type: urn:miot-spec-v2:device:air-fryer:0000A0A4:careli-maf02:1
available: false
home_room: 
icon: mdi:information-off
updater: none
updated_at: 
converters: button.info, sensor.air_fryer.status, air_fryer.fault, sensor.air_fryer.fault, sensor.air_fryer.left_time, sensor.custom.appoint_time_left, number.air_fryer.target_time, number.air_fryer.target_temperature, number.custom.appoint_time, select.custom.food_quanty, select.custom.preheat_switch, select.custom.turn_pot, button.air_fryer.start_cook, button.air_fryer.cancel_cooking, button.air_fryer.pause
customizes: 
interval_seconds: 120
button_actions: air_fryer.start_cook,pause,cancel_cooking,resume_cook
sensor_properties: status,fault,left_time,appoint_time_left
switch_properties: auto_keep_warm,current_keep_warm,preheat,turn_pot_cfg,turn_pot_config
select_properties: mode,food_quanty,preheat_switch,turn_pot,texture,target_cooking_measure
number_properties: >-
  target_time,target_temperature,appoint_time,reservation_left_time,cooking_weight
exclude_miot_properties: recipe_id,recipe_name,recipe_sync
chunk_coordinators:
  - interval: 20
    props: status,target_time,target_temperature,left_time
  - interval: 35
    props: fault,mode,appoint_time,reservation_left_time
ignore_offline: true

miot_error: Unable to discover the device 192.168.1.246
device_class: update
friendly_name: Xiaomi Miot Info
```
