### ISSUE TITLE
Some devices cannot be connected in the LAN, please check their IP and make sure they are in the same subnet as the HA.

### ISSUE THREAD

**Issue by willydannyHU** [al-one/hass-xiaomi-miot#2323]
### Device model / 设备型号

lemesh.switch.sw0c01

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

間歇跳出警告

### Entity attributes / 实体属性

```yaml
icon: mdi:information
device_class: update
friendly_name: 邊門電鎖 Info
info: 邊門電鎖
model: lemesh.switch.sw0c01
did: "732232840"
mac: B8:50:D8:4D:FC:F9
lan_ip: 192.168.0.120
app_link: mihome://device?uid=1577212887&did=732232840
miot_type: urn:miot-spec-v2:device:switch:0000A003:lemesh-sw0c01:1
available: true
home_room: Hu218_1 車庫
updater: local
updated_at: "2025-01-22 21:45:41.276000+08:00"
switch.on: false
remote.remote_switch: 1
remote.remote_ltype: 0
remote.remote_htype: 0
remote.remote_a: 0
remote.remote_b: 0
remote.remote_c: 0
remote.remote_d: 0
remote.remote_e: 0
remote.remote_f: 0
remote.remote_g: 0
remote.remote_h: 0
function.jog: 1
function.delaytime: 1
function.inteligent_switch: 0
function.lock_state: 1347420160
function.icon_style: 0
switch.default_power_on_state: 2
converters:
  - button.info
  - switch.switch.on
customizes:
  chunk_coordinators:
    - interval: 10
      props: "on"
```

### Home Assistant Logs / 系统日志

記錄詳細資料（錯誤）
自行安裝整合產生錯誤。
記錄器: custom_components.xiaomi_miot.core.device.lemesh.switch.sw0c01
來源: custom_components/xiaomi_miot/core/device.py:868
整合: Xiaomi Miot Auto ([相關文件](https://github.com/al-one/hass-xiaomi-miot), [問題](https://github.com/al-one/hass-xiaomi-miot/issues))
首次發生: 2025年1月21日 下午11:57:02 (1318 事件)
最後紀錄: 下午9:36:50

Got MiioException while fetching the state: Unable to discover the device 192.168.0.120, mapping: {'switch.on': {'siid': 2, 'piid': 1}}, max_properties: 1/1
Got MiioException while fetching the state: Unable to discover the device 192.168.0.120, mapping: {'remote.remote_switch': {'siid': 8, 'piid': 1}, 'remote.remote_ltype': {'siid': 8, 'piid': 4}, 'remote.remote_htype': {'siid': 8, 'piid': 5}, 'remote.remote_a': {'siid': 8, 'piid': 6}, 'remote.remote_b': {'siid': 8, 'piid': 7}, 'remote.remote_c': {'siid': 8, 'piid': 8}, 'remote.remote_d': {'siid': 8, 'piid': 9}, 'remote.remote_e': {'siid': 8, 'piid': 10}, 'remote.remote_f': {'siid': 8, 'piid': 11}, 'remote.remote_g': {'siid': 8, 'piid': 12}, 'remote.remote_h': {'siid': 8, 'piid': 13}, 'function.jog': {'siid': 3, 'piid': 3}, 'function.delaytime': {'siid': 3, 'piid': 4}, 'function.inteligent_switch': {'siid': 3, 'piid': 5}, 'function.lock_state': {'siid': 3, 'piid': 6}, 'function.icon_style': {'siid': 3, 'piid': 7}, 'switch.default_power_on_state': {'siid': 2, 'piid': 2}}, max_properties: 9/17
