### ISSUE TITLE
Some devices cannot be connected in the LAN, please check their IP and make sure they are in the same subnet as the HA.

### ISSUE THREAD

**Issue by willydannyHU** [al-one/hass-xiaomi-miot#2324]
### Device model / 设备型号

xiaomi.fan.p45

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

間歇跳出警告

### Entity attributes / 实体属性

```yaml
info: 客廳小米塔扇2
model: xiaomi.fan.p45
did: "820081087"
mac: C4:93:BB:92:D3:C4
lan_ip: 192.168.0.118
app_link: mihome://device?uid=1577212887&did=820081087
miot_type: urn:miot-spec-v2:device:fan:0000A005:xiaomi-p45:1:0000D062
available: false
home_room: 客廳
icon: mdi:information-off
updater: none
updated_at: "2025-01-22 12:50:38.139885+08:00"
indicator_light.on: true
fan.on: false
fan.mode: 1
fan.fan_level: 4
fan-2.stepless_fan_level: 35
dm_service.natural_list: a_b_c_d_e_f_g_h
dm_service.natural_e: 81ea5b9a4e490031000000000000000000000000_360_360_360_360_360_16
dm_service.natural_f: 81ea5b9a4e490032000000000000000000000000_360_360_360_360_360_16
dm_service.natural_g: 81ea5b9a4e490033000000000000000000000000_360_360_360_360_360_16
dm_service.natural_h: 81ea5b9a4e490034000000000000000000000000_360_360_360_360_360_16
delay: false
delay.delay_time: 0
delay.delay_remain_time: 0
physical_controls_locked: false
alarm: true
fan.fault: 0
fan.horizontal_swing: false
horizontal_swing_included_angle-2-7: 150
converters:
  - button.info
  - light.indicator_light.on
  - fan.fan.on
  - fan.on
  - fan.fan_level
  - fan.horizontal_swing
  - fan.mode
  - switch.alarm
  - switch.physical_controls_locked
  - button.fan.turn_left
  - button.fan.turn_right
customizes:
  button_actions: turn_left,turn_right
  number_properties: off_delay_time
  switch_properties: fan_init_power_opt
  chunk_coordinators:
    - interval: 10
      props: on,mode,fan_level
device_class: update
friendly_name: 客廳小米塔扇2 Info
miot_error: Unable to discover the device 192.168.0.118
```

### Home Assistant Logs / 系统日志

記錄詳細資料（錯誤）
自行安裝整合產生錯誤。
記錄器: custom_components.xiaomi_miot.core.device.xiaomi.fan.p45
來源: custom_components/xiaomi_miot/core/device.py:868
整合: Xiaomi Miot Auto ([相關文件](https://github.com/al-one/hass-xiaomi-miot), [問題](https://github.com/al-one/hass-xiaomi-miot/issues))
首次發生: 下午12:50:57 (2652 事件)
最後紀錄: 下午9:49:25

Got MiioException while fetching the state: Unable to discover the device 192.168.0.118, mapping: {'indicator_light.on': {'siid': 5, 'piid': 1}, 'fan.on': {'siid': 2, 'piid': 1}, 'fan.mode': {'siid': 2, 'piid': 3}, 'fan.fan_level': {'siid': 2, 'piid': 4}, 'fan-2.stepless_fan_level': {'siid': 2, 'piid': 5}}, max_properties: 5/5
Got MiioException while fetching the state: Unable to discover the device 192.168.0.118, mapping: {'dm_service.natural_list': {'siid': 13, 'piid': 3}, 'dm_service.natural_e': {'siid': 13, 'piid': 4}, 'dm_service.natural_f': {'siid': 13, 'piid': 5}, 'dm_service.natural_g': {'siid': 13, 'piid': 6}, 'dm_service.natural_h': {'siid': 13, 'piid': 7}, 'delay': {'siid': 12, 'piid': 1}, 'delay.delay_time': {'siid': 12, 'piid': 2}, 'delay.delay_remain_time': {'siid': 12, 'piid': 3}, 'physical_controls_locked': {'siid': 11, 'piid': 1}, 'alarm': {'siid': 7, 'piid': 1}, 'fan.fault': {'siid': 2, 'piid': 2}, 'fan.horizontal_swing': {'siid': 2, 'piid': 6}, 'horizontal_swing_included_angle-2-7': {'siid': 2, 'piid': 7}}, max_properties: 7/13
