### ISSUE TITLE
Got MiioException while fetching the state: Unable to discover...

### ISSUE THREAD

**Issue by gio-dzilla** [al-one/hass-xiaomi-miot#2325]
### Device model / 设备型号

mmgg.feeder.fi1

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Logger: custom_components.xiaomi_miot.core.device.mmgg.feeder.fi1
Source: custom_components/xiaomi_miot/core/device.py:868
integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 07:45:29 (13 occurrences)
Last logged: 07:54:29

Got MiioException while fetching the state: Unable to discover the device 192.xx.xx.xx, mapping: {'clearnserve.cleantime': {'siid': 8, 'piid': 1}, 'keyserve.key_stat': {'siid': 6, 'piid': 1}, 'feedplanserve.feedplan_contr': {'siid': 5, 'piid': 5}, 'feedserve.outfood_num': {'siid': 4, 'piid': 4}, 'feedserve.outletstatus': {'siid': 4, 'piid': 8}, 'feedserve.doorstatus': {'siid': 4, 'piid': 9}, 'desiccant.desiccant_left_time': {'siid': 11, 'piid': 2}, 'indicator_light.on': {'siid': 3, 'piid': 1}, 'pet_feeder.fault': {'siid': 2, 'piid': 1}, 'pet_feeder.pet_food_left_level': {'siid': 2, 'piid': 6}}, max_properties: 1/10

### Entity attributes / 实体属性

```yaml
model: mmgg.feeder.fi1
did: 413813025
app_link: mihome://device?
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-fi1:1
available: true
icon: mdi:information
updater: local
updated_at: 2025-01-24 13:13:14.132056+01:00
clearnserve.cleantime: 3
keyserve.key_stat: 1
feedplanserve.feedplan_contr: 0
feedserve.outfood_num: 5
feedserve.outletstatus: 0
feedserve.doorstatus: 0
desiccant.desiccant_left_time: 0
indicator_light.on: 0
pet_feeder.fault: 0
pet_feeder.pet_food_left_level: 0
converters: button.info, light.indicator_light.on, sensor.pet_feeder.fault, sensor.pet_feeder.pet_food_left_level, sensor.desiccant.desiccant_left_time, sensor.feedserve.outfood_num, sensor.clearnserve.cleantime, binary_sensor.feedserve.outletstatus, binary_sensor.feedserve.doorstatus, number.indicator_light.on, number.keyserve.key_stat, button.pet_feeder.pet_food_out, button.desiccant.reset_desiccant_life, button.clearnserve.resetclean
customizes: 
chunk_properties: '1'
button_actions: pet_food_out,resetclean,reset_desiccant_life
binary_sensor_properties: outletstatus,doorstatus
sensor_properties: fault,pet_food_left_level,outfood_num,cleantime,desiccant_left_time
number_properties: key_stat,indicator_light.on
exclude_miot_properties: >-
  outfood_id,contrycode,feddplan_string,factory_result,phon_time_zonefeedplan_hour,feedplan_min,feedplan_unit,feedplan_stat,feedplan_id,getfeedplan_num
auto_cloud: true
miot_local: true

device_class: update
```

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.core.device.mmgg.feeder.fi1
Source: custom_components/xiaomi_miot/core/device.py:868
integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 07:45:29 (13 occurrences)
Last logged: 07:54:29

Got MiioException while fetching the state: Unable to discover the device 192.xx.xx.xx, mapping: {'clearnserve.cleantime': {'siid': 8, 'piid': 1}, 'keyserve.key_stat': {'siid': 6, 'piid': 1}, 'feedplanserve.feedplan_contr': {'siid': 5, 'piid': 5}, 'feedserve.outfood_num': {'siid': 4, 'piid': 4}, 'feedserve.outletstatus': {'siid': 4, 'piid': 8}, 'feedserve.doorstatus': {'siid': 4, 'piid': 9}, 'desiccant.desiccant_left_time': {'siid': 11, 'piid': 2}, 'indicator_light.on': {'siid': 3, 'piid': 1}, 'pet_feeder.fault': {'siid': 2, 'piid': 1}, 'pet_feeder.pet_food_left_level': {'siid': 2, 'piid': 6}}, max_properties: 1/10
