### ISSUE TITLE
米家智能晾衣机pro (hyd.airer.pro2) current-position参数问题

### ISSUE THREAD

**Issue by AstroQore** [al-one/hass-xiaomi-miot#2327]
### Device model / 设备型号

[hyd.airer.pro2](https://home.miot-spec.com/s/hyd.airer.pro2)

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

相关issue：https://github.com/al-one/hass-xiaomi-miot/issues/1452
https://github.com/XiaoMi/ha_xiaomi_home/issues/549

> 这个设备实现有问题，siid=4、piid=11为current-position且可读、可通知，但是设备发生升降时，不上报properties_changed消息，上报的是event_occured消息，因此current-position属性显示一直不变。

 _Originally posted by @SusanPhevos in [#549](https://github.com/XiaoMi/ha_xiaomi_home/issues/549#issuecomment-2606224717)_

不知道这个问题有没有办法解决，current-position正确上报，但是设备properties_changed不上报，导致没法正确读取该值。

### Entity attributes / 实体属性

```yaml
info: 阳台 晾衣机
model: hyd.airer.pro2
did: *******
mac: *******
lan_ip: 192.168.***.***
app_link: mihome://device?uid=1094657882&did=******
miot_type: urn:miot-spec-v2:device:airer:0000A00D:hyd-pro2:1
available: true
home_room: ******
icon: mdi:information
updater: local
updated_at: 2025-01-24 22:45:50.377825+08:00
set_night_light.start_time_hour: 23
set_night_light.start_time_min: 0
set_night_light.end_time_hour: 6
set_night_light.end_time_min: 0
nightlight_switch-4-5: 0
set_night_light.brightness: 20
set_night_light.upper_limit: 0
set_night_light.lower_limit: 100
set_night_light.set_position: 0
set_night_light-4.brightness: 0
current_position-4-11: 0
set_night_light.motor_speed: 0
light.on: false
light.brightness: 100
airer.fault: 0
airer.status: 0
airer.mode: 0
converters: button.info, light.light.on, light.brightness, select.airer.mode
customizes: 
position_reverse: false
sensor_properties: left_time
switch_properties: uv
select_properties: mode,dryer
number_properties: drying_time
exclude_miot_properties: motor_control
disable_target_position: true
cover_position_mapping:
  '0': 50
  '1': 100
  '2': 0

state_updater: local
miot_error: Unable to discover the device 192.168.***.***
device_class: update
friendly_name: 阳台 晾衣机 Info
```
