### ISSUE TITLE
Cant fully control the zhimi.humidifier.cb1

### ISSUE THREAD

**Issue by almirus** [al-one/hass-xiaomi-miot#2332]
### Device model / 设备型号

zhimi.humidifier.cb1

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

![Image](https://github.com/user-attachments/assets/23f73c52-5da3-4188-8c40-95c48eb24c4b)
I can't set the desired humidity, and the temperature isn't displayed in the humidifier widget.

![Image](https://github.com/user-attachments/assets/09973e43-ad85-488a-9146-31cd2044fd5d)

### Entity attributes / 实体属性

```yaml
min_humidity: 0
max_humidity: 100
available_modes: Off, Auto, Level1, Level2, Level3
current_humidity: 52
mode: Auto
humidifier.on: true
humidifier.fan_level: 0
environment.relative_humidity: 52
environment.temperature: 22.8
physical_controls_locked: false
alarm: false
humidifier.water_level: 120
state_updater: local
device_class: humidifier
friendly_name: Увлажнитель спальня (локально) Humidifier
supported_features: 1
```
