### ISSUE TITLE
philips.light.downlight still shows online on HA when it is actually offline

### ISSUE THREAD

**Issue by uswong** [al-one/hass-xiaomi-miot#2333]
### Device model / 设备型号

philips.light.downlight

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.4

### Integrated mode / 集成方式

Token

### The problem / 问题详情

My philips.light.downlight has recently stays as online even if the light switch to it is turned off, ie no power supply to the light.  I think it happened after I updated Xiomi Miot Auto recently.  It worked well a couple of versions earlier.  Can you please have a look at it?

The following Entity attributes is collected when the power to the light is turned off, but the status of the light on HA shows it is online.

Thanks and best regards,
Ung Sing

### Entity attributes / 实体属性

```yaml
icon: mdi:information-off
device_class: update
friendly_name: Toilet Downlight Info
info: Toilet Downlight
model: philips.light.downlight
did: ""
mac: 7C:49:EB:4B:B9:3E
lan_ip: 192.168.1.128
app_link: ""
miot_type: urn:miot-spec-v2:device:light:0000A001:philips-downlight:1
available: false
home_room: ""
updater: none
updated_at: ""
converters:
  - button.info
  - light.light.on
  - light.brightness
  - light.color_temperature
  - light.mode
  - button.light.toggle
customizes:
  number_properties: off_delay_time,light_on_gradient_time,light_off_gradient_time
  switch_properties: flex_switch,night_light_switch
  button_actions: toggle
  chunk_coordinators:
    - interval: 10
      props: on,brightness,color_temperature,color,mode
miot_error: Unable to discover the device 192.168.1.128
```

### Home Assistant Logs / 系统日志

Home Assistant Core

![Image](https://github.com/user-attachments/assets/3ec98143-ecc0-4580-8bd9-deeb5c2ad8d8)
