### ISSUE TITLE
米家水暖毯不可用

### ISSUE THREAD

**Issue by JirachiZhang** [al-one/hass-xiaomi-miot#2335]
### Device model / 设备型号

qushui.blanket.mj1

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

水暖毯不可用，无法控制开关，状态不同步

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 米家智能温控水暖毯 信息
info: 米家智能温控水暖毯
model: qushui.blanket.mj1
did: 462178780
mac: B4:60:ED:BF:4A:F2
lan_ip: 192.168.123.151
app_link: mihome://device?uid=1415442559&did=462178780
miot_type: urn:miot-spec-v2:device:electric-blanket:0000A069:qushui-mj1:2
available: true
home_room: 北京 卧室
updater: local
updated_at: 2025-01-27 20:50:25.902728+08:00
update.anti_scald_switch: false
custom.timer: 0
custom.a_target_temperature: 3632
custom.antifreezing_switch: false
custom.a_temperature: 38
custom.b_temperature: 31
custom.a_sleep_setting: 01/23590800/127/00/37363535
custom.b_sleep_setting: 00/23590900/127/00/37363535
custom.ab_sleep_setting: 00/23000700/031/00/38363537
indicator_light.on: false
alarm: false
physical_controls_locked: false
electric_blanket.on: true
electric_blanket.fault: 0
electric_blanket.mode: 0
electric_blanket.water_level: 1
target_temperature-2-5: 25
converters: button.info, switch.electric_blanket.on, light.indicator_light.on, switch.alarm, switch.physical_controls_locked, sensor.electric_blanket.fault, sensor.electric_blanket.water_level, sensor.custom.a_temperature, sensor.custom.b_temperature, switch.custom.antifreezing_switch, switch.custom.ab_sleep_switch, switch.update.anti_scald_switch, number.target_temperature-2-5, number.custom.timer, select.electric_blanket.mode
customizes: 
sensor_properties: fault,water_level,a_temperature,b_temperature
select_properties: mode
number_properties: target_temperature,timer
chunk_properties: 1
switch_properties: alarm,antifreezing_switch,ab_sleep_switch,anti_scald_switch
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.device.qushui.blanket.mj1
来源: helpers/update_coordinator.py:379
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 20:44:34 (27 次总计出现)
上次记录: 21:12:44

Unexpected error fetching b4:60:ed:bf:4a:f2-01JJKRB48Q21EAJN6CBNR4XVQS-miot_status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 635, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'low'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 638, in state
    numerical_value = float(value)
ValueError: could not convert string to float: 'low'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 513, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 904, in update_miot_status
    self.dispatch(self.decode(results))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 616, in dispatch
    handler(data, only_info=only_info)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/hass_entity.py", line 183, in on_device_update
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.qushui_mj1_4af2_water_level has device class 'None', state class 'None' unit '%' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'low' (<class 'str'>)
