### ISSUE TITLE
智能窗帘 開啟關閉都是未知 

### ISSUE THREAD

**Issue by wozas123** [al-one/hass-xiaomi-miot#2336]
### Device model / 设备型号

[babai.curtain.cmb5](https://home.miot-spec.com/s/babai.curtain.cmb5)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

core-2025.1.3

### Integrated mode / 集成方式

Automatic (自动模式)
局域网集成
本地
都嘗試過

### The problem / 问题详情
開啟關閉控制是正常
爬文更新過
更新master分支 也是沒用 都無法正常顯示

### Entity attributes / 实体属性

```yaml
實體:cover.babai_cmb5_04ee_motor_control
狀態:unknown

closed_position: 2
deviated_position: 2
device_class: curtain
friendly_name: 書房窗簾 电机控制
supported_features: 15
curtain.motor_control: null
curtain.target_position: null
```

### Home Assistant Logs / 系统日志

Na

![Image](https://github.com/user-attachments/assets/7b3afdf0-9641-467c-aa37-27e943cca186)
![Image](https://github.com/user-attachments/assets/baefd524-d2e5-451f-8610-f0982701b59b)
