### ISSUE TITLE
Repeated device status information

### ISSUE THREAD

**Issue by roiksv** [al-one/hass-xiaomi-miot#2342]
### Device model / 设备型号

yeelight monoa(b)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.x

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Yeelight monoa(b): the integration sends a repeated device status after 5-10 seconds, which makes it impossible to use context. Integrated mode token

### Entity attributes / 实体属性

```yaml
supported_color_modes:
  - brightness
color_mode: brightness
brightness: 255
light.brightness: 100
light.on: true
friendly_name: Monoa_3 light Switch Status
supported_features: 0
```

### Home Assistant Logs / 系统日志

![Image](https://github.com/user-attachments/assets/552710db-9ab5-480a-b25f-64afbac92d3e)
