### ISSUE TITLE
插件从老版升级到新版，很多功能控制的实体都没了什么情况

### ISSUE THREAD

**Issue by 389377616** [al-one/hass-xiaomi-miot#2343]
### Device model / 设备型号

[xiaomi.airc.r24r00](https://home.miot-spec.com/s/xiaomi.airc.r24r00)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

原本插件版本是0.7.19，图片里的圈的哪些功能都可以控制，结果升级到了最新版1.0.8以后那些功能都没了

![Image](https://github.com/user-attachments/assets/953a2699-428d-4a3c-81c8-725055c8403b)

### Entity attributes / 实体属性

```yaml
info: 巨省电Pro
model: xiaomi.airc.r24r00
did: 834040629
mac: E8:4A:54:28:EC:9A
lan_ip: 192.168.1.105
app_link: mihome://device?uid=125847622&did=834040629
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:xiaomi-r24r00:3
available: true
home_room: 新江南 卧室
icon: mdi:information
updater: local
updated_at: 2025-02-02 21:26:57.724164+08:00
like_mode.user_defined_mode: 
like_mode.recommend_mode: 
like_mode.always_favorite_on: false
single_smart_scene.auto_cooling: false,28.0,26.0
automatic_heating-16-2: false,24.0,26.0
single_smart_scene.auto_dry: false,70,55
run_dark_sleep-16-10: false
flag_bit.fault_value: 4
machine_state.indoor_pipe_temp: 50.7
machine_state.indoor_fan_speed: 1070
real_heater_switch-12-4: 0
realindoor_fan_lever-12-5: 6
lightactivated_level-12-6: 0
machine_state.outdoor_temp: 5
machine_state.outdoor_pipe_temp: 0
outdoor_exhaust_temp-12-9: 88.2
machine_state.outdoor_fan_lever: 4
compressor_frequency-12-11: 85
fourway_valve_switch-12-12: true
outdoor_mach_current-12-13: 6.6
outdoor_mach_voltage-12-14: 220
machine_state.expansion_valve: 164
longitude_latitude-12-16: 0
machine_state.version: 0013,V0021,V0011,V0047,0013,V0021,V0011,V0047
external_serial_no-12-23: 26380/KG24C49E0342
machine_state.bk_serial_no: 00000/00IDU0000000,KBE3S/410C48T03644
machine_state.module_temp: 33.7
enhance.fan_percent: 101
enhance.timer: 0
enhance.sleep_diy: false
enhance.secondpart_of_hswing: false
enhance.humidity_range: 40-70
enhance.room_size: 0
enhance.maxfan_select: false
enhance.like_diy.error: -2
enhance.room_select: false
maintenance.clean: 0,100,5,1
maintenance.examine: none
maintenance.running_duration: 527.9
electricity.time_count: 357
electricity.electricity_info: false
cooling_effect-25-1: 3
heating_effect-25-2: 3
relieve_air_deflector_condensation-25-3: false
cooling_outdoor_fan_noise_reduction-25-4: false
cooling_indoor_fan_noise_reduction-25-5: false
heating_outdoor_fan_noise_reduction-25-6: false
heating_indoor_fan_noise_reduction-25-7: false
improve_heat_tar_temp_stop-25-9: false
filter-22.filter_life_level: 101
filter.filter_life_level: 101
power_consumption: 339.71
indicator_light.on: false
indicator_light.brightness: 0
alarm: true
environment.temperature: 21
environment.relative_humidity: 28
fan_control.fan_level: 0
fan_control.vertical_swing: false
vertical_swing_included_angle-3-6: 7
air_conditioner.on: true
air_conditioner.mode: 5
air_conditioner.fault: 0
target_temperature-2-4: 23
air_conditioner.eco: false
air_conditioner.heater: false
air_conditioner.dryer: false
air_conditioner.sleep_mode: false
air_conditioner.target_humidity: 0
unstraight_blowing-2-15: false
air_conditioner.favorite_on: false
air_conditioner.favorite_type: 0
state_updater: local
converters: button.info, light.indicator_light.on, indicator_light.brightness, switch.alarm, sensor.filter.filter_life_level, sensor.filter-22.filter_life_level, sensor.environment.temperature, sensor.environment.relative_humidity, sensor.power_consumption
customizes: 
sensor_properties: power_consumption

device_class: update
friendly_name: 巨省电Pro 信息
```
