### ISSUE TITLE
Xiaomi Pet Feeder

### ISSUE THREAD

**Issue by victorhfoto** [al-one/hass-xiaomi-miot#2344]
### Device model / 设备型号

mmgg.feeder.fi1

### Component version / 插件版本

Firmware: 2.1.3 

### HA core version / HA版本

2025.1.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I'm trying to set feed plan but I haven't been able to get it, Could Someone help me? I can't see in HA feed plan I set in Xiaomi app, 

### Entity attributes / 实体属性

```yaml
.
```

**Comment by z-master42** [comment]
I have never used the feeding plan from the app. I rebuilt it using the custom integration scheduler from the HACS and a script in which I only execute one action.

The script is then executed by the scheduler at the desired time.

The action in the script is:

```
  - action: xiaomi_miot.call_action
    data:
      entity_id: button.name_of_your_pet_feeder_pet_food_out
      siid: 2
      aiid: 1
      params: Enter the amount of food here
```
