### ISSUE TITLE
没有小夜灯模式，app里有，希望添加小夜灯模式支持

### ISSUE THREAD

**Issue by voidjun** [al-one/hass-xiaomi-miot#2346]
### Device model / 设备型号

[aupu.bhf_light.a3spro](https://home.miot-spec.com/s/aupu.bhf_light.a3spro)

### Component version / 插件版本

1.0.8

### HA core version / HA版本

2025.1.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

没有小夜灯模式，app里有，希望添加小夜灯模式支持

### Entity attributes / 实体属性

```yaml
select.aupu_a3spro_fd1d_mode

options: 待机, 吹风, 干燥, 换气, AI恒温暖, 除臭除菌
ptc_bath_heater.mode: 0
friendly_name: 浴霸-主 模式
```
