### ISSUE TITLE
温控器控制面板提示不可用

### ISSUE THREAD

**Issue by komawh** [al-one/hass-xiaomi-miot#2356]
### Device model / 设备型号

[suittc.airrtc.wk168](https://home.miot-spec.com/s/suittc.airrtc.wk168)

### Component version / 插件版本

11.0.9

### HA core version / HA版本

2025.2.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

地暖温控器，之前是没有实时温度显示，控制面板是正常的，刚更新后温度显示有了，控制面板不可用。

### Entity attributes / 实体属性

```yaml
hvac_modes:
  - "off"
min_temp: 2
max_temp: 85
target_temp_step: 1
fan_modes: []
preset_modes:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
friendly_name: 悠房地暖 Thermostat
supported_features: 409
```
