### ISSUE TITLE
Xiaomi Vacuum Robot S10 (ijai.vacuum.v17) missing properties

### ISSUE THREAD

**Issue by banditoth** [al-one/hass-xiaomi-miot#2358]
### Device model / 设备型号

ijai.vacuum.v17

### Component version / 插件版本

1.0.9

### HA core version / HA版本

2025.1.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Couple of properties are missing from Home Assistant, but the most important (at least for me) is to get the **room-ids** from under the **map** entity. Look at: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:ijai-v17:1

### Entity attributes / 实体属性

```yaml
info: Xiaomi Robot Vacuum S10
model: ijai.vacuum.v17
did: "<HIDDEN>"
mac: <HIDDEN>
lan_ip: 192.168.8.245
app_link: mihome://device?uid=<HIDDEN>&did=<HIDDEN>
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:ijai-v17:2
available: true
home_room: medveotthon All devices
icon: mdi:information
updater: local
updated_at: "2025-02-11 21:21:40.698705+01:00"
sweep.cleaning_time: 56
sweep.cleaning_area: 52
vacuum.status: 4
vacuum.mode: 0
vacuum.sweep_type: 0
disturb.dnd_enable: 0
disturb.dnd_start_hour: 23
disturb.dnd_start_minute: 0
disturb.dnd_end_hour: 9
disturb.dnd_end_minute: 0
disturb.multi_prop_dnd: "[0,23,0,9,0]"
map.remember_state: 1
map.cur_map_id: <HIDDEN>
map.map_num: 1
sweep.repeat_state: 0
sweep.suction_state: 3
sweep.water_state: 0
sweep.mop_route: 0
sweep.side_brush_life: 97
sweep.side_brush_hours: 176
sweep.main_brush_life: 70
sweep.main_brush_hours: 252
sweep.hypa_life: 97
sweep.hypa_hours: 176
sweep.mop_life: 100
sweep.mop_hours: 180
sweep.time_zone: -3600
sweep.cur_lang: en_US
sweep.dirt_recognize: 0
sweep.pet_recognize: 0
sweep.ai_recognize: 0
sweep.carpet_booster: 0
sweep.multi_prop_vacuum: >-
  [0,3,0,3,0,0,-3600,56,52.9,1,"en_US","396922SD2311A20497;1659049648","en_US",6,-1,0,0,1,2,1]
sweep.tank_shake: 1
sweep.shake_shift: 2
sweep.map_encrypt: 1
alarm: false
alarm.volume: 0
battery_level: 100
vacuum.fault: 2105
vacuum.on: "[1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1]"
state_updater: local
vacuum.status_desc: Charging
converters:
  - button.info
  - switch.alarm
  - number.alarm.volume
  - sensor.battery_level
  - sensor.vacuum.status
  - sensor.sweep.side_brush_life
  - sensor.sweep.main_brush_life
  - sensor.sweep.hypa_life
  - sensor.sweep.mop_life
  - switch.vacuum.on
  - switch.sweep.repeat_state
  - select.vacuum.mode
  - select.vacuum.sweep_type
  - select.sweep.water_state
  - button.vacuum.start_sweep
  - button.vacuum.stop_sweeping
  - button.vacuum.start_only_sweep
  - button.vacuum.start_sweep_mop
  - button.vacuum.start_mop
  - button.battery.start_charge
customizes:
  binary_sensor_properties: mop_status
  sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
  select_properties: mode,sweep_type,water_state
  number_properties: volume
  button_actions: >-
    start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
  configuration_entities: reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
  chunk_coordinators:
    - interval: 10
      props: status,cleaning_area,cleaning_time,charging_state
      notify: true
    - interval: 15
      props: mode,sweep_mop_type,sweep_type,clean_times
  switch_properties: vacuum.on,repeat_state,alarm
  exclude_miot_services: order
  exclude_miot_properties: zone_points,restrict_points,target_point
device_class: update
friendly_name: Xiaomi Robot Vacuum S10 Info
```
