### ISSUE TITLE
viomi.aircondition.y116: Unable to parse message payload

### ISSUE THREAD

**Issue by menfis911** [al-one/hass-xiaomi-miot#2360]
### Device model / 设备型号

[viomi.aircondition.y116](https://home.miot-spec.com/s/viomi.aircondition.y116)

### Component version / 插件版本

1.0.9

### HA core version / HA版本

2025.2.2

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

After upgrading to the latest version of the integration, there is a constant error in the HA logs, every minute.

### Entity attributes / 实体属性

```yaml
model: viomi.aircondition.y116
did: 
mac: CC:B5:D1:96:E0:2A
lan_ip: 192.168.100.99
app_link: 
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:viomi-y116:1
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-02-12 13:25:50.766170+03:00
indicator_light.on: true
fan_control.fan_level: 0
air_conditioner.on: false
air_conditioner.mode: 5
target_temperature-2-4: 24
function.uv: false
function.auto_clean: false
function.autoclean_worktime: 0
environment.temperature: 10
fan_control.horizontal_swing: false
fan_control.vertical_swing: false
air_conditioner.fault: none
air_conditioner.eco: false
air_conditioner.sleep_mode: false
converters:
  - button.info
  - light.indicator_light.on
  - climate.air_conditioner.mode
  - air_conditioner.on
  - target_temperature-2-4
  - environment.temperature
  - air_conditioner.mode
  - fan_control.fan_level
  - fan_control.horizontal_swing
  - fan_control.vertical_swing
  - switch.air_conditioner.eco
  - switch.air_conditioner.sleep_mode
  - sensor.environment.temperature
  - switch.air_conditioner.on
  - switch.fan_control.horizontal_swing
  - switch.fan_control.vertical_swing
  - select.fan_control.fan_level
customizes: 
sensor_properties: electricity.electricity
switch_properties: air_conditioner.on,horizontal_swing,vertical_swing
select_properties: fan_level
number_properties: target_humidity
fan_services: air_fresh
chunk_coordinators:
  - interval: 10
    props: on,mode,target_temperature,fan_level
    notify: true

device_class: update
friendly_name: Kondei_banya Info
```

### Home Assistant Logs / 系统日志

Регистратор: custom_components.xiaomi_miot.core.device.viomi.aircondition.y116
Источник: custom_components/xiaomi_miot/core/device.py:895
интеграция: Xiaomi Miot Auto ([документация](https://github.com/al-one/hass-xiaomi-miot), [проблемы](https://github.com/al-one/hass-xiaomi-miot/issues))
Первое сообщение: 13:17:00 (1 сообщений)
Последнее сообщение: 13:17:00

Got MiioException while fetching the state: Unable to parse message payload, mapping: {'function.uv': {'siid': 8, 'piid': 8}, 'function.auto_clean': {'siid': 8, 'piid': 9}, 'function.autoclean_worktime': {'siid': 8, 'piid': 10}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'fan_control.horizontal_swing': {'siid': 3, 'piid': 3}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 4}, 'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'air_conditioner.eco': {'siid': 2, 'piid': 7}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 13}}, max_properties: 9/9

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by menfis911** [comment]
Unfortunately the problem persisted and showed up again.

> Регистратор: custom_components.xiaomi_miot.core.device.viomi.aircondition.y116
> Источник: custom_components/xiaomi_miot/core/device.py:895
> интеграция: Xiaomi Miot Auto ([документация](https://github.com/al-one/hass-xiaomi-miot), [проблемы](https://github.com/al-one/hass-xiaomi-miot/issues))
> Первое сообщение: 09:45:32 (**75 сообщений**)
> Последнее сообщение: 10:22:53
> 
> Got MiioException while fetching the state: Unable to parse message payload, mapping: {'function.uv': {'siid': 8, 'piid': 8}, 'function.auto_clean': {'siid': 8, 'piid': 9}, 'function.autoclean_worktime': {'siid': 8, 'piid': 10}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'fan_control.horizontal_swing': {'siid': 3, 'piid': 3}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 4}, 'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'air_conditioner.eco': {'siid': 2, 'piid': 7}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 13}}, max_properties: 9/9

**Comment by menfis911** [comment]
After upgrading to 1.0.11 another error started to appear, also lost the UV mode and stopped showing the room temperature 

Регистратор: custom_components.xiaomi_miot.core.device.viomi.aircondition.y116
Источник: custom_components/xiaomi_miot/core/device.py:895
интеграция: Xiaomi Miot Auto ([документация](https://github.com/al-one/hass-xiaomi-miot), [проблемы](https://github.com/al-one/hass-xiaomi-miot/issues))
Первое сообщение: 18:14:50 (5 сообщений)
Последнее сообщение: 18:19:18

Got MiioException while fetching the state: Unable to parse message payload, mapping: {'environment.temperature': {'siid': 4, 'piid': 7}, 'air_conditioner.fault': {'siid': 2, 'piid': 3}}, max_properties: 2/2

**Comment by al-one** [comment]
Try:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    viomi.aircondition.y116:
      chunk_properties: 1
```
