### ISSUE TITLE
Problem with device zhimi.airp.meb1 (XIAOMI Smart Air Purifier ELITE), can't connect

### ISSUE THREAD

**Issue by androme13** [al-one/hass-xiaomi-miot#2361]
### Device model / 设备型号

zhimi.airp.meb1

### Component version / 插件版本

1.0.9

### HA core version / HA版本

2025.2.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi, plugin can't connect to the device (zhimi.airp.meb1), device is well integrated, but seen as not available.
I tried automatic and local integration.
zhimi.airp.meb1 firmware version : 2.2.7
My other device  (roborock s1)  is well integrated and seen as available.
Thank you.

### Entity attributes / 实体属性

```yaml
info: Air Purifier
model: zhimi.airp.meb1
did: "825273496"
mac: 84:46:93:C5:10:BD
lan_ip: 10.4.0.103
app_link: mihome://device?uid=6176029678&did=825273496
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-meb1:1
available: false
home_room: salon
icon: mdi:information-off
updater: none
updated_at: ""
converters:
  - button.info
  - fan.air_purifier.on
  - air_purifier.on
  - air_purifier.fan_level
  - air_purifier.mode
  - switch.alarm
  - switch.physical_controls_locked
  - sensor.filter.filter_life_level
  - sensor.filter.filter_used_time
  - sensor.environment.temperature
  - sensor.environment.relative_humidity
  - sensor.environment.pm2_5_density
  - sensor.environment.pm10_density
  - sensor.environment.air_quality
  - switch.air_purifier.on
  - switch.air_purifier.uv
customizes:
  switch_properties: air_purifier.on,alarm.alarm,anion,uv
  sensor_properties: relative_humidity,pm2_5_density,temperature,filter_life_level
  chunk_coordinators:
    - interval: 10
      props: on,mode,fan_level
    - interval: 300
      props: filter_life_level,filter_left_time,filter_used_time
miot_error: Unable to discover the device 10.4.0.103
device_class: update
friendly_name: Air Purifier Info
```
