### ISSUE TITLE
Missing Controls & Sensors for Xiaomi Kettle v20 in Xiaomi Miot Auto

### ISSUE THREAD

**Issue by Lett3rs** [al-one/hass-xiaomi-miot#2369]
### Device model / 设备型号

[xiaomi.kettle.v20](https://home.miot-spec.com/s/xiaomi.kettle.v20)

### Component version / 插件版本

1.0.9

### HA core version / HA版本

2025.2.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I am using the Xiaomi Miot Auto integration in Home Assistant with my Xiaomi Kettle v20 (xiaomi.kettle.v20), but I am missing several controls and sensors that are available for other similar models like Xiaomi Kettle v19 (yunmi.kettle.v19).

The kettle is connected successfully, and I can see its basic state and temperature in Home Assistant, but key features like boiling reminder, keep warm settings, and advanced modes are missing.

What I Expected to Happen:
I expected to see and control all available attributes for my kettle, similar to how xiaomi.kettle.v19 is displayed in Xiaomi Miot Auto.

What Actually Happens:
The Xiaomi Kettle v20 entity (water_heater.xiaomi_v20_8d6a_kettle) appears in Home Assistant but only has limited controls.
The following features are missing in Home Assistant:
Boiling reminder (function.boiling_reminder)
Custom knob temperature (function.custom_knob_temp)
Keep warm reminder (function.keep_warm_reminder)
Lift temperature memory (function.lift_remember_temp)
Extended heating modes (function.heat_mode, function.target_mode)
These features are present for xiaomi.kettle.v19 but not for xiaomi.kettle.v2

![Image](https://github.com/user-attachments/assets/7a3cf7df-3505-4ed8-95a6-7994532a5f6a)
![Image](https://github.com/user-attachments/assets/0e968555-5f93-494d-a69e-c2f1149e74d2)

### Entity attributes / 实体属性

```yaml
min_temp: 40
max_temp: 99
current_temperature: 34
temperature: 90
target_temp_high: 99
target_temp_low: 40
local_timing.scene_sequence: 0,0,0,0,0
local_timing.scene_one: 0000,0000,0,0
local_timing.scene_two: 0000,0000,0,0
local_timing.scene_three: 0000,0000,0,0
local_timing.scene_four: 0000,0000,0,0
local_timing.scene_five: 0000,0000,0,0
knob_setting.knob_sequence: 1,2,3,4,0,0
knob_setting.knob_one: 泡奶,0,45,1440
knob_setting.knob_two: 蜂蜜,0,60,1440
knob_setting.knob_three: 煮茶,0,70,1440
knob_setting.knob_four: 咖啡,0,85,1440
knob_setting.knob_five: ",0,0,0"
knob_setting.knob_six: ",0,0,0"
function.keep_warm_time: 1440
function.custom_knob_temp: false
function.lift_remember_temp: true
function.boiling_reminder: false
function.keep_warm_reminder: false
function.kettle_lifting: false
function.extended_mode: 温水,45,1,45,1440_泡枸杞,70,1,70,1440_花茶,80,1,80,1440
function.warming_time: 0
function.target_mode: 0
function.heat_mode: 70,1,45,1440
function.boil_mode: 99,1,45,1440
no_disturb: false
kettle.status: 0
kettle.fault: 0
kettle.temperature: 34
kettle.target_temperature: 90
kettle.auto_keep_warm: false
kettle.keep_warm_temperature: 40
kettle.on: false
state_updater: local
friendly_name: Xiaomi Elkedel
supported_features: 1
icon: mdi:kettle
extra_attributes:
  current_temperature: "{{ states('sensor.kettle_current_temperature') }}"
  target_temperature: "{{ states('sensor.kettle_target_temperature') }}"
  keep_warm_temperature: "{{ states('sensor.kettle_keep_warm_temperature') }}"
  kettle_status: "{{ states('sensor.kettle_status') }}"
  heat_mode: "{{ states('sensor.kettle_mode') }}"
```
