### ISSUE TITLE
Don't understand how to customize my chunmi.pre_cooker.mini1

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [al-one/hass-xiaomi-miot#2373]
Hi,

I have just set up my chunmi.pre_cooker.mini1 with Miiot.
I only have the following controls:

![Image](https://github.com/user-attachments/assets/4bce5ddb-c7f7-47f1-8da6-2e3bf9601c53)

I have found this : https://home.miot-spec.com/spec/chunmi.pre_cooker.mini1
There is apparently a lot more controls available. But I don't understand how to add them.
I have read https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774, but I still don't understand how options from the specs should be set up in the customization fields. I tried to find examples, with no luck.

Could someone help me to add all the available controls to the device ?
Thanks in advance for your help

**Comment by LeVraiRoiDHyrule** [comment]
Thanks for your answer.

I have configured it as you said, and there is now more options. But it looks like there is still options from https://home.miot-spec.com/spec/chunmi.pre_cooker.mini1 that are not in the customization template. For example, `set-menu`, `cooking-start` and others. For example, I can't find what is the setting to configure pressure time, that I can configure from the Mi Home app. I don't know how to make that setting available to home assistant.

**Comment by al-one** [comment]
The  parameter  structure  of  these  actions  is  unknown.

**Comment by LeVraiRoiDHyrule** [comment]
But `taste` is present in https://home.miot-spec.com/spec/chunmi.pre_cooker.mini1, doesn't it mean that we know how it works ?

Do I have a chance to find the missing settings by trial and error ?

**Comment by al-one** [comment]
The `taste` property has a list of values.

```yaml
{
    "iid": 2,
    "type": "urn:chunmi-spec:property:taste:00000002:chunmi-mini1:1",
    "description": "taste",
    "format": "uint8",
    "access": [
        "read",
        "notify"
    ],
    "unit": "none",
    "value-list": [
        {
            "value": 0,
            "description": "嚼劲"
        },
        {
            "value": 1,
            "description": "适中"
        },
        {
            "value": 2,
            "description": "软糯"
        },
        {
            "value": 255,
            "description": "无口感菜谱"
        }
    ]
}
```
