### ISSUE TITLE
syi.airer.zjl 制造商：syil晾衣架只要升级1.0.9之后的版本电机就变成了不可用状态

### ISSUE THREAD

**Issue by hyteplus** [al-one/hass-xiaomi-miot#2379]
### Device model / 设备型号

syi.airer.zjl

### Component version / 插件版本

1.0.9

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

syi.airer.zjl
制造商：syi
Miot Auto 1.0.8(含)之前的版本一切正常，升级1.0.9及以上任一版本，电机控制显示不可用

![Image](https://github.com/user-attachments/assets/e3806126-a3b3-49aa-bd42-7f018da34892)

### Entity attributes / 实体属性

```yaml
info: ZhiJuLe electric drying rack
model: syi.airer.zjl
did: 427307781
mac: xx:xx:xx:xx:xx:xx
lan_ip: 192.168.1.66
app_link: mihome://device?uid=23278897&did=427307781
miot_type: urn:miot-spec-v2:device:airer:0000A00D:syi-zjl:1
available: true
home_room: XX生活阳台
icon: mdi:information
updater: cloud
updated_at: 2025-02-20 14:20:45.656539+08:00
airer.dryer: 0
time.position_bar: 1
light.on: false
airer.fault: 0
airer.uv: false
airer.on: true
converters: button.info, light.light.on, cover.airer.motor_control, airer.motor_control, switch.airer.uv, switch.airer.dryer
customizes: 
position_reverse: true
sensor_properties: left_time
switch_properties: dryer,uv
select_properties: drying_level
chunk_coordinators:
  - interval: 15
    props: status,current_position,target_position,dryer,drying_level

device_class: update
friendly_name: 晾衣架 信息
```
