### ISSUE TITLE
Mi Air Purifier 3C preset mode setting is missed

### ISSUE THREAD

**Issue by THE-KONDRAT** [al-one/hass-xiaomi-miot#2380]
### Device model / 设备型号

zhimi.airpurifier.mb4

### Component version / 插件版本

1.0.12

### HA core version / HA版本

2025.2.4

### Integrated mode / 集成方式

Token

### The problem / 问题详情

![Image](https://github.com/user-attachments/assets/fde98787-6c61-42c9-8dd0-0b1e3807213f)

I'm not able to switch preset mode.
When I change fan speed device stucks in favorite mode.

### Entity attributes / 实体属性

```yaml
preset_modes:
  - Auto
  - Sleep
  - Favorite
friendly_name: Mi Air Purifier 3C Air Purifier
supported_features: 56
preset_mode: Auto
air_purifier.on: true
air_purifier.mode: 0
```
