### ISSUE TITLE
zhimi.heater.mc2a AttributeError: NoneType object has no attribute full_name

### ISSUE THREAD

**Issue by menfis911** [al-one/hass-xiaomi-miot#2382]
### Device model / 设备型号

zhimi.heater.mc2a zhimi

### Component version / 插件版本

1.0.11

### HA core version / HA版本

2025.2.4

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Every 20 seconds there is an error in the log, it does not change if you add the device automatically or via token.

### Entity attributes / 实体属性

```yaml
info: Конвектор новый
model: zhimi.heater.mc2a
did: 
mac: DC:ED:83:EB:4A:37
lan_ip: 192.168.100.72
app_link: 
miot_type: urn:miot-spec-v2:device:heater:0000A01A:zhimi-mc2a:1
available: true
home_room: 
icon: mdi:information
updater: none
updated_at: 2025-02-20 12:57:03.743470+03:00
indicator_light.on: true
heater.on: false
heater.target_temperature: 21
private_service.hw_enable: false
private_service.use_time: 7369408
private_service.country_code: 44
alarm: 1
physical_controls_locked: false
environment.temperature: 4.7311
countdown.countdown_time: 0
heater.fault: 0
converters: button.info, light.indicator_light.on, climate.heater.target_temperature, heater.on, heater.target_temperature, environment.temperature, switch.alarm, switch.physical_controls_locked, sensor.environment.temperature, switch.heater.on, number.countdown.countdown_time
customizes: 
switch_properties: heater.on,horizontal_swing,alarm.alarm,delay.delay
number_properties: countdown_time,delay_time
chunk_coordinators:
  - interval: 10
    props: on,mode,target_temperature,fan_level

device_class: update
friendly_name: Конвектор новый Info
```

### Home Assistant Logs / 系统日志

Регистратор: custom_components.xiaomi_miot.core.device.zhimi.heater.mc2a
Источник: helpers/update_coordinator.py:380
интеграция: Xiaomi Miot Auto ([документация](https://github.com/al-one/hass-xiaomi-miot), [проблемы](https://github.com/al-one/hass-xiaomi-miot/issues))
Первое сообщение: 19 февраля 2025 г. в 19:59:49 (7127 сообщений)
Последнее сообщение: 12:59:29

Unexpected error fetching dc:ed:83:eb:4a:37-f98a3b6396bd75799f5f8d968c2b56eb-chunk_1 data
Unexpected error fetching dc:ed:83:eb:4a:37-f98a3b6396bd75799f5f8d968c2b56eb-miot_status data
Unexpected error fetching dc:ed:83:eb:4a:37-chunk_1 data
Unexpected error fetching dc:ed:83:eb:4a:37-miot_status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 530, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 931, in update_miot_status
    self.dispatch(self.decode(results))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 637, in dispatch
    handler(data, only_info=only_info)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/hass_entity.py", line 176, in on_device_update
    self.set_state(data)
    ~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/xiaomi_miot/climate.py", line 269, in set_state
    self.conv.attrs.add(self._conv_mode.full_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'full_name'
