### ISSUE TITLE
xiaomi_miot is setting state directly (class MiotVacuumEntity)

### ISSUE THREAD

**Issue by jonyrh** [al-one/hass-xiaomi-miot#2385]
### Device model / 设备型号

vacuum.ijai_v3_fb95_robot_cleaner

### Component version / 插件版本

1.0.12

### HA core version / HA版本

2025.2.4

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Hello!

Warnings afret reboot:

Detected that custom integration 'xiaomi_miot' is setting state directly. Entity xiaomi_miot.ijai_v3_fb95_robot_cleaner (<class 'custom_components.xiaomi_miot.vacuum.MiotVacuumEntity'>) should implement the 'activity' property and return its state using the VacuumActivity enum at custom_components/xiaomi_miot/vacuum.py, line 68: async_add_entities(entities, update_before_add=True). This will stop working in Home Assistant 2026.1, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

AND

/usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior Bool = partial(_str2bool)

### Entity attributes / 实体属性

```yaml
info: Mi Robot
model: ijai.vacuum.v3
did: ""
mac: ec:4d:3e:e2:fb:95
lan_ip: 192.168.0.19
app_link: ""
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:ijai-v3:2
available: true
home_room: ""
icon: mdi:information
updater: local
updated_at: "2025-02-21 16:51:20.196734+05:00"
sweep.cleaning_time: 19
sweep.cleaning_area: 14
vacuum.status: 4
vacuum.mode: 2
vacuum.sweep_type: 0
disturb.dnd_enable: 1
disturb.dnd_start_hour: 22
disturb.dnd_start_minute: 0
disturb.dnd_end_hour: 6
disturb.dnd_end_minute: 30
disturb.multi_prop_dnd: "[1,22,0,6,30]"
map.remember_state: 1
map.cur_map_id: 1722596557
map.map_num: 1
sweep.repeat_state: 0
sweep.suction_state: 0
sweep.water_state: 2
sweep.mop_route: 1
sweep.side_brush_life: 0
sweep.side_brush_hours: 0
sweep.main_brush_life: 43
sweep.main_brush_hours: 157
sweep.hypa_life: 0
sweep.hypa_hours: 0
sweep.mop_life: 0
sweep.mop_hours: 0
sweep.time_zone: -18000
sweep.cur_lang: ru_RU
sweep.multi_prop_vacuum: >-
  [0,3,1,0,2,1,-18000,19,14.6,0,"ru_RU","334702602212B08378","en_US",6,-1,0,0,1,2,1]
sweep.tank_shake: 1
sweep.shake_shift: 2
sweep.map_encrypt: 1
alarm: 1
alarm.volume: 0
battery_level: 100
vacuum.fault: 2105
vacuum.on: "[1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]"
state_updater: local
vacuum.status_desc: Заряжается
converters:
  - button.info
  - switch.alarm
  - number.alarm.volume
  - sensor.battery_level
  - sensor.vacuum.status
  - sensor.sweep.side_brush_life
  - sensor.sweep.main_brush_life
  - sensor.sweep.hypa_life
  - sensor.sweep.mop_life
  - switch.vacuum.on
  - switch.sweep.repeat_state
  - select.vacuum.mode
  - select.vacuum.sweep_type
  - select.sweep.water_state
  - button.vacuum.start_sweep
  - button.vacuum.stop_sweeping
  - button.vacuum.start_only_sweep
  - button.vacuum.start_sweep_mop
  - button.vacuum.start_mop
  - button.battery.start_charge
customizes:
  binary_sensor_properties: mop_status
  sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
  select_properties: mode,sweep_type,water_state
  number_properties: volume
  button_actions: >-
    start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
  configuration_entities: reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
  chunk_coordinators:
    - interval: 10
      props: status,cleaning_area,cleaning_time,charging_state
      notify: true
    - interval: 15
      props: mode,sweep_mop_type,sweep_type,clean_times
  switch_properties: vacuum.on,repeat_state,alarm
  exclude_miot_services: order
  exclude_miot_properties: zone_points,restrict_points,target_point
device_class: update
friendly_name: Mi Robot Info
```
