### ISSUE TITLE
Airdog X7SM the problem of work

### ISSUE THREAD

**Issue by GreshnikYa** [al-one/hass-xiaomi-miot#2387]
### Device model / 设备型号

airdog.airpurifier.x7sm

### Component version / 插件版本

1.0.12

### HA core version / HA版本

2025.2.5

### Integrated mode / 集成方式

Token

### The problem / 问题详情

1)The "fan" entity does not control the fan speed
2) The presets "Auto", "Sleep mode", "Favorites" also do not work, without changing the operation of the device in any way.

### Entity attributes / 实体属性

```yaml
info: Airdog
model: airdog.airpurifier.x7sm
did: ""
mac: 43:97:E7:21:C9:2B
lan_ip: 192.168.0.4
app_link: ""
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:airdog-x7sm:1
available: true
home_room: ""
icon: mdi:information
updater: local
updated_at: "2025-02-24 18:58:59.577238+03:00"
hcho: 1
air_purifier.on: true
air_purifier.fan_level: 1
air_purifier.mode: auto
physical_controls_locked: false
environment.pm2_5_density: 18
converters:
  - button.info
  - fan.air_purifier.on
  - air_purifier.on
  - air_purifier.fan_level
  - air_purifier.mode
  - switch.physical_controls_locked
  - sensor.environment.pm2_5_density
  - switch.air_purifier.on
customizes:
  switch_properties: air_purifier.on,alarm.alarm,anion,uv
  sensor_properties: relative_humidity,pm2_5_density,temperature,filter_life_level
  chunk_coordinators:
    - interval: 10
      props: on,mode,fan_level
    - interval: 300
      props: filter_life_level,filter_left_time,filter_used_time
device_class: update
friendly_name: Airdog Info
```

### Home Assistant Logs / 系统日志

Got MiioException while fetching the state: Unable to discover the device 192.168.0.4, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}}, max_properties: 3/3

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by GreshnikYa** [comment]
[[все-один](https://github.com/al-one)
добавлено 
[устройство: очиститель воздуха](https://github.com/al-one/hass-xiaomi-miot/issues?q=state%3Aopen%20label%3A%22device%3A%20air-purifier%22)
 
[miio2miot](https://github.com/al-one/hass-xiaomi-miot/issues?q=state%3Aopen%20label%3A%22miio2miot%22)
 [3 часа назад](https://github.com/al-one/hass-xiaomi-miot/issues/2387#event-16443460320)](url)

**Comment by GreshnikYa** [comment]
[https://github.com/al-one/hass-xiaomi-miot/issues?q=state%3Aopen%20label%3A%22device%3A%20air-purifier%22](url)

1)This partially started to solve one of the problems. The modes began to switch, but incorrectly. By selecting the preset "Faforite", the "Sleep" mode is enabled, and by selecting the preset "Sleep", the "Faforite" mode is enabled.

2)Another problem with fan speed control still exists. Nothing happens when the fan speed is changed.

**Comment by GreshnikYa** [comment]
> Try master branch.
> 
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -

1)This partially started to solve one of the problems. The modes began to switch, but incorrectly. By selecting the preset "Faforite", the "Sleep" mode is enabled, and by selecting the preset "Sleep", the "Faforite" mode is enabled.
still exists. Nothing happens when the fan speed is changed.
There was also an error in the logs: "/usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior Bool = partial(_str2bool)"

**Comment by GreshnikYa** [comment]
> 1. Попробуйте главную ветку еще раз
> 2. Дубликат [functools.partial в будущем станет дескриптором метода #2060](https://github.com/al-one/hass-xiaomi-miot/issues/2060)
> 3. Ориентированный на дизайн

1. It still incorrectly processes commands, namely:
a) Calling the AUTO = AUTO command This mode works correctly. You don't need to edit anything here.
 b) Calling the Favorite = SLEEP command. There's a mistake here, it must be Favorite = Favorite This mode is not working correctly. Needs to be fixed.
 c) Calling the SLEEP=Favorite command. There is also a mistake here, it must be SLEEP=Favorite. This mode is not working correctly. Needs to be fixed.

2. There is also a problem with fan speed control. Nothing happens when the fan motor speed is changed.

**Comment by al-one** [comment]
Try master branch again.

**Comment by GreshnikYa** [comment]
> Попробуйте еще раз в главной ветке.

1)We almost managed to overcome the problem with the modes. But there is one small inaccuracy. When switching from SLEEP mode to FAVORITE mode, AUTO mode is enabled, and the FAVORITE mode should be enabled. When switching other modes, everything works correctly. It does not work from SLEEP mode to FAVORITE mode.
2)The problem with controlling the speed of the fan motor remains, the motor is not controlled at all.

**Comment by GreshnikYa** [comment]
> Try master branch again.

The problem persists. The fan speed is still not working. When I try to change the fan speed, I get 1 error and 1 warning
warning
Template variable warning: 'dict object' has no attribute 'switch_type' when rendering '{{ value_json.switch_type }}'
Template variable warning: 'dict object' has no attribute 'power_on_behavior' when rendering '{{ value_json.power_on_behavior }}'
Error
[139936502840334] Error during service call to fan.set_percentage: ValueError: Template error: int got invalid input 'None' when rendering template '{{ [props.mode, value|int] }}' but no default was specified

**Comment by GreshnikYa** [comment]
I still don't see the fan speed control working properly

Bad logger message: Request xiaomi api: miotspec/prop/get {'params': [{'did': '317042504', 'siid': 2, 'piid': 1}, {'did': '317042504', 'siid': 3, 'piid': 1}, {'did': '317042504', 'siid': 3, 'piid': 2}, {'did': '317042504', 'siid': 4, 'piid': 1}, {'did': '317042504', 'siid': 5, 'piid': 1}]} failed, response: None (('miotspec/prop/get', {'params': [{'did': '317042504', 'siid': 2, 'piid': 1}, {'did': '317042504', 'siid': 3, 'piid': 1}, {'did': '317042504', 'siid': 3, 'piid': 2}, {'did': '317042504', 'siid': 4, 'piid': 1}, {'did': '317042504', 'siid': 5, 'piid': 1}]}, None))

**Comment by al-one** [comment]
Provide debug logs

**Comment by GreshnikYa** [comment]
> Предоставление журналов отладки

https://pastebin.com/6yxa3Abt

**Comment by al-one** [comment]
```yaml
Device write data: [{'switch.physical_controls_locked': True}, {'method': 'set_properties', 'params': [{'siid': 4, 'piid': 1, 'did': '', 'value': True}]}]
Device write data: [{'switch.air_purifier.on': False}, {'method': 'set_properties', 'params': [{'siid': 2, 'piid': 1, 'did': '', 'value': False}]}]
Device write data: [{'switch.air_purifier.on': True}, {'method': 'set_properties', 'params': [{'siid': 2, 'piid': 1, 'did': '', 'value': True}]}]
Device write data: [{'air_purifier.on': False}, {'method': 'set_properties', 'params': [{'siid': 2, 'piid': 1, 'did': '', 'value': False}]}]
Device write data: [{'air_purifier.on': True}, {'method': 'set_properties', 'params': [{'siid': 2, 'piid': 1, 'did': '', 'value': True}]}]
Device write data: [{'air_purifier.mode': 'Favorite'}, {'method': 'set_properties', 'params': [{'siid': 2, 'piid': 3, 'did': '', 'value': 2}]}]
```
I only see logs related to operating the child lock, on/off, and modes, but not any logs related to fan speed.
