### ISSUE TITLE
dmaker.fan.p5c can only be set to 25, 50, 75 and 100%

### ISSUE THREAD

**Issue by NecoPastor** [al-one/hass-xiaomi-miot#2390]
### Device model / 设备型号

[dmaker.fan.p5c](https://home.miot-spec.com/s/dmaker.fan.p5c)

### Component version / 插件版本

v1.0.12

### HA core version / HA版本

core-2025.2.5

### Integrated mode / 集成方式

Token

### The problem / 问题详情

The ability to control the fan speed with precision down to the percentage has disappeared; now you can only select 0%, 25%, 50%, 75%, or 100%. In the older versions, everything worked fine

### Entity attributes / 实体属性

```yaml
info: dmaker.fan.p5c
model: dmaker.fan.p5c
did: ""
mac: 64:9E:31:23:07:0C
lan_ip: 10.10.0.220
app_link: ""
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p5c:1
available: true
home_room: ""
icon: mdi:information
updater: local
updated_at: "2025-02-26 10:26:08.645118+03:00"
indicator_light.on: false
fan.on: false
fan.fan_level: 1
fan.mode: 0
dm_service.speed_level: 25
dm_service.natural_list: a_b_c_d_e_f_g_h
dm_service.natural_e: 81ea5b9a4e490031_360_360_360_360_360_16
dm_service.natural_f: 81ea5b9a4e490032_360_360_360_360_360_16
dm_service.natural_g: 81ea5b9a4e490033_360_360_360_360_360_16
dm_service.natural_h: 81ea5b9a4e490034_360_360_360_360_360_16
off_delay_time: 0
physical_controls_locked: false
alarm: false
fan.horizontal_swing: false
horizontal_swing_included_angle-2-5: 140
fan.status: 0
converters:
  - button.info
  - light.indicator_light.on
  - fan.fan.on
  - fan.on
  - fan.fan_level
  - fan.horizontal_swing
  - fan.mode
  - switch.alarm
  - switch.physical_controls_locked
  - switch.fan.horizontal_swing
  - number.off_delay_time
  - select.horizontal_swing_included_angle-2-5
  - button.fan.turn_left
  - button.fan.turn_right
  - button.dm_service.toggle_mode
  - button.dm_service.loop_gear
customizes:
  button_actions: turn_left,turn_right,toggle_mode,loop_gear
  number_properties: off_delay_time
  switch_properties: alarm,horizontal_swing,vertical_swing
  chunk_coordinators:
    - interval: 10
      props: on,mode,fan_level
  number_select_properties: >-
    horizontal_swing_included_angle,horizontal_angle,vertical_swing_included_angle,vertical_angle
  percentage_property: speed_level
device_class: update
friendly_name: dmaker.fan.p5c Info
```
