### ISSUE TITLE
Xiaomi Aqara Wall Switch Wireless single button (WXKG03LM) lumi.remote.b186acn02

### ISSUE THREAD

**Issue by akepax** [al-one/hass-xiaomi-miot#2391]
### Device model / 设备型号

WXKG03LM

### Component version / 插件版本

1.0.12

### HA core version / HA版本

2025.2.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Xiaomi Aqara Wall Switch Wireless single button (WXKG03LM) lumi.remote.b186acn02, It has no functions, no automation, does not show battery charge

### Entity attributes / 实体属性

```yaml
info: Выключатель
model: lumi.remote.b186acn02
did: lumi.158d000abe42b1
mac: lumi.158d000abe42b1
lan_ip: 
app_link: mihome://device?uid=4180437857&did=lumi.158d000abe42b1
miot_type: urn:miot-spec-v2:device:remote-control:0000A021:lumi-b186acn02:1
available: true
home_room: Дом пользователя Денис Прихожая
icon: mdi:information
updater: none
updated_at: 
converters: button.info
customizes: 
{}

device_class: update
friendly_name: Выключатель Info
```
