### ISSUE TITLE
智米马桶不能正常工作

### ISSUE THREAD

**Issue by benjaminlei2007** [al-one/hass-xiaomi-miot#2393]
### Device model / 设备型号

[zhimi.toilet.pa5](https://home.miot-spec.com/s/zhimi.toilet.pa5)

### Component version / 插件版本

1.0.12

### HA core version / HA版本

2025.2.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

在HA中添加了该智米智能马桶2Pro（zhimi.toilet.pa5）以后，会挠乱原本设备自身的配置（原本通过设备遥控器设置的配置，以及米家APP设定的配置），比如，原本设定离座自动冲水，在HA集成后，就会被修改，且在米家APP中重新设置后，过一段时间又会被修改，直至从HA中删除集成。另外，智米智能马桶2Pro（zhimi.toilet.pa5）本身插件也不能正常：滤芯剩余寿命、工作状态、座盖/座圈开合状态、提示音、物理控制锁、离座自动冲水、夜灯、指示灯、马桶盖、触发马桶大冲，这实体显示不可用。

### Entity attributes / 实体属性

```yaml
info: 智米智能马桶
model: zhimi.toilet.pa5
did: 873653543
mac: xx:xx:xx:xx:xx:xx
lan_ip: 192.168.84.34
app_link: mihome://device?uid=15530681&did=873653543
miot_type: urn:miot-spec-v2:device:toilet:0000A02E:zhimi-pa5:1
available: false
home_room: wo家 卫生间
icon: mdi:information-off
updater: none
updated_at: 
state_updater: null
state_property: toilet.seating_state
converters: button.info, light.night_light.on, light.indicator_light.on, switch.alarm, switch.physical_controls_locked, sensor.filter.filter_life_level, sensor.toilet.status, sensor.function.cover_circle_status, switch.function.leave_auto_flushing, select.function.water_temperature, select.function.wind_temperature, button.function.flushing, button.function.open_cover_circle, button.function.stoving, button.function.hip_washing, button.function.women_washing, button.function.move_back_and_forth, button.function.close_cover_circle
customizes: 
sensor_properties: >-
  status,cover_circle_status,current_water_temp,current_seat_temp,flush_status,radar_sensor_status
switch_properties: pir_switch,leave_auto_flushing,off_seat_close_cover
select_properties: water_temperature,wind_temperature
button_actions: >-
  flushing,open_cover_circle,close_cover_circle,stoving,hip_washing,women_washing,move_back_and_forth,hot_cold_massage,nozzle_cleaning

miot_error: Unable to recover failed command
device_class: update
friendly_name: 智米智能马桶 信息
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: miio.miioprotocol
来源: custom_components/xiaomi_miot/core/device.py:1379
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 15:31:18 (29 次总计出现)
上次记录: 15:45:20

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
