### ISSUE TITLE
cubee.airrtc.th123w change modes not work

### ISSUE THREAD

**Issue by skymota** [al-one/hass-xiaomi-miot#2399]
### Device model / 设备型号

cubee.airrtc.th123w

### Component version / 插件版本

1.0.12

### HA core version / HA版本

2025.2.5

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

In previous version (1.0.8 and before), the change mode is working correct, but after version 1.0.9 predefined modes (HOME AWAY SMART SLEEP ) not working. When select the device not change mode.

### Entity attributes / 实体属性

```yaml
icon: mdi:information
device_class: update
friendly_name: Termostato Info
info: Termostato
model: cubee.airrtc.th123w
did: 436713373
mac: B4:60:ED:26:4A:F2
lan_ip: 192.168.0.10
app_link: mihome://device?uid=1759959757&did=436713373
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:cubee-th123w:1
available: true
home_room: Casa Entrada
updater: cloud
updated_at: 2025-03-03 00:43:44.019626+01:00
thermostat.on: true
thermostat.mode: 2
thermostat.target_temperature: 15
heatold.childlock: false
heatold.tempactivate: 1
heatold.tempcomp: 0
heatold.tempfloor: 0
thermostat.status: 0
thermostat.temperature: 17
converters: button.info, climate.thermostat.mode, thermostat.on, thermostat.target_temperature, thermostat.temperature, thermostat.mode, switch.heatold.childlock, select.heatold.tempactivate, select.heatold.tempcomp
customizes: 
switch_properties: childlock
chunk_coordinators:
  - interval: 10
    props: on,mode,target_temperature,fan_level
    notify: true
chunk_properties: 1
select_properties: tempactivate,tempcomp
exclude_miot_properties: fault,sensortype,maxsettemp,minsettemp
```
