### ISSUE TITLE
vacuum-cleaner stopped working since version 0.47

### ISSUE THREAD

**Issue by catalin2009** [al-one/hass-xiaomi-miot#240]
vacuum.mijia_v2_5512_robot_cleaner stopped working since version 0.4.8. 

version 0.4.7 was ok.

error -9999 when any commands is given from lan.

**Comment by al-one** [comment]
The vacuum of this model [`mijia.vacuum.v2`](https://home.miot-spec.com/s/mijia.vacuum.v2) supports local mode, but it may return error `-9999` due to querying too many properties. Please try to [add this custom attribute ](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui)and observe again:
```yaml
# customize.yaml
vacuum.mijia_v2_5512_robot_cleaner:
  exclude_miot_services: alarm,remote_control,language
```
