### ISSUE TITLE
v1.0.13 broke yeelink.curtain.ctmt2 support

### ISSUE THREAD

**Issue by almirus** [al-one/hass-xiaomi-miot#2403]
### Device model / 设备型号

[yeelink.curtain.ctmt2](https://home.miot-spec.com/s/yeelink.curtain.ctmt2) support  

### Component version / 插件版本

1.0.13

### HA core version / HA版本

2025.2.5

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

After updating the integration to version 0.1.13, HA stopped receiving and updating the status of whether the curtain is open or not. However, the control icons update correctly. The global status remains "Closed" even after opening the curtain.

**The issue might be related to the new attribute "state_is_closed".**

### Entity attributes / 实体属性

```yaml
v1.0.12
`
cover.yeelink_ctmt2_4752_motor_control
closed	
current_position: 0
closed_position: 2
deviated_position: 2
curtain.target_position: 50
curtain.current_position: 1
curtain.motor_control: null
device_class: curtain
friendly_name: Шторы гостиная Штора
supported_features: 15
`
v1.0.13
`
cover.yeelink_ctmt2_4752_motor_control
closed	
current_position: 100
closed_position: 2
deviated_position: 2
state_is_closed: true
curtain.current_position: 100
curtain.target_position: 50
device_class: curtain
friendly_name: Шторы гостиная Штора
supported_features: 15
curtain.motor_control: null
`
```
