### ISSUE TITLE
米家智能晾衣架pro电机反转又失效了

### ISSUE THREAD

**Issue by tuzkiyoung** [al-one/hass-xiaomi-miot#2404]
### Device model / 设备型号

hyd.airer.pro2

### Component version / 插件版本

1.0.13

### HA core version / HA版本

2025.2.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

$customize.yaml
cover.hyd_pro2_db57_airer_2:
  motor_reverse: true
之前有个版本电机反转配置失效，上个版本好了，这次更新之后又失效了。homekit显示打开（实际关闭），反之亦然，麻烦大佬看下，谢谢

### Entity attributes / 实体属性

```yaml
实体
cover.hyd_pro2_db57_airer_2
Mijia Smart Clothes Drying Rack Pro 晾衣架

状态
unknown

属性
friendly_name: Mijia Smart Clothes Drying Rack Pro 晾衣架
supported_features: 11
motor_reverse: true
target2current_position: true
state_is_closed: null
airer.status: 4
```
