### ISSUE TITLE
Viomi heater is unavailable

### ISSUE THREAD

**Issue by RykovDC** [al-one/hass-xiaomi-miot#2409]
### Device model / 设备型号

viomi.heater.v9

### Component version / 插件版本

1.0.13

### HA core version / HA版本

2025.3.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Viomi heater is unavailable. 

![Image](https://github.com/user-attachments/assets/40932c4f-4b6d-4a8e-a745-d7ac5faeb6a7)

### Entity attributes / 实体属性

```yaml
climate.viomi_heater_bedroom

unavailable

hvac_modes: off, auto
min_temp: 5
max_temp: 35
target_temp_step: 1
preset_modes: Strong
friendly_name: Конвектор
supported_features: 401
```

### Home Assistant Logs / 系统日志

[home-assistant_2025-03-10T12-17-17.543Z.log](https://github.com/user-attachments/files/19162299/home-assistant_2025-03-10T12-17-17.543Z.log)
