### ISSUE TITLE
Request Support for aqara smart clothes drying rack lite

### ISSUE THREAD

**Issue by merv2k4** [al-one/hass-xiaomi-miot#2413]
### Device model / 设备型号

[lumi.airer.acn02](https://home.miot-spec.com/s/umi.airer.acn02)

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi Currently when i added the drying rack lite with the host key and ip, it is added successfully.

But I can only control the Down button and not the up. 

1) The status percentage being updated is correct. Whenever i use Mi Home app to control the cover, it is updating properly.

![Image](https://github.com/user-attachments/assets/289a18a2-f303-49ac-b704-6f6c23925b24)

![Image](https://github.com/user-attachments/assets/a80f7126-3c9b-4620-a539-5c71b93cf595)

2) The problem is, I can only see and press the Down Button. The UP button cannot be selected or used.

![Image](https://github.com/user-attachments/assets/20c7f636-2e55-47b3-8b13-a14f91449be5)

3) attributes

![Image](https://github.com/user-attachments/assets/c253c11d-fafd-476f-9aa3-f2467d441781)

Thanks!

![Image](https://github.com/user-attachments/assets/47946516-219f-40e4-8c04-c914ccdffad2)

![Image](https://github.com/user-attachments/assets/d6fded36-3724-4fff-a14c-9f87f1514184)

### Entity attributes / 实体属性

```yaml
button.lumi_acn02_17d2_info
2025-03-11T16:31:42.239821+00:00
device_class: update
icon: mdi:information
friendly_name: L1 WASH AREA HANGER Info
button.info: L1 WASH AREA HANGER
model: lumi.airer.acn02
did: 
mac: B4:60:ED:30:17:D2
lan_ip: 192.168.102.245
app_link: 
miot_type: urn:miot-spec-v2:device:airer:0000A00D:lumi-acn02:1
available: true
home_room: 
updater: local
updated_at: 2025-03-12 01:17:09.076247+08:00
airer.status: 0
airer.current_position: 20
airer.target_position: 100
remote_button.f_one_wireless: 0
remote_button.f_two_wireless: 0
remote_button.f_three_wireless: 0
remote_button.f_four_wireless: 0
remote_button.f_one_position: 20
remote_button.f_two_position: 40
remote_button.f_three_position: 60
remote_button.f_four_position: 80
airer_user.pos_limit: 1
airer_user.mute_mode: 0
airer_user.tracer_mode: 0
airer_user.tracer_mode_cfg: 
airer_user.run_time: 16
light.on: false
airer.fault: 0
converters: button.info, light.light.on, cover.airer.motor_control, airer.status, airer.motor_control, airer.current_position, airer.target_position
customizes: 
position_reverse: true
sensor_properties: left_time
switch_properties: dryer,uv
select_properties: drying_level
chunk_coordinators:
  - interval: 15
    props: status,current_position,target_position,dryer,drying_level

info: null



cover.lumi_acn02_17d2_airer
motor_reverse: false
position_reverse: true
closed_position: 2
deviated_position: 2
friendly_name: L1 WASH AREA HANGER Airer
supported_features: 15
current_position: 80
state_is_closed: false
airer.current_position: 20
airer.target_position: 100
airer.status: 0
```
