### ISSUE TITLE
电热毛巾架正常工作，但是有报错日志

### ISSUE THREAD

**Issue by z-henry** [al-one/hass-xiaomi-miot#2414]
### Device model / 设备型号

jyf.tow_w.ts03

### Component version / 插件版本

1.0.9

### HA core version / HA版本

2024.11.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

设备能正常工作，但是有大量的error日志  

![Image](https://github.com/user-attachments/assets/c4c325b1-5c93-49dd-bd98-393cf5ff7c49)

### Entity attributes / 实体属性

```yaml
info: Drying towel rack
model: jyf.tow_w.ts03
did: "732395954"
mac: B8:50:D8:50:7A:23
lan_ip: 192.168.100.119
app_link: mihome://device?uid=1310658641&did=732395954
miot_type: urn:miot-spec-v2:device:towel-rack:0000A09A:jyf-ts03:1
available: true
home_room: 卫生间
icon: mdi:information
updater: cloud
updated_at: "2025-03-14 13:43:10.590330+08:00"
airer.left_time: 118
towel_rack.on: false
towel_rack.temperature: 25
towel_rack.target_temperature: 45
converters:
  - button.info
  - switch.towel_rack.on
  - cover.airer.motor_control
  - airer.motor_control
  - sensor.towel_rack.temperature
  - number.towel_rack.target_temperature
  - select.towel_rack.mode
customizes:
  sensor_properties: temperature
  select_properties: mode
  number_properties: target_temperature
  auto_cloud: true
  interval_seconds: 120
  exclude_miot_properties: mode,fault
  chunk_coordinators:
    - interval: 30
      props: on,target-temperature,temperature,left_time
device_class: update
friendly_name: Drying towel rack 信息
```

### Home Assistant Logs / 系统日志

2025-03-14 13:27:49.156 DEBUG (MainThread) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request miot api: scene/history {'home_id': 17001115792, 'uid': 1310658641, 'owner_uid': 1310658641, 'command': 'history', 'limit': 15} result: bytearray(b'{"code":0,"message":"\xe6\x88\x90\xe5\x8a\x9f","result":{"history":[]}}')
2025-03-14 13:27:49.156 DEBUG (MainThread) [custom_components.xiaomi_miot.sensor] Finished fetching xiaomi_miot-mihome-scene-history-1310658641_17001115792 data in 0.057 seconds (success: True)
2025-03-14 13:27:50.569 ERROR (SyncWorker_57) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2025-03-14 13:27:50.570 INFO (MainThread) [custom_components.xiaomi_miot.core.device.jyf.tow_w.ts03] Got MiioException while fetching the state: Unable to recover failed command, mapping: {'airer.left_time': {'siid': 4, 'piid': 10}, 'towel_rack.on': {'siid': 2, 'piid': 1}, 'towel_rack.temperature': {'siid': 2, 'piid': 6}}, max_properties: 3/3
2025-03-14 13:27:50.602 DEBUG (MainThread) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request miot api: miotspec/prop/get {'params': [{'did': '732395954', 'siid': 4, 'piid': 10}, {'did': '732395954', 'siid': 2, 'piid': 1}, {'did': '732395954', 'siid': 2, 'piid': 6}]} result: bytearray(b'{"code":0,"message":"ok","result":[{"did":"732395954","iid":"0.4.10","siid":4,"piid":10,"value":134,"code":0,"updateTime":1741930070,"exe_time":0},{"did":"732395954","iid":"0.2.1","siid":2,"piid":1,"value":false,"code":0,"updateTime":1741930070,"exe_time":0},{"did":"732395954","iid":"0.2.6","siid":2,"piid":6,"value":25,"code":0,"updateTime":1741930070,"exe_time":0}]}')
2025-03-14 13:27:50.602 INFO (MainThread) [custom_components.xiaomi_miot.core.device.jyf.tow_w.ts03] Device updated: {'switch.towel_rack.on': False, 'sensor.towel_rack.temperature': 25, 'only_info': False}
2025-03-14 13:27:50.603 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] switch.jyf_ts03_7a23_towel_rack: Entity state updated: None
2025-03-14 13:27:50.604 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.jyf_ts03_7a23_info: Entity state updated: None
2025-03-14 13:27:50.604 DEBUG (MainThread) [custom_components.xiaomi_miot.core.device.jyf.tow_w.ts03] Finished fetching b8:50:d8:50:7a:23-32cb8658ff391a2503aa1a70c421c607-chunk_1 data in 16.180 seconds (success: True)
2025-03-14 13:27:50.604 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Drying towel rack(jyf.tow_w.ts03): Coordinator updated: ['b8:50:d8:50:7a:23-32cb8658ff391a2503aa1a70c421c607-chunk_1', [{'did': '732395954', 'iid': '0.4.10', 'siid': 4, 'piid': 10, 'value': 134, 'code': 0, 'updateTime': 1741930070, 'exe_time': 0, 'prop': 'airer.left_time'}, {'did': '732395954', 'iid': '0.2.1', 'siid': 2, 'piid': 1, 'value': False, 'code': 0, 'updateTime': 1741930070, 'exe_time': 0, 'prop': 'towel_rack.on'}, {'did': '732395954', 'iid': '0.2.6', 'siid': 2, 'piid': 6, 'value': 25, 'code': 0, 'updateTime': 1741930070, 'exe_time': 0, 'prop': 'towel_rack.temperature'}]]
