### ISSUE TITLE
Pet feeder 2: Eaten food measurement always 0

### ISSUE THREAD

**Issue by NeskireDK** [al-one/hass-xiaomi-miot#2415]
### Device model / 设备型号

xiaomi.feeder.iv2001

### Component version / 插件版本

1.0.13

### HA core version / HA版本

2025.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

These 3 entities keep showing 0, regardless of how much food is dispensed and eaten by the cats. 
- sensor.xiaomi_iv2001_75ab_eaten_food_measure_4
- sensor.xiaomi_iv2001_75ab_eaten_food_measure_2
- sensor.xiaomi_iv2001_75ab_eaten_food_measure

![Image](https://github.com/user-attachments/assets/aa07f0d3-c8bf-4ae6-b064-255d0eb4f43a)

The same info in Xiaomi app works as expected. 

![Image](https://github.com/user-attachments/assets/236311d7-0c2f-4f01-87a0-529ac3c0cad2)

### Entity attributes / 实体属性

```yaml
button.info: Pet Feeder
model: xiaomi.feeder.iv2001
did: 644128806
mac: DC:ED:83:B2:75:AB
lan_ip: 192.168.1.136
app_link: mihome://device?uid=1863521112&did=644128806
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:xiaomi-iv2001:1
available: true
home_room: Kitchen
icon: mdi:information
updater: local
updated_at: 2025-03-15 09:36:58.741878+01:00
feeder_schedule-5-1: [1,06300101,12000101,18000101]
add_meal_state-5-3: 0
plan_process_display-5-4: 1
food_intake_rate-5-5: 10
food_intake_state-5-6: 1
max_schcdule_num-5-7: 35
schedule_state-5-8: 1
add_meal_cycle-5-10: 8
food_out_progress-5-11: 100
compensate_switch-5-12: 0
prevent_accumulation-5-14: 1
schedule_progress-5-15: 33
add_meal_triggertime-5-16: 0
device_timezone-5-17: 3600
desiccant.desiccant_left_level: 0
desiccant.desiccant_left_time: 0
battery_level: false
physical_controls_locked: false
physical_controls_locked.mode: 0
pet_feeder.fault: 0
pet_feeder.pet_food_left_level: 0
target_feeding_measure-2-7: 1
pet_feeder.status: 0
pet_feeder-2.food_out_status: 0
add_meal_notify_status-2-13: 0
pet_feeder-2.food_heap_status: 0
pet_feeder.eaten_food_measure: 0
pet_feeder-2.eaten_food_measure: 0
eaten_food_measure-2-22: 0
eaten_food_measure-2-23: 0
pet_feeder-2.status: 0
pet_feeder-2.status-28: 0
pet_feeder-2.status-29: 33
pet_feeder-2.status-31: 0
pet_feeder-2.status-32: 0
converters: button.info, sensor.pet_feeder.status, switch.physical_controls_locked, sensor.battery_level, sensor.pet_feeder.pet_food_left_level, sensor.pet_feeder-2.food_out_status, sensor.add_meal_notify_status-2-13, sensor.pet_feeder-2.food_heap_status, sensor.pet_feeder.eaten_food_measure, sensor.pet_feeder-2.eaten_food_measure, sensor.eaten_food_measure-2-22, sensor.eaten_food_measure-2-23, sensor.pet_feeder-2.status, sensor.pet_feeder-2.status-28, sensor.pet_feeder-2.status-29, sensor.pet_feeder-2.status-31, sensor.pet_feeder-2.status-32, sensor.desiccant.desiccant_left_level, sensor.desiccant.desiccant_left_time, sensor.status, switch.compensate_switch-5-12, switch.prevent_accumulation-5-14, number.target_feeding_measure-2-7, button.pet_feeder.pet_food_out, button.pet_feeder.weigh_manual_calibrate, button.desiccant.reset_desiccant_life
customizes: 
button_actions: pet_food_out,reset_desiccant_life,weigh_manual_calibrate
number_properties: target_feeding_measure,food-intake-rate
sensor_properties: >-
  pet_food_left_level,status,eaten_food_measure,desiccant_left_level,desiccant_left_time
switch_properties: >-
  add-meal-state,food-intake-state,schedule-state,compensate_switch,prevent_accumulation
select_properties: set-screen-display

info: null
device_class: update
friendly_name: Pet Feeder Info
```

### Home Assistant Logs / 系统日志

states: 

![Image](https://github.com/user-attachments/assets/feb7f066-fea7-4ef0-bf4d-3cf20405aa10)

**Comment by al-one** [comment]
They are properties from the miot specifications defined by the manufacturer. If you think they are useless, you can disable them in HA.

**Comment by NeskireDK** [comment]
Ah, I should have been more clear. I’d like to access the property of how many grams have been removed from the bowl, total over the day. Is this not possible to access? Any work arounds such as sum max scale every 5 minutes per day?

**Comment by Wh1terat** [comment]
@al-one I also upgraded to xiaomi.feeder.iv2001 😸 (we spent some time working on the older mmgg feeder a few years ago - at least this one supports miot!)

Only just started looking into it; but here is the react plugin for this feeder which may illuminate the matter further.

[signed_10093_1020565_31_IOS_bundle_f71fca042d58d6a69059a10390d3a9f9.zip](https://github.com/user-attachments/files/19267241/signed_10093_1020565_31_IOS_bundle_f71fca042d58d6a69059a10390d3a9f9.zip)

**Comment by Wh1terat** [comment]
So just looks like yet another half arsed miot spec from Xiaomi. (What is the point of their spec validation suite at this point?)
and this one is actually a Xiaomi product for a change too! Setting a bad example I'd say.
(surely duplicate names under a siid should not be allowed?)

As best as I can tell, the food eaten miot props do nothing. The app relies upon the custom service.
Perhaps possible to use `xiaomi_miot.request_xiaomi_api` in a script to pull this.

Feeding measure seems to be mostly broken (siid 2, piid 8) has no access at all) and piid 7 takes whatever value was last used by pet-food-out, you can write to it but it gets overwritten.  Also not sure the piid gets passed to `pet-food-out` still as always dispenses 1.

Toggling automatic feeding is not as simple as just a switch; it needs to set the first list entry for feeder_schedule (siid 5, piid 1) to 0/1 rather than just a normal bool property.

This is what I'm going with so far.

```yaml
customizing_device:
  xiaomi.feeder.iv2001:
    binary_sensor_properties: fault
    button_actions: pet_food_out,reset_desiccant_life,weigh_manual_calibrate
    number_properties: target_feeding_measure,add_meal_cycle,food_intake_rate
    sensor_properties: feeding_measure,pet_food_left_level,food_out_status,food_out_progress,food_heap_status,eaten_food_measure,desiccant_left_level,desiccant_left_time,schedule_progress,status
    switch_properties: mode,plan_process_display,add_meal_triggertime,compensate_switch,prevent_accumulation,food_intake_state
```

Also just for matching up to the app descriptions:

| siid | piid | description                                |
|------|------|--------------------------------------|
| 3    | 1    | Child lock                          |
| 3    | 3    | Auto screen-off                     |
| 5    | 4    | Display schedule progress           |
| 5    | 5    | Low food intake threshold          |
| 5    | 6    | Low food consumption notification   |
| 5    | 10   | Empty food bowl duration           |
| 5    | 12   | Dispensing error correction        |
| 5    | 14   | Food bowl spillage prevention      |
| 5    | 15   | Food eaten today                   |
| 5    | 16   | Refill reminder                    |
