### ISSUE TITLE
Incorrect Humidifier fan level

### ISSUE THREAD

**Issue by dennismora** [al-one/hass-xiaomi-miot#2423]
### Device model / 设备型号

zhimi.humidifier.ca1 zhimi.humidifier.cb1

### Component version / 插件版本

2.1.0

### HA core version / HA版本

last

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Incorrect Humidifier fan level on zhimi.humidifier.ca1 zhimi.humidifier.cb1

![Image](https://github.com/user-attachments/assets/d9c497a9-74d2-4a76-a0c7-e0b965a5a09b)

### Entity attributes / 实体属性

```yaml
id: 1734551819919
last_triggered: 2025-03-19T07:48:02.589783+00:00
mode: single
current: 0
friendly_name: Илья увлажнитель 1
```
