### ISSUE TITLE
Dehumidifier can't correctly set humidity

### ISSUE THREAD

**Issue by IDhiding** [al-one/hass-xiaomi-miot#2424]
### Device model / 设备型号

deye.derh.u20a3

### Component version / 插件版本

1.0.14

### HA core version / HA版本

2025.3.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

<img width="623" alt="Image" src="https://github.com/user-attachments/assets/5ed104dc-c8b2-4522-b706-8ceece155ca8" />

Previous version can be adjusted between 30 and 80, like in the mihome app.

![Image](https://github.com/user-attachments/assets/7cf2f30c-ae05-467b-a4fc-cd6cf77bd97f)

### Entity attributes / 实体属性

```yaml
min_humidity: 0
max_humidity: 11
available_modes:
  - "Off"
  - 除湿
  - 净化
  - 干衣
  - 自动
  - 睡眠
current_humidity: 57
humidity: 55
mode: "Off"
dehumidifier.target_humidity: 6
dehumidifier.on: false
dehumidifier.mode: 0
dehumidifier.fan_level: 3
environment.relative_humidity: 57
device_class: dehumidifier
friendly_name: 除湿机
supported_features: 1
```
