### ISSUE TITLE
地暖中的模式其实是空调的模式，地暖应该只有开关和温度调节

### ISSUE THREAD

**Issue by classhu** [al-one/hass-xiaomi-miot#2426]
### Device model / 设备型号

[tofan.airrtc.wk01](https://home.miot-spec.com/s/tofan.airrtc.wk01)

### Component version / 插件版本

1.0.15

### HA core version / HA版本

2025.2.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

地暖中是空调的模式

![Image](https://github.com/user-attachments/assets/a100abd4-a2e9-4ccc-a04e-18caa2ff6518)

![Image](https://github.com/user-attachments/assets/de81eb33-1782-458a-a5f7-30ccaa9cb57a)

### Entity attributes / 实体属性

```yaml
地暖
hvac_modes:
  - heat
  - auto
  - cool
  - fan_only
  - "off"
  - dry
min_temp: 16
max_temp: 35
target_temp_step: 1
current_temperature: 21
temperature: 35
current_humidity: 33
air_conditioner.on: false
air_conditioner.mode: 0
target_temperature-2-4: 35
environment.relative_humidity: 33
environment.temperature: 21
friendly_name: 客厅地暖
supported_features: 385

空调
hvac_modes:
  - auto
  - "off"
min_temp: 16
max_temp: 32
target_temp_step: 1
fan_modes:
  - 自动
  - 低风速
  - 中风速
  - 高风速
current_temperature: 21
temperature: 30
current_humidity: 33
fan_mode: 高风速
thermostat.fan_level: 4
thermostat.target_temperature: 30
thermostat.on: false
environment.relative_humidity: 33
environment.temperature: 21
friendly_name: 客厅空调
supported_features: 393
```

### Home Assistant Logs / 系统日志

2025-03-21 16:25:59.458 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] 2.0TR(tofan.airrtc.wk01): Coordinator updated: ['ac:8c:46:5c:b5:75-01J87BHX7KEPPMVCRVKCQ4JNS8-chunk_1', [{'did': '887737500', 'iid': '0.4.1', 'siid': 4, 'piid': 1, 'value': False, 'code': 0, 'updateTime': 1742545424, 'exe_time': 0, 'prop': 'thermostat.on'}, {'did': '887737500', 'iid': '0.4.2', 'siid': 4, 'piid': 2, 'value': 17, 'code': 0, 'updateTime': 1742545421, 'exe_time': 0, 'prop': 'thermostat.target_temperature'}, {'did': '887737500', 'iid': '0.4.3', 'siid': 4, 'piid': 3, 'value': 4, 'code': 0, 'updateTime': 1742529658, 'exe_time': 0, 'prop': 'thermostat.fan_level'}, {'did': '887737500', 'iid': '0.3.1', 'siid': 3, 'piid': 1, 'value': False, 'code': 0, 'updateTime': 1742538559, 'exe_time': 0, 'prop': 'air_fresh.on'}, {'did': '887737500', 'iid': '0.3.3', 'siid': 3, 'piid': 3, 'value': 1, 'code': 0, 'updateTime': 1742538557, 'exe_time': 0, 'prop': 'air_fresh.mode'}, {'did': '887737500', 'iid': '0.3.4', 'siid': 3, 'piid': 4, 'value': 4, 'code': 0, 'updateTime': 1742538553, 'exe_time': 0, 'prop': 'air_fresh.fan_level'}, {'did': '887737500', 'iid': '0.2.1', 'siid': 2, 'piid': 1, 'value': False, 'code': 0, 'updateTime': 1742545411, 'exe_time': 0, 'prop': 'air_conditioner.on'}, {'did': '887737500', 'iid': '0.2.2', 'siid': 2, 'piid': 2, 'value': 0, 'code': 0, 'updateTime': 1742545408, 'exe_time': 0, 'prop': 'air_conditioner.mode'}, {'did': '887737500', 'iid': '0.2.4', 'siid': 2, 'piid': 4, 'value': 16, 'code': 0, 'updateTime': 1742545393, 'exe_time': 0, 'prop': 'target_temperature-2-4'}]]
