### ISSUE TITLE
Missing water level for xiaomi.humidifier.p800

### ISSUE THREAD

**Issue by ilyakitaev** [al-one/hass-xiaomi-miot#2428]
### Device model / 设备型号

xiaomi.humidifier.p800

### Component version / 插件版本

1.0.15

### HA core version / HA版本

2025.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

https://home.miot-spec.com/spec/xiaomi.humidifier.p800

No entity present in integration for triggering like zhimi.humidifier.ca6 as example. 

### Entity attributes / 实体属性

```yaml
button.info: Humidifier 2
model: xiaomi.humidifier.p800
did: 
mac: 
lan_ip: 
app_link: 
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:xiaomi-p800:1
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-03-21 12:37:27.824854+03:00
humidifier.on: false
humidifier.mode: 0
humidifier.target_humidity: 55
environment.relative_humidity: 47
environment.temperature: 23
filter.filter_life_level: 99
dm_service.filter_clean: 0
delay: false
delay.delay_time: 0
delay.delay_remain_time: 0
clean.self_clean: 1
clean.clean_left_time: 0
physical_controls_locked: false
screen.on: true
screen.brightness: 1
alarm: false
humidifier.fault: 0
humidifier.overwet_protect: false
humidifier.automatic_air_drying: true
humidifier.air_dry_remain_time: 9
humidifier.water_level: 53
converters: button.info, humidifier.humidifier.on, humidifier.on, humidifier.target_humidity, humidifier.mode, environment.relative_humidity, switch.alarm, switch.physical_controls_locked, sensor.filter.filter_life_level, sensor.environment.temperature, sensor.environment.relative_humidity, select.humidifier.mode
customizes: 
interval_seconds: 120
select_properties: mode
chunk_coordinators:
  - interval: 20
    props: humidifier.on,mode,target_humidity,fan_level
  - interval: 25
    props: relative_humidity,temperature
  - interval: 300
    props: filter_life_level,filter_left_time,filter_used_time

info: null
device_class: update
friendly_name: Humidifier 2 Info
```
