### ISSUE TITLE
Set sweep mode (vacuum, vacumm&mop, mop) - Viomi SE

### ISSUE THREAD

**Issue by kodifan** [al-one/hass-xiaomi-miot#243]
Not exactly an issue but rather help request :)
How can I set this vacuum mode ? 
I can read state of it without any problem (vacuum.wdr_mode attribute) but cannot set it the same way that i set water grade for example:
```yaml
service: vacuum.send_command
target:
  entity_id: vacuum.viomi_v19_e351_robot_cleaner
data:
  command: set_properties
  params:
    - siid: 2
      piid: 11
      value: 2
```
Is it even possible or it is depending on other command or attribute ?

**Comment by al-one** [comment]
You need to use service: [`xiaomi_miot.set_miot_property`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.set_miot_property)
```yaml
service: xiaomi_miot.set_miot_property
data:
  entity_id: vacuum. viomi_v19_e351_robot_cleaner
  siid: 2
  piid: 11
  value: 2
```
