### ISSUE TITLE
Expose mode selection to assistant

### ISSUE THREAD

**Issue by D3SOX** [al-one/hass-xiaomi-miot#2431]
### Device model / 设备型号

 zhimi.airp.mb5 

### Component version / 插件版本

1.0.15

### HA core version / HA版本

2025.3.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

My voice assistant can't set my device to specific modes (or percentages).

I have a workaround by creating helper scripts like that

![Image](https://github.com/user-attachments/assets/2c887893-8ed5-41f3-b0cb-0e3ecfbb308e)

but I think it would be possible and better for the integration to somehow expose it automatically.

### Entity attributes / 实体属性

```yaml
button.info: Anti-Virus real life edition
model: zhimi.airp.mb5
did: 494464584
mac: 7C:C2:94:19:36:8E
lan_ip: 192.168.0.241
app_link: mihome://device?uid=1877345482&did=494464584
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb5:1
available: true
home_room: Vienna Nico's room
icon: mdi:information
updater: local
updated_at: 2025-03-22 16:02:30.092233+01:00
air_purifier.on: true
air_purifier.mode: 0
air_purifier.fan_level: 2
filter.filter_life_level: 41
filter.filter_used_time: 4152
filter.filter_left_time: 118
rfid.rfid_tag: 80:71:cb:ba:75:d8:4
rfid.rfid_factory_id: 0:0:41:50
rfid.rfid_product_id: 0:0:32:36
rfid.rfid_time: 0:21:11:2
rfid.rfid_serial_num: 0:0:61:19
aqi.purify_volume: 430538
aqi.average_aqi: 47
aqi.aqi_state: 1
aqi.aqi_updata_heartbeat: 0
custom_service.moto_speed_rpm: 1056
custom_service.favorite_speed: 2000
custom_service.motor_set_speed: 1050
custom_service.favorite_level: 11
custom_service.buttom_door: false
custom_service.reboot_cause: 0
custom_service.manual_level: 2
custom_service.country_code: 2
custom_service.iic_error_count: 3
temperature_display_unit-14-1: 1
screen.brightness: 2
physical_controls_locked: false
alarm: false
environment.relative_humidity: 43
environment.pm2_5_density: 30
environment.temperature: 18.9
air_purifier.fault: 0
air_purifier.anion: false
converters: button.info, fan.air_purifier.on, air_purifier.on, air_purifier.fan_level, air_purifier.mode, switch.alarm, switch.physical_controls_locked, sensor.filter.filter_life_level, sensor.filter.filter_left_time, sensor.filter.filter_used_time, sensor.environment.temperature, sensor.environment.relative_humidity, sensor.environment.pm2_5_density, sensor.custom_service.moto_speed_rpm, sensor.filter_time.filter_used_debug, switch.air_purifier.anion, number.custom_service.favorite_speed, number.custom_service.favorite_level, select.screen.brightness, select.temperature_display_unit-14-1
customizes: 
switch_properties: anion,alarm
sensor_properties: moto_speed_rpm,filter_used_debug
chunk_coordinators:
  - interval: 10
    props: on,mode,fan_level
  - interval: 300
    props: filter_life_level,filter_left_time,filter_used_time
select_properties: brightness,temperature_display_unit
number_properties: favorite_speed,favorite_level

info: null
device_class: update
friendly_name: Anti-Virus real life edition Info
```

### Home Assistant Logs / 系统日志

This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/xiaomi_miot/core/converters.py:4
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 4:01:11 PM (1 occurrences)
Last logged: 4:01:11 PM

/usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior Bool = partial(_str2bool)
