### ISSUE TITLE
"LOEASE Smart Temperature And Humidity Meter T35 " no data show up

### ISSUE THREAD

**Issue by mars33** [al-one/hass-xiaomi-miot#2432]
### Device model / 设备型号

LOEASE Smart Temperature And Humidity Meter T35 BLE

### Component version / 插件版本

1.0.15

### HA core version / HA版本

2025.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

"LOEASE Smart Temperature And Humidity Meter T35 " no data show up

I have added “LOEASE Smart Temperature And Humidity Meter T35” to the app and it displays the data, but there is no physical display of temperature and humidity in HA.

![Image](https://github.com/user-attachments/assets/0d2184e2-2668-4b18-955a-a2005a3cf135)

### Entity attributes / 实体属性

```yaml
select.ec7611716fcf_command
options: -, info
icon: mdi:apple-keyboard-command
friendly_name: LOEASE Smart Temperature And Humidity Meter T35 Command
```
