### ISSUE TITLE
小米屏幕挂灯1S连接不稳定，日志频繁报错

### ISSUE THREAD

**Issue by ZiqiangWangUNSW** [al-one/hass-xiaomi-miot#2434]
### Device model / 设备型号

yeelink.light.lamp22

### Component version / 插件版本

1.0.15

### HA core version / HA版本

2025.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

HA系统日志中，提醒出现重复报错：
日志记录器: custom_components.xiaomi_miot.core.device.yeelink.light.lamp22
来源: custom_components/xiaomi_miot/core/device.py:910
首次出现: 15:51:42 (26 次总计出现)
上次记录: 18:22:07

> Got MiioException while fetching the state: Unable to discover the device 192.168.1.100, mapping: {'yl_light.save_state': {'siid': 3, 'piid': 1}, 'yl_light.delay_time': {'siid': 3, 'piid': 2}, 'yl_light.delay_off_enable': {'siid': 3, 'piid': 4}, 'yl_light.double_click_enable': {'siid': 3, 'piid': 6}, 'yl_light.double_click': {'siid': 3, 'piid': 7}, 'yl_light.long_press_enable': {'siid': 3, 'piid': 8}, 'yl_light.scene_mode': {'siid': 3, 'piid': 9}, 'yl_light.long_press_one': {'siid': 3, 'piid': 13}, 'yl_light.long_press_two': {'siid': 3, 'piid': 14}, 'yl_light.long_press_three': {'siid': 3, 'piid': 15}, 'yl_light.work_minutes': {'siid': 3, 'piid': 16}, 'yl_light.break_minutes': {'siid': 3, 'piid': 17}, 'yl_light.pomodoro_enable': {'siid': 3, 'piid': 18}, 'yl_light.mode_one_bright': {'siid': 3, 'piid': 19}, 'yl_light.mode_one_ct': {'siid': 3, 'piid': 20}, 'yl_light.mode_two_bright': {'siid': 3, 'piid': 21}, 'yl_light.mode_two_ct': {'siid': 3, 'piid': 22}, 'yl_light.mode_three_bright': {'siid': 3, 'piid': 23}, 'yl_light.mode_three_ct': {'siid': 3, 'piid': 24}, 'yl_light.mode_four_bright': {'siid': 3, 'piid': 25}, 'yl_light.mode_four_ct': {'siid': 3, 'piid': 26}, 'yl_light.ble_paired_mac': {'siid': 3, 'piid': 27}, 'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.default_power_on_state': {'siid': 2, 'piid': 4}, 'light.mode': {'siid': 2, 'piid': 5}}, max_properties: 9/27

家中目前只有这一个正常连接的小米设备，貌似是在轮询查询状态时，时不时地报错（因为也看到有类似以下内容的日志，感觉像是有时候成功，有时候失败）

> 2025-03-24 16:14:31.705 INFO (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.lamp22] Device updated: {'light.light.on': True, 'light.brightness': 204.0, 'light.color_temperature': 3200, 'light.mode': None, 'only_info': False}
> 2025-03-24 16:14:31.709 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.yeelink_lamp22_f8e9_info: Entity state updated: 屏幕灯

目前已经做了的排查尝试

1. 自己动手微调了下代码，目前只能定位到是core/device.py 1394行 这里`self.get_properties(
            properties,
            property_getter='get_properties',
            max_properties=max_properties,
        )`报错DeviceException。

2. 又尝试手动套上ip和token，封装了个写了个miio Device用已经拼接好的`properties=[{'did': '581116169', 'siid': 3, 'piid': 1}, {'did': '581116169', 'siid': 3, 'piid': 2}, {'did': '581116169', 'siid': 3, 'piid': 4}, {'did': '581116169', 'siid': 3, 'piid': 6}, {'did': '581116169', 'siid': 3, 'piid': 7}, {'did': '581116169', 'siid': 3, 'piid': 8}, {'did': '581116169', 'siid': 3, 'piid': 9}, {'did': '581116169', 'siid': 3, 'piid': 13}, {'did': '581116169', 'siid': 3, 'piid': 14}, {'did': '581116169', 'siid': 3, 'piid': 15}, {'did': '581116169', 'siid': 3, 'piid': 16}, {'did': '581116169', 'siid': 3, 'piid': 17}, {'did': '581116169', 'siid': 3, 'piid': 18}, {'did': '581116169', 'siid': 3, 'piid': 19}, {'did': '581116169', 'siid': 3, 'piid': 20}, {'did': '581116169', 'siid': 3, 'piid': 21}, {'did': '581116169', 'siid': 3, 'piid': 22}, {'did': '581116169', 'siid': 3, 'piid': 23}, {'did': '581116169', 'siid': 3, 'piid': 24}, {'did': '581116169', 'siid': 3, 'piid': 25}, {'did': '581116169', 'siid': 3, 'piid': 26}, {'did': '581116169', 'siid': 3, 'piid': 27}, {'did': '581116169', 'siid': 2, 'piid': 1}, {'did': '581116169', 'siid': 2, 'piid': 2}, {'did': '581116169', 'siid': 2, 'piid': 3}, {'did': '581116169', 'siid': 2, 'piid': 4}, {'did': '581116169', 'siid': 2, 'piid': 5}]`和同样的`max_properties=9` `.get_properties(properties=properties, property_getter='get_properties', max_properties=9)`请求去查询状态，是能正常查到返回的状态value的 `[{'did': '581116169', 'siid': 3, 'piid': 1, 'code': 0, 'value': True}, {'did': '581116169', 'siid': 3, 'piid': 2, 'code': 0, 'value': 15}, {'did': '581116169', 'siid': 3, 'piid': 4, 'code': 0, 'value': False}, {'did': '581116169', 'siid': 3, 'piid': 6, 'code': 0, 'value': False}, {'did': '581116169', 'siid': 3, 'piid': 7, 'code': 0, 'value': 1}, {'did': '581116169', 'siid': 3, 'piid': 8, 'code': 0, 'value': True}, {'did': '581116169', 'siid': 3, 'piid': 9, 'code': 0, 'value': 0}, {'did': '581116169', 'siid': 3, 'piid': 13, 'code': 0, 'value': 9}, {'did': '581116169', 'siid': 3, 'piid': 14, 'code': 0, 'value': 8}, {'did': '581116169', 'siid': 3, 'piid': 15, 'code': 0, 'value': 5}, {'did': '581116169', 'siid': 3, 'piid': 16, 'code': 0, 'value': 45}, {'did': '581116169', 'siid': 3, 'piid': 17, 'code': 0, 'value': 10}, {'did': '581116169', 'siid': 3, 'piid': 18, 'code': 0, 'value': False}, {'did': '581116169', 'siid': 3, 'piid': 19, 'code': 0, 'value': 50}, {'did': '581116169', 'siid': 3, 'piid': 20, 'code': 0, 'value': 4000}, {'did': '581116169', 'siid': 3, 'piid': 21, 'code': 0, 'value': 100}, {'did': '581116169', 'siid': 3, 'piid': 22, 'code': 0, 'value': 2700}, {'did': '581116169', 'siid': 3, 'piid': 23, 'code': 0, 'value': 30}, {'did': '581116169', 'siid': 3, 'piid': 24, 'code': 0, 'value': 5000}, {'did': '581116169', 'siid': 3, 'piid': 25, 'code': 0, 'value': 60}, {'did': '581116169', 'siid': 3, 'piid': 26, 'code': 0, 'value': 3000}, {'did': '581116169', 'siid': 3, 'piid': 27, 'code': 0, 'value': 'ec:4d:3e:01:af:3a'}, {'did': '581116169', 'siid': 2, 'piid': 1, 'code': 0, 'value': True}, {'did': '581116169', 'siid': 2, 'piid': 2, 'code': 0, 'value': 80}, {'did': '581116169', 'siid': 2, 'piid': 3, 'code': 0, 'value': 3200}, {'did': '581116169', 'siid': 2, 'piid': 4, 'code': 0, 'value': True}, {'did': '581116169', 'siid': 2, 'piid': 5, 'code': 0, 'value': 0}]`，但是不好说这个情况是不是偶发的。

3. 尝试在请求将device的timeout延长设为10，可是没有找到Device类可以调控的参数变量，貌似miio包不支持更改timeout？（也可能是我找错地方了，欢迎指正）， 另外，在miio的[issue](https://github.com/rytilahti/python-miio/issues/1969)中看到有人有遇到类似的情况，yeelink的灯timeout，miio的作者推荐调整max_properties

4. 设置根据`self._local_fails`来动态调整`max_properties = max_properties - self._local_fails - 1`, 跑了半个多小时，最多一次失败轮数为失败3次（再下一次改为了max_properties=5就成功了）

![Image](https://github.com/user-attachments/assets/e048b070-f899-47bb-9acc-32c228fa2108)

求大佬指教，这个思路正确吗？除了max_properties还有别的方法吗？

### Entity attributes / 实体属性

```yaml
button.info: 屏幕灯
model: yeelink.light.lamp22
did: 581116169
mac: CC:B5:D1:02:F8:E9
lan_ip: 192.168.1.100
app_link: mihome://device?uid=1083249715&did=581116169
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-lamp22:1:0000C802
available: true
home_room: 我的家庭 客厅
icon: mdi:information
updater: local
updated_at: 2025-03-24 18:23:54.257487+11:00
yl_light.save_state: true
yl_light.delay_time: 15
yl_light.delay_off_enable: false
yl_light.double_click_enable: false
yl_light.double_click: 1
yl_light.long_press_enable: true
yl_light.scene_mode: 0
yl_light.long_press_one: 9
yl_light.long_press_two: 8
yl_light.long_press_three: 5
yl_light.work_minutes: 45
yl_light.break_minutes: 10
yl_light.pomodoro_enable: false
yl_light.mode_one_bright: 50
yl_light.mode_one_ct: 4000
yl_light.mode_two_bright: 100
yl_light.mode_two_ct: 2700
yl_light.mode_three_bright: 30
yl_light.mode_three_ct: 5000
yl_light.mode_four_bright: 60
yl_light.mode_four_ct: 3000
yl_light.ble_paired_mac: ec:4d:3e:01:af:3a
light.on: false
light.brightness: 80
light.color_temperature: 3200
light.default_power_on_state: true
light.mode: 0
converters: button.info, light.light.on, light.brightness, light.color_temperature, light.mode, button.light.toggle
customizes: 
number_properties: off_delay_time,light_on_gradient_time,light_off_gradient_time
switch_properties: bg_on,init_power_opt,fan_init_power_opt
button_actions: toggle
chunk_coordinators: []
interval_seconds: 20

info: null
device_class: update
friendly_name: 屏幕灯 信息
```

### Home Assistant Logs / 系统日志

[home-assistant_xiaomi_miot_2025-03-24T10-30-42.122Z.log](https://github.com/user-attachments/files/19427930/home-assistant_xiaomi_miot_2025-03-24T10-30-42.122Z.log)
