### ISSUE TITLE
xtl.vacuum.xm2216 timeout

### ISSUE THREAD

**Issue by fw23git** [al-one/hass-xiaomi-miot#2437]
### Device model / 设备型号

xtl.vacuum.xm2216

### Component version / 插件版本

1.0.15

### HA core version / HA版本

2025.3.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

possibly related to a firmware update

### Entity attributes / 实体属性

```yaml
button.info: JONR
model: xtl.vacuum.xm2216
did: 
mac: 44:87:63:58:a3:e6
lan_ip: 192.168.1.217
app_link: 
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:xtl-xm2216:3
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-03-28 09:11:50.709497+01:00
vacuum.status: 13
state_updater: local
vacuum.status_desc: Charged
converters: button.info, sensor.battery_level, sensor.vacuum.status, number.robotic_vacuum.volume, button.vacuum.start_sweep, button.vacuum.stop_sweeping, button.vacuum.pause_sweeping, button.battery.start_charge, button.robotic_vacuum.reset_consumable
customizes: 
binary_sensor_properties: mop_status
sensor_properties: status
select_properties: mode,sweep_mop_type,sweep_type,suction_level,water_level,clean_times
number_properties: volume
button_actions: >-
  start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_*
configuration_entities: reset_*
diagnostic_entities: filter_l*,brush_l*,detergent_l*,dust_bag_l*
chunk_coordinators:
  - interval: 11
    props: status,charging_state
    notify: true
  - interval: 16
    props: mode,sweep_mop_type,sweep_type,suction_level,water_level
  - interval: 301
    props: filter_l*,brush_l*,detergent_l*,dust_bag_l*
auto_cloud: false
miot_cloud_action: true
miot_local: true
ignore_offline: true

info: null
device_class: update
friendly_name: JONR Info
```

### Home Assistant Logs / 系统日志

Got error when receiving: timed out

Got MiioException while fetching the state: No response from the device, mapping: {'battery_level': {'siid': 16, 'piid': 1}, 'robotic_vacuum.disturb_switch': {'siid': 17, 'piid': 1}, 'break_clean_switch-17-2': {'siid': 17, 'piid': 2}, 'robotic_vacuum.child_lock': {'siid': 17, 'piid': 6}, 'carpet_boost_switch-17-7': {'siid': 17, 'piid': 7}, 'clean_type_status-17-9': {'siid': 17, 'piid': 9}, 'robotic_vacuum.clean_mode': {'siid': 17, 'piid': 10}, 'carpet_clean_prefer-17-11': {'siid': 17, 'piid': 11}, 'robotic_vacuum.water_mode': {'siid': 17, 'piid': 12}, 'robotic_vacuum.fan_mode': {'siid': 17, 'piid': 13}, 'robotic_vacuum.clean_count': {'siid': 17, 'piid': 14}, 'robotic_vacuum.volume': {'siid': 17, 'piid': 15}, 'robotic_vacuum.scheduled_timers': {'siid': 17, 'piid': 17}, 'robotic_vacuum.disturb_time': {'siid': 17, 'piid': 19}, 'dust_collection_freq-17-20': {'siid': 17, 'piid': 20}, 'robotic_vacuum.drying_switch': {'siid': 17, 'piid': 21}, 'robotic_vacuum.drying_time': {'siid': 17, 'piid': 22}, 'mop_wash_frequency-17-23': {'siid': 17, 'piid': 23}, 'robotic_vacuum.time_zone': {'siid': 17, 'piid': 24}, 'robotic_vacuum.language_voice': {'siid': 17, 'piid': 25}, 'robotic_vacuum.clean_time': {'siid': 17, 'piid': 26}, 'robotic_vacuum.clean_area': {'siid': 17, 'piid': 27}, 'robotic_vacuum.battery': {'siid': 17, 'piid': 28}, 'robotic_vacuum.clean_area_total': {'siid': 17, 'piid': 29}, 'clean_count_total-17-30': {'siid': 17, 'piid': 30}, 'robotic_vacuum.clean_time_total': {'siid': 17, 'piid': 31}, 'robotic_vacuum.consumables': {'siid': 17, 'piid': 32}, 'robotic_vacuum.clean_values': {'siid': 17, 'piid': 34}, 'robotic_vacuum.error': {'siid': 17, 'piid': 35}, 'robotic_vacuum.message': {'siid': 17, 'piid': 36}, 'robotic_vacuum.save_map_switch': {'siid': 17, 'piid': 39}, 'robotic_vacuum.erp_switch': {'siid': 17, 'piid': 42}, 'mop_augment_switch-17-43': {'siid': 17, 'piid': 43}, 'auto_solution_switch-17-44': {'siid': 17, 'piid': 44}, 'robotic_vacuum.mop_wash_temp': {'siid': 17, 'piid': 45}, 'robotic_vacuum.clean_records': {'siid': 17, 'piid': 46}, 'multifloor_switch-17-47': {'siid': 17, 'piid': 47}, 'robotic_vacuum.return_status': {'siid': 17, 'piid': 48}, 'robotic_vacuum.robot_status': {'siid': 17, 'piid': 49}, 'auto_water_change-17-50': {'siid': 17, 'piid': 50}, 'clean_water_cistern-17-51': {'siid': 17, 'piid': 51}, 'robotic_vacuum.drain_cistern': {'siid': 17, 'piid': 52}, 'robotic_vacuum.dust_bag': {'siid': 17, 'piid': 53}, 'robotic_vacuum.mop_clean_tank': {'siid': 17, 'piid': 54}, 'robotic_vacuum.expanded_map': {'siid': 17, 'piid': 64}, 'robotic_vacuum.fine_drag': {'siid': 17, 'piid': 65}, 'robotic_vacuum.aw_check_data': {'siid': 17, 'piid': 66}, 'robotic_vacuum.aw_check_sign': {'siid': 17, 'piid': 72}, 'carpet_cleantwice-17-74': {'siid': 17, 'piid': 74}, 'carpet_cleanchoice-17-75': {'siid': 17, 'piid': 75}, 'room_edite_result-17-76': {'siid': 17, 'piid': 76}, 'robotic_vacuum.language_ver': {'siid': 17, 'piid': 78}, 'robotic_vacuum.station_error': {'siid': 17, 'piid': 79}}, max_properties: 10/53
