### ISSUE TITLE
Xiaomi Smart Air Fryer 4.5L modes

### ISSUE THREAD

**Issue by jonicunha** [al-one/hass-xiaomi-miot#2439]
### Device model / 设备型号

xiaomi.fryer.maf14

### Component version / 插件版本

1.0.15

### HA core version / HA版本

2025.4.0b5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi,

I have a Xiaomi Smart Air Fryer 4.5L - xiaomi.fryer.maf14 - but the modes are in a different order than https://home.miot-spec.com/spec/xiaomi.fryer.maf14 (PIID 5).

The order of the modes of my xiaomi.fryer.maf14 are:
    Manual = 0
    FrenchFries = 1
    ChickenWing = 2
    Steak = 3
    Fish = 4
    Shrimp = 5
    Vegetables = 6
    Cake = 7
    Defrost = 8
    DriedFruit = 9
    Yogurt = 10

Is it possible to fix it or is it possible for me to change the names in this list?

Thank you!

### Entity attributes / 实体属性

```yaml
Entity:
- select.xiaomi_maf14_920f_mode

State:
- Defrost

Attributes:
- options: Manual, Chicken Wing, Steak , Fish, French Fries, Cake, Defrost, Dried Fruit, Yogurt, Shrimp, Vegetables 
- friendly_name: Xiaomi Smart Air Fryer 4.5L Mode
- air_fryer.mode: 6
```
