### ISSUE TITLE
(xiaomi.tv.rmh1) TV meets a auto reboot issue

### ISSUE THREAD

**Issue by xiaolong51996** [al-one/hass-xiaomi-miot#2453]
### Device model / 设备型号

device.xiaomi.tv.rmh1

### Component version / 插件版本

1.0.16

### HA core version / HA版本

2025.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

xiaomi_rmh1_6b45_play_control makes my RedmiTV Reboot repeatedly.
After disabled xiaomi_rmh1_6b45_play_control , the TV gets normal.
当添加电视设备后，造成电视机不断自动重启，禁用xiaomi_rmh1_6b45_play_control后，电视机不再自动重启。

### Entity attributes / 实体属性

```yaml
button.info: 电视
model: xiaomi.tv.rmh1
did: X
mac: X
lan_ip: 192.168.123.86
app_link: mihome://device?uid=690993170&did=613815048
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-rmh1:2
available: true
home_room: X
icon: mdi:information
updater: local
updated_at: "2025-04-12 11:19:24.952417+08:00"
television.input_control: 1
play_control.playing_state: 0
speaker.volume: 100
speaker.mute: false
remote_control.state_playing: false
remote_control.play_info: >-
  eyJwb3NpdGlvbiI6LTEsImR1cmF0aW9uIjowLCJtZWRpYUlkIjoiIiwibWVkaWFOYW1lIjoiIiwicWlQdUlkIjoiIiwiYWxidW1RaVB1SWQiOiIifQ==
screenshot_result-7-3: ""
remote_control.progress_avail: true
remote_control.screenshot_avail: true
voicecontrol_avail-7-8: true
speaker_mode.is_on: false
state_updater: cloud
6095_state: false
converters:
  - button.info
  - switch.speaker_mode.is_on
  - number.speaker.volume
  - text.message_router.post
customizes:
  auto_cloud: true
  switch_properties: is_on
  number_properties: speaker.volume
  text_actions: message_router.post
info: null
device_class: update
friendly_name: 电视 信息
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.device.xiaomi.tv.rmh1
来源: custom_components/xiaomi_miot/core/device.py:911
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 11:12:00 (2 次总计出现)
上次记录: 11:12:21

Got MiioException while fetching the state: Unable to discover the device 192.168.123.86, mapping: {'television.input_control': {'siid': 2, 'piid': 1}, 'play_control.playing_state': {'siid': 3, 'piid': 1}, 'speaker.volume': {'siid': 4, 'piid': 1}, 'speaker.mute': {'siid': 4, 'piid': 2}, 'remote_control.state_playing': {'siid': 7, 'piid': 1}, 'remote_control.play_info': {'siid': 7, 'piid': 2}, 'screenshot_result-7-3': {'siid': 7, 'piid': 3}, 'remote_control.progress_avail': {'siid': 7, 'piid': 6}, 'remote_control.screenshot_avail': {'siid': 7, 'piid': 7}, 'voicecontrol_avail-7-8': {'siid': 7, 'piid': 8}, 'speaker_mode.is_on': {'siid': 8, 'piid': 1}}, max_properties: 6/11
