### ISSUE TITLE
viomi.aircondition.y112 - uv switch became inactive

### ISSUE THREAD

**Issue by Nikznah** [al-one/hass-xiaomi-miot#2464]
### Device model / 设备型号

viomi.aircondition.y112 / VIOMI Cross 9000BTU

### Component version / 插件版本

1.0.16

### HA core version / HA版本

2025.3.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hello everyone! I use 
VIOMI Cross 9000BTU in automation, after the last update the ultraviolet button became inactive, although such a function exists

### Entity attributes / 实体属性

```yaml
switch.viomi_y112_88c1_uv
unavailable
restored: true
friendly_name: UL
supported_features: 0
```
