### ISSUE TITLE
viomi.vacuum.v7 map

### ISSUE THREAD

**Issue by olaulau** [al-one/hass-xiaomi-miot#2466]
### Device model / 设备型号

viomi.vacuum.v7

### Component version / 插件版本

1.0.16

### HA core version / HA版本

2025.4.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

missing feature :
- get current map name
- set map

### Entity attributes / 实体属性

```yaml
button.info: Robot aspirateur
model: viomi.vacuum.v7
did: 308778309
mac: 5C:E5:0C:7A:1F:B9
lan_ip: 192.168.2.247
app_link: mihome://device?uid=6240267797&did=308778309
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:viomi-v7:2
available: true
home_room: maison laulau chambre 1
icon: mdi:information
updater: local
updated_at: 2025-04-18 01:32:07.348333+02:00
vacuum.mode: 1
vacuum.status: 6
battery_level: 100
viomi_vacuum.main_brush_life: 0
viomi_vacuum.side_brush_life: 0
viomi_vacuum.hypa_life: 0
viomi_vacuum.mop_life: 32
state_updater: local
vacuum.status_desc: Charging
miio.run_state: 5
miio.mode: 0
miio.err_state: 2105
miio.battary_life: 100
miio.box_type: 1
miio.mop_type: 0
miio.s_time: 0
miio.s_area: 0
miio.suction_grade: 2
miio.water_grade: 13
miio.remember_map: 1
miio.has_map: 1
miio.is_mop: 0
miio.has_newmap: 0
clean_area: 0
clean_time: 0
converters: button.info, sensor.battery_level, sensor.vacuum.status, sensor.viomi_vacuum.main_brush_life, sensor.viomi_vacuum.side_brush_life, sensor.viomi_vacuum.hypa_life, sensor.viomi_vacuum.mop_life, select.vacuum.mode, button.vacuum.start_sweep, button.vacuum.stop_sweeping, button.vacuum.start_sweep_mop, button.vacuum.start_mop, button.vacuum.pause_sweeping, button.battery.start_charge, sensor.clean_area, sensor.clean_time
customizes: 
binary_sensor_properties: mop_status
sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life
select_properties: mode,sweep_mop_type,sweep_type,suction_level,water_level,clean_times
number_properties: volume
button_actions: >-
  start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_*
configuration_entities: reset_*
diagnostic_entities: filter_l*,brush_l*,detergent_l*,dust_bag_l*
chunk_coordinators:
  - interval: 11
    props: status,charging_state
    notify: true
  - interval: 16
    props: mode,sweep_mop_type,sweep_type,suction_level,water_level
  - interval: 301
    props: filter_l*,brush_l*,detergent_l*,dust_bag_l*
sensor_attributes: clean_area,clean_time

info: null
device_class: update
friendly_name: Robot aspirateur Info
```
