### ISSUE TITLE
Qingping Air Monitor Lite - Some devices cannot be connected in the LAN

### ISSUE THREAD

**Issue by StrafeBink** [al-one/hass-xiaomi-miot#2475]
### Device model / 设备型号

Qingping Air Monitor Lite

### Component version / 插件版本

1.0.17

### HA core version / HA版本

2025.4.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Air monitor is connected to WiFi and is being assigned an IP address, through the QingPing+ application I can see it is working. However, cannot get sensor data through Home Assistant. The error message below from Home Assistant.

Devices Offline
Some devices cannot be connected in the LAN, please check their IP and make sure they are in the same subnet as the HA.

一些设备无法通过局域网连接，请检查它们的IP，并确保它们和HA在同一子网。

    Qingping Air Monitor Lite(cgllc.airm.cgd1st): 192.168.1.236

### Entity attributes / 实体属性

```yaml
button.info: Qingping Air Monitor Lite
model: cgllc.airm.cgd1st
did: 531563220
mac: 7C:C2:94:C9:40:D4
lan_ip: 192.168.1.236
app_link: mihome://device?uid=1704513858&did=531563220
miot_type: urn:miot-spec-v2:device:air-monitor:0000A008:cgllc-cgd1st:1
available: false
home_room: 1704513858 Master bedroom
icon: mdi:information-off
updater: none
updated_at: 
converters: button.info, sensor.environment.temperature, sensor.environment.relative_humidity, sensor.environment.pm2_5_density, sensor.environment.pm10_density, sensor.environment.co2_density, sensor.battery_level, sensor.battery.voltage, sensor.battery.charging_state
customizes: 
exclude_miot_services: mac,settings

miot_error: Unable to discover the device 192.168.1.236
info: null
device_class: update
friendly_name: Qingping Air Monitor Lite Info
```
