### ISSUE TITLE
hyd.airer.znlyj2上的灯实体不可用

### ISSUE THREAD

**Issue by CHINAshanonline** [al-one/hass-xiaomi-miot#2477]
### Device model / 设备型号

[hyd.airer.znlyj2](https://home.miot-spec.com/s/hyd.airer.znlyj2)

### Component version / 插件版本

1.0.17

### HA core version / HA版本

2025.4.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

1.0.15版本下hyd.airer.znlyj2上的灯实体可用，升级到1.0.16及1.0.17版本后hyd.airer.znlyj2上的灯实体变为不可用，晾衣架的升降功能一直可用

### Entity attributes / 实体属性

```yaml
button.info: Mijia Smart Clothes Drying Rack
model: hyd.airer.znlyj2
did: xxxxxxxxx
mac: XX:XX:XX:XX:XX:XX
lan_ip: XX.XX.XX.XX
app_link: mihome://device?uid=xxxx &did=xxx 
miot_type: urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj2:2
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-04-24 10:07:06.675647+08:00
airer.current_position: 1
airer.status.error: -4004 Other internal errors
airer.fault: 0
light.on.error: -4004 Other internal errors
converters: button.info, light.light.on, cover.airer.motor_control, airer.status, airer.motor_control, airer.current_position
customizes: 
sensor_properties: left_time
switch_properties: uv
select_properties: mode,dryer
chunk_coordinators:
  - interval: 15
    props: status,current_position,target_position,dryer,drying_level
number_properties: drying_time
exclude_miot_properties: motor_control
cover_position_mapping:
  '0': 50
  '1': 100
  '2': 0

info: null
device_class: update
friendly_name: Mijia Smart Clothes Drying Rack 信息
```

### Home Assistant Logs / 系统日志

2025-04-24 10:11:33.932 INFO (MainThread) [custom_components.xiaomi_miot.core.device.hyd.airer.znlyj2] Device updated: {'only_info': False}
2025-04-24 10:11:33.933 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] button.hyd_znlyj2_e3df_info: Entity state updated: Mijia Smart Clothes Drying Rack
2025-04-24 10:11:33.933 DEBUG (MainThread) [custom_components.xiaomi_miot.core.coordinator] Mijia Smart Clothes Drying Rack(hyd.airer.znlyj2): Coordinator updated: ['58:b6:23:ef:e3:df-d0512e489b7460d32e961565252fa172-miot_status', [{'did': 'xxxxxxxxx', 'siid': 2, 'piid': 1, 'code': 0, 'value': 0}, {'did': 'xxxxxxxxx', 'siid': 3, 'piid': 1, 'code': -4004}]]
