### ISSUE TITLE
Yeelight LED Lightstrip 1S fails to change the color

### ISSUE THREAD

**Issue by Tiktack** [al-one/hass-xiaomi-miot#2480]
### Device model / 设备型号

yeelink.light.strip6

### Component version / 插件版本

1.0.17

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Firmware: 2.1.7_0020
Brightness and temperature works fine, but color change doesn't work. 
Would be nice if anyone could fix that.
It gives an error: 

![Image](https://github.com/user-attachments/assets/ab02a73a-beee-4748-84b1-05edbf11b325)

### Entity attributes / 实体属性

```yaml
button.info: Yeelight LED Lightstrip 1S
model: yeelink.light.strip6
did: "360344341"
mac: XXX
lan_ip: 192.168.0.XX
app_link: mihome://device?uid=6395145038&did=360344341
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-strip6:3
available: true
home_room: XXX
icon: mdi:information
updater: local
updated_at: "2025-04-26 20:58:30.869515+02:00"
light.on: true
light.brightness: 46
light.color: 16711680
converters:
  - button.info
  - light.light.on
  - light.brightness
  - light.color_temperature
  - light.color
  - button.light.toggle
customizes:
  number_properties: off_delay_time,light_on_gradient_time,light_off_gradient_time
  switch_properties: bg_on,init_power_opt,fan_init_power_opt
  button_actions: toggle
  chunk_coordinators: []
  interval_seconds: 20
info: null
device_class: update
friendly_name: Yeelight LED Lightstrip 1S Info
```

### Home Assistant Logs / 系统日志

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 648, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/xiaomi_miot/light.py", line 156, in async_turn_on
    await self.device.async_write(dat)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 701, in async_write
    data = self.encode(payload)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 696, in encode
    conv.encode(self, payload, v)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/converters.py", line 240, in encode
    super().encode(device, payload, MiotRgbColorConv.rgb_to_int(rgb))
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/config/custom_components/xiaomi_miot/core/converters.py", line 244, in rgb_to_int
    num = int(rgb[0]) << 16 | int(rgb[1]) << 8 | int(rgb[3])
                                                     ~~~^^^
IndexError: tuple index out of range

Edited: 
Any color change produces error ( tried from palette and from predefined). 
Color change works fine in native Xiaomi Home application.
