### ISSUE TITLE
tts调用 小米音箱pro 不断重复

### ISSUE THREAD

**Issue by lazybabyz** [al-one/hass-xiaomi-miot#2485]
### Device model / 设备型号

xiaomi.wifispeaker.lx06

### Component version / 插件版本

1.0.17

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

edge-tts
tts.google_translate_say
tts调用 小米音箱pro 无论是自动化还是开发者工具 播出后不断重复 

自动化代码
action: tts.xiaomo_say
data:
  entity_id: media_player.xiaomi_lx06_aa92_play_control
  message: test

### Entity attributes / 实体属性

```yaml
media_player.xiaomi_lx06_aa92_play_control
```

**Comment by al-one** [comment]
使用集成自带的tts:
```
action: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaoai_lx04_xxxx
  text: TTS内容
  execute: false # 执行指令
  silent: false  # 静默执行
```
