### ISSUE TITLE
苹果 home设置空调风速，会触发仅送风模式

### ISSUE THREAD

**Issue by hoganwang** [al-one/hass-xiaomi-miot#2489]
### Device model / 设备型号

qdhkl.aircondition.ac

### Component version / 插件版本

1.0.18

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

空调控制器用Xiaomi Miot Auto 集成，将米家空调控制器添加到 homeassistant 里面，然后是用 homekit bridge 添加到苹果 home 里面。再苹果 home 里面设置空调风速的时候，会突然把模式切换到送风。

### Entity attributes / 实体属性

```yaml
button.info: 主卧空调
model: qdhkl.aircondition.ac
did: proxy.749686446.0102
mac: proxy.749686446.0102
lan_ip: 
app_link: mihome://device?uid=1621678202&did=proxy.749686446.0102
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:qdhkl-ac:2
available: true
home_room: 杭州 主卧
icon: mdi:information
updater: local
updated_at: 2025-05-02 18:49:03.400586+08:00
air_conditioner.on: false
air_conditioner.mode: 4
target_temperature-2-4: 22
fan_control.fan_level: 4
air_conditioner.fault: 0
environment.temperature: 28
converters: button.info, climate.air_conditioner.mode, air_conditioner.on, target_temperature-2-4, environment.temperature, air_conditioner.mode, fan_control.fan_level, sensor.environment.temperature, switch.air_conditioner.on, select.fan_control.fan_level
customizes: 
sensor_properties: electricity.electricity
switch_properties: air_conditioner.on
select_properties: fan_level
number_properties: target_humidity
fan_services: air_fresh
chunk_coordinators:
  - interval: 10
    props: on,mode,target_temperature,fan_level
    notify: true

info: null
device_class: update
friendly_name: 主卧空调 信息
```

### Home Assistant Logs / 系统日志

2025-05-02 04:43:55.694 DEBUG (MainThread) [homeassistant.components.homekit.type_thermostats] climate.qdhkl_ac_0102_air_conditioner: Set fan speed to 66.66666666666667
2025-05-02 04:43:55.695 INFO (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Device write data: [{'air_conditioner.on': True, 'air_conditioner.mode': '送风', 'fan_control.fan_level': 'medium'}, {'method': 'set_properties', 'params': [{'siid': 2, 'piid': 1, 'did': 'proxy.749686446.0102', 'value': True}, {'siid': 2, 'piid': 2, 'did': 'proxy.749686446.0102', 'value': 4}, {'siid': 3, 'piid': 2, 'did': 'proxy.749686446.0102', 'value': 2}]}]
2025-05-02 04:43:55.696 DEBUG (MainThread) [pyhap.accessory_driver] Send event: topic(2729130570.16), data({'aid': 2729130570, 'iid': 16, 'value': 66.66666666666667}), sender_client_addr(('192.168.10.189', 49179))
2025-05-02 04:43:55.696 DEBUG (MainThread) [pyhap.accessory_driver] Skip sending event to client since its the client that made the characteristic change: ('192.168.10.189', 49179)
2025-05-02 04:43:55.699 DEBUG (MainThread) [pyhap.hap_protocol] ('192.168.10.189', 49179) (333110f4-d730-4c48-961c-aeb9bebd8c96): Send encrypted: b'HTTP/1.1 204 No Content\r\n\r\n'
2025-05-02 04:43:55.700 DEBUG (MainThread) [pyhap.hap_protocol] ('192.168.10.189', 49179) (333110f4-d730-4c48-961c-aeb9bebd8c96): h11 Event: NEED_DATA
2025-05-02 04:43:56.053 INFO (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Device write result: [{'air_conditioner.on': True, 'air_conditioner.mode': '送风', 'fan_control.fan_level': 'medium'}, [{'did': 'proxy.749686446.0102', 'siid': 2, 'piid': 1, 'code': 0}, {'did': 'proxy.749686446.0102', 'siid': 2, 'piid': 2, 'code': 0}, {'did': 'proxy.749686446.0102', 'siid': 3, 'piid': 2, 'code': 0}]]
2025-05-02 04:43:56.053 INFO (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Device updated: {'air_conditioner.on': True, 'air_conditioner.mode': '送风', 'fan_control.fan_level': 'medium', 'only_info': False}
2025-05-02 04:43:56.055 DEBUG (MainThread) [custom_components.xiaomi_miot.core.hass_entity] climate.qdhkl_ac_0102_air_conditioner: Entity state updated: {'air_conditioner.on': True, 'air_conditioner.mode': '送风', 'fan_control.fan_level': 'medium'}
2025-05-02 04:43:56.055 DEBUG (MainThread) [homeassistant.components.homekit.accessories] New_state: <state climate.qdhkl_ac_0102_air_conditioner=fan_only; hvac_modes=[<HVACMode.OFF: 'off'>, <HVACMode.HEAT: 'heat'>, <HVACMode.COOL: 'cool'>, <HVACMode.DRY: 'dry'>, <HVACMode.FAN_ONLY: 'fan_only'>, <HVACMode.AUTO: 'auto'>], min_temp=16, max_temp=30, target_temp_step=1, fan_modes=['low', 'medium', 'high', 'auto'], preset_modes=['00'], current_temperature=24.0, temperature=22.0, fan_mode=medium, hvac_action=fan, preset_mode=None, target_temperature-2-4=22.0, air_conditioner.mode=4, fan_control.fan_level=4, air_conditioner.on=False, environment.temperature=24.0, friendly_name=主卧空调 空调, supported_features=409 @ 2025-05-02T04:43:56.054433+08:00>
2025-05-02 04:43:56.057 DEBUG (MainThread) [pyhap.characteristic] set_value: TargetHeatingCoolingState to 2
2025-05-02 04:43:56.057 DEBUG (MainThread) [pyhap.characteristic] set_value: CurrentHeatingCoolingState to 2
2025-05-02 04:43:56.057 DEBUG (MainThread) [pyhap.characteristic] set_value: CurrentTemperature to 24.0
2025-05-02 04:43:56.057 DEBUG (MainThread) [pyhap.characteristic] set_value: TargetTemperature to 22.0
2025-05-02 04:43:56.058 DEBUG (MainThread) [pyhap.characteristic] set_value: TemperatureDisplayUnits to 0
2025-05-02 04:43:56.058 DEBUG (MainThread) [pyhap.characteristic] set_value: Fan Mode to 66
2025-05-02 04:43:56.058 DEBUG (MainThread) [pyhap.characteristic] set_value: Fan Auto to 0
2025-05-02 04:43:56.058 DEBUG (MainThread) [pyhap.characteristic] set_value: Fan State to 2
2025-05-02 04:43:56.059 DEBUG (MainThread) [pyhap.characteristic] set_value: Active to 1
