### ISSUE TITLE
小米空气净化器接入后无法对设备进行控制。

### ISSUE THREAD

**Issue by jianguooo** [al-one/hass-xiaomi-miot#249]
<img width="1007" alt="QQ20211117-002052@2x" src="https://user-images.githubusercontent.com/16218132/142024541-70586c9a-e019-43a7-bd76-6eafd5a97e5c.png">
界面中的Air PurPurifier 无法进行操作

**Comment by al-one** [comment]
可以通过`climate`实体控制风速，你需要点开`Air Purifier`实体弹出框来控制。

**Comment by al-one** [comment]
你还可以通过[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)生成开关实体:
```yaml
# customize.yaml
climate.zhimi_v6_entity_id:
  switch_properties: on
```
