### ISSUE TITLE
there is no action

### ISSUE THREAD

**Issue by shurakenas** [al-one/hass-xiaomi-miot#2491]
### Device model / 设备型号

careli.fryer.maf10a

### Component version / 插件版本

1.0.18

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

the start_recipe_cook action is missing

### Entity attributes / 实体属性

```yaml
button.info: Xiaomi Smart Air Fryer 6.5L
model: careli.fryer.maf10a
did: "something"
mac: something
lan_ip: something
app_link: mihome://device?uid=something&did=something
miot_type: urn:miot-spec-v2:device:air-fryer:something:careli-maf10a:1
available: false
home_room: Кухня
icon: mdi:information-off
updater: none
updated_at: "2025-05-02 15:29:09.947420+03:00"
air_fryer.fault: 0
air_fryer.mode: 0
air_fryer.reservation_left_time: 0
air_fryer.status: 1
air_fryer.target_time: 15
air_fryer.target_temperature: 200
air_fryer.left_time: 15
air_fryer.auto_keep_warm: true
air_fryer.current_keep_warm: true
air_fryer.preheat: true
target_cooking_measure-2-13: 1
air_fryer.turn_pot: 1
air_fryer.turn_pot_config: true
air_fryer.texture: 0
air_fryer.cooking_weight: 500
converters:
  - button.info
  - sensor.air_fryer.status
  - air_fryer.fault
  - sensor.air_fryer.fault
  - sensor.air_fryer.left_time
  - switch.air_fryer.auto_keep_warm
  - switch.air_fryer.current_keep_warm
  - switch.air_fryer.preheat
  - switch.air_fryer.turn_pot_config
  - number.air_fryer.target_time
  - number.air_fryer.target_temperature
  - number.air_fryer.reservation_left_time
  - number.air_fryer.cooking_weight
  - select.air_fryer.mode
  - select.target_cooking_measure-2-13
  - select.air_fryer.turn_pot
  - select.air_fryer.texture
  - button.air_fryer.start_cook
  - button.air_fryer.cancel_cooking
  - button.air_fryer.pause
  - button.air_fryer.resume_cook
customizes:
  interval_seconds: 120
  button_actions: air_fryer.start_cook,pause,cancel_cooking,resume_cook
  sensor_properties: status,fault,left_time,appoint_time_left
  switch_properties: auto_keep_warm,current_keep_warm,preheat,turn_pot_cfg,turn_pot_config
  select_properties: mode,food_quanty,preheat_switch,turn_pot,texture,target_cooking_measure
  number_properties: >-
    target_time,target_temperature,appoint_time,reservation_left_time,cooking_weight
  exclude_miot_properties: recipe_id,recipe_name,recipe_sync
  chunk_coordinators:
    - interval: 20
      props: status,target_time,target_temperature,left_time
    - interval: 35
      props: fault,mode,appoint_time,reservation_left_time
  ignore_offline: true
info: null
device_class: update
friendly_name: Xiaomi Smart Air Fryer 6.5L Info
miot_error: Unable to discover the device something
```
