### ISSUE TITLE
Mijia Smart Clothes Drying Rack

### ISSUE THREAD

**Issue by aaastafyev** [al-one/hass-xiaomi-miot#2493]
### Device model / 设备型号

hyd.airer.znlyj4

### Component version / 插件版本

1.0.18

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Hi!

The down button does not work because it is inactive.
The up and stop buttons work.

![Image](https://github.com/user-attachments/assets/2eae84dd-1735-4efd-8e2b-de2995a8e6b7)

### Entity attributes / 实体属性

```yaml
current_position: 0
motor_reverse: null
position_reverse: true
closed_position: 2
deviated_position: 2
state_is_closed: false
airer.current_position: 1
device_class: shade
friendly_name: MijiaSmartClothesDryingRack Airer
supported_features: 11
```
