### ISSUE TITLE
Fan motor control 1-99% and not just 25/50/75/100%

### ISSUE THREAD

**Issue by plxflx** [al-one/hass-xiaomi-miot#2494]
### Device model / 设备型号

dmaker.fan.p18

### Component version / 插件版本

1.0.18

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Fan motor can not be set freely. Fan motor can only be set in steps of 25% (0/25/50/75/100) from HA. In Xiaomi Home app fan motor can be set to any number between 1 and 100 so there is not a device restriction.
A year ago this was not a problem but I do not know what version I used then so this have worked before.

### Entity attributes / 实体属性

```yaml
button.info: Mi Smart Standing Fan 2
model: dmaker.fan.p18
did: 
mac: 
lan_ip: 
app_link: 
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p18:1
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-05-04 13:32:13.220450+02:00
fan.on: false
fan.fan_level: 1
fan.mode: 0
fan.speed_level: 1
fan.horizontal_swing: false
fan.off_delay_time: 0
fan.horizontal_angle: 30
fan.brightness: true
fan.alarm: false
physical_controls_locked: false
converters: button.info, fan.fan.on, fan.on, fan.fan_level, fan.horizontal_swing, fan.mode, switch.physical_controls_locked, switch.fan.horizontal_swing, switch.fan.alarm, number.fan.off_delay_time, select.fan.horizontal_angle
customizes: 
button_actions: turn_left,turn_right
number_properties: off_delay_time
switch_properties: alarm,horizontal_swing,vertical_swing
chunk_coordinators:
  - interval: 16
    props: on,mode,fan_level,speed_level
  - interval: 21
    props: off_delay_time,horizontal_swing*
interval_seconds: 90
number_select_properties: >-
  horizontal_swing_included_angle,horizontal_angle,vertical_swing_included_angle,vertical_angle
exclude_miot_properties: natural_*

info: null
device_class: update
friendly_name: Mi Smart Standing Fan 2 Info
```
