### ISSUE TITLE
Thermostat custom fields are not working (heatold subtopic)

### ISSUE THREAD

**Issue by Sol1in** [al-one/hass-xiaomi-miot#2496]
### Device model / 设备型号

[cubee.airrtc.th123e](https://home.miot-spec.com/s/cubee.airrtc.th123e)

### Component version / 插件版本

1.0.18

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

I use HeatCold thermostat to control electric heat floor. After upgrade to version 1.x of the component all customizations stoped working. Now I see that current temperature is 14 instead of 25 and tempactivate/tempcomp properties are not displayed. Seems like customization of device stoped working properly.

Here is info:
```yaml
icon: mdi:information
device_class: update
friendly_name: Теплый пол в Ванной Info
button.info: Теплый пол в Ванной
model: cubee.airrtc.th123e
did: 
mac: 54:48:E6:52:BF:BE
lan_ip: 192.168.0.102
app_link: 
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:cubee-th123e:1
available: true
home_room: 
updater: local
updated_at: 2025-05-04 18:18:04.105043+03:00
thermostat.on: false
thermostat.mode: 0
thermostat.target_temperature: 26
thermostat.status: 0
thermostat.temperature: 14
heatold.childlock: false
heatold.tempactivate: 2
heatold.tempcomp: -9
heatold.tempfloor: 25
converters: button.info, climate.thermostat.mode, thermostat.on, thermostat.target_temperature, thermostat.temperature, thermostat.mode, switch.heatold.childlock, select.heatold.tempactivate, select.heatold.tempcomp
customizes: 
switch_properties: heatold.childlock
chunk_coordinators:
  - interval: 10
    notify: true
    props: on,mode,target_temperature,fan_level
chunk_properties: '1'
select_properties: heatold.tempactivate,heatold.tempcomp
exclude_miot_properties: fault,sensortype,maxsettemp,minsettemp
current_temp_property: heatold.tempfloor

info: null
```

Here is customization (tried different ways, with no success):
```yaml
chunk_coordinators:
  - interval: 10
    notify: true
    props: on,mode,target_temperature,fan_level
chunk_properties: "1"
current_temp_property: tempfloor
exclude_miot_properties: fault,sensortype,maxsettemp,minsettemp
select_properties: tempactivate,tempcomp
switch_properties: childlock
````

### Entity attributes / 实体属性

```yaml
hvac_modes: off, auto
min_temp: 0
max_temp: 90
target_temp_step: 1
preset_modes: Inhome, Outhome, Smart, Sleep
friendly_name: Теплый пол в Ванной
supported_features: 401
current_temperature: 14
temperature: 26
hvac_action: off
preset_mode: null
thermostat.mode: 0
thermostat.target_temperature: 26
thermostat.on: false
thermostat.temperature: 14
```
