### ISSUE TITLE
hass-xiaomi-miot ❤️ mini-media-player

### ISSUE THREAD

**Issue by al-one** [al-one/hass-xiaomi-miot#250]
[`mini-media-player`](https://github.com/kalkih/mini-media-player)是一个优秀的播放器卡片，可以用于本插件接入HA的小爱音箱和小米电视。该卡片在 https://github.com/kalkih/mini-media-player/pull/569 中新增支持了使用任意服务TTS（未发布，预计`v1.15`），可结合本插件TTS到小米音箱或执行语音命令。具体卡片配置如下：
```yaml
type: custom:mini-media-player
entity: media_player.xiaoai_entity_id
tts:
  platform: service
  data:
    message_filed: text
    service: xiaomi_miot.intelligent_speaker
    service_data:
      execute: true # 执行语音命令 false为朗读文本(TTS)
      silent: true  # 静默执行 小爱音响不回应执行结果
```

**Comment by al-one** [comment]
再分享一个模仿群友 [@chuixue](https://bbs.hassbian.com/?48072) 制作的小米/Redmi电视卡片。

- 首先需要通过[Generic Camera](https://www.home-assistant.io/integrations/generic)生成一个电视截图的`camera`实体：
```yaml
camera:
  # https://www.home-assistant.io/integrations/generic
  - platform: generic
    name: xiao_tv_screen # 电视截图实体ID为: camera.xiaomi_tv_screen
    still_image_url: |
      {{ state_attr('media_player.xiaomi_tv_xxxx','capture') }}
```

- 添加一个自定义卡片，粘贴一下代码：
```yaml
type: vertical-stack
cards:
  # 显示小米电视屏幕截图
  - type: picture-entity
    entity: select.xiaomi_tv_xxxx_keycodes # 小米电视通过本插件接入后都会生成该实体，替换成你的keycodes实体ID
    camera_image: camera.xiaomi_tv_screen  # 上一步生成的电视截图实体
    camera_view: live
    show_state: false
    show_name: false

  # 播放器及遥控按钮等
  - type: custom:mini-media-player
    entity: media_player.xiaomi_tv_xxxx # 换成你的小米电视实体ID
    hide:
      icon: true
    tts:
      platform: service
      data:
        message_filed: text
        service: xiaomi_miot.intelligent_speaker
        service_data:
          execute: true # 小米电视只支持语音命令 且不可静默执行
    shortcuts:
      columns: 4 # 四列按钮
      buttons:
        - type: service
          icon: mdi:home
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: home
        - type: service
          icon: mdi:arrow-up
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: up
        - type: service
          icon: mdi:menu
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: menu
        - type: service
          icon: mdi:home-assistant
          id: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaomi_tv_xxxx
            text: 打开米家
            execute: true
        - type: service
          icon: mdi:arrow-left
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: left
        - type: service
          icon: mdi:play-circle
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: enter
        - type: service
          icon: mdi:arrow-right
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: right
        - type: service
          icon: mdi:television-play
          id: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaoai_entity_id # 使用小爱打开电视
            text: 打开客厅小米电视
            execute: true
        - type: service
          icon: mdi:cog
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_app_current
            option: 电视设置 - com.xiaomi.mitv.settings
        - type: service
          icon: mdi:arrow-down
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: down
        - type: service
          icon: mdi:backspace
          id: select.select_option
          data:
            entity_id: select.xiaomi_tv_xxxx_keycodes
            option: back
        - type: service
          icon: mdi:television-off
          id: xiaomi_miot.intelligent_speaker
          data:
            entity_id: media_player.xiaomi_tv_xxxx
            text: 关闭屏幕
            execute: true
```

- 如果你的小米电视不支持小爱语音命令，可以指定小爱音响
```yaml
  - type: custom:mini-media-player
    entity: media_player.xiaomi_tv_xxxx # 小米电视实体ID
    hide:
      icon: true
    tts:
      platform: service
      data:
        message_filed: text
        service: xiaomi_miot.intelligent_speaker
        service_data:
          entity_id: media_player.xiaoai_entity_id # 小爱音箱实体ID
          execute: true # 执行语音命令
          silent: true  # 静默执行
```

效果如下：
![小米电视](https://user-images.githubusercontent.com/4549099/142363434-e1ff7ec5-1a49-47a4-a014-38edac5e14df.png)
