### ISSUE TITLE
Unexpected error fetching (xiaomi.sensor_occupy.p1)

### ISSUE THREAD

**Issue by tkhkbn** [al-one/hass-xiaomi-miot#2502]
### Device model / 设备型号

xiaomi.sensor_occupy.p1

### Component version / 插件版本

1.0.18

### HA core version / HA版本

2025.4.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

The device is working but keeps giving the following log from time to time.

### Entity attributes / 实体属性

```yaml
utton.info: Xiaomi Presence
model: xiaomi.sensor_occupy.p1
did: 
mac: C4:93:BB:9C:XX:XX
lan_ip: 192.168.1.XX
app_link: 
miot_type: urn:miot-spec-v2:device:occupancy-sensor:0000A0BF:xiaomi-p1:2
available: true
home_room: 
icon: mdi:information
updater: local
updated_at: 2025-05-09 15:16:59.345596+08:00
occupancy_status-2-1: 1
occupancy_status-4-1: 0
occupancy_status-5-1: 0
occupancy_status-6-1: 0
occupancy_status-7-1: 0
occupancy_status-8-1: 0
occupancy_status-9-1: 0
occupancy_status-10-1: 0
occupancy_status-11-1: 0
occupancy_status-12-1: 0
occupancy_status-13-1: 0
occupancy_status-14-1: 0
occupancy_status-15-1: 0
occupancy_status-16-1: 0
occupancy_status-17-1: 0
occupancy_status-18-1: 0
occupancy_status-19-1: 0
occupancy_status-20-1: 0
occupancy_status-21-1: 0
occupancy_status-22-1: 0
occupancy_status-23-1: 0
occupancy_status-24-1: 0
occupancy_status-25-1: 0
occupancy_status-26-1: 0
occupancy_status-27-1: 0
occupancy_status-28-1: 0
occupancy_status-29-1: 0
occupancy_status-30-1: 0
occupancy_status-31-1: 0
occupancy_status-32-1: 0
occupancy_status-33-1: 0
occupancy_status-34-1: 0
occupancy_status-35-1: 0
has_someone_duration-2-3: 0
has_someone_duration-4-3: 0
has_someone_duration-5-3: 0
has_someone_duration-6-3: 0
has_someone_duration-7-3: 0
has_someone_duration-8-3: 0
has_someone_duration-9-3: 0
has_someone_duration-10-3: 0
has_someone_duration-11-3: 0
has_someone_duration-12-3: 0
has_someone_duration-13-3: 0
has_someone_duration-14-3: 0
has_someone_duration-15-3: 0
has_someone_duration-16-3: 0
has_someone_duration-17-3: 0
has_someone_duration-18-3: 0
has_someone_duration-19-3: 0
has_someone_duration-20-3: 0
has_someone_duration-21-3: 0
has_someone_duration-22-3: 0
has_someone_duration-23-3: 0
has_someone_duration-24-3: 0
has_someone_duration-25-3: 0
has_someone_duration-26-3: 0
has_someone_duration-27-3: 0
has_someone_duration-28-3: 0
has_someone_duration-29-3: 0
has_someone_duration-30-3: 0
has_someone_duration-31-3: 0
has_someone_duration-32-3: 0
has_someone_duration-33-3: 0
has_someone_duration-34-3: 0
has_someone_duration-35-3: 0
no_one_duration-2-4: 0
no_one_duration-4-4: 0
no_one_duration-5-4: 0
no_one_duration-6-4: 0
no_one_duration-7-4: 0
no_one_duration-8-4: 0
no_one_duration-9-4: 0
no_one_duration-10-4: 0
no_one_duration-11-4: 0
no_one_duration-12-4: 0
no_one_duration-13-4: 0
no_one_duration-14-4: 0
no_one_duration-15-4: 0
no_one_duration-16-4: 0
no_one_duration-17-4: 0
no_one_duration-18-4: 0
no_one_duration-19-4: 0
no_one_duration-20-4: 0
no_one_duration-21-4: 0
no_one_duration-22-4: 0
no_one_duration-23-4: 0
no_one_duration-24-4: 0
no_one_duration-25-4: 0
no_one_duration-26-4: 0
no_one_duration-27-4: 0
no_one_duration-28-4: 0
no_one_duration-29-4: 0
no_one_duration-30-4: 0
no_one_duration-31-4: 0
no_one_duration-32-4: 0
no_one_duration-33-4: 0
no_one_duration-34-4: 0
no_one_duration-35-4: 0
occupancy_sensor.illumination: 23
config_sensor.one_map_name: 
config_sensor.two_map_name: 
config_sensor.people_num: 1
occupancy_sensor.enable_switch: true
installation_method-3-1: 0
config_sensor.bio_sensitive: 1
config_sensor.use_map_number: 1
installation_image-3-4: false
config_sensor.response_speed: 1
indicator_light.on: false
converters: button.info, sensor.occupancy_status-2-1, sensor.occupancy_status-4-1, sensor.occupancy_status-5-1, sensor.occupancy_status-6-1, sensor.occupancy_status-7-1, sensor.occupancy_status-8-1, sensor.occupancy_status-9-1, sensor.occupancy_status-10-1, sensor.occupancy_status-11-1, sensor.occupancy_status-12-1, sensor.occupancy_status-13-1, sensor.occupancy_status-14-1, sensor.occupancy_status-15-1, sensor.occupancy_status-16-1, sensor.occupancy_status-17-1, sensor.occupancy_status-18-1, sensor.occupancy_status-19-1, sensor.occupancy_status-20-1, sensor.occupancy_status-21-1, sensor.occupancy_status-22-1, sensor.occupancy_status-23-1, sensor.occupancy_status-24-1, sensor.occupancy_status-25-1, sensor.occupancy_status-26-1, sensor.occupancy_status-27-1, sensor.occupancy_status-28-1, sensor.occupancy_status-29-1, sensor.occupancy_status-30-1, sensor.occupancy_status-31-1, sensor.occupancy_status-32-1, sensor.occupancy_status-33-1, sensor.occupancy_status-34-1, sensor.occupancy_status-35-1, light.indicator_light.on, sensor.has_someone_duration-2-3, sensor.no_one_duration-2-4, sensor.occupancy_sensor.illumination, sensor.has_someone_duration-4-3, sensor.no_one_duration-4-4, sensor.has_someone_duration-5-3, sensor.no_one_duration-5-4, sensor.has_someone_duration-6-3, sensor.no_one_duration-6-4, sensor.has_someone_duration-7-3, sensor.no_one_duration-7-4, sensor.has_someone_duration-8-3, sensor.no_one_duration-8-4, sensor.has_someone_duration-9-3, sensor.no_one_duration-9-4, sensor.has_someone_duration-10-3, sensor.no_one_duration-10-4, sensor.has_someone_duration-11-3, sensor.no_one_duration-11-4, sensor.has_someone_duration-12-3, sensor.no_one_duration-12-4, sensor.has_someone_duration-13-3, sensor.no_one_duration-13-4, sensor.has_someone_duration-14-3, sensor.no_one_duration-14-4, sensor.has_someone_duration-15-3, sensor.no_one_duration-15-4, sensor.has_someone_duration-16-3, sensor.no_one_duration-16-4, sensor.has_someone_duration-17-3, sensor.no_one_duration-17-4, sensor.has_someone_duration-18-3, sensor.no_one_duration-18-4, sensor.has_someone_duration-19-3, sensor.no_one_duration-19-4, sensor.has_someone_duration-20-3, sensor.no_one_duration-20-4, sensor.has_someone_duration-21-3, sensor.no_one_duration-21-4, sensor.has_someone_duration-22-3, sensor.no_one_duration-22-4, sensor.has_someone_duration-23-3, sensor.no_one_duration-23-4, sensor.has_someone_duration-24-3, sensor.no_one_duration-24-4, sensor.has_someone_duration-25-3, sensor.no_one_duration-25-4, sensor.has_someone_duration-26-3, sensor.no_one_duration-26-4, sensor.has_someone_duration-27-3, sensor.no_one_duration-27-4, sensor.has_someone_duration-28-3, sensor.no_one_duration-28-4, sensor.has_someone_duration-29-3, sensor.no_one_duration-29-4, sensor.has_someone_duration-30-3, sensor.no_one_duration-30-4, sensor.has_someone_duration-31-3, sensor.no_one_duration-31-4, sensor.has_someone_duration-32-3, sensor.no_one_duration-32-4, sensor.has_someone_duration-33-3, sensor.no_one_duration-33-4, sensor.has_someone_duration-34-3, sensor.no_one_duration-34-4, sensor.has_someone_duration-35-3, sensor.no_one_duration-35-4, sensor.config_sensor.people_num, switch.occupancy_sensor.enable_switch, switch.installation_image-3-4, number.config_sensor.bio_sensitive, select.installation_method-3-1, select.config_sensor.use_map_number, select.config_sensor.response_speed, text.config_sensor.one_map_name, text.config_sensor.two_map_name
customizes: 
sensor_properties: occupancy_status,has_someone_duration,no_one_duration,illumination,people_num
chunk_coordinators:
  - interval: 10
    props: occupancy_status
  - interval: 15
    props: has_someone_duration
  - interval: 15
    props: no_one_duration
  - interval: 20
    props: illumination,people_num,one_map_name,two_map_name
  - interval: 300
    props: >-
      enable_switch,installation_method,bio_sensitive,use_map_number,installation_image,response_speed
switch_properties: enable_switch,installation_image
select_properties: installation_method,use_map_number,response_speed
number_properties: bio_sensitive
text_properties: one_map_name,two_map_name

info: null
device_class: update
friendly_name: Xiaomi Presence Info
```

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.core.device.xiaomi.sensor_occupy.p1
Source: helpers/update_coordinator.py:380
integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: May 8, 2025 at 11:58:08 AM (14 occurrences)
Last logged: 2:28:15 PM

Unexpected error fetching c4:93:bb:9c:xx:xx-chunk_1 data
Unexpected error fetching c4:93:bb:9c:xx:xx-chunk_3 data
Unexpected error fetching c4:93:bb:9c:xx:xx-chunk_2 data
Unexpected error fetching c4:93:bb:9c:xx:xx-miot_status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 536, in _update
    result = await self.update_miot_status(mapping, chunk_services=chunk_services)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 886, in update_miot_status
    res = await self.local.async_get_properties_for_mapping(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1402, in async_get_properties_for_mapping
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1395, in get_properties_for_mapping
    return self.get_properties(
           ~~~~~~~~~~~~~~~~~~~^
        properties,
        ^^^^^^^^^^^
        property_getter='get_properties',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        max_properties=max_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str
