### ISSUE TITLE
能接入云米的洗衣机吗？进米家的

### ISSUE THREAD

**Issue by ilongjiang** [al-one/hass-xiaomi-miot#251]
Model: [viomi.washer.u2](https://home.miot-spec.com/s/viomi.washer.u2)

**Comment by al-one** [comment]
请更新到master分支后再次尝试。
![图片](https://user-images.githubusercontent.com/4549099/142573525-f7525ce1-82a4-4663-a988-98ab93200e67.png)

**Comment by al-one** [comment]
由于该设备的[miot-spec规格](https://home.miot-spec.com/spec/viomi.washer.u2)中没有定义电源开关属性，你可能还需要添加一个[脚本实体](https://my.home-assistant.io/redirect/scripts)来打开洗衣机电源：
```yaml
alias: turn off washer
mode: single
sequence:
  - service: xiaomi_miot.send_command
    data:
      entity_id: sensor.viomi_u2_xxxx_washer # 洗衣机sensor实体ID
      method: set_wash_action
      params:
        - 2
```
