### ISSUE TITLE
miio2miot.py 中时间戳溢出导致 struct ‘>L’ 打包失败，导致群晖宕机，设备频繁离线重启

### ISSUE THREAD

**Issue by wqh227** [al-one/hass-xiaomi-miot#2510]
### Device model / 设备型号

yeelink.light.lamp1

### Component version / 插件版本

1.0.18

### HA core version / HA版本

2025.5.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

**内容：**

你好，感谢你开发的优秀项目！

我在使用 `custom_components/xiaomi_miot` 的时候遇到了一个比较严重的问题，会导致某些设备（比如我的 Yeelight 台灯）频繁离线、重启，甚至在米家 App 中也无法正常连接。

---

### ❗问题描述

日志中出现大量如下报错，定位到 `miio2miot.py`：

```
struct.error: 'L' format requires 0 <= number <= 4294967295
construct.core.FormatFieldError: struct '>L' error during building, given value 4294967296
```

也就是说，在使用 `construct.Struct('>L')` 打包 `ts` 字段时，传入了超出 `uint32` 范围的数值（比如 4294967296），导致构建失败。

这段问题代码类似如下：

```python
ts = int(time.time())
...
Struct(">L").build(ts)  # 如果 ts 超过 4294967295 就会异常
```

---

### 💥 实际表现

* 设备日志中持续报错，Home Assistant 内核 CPU 占用飙高（接近 100%），内存占用超过1G；
* 群晖docker和终端直接卡死，后台无法登录，所有内网服务全都瘫痪，包括统一用户认证、文件服务、Gitea、网页服务、数据库全都无法运行，硬盘有大量异常读写操作和异常声音，然后机器死机完全无法打开任何网页后台，无法连接到设备进行调试和查看相关日志，查看群晖报告只有Python3进程异常，但无法查看到是哪一个软件导致；
* 在多次询问ChatGPT，一个月的bug追踪后，才找到可能是home assistant导致，他让我不要在故障后不能重新启动系统和容器，直接通过文件提取日志，修改群晖的docker配置限制资源访问隔离故障才得以保存日志；
* 该设备（比如 米家台灯1代）频繁离线、重启；
* 米家 App 也无法正常控制该设备；
* ChatGPT排查发现是因为 ts 超出了范围导致构建失败、不断重试。
* 在这个软件bug下，灯的本体和群晖硬件都是正常的，暂时没有受到损坏。

---

### ✅ 建议修改

建议在构建 `ts` 字段前加一层限制处理，保证它在 32 位无符号整型范围内，比如这样写：

```python
ts = int(time.time()) & 0xFFFFFFFF
```

这个改动可以避免时间戳溢出导致的 struct 打包异常，同时不会影响正常功能。

---

如果需要我提供完整日志或复现环境，可以随时联系我，完成的日志超过100 MB，故障数据库超过800MB，重启后系统没办法在系统内部再次观看日志，再次感谢你的辛苦维护！

---

你可以复制这段内容贴到 GitHub 的 issue 页面里，如果需要我帮你发英文版本或者跟进 issue 回复也可以继续告诉我。

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 电脑台灯 信息
button.info: 电脑台灯
model: yeelink.light.lamp1
did: "118640806"
mac: 40:31:3C:C4:3B:5A
lan_ip: 192.168.50.212
app_link: mihome://device?uid=********&did=118640806
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelight-lamp1:1
available: true
home_room: 自己家 南房间
updater: local
updated_at: "2025-05-16 22:38:00.427637+08:00"
light.on: false
light.brightness: 100
light.color_temperature: 3900
converters:
  - button.info
  - light.light.on
  - light.brightness
  - light.color_temperature
  - light.mode
  - button.light.toggle
customizes:
  number_properties: off_delay_time,light_on_gradient_time,light_off_gradient_time
  switch_properties: bg_on,init_power_opt,fan_init_power_opt
  button_actions: toggle
  chunk_coordinators: []
  interval_seconds: 20
info: null
```

### Home Assistant Logs / 系统日志

2025-05-15 03:48:17.629 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: timed out
2025-05-15 03:49:37.648 ERROR (SyncWorker_26) [miio.miioprotocol] Got error when receiving: timed out
2025-05-15 03:49:58.204 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.lamp1] Unexpected error fetching 40:31:3c:c4:3b:5a-e298e402f2d52b207f3369c1faf78611-miot_status data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 1049, in _build
    data = struct.pack(self.fmtstr, obj)
struct.error: 'L' format requires 0 <= number <= 4294967295

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 536, in _update
    result = await self.update_miot_status(mapping, chunk_services=chunk_services)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 865, in update_miot_status
    results = await self.miio2miot.async_get_miot_props(self.local, mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 112, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        partial(self.get_miot_props, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 120, in get_miot_props
    if dic := self.get_miio_props(device):
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 66, in get_miio_props
    vls = device.get_properties(self.miio_props, max_properties=num)
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 174, in send
    m = Message.build(msg, token=self.token)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 336, in build
    self.build_stream(obj, stream, **contextkw)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 348, in build_stream
    self._build(obj, stream, context, "(building)")
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 2144, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 2657, in _build
    return self.subcon._build(obj, stream, context, path)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 4616, in _build
    buildret = self.subcon._build(value, stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 2144, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 2657, in _build
    return self.subcon._build(obj, stream, context, path)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 708, in _build
    buildret = self.subcon._build(obj2, stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 2938, in _build
    return self.subcon._build(obj, stream, context, path)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 1051, in _build
    raise FormatFieldError("struct %r error during building, given value %r" % (self.fmtstr, obj), path=path)
construct.core.FormatFieldError: Error in path (building) -> header -> ts
struct '>L' error during building, given value 4294967296
2025-05-15 03:50:18.753 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.yeelink.light.lamp1] Unexpected error fetching 40:31:3c:c4:3b:5a-e298e402f2d52b207f3369c1faf78611-miot_status data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 1049, in _build
    data = struct.pack(self.fmtstr, obj)
。。。。。。进行死循环。
