### ISSUE TITLE
cuco.plug.co3d 电压小数点错误移位

### ISSUE THREAD

**Issue by xrh0905** [al-one/hass-xiaomi-miot#2511]
### Device model / 设备型号

cuco.plug.co3d

### Component version / 插件版本

1.0.17

### HA core version / HA版本

2025.5.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

state_class: measurement
power_consumption.voltage: 223.6492
unit_of_measurement: V
device_class: voltage
friendly_name: 花园灯插座 电压

显示和统计的是`22.36492`

### Entity attributes / 实体属性

```yaml
button.info: 花园灯插座
model: cuco.plug.co3d
did: 619480791
mac: DC:[CENSORED]:04
lan_ip: 192.168.2.152
app_link: mihome://device?uid=1148685590&did=619480791
miot_type: urn:miot-spec-v2:device:outlet:0000A002:cuco-co3d:1
available: true
home_room: [CENSORED]的别墅 北阳台
icon: mdi:information
updater: local
updated_at: 2025-05-17 15:02:32.381383+08:00
physical_controls_locked: false
power_consumption: 0.0005
electric_current-8-2: 0
power_consumption.voltage: 223.6492
setting.light: true
setting.memory: 0
setting.mode: false
setting.start_time: 1380
setting.end_time: 420
cycle.status: false
cycle.data_value: 30;30;;0;1439;0
alarm.temp_over: false
alarm.current_over: false
power_cost_today: 0.002
power_cost_month: 0.23
switch.on: false
electric_power-8-4: 0
converters: button.info, switch.switch.on, switch.physical_controls_locked, sensor.electric_power-8-4, sensor.electric_current-8-2, sensor.power_consumption.voltage, binary_sensor.alarm.temp_over, binary_sensor.alarm.current_over, switch.setting.light, switch.setting.mode, select.setting.memory, sensor.power_cost_today, sensor.power_cost_month
customizes: 
chunk_coordinators:
  - interval: 10
    props: switch.on,electric_power
parallel_updates: 3
binary_sensor_properties: temp_over,current_over
switch_properties: light,mode
select_properties: memory
sensor_attributes: power_cost_today,power_cost_month
stat_power_cost_key: '8.1'

info: null
device_class: update
friendly_name: 花园灯插座 信息
```
