### ISSUE TITLE
VRF空调内机子设备无法通过本地控制

### ISSUE THREAD

**Issue by basicfu** [al-one/hass-xiaomi-miot#2512]
### Device model / 设备型号

qdhkl.gateway.b19

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.4.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

查看历史关于vrf的issue，我看应该是支持本地控制了
我选择auto自动模式，能显示子设备但是提示设备不可用，必须手动选择云端模式才可以正常使用，如果不支持的话，auto模式应该自动使用云端模式把？

![Image](https://github.com/user-attachments/assets/42742fb0-5396-4104-9953-2c0cad4510ea)

![Image](https://github.com/user-attachments/assets/59369597-7b86-4d66-b900-3545bf78ad44)

<img width="1034" alt="Image" src="https://github.com/user-attachments/assets/77966bde-0e70-41b2-ba31-8938b0d81288" />

### Entity attributes / 实体属性

```yaml
vrf
button.info: VRF Central Air Conditioner Controller
model: qdhkl.gateway.b19
did: "709155662"
mac: D4:F0:EA:7C:11:91
lan_ip: 10.1.2.229
app_link: mihome://device?uid=2175987315&did=709155662
miot_type: urn:miot-spec-v2:device:gateway:0000A019:qdhkl-b19:1
available: false
home_room: 1302 客厅
icon: mdi:information-off
updater: none
updated_at: ""
converters:
  - button.info
customizes: {}
miot_error: Unable to discover the device 10.1.2.229
info: null
device_class: update
friendly_name: VRF Central Air Conditioner Controller 信息



子设备

button.info: VRF Air Conditioner 3
model: qdhkl.aircondition.ac
did: proxy.709155662.0103
mac: proxy.709155662.0103
lan_ip: ""
app_link: mihome://device?uid=2175987315&did=proxy.709155662.0103
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:qdhkl-ac:2
available: false
home_room: 1302 客厅
icon: mdi:information-off
updater: none
updated_at: ""
converters:
  - button.info
  - climate.air_conditioner.mode
  - air_conditioner.on
  - target_temperature-2-4
  - environment.temperature
  - air_conditioner.mode
  - fan_control.fan_level
  - sensor.environment.temperature
  - switch.air_conditioner.on
  - select.fan_control.fan_level
customizes:
  sensor_properties: electricity.electricity
  switch_properties: air_conditioner.on
  select_properties: fan_level
  number_properties: target_humidity
  fan_services: air_fresh
  chunk_coordinators:
    - interval: 10
      props: on,mode,target_temperature,fan_level
      notify: true
miot_error: Unable to discover the device 10.1.2.229
info: null
device_class: update
friendly_name: VRF Air Conditioner 3 信息
```

### Home Assistant Logs / 系统日志

2025-05-18 16:54:33.522 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.gateway.b19] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'gateway.on': {'siid': 2, 'piid': 1}}, max_properties: 1/1
2025-05-18 16:54:38.601 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:54:43.607 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'environment.temperature': {'siid': 4, 'piid': 7}}, max_properties: 2/2
2025-05-18 16:54:48.616 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:54:53.473 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:54:53.622 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'environment.temperature': {'siid': 4, 'piid': 7}}, max_properties: 2/2
2025-05-18 16:54:58.632 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:55:03.354 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:55:03.639 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'environment.temperature': {'siid': 4, 'piid': 7}}, max_properties: 2/2
2025-05-18 16:55:08.651 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:55:13.456 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:55:13.657 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'environment.temperature': {'siid': 4, 'piid': 7}}, max_properties: 2/2
2025-05-18 16:55:18.667 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:55:23.195 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:55:23.674 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'environment.temperature': {'siid': 4, 'piid': 7}}, max_properties: 2/2
2025-05-18 16:55:33.261 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.aircondition.ac] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}}, max_properties: 4/4
2025-05-18 16:55:33.692 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.qdhkl.gateway.b19] Got MiioException while fetching the state: Unable to discover the device 10.1.2.229, mapping: {'gateway.on': {'siid': 2, 'piid': 1}}, max_properties: 1/1
