### ISSUE TITLE
[请求支持]市面上唯一一款支持米家的太阳能热水器控制面板

### ISSUE THREAD

**Issue by SeanChengN** [al-one/hass-xiaomi-miot#2517]
### Device model / 设备型号

zinguo.etool.tk01

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.5.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

以前只有涂鸦的控制面板，最近买了一款支持米家的，但是安装上以后发现还没有支持
文档里是有这个产品的：https://home.miot-spec.com/spec/zinguo.etool.tk01

![Image](https://github.com/user-attachments/assets/b0b336de-76bb-44a4-a2ff-8c060c0eb2c2)

### Entity attributes / 实体属性

```yaml
无实体
```

**Comment by SeanChengN** [comment]
我尝试了添加自定义实体，有四种运行模式：定时、节能、晴天、雨天，每种模式都有三次上水和加热，而且文档中id是一样的，我增加了mode.前缀后还是只有第一个实体有效：

![Image](https://github.com/user-attachments/assets/5de2d9a0-b718-4471-8a1e-37a96f703cb6)

```python
device_customizes:
  "zinguo.etool.tk01":
    sensor_properties:
      "temperature,water_level,recircle_left,defreeze_status,defreeze_open_left,defreeze_pause_left,
      key_response,sensor_fault,power,energy"
    binary_sensor_properties: "boost,feed,heat,recircle,defreeze,key_info,water_shortage,low_pressure,overflow,overload,leakage"
    switch_properties:
      "wenkong_enable,hengshui_enable,hengwen_enable,back_light,boost_enable,recircle_enable,defreeze_enable,overload_protect,
      timer_mode.*_feed_enable,timer_mode.*_heat_enable,
      eco_mode.*_feed_enable,eco_mode.*_heat_enable,
      sunny_mode.*_feed_enable,sunny_mode.*_heat_enable,
      rainy_mode.*_feed_enable,rainy_mode.*_heat_enable"
    number_properties:
      "pre_temperature,wenkong_temperature,hengwen_temperature,recircle_time,defreeze_open_time,defreeze_pause_time,shortage_delay_time,
      timer_mode.*_feed_hour,timer_mode.*_feed_minute,timer_mode.*_heat_hour,timer_mode.*_heat_minute,timer_mode.*_heat_temperature,
      eco_mode.*_feed_hour,eco_mode.*_feed_minute,eco_mode.*_heat_hour,eco_mode.*_heat_minute,eco_mode.*_heat_temperature,
      sunny_mode.*_feed_hour,sunny_mode.*_feed_minute,sunny_mode.*_heat_hour,sunny_mode.*_heat_minute,sunny_mode.*_heat_temperature,
      rainy_mode.*_feed_hour,rainy_mode.*_feed_minute,rainy_mode.*_heat_hour,rainy_mode.*_heat_minute,rainy_mode.*_heat_temperature"
    select_properties: "mode,pre_water_level,hengshui_level,show_set,sensility,
      exe_feed,exe_heat,exe_recircle,exe_defreeze,
      timer_mode.*_feed_level,eco_mode.*_feed_level,sunny_mode.*_feed_level,rainy_mode.*_feed_level"
    button_actions: "restore_factory"
  "zinguo.etool.tk01:energy:ENERGY_KWH":
    "unit_of_measurement": "kWh"
  "zinguo.etool.tk01:power":
    "state_class": "measurement"
    "device_class": "power"
    "unit_of_measurement": "W"
  "zinguo.etool.tk01:water_level":
    "unit_of_measurement": "%"
  "zinguo.etool.tk01:temperature":
    "unit_of_measurement": "°C"

```

**Comment by al-one** [comment]
yaml语法不对

**Comment by SeanChengN** [comment]
这样对了吗？问题依旧
```
device_customizes:
  "zinguo.etool.tk01":
    sensor_properties: "temperature,water_level,recircle_left,defreeze_status,defreeze_open_left,defreeze_pause_left,key_response,sensor_fault,power,energy"
    binary_sensor_properties: "boost,feed,heat,recircle,defreeze,key_info,water_shortage,low_pressure,overflow,overload,leakage"
    switch_properties: "wenkong_enable,hengshui_enable,hengwen_enable,back_light,boost_enable,recircle_enable,defreeze_enable,overload_protect,timer_mode.*_feed_enable,timer_mode.*_heat_enable,eco_mode.*_feed_enable,eco_mode.*_heat_enable,sunny_mode.*_feed_enable,sunny_mode.*_heat_enable,rainy_mode.*_feed_enable,rainy_mode.*_heat_enable"
    number_properties: "pre_temperature,wenkong_temperature,hengwen_temperature,recircle_time,defreeze_open_time,defreeze_pause_time,shortage_delay_time,timer_mode.*_feed_hour,timer_mode.*_feed_minute,timer_mode.*_heat_hour,timer_mode.*_heat_minute,timer_mode.*_heat_temperature,eco_mode.*_feed_hour,eco_mode.*_feed_minute,eco_mode.*_heat_hour,eco_mode.*_heat_minute,eco_mode.*_heat_temperature,sunny_mode.*_feed_hour,sunny_mode.*_feed_minute,sunny_mode.*_heat_hour,sunny_mode.*_heat_minute,sunny_mode.*_heat_temperature,rainy_mode.*_feed_hour,rainy_mode.*_feed_minute,rainy_mode.*_heat_hour,rainy_mode.*_heat_minute,rainy_mode.*_heat_temperature"
    select_properties: "mode,pre_water_level,hengshui_level,show_set,sensility,exe_feed,exe_heat,exe_recircle,exe_defreeze,timer_mode.*_feed_level,eco_mode.*_feed_level,sunny_mode.*_feed_level,rainy_mode.*_feed_level"
    button_actions: "restore_factory"

  "zinguo.etool.tk01:energy:ENERGY_KWH":
    "unit_of_measurement": "kWh"

  "zinguo.etool.tk01:power":
    "state_class": "measurement"
    "device_class": "power"
    "unit_of_measurement": "W"

  "zinguo.etool.tk01:water_level":
    "unit_of_measurement": "%"

  "zinguo.etool.tk01:temperature":
    "unit_of_measurement": "°C"

```
