### ISSUE TITLE
lxzn.switch.cbcsmj智能断路器缺少月耗电量实体

### ISSUE THREAD

**Issue by Verizon-rl** [al-one/hass-xiaomi-miot#2521]
### Device model / 设备型号

lxzn.switch.cbcsmj

### Component version / 插件版本

1.1.0

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

此设备无日耗电量、月耗电量实体。同时电流比实际值大1000倍，电压比实际值大10倍，跪求解决，谢谢

![Image](https://github.com/user-attachments/assets/82650adb-7b86-4a1a-8cb3-182b4e0c12fc)

### Entity attributes / 实体属性

```yaml
device_class: update
icon: mdi:information
friendly_name: 吧台后加热设备总控 信息
button.info: 吧台后加热设备总控
model: lxzn.switch.cbcsmj
did: 858201851
mac: CC:4D:75:2D:1C:18
lan_ip: 10.228.10.54
app_link: mihome://device?uid=3068642112&did=858201851
miot_type: urn:miot-spec-v2:device:switch:0000A003:lxzn-cbcsmj:1:0000D00D
available: true
home_room: 
updater: local
updated_at: 2025-05-23 21:32:48.368851+08:00
switch.on: true
switch.fault: 0
switch.temperature: 43.85955
switch.default_power_on_state: 1
power_consumption: 18744
electric_current-3-2: 8210
power_consumption.voltage: 2377
electric_power-3-6: 1942
fault_setting.electric_alarm: 15
electric_alarm_set-4-2: true
fault_setting.heat_alert: 80
fault_setting.heat_alert_set: true
fault_setting.overcurrent_alarm: 63
fault_setting.overcurrent_set: true
fault_setting.overvoltage_alarm: 250
fault_setting.overvoltage_set: true
undervoltage_alarm-4-9: 90
fault_setting.undervoltage_set: true
custom.device: 1
custom.device_config: 1
converters: button.info, switch.switch.on, sensor.electric_power-3-6, sensor.electric_current-3-2, sensor.power_consumption.voltage, sensor.switch.temperature, switch.electric_alarm_set-4-2, switch.fault_setting.heat_alert_set, switch.fault_setting.overcurrent_set, switch.fault_setting.overvoltage_set, switch.fault_setting.undervoltage_set, number.fault_setting.electric_alarm, number.fault_setting.heat_alert, number.fault_setting.overcurrent_alarm, number.fault_setting.overvoltage_alarm, number.undervoltage_alarm-4-9, select.switch.default_power_on_state
customizes: 
chunk_coordinators:
  - interval: 10
    props: 'on'
sensor_properties: temperature,electric_power
select_properties: default_power_on_state
switch_properties: >-
  electric_alarm_set,heat_alert_set,overcurrent_set,overvoltage_set,undervoltage_set
number_properties: >-
  electric_alarm,heat_alert,overcurrent_alarm,overvoltage_alarm,undervoltage_alarm

info: null
```
