### ISSUE TITLE
UnicodeDecodeError in miio.protocol.py when fetching data for Xiaomi d109gl

### ISSUE THREAD

**Issue by push-my-buttons** [al-one/hass-xiaomi-miot#2527]
### Device model / 设备型号

xiaomi.vacuum.d109gl

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.5.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The core issue appears to be a UnicodeDecodeError occurring when the miio library attempts to decode("utf-8") a byte sequence received from the device, specifically encountering byte 0xfb at position 128. This suggests the device is sending data that isn't valid UTF-8. The subsequent UnboundLocalError is a consequence of the initial UnicodeDecodeError, as the decoded variable isn't assigned a value.

### Entity attributes / 实体属性

```yaml
fan_speed_list:
  - Silent
  - Basic
  - Strong
  - Full Speed
battery_level: 83
battery_icon: mdi:battery-80
fan_speed: Basic
vacuum.status: 4
vacuum.cleaning_area: 3100
vacuum.cleaning_time: 2040
battery.charging_state: 2
vacuum.sweep_mop_type: 3
vacuum.sweep_type: 1
vacuum.clean_times: 1
vacuum.mode: 2
vacuum.vacuum_frameware_version: "{\"base_version\":\"0.1.27\"}"
vacuum.fault: 0
vacuum.mop_water_output_level: 1
vacuum.mop_status: true
vacuum.zone_ids: ""
vacuum.restricted_sweep_areas: ""
vacuum.restricted_walls: ""
vacuum.room_information: >-
  {"rooms":[{"id":7,"name":"Bathroom"},{"id":8,"name":"Technical
  room"},{"id":9,"name":"Living
  room"},{"id":11,"name":"Bedroom"},{"id":12,"name":"Corridor"},{"id":13,"name":""},{"id":14,"name":""},{"id":15,"name":""}],"map_uid":2}
vacuum.last_clean_time: 1748347796
base_station_working_status-2-18: "{\"mode\":0,\"runtime\":0,\"total_time\":0}"
vacuum.order_clean: "{\"time_labels\":[]}"
vacuum.carpet_boost: true
vacuum.carpet_avoidance: false
vacuum.carpet_display: false
vacuum.sweep_break_switch: true
vacuum.sleep_status: false
vacuum.location_status: false
vacuum.map_complete_dialog: 0
vacuum.enable_mop_wash: true
vacuum.frequency_mop_wash: 1
water_output_for_washing_mop-2-30: 1
vacuum.drying_time: 2
vacuum.auto_dust_arrest: true
vacuum.dust_arrest_frequency: 1
vacuum.auto_mop_dry: true
vacuum.auto_water_change: false
vacuum.use_detergent: false
vacuum.exit_remote_dialog: false
vacuum.current_cleaning_config: "{\"clean_mode\":1,\"is_ai_cleaning\":false}"
vacuum.user_define_sweep_cfg: "{\"user_labels\":[]}"
vacuum.user_define_sweep_id: 0
vacuum.water_check_list: ""
vacuum.water_check_status: 0
vacuum.sweep_furniture: ""
vacuum.carpet_object: ""
vacuum.detergent_self_delivery: false
mop_water_output_level_no_tank-2-60: 0
frequency_mop_wash_no_tank-2-61: 4
auto_water_change_installed-2-62: false
vacuum.fault_ids: "{\"ts\":1748352618,\"fault\":[0]}"
vacuum.action_result: ""
vacuum.plugin_info_remind: ""
detergent_depletion_reminder-2-71: false
vacuum.notice: ""
vacuum.carpet_cleaning_method: 0
vacuum.sweep_route: 3
obstacle_avoidance_strategy-2-75: 0
vacuum.carpet_deep_cleaning: false
vacuum.carpet_discriminate: true
vacuum.sweep_carpet_first: false
vacuum.mop_outer_swing: true
mop_outer_swing_frequency-2-80: 1
frequency_mop_wash_by_time-2-81: 20
auto_dust_arrest_power_level-2-82: 0
vacuum.worry_free_clean_mode: 2
wash_mop_water_temperature-2-84: 0
battery.voltage: 0
alarm: false
alarm.volume: 85
physical_controls_locked: false
current_physical_control_lock-5-2: false
mop.mop_life_level: 39
mop.mop_left_time: 31
no_disturb: true
no_disturb.enable_time_period: 369100288
no_disturb.current_no_disturb: false
brush_cleaner.brush_life_level: 84
brush_cleaner.brush_left_time: 250
brush_life_level-13-1: 76
brush_left_time-13-2: 150
filter.filter_life_level: 67
filter.filter_left_time: 100
detergent_left_level-18-1: 100
detergent_self_delivery-18-2: false
detergent_self_delivery_level-18-3: 0
dust_bag.dust_bag_life_level: 100
dust_bag.dust_bag_left_time: 200
state_updater: local
vacuum.status_desc: Sweeping
friendly_name: X20 Max Robot Cleaner
supported_features: 12540
```

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.core.device.xiaomi.vacuum.d109gl
Zdroj: helpers/update_coordinator.py:380
integrace: Xiaomi Miot Auto (dokumentace, problémy)
První výskyt: 13:25:04 (1 výskyt)
Naposledy logováno: 13:25:04

Unexpected error fetching e8:4a:54:ea:9e:d9-01JW8HTWER0BZH3DGKF3S2WWTS-chunk_2 data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/miio/protocol.py", line 198, in _decode
    decoded = quirk(decrypted).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 536, in _update
    result = await self.update_miot_status(mapping, chunk_services=chunk_services)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 886, in update_miot_status
    res = await self.local.async_get_properties_for_mapping(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1402, in async_get_properties_for_mapping
    return await self.hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1395, in get_properties_for_mapping
    return self.get_properties(
            ~~~~~~~~~~~~~~~~~~~^
        properties,
        ^^^^^^^^^^^
        property_getter='get_properties',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        max_properties=max_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
            ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 194, in send
    m = Message.parse(data, token=self.token)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 2653, in _parse
    return self.subcon._parsereport(stream, context, path)
            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 4295, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 4598, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.13/site-packages/construct/core.py", line 704, in _parse
    return self._decode(obj, context, path)
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/protocol.py", line 204, in _decode
    _LOGGER.debug("Unable to parse json '%s': %s", decoded, ex)
                                                 ^^^^^^^
UnboundLocalError: cannot access local variable 'decoded' where it is not associated with a value
