### ISSUE TITLE
小米浴霸yeelink.bhf_light.v5

### ISSUE THREAD

**Issue by jjss520** [al-one/hass-xiaomi-miot#2528]
### Device model / 设备型号

yeelink.bhf_light.v5

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.5.2

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

模式里的仅送风和预设里的Ventilate 功能正好相反。应该对换一下

### Entity attributes / 实体属性

```yaml
hvac_modes:
  - "off"
  - heat
  - dry
  - fan_only
min_temp: 25
max_temp: 45
target_temp_step: 1
fan_modes:
  - low
  - high
preset_modes:
  - Defog
  - Quick Defog
  - Quick Heat
  - Ventilate
  - "off"
current_temperature: 25
temperature: 30
fan_mode: low
hvac_action: "off"
preset_mode: "off"
light.on: false
light.brightness: 100
ptc_bath_heater.mode: 5
ptc_bath_heater.heating: false
ptc_bath_heater.blow: false
ptc_bath_heater.ventilation: false
target_temperature-3-5: 30
ptc_bath_heater.temperature: 25
ptc_bath_heater.fan_level: 1
ptc_bath_heater.heat_mode: 0
ptc_bath_heater.cold_mode: 0
ptc_bath_heater.vent_mode: 0
state_updater: local
friendly_name: 次卫浴霸
supported_features: 409
```
