### ISSUE TITLE
Xiaomi X20 Max Won’t Clean Specific Rooms via Xiaomi Miot Auto – Tried Everything

### ISSUE THREAD

**Issue by timo232323** [al-one/hass-xiaomi-miot#2532]
### Device model / 设备型号

X20 max - xiaomi-d109gl

### Component version / 插件版本

6.12.20-haos

### HA core version / HA版本

2025.4.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

**Title:** Xiaomi X20 Max Won’t Clean Specific Rooms via Xiaomi Miot Auto – Tried Everything

Hi everyone,

I’m at my wits’ end trying to get my **Xiaomi X20 Max** to clean specific rooms using **Xiaomi Miot Auto integration** in Home Assistant.

Here’s the exact automation I’m using:

```yaml
- data:
    entity_id: vacuum.xiaomi_d109gl_135d_robot_cleaner
    siid: 2
    aiid: 42
    params:
      - 266706341
  action: xiaomi_miot.call_action
mode: single
```

The **ID (`266706341`) is 100% correct** — I extracted it directly from the **kita (label) file**, so that shouldn’t be the issue.

I’ve double-checked the structure against the official documentation at:
👉 [https://home.miot-spec.com/spec/xiaomi.vacuum.d109gl](https://home.miot-spec.com/spec/xiaomi.vacuum.d109gl)

Still, when I run the automation, **the vacuum does absolutely nothing**. No error, no movement, no logs — just silence.
I’ve tried:

At this point I’m honestly stuck and could really use help.
Has **anyone successfully triggered room-based cleaning** on the **X20 Max** with this integration?
Do I need to pass additional parameters? Am I missing something obvious?

Any help, working examples, or advice would be incredibly appreciated.

Thanks in advance!

### Entity attributes / 实体属性

```yaml
.
```

**Comment by timo232323** [comment]
```yaml
action: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_d109gl_135d_robot_cleaner
  siid: 2 
  aiid: 42
  params: 1759492181
```

Worked!

**Comment by estevangarcia** [comment]
I'm trying to get my X20 MAX (d109gl) to clean specific rooms, but using the YAML below, it starts the cleanup and immediately warns that it can't access the room.

I've already checked in the HA developer tool and the room has the correct ID.

NOTE: Performing the same cleanup per room via the app, everything goes smoothly.

NOTE 2: Using aiid: 42 (start-user-define-sweep) works, but the app only allows 5 definitions.



vacuum.room_information: {"rooms":[{"id":6,"name":"Sacada"},{"id":13,"name":"Sala"},{"id":15,"name":"Cozinha"},{"id":18,"name":"Sala de jantar"},{"id":19,"name":"Quarto visitas"},{"id":20,"name":"Corredor"},{"id":21,"name":"Banheiro suíte"},{"id":22,"name":"Suite"},{"id":23,"name":""},{"id":24,"name":"Escritório"}],"map_uid":9}

```yaml
action: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_d109gl_ac4e_robot_cleaner
  siid: 2
  aiid: 37
  params:
    - "{\"room\": [20] }"
```

**Comment by eltigre4jc** [comment]
I found this: https://home.miot-spec.com/spec/xiaomi.vacuum.d109gl
and it helped me clean specific rooms. (I think aiid was 16 for this)

**Comment by groundbyNG** [comment]
Try:
`configuration.yaml`
```
input_boolean:
  vacuum_room_1:
    name: "Room 1"
    icon: mdi:home
  vacuum_room_2:
    name: "Room 2"
    icon: mdi:home
  vacuum_room_3:
    name: "Room 3"
    icon: mdi:home
script:
  vacuum_clean_selected_rooms:
      alias: "Vacuum Clean Selected Rooms"
      sequence:
        - service: xiaomi_miot.call_action
          data:
            entity_id: vacuum.YOUR_ROBOT_ENTITY
            siid: 2
            aiid: 16
            params: >-
              {% set rooms = [] %}
              {% if is_state('input_boolean.vacuum_room_1', 'on') %}{% set rooms = rooms + ['1'] %}{% endif %}
              {% if is_state('input_boolean.vacuum_room_2', 'on') %}{% set rooms = rooms + ['2'] %}{% endif %}
              {% if is_state('input_boolean.vacuum_room_3', 'on') %}{% set rooms = rooms + ['3'] %}{% endif %}
              [{"piid": 15, "value": "{{ rooms | join(',') }}"}]
            force_params: true
```


`lovelace.yaml`
```
type: vertical-stack
cards:
- type: entities
    title: Select Rooms to Clean
    show_header_toggle: false
    entities:
      - entity: input_boolean.vacuum_room_1
        name: Room 1
      - entity: input_boolean.vacuum_room_2
        name: Room 2
      - entity: input_boolean.vacuum_room_3
        name: Room 3
 - type: button
        name: Start
        icon: mdi:play
        tap_action:
          action: call-service
          service: script.vacuum_clean_selected_rooms
```

**Comment by fabiobrolo** [comment]
I tried the action below, but the vacuum leaves the dock, spins, and stops nearby with an error. It's failing to clean room 10 (valid room id of my office).
      
```
- service: xiaomi_miot.call_action
  data:
      entity_id: vacuum.aspirador
      siid: 2
      aiid: 16
      params: >-
            [{"piid": 15, "value": "10"}]
      force_params: true
```

**Comment by ThyHunter777** [comment]
```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.xiaomi_d109gl_edd1_robot_cleaner
  siid: 2
  aiid: 16
  params: >-
        [{"piid": 15, "value": "14"}]
  force_params: true
```

Exactly the same behavior for me. It looks like is going for asked service but immediately returns to the base

I feel I tried everything...
