### ISSUE TITLE
midr.cateye.ph300 status Unknown/Unavailable

### ISSUE THREAD

**Issue by sdenisb** [al-one/hass-xiaomi-miot#2535]
### Device model / 设备型号

midr.cateye.ph300

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.5.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![Image](https://github.com/user-attachments/assets/6b4da6f9-0e0f-4596-a089-292aa16ff9f9)

### Entity attributes / 实体属性

```yaml
button.info: peephole
model: midr.cateye.ph300
did: 11xxxxx06
mac: 44:xx:70:xx:F3:xx
lan_ip: 192.168.31.67
app_link: mihome://device?uid=18xxxx0&did=11xxxxx06
miot_type: urn:miot-spec-v2:device:video-doorbell:0000A03A:midr-ph300:2
available: false
home_room: Hallway
icon: mdi:information-off
updater: none
updated_at: 2025-06-03 15:12:53.919935+03:00
state_updater: null
video_doorbell.on: 1
video_doorbell.status: 1
video_doorbell.night_shot: 2
video_doorbell.time_watermark: true
video_doorbell.eco: false
video_doorbell.ringtone: 2
image_distortion_correction-2-8: true
video_doorbell.local_storage: true
forcibly_removed_alarm_switch-2-12: true
video_doorbell.auto_screen_on: true
indicator_light.on: false
indicator_light.mode.error: -4002 Property is not writable
indicator_light.brightness.error: -4002 Property is not writable
indicator_light.color.error: -4002 Property is not writable
color_temperature-3-5.error: -4002 Property is not writable
indicator_light.flow.error: -4002 Property is not writable
indicator_light.saturability.error: -4002 Property is not writable
indicator_light.auto_lights_off.error: -4002 Property is not writable
motion_detection: true
motion_detection.alarm_interval: 60
detection_sensitivity-4-3: 2
motion_detection_start_time-4-4: 00:00-23:59
motion_detection.record_delay: 0
max_record_time-4-7: 60
device_warn_time-4-8: 0
battery_level: 0
battery.charging_state: 0
speaker.volume: 50
memory_card_management.status: 0
storage_total_space-7-2: 124981648
storage_free_space-7-3: 529728
storage_used_space-7-4: 124451920
auto_reply: false
auto_reply.auto_reply_week: 1,2,3,4,5,6,7
auto_reply_start_time-8-3: 00:00-23:59
auto_reply.auto_reply_end_time.error: -4002 Property is not writable
auto_reply.auto_reply_item: 1_URL
camera_control.on.error: -4002 Property is not writable
camera_control.image_rollover.error: -4002 Property is not writable
camera_control.night_shot.error: -4002 Property is not writable
camera_control.time_watermark.error: -4002 Property is not writable
camera_control.wdr_mode.error: -4002 Property is not writable
glimmer_full_color-10-6.error: -4002 Property is not writable
camera_control.recording_mode.error: -4002 Property is not writable
camera_control.motion_tracking.error: -4002 Property is not writable
camera_control.local_storage.error: -4002 Property is not writable
camera_control.ptz_camera.error: -4002 Property is not writable
camera_control.human_tracking.error: -4002 Property is not writable
camera_control.ai_frame.error: -4002 Property is not writable
camera_control.hdr_mode: false
image_distortion_correction-10-14.error: -4002 Property is not writable
auto_sound_and_light_warning-10-15.error: -4002 Property is not writable
manual_sound_and_light_warning-10-16.error: -4002 Property is not writable
p2p_stream.talk_mode.error: -4002 Property is not writable
p2p_stream.audio_codec.error: -4002 Property is not writable
p2p_stream.audio_bit_width.error: -4002 Property is not writable
p2p_stream.video_codec.error: -4002 Property is not writable
p2p_stream.audio_smp_rate.error: -4002 Property is not writable
p2p_stream.audio_channel.error: -4002 Property is not writable
p2p_stream.talk_codec.error: -4002 Property is not writable
p2p_stream.distortion_crt_osdx.error: -4002 Property is not writable
p2p_stream.distortion_crt_osdy.error: -4002 Property is not writable
p2p_stream.resolution_types.error: -4002 Property is not writable
face_detection_switch-13-4.error: -4002 Property is not writable
ai_detection.human_detection.error: -4002 Property is not writable
ai_detection.move_detection.error: -4002 Property is not writable
ai_detection.car_detection.error: -4002 Property is not writable
ai_detection.goods_detection.error: -4002 Property is not writable
ai_detection.detection_area.error: -4002 Property is not writable
detection_area_osd_switch-13-16.error: -4002 Property is not writable
ai_detection.car_detected_mode.error: -4002 Property is not writable
person_approaching_car_mode-13-18.error: -4002 Property is not writable
smart_care.smart_care_switch: false
smart_care.smart_care_area: [{"lT":{"x":140,"y":105},"lB":{"x":140,"y":255},"rT":{"x":340,"y":105},"rB":{"x":340,"y":255},"if_using":true}]
screen.display_state: 0
screen.auto_screen_off_time: 10
no_disturb: false
no_disturb.enable_time_period: 20:00-06:00
sreen_connect_custom-11-5.error: -4002 Property is not writable
max_screen_duration-11-9.error: -4002 Property is not writable
motion_video_time: 2025-06-03 15:12:38.399000
motion_video_type: Pass
stream_address: https://business.smartcamera.api.io.mi.com/common/app/xxxxxxxxxxxxxxxxxxxx
image_address: https://processor.smartcamera.api.io.mi.com/miot/camera/app/v1/xxxxxxxxxxxxxxxx
converters: button.info, light.indicator_light.on, indicator_light.brightness, indicator_light.mode, sensor.battery_level, sensor.battery.charging_state
customizes: 
use_motion_stream: true

miot_error: {'code': -30012, 'message': 'busy.'}
info: null
device_class: update
friendly_name: peephole Info
```

**Comment by sdenisb** [comment]
1. 设备连接问题：

- 请确认设备是否在线（通过米家APP检查）
**Yes, the device is connected to Mijia**

![Image](https://github.com/user-attachments/assets/f4807e04-148f-4860-bb24-18c3bb3998fc)

- 检查设备是否与WiFi网络正常连接
**The device is connected to Wi-Fi**

2. 集成配置问题：

- 尝试重新启动Home Assistant
**Rebooting doesn't help**
- 在集成配置中尝试"更新设备列表"
**Updating/re-adding the device does not help**

对于这类智能猫眼设备，如果通过云端集成，状态更新可能会有延迟。您可以尝试以下方法：
```
# configuration.yaml
xiaomi_miot:
  device_customizes:
    midr.cateye.ph300:
      cloud_delay_update: 5  # 增加状态更新延迟
      interval_seconds: 15   # 缩短轮询间隔
```
**Nothing has changed, the device is unavailable**

请提供更多信息以便更准确地诊断问题。特别是：

- 设备实体属性

![Image](https://github.com/user-attachments/assets/467fc057-c6bd-43f1-b916-ea1358cef775)

- Home Assistant日志中的相关错误

[Log details.txt](https://github.com/user-attachments/files/20653533/Log.details.txt)

- 设备在米家APP中的状态

![Image](https://github.com/user-attachments/assets/f4807e04-148f-4860-bb24-18c3bb3998fc)

**Comment by sdenisb** [comment]
> 根据您提供的信息，设备型号为 `midr.cateye.ph300`，状态显示为 "Unknown/Unavailable"。这种情况可能有几个原因：
> 
> 1. **设备连接问题**：
>    
>    * 请确认设备是否在线（通过米家APP检查）
>    * 检查设备是否与WiFi网络正常连接
> 2. **集成配置问题**：
>    
>    * 尝试重新启动Home Assistant
>    * 在集成配置中尝试"更新设备列表"
> 3. **需要更多信息来诊断问题**：
>    
>    * 请提供设备的实体属性（在开发者工具 > 状态中查看）
>    * 请检查Home Assistant日志中是否有相关错误信息
>    * 请确认设备在米家APP中的工作状态是否正常
> 
> 对于这类智能猫眼设备，如果通过云端集成，状态更新可能会有延迟。您可以尝试以下方法：
> 
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     midr.cateye.ph300:
>       cloud_delay_update: 5  # 增加状态更新延迟
>       interval_seconds: 15   # 缩短轮询间隔
> 请提供更多信息以便更准确地诊断问题。特别是：
> 
> * 设备实体属性
> * Home Assistant日志中的相关错误
> * 设备在米家APP中的状态

1. 设备连接问题：

- 请确认设备是否在线（通过米家APP检查）
**Yes, the device is connected to Mijia**

![Image](https://github.com/user-attachments/assets/f4807e04-148f-4860-bb24-18c3bb3998fc)

- 检查设备是否与WiFi网络正常连接
**The device is connected to Wi-Fi**

2. 集成配置问题：

- 尝试重新启动Home Assistant
**Rebooting doesn't help**
- 在集成配置中尝试"更新设备列表"
**Updating/re-adding the device does not help**

对于这类智能猫眼设备，如果通过云端集成，状态更新可能会有延迟。您可以尝试以下方法：
```
# configuration.yaml
xiaomi_miot:
  device_customizes:
    midr.cateye.ph300:
      cloud_delay_update: 5  # 增加状态更新延迟
      interval_seconds: 15   # 缩短轮询间隔
```
**Nothing has changed, the device is unavailable**

请提供更多信息以便更准确地诊断问题。特别是：

- 设备实体属性

![Image](https://github.com/user-attachments/assets/467fc057-c6bd-43f1-b916-ea1358cef775)

- Home Assistant日志中的相关错误

[Log details.txt](https://github.com/user-attachments/files/20653533/Log.details.txt)

- 设备在米家APP中的状态

![Image](https://github.com/user-attachments/assets/f4807e04-148f-4860-bb24-18c3bb3998fc)
