### ISSUE TITLE
aircondition plug not working

### ISSUE THREAD

**Issue by kyc1338** [al-one/hass-xiaomi-miot#2538]
### Device model / 设备型号

lumi.aircondition.acn05 & lumi.acpartner.v3

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.05.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I have 3 no. acn05 and 1 no. acpartner.v3, all were working well couple weeks ago but became unavailable since last week. 

### Entity attributes / 实体属性

```yaml
climate.lumi_acn05_65c1_air_conditioner
空调
unavailable	restored: true
hvac_modes: auto, fan_only, heat, off, cool, dry
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
swing_modes: on, off
friendly_name: 空调
supported_features: 425
climate.lumi_acn05_d3c9_air_conditioner
空调
unavailable	restored: true
hvac_modes: auto, fan_only, heat, off, cool, dry
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
swing_modes: on, off
friendly_name: 空调
supported_features: 425
```
