### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by basicfu** [al-one/hass-xiaomi-miot#2539]
启用miot集成后，homeassistant日志中持续输出当前错误，我的miot中有vrf中央空调，我不确定它是否和当前组件是否有关，但是我禁用当前集成后错误停止，我在ha中看到了这个issues ，但是我不清楚具体和哪个地方有关
https://github.com/home-assistant/core/issues/106522

2025-06-09 21:58:24.284 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1014, in _async_write_ha_state_from_call_soon_threadsafe
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1081, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 379, in capability_attributes
    FanEntityFeature.SET_SPEED in supported_features
TypeError: argument of type 'int' is not iterable

**Comment by al-one** [comment]
提供中央空调子设备型号，及info实体属性。

**Comment by basicfu** [comment]
vrf的：
```yaml
button.info: VRF Central Air Conditioner Controller
model: qdhkl.gateway.b19
did: "709155662"
mac: D4:F0:EA:7C:11:91
lan_ip: 10.1.1.200
app_link: mihome://device?uid=2175987315&did=709155662
miot_type: urn:miot-spec-v2:device:gateway:0000A019:qdhkl-b19:1
available: true
home_room: ""
icon: mdi:information
updater: local
updated_at: "2025-06-13 14:27:10.546269+08:00"
gateway.on: true
converters:
  - button.info
customizes: {}
info: null
device_class: update
friendly_name: VRF Central Air Conditioner Controller 信息
```
#子设备的
```yaml
button.info: 空调-书房
model: qdhkl.aircondition.ac
did: proxy.709155662.0101
mac: proxy.709155662.0101
lan_ip: ""
app_link: mihome://device?uid=2175987315&did=proxy.709155662.0101
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:qdhkl-ac:2
available: true
home_room: ""
icon: mdi:information
updater: local
updated_at: "2025-06-13 14:27:21.693888+08:00"
air_conditioner.on: true
air_conditioner.mode: 1
target_temperature-2-4: 26
fan_control.fan_level: 1
air_conditioner.fault: 0
environment.temperature: 27
converters:
  - button.info
  - climate.air_conditioner.mode
  - air_conditioner.on
  - target_temperature-2-4
  - environment.temperature
  - air_conditioner.mode
  - fan_control.fan_level
  - sensor.environment.temperature
  - switch.air_conditioner.on
  - select.fan_control.fan_level
customizes:
  sensor_properties: electricity.electricity
  switch_properties: air_conditioner.on
  select_properties: fan_level
  number_properties: target_humidity
  fan_services: air_fresh
  chunk_coordinators:
    - interval: 10
      props: on,mode,target_temperature,fan_level
      notify: true
info: null
device_class: update
friendly_name: 空调-书房 信息
```
