### ISSUE TITLE
Smart Air Purifier 4 Lite, zhimi.airp.rma3. Incorrect PM2.5 diagnostics if the device is turned off.

### ISSUE THREAD

**Issue by garry0garry** [al-one/hass-xiaomi-miot#2540]
### Device model / 设备型号

zhimi.airp.rma3

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.5.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

If the Xiaomi Smart Air Purifier 4 Lite was turned off by pressing the button, the air quality graphs freeze for an infinite period of time.

Problem:
![Image](https://github.com/user-attachments/assets/345662ed-230b-458c-baff-be480b290ca8)
![Image](https://github.com/user-attachments/assets/00d8710b-279d-411a-8311-fa6e7f301edf)

No problem:
![Image](https://github.com/user-attachments/assets/e4febc57-cb75-447e-b87b-c849668aafce)
![Image](https://github.com/user-attachments/assets/679db09d-b672-4de6-93b8-6f1f218bd9e2)

### Entity attributes / 实体属性

```yaml
button.info: Xiaomi Smart Air Purifier 4 Lite
model: zhimi.airp.rma3
did: 826669006
mac: XX:XX:XX:XX:XX:XX
lan_ip: 192.168.XX.XX
app_link: mihome://device?uid=XXXXXXXXXX&did=XXXXXXXX
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-rma3:1
available: true
home_room: Баня
icon: mdi:information
updater: local
updated_at: 2025-06-11 08:56:55.796770+03:00
air_purifier.on: true
air_purifier.mode: 0
air_purifier_favorite.fan_level: 14
air_purifier.fault: 0
environment.relative_humidity: 50
environment.pm2_5_density: 2
environment.temperature: 23
environment.air_quality: 0
filter.filter_life_level: 0
filter.filter_used_time: 3500
filter.filter_left_time: 0
filter_used_time_dbg-9-2: 3500
alarm: true
screen.brightness: 2
physical_controls_locked: false
custom_service.moto_speed_rpm: 416
aqi.aqi_updata_heartbeat: 300
converters: button.info, fan.air_purifier.on, air_purifier.on, air_purifier.mode, switch.alarm, switch.physical_controls_locked, sensor.filter.filter_life_level, sensor.filter.filter_left_time, sensor.filter.filter_used_time, sensor.environment.temperature, sensor.environment.relative_humidity, sensor.environment.pm2_5_density, sensor.environment.air_quality, sensor.custom_service.moto_speed_rpm, select.screen.brightness, select.air_purifier_favorite.fan_level
customizes: 
switch_properties: alarm
sensor_properties: moto_speed_rpm
chunk_coordinators:
  - interval: 21
    props: on,mode,fan_level
  - interval: 61
    props: fault,relative_humidity,pm2_5_density,temperature,air_quality
  - interval: 301
    props: filter_*
interval_seconds: 150
select_properties: brightness,air_purifier_favorite.fan_level

info: null
device_class: update
friendly_name: Xiaomi Smart Air Purifier 4 Lite Info
```
