### ISSUE TITLE
Xiaomi Imilab EC5 Floodlight Camera - P2P Stream Entities Missing (i.e No Video Stream)

### ISSUE THREAD

**Issue by Deusex-ai** [al-one/hass-xiaomi-miot#2547]
### Device model / 设备型号

chuangmi.camera.055c02

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.6.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hello,

Background:

I have been able to integrate, and get many control entities of the camera, but the Sensors: 'Camera Control' (which I assume should give a video, when openned) and also the 'Camera Control motion_event' (which I assume should give a snapshot/captured video) do not show.

Also, following entities are missing:

1) When integrating the camera, it doesn't present all the entities per spec: https://home.miot-spec.com/spec/chuangmi.camera.055c02
Specifically the 'start-p2p-stream', 'stop-p2p-stream'.

Can I configure this manually in the customization, if so kindly advise - how to define the correct tempate to use them in customization.yml?

2) In the info of the entity, the 'Stream address' is blank and there's no address for streaming.

If possible, kindly advise how I can get the stream into go2rtc/rtsp (for Frigate usage) for this camera?

P.S
I've tried to add per examples I've seen for customization for xiaomi_miot the following structure in customize.yml, but it doesn't recognize the entity of 'xiaomi_miot':

xiaomi_miot:
  device_customizes:
    chuangmi.camera.055c02:
      switch_properties: on    

The system cannot restart because the configuration is not valid: Invalid config for 'homeassistant' at customize.yaml, line 5: Entity ID xiaomi_miot is an invalid entity ID 'customize->xiaomi_miot', got {'device_customizes': {'chuangmi.camera.055c02': {'switch_properties': True}}}

### Entity attributes / 实体属性

```yaml
button.info: IMILAB EC5 Floodlight Camera
model: chuangmi.camera.055c02
did: "1144491660"
mac: 78:DF:72:E3:AA:13
lan_ip: 192.168.1.247
app_link: mihome://device?uid=6811182988&did=1144491660
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-055c02:2
available: true
home_room: ""
icon: mdi:information
updater: local
updated_at: "2025-06-18 22:27:08.888140+03:00"
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 5
camera_control.wdr_mode: false
glimmer_full_color-2-6: true
camera_control.recording_mode: 0
camera_control.motion_tracking: true
camera_control.time_watermark: true
indicator_light.on: false
memory_card_management.status: 0
storage_total_space-4-2: 122120320
storage_free_space-4-3: 242112
storage_used_space-4-4: 0
motion_detection: true
motion_detection.alarm_interval: 3
detection_sensitivity-5-3: 1
motion_detection_start_time-5-4: "00:00:00"
motion_detection_end_time-5-5: "23:59:00"
stream_status-17-9: 1
stream_status-18-9: 1
fav_area: >-
  [{"idx":1,"pos":"[69,66]","active_time":"[16777215,16777215,16777215,16777215,16777215,16777215,16777215]","ver":1,"time":"0,24","rpt":"1,1,1,1,1,1,1"}]
fav_area.boundary_attr: >-
  [{"idx":1,"switch":1,"num":2,"L1":"51,53,38,90","D1":"51,53,38,90","L2":"51,53,77,77","D2":"51,53,77,77","sound_alarm":{"switch":0,"name":"1-alarm"},"light_alarm":{"switch":0,"param":"[1,10000,5,500,500]"}}]
fav_area.key_area_attr: >-
  [{"idx":1,"switch":1,"area":"[41,63,69,100]","sound_alarm":{"switch":0,"name":"1-alarm"},"light_alarm":{"switch":0,"param":"[1,10000,5,500,500]"}}]
fav_area.active_fav_area: 1
fav_area.motor_position: "[69,66]"
people_detect_attr-10-1: "{\"switch\":1,\"start_time\":\"00:00\",\"end_time\":\"23:59\"}"
object_detect_attr-10-2: "{\"switch\":0,\"start_time\":\"00:00\",\"end_time\":\"23:59\"}"
hotspot: >-
  {"switch_enable":"0","ap_switch":"0","ap_name":"xiaobaishexiangji","ap_passwd":"12345678"}
white_light_control: "{\"switch\":0,\"brightness\":5}"
brightness_on_night-13-2: 5
lock_region.lock_region_attr: "{\"lock_region\":0,\"legal_status\":0}"
camera_capacity: boundary,key_area,no_wired_network
sd_status.ejected: true
state_updater: local
motion_video_time: "2025-06-18 21:16:01.011000"
motion_video_type: PeopleMotion
stream_address: ""
expire_at: "2025-06-18 22:30:10.088137"
converters:
  - button.info
  - light.indicator_light.on
  - sensor.memory_card_management.status
  - sensor.storage_free_space-4-3
  - sensor.storage_used_space-4-4
  - switch.camera_control.on
  - switch.camera_control.wdr_mode
  - switch.glimmer_full_color-2-6
  - switch.camera_control.motion_tracking
  - switch.camera_control.time_watermark
  - switch.indicator_light.on
  - switch.motion_detection
  - number.camera_control.image_rollover
  - number.motion_detection.alarm_interval
  - select.camera_control.night_shot
  - select.camera_control.recording_mode
  - select.detection_sensitivity-5-3
customizes:
  miot_cloud_action: true
  sensor_properties: memory_card_management.status,storage_free_space,storage_used_space
  select_properties: night_shot,recording_mode,detection_sensitivity
  switch_properties: >-
    on,time_watermark,motion_tracking,motion_detection,wdr_mode,glimmer_full_color
  number_properties: image_rollover,alarm_interval
info: null
device_class: update
friendly_name: IMILAB EC5 Floodlight Camera Info
```

### Home Assistant Logs / 系统日志

2025-06-18 21:34:03.319 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-18 21:34:03.320 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-18 21:34:03.320 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-18 21:34:03.321 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-06-18 21:34:06.112 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  Bool = partial(_str2bool)

2025-06-18 21:34:06.360 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'webrtc' accessed lovelace_data['resources'] instead of lovelace_data.resources at custom_components/webrtc/utils.py, line 129: resources: ResourceStorageCollection = hass.data["lovelace"]["resources"]. This will stop working in Home Assistant 2026.2, please create a bug report at https://github.com/AlexxIT/WebRTC/issues
2025-06-18 21:34:10.877 WARNING (SyncWorker_0) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg16.livestreaming.io.mi.com/hlstranscoder/GCBkMmY2Y2ExY2UyYmY0NDFhYjE4ZWRkZjA0NGM4YTlmNRgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:35:12.896 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.221
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 257, in get
    return await ws_poster(hass, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webrtc/__init__.py", line 210, in ws_poster
    _LOGGER.debug(f"webrtc image_entity: {image_entity} - {len(image)}")
                                                           ~~~^^^^^^^
TypeError: object of type 'NoneType' has no len()
2025-06-18 21:35:15.116 WARNING (SyncWorker_0) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg104.livestreaming.io.mi.com/hlstranscoder/GCA5NTI5OTczNmE3YmI0NzIyOGE3MGNhMTFmYWNkYmU2OBgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:35:24.300 WARNING (SyncWorker_1) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg21.livestreaming.io.mi.com/hlstranscoder/GCA5ZGZkNjUxY2Q0M2I0ZmFmOGEwOGMyZDYxNTJjNzJiNRgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:39:54.368 WARNING (SyncWorker_2) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg20.livestreaming.io.mi.com/hlstranscoder/GCAzOTY3MmIxYWI4ZTM0YzE1Yjg5ZjcxNzYyNGZiYWY4ZhgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:40:45.851 WARNING (SyncWorker_3) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg19.livestreaming.io.mi.com/hlstranscoder/GCBkYjViYWVjODk5MjA0NzZhODhhMjhhNDZjMjA0ZmQ2MRgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:45:15.866 WARNING (SyncWorker_1) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg21.livestreaming.io.mi.com/hlstranscoder/GCAzYzhmNjkzOWI1ODQ0ZGY5OGYwZDRjOWU0N2JkZmE2ZBgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:46:36.437 WARNING (SyncWorker_2) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg17.livestreaming.io.mi.com/hlstranscoder/GCA4MzBmODg1YjBhMzc0ODY0OTY3MDg0NjNkN2IyZjAzYhgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:49:42.355 WARNING (SyncWorker_0) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg21.livestreaming.io.mi.com/hlstranscoder/GCA3YzdkYTU5Y2YwOWY0MjBlOGRhY2UzZjUwN2U4MGFmYhgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
2025-06-18 21:54:12.280 WARNING (SyncWorker_1) [custom_components.xiaomi_miot.camera] IMILAB EC5 Floodlight Camera(chuangmi.camera.055c02): Get miot camera stream error from cloud: {'did': '1144491660', 'miid': 0, 'siid': 17, 'aiid': 1, 'code': 0, 'out': ['https://sg22.livestreaming.io.mi.com/hlstranscoder/GCA3MjJhZTliNzYwMmY0OGZjOWU4YTZjNTUwMjE1MzllOBgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'withLatency': 0}
