### ISSUE TITLE
xiaomi_miot is an invalid entity

### ISSUE THREAD

**Issue by Deusex-ai** [al-one/hass-xiaomi-miot#2549]
### Device model / 设备型号

chuangmi.camera.055c02

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.6.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Trying to configure add P2P Start/Stop for Imilab EC5 camera, which are not present in the camera entity:

For the code in customize.yaml:

xiaomi_miot:
  device_customizes:
    chuangmi.camera.055c02:
      sensor_properties: motion_event
      button_actions: start-p2p-stream,stop-p2p-stream
      chunk_properties: 1

I get following error:

The system cannot restart because the configuration is not valid: Invalid config for 'homeassistant' at customize.yaml, line 11: Entity ID xiaomi_miot is an invalid entity ID 'customize->xiaomi_miot', got {'device_customizes': {'chuangmi.camera.055c02': {'sensor_properties': 'motion_event', 'button_actions': 'start-p2p-stream,stop-p2p-stream', 'chunk_properties': 1}}}

And for code:

chuangmi.camera.055c02:
  sensor_properties: motion_event
  button_actions: start-p2p-stream,stop-p2p-stream
  chunk_properties: 1

I get following error:

The system cannot restart because the configuration is not valid: Invalid config for 'homeassistant' at customize.yaml, line 13: Entity ID chuangmi.camera.055c02 is an invalid entity ID 'customize->chuangmi.camera.055c02', got {'sensor_properties': 'motion_event', 'button_actions': 'start-p2p-stream,stop-p2p-stream', 'chunk_properties': 1}

### Entity attributes / 实体属性

```yaml
button.chuangmi_055c02_aa13_info
IMILAB EC5 Floodlight Camera Info
2025-06-18T18:17:33.090975+00:00	device_class: update
icon: mdi:information
friendly_name: IMILAB EC5 Floodlight Camera Info
button.info: IMILAB EC5 Floodlight Camera
model: chuangmi.camera.055c02
did: 1144491660
mac: 78:DF:72:E3:AA:13
lan_ip: 192.168.1.247
app_link: mihome://device?uid=6811182988&did=1144491660
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-055c02:2
available: true
home_room: 
updater: local
updated_at: 2025-06-19 21:14:51.877512+03:00
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 5
camera_control.wdr_mode: false
glimmer_full_color-2-6: true
camera_control.recording_mode: 0
camera_control.motion_tracking: true
camera_control.time_watermark: true
indicator_light.on: false
memory_card_management.status: 0
storage_total_space-4-2: 122120320
storage_free_space-4-3: 241984
storage_used_space-4-4: 0
motion_detection: true
motion_detection.alarm_interval: 3
detection_sensitivity-5-3: 1
motion_detection_start_time-5-4: 00:00:00
motion_detection_end_time-5-5: 23:59:00
stream_status-17-9: 1
stream_status-18-9: 1
fav_area: [{"idx":1,"pos":"[83,66]","active_time":"[16777215,16777215,16777215,16777215,16777215,16777215,16777215]","ver":1,"time":"0,24","rpt":"1,1,1,1,1,1,1"}]
fav_area.boundary_attr: [{"idx":1,"switch":1,"num":2,"L1":"44,54,30,97","D1":"44,54,30,97","L2":"44,57,67,74","D2":"44,57,67,74","sound_alarm":{"switch":0,"name":"1-alarm"},"light_alarm":{"switch":0,"param":"[1,10000,5,500,500]"}}]
fav_area.key_area_attr: [{"idx":1,"switch":1,"area":"[35,64,61,100]","sound_alarm":{"switch":0,"name":"1-alarm"},"light_alarm":{"switch":0,"param":"[1,10000,5,500,500]"}}]
fav_area.active_fav_area: 1
fav_area.motor_position: [83,66]
people_detect_attr-10-1: {"switch":1,"start_time":"00:00","end_time":"23:59"}
object_detect_attr-10-2: {"switch":1,"start_time":"00:00","end_time":"23:59"}
hotspot: {"switch_enable":"0","ap_switch":"0","ap_name":"xiaobaishexiangji","ap_passwd":"12345678"}
white_light_control: {"switch":0,"brightness":5}
brightness_on_night-13-2: 5
lock_region.lock_region_attr: {"lock_region":0,"legal_status":0}
camera_capacity: boundary,key_area,no_wired_network
sd_status.ejected: true
converters: button.info, light.indicator_light.on, sensor.memory_card_management.status, sensor.storage_free_space-4-3, sensor.storage_used_space-4-4, switch.camera_control.on, switch.camera_control.wdr_mode, switch.glimmer_full_color-2-6, switch.camera_control.motion_tracking, switch.camera_control.time_watermark, switch.indicator_light.on, switch.motion_detection, number.camera_control.image_rollover, number.motion_detection.alarm_interval, select.camera_control.night_shot, select.camera_control.recording_mode, select.detection_sensitivity-5-3
customizes: 
miot_cloud_action: true
sensor_properties: memory_card_management.status,storage_free_space,storage_used_space
select_properties: night_shot,recording_mode,detection_sensitivity
switch_properties: on,time_watermark,motion_tracking,motion_detection,wdr_mode,glimmer_full_color
number_properties: image_rollover,alarm_interval

info: null
state_updater: local
motion_video_time: 2025-06-19 21:06:45.672000
motion_video_type: ObjectMotion
stream_address: 
expire_at: 2025-06-19 21:18:21.111108
```
