### ISSUE TITLE
yeelight 螢幕燈的情境燈可以加入支援嗎?

### ISSUE THREAD

**Issue by kingwap99** [al-one/hass-xiaomi-miot#255]
[yeelink.light.lamp15](https://home.miot-spec.com/s/yeelink.light.lamp15) by yeelink
Yeelight智能显示器屏幕挂灯

在米家中有二個開關可用, 
一個是原來的螢幕燈, 另一個則為背後的情境燈
目前在 miot 中, 只可以看到第一個開關,
請問, 可以加入第2個情境燈嗎? 
非常感謝

**Comment by al-one** [comment]
该设备的[miot-spec规格](https://home.miot-spec.com/spec/yeelink.light.lamp15)中仅定义了一个`light`服务，未看到背景灯相关属性。
你可以参考 https://github.com/al-one/hass-xiaomi-miot/issues/218#issuecomment-964712557 此方法获取相关属性及使用[`xiaomi_miot.send_command`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)服务控制背景灯。

**Comment by luckystarwy** [comment]
这个灯，ha自带的yeelight不是可以识别成2个麽？我同款，正常使用好久了啊

**Comment by al-one** [comment]
https://gitlab.com/stavros/python-yeelight/-/blob/master/yeelight/main.py

根据`python-yeelight`库可以看出，背景灯的属性应该为`bg_power`，控制方法为`bg_set_power`。
可以通过[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)将该属性读取到实体的状态属性中：
```yaml
# customize.yaml
light.yeelink_lamp15_entity_id:
  miio_properties: bg_power
```

再通过[模板](https://www.home-assistant.io/integrations/light.template)创建一个灯实体：
```yaml
# configuration.yaml
light:
  - platform: template
    lights:
      yeelink_lamp15_bg:
        friendly_name: 屏幕挂灯背景灯
        value_template: |
          {{ state_attr('light.yeelink_lamp15_entity_id', 'miio.bg_power') == 'on' }}
        turn_on:
          service: xiaomi_miot.send_command
          data:
            entity_id: camera.isa_hlc7_1ab7
            method: bg_set_power
            params:
              - 'on'
        turn_off:
          service: xiaomi_miot.send_command
          data:
            entity_id: camera.isa_hlc7_1ab7
            method: bg_set_power
            params:
              - 'off'
```
