### ISSUE TITLE
xiaomi.diffuser.xw002 actions to add

### ISSUE THREAD

**Issue by Crickus** [al-one/hass-xiaomi-miot#2550]
### Device model / 设备型号

xiaomi.diffuser.xw002

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.6.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi
need your assistance to enable device manual fragrance action.
According to specs this value is available (fragrance-delivery).
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:diffuser:0000A01E:xiaomi-xw002:2:0000C82B

![Image](https://github.com/user-attachments/assets/9b756247-1b50-477c-9c52-964cb8a0d3e9)

As I understand it may be called with correct miot call action.

![Image](https://github.com/user-attachments/assets/eb15411e-b02c-4f5e-b7c5-f35beae1dc5c)

From the device page we may extract SIID and AIID. But what about entity ID?
This device doesn't have stand-alone domain entity. Only set of sensors and switch but any high level abstraction.

![Image](https://github.com/user-attachments/assets/210a580d-992e-42bf-a103-961f46604f6c)

Could you please suggest how it is possible to implement this activity triggering with your integration?

### Entity attributes / 实体属性

```yaml
button.info: Xiaomi Smart Scent Diffuser
model: xiaomi.diffuser.xw002
did: 1131990769
mac: E8:4A:54:71:4F:33
lan_ip: 5.248.16.30
app_link: mihome://device?uid=1738304897&did=1131990769
miot_type: urn:miot-spec-v2:device:diffuser:0000A01E:xiaomi-xw002:2:0000C82B
available: true
home_room: Home Sweet Home Ванная
icon: mdi:information
updater: cloud
updated_at: 2025-06-21 16:13:56.235817+03:00
diffuser.fault: false
diffuser.on: false
diffuser.fragrance_out_time: 6
diffuser-2.fragrance_out_time: 20
ambient_light.on: false
ambient_light.brightness: 79
ambient_light.color: 9564028
battery_level: 90
battery.charging_state: 2
other.auto_fragrance: false
other.auto_light: true
other.light_auto_off: false
converters: button.info, switch.diffuser.on, light.ambient_light.on, ambient_light.brightness, ambient_light.color, sensor.battery_level, sensor.battery.charging_state
customizes: 
{}

info: null
device_class: update
friendly_name: Xiaomi Smart Scent Diffuser Info
```
