### ISSUE TITLE
在最新修复下HomeKit中环境温度始终为21度，不反映温度变化

### ISSUE THREAD

**Issue by wqhqq1** [al-one/hass-xiaomi-miot#2552]
### Device model / 设备型号

090615.aircondition.ktf

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.6.1

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

虽然最新更改已经读取到setmode.roomtemp: 29，但仍需映射到current_temperature: null，方能正常被homekit读取
具体可参考下方实体属性信息

### Entity attributes / 实体属性

```yaml
hvac_modes: cool, off, heat, fan_only, auto, dry
min_temp: 16
max_temp: 32
target_temp_step: 1
fan_modes: 自动, 低风, 中风, 高风
friendly_name: 
supported_features: 393
current_temperature: null
temperature: 27
fan_mode: 低风
hvac_action: off
air_conditioner.mode: 0
air_conditioner.on: false
fan_control.fan_level: 1
target_temperature-2-4: 27
setmode.roomtemp: 29
```
