### ISSUE TITLE
lumi.gateway.mieu01 entities not working

### ISSUE THREAD

**Issue by Neuropsihopuppu** [al-one/hass-xiaomi-miot#2557]
### Device model / 设备型号

lumi.gateway.mieu01

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025.6.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Alarm and light entity does not work on lumi.gateway.mieu01

![Image](https://github.com/user-attachments/assets/7433bc24-30ad-4471-afdb-44fb2c74b4dd)

### Entity attributes / 实体属性

```yaml
switch.lumi_mieu01_1ec7_alarm 
light.lumi_mieu01_1ec7_light
```

**Comment by Neuropsihopuppu** [comment]
![Image](https://github.com/user-attachments/assets/63b35d08-bf1d-4eac-940a-791212d725c3)

alarm: false
friendly_name: Control Hub Alarm

![Image](https://github.com/user-attachments/assets/b4b645ad-63b7-4603-8aa9-a2b256d56692)


supported_color_modes:
  - onoff
color_mode: null
light.on: false
friendly_name: Control Hub Light
supported_features: 0

**Comment by redhatted** [comment]
I'm having the same exact problem. Device stopped working. It's working correctly through the Mi Home App.
I've removed and added it again multiple times with no result.

![Image](https://github.com/user-attachments/assets/d94f7d1b-0b5b-4bb2-b690-322b2df8d7a8)

**Comment by JGC-HA** [comment]
Hi, same problem here with this gateway: lumi.gateway.mieu01

Arm/disarm swith doesn´t work, it change the state in Home assistant but don´t perform the action in the gateway.

Same issue for light switch :(

**Comment by JGC-HA** [comment]
Just an update about this issue and my previous message. Sound bar to increase/decrease the volume of the gateway alarm works fine. Then problem is only with the arm/disarm switch and light switch. It is very strange because one of the three function works and the other two functions fail.

**Comment by fvbuelow** [comment]
> Just an update about this issue and my previous message. Sound bar to increase/decrease the volume of the gateway alarm works fine. Then problem is only with the arm/disarm switch and light switch. It is very strange because one of the three function works and the other two functions fail.

Exactly the same behaviour here.

**Comment by Neuropsihopuppu** [comment]
@al-one sorry to ping you directly but is it possible to get lumi.gateway.miru01 properly working with this integration?  The only other integration that supported this device no longer works because of xiaomi's new login method and the devs do not want to fix it

**Comment by al-one** [comment]
Provide the debug logs and perform the following actions in the developer tools:
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: button.lumi_mieu01_xxxx_info
  method: get_prop
  params: [doorbell_volume, gateway_volume, alarming_volume, doorbell_push]
```
```yaml
action: xiaomi_miot.send_command
data:
  entity_id: button.lumi_mieu01_xxxx_info
  method: get_prop
  params: [arming, rgb, night_light_rgb, arm_wait_time, corridor_light]
```

**Comment by ChrisVrekos** [comment]
Hi @al-one,

After multiple attempts, I have found a solution that works for the lumi.gateway.mieu01 (EU Version) using this integration.

First, here are the results of the get_prop commands you requested earlier:

Command 1: params: [doorbell_volume, gateway_volume, alarming_volume, doorbell_push] Result: [1, 100, 100, "off"]

Command 2: params: [arming, rgb, night_light_rgb, arm_wait_time, corridor_light] Result: ["off", 0, 0, 5, "off"]

The issue appears to be that the EU firmware blocks the modern guard-mode property (SIID 2), resulting in "Property not writable" errors when the integration tries to use it. However, the device does respond to the legacy set_arming method via the cloud.

I successfully got the Guard mode to trigger using the following command:
YAML

action: xiaomi_miot.send_command
data:
  entity_id: button.lumi_mieu01_xxxx_info
  method: set_arming
  params: ["on"]

Since I am new to Home Assistant, I am unsure how to implement this command as a button on my dashboard, or if it is possible to configure the integration to use this legacy method natively. Any help would be really appreciated!

**Comment by ChrisVrekos** [comment]
I've succed in making a button that can be added to configuration.yaml with the file editor add on but it is not perfect as it can't know the state of the arming here is the code (after adding it just restart home assitant and add a button card to your Dashboard : 
```
template:
- switch:
  - turn_on:
    - action: xiaomi_miot.send_command
      target:
        entity_id:
        - button.lumi_mieu01_xxxx_info
      data:
        method: set_arming
        params:
        - 'on'
    turn_off:
    - action: xiaomi_miot.send_command
      target:
        entity_id:
        - button.lumi_mieu01_xxxx_info
      data:
        method: set_arming
        params:
        - 'off'
    default_entity_id: switch.gateway_guard_manual
    icon: mdi:shield-lock
    name: Guard Mode Manual 
```

**Comment by redhatted** [comment]
> I've succed in making a button that can be added to configuration.yaml with the file editor add on but it is not perfect as it can't know the state of the arming here is the code (after adding it just restart home assitant and add a button card to your Dashboard :
> 
> ```
> template:
> - switch:
>   - turn_on:
>     - action: xiaomi_miot.send_command
>       target:
>         entity_id:
>         - button.lumi_mieu01_xxxx_info
>       data:
>         method: set_arming
>         params:
>         - 'on'
>     turn_off:
>     - action: xiaomi_miot.send_command
>       target:
>         entity_id:
>         - button.lumi_mieu01_xxxx_info
>       data:
>         method: set_arming
>         params:
>         - 'off'
>     default_entity_id: switch.gateway_guard_manual
>     icon: mdi:shield-lock
>     name: Guard Mode Manual 
> ```

Can confirm that this works!

Thank a lot!

**Comment by Neuropsihopuppu** [comment]
> I've succed in making a button that can be added to configuration.yaml with the file editor add on but it is not perfect as it can't know the state of the arming here is the code (after adding it just restart home assitant and add a button card to your Dashboard :
> 
> ```
> template:
> - switch:
>   - turn_on:
>     - action: xiaomi_miot.send_command
>       target:
>         entity_id:
>         - button.lumi_mieu01_xxxx_info
>       data:
>         method: set_arming
>         params:
>         - 'on'
>     turn_off:
>     - action: xiaomi_miot.send_command
>       target:
>         entity_id:
>         - button.lumi_mieu01_xxxx_info
>       data:
>         method: set_arming
>         params:
>         - 'off'
>     default_entity_id: switch.gateway_guard_manual
>     icon: mdi:shield-lock
>     name: Guard Mode Manual 
> ```

works perfectly thank you,can this be replicated to turn the light on and off also

light.lumi_mieu01_xxxx_light

**Comment by ChrisVrekos** [comment]
> > I've succed in making a button that can be added to configuration.yaml with the file editor add on but it is not perfect as it can't know the state of the arming here is the code (after adding it just restart home assitant and add a button card to your Dashboard :
> > ```
> > template:
> > - switch:
> >   - turn_on:
> >     - action: xiaomi_miot.send_command
> >       target:
> >         entity_id:
> >         - button.lumi_mieu01_xxxx_info
> >       data:
> >         method: set_arming
> >         params:
> >         - 'on'
> >     turn_off:
> >     - action: xiaomi_miot.send_command
> >       target:
> >         entity_id:
> >         - button.lumi_mieu01_xxxx_info
> >       data:
> >         method: set_arming
> >         params:
> >         - 'off'
> >     default_entity_id: switch.gateway_guard_manual
> >     icon: mdi:shield-lock
> >     name: Guard Mode Manual 
> > ```
> 
> works perfectly thank you,can this be replicated to turn the light on and off also
> 
> light.lumi_mieu01_xxxx_light
Here is a polished, professional version of your message for the GitHub issue. It clearly presents your findings about the light, the interchangeable Entity IDs, and asks the developer the "Golden Question" about fixing the native entities.

Copy and paste this into the GitHub issue:

Yes, this can absolutely be replicated for the light!

The issue is identical to the alarm: the firmware ignores the standard "Turn On" command (set_properties) but still obeys the legacy set_rgb command. To turn it on, we have to send a specific integer that combines the Color and Brightness.

I verified this with the following command (which forces the light to Warm White at 100% brightness):


```
action: xiaomi_miot.send_command
target:
  # I found that ANY entity from the device works as a target 
  # (button.info, light.light, switch.alarm, etc.)
  entity_id: button.lumi_mieu01_xxxx_info 
data:
  method: set_rgb
  # Formula: (Brightness_Percent * 16777216) + Decimal_Color
  # This number (1694498815) = 100% Brightness + Warm White
  params: [1694498815]
```

My question is if there is a way to configure device_customizes to alter the native entities so they use these legacy commands (set_arming and set_rgb) by default?

Right now, I have to create custom Template Switches to wrap these commands. I tried using  Customizing entities / devices  with something like this 

 `miot_local: false
switch_properties: arming, alarm, corridor_light, mute
number_properties: volume, arming_time
sensor_properties: arming
light_services: light
`
which  failed to make the already existing entitites work correctly (I don't fully understand what the Customizing entities / devices does to the entitites)
, the native Light and Switch entities I'm guessing still persist in trying to use the broken MIoT properties (SIID 2/4) instead of the working legacy methods. @al-one I believe is the only one that can help us in this case.
