### ISSUE TITLE
WalkingPad A1

### ISSUE THREAD

**Issue by dmatora** [al-one/hass-xiaomi-miot#261]
Changelog says WalkingPad is supported, but when I add it with ip and token (whenever I enable cloud or not) I just get one sensor and it's not available. At the same time WalkingPad does respond to network requests

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/647062/143688043-0df9138c-1f9f-444d-babe-11b98b0f0992.png">

**Comment by al-one** [comment]
Check for the device related [logs](https://my.home-assistant.io/redirect/logs).

**Comment by dmatora** [comment]
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.sensor
Source: custom_components/xiaomi_miot/__init__.py:1086 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 16:22:55 (99 occurrences) 
Last logged: 17:12:00

Xiaomi Miot Walking Pad Status: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'walking_pad.on': {'siid': 2, 'piid': 1}, 'walking_pad.mode': {'siid': 2, 'piid': 2}, 'walking_pad.status': {'siid': 2, 'piid': 3}, 'walking_pad.speed_level': {'siid': 2, 'piid': 4}, 'walking_pad.current_distance': {'siid': 2, 'piid': 5}, 'walking_pad.working_time': {'siid': 2, 'piid': 6}, 'walking_pad.current_step_count': {'siid': 2, 'piid': 7}, 'current_calorie_consumption-2-8': {'siid': 2, 'piid': 8}}, max_properties: 9/8

**Comment by al-one** [comment]
It seems that your device may not support local mode. It is recommended that you integrate it through Xiaomi account (Automatic mode).

**Comment by dmatora** [comment]
I have no issue controlling device using miiocli, if that's what you're talking about

**Comment by dmatora** [comment]
Well, I tried Automatic mode and it helped.
Except that it won't poll or update speed

**Comment by al-one** [comment]
> I have no issue controlling device using miiocli, if that's what you're talking about

You can control through `miiocli` because it uses the `miio` protocol, not the `miot` protocol used by this component. If you want to integrate it through this component, Xiaomi cloud is required.

------

>  Except that it won't poll or update speed

Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states) of this entity.

**Comment by dmatora** [comment]
options:
  - '0.5'
  - '1.0'
  - '1.5'
  - '2.0'
  - '2.5'
  - '3.0'
  - '3.5'
  - '4.0'
  - '4.5'
  - '5.0'
  - '5.5'
  - '6.0'
entity_class: MiotSelectSubEntity
parent_entity_id: sensor.ksmb_v1_d595_walking_pad_2
service_description: Walking Pad
property_description: Speed Level
walking_pad.speed_level: 1
unit_of_measurement: km/h
friendly_name: WalkingPad Walking Pad Speed Level
supported_features: 0

**Comment by al-one** [comment]
Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states) of `sensor.ksmb_v1_d595_walking_pad_2`.

**Comment by dmatora** [comment]
model: ksmb.walkingpad.v1
lan_ip: 192.168.1.50
mac_address: 04:CF:8C:81:D5:95
firmware_version: 2.0.5
hardware_version: ''
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:walking-pad:0000A018:ksmb-v1:1
state_property: walking_pad.status
walking_pad.on: true
walking_pad.mode: 0
walking_pad.status: 1
walking_pad.speed_level: 1
walking_pad.current_distance: 170
walking_pad.working_time: 638
walking_pad.current_step_count: 546
current_calorie_consumption-2-8: 10570
state_updater: cloud
walking_pad.status_desc: Run
sub_entities:
  - walking_pad-2.current_distance-5
  - walking_pad-2.working_time-6
  - walking_pad-2.current_step_count-7
  - walking_pad-2.current_calorie_consumption-8
  - walking_pad-2.mode-2
  - walking_pad-2.speed_level-4
  - walking_pad-2.on-1
friendly_name: WalkingPad Walking Pad Status
supported_features: 0

**Comment by al-one** [comment]
There seems to be no issue.

**Comment by dmatora** [comment]
There I obvious mismatch between 1 and 1.0
1. When speed is 0.5 it's shown on UI, when speed is 1 - it's not
<img width="325" alt="image" src="https://user-images.githubusercontent.com/647062/143817902-c649c5e7-3a90-4294-bfc4-5d80cc7ab816.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/647062/143817963-dcc93fdb-62b9-41ad-b2a4-7107cd0f19db.png">
2. Besides that only 1 of 3 controls are working, changing speed or mode has no effect

**Comment by al-one** [comment]
> 1. When speed is 0.5 it's shown on UI, when speed is 1 - it's not

Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/47a39fc068e54072b7343a7d9b80377800d98844

------

> 2. Besides that only 1 of 3 controls are working, changing speed or mode has no effect

Are there any [logs](https://my.home-assistant.io/redirect/logs) after change mode.

**Comment by dmatora** [comment]
Well, actually mode works, but it's label is misleading (changing manual to standby, not auto)
Speed does't work, log after changing speed is
Updating xiaomi_miot sensor took longer than the scheduled update interval 0:00:30

**Comment by al-one** [comment]
The label of working mode is from [miot-spec](https://home.miot-spec.com/spec/ksmb.walkingpad.v1). if you want to change it, you can configure `translations`.
```yaml
# configuration.yaml
xiaomi_miot:
  translations:
    walking_pad.mode:
      none: manual
      auto: standby
```

------

>  Updating xiaomi_miot sensor took longer than the scheduled update interval 0:00:30

This log has nothing to do with setting the speed. Maybe you can try to upgrade to the master branch, which will generate a `number` entity for the speed level, and the old `select` entity will become invalid and can be deleted.

**Comment by dmatora** [comment]
Ok, I was wrong, "auto" is labeled currently (was checking at custom app which displays it wrong)
Latest master fixes both read and write for the speed, although I'm not a big fan if number entity UI, since it requires extra effort to see the value, personally I'd prefer a dropdown

**Comment by dmatora** [comment]
Is there no way you could add autostart on/off toggle and selecting autostart speed? Both features are available over miio protocol

**Comment by dmatora** [comment]
Also is there a way to specify poll frequency? right now it's not very frequent

**Comment by al-one** [comment]
> Is there no way you could add autostart on/off toggle and selecting autostart speed? Both features are available over miio protocol

Sorry for my English, I don't quite understand this sentence.

**Comment by al-one** [comment]
> Also is there a way to specify poll frequency? right now it's not very frequent

```yaml
# customize.yaml
sensor.ksmb_v1_d595_walking_pad_2:
  interval_seconds: 20 # seconds
```

> [Customization Using The UI](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui)

**Comment by dmatora** [comment]
>Sorry for my English, I don't quite understand this sentence.
Two most critical features are still missing
1. set autostart speed
2. enable/disable autostart

**Comment by al-one** [comment]
They don't seem to be defined in the [miot-spec](https://home.miot-spec.com/spec/ksmb.walkingpad.v1) of the device, but maybe you can call them through service: [`xiaomi_miot.send_command`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command):

```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.ksmb_v1_d595_walking_pad_2
  method: miio_method
  params: []
```

**Comment by dmatora** [comment]
That works!
```
 method: set_auto
 params: [0]
```
does disable autostart
and
```
 method: set_auto
 params: [0]
```
does enable it
do you think this can be added to ui within the component?

**Comment by al-one** [comment]
Get miio state to entity attributes:
```yaml
# customize.yaml
sensor.ksmb_v1_d595_walking_pad_2:
  sensor_properties: auto
```

Create a switch entity via [template](https://www.home-assistant.io/integrations/switch.template):
```yaml
# configuration.yaml
switch:
  - platform: template
    switches:
      skylight:
        value_template: |
          {{ state_attr('sensor.ksmb_v1_d595_walking_pad_2', 'miio.auto') | int == 1 }}
        turn_on:
          service: xiaomi_miot.send_command
          data:
            entity_id: sensor.ksmb_v1_d595_walking_pad_2
            method: set_auto
            params: [1]
        turn_off:
          service: xiaomi_miot.send_command
          data:
            entity_id: sensor.ksmb_v1_d595_walking_pad_2
            method: set_auto
            params: [0]
```

**Comment by dmatora** [comment]
is there a way to set units for steps?
Time has units and it's history is show as graph
<img width="400" alt="image" src="https://user-images.githubusercontent.com/647062/144200000-41c02b1d-fae4-44a7-8d7f-b7d269ebdab4.png">
steps don't have units and it's history is useless
<img width="399" alt="image" src="https://user-images.githubusercontent.com/647062/144200172-bfa8ed78-d843-40a0-bbc4-403793c12164.png">

**Comment by al-one** [comment]
Set `unit_of_measurement` via [customization](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui).

**Comment by dmatora** [comment]
When I add
```
sensor.ksmb_v1_d595_walking_pad_2:
  sensor_properties: auto
``` to customise integration stops working
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/647062/144290274-023b0c44-ac76-4166-97e5-8e0100b2003d.png">
this is what I get in log
```
Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:163 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 8:34:00 PM (48 occurrences) 
Last logged: 9:13:03 PM

Request miot api: miotspec/prop/get {'params': [{'did': '130967143', 'siid': 2, 'piid': 1}, {'did': '130967143', 'siid': 2, 'piid': 2}, {'did': '130967143', 'siid': 2, 'piid': 3}, {'did': '130967143', 'siid': 2, 'piid': 4}, {'did': '130967143', 'siid': 2, 'piid': 5}, {'did': '130967143', 'siid': 2, 'piid': 6}, {'did': '130967143', 'siid': 2, 'piid': 7}, {'did': '130967143', 'siid': 2, 'piid': 8}]} failed, result: None
Request miot api: miotspec/prop/get {'params': [{'did': '120524991', 'siid': 2, 'piid': 3}]} failed, result: None
```

**Comment by al-one** [comment]
These logs are not associated with this custom attribute. The Xiaomi cloud API sometimes returns empty data. Maybe it is busy.

**Comment by al-one** [comment]
Does it work ?

**Comment by dmatora** [comment]
Well, sort of. 
1. I can't get reading on autostart, but write works. 
2. Reading on speed only works when i write from another app, while home assistant reads it. 
3. Sometimes all reading stops until I reload the integration.

**Comment by dmatora** [comment]
I've implemented an automation that reloads integration if walkingpad status hasn't updated in 10 minutes
That seems to be solving "reading stops" issue

**Comment by dmatora** [comment]
I guess 10 minutes is too often it ends with 
```
Error while executing request to https://api.io.mi.com/app/miotspec/prop/get :HTTPSConnectionPool(host='api.io.mi.com', port=443): Max retries exceeded with url: /app/miotspec/prop/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa902b00040>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by al-one** [comment]
I sometimes get similar errors. I guess the Xiaomi server may be too busy, or you are not using the nearest server.

**Comment by al-one** [comment]
About get miio state to entity attributes: https://github.com/al-one/hass-xiaomi-miot/issues/261#issuecomment-982541120

```yaml
# customize.yaml
sensor.ksmb_v1_d595_walking_pad_2:
  miio_properties: auto
```
I updated the custom attribute name, please try again.

**Comment by dmatora** [comment]
I pulled latest master and then realised I was doing `sensor_properties: auto` instead of `miio_properties: auto`
tried `miio_properties: auto` and it seems to be working

**Comment by dmatora** [comment]
tried changing it to `miio_properties: auto,start_speed` and now I'm not getting state on any of two

**Comment by al-one** [comment]
Like this: https://github.com/rytilahti/python-miio/issues/797#issuecomment-770154446

`raw_command get_prop '["auto", "start_speed"]'` returns ?

**Comment by dmatora** [comment]
that returns error, all readings can only be called separately

**Comment by al-one** [comment]
Upgrade to master branch, and try:
```yaml
# customize.yaml
sensor.ksmb_v1_d595_walking_pad_2:
  miio_commands:
    - method: get_prop
      params: ['auto']
      values: ['auto']
    - method: get_prop
      params: ['start_speed']
      values: ['start_speed']
```

**Comment by dmatora** [comment]
reading auto stopped working, here is new state
```
model: ksmb.walkingpad.v1
lan_ip: 192.168.1.50
mac_address: 04:CF:8C:81:D5:95
entity_class: MiotSensorEntity
home_room: Новая Bedroom
miot_type: urn:miot-spec-v2:device:walking-pad:0000A018:ksmb-v1:1
state_property: walking_pad.status
walking_pad.on: true
walking_pad.mode: 0
walking_pad.status: 0
walking_pad.speed_level: 0.5
walking_pad.current_distance: 0
walking_pad.working_time: 3
walking_pad.current_step_count: 0
current_calorie_consumption-2-8: 0
state_updater: cloud
walking_pad.status_desc: Stop
sub_entities:
  - walking_pad-2.current_distance-5
  - walking_pad-2.working_time-6
  - walking_pad-2.current_step_count-7
  - walking_pad-2.current_calorie_consumption-8
  - walking_pad-2.mode-2
  - walking_pad-2.speed_level-4
  - walking_pad-2.on-1
friendly_name: WalkingPad Walking Pad Status
supported_features: 0
miio_commands:
  - method: get_prop
    params:
      - auto
    values:
      - auto
  - method: get_prop
    params:
      - start_speed
    values:
      - start_speed
```

**Comment by al-one** [comment]
The log is not associated with the changes. The Xiaomi cloud API returned null data.
Have you upgraded to the master branch?

**Comment by dmatora** [comment]
I did

**Comment by al-one** [comment]
Upgrade to master branch again, and try:
```yaml
# customize.yaml
sensor.ksmb_v1_d595_walking_pad_2:
  miio_commands:
    - method: get_prop
      params: ['auto']
    - method: get_prop
      params: ['start_speed']
```

**Comment by al-one** [comment]
Does it work ?

**Comment by dmatora** [comment]
Well since I updated master I can't get walkingpad working at all.
I was hoping it's just a temporary server problem, but it's been dead for a few days

**Comment by dmatora** [comment]
But it would be really awesome to be able to specify props I want to bу red and written using miio protocol, (is that what you just implemented?) since devices like walkingpad can not be added to local server (tried both Russia and UK and it's not supported) and connection with China server from Russia is very poor (not to mentioned local performance is always much better than cloud).

I have other devices that can only be added to China server and they keep failing off.

**Comment by al-one** [comment]
Do you know what the miio properties corresponding to each property [here](https://home.miot-spec.com/spec/ksmb.walkingpad.v1) is ?

```yaml
on: true # ?
mode: 0 # mode or auto ?
status: 0 # ?
speed_level: 0.5 # start_speed
current_distance: 0 # dist
working_time: 3 # time
current_step_count: 0 # step
current_calorie_consumption: 0 # cal
```
