### ISSUE TITLE
如何通过HA服务重载插件的集成配置？

### ISSUE THREAD

**Issue by sctale** [al-one/hass-xiaomi-miot#264]
如题情况，能否在未来版本增加重启插件的service。这样就能在HA设个检测的传感器，真的有问题就重启插件。

**Comment by al-one** [comment]
HA内置了重载集成配置的服务：
```yaml
service: homeassistant.reload_config_entry
data
  entity_id: sensor.xiaomi_miot_entity_id # 任意想重载集成所属的实体ID
```

或者：
```yaml
service: homeassistant.reload_config_entry
data:
  entry_id: xxxxxx # 集成配置ID
```
