### ISSUE TITLE
nwt.derh.wdh318efw1 does not alert when tank is full

### ISSUE THREAD

**Issue by shift-del1** [al-one/hass-xiaomi-miot#283]
The [dehumidifier](https://home.miot-spec.com/s/nwt.derh.wdh318efw1)'s alarm attribute is always 'false', even when the tank is full or removed. Latest integration, firmware installed, cloud mode is used. Thank you.

**Comment by al-one** [comment]
The value of this attribute comes from Xiaomi cloud. I'm not sure it contains these fault information.

**Comment by shift-del1** [comment]
I'm talking abou this:
![IMG_20211207_202045](https://user-images.githubusercontent.com/63366470/145093317-713a8260-fdac-4102-9bbe-f02c800e63b9.jpg)
In Mi Home (using the cloud too), the alarm is shown as below:
![IMG_20211207_203154](https://user-images.githubusercontent.com/63366470/145094272-6ce6e12a-7dfc-48ee-8cb4-bd1d4ddc8e1a.jpg)
In the MIoT specs, there is a separate section for alarm, is it possible to use that somehow?

**Comment by al-one** [comment]
```json
{
    "iid": 4,
    "type": "urn:miot-spec-v2:service:alarm:00007804:nwt-wdh318efw1:1",
    "description": "Alarm",
    "properties": [{
        "iid": 1,
        "type": "urn:miot-spec-v2:property:alarm:00000012:nwt-wdh318efw1:1",
        "description": "Alarm",
        "format": "bool",
        "access": ["read", "write", "notify"]
    }]
}
```

This is the `alarm` service defined in [miot-spec](https://home.miot-spec.com/spec/nwt.derh.wdh318efw1), which has only one property `alram: false`.

**Comment by shift-del1** [comment]
So it means unless Xiaomi enhances the specification, dehumidifier won't be able to notify the user with MIoT when the tank is full? Minus 1 functon compared to MiIO :-/ Anyway, thank you for your great work.

**Comment by al-one** [comment]
Yes ! Or you can refer to this way to obtain miio props: https://github.com/al-one/hass-xiaomi-miot/issues/242#issuecomment-989453399

**Comment by shift-del1** [comment]
Thanks for the idea, I extracted from the log the moment, when the alarm is triggered (tank gets full, fan stops):

2021-12-10 21:39:08 -> {"id":5503,"method":"get_prop","params":["auto","defrost_status","tank_full","fan_speed","child_lock","led","buzzer","fan_st","mode","on_off","humidity"]}
2021-12-10 21:39:08 <- {"code":0,"exe_time":200,"id":5503,"otlocalts":1639168743282003,"result":[50,"off","off",2,"off","on","off",2,"on","on",40]}
2021-12-10 21:39:13 -> {"id":5504,"method":"get_prop","params":["auto","defrost_status","tank_full","fan_speed","child_lock","led","buzzer","fan_st","mode","on_off","humidity"]}
2021-12-10 21:39:13 <- {"code":0,"exe_time":160,"id":5504,"otlocalts":1639168748346372,"result":[50,"off","on",0,"off","on","off",2,"on","on",40]}

Can you please help and build the customization? I have no experience wth this (but I tried to understand your instructions/example). Thank you.

**Comment by al-one** [comment]
Add this [custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities):
```yaml
# customize.yaml
humidifier.nwt_wdh318efw1_entity_id:
  miio_properties: auto,defrost_status,tank_full,fan_speed,child_lock,led,buzzer,fan_st,mode,on_off,humidity
```

Create sensor entities via [template](https://www.home-assistant.io/integrations/template):
```yaml
# configuration.yaml
template:
  - trigger:
      - platform: state
        entity_id: humidifier.nwt_wdh318efw1_entity_id
        attribute: miio.tank_full
    binary_sensor:
      - name: nwt_wdh318efw1_tank_full
        state: |
          {{ trigger.to_state.attributes['miio.tank_full'] | default == 'on'  }}
```

**Comment by shift-del1** [comment]
I added the 2 sections after modifying the entity name. The miio_properties appeared under the entity:
![IMG_20211212_111853](https://user-images.githubusercontent.com/63366470/145708703-d5b2d8f0-6110-46b1-a614-70993a090500.jpg)
However the binary sensor remained empty and not updated when I removed the tank:
![IMG_20211212_111947](https://user-images.githubusercontent.com/63366470/145708716-5a0a7e82-107f-4933-bda7-fda56c1c52e8.jpg)
Is there anything else I need to do (automation, service call etc.)? Thank you.

**Comment by al-one** [comment]
> ![IMG_20211212_111853](https://user-images.githubusercontent.com/63366470/145708703-d5b2d8f0-6110-46b1-a614-70993a090500.jpg)

Show me all attributes of the entity.

**Comment by al-one** [comment]
Make sure your HA can access the device IP and check the relevant [logs](https://my.home-assistant.io/redirect/logs).

**Comment by shift-del1** [comment]
HA is on the same subnet as the dehumidifier, no firewall, no filtering etc. Here is the full list of attributes:
![IMG_20211214_210823](https://user-images.githubusercontent.com/63366470/146072148-9a54f39f-7401-4277-ac1c-8ff9d7e89fdf.jpg)
and here is the error I got after enabled logging:
![IMG_20211214_210700](https://user-images.githubusercontent.com/63366470/146072219-e1b6816a-7e59-4d3a-9951-03959d23c2e9.jpg)

**Comment by al-one** [comment]
This device may not be able to get multiple properties at once. Please try:
```yaml
# customize.yaml
humidifier.nwt_wdh318efw1_entity_id:
  miio_properties: tank_full
```
