### ISSUE TITLE
Zone/Room cleaning on Dreame D9

### ISSUE THREAD

**Issue by fewdji** [al-one/hass-xiaomi-miot#289]
Hi!
I can't get zone/room cleaning to work on my Dreame D9.

When I start room cleaning I get this log from modified MiHome (by vevs):
`-> {"id":8483,"method":"action","params":{"did":"382836840","siid":4,"aiid":1,"in":[{"piid":1,"value":18},{"piid":10,"value":"{\"selects\":[[3,1,3,3,1]]}"}]}}`
or zone:
`-> {"id":8408,"method":"action","params":{"did":"382836840","siid":4,"aiid":1,"in":[{"piid":1,"value":19},{"piid":10,"value":"{\"areas\":[[-970,-339,24,410,2,3,3]]}"}]}}`

But when I trying call service with this params - I got error with code -1 in notification.
<img width="256" alt="1" src="https://user-images.githubusercontent.com/13124598/145124457-2ce63b53-b139-48a4-a60c-55f0f2be5152.png">
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_d9
  did: 382836840
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[3,1,3,3,1]]}'
  throw: true
```

Without params it works like simple cleaning of all square.

What is correct way to call xiaomi_miot.call_action with params?

**miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2009:2**

**Comment by al-one** [comment]
Maybe it's similar to https://github.com/al-one/hass-xiaomi-miot/issues/279#issuecomment-987744629 .

`start-clean` action only have one param in [miot-spec](https://home.miot-spec.com/spec/dreame.vacuum.p2009), but there are two in your Mihome logs.

You need use this command:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_d9
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[3,1,3,3,1]]}'
  force_params: true # don't format params
```

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_d9
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 19
    - piid: 10
      value: '{"areas":[[-970,-339,24,410,2,3,3]]}'
  force_params: true
```
