### ISSUE TITLE
Smartmi Humidifier (zhimi.humidifier.ca1)

### ISSUE THREAD

**Issue by dmatora** [al-one/hass-xiaomi-miot#292]
Model: [zhimi.humidifier.ca1](https://home.miot-spec.com/s/zhimi.humidifier.ca1)

Water level renders as binary sensor, while in fact it's a number (range of 0-120)
<img width="993" alt="image" src="https://user-images.githubusercontent.com/647062/145207326-a7bef71a-9a53-473f-8daa-4f59b62ae1e5.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/647062/145207433-e1abf774-f2f1-4b8e-9e30-7a80bccdc194.png">

**Comment by al-one** [comment]
I think it's time to implement it with number entity.

**Comment by al-one** [comment]
Please upgrade to master branch.

**Comment by dmatora** [comment]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/647062/145372286-60d2c49e-dbb2-4d8d-a5d0-856dc4d5b751.png">
Much better. Shouldn't it be sensor (read only) instead of input though?

**Comment by dmatora** [comment]
Added
```
humidifier.zhimi_ca1_bcd0_humidifier:
  sensor_properties: water_level
sensor.zhimi_ca1_bcd0_water_level:
  icon: mdi:waves-arrow-up
```
Looks much better. Would be nice to have it out of the box, so that people don't have to go through all of humidifiers (I currently have 7 in my house) and customise them all
<img width="996" alt="image" src="https://user-images.githubusercontent.com/647062/145522539-e2c44793-451b-4908-a379-67bceca4d139.png">

**Comment by dmatora** [comment]
I tried to change it to 
```
humidifier.zhimi_ca1_bcd0_humidifier:
  check_lan: true
  sensor_properties: water_level
```
and reloaded home assistant but state still says `state_updater: cloud` is that normal?

**Comment by al-one** [comment]
> Looks much better, thank you. Would be nice to have it out of the box, so that people don't have to go through all of humidifiers (I currently have 7 in my house) and customise them all

```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    '*.humidifier.*':
      sensor_properties: water_level
```

However, the `icon` still needs to be customized for each entity in `customize.yaml`.

----

> and reloaded home assistant but state still says state_updater: cloud is that normal?

I don't think the [humidifier](https://home.miot-spec.com/s/zhimi.humidifier.ca1) supports local miot protocol because it was produced in earlier years.
