### ISSUE TITLE
yeelink.light.bslamp2 moonlight/night mode

### ISSUE THREAD

**Issue by manymuch** [al-one/hass-xiaomi-miot#301]
Is there a way to enable moonlight/night mode for [yeelink.light.bslamp2](https://home.miot-spec.com/s/yeelink.light.bslamp2) ?

There is a night mode in Xiaomi App or Yeelight App.

This is not possible by setting value of brightness or color, as the brightness of "night mode" is obviously lower than smallest brightness value in normal mode.
There is a relavant conversaion:
Ref: https://community.home-assistant.io/t/xiaomi-yeelight-bedside-lamp-color-state/71617/7
By using LAN control and Yeelight integration, it seems possible to enable moonlight mode via HA, however as Firmware updated, Yeelight block LAN control so this methods is no longer available.

Thanks for any advice!

有没有办法打开米家床头灯的夜灯模式

**Comment by al-one** [comment]
Try this [service](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command):
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: light.yeelink_bslamp2_entity_id
  method: set_ps
  params:
    - nightlight
    - 'on'
```
