### ISSUE TITLE
大神你好，我想把净水器的水质数据转化成光照强度，单位是流明，让homekit能识别，需要怎么修改哪个配置文件，怎么修改，小白请多指教

### ISSUE THREAD

**Issue by SUNDONG1996** [al-one/hass-xiaomi-miot#339]
sensor.yunmi_s14_5cd9_total_dissolved_solids_for_output_water

**Comment by al-one** [comment]
你需要为该实体添加[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)：
```yaml
# customize.yaml
sensor.yunmi_s14_5cd9_total_dissolved_solids_for_output_water:
  device_class: illuminance
  unit_of_measurement: lx
```

![image](https://user-images.githubusercontent.com/4549099/148529693-1276a694-423d-432b-8923-dbf160e849a9.png)
