### ISSUE TITLE
tinymu.toiletlid.v1（小沐智能马桶盖）本地模式不可用，远端模式状态不更新

### ISSUE THREAD

**Issue by maybeloveu** [al-one/hass-xiaomi-miot#343]
设备型号：[tinymu.toiletlid.v1（小沐智能马桶盖）](https://home.miot-spec.com/s/tinymu.toiletlid.v1)
问题现象：本地模式不可用，远端模式状态不更新。
希望增加这个设备支持

**Comment by al-one** [comment]
最新的提交中为该设备适配了本地模式，请更新到master分支后通过自动模式接入。

**Comment by maybeloveu** [comment]
> 最新的提交中为该设备适配了本地模式，请更新到master分支后通过自动模式接入。

本地模式已经可用，但是状态不更新。之前下面的插件可以用，但是hass更新后就不行了。提供他给大神参考。
https://github.com/scp10011/xiaomi_toiletlid

**Comment by maybeloveu** [comment]
binary_sensor.tinymu_v1_eb57_seat 状态一直为OFF,有人使用时也是off。
属性如下：
model: tinymu.toiletlid.v1
lan_ip: 192.168.3.XX
mac_address: 7C:49:EB:11:XX:XX
entity_class: MiotToiletEntity
home_room: 卫生间
miot_type: urn:miot-spec-v2:device:toilet:0000A02E:tinymu-v1:1
state_property: null
seat.status: 0
seat.seating_state: false
filter.filter_used_time: 0
filter.filter_used_flow: 0
state_updater: lan
sub_entities: filter-2.filter_used_time-1, filter-2.filter_used_flow-2
icon: mdi:toilet
friendly_name: 马桶盖 Seat
supported_features: 0

**Comment by al-one** [comment]
请在你的配置文件中添加下面的配置并获取日志给我：
```yaml
# configuration.yaml
logger:
  default: warning
  logs:
    custom_components.xiaomi_miot.core.miio2miot: debug
```

或者使用下面的服务（无需重启）：
```yaml
service: logger.set_level
data:
  custom_components.xiaomi_miot.core.miio2miot: debug
```

**Comment by maybeloveu** [comment]
2022-01-06 10:50:31 INFO (SyncWorker_22) [custom_components.xiaomi_miot.core.miio2miot] Got miio props for miot: ['192.168.3.26', {'filter_use_time': 0, 'filter_use_flux': 0, 'work_state': 1}]
2022-01-06 10:51:01 INFO (SyncWorker_28) [custom_components.xiaomi_miot.core.miio2miot] Got miio props for miot: ['192.168.3.26', {'filter_use_time': 0, 'filter_use_flux': 0, 'work_state': 1}]
2022-01-06 10:51:31 INFO (SyncWorker_56) [custom_components.xiaomi_miot.core.miio2miot] Got miio props for miot: ['192.168.3.26', {'filter_use_time': 0, 'filter_use_flux': 0, 'work_state': 1}]
2022-01-06 10:53:01 INFO (SyncWorker_22) [custom_components.xiaomi_miot.core.miio2miot] Got miio props for miot: ['192.168.3.26', {'filter_use_time': 0, 'filter_use_flux': 0, 'work_state': 1}]

期间我在马桶盖上坐了一下，看日志，状态都是1

**Comment by al-one** [comment]
请再尝试坐在马桶上与不坐时执行下面的服务，并查看HA通知中的结果：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: binary_sensor.tinymu_v1_eb57_seat
  method: get_prop
  params:
    - work_state
    - filter_use_flux
    - filter_use_time
  throw: true
```
