### ISSUE TITLE
yeelink.light.lamp4 not working any more

### ISSUE THREAD

**Issue by rirofal** [al-one/hass-xiaomi-miot#353]
Can't control my desktop light any more... 

[yeelink.light.lamp4](https://home.miot-spec.com/s/yeelink.light.lamp4)
Firmware: 2.1.7_0017

This is the HA-log:
`
2022-01-04 10:32:13 ERROR (MainThread) [custom_components.xiaomi_miot.light] Mi LED Desk Lamp 1S Light: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}, 'light_extension.ct_adjust_alexa': {'siid': 3, 'piid': 3}}, max_properties: 9/7
`

**Comment by al-one** [comment]
Please try this configuration:
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    yeelink.light.lamp4:
      exclude_miot_services: light_extension
```

> [⚙️  Configuration](https://my.home-assistant.io/redirect/config) > [Server Controls](https://my.home-assistant.io/redirect/server_controls) > YAML configuration reloading > `XIAOMI MIOT AUTO`

**Comment by rirofal** [comment]
No luck...

HA-Log:

`2022-01-04 12:51:31 ERROR (MainThread) [custom_components.xiaomi_miot.light] Mi LED Desk Lamp 1S Light: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}}, max_properties: 7/4
`

**Comment by al-one** [comment]
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    yeelink.light.lamp4:
      chunk_properties: 2
      exclude_miot_services: light_extension
```

**Comment by rirofal** [comment]
`2022-01-04 13:05:04 ERROR (MainThread) [custom_components.xiaomi_miot.light] Mi LED Desk Lamp 1S Light: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}, 'light_extension.ct_adjust_alexa': {'siid': 3, 'piid': 3}}, max_properties: 2/7`

**Comment by al-one** [comment]
Does `exclude_miot_services: light_extension` still exist in your configuration ?

```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    yeelink.light.lamp4:
      chunk_properties: 1
      exclude_miot_services: light_extension
```

**Comment by rirofal** [comment]
Nope, using the UI for this integration. Only this lamp that is included (did try to uninstall, restart, install).

`2022-01-04 13:11:32 ERROR (MainThread) [custom_components.xiaomi_miot.light] Mi LED Desk Lamp 1S Light: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}, 'light_extension.ct_adjust_alexa': {'siid': 3, 'piid': 3}}, max_properties: 1/7`

**Comment by rirofal** [comment]
Ehm... well, it (exclude...) exists in that snippet you pasted.

**Comment by al-one** [comment]
Show me your configuration.yaml contains `xiaomi_miot:`.

**Comment by rirofal** [comment]
Installed via UI
Added only this lamp

```yaml
xiaomi_miot:
  device_customizes:
    yeelink.light.lamp4:
      chunk_properties: 1
      exclude_miot_services: light_extension
````

Generates this log:
`2022-01-04 13:17:08 ERROR (MainThread) [custom_components.xiaomi_miot.light] Mi LED Desk Lamp 1S Light: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}}, max_properties: 1/4`
