### ISSUE TITLE
viomi.waterheater.e1

### ISSUE THREAD

**Issue by soulthiefer** [al-one/hass-xiaomi-miot#375]
Good evening!  device [viomi.waterheater.e1](https://home.miot-spec.com/s/viomi.waterheater.e1).  does not show the current temperature and water-level.  the current temperature is always 0 , water-level does not show anywhere at all.  how to fix it, tell me please

**Comment by al-one** [comment]
Try this [service](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command), and find the result in the HA notification:
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: water_heater.viomi_e1_entity_id
  method: get_prop
  params: [targetTemp,waterTemp,washStatus,hotWater,modeType]
  throw: true
```

**Comment by soulthiefer** [comment]
result this service in notification:
Miio command result
[7]

7 - this Target temp 
current temp? water_lewel?

this condition my entity
min_temp: 30
max_temp: 75
operation_list:
  - Normal
  - Heat
  - Delay
current_temperature: 0
temperature: 7
target_temp_high: 75
target_temp_low: 30
operation_mode: null
model: viomi.waterheater.e1
lan_ip: 192.168.31.24
mac_address: 50:EC:50:AC:50:E8
entity_class: MiotWaterHeaterEntity
miot_type: urn:miot-spec-v2:device:water-heater:0000A02A:viomi-e1:1
water_heater.target_temperature: 7
water_heater.status: null
water_heater.on: true
water_heater.mode: null
state_updater: lan
sub_entities:
  - water_heater-2.on-4
friendly_name: Xiaomi_Waterheat Water Heater
supported_features: 3

!!!current_temperature: 0 and water-level absent

**Comment by al-one** [comment]
Upgrade to master branch and try again.

**Comment by soulthiefer** [comment]
service:
![image](https://user-images.githubusercontent.com/78509632/149332937-5ed54747-875d-4eeb-88ca-fdf8ea925ad2.png)
result:
![image](https://user-images.githubusercontent.com/78509632/149333071-4dcdbefd-3b08-424a-a88c-2c2510737081.png)

nothing has changed((( show only "7" (((

**Comment by soulthiefer** [comment]
in server's logs , intergation sgeated mistake

Logger: custom_components.xiaomi_miot.water_heater
Source: custom_components/xiaomi_miot/__init__.py:1312
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 15:06:44 (90 occurrences)
Last logged: 15:49:59

Xiaomi_Waterheat Water Heater: Got miio properties ['washStatus', 'velocity', 'waterTemp', 'targetTemp', 'errStatus', 'hotWater', 'needClean', 'modeType', 'appointStart', 'appointEnd'] failed: {'code': -9998, 'message': 'user ack invalid'}

maybe these errors will help to understand the reason

**Comment by Zuz666** [comment]
> maybe these errors will help to understand the reason

device_customizes.py:
```yaml 
    'viomi.waterheater.e1': {
        'chunk_properties': 1,
        'miio_properties': 'washStatus,velocity,waterTemp,targetTemp,errStatus,'
                           'hotWater,needClean,modeType,appointStart,appointEnd',
    },
```

__init__.py:
```python
    def update_miio_props(self, props):
        if not self.miot_device:
            return
        try:
            max_properties = self.custom_config_integer('chunk_properties') or 10
            attrs = self._device.get_properties(props, max_properties=max_properties)
        except DeviceException as exc:
```

**Comment by soulthiefer** [comment]
thank you very much!!! problem solved
![image](https://user-images.githubusercontent.com/78509632/149400780-94f7a6d8-99b2-4399-9199-cde9a5ad834b.png)
there is a similar problem with

zhimi.humidifier.ca1
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1164
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 22:58:58 (13 occurrences)
Last logged: 23:05:03

AirHumidifier Humidifier: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fan_level': {'siid': 2, 'piid': 2}, 'humidifier.water_level': {'siid': 2, 'piid': 3}}, max_properties: 7/3
AirHumidifier Humidifier: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fan_level': {'siid': 2, 'piid': 2}, 'humidifier.water_level': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'alarm': {'siid': 4, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 2}}, max_properties: 9/7

and
chuangmi.camera.v2
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.xiaomi_miot.camera
Source: custom_components/xiaomi_miot/__init__.py:1164
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 22:59:31 (12 occurrences)
Last logged: 23:04:59

Xiaomi_Cam360 Camera Control: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'camera_control.on': {'siid': 2, 'piid': 1}, 'camera_control.image_rollover': {'siid': 2, 'piid': 2}, 'camera_control.night_shot': {'siid': 2, 'piid': 3}, 'camera_control.time_watermark': {'siid': 2, 'piid': 4}, 'camera_control.wdr_mode': {'siid': 2, 'piid': 5}, 'camera_control.recording_mode': {'siid': 2, 'piid': 6}}, max_properties: 8/6

please help me solve

**Comment by Zuz666** [comment]
And in miio2miot_specs.py set_template must be:

```yaml
    'viomi.waterheater.e1': {
        'chunk_properties': 1,
        'miio_specs': {
            'prop.2.1': {'prop': 'targetTemp', 'setter': 'set_temp', 'set_template': '{{ value | int }}'},
            'prop.2.2': {'prop': 'waterTemp'},
            'prop.2.3': {'prop': 'washStatus'},
            'prop.2.4': {
                'prop': 'washStatus',
                'setter': 'set_power',
                'template': '{{ value != 0 }}',
                'set_template': '{{ [value | int] }}',
            },
            'prop.2.5': {'prop': 'hotWater'}, # water-level
            'prop.2.6': {'prop': 'modeType', 'setter': 'set_mode'},
        },
    },
```
otherwise "power off" does not work.
