### ISSUE TITLE
小米人体传感器2环境光实体在homekit中被识别为人体传感器

### ISSUE THREAD

**Issue by JimmyKmi** [al-one/hass-xiaomi-miot#376]
先说一下大佬这个插件实在是太好用了，啥都接的上还很方便，但是偶尔还是会有些奇怪的事情

问题细节：
小米人体传感器2（[lumi.motion.bmgl01](https://home.miot-spec.com/s/lumi.motion.bmgl01)）
之前用另外一个作者的miot插件，将人体传感器2添加到homeassistance之后是可以显示的，但是添加到homekit后homekit是没有显示到这个设备的，换了大佬的这个miot就可以在homekit显示到设备了！
但是添加到homekit之后，传感器实体（xxx_motion_sensor）在homekit中显示为动作传感器，环境光实体（xxx_light_strong）在homekit中显示为人体传感器，挺奇怪。但是电池电量能够正常加载。
这个问题会导致在homekit中设备配置自动化时，在xx检测到有人时会因为光强实体转为true时触发，并且看着实在有点奇怪，并且我需要通过光强属性设置联动，所以也没有禁用这个实体

我不是专业的，我不确定这个问题在不在miot插件可以解决的范围之内，但是我真的希望这个问题能够得到解决，大佬这个插件实在是太好用了！

**Comment by al-one** [comment]
该设备的光线传感器仅能检测环境光强弱，因此`xxx_light_strong`实体和人体传感器一样是一个二元传感器(`binary_sensor`)。
插件为`xxx_light_strong`实体默认设置了`device_class: light`，但是HA的homekit集成并不支持该类型的二元传感器，所以将其作为人体传感器(`occupancy`)显示。
[![homekit](https://user-images.githubusercontent.com/4549099/149287984-229de424-3611-47da-a302-3d4ead85747e.png)](https://www.home-assistant.io/integrations/homekit)

**Comment by JimmyKmi** [comment]
在HomeKit集成提供解决方案之前这个方法确实不错，如果能把传感器作为亮度传感器，环境光为亮时标注为100lux，暗时为0lux会让强迫症患者看着更舒服ヽ(ˋДˊ)ノ并且询问siri房间内是否有人的时候siri才能准确回答

**Comment by al-one** [comment]
https://www.home-assistant.io/integrations/template#trigger-based-template-sensors
```yaml
# configuration.yaml
template:
  - trigger:
      - platform: state
        entity_id: binary_sensor.lumi_bmgl01_xxxx_light_strong
    sensor:
      - name: lumi_bmgl01_xxxx_illuminance
        state: '{{ 100 if trigger.to_state.state else 0 }}'
        device_class: illuminance
        unit_of_measurement: lx
```
