### ISSUE TITLE
dreame.vacuum.p2150b状态及属性不更新

### ISSUE THREAD

**Issue by z80020100** [al-one/hass-xiaomi-miot#378]
实测透过小米帐号接入[小米扫拖机器人2 Ultra 集尘版](https://home.mi.com/baike/index.html#/detail?model=dreame.vacuum.p2150b) ([dreame.vacuum.p2150b](https://home.miot-spec.com/s/dreame-p2150b))
清扫指令和风速设置都能正常运作
但机器人本身的状态及属性不会自动更新
![image](https://user-images.githubusercontent.com/6964982/149272232-d77488b1-3443-4b3d-8f61-a09e0d398e88.png)
![image](https://user-images.githubusercontent.com/6964982/149272368-0636a580-0336-4ec9-9883-af7eaee65ce2.png)

只有在勾选**Force renew devices**并传送后才会更新
![image](https://user-images.githubusercontent.com/6964982/149272465-77b75803-5692-40d9-961a-7d796c67aa9c.png)

**Comment by al-one** [comment]
Try to integrate it via token, if not available, report logs to me.

**Comment by z80020100** [comment]
谢谢您的回复，尝试用token集成后同样无法更新状态，永远只会显示充电中
请问我该如何提取出日志并提交呢？

**Comment by al-one** [comment]
在你的配置文件中添加：
```yaml
# configuration.yaml
logger:
  default: warning
  logs:
    custom_components.xiaomi_miot.vacuum: debug
```
