### ISSUE TITLE
Problem with sensors lumi.sensor_magnet.v2

### ISSUE THREAD

**Issue by Techfreak96** [al-one/hass-xiaomi-miot#380]
Hello, i got a big problem with my lumi sensors. 
In my case, these control the heating. If window open = heating off, if window closed = heating on 

The problem is that my heaters are off more often. So I took a deeper look today. In the Xiaomi app, the sensors reset briefly or something similar. The sensor is triggered to open, then directly to close again. However, Xiaomi Miot only notices that the sensor is open, not closed again. How can I fix this problem?
![Screenshot_20220113-110949](https://user-images.githubusercontent.com/44571250/149310230-f8190532-3c05-4759-ba5b-eeb82c5ca02d.png)
![Screenshot 2022-01-13 082136](https://user-images.githubusercontent.com/44571250/149284762-2805abd3-5fef-49e3-8046-c9556591d683.jpg)

"geöffnet" is "open"
"geschlossen" is "closed"

**Comment by al-one** [comment]
What version of the component are you using ?

**Comment by Techfreak96** [comment]
@al-one newest version, v0.5.0

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/121#issuecomment-874436616
- https://github.com/al-one/hass-xiaomi-miot/issues/188#issuecomment-927213574

**Comment by Techfreak96** [comment]
Thank you, but where to add the custom entity attributes?

The default update frequency of the binary_sensor entity is 30 seconds, so if the door is opened and closed within 30 seconds, the state will not be accurately obtained.
You can modify the update frequency by adding custom entity attributes:

binary_sensor.magnet_entity_id:
  interval_seconds: 3

    Customizing entities

**Comment by al-one** [comment]
https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities
```yaml
# customize.yaml
binary_sensor.lumi_magnet_entity_id:
  interval_seconds: 3
```

Or

```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    lumi.sensor_magnet.v2:
      interval_seconds: 3
```
