### ISSUE TITLE
New function of Device Support: IR (remote) of Aqara AirConditioner Companion P3 (lumi.aircondition.acn05)

### ISSUE THREAD

**Issue by home110120** [al-one/hass-xiaomi-miot#389]
The Aqara P3 support remote IR function to study from remote controller, and re-send the command after click the button in Mi-Home App, is it possible to support the function using miot auto within HA, or if there is any available option to do so for now? Thanks for your helping in advance.

**Comment by al-one** [comment]
1. Find `did` of the device in file: `.storage/xiaomi_miot/devices-xxxx.json`
2. Call this [service](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.request_xiaomi_api):
    ```yaml
    service: xiaomi_miot.request_xiaomi_api
    data:
      entity_id: climate.lumi_acn05_entity_id
      api: /v2/irdevice/controller/keys
      data:
        did: 'your_did'
    ```
