### ISSUE TITLE
[Feature Request] Use description for vacuum attributes instead of numbers

### ISSUE THREAD

**Issue by auanasgheps** [al-one/hass-xiaomi-miot#392]
Hello,
Thanks for this integration, currently this is the only one that supports Dreame Vacuums.

The integration works fine for my L10 Pro (dreame.vacuum.p2029), but the vacuum attributes are shown as values/numbers.
Example
![image](https://user-images.githubusercontent.com/20586878/150121559-027a00b9-e151-4db8-843d-28d7eaceffa6.png)

Almost all these values have a description [here](https://home.miot-spec.com/spec/dreame.vacuum.p2029)
Example:
![image](https://user-images.githubusercontent.com/20586878/150121620-6e0a3ef7-9a53-49ca-8ca0-20351679cd5d.png)

So would be great to see `Status - Sweeping` instead of `Status - 1` and `Mode - Basic` instead of `Mode - 0`.

Would be possible to use these vaules instead of numbers so we can understand more about the device and use them in cards?

Also, some of these values are missing in the spec website. Is there a way I could contribute to add them?

**Comment by al-one** [comment]
Currently, attributes only use descriptions as state when they are sensor entities.
```yaml
# customize.yaml
vacuum.dreame_p2029_your_entity_id:
  sensor_properties: status,mode
```

Another way, you can format entity attributes:
```yaml
#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    dreame.vacuum.p2029:
      attributes_template: |-
        {%- set sta = data['vacuum.status'] | default(0) | int(0) %}
        {%- set mod = data['vacuum.mode'] | default(0) | int(0) %}
        {{ {
        'vacuum_status': [None,'Sweeping','Idle','Paused','Error','Returning','Charging','Mopping','xxxx'][sta] | default(None),
        'vacuum_mode': ['Silent','Basic','Strong','Full Speed'][mod] | default(None),
        } }}
```
