### ISSUE TITLE
Unavailable device is not causing sub-entities to also be unavailable

### ISSUE THREAD

**Issue by pplucky** [al-one/hass-xiaomi-miot#393]
Hello.

I currently have a [Mi Smart Space Heater S (zhimi.heater.mc2)](https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Aheater%3A0000A01A%3Azhimi-mc2%3A1) connected to HA via your custom component.

Still then, every time the device is unavailable (physically plugged off), only one of the entities (in the case, the climate one) is marked as unavailable, while all the remaining are "available" (obviously not working):
![image](https://user-images.githubusercontent.com/16407309/150138394-9fd7acb2-6083-4c6d-8bf6-0f3810dc03df.png)

![image](https://user-images.githubusercontent.com/16407309/150137815-81a0cdc2-23a7-40c8-93a7-a110a0043f4c.png)

My yaml config is the following:
```yaml
xiaomi_miot:
### Enable Xiaomi Cloud
#   username: !secret xiaomi_cloud_username
#   password: !secret xiaomi_cloud_password
### Ideas taken from https://github.com/al-one/hass-xiaomi-miot/issues/326
  device_customizes:
    hfjh.fishbowl.v2:
### Generate number entities for pump flux, brightness and led color
      number_properties: pump_flux,ledboard_brightness,ledboard_color 
### Generate a button entity to trigger the action to feed the fish
      button_actions: set_feed_single
### Add attribute to keep track of latest feed-record event
      miio_cloud_props: event.4.1
    zhimi.heater.mc2:
### Assign a different temp sensor to climate entity generated for heater
      bind_sensor: sensor.temperature_158d0001571539
### Generate switches for heater on/off + alarm on/off
      switch_properties: heater.on,alarm
    careli.fryer.maf02:
### Generate a sensor entity to show the remaining cooking time
      sensor_properties: air_fryer.left_time
  exclude_state_attributes:
### Generic attributes to exclude
    - mac_address
### Heater attributes to exclude
    - private_service.hw_enable
    - private_service.use_time
    - private_service.country_code
### Aquarium attributes to exclude
    - function.mcu_type
    - function.mcu_type_new
    - function.key_switch
    - function.feed_time_week
    - function.feed_num
    - function.feed_time
    - function.feed_time_switch
    - function.ledboard_time_switch
    - function.ledboard_time_open
    - function.ledboard_time_close
    - function.ledboard_model
    - function.ledboard_sun
    - function.ledboard_stream
    - function.ledboard_speed
    - function.ledboard_time_switch
    - function.ledboard_time_open
    - function.ledboard_time_close
### Air Fryer attributes to exclude
    - home_room
```

Is this something that can be fixed?

Thanks in advance.
