### ISSUE TITLE
加湿器和天然气监测问题

### ISSUE THREAD

**Issue by sctale** [al-one/hass-xiaomi-miot#396]
大神，我有一个加湿器和一个天然气卫士有点疑问，想请假下。先谢谢啦。
加湿器: [deerma.humidifier.jsq1](https://home.miot-spec.com/s/deerma.humidifier.jsq1)
这个加湿器在打开状态下如果电源断开了，HA一直显示的打开状态，能否向米家一样显示为离线？
设备参数如下：
```yaml
min_humidity: null
max_humidity: null
available_modes:
  - 'Off'
  - Level1
  - Level2
  - Level3
  - ConstHumidity
mode: Level3
model: deerma.humidifier.jsq1
lan_ip: 192.168.20.210
mac_address: 54:48:E6:.........
entity_class: MiotHumidifierEntity
home_room: 浩浩的家 主卧
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq1:1
humidifier.on: true
humidifier.fan_level: 3
state_updater: cloud
exclude_miot_services:
  - custom
  - humidifier
  - device_information
indicator_light.on: true
alarm: true
environment.relative_humidity: 53
environment.temperature: 17
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-2
  - indicator_light-5
device_class: humidifier
friendly_name: 加湿器 Humidifier
supported_features: 1
```

**Comment by sctale** [comment]
天然气卫士：lumi.sensor_gas.mcn02
目前只有一个天然气浓度实体，其他什么都没有，能否出现那种直接判断的是否的binary_sensor？
设备属性如下：
model: lumi.sensor_gas.mcn02
lan_ip: 192.168.20.238
mac_address: 54:48:E6:............
entity_class: MiotSensorEntity
home_room: 浩浩的家 厨房
miot_type: urn:miot-spec-v2:device:gas-sensor:0000A022:lumi-mcn02:1
state_property: gas_sensor.gas_concentration
gas_sensor.status: 1
gas_sensor.gas_concentration: 0
state_updater: cloud
exclude_miot_services:
  - gas_sensor_control
unit_of_measurement: '%'
friendly_name: 天然气报警器 Gas Sensor Concentration
supported_features: 0

**Comment by baiuu** [comment]
> lumi.sensor_gas.mcn02

你想判断什么 是否报警么 这个参数有的。。

**Comment by al-one** [comment]
> 加湿器: deerma.humidifier.jsq1

由于小米云端会缓存设备的在线状态，导致设备离线后插件拿到的仍是设备在线时的状态。
你可以参考 https://github.com/al-one/hass-xiaomi-miot/issues/91#issuecomment-846492664 添加下面的[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)：
```yaml
# customize.yaml
humidifier.deerma_jsq1_entity_id:
  check_lan: true
```

**Comment by al-one** [comment]
> 天然气卫士：lumi.sensor_gas.mcn02

最新的提交 https://github.com/al-one/hass-xiaomi-miot/commit/f7c46d1639db21f24323d244cd25d788f2a8379b 中为该设备新增了一个`sensor`传感器实体，如果你想要`binary_sensor`实体，建议使用[模板](https://www.home-assistant.io/integrations/template)创建：
```yaml
# configuration.yaml
template:
  - trigger:
      - platform: state
        entity_id: sensor.lumi_mcn02_entity_id
        attribute: gas_sensor.status
    binary_sensor:
      - name: lumi_mcn02_alarming
        state: |
          {{ (trigger.to_state.attributes['gas_sensor.status'] | default(1)) == 5 }}
        device_class: gas
```
