### ISSUE TITLE
XIAOWAN Smart Pet Feeder (mmgg.feeder.spec)

### ISSUE THREAD

**Issue by gluk3** [al-one/hass-xiaomi-miot#413]
Hi,

I have tried to integrate XIAOWAN Smart Pet Feeder (**mmgg.feeder.spec**) without success.

This is the state of entity:
```model: mmgg.feeder.spec
lan_ip: 192.168.1.103
mac_address: B4:60:xx:xx:xx:xx
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-spec:1
state_property: pet_feeder.fault
pet_feeder.fault: 0
state_updater: lan
pet_feeder.fault_desc: No Faults
factory_result-9-11: 1,2,3,6,1
phon_time_zone-9-12.error: -4004 Other internal errors
server_time_zone-9-13.error: -4004 Other internal errors
devicecontrolserve.null.error: -4004 Other internal errors
clearnserve.cleantime.error: -4004 Other internal errors
dryerserve.dryertime.error: -4004 Other internal errors
keyserve.key_stat: 0
feedplanserve.feedplan_contr: 1
feedplanserve.feedplan_hour: 1
feedplanserve.feedplan_min: 1
feedplanserve.feedplan_unit: 1
feedplanserve.feedplan_stat: 1
feedplanserve.feedplan_id: 1
feedplanserve.getfeedplan_num.error: -4004 Other internal errors
feedplanserve.feddplan_string: 1,2,3,6,0
feedserve.feedtotal.error: -4004 Other internal errors
feedserve.outfood_num.error: -4004 Other internal errors
feedserve.outfood_id.error: -4004 Other internal errors
feedserve.weightlevel.error: -4004 Other internal errors
feedserve.foodstatus.error: -4004 Other internal errors
feedserve.outletstatus.error: -4004 Other internal errors
feedserve.doorstatus.error: -4004 Other internal errors
devicecontrolserve.led_control: 1
pet_feeder.fault.error: -4004 Other internal errors
devicecontrolserve.led_control.error: -4004 Other internal errors
friendly_name: Smart Pet Feeder Pet Feeder Device Fault
supported_features: 0
```

It appears that no attributes are being read correctly, but if I use the service (for example):

```
service: xiaomi_miot.get_properties
data:
  entity_id: sensor.mmgg_spec_2b9a_pet_feeder
  mapping:
    fault:
      siid: 2
      piid: 1
    feedtotal:
      siid: 4
      piid: 2
    outfood-num:
      siid: 4
      piid: 4
    foodstatus:
      siid: 4
      piid: 7
    dryertime:
      siid: 7
      piid: 1
    clearnserve:
      siid: 8
      piid: 1
  throw: true
```

the result is:

```
[{'did': 'prop.2.1', 'siid': 2, 'piid': 1, 'code': 0, 'value': 0},
 {'did': 'prop.4.2', 'siid': 4, 'piid': 2, 'code': 0, 'value': 0},
 {'did': 'prop.4.4', 'siid': 4, 'piid': 4, 'code': 0, 'value': 4},
 {'did': 'prop.4.7', 'siid': 4, 'piid': 7, 'code': 0, 'value': 0},
 {'did': 'prop.7.1', 'siid': 7, 'piid': 1, 'code': 0, 'value': 3},
 {'did': 'prop.8.1', 'siid': 8, 'piid': 1, 'code': 0, 'value': 9}]
```

How can I integrate this pet feeder correctly? 

Thanks
