### ISSUE TITLE
Aqara空调伴侣(升级版)如何控制电源开关

### ISSUE THREAD

**Issue by gncy2013** [al-one/hass-xiaomi-miot#414]
Aqara空调伴侣(升级版)[`lumi.acpartner.v3`](https://home.miot-spec.com/s/lumi.acpartner.v3)，在米家里和其他插座一样可以控制电源开关。  
如何在插件里添加这个插座开关。

**Comment by gncy2013** [comment]
通过 [xiaomi_miio_plug](https://github.com/syssi/xiaomiplug) 添加开关可以用

**Comment by al-one** [comment]
你还可以通过添加[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)为其生成开关实体:
```yaml
# customize.yaml
climate.lumi_v3_entity_id:
  switch_properties: 'on'
```

**Comment by al-one** [comment]
请问上述方法有效吗？

**Comment by gncy2013** [comment]
通过以下方法添加的开关为红外控制空调的开关，不是插座的电源开关



> 你还可以通过添加[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)为其生成开关实体:
> 
> ```yaml
> # customize.yaml
> climate.lumi_v3_entity_id:
>   switch_properties: 'on'
> ```
> 
> 或者：
> 
> ```yaml
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     'lumi.acpartner.*':
>       switch_properties: 'on'
> ```

**Comment by al-one** [comment]
该设备的[miot-spec](https://home.miot-spec.com/spec/lumi.acpartner.v3)未定义插座电源开关属性。如果想通过本插件控制电源，请通过服务控制：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.lumi_v3_entity_id
  method: toggle_plug
  params:
    - 'on'
```
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.lumi_v3_entity_id
  method: toggle_plug
  params:
    - 'off'
```
