### ISSUE TITLE
deerma.humidifier.jsq5 missing attribute

### ISSUE THREAD

**Issue by Kejszijo** [al-one/hass-xiaomi-miot#420]
Hi,

After upgrade the integration to 0.5.2, the **custom.water_shortage_fault** attribute is missing. 
With 0.4.16 version it still existed.

**Comment by al-one** [comment]
Some users reported that the device was sometimes unavailable, and it returned to normal after excluding `custom` service. Please try adding this option to get it back:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    exclude_miot_services: []
```

**Comment by Kejszijo** [comment]
unfortunately it doesn't work. 

it's still there:

exclude_miot_services:
  - custom

**Comment by al-one** [comment]
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    exclude_miot_services: null
```
https://github.com/al-one/hass-xiaomi-miot/issues/332#issuecomment-1031711816
