### ISSUE TITLE
Variable content xiaomi_miot.call_action formating

### ISSUE THREAD

**Issue by Bloodpilot** [al-one/hass-xiaomi-miot#425]
Hi Guys, 

I know that this is not an issue fully related to this git but may someone can help me.
I try to create a service to send my vacuum to a room If I hardcode the room everything works fine.

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2187_51af_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[6,1,0,2,1]]}'
  force_params: true
```

but if I try adding a variable with the parameters inside it does not work.
As it looks in the debugger it is formating that JSON parameter as a yaml.

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2187_51af_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":{{someVariable}}}'
  force_params: true
```

What am I doing wrong?

Debugger shows:

> Executed: February 9, 2022, 13:06:44
Result:
```yaml
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    entity_id: vacuum.dreame_p2187_51af_robot_cleaner
    siid: 4
    aiid: 1
    params:
      - piid: 1
        value: 18
      - piid: 10
        value:
          selects:
            - - 1
              - 2
              - 2
              - 2
              - 1
            - - 2
              - 2
              - 2
              - 2
              - 2
            - - 3
              - 2
              - 2
              - 2
              - 3
            - - 4
              - 2
              - 2
              - 2
              - 4
    force_params: true
  target: {}
running_script: false
limit: 10
```

Thanks!

**Comment by al-one** [comment]
Try:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2187_51af_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: |
        {"selects":{{ someVariable | to_json }}}
  force_params: true
```

**Comment by Bloodpilot** [comment]
Thanks for the fast reply, still the same result:
```yaml

Executed: February 10, 2022, 08:22:05
Result:
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    entity_id: vacuum.dreame_p2187_51af_robot_cleaner
    siid: 4
    aiid: 1
    params:
      - piid: 1
        value: 18
      - piid: 10
        value:
          selects:
            - - 1
              - 2
              - 2
              - 2
              - 1
            - - 2
              - 2
              - 2
              - 2
              - 2
            - - 3
              - 2
              - 2
              - 2
              - 3
            - - 4
              - 2
              - 2
              - 2
              - 4
    force_params: true
  target: {}
running_script: false
limit: 10

```

**Comment by Bloodpilot** [comment]
Same:
```yaml
Executed: February 10, 2022, 08:38:02
Result:
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    entity_id: vacuum.dreame_p2187_51af_robot_cleaner
    siid: 4
    aiid: 1
    params:
      - piid: 1
        value: 18
      - piid: 10
        value:
          selects:
            - - 1
              - 2
              - 2
              - 2
              - 1
            - - 2
              - 2
              - 2
              - 2
              - 2
            - - 3
              - 2
              - 2
              - 2
              - 3
            - - 4
              - 2
              - 2
              - 2
              - 4
    force_params: true
  target: {}
running_script: false
limit: 10
```

I've also posted in the home assistant community may you can check that out: [https://community.home-assistant.io/t/send-json-with-variable-as-key-value/390673/3](url)

**Comment by al-one** [comment]
Try:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2187_51af_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: |
        {{ {"selects": someVariable} | to_json | to_json }}
  force_params: true
```

**Comment by Bloodpilot** [comment]
Looks better but no reaction by the vacuum:
```yaml
Executed: February 10, 2022, 09:27:17
Result:
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    entity_id: vacuum.dreame_p2187_51af_robot_cleaner
    siid: 4
    aiid: 1
    params:
      - piid: 1
        value: 18
      - piid: 10
        value: >-
          "{\"selects\": [[1, 1, 0, 1, 1], [2, 1, 0, 1, 2], [3, 1, 0, 1, 3], [4,
          1, 0, 1, 4]]}"
    force_params: true
  target: {}
running_script: false
limit: 10

```

**Comment by Bloodpilot** [comment]
I think it is just shown like that as it is not valid JSON string as soon as it get's one it is interpreted as yaml.

**Comment by Bloodpilot** [comment]
Got it working, the solution is:
```yaml
  service: xiaomi_miot.call_action
  data:
    entity_id: vacuum.dreame_p2187_51af_robot_cleaner
    siid: 4
    aiid: 1
    params: >-
      [
        {
          "piid": 1,
          "value": 18
        },
        {
          "piid": 10,
          "value": "{\"selects\":{{vac3}}}"
        }
      ]
    force_params: true
```
