### ISSUE TITLE
deerma.humidifier.jsqs not returning water-shortage-fault

### ISSUE THREAD

**Issue by AlexeyTorch** [al-one/hass-xiaomi-miot#446]
Device: [deerma.humidifier.jsqs](https://home.miot-spec.com/s/deerma.humidifier.jsqs)
Connects to home assistant but does not return water-shortage-fault (siid: 7, piid: 1)
siid 7 is custom

In the properties of the humidifier you can see:
exclude_miot_services:
   -custom

How can I get the value of water-shortage-fault ? 
Without it, my automation does not work correctly (turning on, off and changing the operating mode of the humidifier)

**Comment by al-one** [comment]
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsqs:
      exclude_miot_services: null
```

- https://github.com/al-one/hass-xiaomi-miot/issues/332#issuecomment-1031711816
- https://github.com/al-one/hass-xiaomi-miot/issues/420
