### ISSUE TITLE
Dreame L10 Pro Vacuum - Room Cleaning

### ISSUE THREAD

**Issue by xBourner** [al-one/hass-xiaomi-miot#449]
Hey i found this integation and it looks very great. I have some services which are for room based mopping.
How to add this to my [Dreame L10 Pro](https://home.miot-spec.com/s/dreame.vacuum.p2029)?

I found this in another issue:

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2029_1882_robot_cleaner
  siid: 2
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
```

But it only starts cleaning. Not a certain room. How to find out the correct siid, aiid, piid and room ids?
Or does anything else need to be put in configuration.yaml?

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/dreame.vacuum.p2029

Find siid, aiid, piid in this website.

**Comment by xBourner** [comment]
Yes i saw this. But i still struggle with the ids.

`service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2029_1882_robot_cleaner
  siid: 2
  aiid: 3
  params:
    - piid: 4
      value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'`

This is what i have right now. 

siid: 2 = vacuum cleaner robot
aiid: 3 = start-room-sweep
piid: 4 = by room id

how to get the room ids?

**Comment by xBourner** [comment]
found the values from mi home by vevs.

this is how it works for me

`siid: 4
aiid: 1
params:
  - piid: 1
    value: 18
  - piid: 10
    value: '{"selects":[[3,1,3,3,1]]}'
force_params: true
entity_id: vacuum.dreame_p2029_1882_robot_cleaner`

**Comment by vuasia** [comment]
> ```yaml
>    - piid: 1
>       value: 18
>     - piid: 10
>       value: '{"selects":[[3,1,3,3,1]]}''
> ```

didnt work for me, got  the notification:
"Miot action result
{'did': '447391206', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': -704220025, 'exe_time': 0, 'withLatency': 0}"

**Comment by al-one** [comment]
@vuasia Please open a new issue with you vacuum model.

**Comment by al-one** [comment]
@vuasia   Copy this:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2029_1882_robot_cleaner
  siid: 2
  aiid: 3
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[3,1,3,3,1]]}'
```
