### ISSUE TITLE
Fan speed slider resets to 0%

### ISSUE THREAD

**Issue by h3nrytan** [al-one/hass-xiaomi-miot#465]
same issue but the fix didnt work for [zhimi.fan.za4](https://home.miot-spec.com/s/zhimi.fan.za4)

once i apply this fix, the speed_list shows nothing. below state attribute is before the fix.

```yaml
speed_list:
  - 'off'
  - '1'
  - '2'
  - '3'
  - '4'
preset_modes:
  - Straight Wind
  - Natural Wind
direction: null
oscillating: true
speed: 1
percentage: null
percentage_step: 1
preset_mode: Natural Wind
model: zhimi.fan.za4
lan_ip: ###
mac_address: ###
entity_class: MiotFanEntity
home_room: ###
miot_type: urn:miot-spec-v2:device:fan:0000A005:zhimi-za4:1
fan.on: true
fan.fan_level: 1
fan.horizontal_swing: true
fan.horizontal_angle: 90
fan.mode: 1
state_updater: lan
indicator_light.on: true
alarm: false
physical_controls_locked: false
sub_entities:
  - physical_controls_locked-3.physical_controls_locked-1
  - indicator_light-5
friendly_name: Stand Fan
supported_features: 15
```

_Originally posted by @h3nrytan in https://github.com/al-one/hass-xiaomi-miot/issues/440#issuecomment-1060216002_
