### ISSUE TITLE
❓️ 如何在HA查看摄像头实体回放(看家助手)视频？

### ISSUE THREAD

**Issue by Miaoerr** [al-one/hass-xiaomi-miot#466]
我一直在找支持可视门铃的hass插件，发现本插件有相关功能，但是会有“静止的视频画面”的问题，根据描述进行了配置，但仍然有此问题，我发现在实体的属性中有这样一句话：miot_error: Nonsupport start hls/rstp stream via miot-spec
我的设备是[madv.cateye.miowl3（小米智能门铃3）](https://home.miot-spec.com/spec/madv.cateye.miowl3)
这个提示是不是就表示这个问题无法解决了？
如果需要我可以提供其他日志，以便于解决该问题.
另外，对于可视门铃，是否不支持实时查看，只能查看回放？这个设备（madv.cateye.miowl3）我在米家APP中可以进行实时查看。

❓️ 如何在HA查看摄像头实体回放(看家助手)视频？

---

🙋 本插件在[v0.4版本](https://github.com/al-one/hass-xiaomi-miot/releases)中添加了对**摄像头**、**猫眼**及**可视门铃**的回放视频支持，原理是通过米家接口获取设备的最后一个看家助手视频。如接入摄像头后仍看不到回放视频，请在米家APP中开启摄像头的`看家助手`。
由于小米云端视频文件编码的问题，部分型号摄像头的回放视频仍然无法播放，你可以尝试为主实体[添加自定义属性](#issuecomment-864678774)`motion_stream_slice: -1`，经测试此方法可能会显示一个静止的视频画面，原因未知。
```yaml
# customize.yaml
# 以下自定义属性不是必须
camera.your_entity_id:
  use_motion_stream: true # 在主实体开启回放，猫眼默认已开启
  sub_motion_stream: true # 为回放视频单独生成一个camera实体，与`use_motion_stream`属性选其一
  motion_stream_slice: -1 # 视频切片文件索引，-1表示最后一个切片文件，0表示第一个
```

_Originally posted by @al-one in https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-903078604_
