### ISSUE TITLE
Chanitex CXR800-A1/T1无法正确显示 

### ISSUE THREAD

**Issue by cybaijie** [al-one/hass-xiaomi-miot#467]
[Chanitex CXR800-A1/T1](https://home.miot-spec.com/s/smith.waterpuri.cxr800)无法正确显示 
![屏幕截图 2022-03-08 010848](https://user-images.githubusercontent.com/59301469/157083055-c1e5f12f-d437-42b4-aa1c-29ff358f0296.png)

![image](https://user-images.githubusercontent.com/59301469/157083266-ef20bd2b-ad2f-4340-a7dd-525009f417b7.png)

**Comment by al-one** [comment]
请提供[开发者工具](https://my.home-assistant.io/redirect/developer_states)中的实体状态属性。

**Comment by cybaijie** [comment]
![image](https://user-images.githubusercontent.com/59301469/157246845-d1a4587f-50d1-4988-8f51-a4a6e4eaf9c3.png)

**Comment by cybaijie** [comment]
> 请提供[开发者工具](https://my.home-assistant.io/redirect/developer_states)中的实体状态属性。
![image](https://user-images.githubusercontent.com/59301469/157246963-276556d9-1e3a-4dd1-9b32-53d9da22b5d3.png)

**Comment by al-one** [comment]
请更新到master分支后尝试。

**Comment by cybaijie** [comment]
咋更新，有没有教程，我是在HACS下的最新版了

**Comment by cybaijie** [comment]
> 请更新到master分支后尝试。
已添加后关机重启，还是不行
![image](https://user-images.githubusercontent.com/59301469/157274690-ce8e14ac-9ca2-45ee-a64c-425cc8ab4166.png)

**Comment by al-one** [comment]
实体属性

**Comment by cybaijie** [comment]
抱歉最近比较忙现在才有空
![image](https://user-images.githubusercontent.com/59301469/157689589-6c7ae5ed-6d00-441a-97b8-dbb0d7025246.png)

**Comment by cybaijie** [comment]
大佬还在吗？

**Comment by cybaijie** [comment]
> 实体属性
大佬还在吗

**Comment by al-one** [comment]
请尝试使用本地模式接入此设备。

**Comment by al-one** [comment]
请问本地模式下该设备可用吗？

**Comment by cybaijie** [comment]
不行。。。。

**Comment by cybaijie** [comment]
![image](https://user-images.githubusercontent.com/59301469/160309208-5de0cb3d-cf88-4e6e-a08b-b9dc553974bb.png)

**Comment by al-one** [comment]
请尝试添加下面的[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)再试：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    smith.waterpuri.cxr800:
      miot_local: true
      chunk_properties: 1
```

**Comment by cybaijie** [comment]
大佬这个添加后还是无法显示
![image](https://user-images.githubusercontent.com/59301469/170492453-ec2b143b-941a-4b16-ac26-8f21849315a4.png)

**Comment by al-one** [comment]
请尝试添加下面的[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)再试：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    smith.waterpuri.cxr800:
      miot_local: true
      chunk_properties: 1
      exclude_miot_services: chanitex_wp_gs
```

> 最新版已支持通过UI自定义设备 (#600)

**Comment by al-one** [comment]
请尝试添加下面的[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)再试：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    smith.waterpuri.cxr800:
      miot_local: true
      chunk_properties: 1
      exclude_miot_services: chanitex_wp_gs
      exclude_miot_properties: fault
```

如果还是不行，把`chunk_properties: 1`去掉再试下，并反馈两种情况下的实体属性。
