### ISSUE TITLE
xiaomi.tv.fsv1 电视关机后无法通过按钮开机

### ISSUE THREAD

**Issue by StimeKe** [al-one/hass-xiaomi-miot#479]
xiaomi.tv.fsv1 电视关机后无法通过按钮开机，是否可以通过自动化监听按了开机按钮，然后我让小爱开机呢。

**Comment by al-one** [comment]
小米电视可以通过下面的方法(二选一)绑定小爱音箱来打开电视。
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    xiaomi.tv.fsv1:
      bind_xiaoai: media_player.xiaoai_entity_id
```
或者
```yaml
# customize.yaml
media_player.mitv_entity_id:
  bind_xiaoai: media_player.xiaoai_entity_id
```

需要注意的是，此方法需要在米家中设置电视设备的名称，尽量保持和在电视设置中的名字一样。
![xiaomi miot tv](https://user-images.githubusercontent.com/4549099/158509451-56d4830f-3532-4645-973f-0d4b2ef85d2f.png)

**Comment by StimeKe** [comment]
谢谢，刚开始没看到这个文档，后面看到了，所以关闭了issues。

**Comment by yangtfu** [comment]
> 小米电视可以通过下面的方法(二选一)绑定小爱音箱来打开电视。
> 
> ```yaml
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     xiaomi.tv.fsv1: # 改成你的电视型号
>       bind_xiaoai: media_player.xiaoai_entity_id
> ```
> 
> 或者
> 
> ```yaml
> # customize.yaml
> media_player.mitv_entity_id:
>   bind_xiaoai: media_player.xiaoai_entity_id
> ```
> 
> 需要注意的是，此方法需要在米家中设置电视设备的名称，尽量保持和在电视设置中的名字一样。 ![xiaomi miot tv](https://user-images.githubusercontent.com/4549099/158509451-56d4830f-3532-4645-973f-0d4b2ef85d2f.png)

这样小爱似乎会发声？能否给个选项不发声

**Comment by al-one** [comment]
请确认你的插件为最新版本，并检查有无配置`xiaoai_silent`自定义属性：
```yaml
# customize.yaml​
​media_player.your_mitv_entity_id​:
  ​bind_xiaoai​: ​media_player.xiaoai_entity_id
  xiaoai_silent: true # 默认为true 不发声
  television_name: 客厅小米电视 # 默认自动获取
```
