### ISSUE TITLE
云米洗烘一体机请求支持烘干、洗衣液投放等自定义设置

### ISSUE THREAD

**Issue by axelburks** [al-one/hass-xiaomi-miot#48]
Model
viomi.washer.v13

![image](https://user-images.githubusercontent.com/11376445/113656309-30239600-96ce-11eb-9629-f6e6f9c58313.png)
洗烘一体机支持自定义设置 洗衣温度、转速、漂洗次数、烘干、洗衣液投放
本插件目前已支持设置洗衣温度、转速、漂洗次数；

请求支持其他的烘干、洗衣液投放等自定义设置

**Comment by al-one** [comment]
请提供洗衣机实体的[状态属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by axelburks** [comment]
model: viomi.washer.v13 lan_ip: 192.168.123.16 mac_address: 5C:E5:0C:10:B2:0F firmware_version: 2.1.3 hardware_version:  entity_class: MiotSwitchEntity key_press.key_props.error: -704053100 key_press.key_value.error: -704053100 key_press.key_time.error: -704053100 consumables.detergent: true consumables.detergent_dosage: 1 consumables.detergent_consume.error: -704053100 consumables.softener.error: -704053100 consumables.softener_dosage.error: -704053100 consumables.softener_consume.error: -704053100 consumables.disinfectant.error: -704053100 consumables.disinfectant_dosage.error: -704053100 disinfectant_consume.error: -704053100 consumables.prepare_time.error: -704053100 consumables.detergent_gone: false consumables.softener_gone.error: -704053100 consumables.disinfectant_gone.error: -704053100 physical_controls_locked: false washer.on: false washer.status: 0 washer.mode: 0 washer.fault.error: -704053100 washer.left_time: 50 washer.target_temperature: 40 washer.spin_speed: 1000 washer.drying_time: 0 washer.rinsh_times: 6 washer.speed_level.error: -704053100 washer.door_state: 1 washer.power_consumption.error: -704053100 washer.water_consumption.error: -704053100 washer.working_time.error: -704053100 state_updater: cloud sub_entities: physical_controls_locked-3.physical_controls_locked-1, mode, target_temperature, spin_speed, rinsh_times, action friendly_name: 洗衣机 Washer icon: mdi:washing-machine supported_features: 0 device_class: switch
--

**Comment by al-one** [comment]
最新提交的版本已支持干衣，但是不支持洗衣液投放等设置。
不过你可以通过HA服务控制：
```yaml
service: xiaomi_miot.set_property
data:
  entity_id: switch.your_washer_entity_id
  field: consumables.detergent
  value: true # or false
```

```yaml
service: xiaomi_miot.set_property
data:
  entity_id: switch.your_washer_entity_id
  field: consumables.detergent_dosage
  value: 1 # 0 ~ 2
```
