### ISSUE TITLE
lumi.acpartner.mcn04 / KTB04LM - Target Temperature - always reported as 225C

### ISSUE THREAD

**Issue by johnjoemorgan** [al-one/hass-xiaomi-miot#484]
I have 2 of these devices and both work well except that in the UI they report a target temperature of 255C no matter what the setting is even switching on and setting the required temp.  When using via HA the target temperature _seems_ to be obeyed but the reported target temperature stays at 255C

![lumi acpartner mcn04  KTB04LM - 1](https://user-images.githubusercontent.com/45795798/159154326-1a34a8d7-e8da-405a-8a1a-4e537d162d4a.png)
![lumi acpartner mcn04  KTB04LM - 2](https://user-images.githubusercontent.com/45795798/159154329-ea51babf-1f1f-45d3-9522-a9f69df65a94.png)
![lumi acpartner mcn04  KTB04LM - 3](https://user-images.githubusercontent.com/45795798/159154562-94c030d8-039f-427a-bb09-60c883b8eddb.png)

Both devices are configured via cloud.  I have a MCN2 as well and that reports target temperature correctly.

**Comment by al-one** [comment]
Show me the entity [attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by johnjoemorgan** [comment]
climate.lumi_mcn04_8e92_air_conditioner
Aircon Air Conditioner
	off 	hvac_modes: auto, cool, heat, dry, fan_only, off
	
	
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
swing_modes: Off, Vertical
current_temperature: null
temperature: 26
fan_mode: Auto
swing_mode: Vertical
model: lumi.acpartner.mcn04
lan_ip: 192.168.0.108
mac_address: 58:B6:23:37:8E:92
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:air-condition-outlet:0000A045:lumi-mcn04:1
air_conditioner.on: false
air_conditioner.mode: 4
air_conditioner.fault: 0
target_temperature-3-4: 26
indicator_light: 1
indicator_light.effective_time: 393234
ac_function.set_ele_info: 
ac_function.brand_id: 12
ac_function.remote_id: 4736
ac_function.ac_mode: 1
ac_function.ac_type: 2
ac_function.ac_ctrl_range: {"models":[{"mode":0,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":1,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":2,"speeds":[0,1,2,3],"temps":[],"directs":[1],"type":2},{"mode":3,"speeds":[1,2,3],"temps":[],"directs":[1],"type":2},{"mode":4,"speeds":[0],"temps":[],"directs":[1],"type":2}]}
ac_function.ac_state: P1_M4_S0_D0
ac_function.quick_cool_enable: false
ac_function.quick_cool_time: 10
ac_function.quick_cool_status: 0
ac_function.sleep_cfg: [0]
ac_function.sleep_status: 0
power_consumption: 254.637
electric_power-7-2: 0
power_consumption-7-3: 0.23
electric_power-7-4: 0
fan_control.fan_level: 0
fan_control.vertical_swing: true
state_updater: lan
sub_entities: power_consumption-7.power_consumption-1, power_consumption-7.electric_power-2, power_consumption-7.power_consumption-3, power_consumption-7.electric_power-4
icon: phu:lg-aircon
friendly_name: Aircon Air Conditioner
supported_features: 41

**Comment by johnjoemorgan** [comment]
The second aircon shows 255C

oys Aircon Air Conditioner
	dry 	hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
swing_modes: Off, Vertical
current_temperature: null
temperature: 30
fan_mode: Auto
swing_mode: Vertical
model: lumi.acpartner.mcn02
lan_ip: 192.168.0.65
mac_address: 54:48:E6:E9:06:51
entity_class: MiotClimateEntity
home_room: chinrse home Kids' room
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:lumi-mcn02:1
electric_power: 913.75
power_cost_today: 1562
power_cost_month: 31267
air_conditioner.on: true
air_conditioner.mode: 2
target_temperature-2-3: 30
fan_control.fan_level: 0
fan_control.vertical_swing: true
state_updater: lan
sub_entities: electric_power, power_cost_today, power_cost_month
friendly_name: Boys Aircon Air Conditioner
supported_features: 41
climate.lumi_mcn04_5755_air_conditioner
Jess Aircon Air Conditioner
	off 	hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
swing_modes: Off, Vertical
current_temperature: null
temperature: 255
fan_mode: Auto
swing_mode: Vertical
model: lumi.acpartner.mcn04
lan_ip: 192.168.YY.XX
mac_address: 54:48:E6:E3:YY:XX
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:air-condition-outlet:0000A045:lumi-mcn04:1
air_conditioner.on: false
air_conditioner.mode: 4
air_conditioner.fault: 0
target_temperature-3-4: 255
indicator_light: 1
indicator_light.effective_time: 393237
ac_function.set_ele_info: 
ac_function.brand_id: 12
ac_function.remote_id: 4736
ac_function.ac_mode: 1
ac_function.ac_type: 2
ac_function.ac_ctrl_range: {"models":[{"mode":0,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":1,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":2,"speeds":[0,1,2,3],"temps":[],"directs":[1],"type":2},{"mode":3,"speeds":[1,2,3],"temps":[],"directs":[1],"type":2},{"mode":4,"speeds":[0],"temps":[],"directs":[1],"type":2}]}
ac_function.ac_state: P1_M4_S0_D0
ac_function.quick_cool_enable: false
ac_function.quick_cool_time: 10
ac_function.quick_cool_status: 0
ac_function.sleep_cfg: [0]
ac_function.sleep_status: 0
power_consumption: 54.969
electric_power-7-2: 0
power_consumption-7-3: 0
electric_power-7-4: 0
fan_control.fan_level: 0
fan_control.vertical_swing: true
state_updater: lan
sub_entities: power_consumption-7.power_consumption-1, power_consumption-7.electric_power-2, power_consumption-7.power_consumption-3, power_consumption-7.electric_power-4
friendly_name: Jess Aircon Air Conditioner
supported_features: 41
chunk_properties: 7
miot_cloud: false

**Comment by johnjoemorgan** [comment]
The other unit is still showiong 255C

=============

climate.lumi_mcn04_5755_air_conditioner
Jess Aircon Air Conditioner
	dry 	hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
swing_modes: Off, Vertical
current_temperature: null
temperature: 255
fan_mode: Auto
swing_mode: Vertical
model: lumi.acpartner.mcn04
lan_ip: 192.168.
mac_address: 54:48:E6:E3:
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:air-condition-outlet:0000A045:lumi-mcn04:1
air_conditioner.on: true
air_conditioner.mode: 4
air_conditioner.fault: 0
target_temperature-3-4: 255
indicator_light: 1
indicator_light.effective_time: 393237
ac_function.set_ele_info: 
ac_function.brand_id: 12
ac_function.remote_id: 4736
ac_function.ac_mode: 1
ac_function.ac_type: 2
ac_function.ac_ctrl_range: {"models":[{"mode":0,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":1,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":2,"speeds":[0,1,2,3],"temps":[],"directs":[1],"type":2},{"mode":3,"speeds":[1,2,3],"temps":[],"directs":[1],"type":2},{"mode":4,"speeds":[0],"temps":[],"directs":[1],"type":2}]}
ac_function.ac_state: P0_M4_S0_D0
ac_function.quick_cool_enable: false
ac_function.quick_cool_time: 10
ac_function.quick_cool_status: 0
ac_function.sleep_cfg: [0]
ac_function.sleep_status: 0
power_consumption: 54.969
electric_power-7-2: 1167
power_consumption-7-3: 0
electric_power-7-4: 0
fan_control.fan_level: 0
fan_control.vertical_swing: true
state_updater: lan
sub_entities: power_consumption-7.power_consumption-1, power_consumption-7.electric_power-2, power_consumption-7.power_consumption-3, power_consumption-7.electric_power-4
friendly_name: Jess Aircon Air Conditioner
supported_features: 41
chunk_properties: 7
miot_cloud: false

**Comment by al-one** [comment]
I have a device of the same model as yours and it works just fine.
```yaml
hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: 自动, 低档, 中档, 高档
swing_modes: Off, Vertical
current_temperature: null
temperature: 29
fan_mode: 高档
swing_mode: Vertical
model: lumi.acpartner.mcn04
lan_ip: 192.168.26.15
mac_address: 58:B6:23:78:D9:15
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:air-condition-outlet:0000A045:lumi-mcn04:1
power_cost_today: 0
power_cost_month: 0
air_conditioner.on: false
air_conditioner.mode: 3
air_conditioner.fault: 0
target_temperature-3-4: 29 # target temperature
indicator_light: 0
indicator_light.effective_time: 589845
ac_function.set_ele_info: 
ac_function.brand_id: 97
ac_function.remote_id: 10727
ac_function.ac_mode: 1
ac_function.ac_type: 2
ac_function.ac_ctrl_range: {"models":[{"mode":0,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":1,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":2,"speeds":[0,1,2,3],"temps":[],"directs":[1],"type":2},{"mode":3,"speeds":[0,1,2,3],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2},{"mode":4,"speeds":[1],"temps":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"directs":[1],"type":2}]}
ac_function.ac_state: P1_M3_T29_S3_D0
ac_function.quick_cool_enable: false
ac_function.quick_cool_time: 10
ac_function.quick_cool_status: 0
ac_function.sleep_cfg: [0]
ac_function.sleep_status: 0
power_consumption: 1.364
electric_power-7-2: 1
power_consumption-7-3: 0
electric_power-7-4: 0
fan_control.fan_level: 3
fan_control.vertical_swing: true
state_updater: lan
sub_entities: power_consumption-7.power_consumption-1, power_consumption-7.electric_power-2, power_consumption-7.power_consumption-3, power_consumption-7.electric_power-4, power_cost_today, power_cost_month
icon: mdi:air-conditioner
friendly_name: 主卧空调
supported_features: 41
```
