### ISSUE TITLE
Dreame D9 & L10 Pro specific room cleaning

### ISSUE THREAD

**Issue by Sim0cYz** [al-one/hass-xiaomi-miot#491]
Hello! I tried to follow other issues to setup specific room cleaning in Home Assistant for my robots (D9 and L10 Pro) without any success. I am only able to create scripts to start, stop whole floor cleaning and return to docking station.

For example:

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2029_2133_robot_cleaner
  siid: 3
  aiid: 1
  throw: true
```
is successfully returning to the base, but this does nothing:

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2029_1882_robot_cleaner
  siid: 2
  aiid: 3
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[3,1,3,3,1]]}''
```

__Originally posted by @xBourner in https://github.com/al-one/hass-xiaomi-miot/issues/449#issuecomment-1050818124__

and I can't understand where are those params took from..

I tried to use [Vevs' modded MiHome APK](https://github.com/al-one/hass-xiaomi-miot/issues/114#issuecomment-868721912), but I'm missing something because I can't find room ids in my logs. What should I do and what should I look for? 
Thank you!

**Comment by al-one** [comment]
You can show me the vevs logs.

**Comment by Sim0cYz** [comment]
Sure, hope pastebin is ok for you.

[D9](https://pastebin.com/fb8K3ru0)
[L10 Pro](https://pastebin.com/yuPeHMdg)

Let me know if you needed something else. Thank you!

**Comment by al-one** [comment]
- [dreame.vacuum.p2009 D9](https://home.miot-spec.com/spec/dreame.vacuum.p2009)
- [dreame.vacuum.p2029 L10 Pro](https://home.miot-spec.com/spec/dreame.vacuum.p2029)

```yaml
- siid: 2 # vacuum
  aiid: 3 # start-room-sweep
- siid: 4 # vacuum-extend
  aiid: 1 # start-clean
```

`2022-03-27 19:54:38 -> {"id":4004,"method":"action","params":{"did":"447506991","siid":4,"aiid":1,"in":[{"piid":1,"value":18},{"piid":10,"value":"{\"selects\":[[4,1,2,2,1]]}"}]}}`

If only one related record is found in your logs, please clean your each room in the Mihone APP (vevs) and then search for `"siid":2,"aiid":3` or `"siid":4,"aiid":1` in the logs.

**Comment by Sim0cYz** [comment]
Thank you, I tried creating this script:
```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2029_2133_robot_cleaner
  siid: 2
  aiid: 3
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[4,1,2,2,1]]}''
```
but it does nothing..
Do I need to control it via Cloud, or locally should work too?

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum. dreame_p2029_2133_robot_cleaner
  siid: 2
  aiid: 3
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[3,1,3,3,1]]}'
```
The original post mistakenly wrote an extra quotation mark.

**Comment by Sim0cYz** [comment]
Thank you, that worked! But I find out that my L10 Pro goes unavailable after few hours, without I do anything.
Is that a known issue? Thank you

**Comment by al-one** [comment]
If you find some [error/warning logs](https://my.home-assistant.io/redirect/logs) after it's unavailable, please report it to me via a new issue.

**Comment by Sim0cYz** [comment]
> If you find some [error/warning logs](https://my.home-assistant.io/redirect/logs) after it's unavailable, please report it to me via a new issue.

[Here's the new issue](https://github.com/al-one/hass-xiaomi-miot/issues/526) and it's related for sure to this issue of being unable to clean certain rooms with scripts (in cloud mode they don't work, but in local mode - when it happened to be available - they worked fine)

**Comment by Sim0cYz** [comment]
Ok so it was a connection issue between Home Assistant Core and my device, solved as in the issue linked above. Now the script to clean a specific room works, without that extra quotation mark. This works fine:
```yaml
entity_id: vacuum.dreame_p2029_2133_robot_cleaner
siid: 4
aiid: 1
params:
  - piid: 1
    value: 18
  - piid: 10
    value: '{"selects":[[4,1,2,2,1]]}'
force_params: true
throw: true
```

Thank you for your kind support! 👍

**Comment by jlssmt** [comment]
Hi @Sim0cYz 
I also have your Dreame D9. I tried to adapt your calls above for the L10. Unfortunately, I can't get it to work. I figured out my room IDs. Would you happen to have a current running template for the D9 for me? Thanks in advance ;-)

**Comment by maxdobmax** [comment]
Same for me,
This method doesn't work for me, could somebody clarify if I have any mitsake in this code:

```
actions:
  - action: script.standard_mode_on
    metadata: {}
    data: {}
  - action: xiaomi_miot.call_action
    data:
      entity_id: vacuum.xiaomi_d110ch_b6d2_robot_cleaner
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 10
          value: "{\"selects\":[6,1,1,2,1]}"
      force_params: true
mode: single
```

Tried plenty variants with different types of quotes, brackets - doesn't work at all while all other commands for exanmple piid 2 and aiid 2 - makes Vacuum Cleaner running and working properly. 

![Image](https://github.com/user-attachments/assets/ad2dbc0e-69e5-466b-bde5-72f4350a5800)
