### ISSUE TITLE
79元的空调伴侣2不可用

### ISSUE THREAD

**Issue by mikeinblue** [al-one/hass-xiaomi-miot#5]
可以添加，但不可用
![620F6357-D90A-43BA-9D40-21C32F415138](https://user-images.githubusercontent.com/62834868/105519908-fc62e200-5d14-11eb-87eb-f459c7e42055.jpeg)

**Comment by al-one** [comment]
请问具体型号多少？以及有无报错日志？

**Comment by mikeinblue** [comment]
我现在是按
https://bbs.hassbian.com/forum.php?mod=viewthread&tid=10763&highlight=%E7%A9%BA%E8%B0%83%E4%BC%B4%E4%BE%A32
这个帖子的方法接入的

**Comment by al-one** [comment]
> 我现在是按
> https://bbs.hassbian.com/forum.php?mod=viewthread&tid=10763&highlight=%E7%A9%BA%E8%B0%83%E4%BC%B4%E4%BE%A32
> 这个帖子的方法接入的

与本插件无关

**Comment by mikeinblue** [comment]
我按照上面的方法可以用，但不理想。用您的这个插件是截图的那个，我想知道您的插件是不是能支持这个空调伴侣

**Comment by al-one** [comment]
你的设备型号是多少？
可以下载最新版再试下。

**Comment by mikeinblue** [comment]
Model ID:lumi.acpartner.mcn02
Model number:KTBL03LM	
Product name:Xiaomi Mi Air Conditioner Companion 2

我再试试新的插件，因为这个空调伴侣比较特殊，插件只有一个

**Comment by lipwah** [comment]
一样不可用，可以添加
Logger: custom_components.xiaomi_miot
Source: custom_components/xiaomi_miot/__init__.py:418
Integration: Xiaomi Miot (documentation, issues)
First occurred: 下午11:02:54 (2 occurrences)
Last logged: 下午11:03:58

Got exception while fetching the state for None: {'code': -9999, 'message': 'user ack timeout'}
Got exception while fetching the state for climate.kong_diao_cha_zuo_air_conditioner: {'code': -9999, 'message': 'user ack timeout'}

**Comment by al-one** [comment]
-9999的设备可以通过配置miot_cloud解决

**Comment by aktifin** [comment]
通过cloud模式空调伴侣二代成功接入

**Comment by lipwah** [comment]
> 通过cloud模式空调伴侣二代成功接入

怎样配置

**Comment by al-one** [comment]
> > 通过cloud模式空调伴侣二代成功接入
> 
> 怎样配置

https://github.com/al-one/hass-xiaomi-miot#configuration-xiaomi-cloud


```yaml
# configuration.yaml
xiaomi_miot:
  username: xiaomi_username
  password: xiaomi_password

# customize.yaml (Configuration > Customize > Select Entity > Add Other Attribute)
climate.xiaomi_mc5_374e: # Your entity id
  miot_cloud: true    # Enabled cloud
  # miot_did: 123456789 # Your miot device id, Optional (Get form cloud)
```
