### ISSUE TITLE
Mi 360° Home Security Camera 2K Pro (chuangmi.camera.021a04)

### ISSUE THREAD

**Issue by Benny2102** [al-one/hass-xiaomi-miot#50]
I bought a camera.  You have not created an entity.  Is it possible to add?

**Comment by al-one** [comment]
Try last commit: https://github.com/al-one/hass-xiaomi-miot/commit/3788f2601b52936b34340cc7fdad85835a4d08c0 of [master](https://github.com/al-one/hass-xiaomi-miot/tree/master).

**Comment by Benny2102** [comment]
Unfortunately, there is no success.

**Comment by al-one** [comment]
### Get Entity State Attributes

> [🔨 Developer tools](https://my.home-assistant.io/redirect/developer_states) > [ℹ️ State](https://my.home-assistant.io/redirect/developer_states) > 🔍 Filter Entity

### [Get Debug Logs](https://www.home-assistant.io/integrations/logger)

```yaml
# configuration.yaml
logger:
  default: warning
  logs:
    custom_components.xiaomi_miot: debug
```

> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > [✍️ Logs](https://my.home-assistant.io/redirect/logs)
