### ISSUE TITLE
How to launch cleaning specific room

### ISSUE THREAD

**Issue by antoweb** [al-one/hass-xiaomi-miot#506]
I have integrated my mop 2 pro and used vevs modded app xiaomi home for log.

I cant understand how to launch from HA for cleaning specific area/room

Can you help me?

**Comment by al-one** [comment]
Show me vevs logs after your mop clean each room.

**Comment by antoweb** [comment]
Ok i will generate. Just vacuum or washing else?

**Comment by antoweb** [comment]
Yes but each room with separately job or compelte cleaning all home?

**Comment by al-one** [comment]
Separately, and only need to send the command, no need to wait for completion.

**Comment by antoweb** [comment]
[room3_MY_MAP_ID.txt](https://github.com/al-one/hass-xiaomi-miot/files/8450981/room3_MY_MAP_ID.txt)
[room4_MY_MAP_ID.txt](https://github.com/al-one/hass-xiaomi-miot/files/8450982/room4_MY_MAP_ID.txt)
[room5_MY_MAP_ID.txt](https://github.com/al-one/hass-xiaomi-miot/files/8450983/room5_MY_MAP_ID.txt)
[room1_MY_MAP_ID.txt](https://github.com/al-one/hass-xiaomi-miot/files/8450984/room1_MY_MAP_ID.txt)
[room2_MY_MAP_ID.txt](https://github.com/al-one/hass-xiaomi-miot/files/8450985/room2_MY_MAP_ID.txt)
Attached one file for every room. I have started the room cleaning than stopped.
I have omitted sensitive data such map id and token
Thanks for your help

**Comment by antoweb** [comment]
Error in debug log:

2022-04-08 18:51:45 DEBUG (MainThread) [custom_components.xiaomi_miot.vacuum] Aspirapolvere(ijai.vacuum.v3): Got new state: {'vacuum.status': 4, 'vacuum.fault': 2103, 'vacuum.mode': 0, 'vacuum.sweep_type': 0, 'vacuu
m.on': '[1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]', 'disturb.dnd_enable': 1, 'disturb.dnd_start_hour': 23, 'disturb.dnd_start_minute': 0, 'disturb.dnd_end_hour': 8, 'disturb.dnd_end_minute': 0, 'disturb.multi_prop_dnd': '[1
,23,0,8,0]', 'map.remember_state': 1, 'map.cur_map_id': 1649342728, 'map.map_num': 2, '**map.cur_cleaning_path.error': '-704220043 Property value error', 'map.build_map': 0, 'map.has_new_map': 0, 'map.map_uploads.erro**
r': '-704030013 Property is not readable', 'sweep.repeat_state': 0, 'sweep.door_state': 1, 'sweep.cloth_state': 1, 'sweep.suction_state': 3, 'sweep.water_state': 1, 'sweep.mop_route': 0, 'sweep.side_brush_life': 97,
 'sweep.side_brush_hours': 176, 'sweep.main_brush_life': 98, 'sweep.main_brush_hours': 356, 'sweep.hypa_life': 97, 'sweep.hypa_hours': 176, 'sweep.mop_life': 97, 'sweep.mop_hours': 176, '**sweep.direction.error': '-70
4030013 Property is not readable**', 'sweep.time_zone': -7200, 'sweep.cur_lang': 'it_IT', 'sweep.cleaning_time': 0, 'sweep.cleaning_area': 0, 'sweep.multi_prop_vacuum': '[0,1,1,3,1,0,-7200,14,12.5,0,"it_IT","334702602
10948870","it_IT",-1,-1,0,0,1,2]', 'sweep.tank_shake': 1, 'sweep.shake_shift': 2, 'alarm': 1, 'alarm.volume': 10, 'battery.battery_level': 66, 'state_updater': 'cloud'}

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/ijai.vacuum.v3
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.ijai_v3_your_entity_id
  siid: 7 # sweep
  aiid: 3 # set-room-clean
  params:
    - '10' # clean-room-ids
    - 0 # clean-room-mode
    - 1 # clean-room-oper
```

Your room ids are `10,11,12,13,15`, you can lookup `"aiid":3` in vevs logs.
```
{"params":{"aiid":3,"did":"MY_MAP_ID","in":["10",0,1],"siid":7}} /miotspec/action
```

**Comment by antoweb** [comment]
Hi, thanks very good.
Can you please explain how to use clean-rom-mode and clean-room-oper? In page you have posted i see
24 - clean-room-ids
25 - clean-room-mode
26 - clean-room-oper

wich are the mode and oper codes?

Another question:
WHen launching the script from HA the first time receive an error on Mi Home app because in app last modes was setted in wash mode and because water tank was not inserted generating error. After change fro Mi Home app to sweep only the HA script started successfully. There is a method to change the last modem used in app?

**Comment by antoweb** [comment]
Another question: When i pause the robot the state of the entity in HA goes to docker should be paused. :-)

**Comment by al-one** [comment]
```javascript
[
    {
        "iid":24,
        "type":"urn:ijai-spec:property:clean-room-ids:00000013:ijai-v3:1",
        "description":"",
        "format":"string",
        "access":[],
        "unit":"none"
    },
    {
        "iid":25,
        "type":"urn:ijai-spec:property:clean-room-mode:00000016:ijai-v3:1",
        "description":"",
        "format":"uint8",
        "access":[],
        "unit":"none",
        "value-list":[
            {
                "value":0,
                "description":"全局" // global
            },
            {
                "value":1,
                "description":"沿边" // along the edge
            }
        ]
    },
    {
        "iid":26,
        "type":"urn:ijai-spec:property:clean-room-oper:00000017:ijai-v3:1",
        "description":"clean-room-oper",
        "format":"uint8",
        "access":[],
        "unit":"none",
        "value-list":[
            {
                "value":0,
                "description":"停止" // stop
            },
            {
                "value":1,
                "description":"开始" // start
            },
            {
                "value":2,
                "description":"暂停" // pause
            },
            {
                "value":3,
                "description":"假暂停" // pause
            }
        ]
    }
]
```

**Comment by antoweb** [comment]
Ok....and wath means? I have to do something?

**Comment by al-one** [comment]
> WHen launching the script from HA the first time receive an error on Mi Home app because in app last modes was setted in wash mode and because water tank was not inserted generating error. After change fro Mi Home app to sweep only the HA script started successfully. There is a method to change the last modem used in app?

```yaml
service: xiaomi_miot.set_property
data:
  entity_id: vacuum. ijai_v3_your_entity_id
  field: vacuum.mode
  value: 0 # 0: Sweep 1: Sweep And Mop 2: Mop
```

**Comment by antoweb** [comment]
> > WHen launching the script from HA the first time receive an error on Mi Home app because in app last modes was setted in wash mode and because water tank was not inserted generating error. After change fro Mi Home app to sweep only the HA script started successfully. There is a method to change the last modem used in app?
> 
> ```yaml
> service: xiaomi_miot.set_property
> data:
>   entity_id: vacuum. ijai_v3_your_entity_id
>   field: vacuum.mode
>   value: 0 # 0: Sweep 1: Sweep And Mop 2: Mop
> ```

Many thanks !!!

**Comment by antoweb** [comment]
Sorry last help pls:
I want to cleaning a specific area (not a room) attached is the log,
i have created a script like:

aspira_intorno_isola:
  alias: Aspira intorno isola
  sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 9
      aiid: 8
      params:
      - - 8.645
      - 1.605
      - - 8.645
      - - 1.092
      - - 5.147
      - - 1.092
      - - 5.147
[pulizia_intorno_isola.txt](https://github.com/al-one/hass-xiaomi-miot/files/8463613/pulizia_intorno_isola.txt)

      - 1.605
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 10
      aiid: 12
      params:
      - 148
      - 157
  mode: single

but nothing happened

**Comment by antoweb** [comment]
[pulizia_intorno_isola.txt](https://github.com/al-one/hass-xiaomi-miot/files/8463616/pulizia_intorno_isola.txt)

**Comment by antoweb** [comment]
> ```js
> [
>     {
>         "iid":24,
>         "type":"urn:ijai-spec:property:clean-room-ids:00000013:ijai-v3:1",
>         "description":"",
>         "format":"string",
>         "access":[],
>         "unit":"none"
>     },
>     {
>         "iid":25,
>         "type":"urn:ijai-spec:property:clean-room-mode:00000016:ijai-v3:1",
>         "description":"clean-room-mode",
>         "format":"uint8",
>         "access":[],
>         "unit":"none",
>         "value-list":[
>             {
>                 "value":0,
>                 "description":"全局" // global
>             },
>             {
>                 "value":1,
>                 "description":"沿边" // along the edge
>             }
>         ]
>     },
>     {
>         "iid":26,
>         "type":"urn:ijai-spec:property:clean-room-oper:00000017:ijai-v3:1",
>         "description":"clean-room-oper",
>         "format":"uint8",
>         "access":[],
>         "unit":"none",
>         "value-list":[
>             {
>                 "value":0,
>                 "description":"停止" // stop
>             },
>             {
>                 "value":1,
>                 "description":"开始" // start
>             },
>             {
>                 "value":2,
>                 "description":"暂停" // pause
>             },
>             {
>                 "value":3,
>                 "description":"假暂停" // pause
>             }
>         ]
>     }
> ]
> ```

I have tried and there is actually something wrong. the status ids in HA front end is are:

5 cleaning
3 returning
1 docked
4 docked

While status 1 should be paused

**Comment by antoweb** [comment]
> Sorry last help pls: I want to cleaning a specific area (not a room) attached is the log, i have created a script like:
> 
> ```
> aspira_intorno_isola:
>   alias: Aspira intorno isola
>   sequence:
>   - service: xiaomi_miot.call_action
>     data:
>       entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
>       siid: 9
>       aiid: 8
>       params:
>       - - 8.645
>       - 1.605
>       - - 8.645
>       - - 1.092
>       - - 5.147
>       - - 1.092
>       - - 5.147
>       - 1.605
>   - service: xiaomi_miot.call_action
>     data:
>       entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
>       siid: 10
>       aiid: 12
>       params:
>       - 148
>       - 157
>   mode: single
> ```
> 
> but nothing happened

Solved by myself :-) correct script is:

```
aspira_intorno_isola:
  alias: Aspira intorno isola
  sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 9
      aiid: 8
      params: -8.645,1.605,-8.645,-1.092,-5.147,-1.092,-5.147,1.605
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 9
      aiid: 3
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 10
      aiid: 12
      params:
      - 148
      - 157
  mode: single
```

**Comment by antoweb** [comment]
Hello can i ask another help?
Now works all good but i have a question:
The first time i have configured a room cleaning script on HA in the Xiaomi app  I saw just before the cleaning started, the area that will be cleaned was highlighted. Now this doesn't happen anymore. Is it possible to highlight in the xiaomi app the area that is going to be cleaned when the vacuum cleaner starts?

**Comment by paulakfleck** [comment]
@antoweb @al-one Hey! I know it's been a while since o your post, but I have a very similar model as yours and I'm having a hard time making it clean a specified zone.

This is my model: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:ijai-v10:1

I'm running this same sequence of services here as you:
```yaml
aspira_intorno_isola:
  alias: Aspira intorno isola
  sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 9
      aiid: 8
      params: -8.645,1.605,-8.645,-1.092,-5.147,-1.092,-5.147,1.605
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 9
      aiid: 3
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v3_b0ec_robot_cleaner
      siid: 10
      aiid: 12
      params:
      - 148
      - 157
  mode: single
```
I have a few questions: 

1) So, does your robot goes sweeping after all these 3 services?

2) What are these params? `params: -8.645,1.605,-8.645,-1.092,-5.147,-1.092,-5.147,1.605` I see my zones are 4 coordinates, but here you're sending 8. Why is that?

3) After you make the fist service call (siid 9, aiid 8), how does the API respond? I see this here: 
```json
{'code': 0, 'out': [{'piid': 7, 'value': 1}, {'piid': 8, 'value': 0}, {'piid': 9, 'value': 0}]}
```

I imagine 1, 0 and 0 are the map-id, map-type and timestamp. But I don't know if 1, 0 and 0 means it's not working.

4) In your last service, what these params are? `- 148 - 157`

Thank you so much in advance, both of you!
