### ISSUE TITLE
How to interpret Vacuum Status

### ISSUE THREAD

**Issue by buhito81** [al-one/hass-xiaomi-miot#507]
My robot vacuum has a state_attr called vacuum.status, which (seemingly) reports values between 1-6. How can I interpret this different statuses? I've thusfar figured out that vacuum.status '4' is an error, which enables me to restart it from an automation (brush errors occur frequently with my carpets), but I'd like to determine if the vacuum is just "returning to the dock to charge" or if it has completed cleaning. As I have a fairly basic vacuum, this appears to be the only way to do it - in order to have other automations determine if the house has been cleaned.

Any help would be appreciated.

[mijia.vacuum.v2](https://home.miot-spec.com/s/mijia.vacuum.v2)

**Comment by al-one** [comment]
Show me the [entity state attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by buhito81** [comment]
![image](https://user-images.githubusercontent.com/101875447/162466888-5b52de07-d5bb-46fb-bf1b-d4ac774bd703.png)

Values here will be between 1-6, depending on operation.

**Comment by al-one** [comment]
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:mijia-v2:1
```json
{
    "iid":1,
    "type":"urn:miot-spec-v2:property:status:00000007:mijia-v2:1",
    "description":"Status",
    "format":"uint8",
    "access":["read", "notify"],
    "unit":"none",
    "value-list":[
        {"value":1, "description":"Idle"},
        {"value":2, "description":"Sweeping"},
        {"value":3, "description":"Paused"},
        {"value":4, "description":"Error"},
        {"value":5, "description":"Charging"},
        {"value":6, "description":"Go Charging"}
    ]
}
```

You can create sensor entities by `device_customizes`:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    mijia.vacuum.v2:
      sensor_properties: vacuum.status,vacuum.fault,charging_state,clean_area,clean_time,total_clean_area,total_clean_time,total_clean_count,brush_life_level
      select_properties: mode,target_water_level
```
