### ISSUE TITLE
Please support deerma.humidifier.jsq buzzer and child lock

### ISSUE THREAD

**Issue by fantnhu** [al-one/hass-xiaomi-miot#514]
Hi!
Thank you for your work, this is a wonderful integration. i use [deerma.humidifier.jsq](https://home.miot-spec.com/s/deerma.humidifier.jsq) humidifier which i can also control. Whats missing:
- Child lock
- Buzzer
Please add these.
![image](https://user-images.githubusercontent.com/73642352/162611286-7009e7a5-dfe5-42ca-8fde-0c870b290a5a.png)
Thank you! :)

**Comment by al-one** [comment]
This device seems to only support beeping, not child lock, if the MIHome APP has it, please send me a screenshot.
Add a buzzer switch entity:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq:
      switch_properties: alarm
```
