### ISSUE TITLE
After last update state_updater: lan

### ISSUE THREAD

**Issue by NikDevx** [al-one/hass-xiaomi-miot#52]
I didn't change my config.yaml
```
xiaomi_miot:
  username: ****
  password: ***
  server_country: de
```

Always see `state_updater: lan`
