### ISSUE TITLE
Xiamo Miaja Termostat Heatcold get property error -4004

### ISSUE THREAD

**Issue by rndvip** [al-one/hass-xiaomi-miot#521]
i have two device:

- climate.cubee_th125t_7946_thermostat
- climate.cubee_th123e_790d_thermostat

xiaomi_miot.get_properties return only firts mapping property, no matter how many I ask
```yaml
service: xiaomi_miot.get_properties
data:
  entity_id: climate.cubee_th125t_7946_thermostat
  mapping:
    on:
      siid: 2
      piid: 1     
    status:
      siid: 2
      piid: 2       
  throw: true
```
return
`[{'did': 'prop.2.1', 'siid': 2, 'piid': 1, 'code': 0, 'value': True}, {'did': 'prop.2.2', 'siid': 2, 'piid': 2, 'code': -4004}]`

if chek status of device
```yaml
hvac_modes: cool, heat, off
min_temp: 0
max_temp: 90
target_temp_step: 1
fan_modes: Low, Medium, High, Auto
preset_modes: UFH And AC, UFH, off
current_temperature: 25
temperature: 0
fan_mode: null
preset_mode: UFH And AC
model: cubee.airrtc.th125t
lan_ip: 192.168.88.228
mac_address: 54:48:E6:53:79:46
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:cubee-th125t:1
thermostat.on: true
thermostat.status.error: -4004 Other internal errors
thermostat.fault.error: -4004 Other internal errors
thermostat.target_temperature.error: -4004 Other internal errors
thermostat.fan_level.error: -4004 Other internal errors
heatold.childlock: false
heatold.sensortype.error: -4004 Other internal errors
heatold.tempcomp.error: -4004 Other internal errors
heatold.tempfloor.error: -4004 Other internal errors
heatold.minsettemp.error: -4004 Other internal errors
state_updater: lan
thermostat.mode: 2
thermostat.temperature: 25
heatold.childlock.error: -4004 Other internal errors
heatold.tempactivate: 1
heatold.maxsettemp: 40
friendly_name: Конвектор
supported_features: 25
chunk_properties: 3
```

**Comment by al-one** [comment]
Try this configuration:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    cubee.airrtc.th125t:
      chunk_properties: 1
```
