### ISSUE TITLE
chuangmi.camera.ipc016 - set state on/off for alarm and not dynamic data like cam1: Motion detected at 10:00

### ISSUE THREAD

**Issue by marian790** [al-one/hass-xiaomi-miot#524]
Hi, is possible to add some sensor entity if camera make alarm? So i than setup some automations if alarm is on....

EDIT: so find entity Xiaomi 123456789 message, that triger new state if alarm (motion) detected).

BUT, state is dynamic value, like "cam1: Motion detected at 10:00"... It will be better, if state have only defined values like "on/off"
and in event have info, what make alarm, like "cam1: Motion detected at 10:00"....

**Comment by al-one** [comment]
`sensor.mi_123456789_message` is not the entity of the camera, it is the MiHome APP system notification.
You can create a motion sensor from a template:
```yaml
# configuration.yaml
template:
  - trigger:
      - platform: state
        entity_id: sensor.mi_123456789_message
    binary_sensor:
      - name: cam1 motion
        state: |-
          {{ 'cam1: Motion detected' in trigger.to_state.state
          and as_timestamp(now()) - as_timestamp(trigger.to_state.attributes.timestamp or now()) < 90 }}
        device_class: motion
```
