### ISSUE TITLE
Error deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by Mick51** [al-one/hass-xiaomi-miot#533]
I have been getting this error for some time, why ?

`Cette erreur provient d'une intégration personnalisée

Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1242
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 17:47:00 (1 occurrences)
Last logged: 17:47:00

Antibacterial Humidifier(deerma.humidifier.jsq5): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 4/8`

**Comment by al-one** [comment]
Try to [add this custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities) and observe again:
```yaml
# customize.yaml
humidifier.deerma_jsq5_entity_id:
  chunk_properties: 1
  interval_seconds: 90
  exclude_miot_services: alarm,custom,indicator_light
```

**Comment by Mick51** [comment]
> Try to [add this custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities) and observe again:
> 
> ```yaml
> # customize.yaml
> humidifier.deerma_jsq5_entity_id:
>   chunk_properties: 1
>   interval_seconds: 90
>   exclude_miot_services: alarm,custom,indicator_light
> ```

Do you need to create this file and put it in the config directory ?

**Comment by al-one** [comment]
```yaml
# configuration.yaml
homeassistant:
  customize: !include customize.yaml
```
