### ISSUE TITLE
米家智能插座云端模式功率错误

### ISSUE THREAD

**Issue by goomadao** [al-one/hass-xiaomi-miot#534]
设备型号： chuangmi.plug.212a01

由于有一个智能插座在另一个地点，只能通过云端模式接入。

本地模式时显示的功率是正确的，云端模式下功率刚好小了100倍（如本来80W，显示0.8W）

如图，从本地模式切换到云端模式后，上报功率数值发生的变化
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/39483078/164404722-19173d4b-6065-48dd-82ed-9355a1a18fef.png">

**Comment by al-one** [comment]
请通过[添加自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)来修复此问题：
```yaml
# customize.yaml
sensor.chuangmi_212a01_7d09_electric_power:
  value_ratio: 1
```
