### ISSUE TITLE
米家晾衣机 hyd.airer.znlyj4 ，状态频繁显示不可用

### ISSUE THREAD

**Issue by tty228** [al-one/hass-xiaomi-miot#538]
卷帘和灯隔一段时间就会显示不可用，出现得比较频繁
卷帘我已经屏蔽了，但是还是想看到灯的日志

操作上都是正常的，灯可以正常开启关闭，卷帘的控制也还算正常（偶尔不可用再恢复之后，卷帘的状态不能同步，会造成状态错误，但通过调用服务是可以操作的）
设备型号 ： hyd.airer.znlyj4
版本：core-2022.4.6
Xiaomi Miot Auto：0.5.7

![QQ截图20220424173809](https://user-images.githubusercontent.com/33397881/164970464-19467390-8828-4362-8845-fe02ba6a3a52.png)

**Comment by al-one** [comment]
请尝试添加以下自定义属性：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    hyd.airer.znlyj4:
      auto_cloud: True     # 本地不可用时自动获取云端状态
      interval_seconds: 90 # 增加轮询间隔时长，减少对设备的负担
      main_miot_services: airer
```
