### ISSUE TITLE
小米智能插座2 轮询时间修改无效

### ISSUE THREAD

**Issue by MURChen** [al-one/hass-xiaomi-miot#546]
interval_seconds: 10 # 轮询间隔时长(秒) 
设备：小米智能插座2 蓝牙网关版
修改 间隔时间到8s  属性值也显示
不生效，仍为30s更新
![Snipaste_2022-04-27_22-16-36](https://user-images.githubusercontent.com/47627266/165539928-f5c1c766-d369-4c8a-91c3-6189ead02a48.png)
![Snipaste_2022-04-27_22-16-59](https://user-images.githubusercontent.com/47627266/165539948-73e6b2cb-4e42-4772-9cb1-485488d2fe62.png)

[](url)

**Comment by al-one** [comment]
自定义属性`interval_seconds`只能作用于父实体，`sensor.chuangmi_212a01_c624_electric_power`为子实体，无法使用该属性。你可以为`switch.chuangmi_212a01_c624_switch`实体定义：
```yaml
# customize.yaml
switch.chuangmi_212a01_c624_switch:
  interval_seconds: 8
```
