### ISSUE TITLE
大神可以把云米viomi.waterheater.u1这个热水器能接入详细一点吗？

### ISSUE THREAD

**Issue by ilongjiang** [al-one/hass-xiaomi-miot#554]
大神可以把云米viomi.waterheater.u1这个热水器能接入详细一点吗？另一位大神接入的有状态属性。米家app也有用气量等

**Comment by al-one** [comment]
请提供开发者工具中的[状态属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by ilongjiang** [comment]
不好意思看错了。大神的插件有两个实体。有一个实体有状态属性了。但是米家里面的用气量和用水量。好像没看到

**Comment by al-one** [comment]
请执行下面的服务[`xiaomi_miot.get_device_data`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.get_device_data)并查看HA通知获取结果：
```yaml
service: xiaomi_miot.get_device_data
data:
  entity_id: water_heater.viomi_u1_xxxx_water_heater # 你的热水器实体ID
  type: event
  key: wash_record
  time_start: 1649952000
  limit: 20
```
