### ISSUE TITLE
leshow.humidifier.jsq1 wrong water level reported

### ISSUE THREAD

**Issue by Aljutor** [al-one/hass-xiaomi-miot#556]
Hi, I've got a [leshow.humidifier.jsq1](https://home.miot-spec.com/spec/leshow.humidifier.jsq1) but it reports water level wrongly 

In devices states it is `device.water_level: 1`
```
min_humidity: 40
max_humidity: 70
available_modes: Off, Const Humidity, Strong, Sleep
device_class: humidifier
friendly_name: Mi Smart Evaporative Humidifer Pro Humidifier
supported_features: 1
humidity: 50
mode: Strong
model: leshow.humidifier.jsq1
lan_ip: *.*.*.*
mac_address: XX:XX:XX:XX:XX:XX
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:1
humidifier.on: true
humidifier.fault: 0
humidifier.mode: 1
humidifier.target_humidity: 50
device.water_level: 1
device.tsms_turn_off: 0
device.turn_off_dry_turn: true
device.warm_wind_turn: 1
device.mode: 1
alarm: true
environment.relative_humidity: 34
state_updater: lan
sub_entities: device-8.water_level-1, environment-3.relative_humidity-1
```
But if I use `Xiaomi Miot Auto: get_properties` service: 
`[{'did': 'prop.2.7', 'siid': 2, 'piid': 7, 'code': 0, 'value': 20}]` 
Same as in MiHome App

Home Assistant 2022.4.7
Xiaomi Miot 0.6.1

**Comment by al-one** [comment]
<img width="495" alt="leshow.humidifier.jsq1" src="https://user-images.githubusercontent.com/4549099/166240359-eb70f1ce-e64b-4318-8b5b-87f74920cfb6.png">

There is no `water_level` property under the `humidifier` service in [`urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:1`](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:1), only [`urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:2`](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:2) has it, but it is debug state.

You need to specify it manually:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    leshow.humidifier.jsq1:
      miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:2
```

**Comment by Aljutor** [comment]
From what I see there is [water-percentage](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:leshow-spec:property:water-percentage:00000007) and [water-level](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:leshow-spec:property:water-level:00000001) property in the "device" section but unfortunately I am not confident in reading this miot specs. 


if I change specification manual as you say, after restart (both, config only and full reload) it's state reports as:

```
min_humidity: 40
max_humidity: 70
available_modes:
  - 'Off'
  - Const Humidity
  - Strong
  - Sleep
humidity: 49
mode: Strong
model: leshow.humidifier.jsq1
lan_ip: *.*.*.*
mac_address: XX:XX:XX:XX:XX:XX
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:1
humidifier.on: true
humidifier.fault: 0
humidifier.mode: 1
humidifier.target_humidity: 49
device.water_level: 2
device.tsms_turn_off: 0
device.turn_off_dry_turn: true
device.warm_wind_turn: 1
device.mode: 1
alarm: true
environment.relative_humidity: 32
state_updater: lan
device_class: humidifier
friendly_name: Mi Smart Evaporative Humidifer Pro Humidifier
supported_features: 1

```


This line seems strange:
`miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:1`

In configuration.yaml I have this:
```
xiaomi_miot:
  device_customizes:
    leshow.humidifier.jsq1:
      miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:2
```

**Comment by al-one** [comment]
Try restart HA.

**Comment by Aljutor** [comment]
> Try restart HA.
Restarted HA, checked logs - nothing, seems like it just ignoring `miot_type` option in customisation

**Comment by al-one** [comment]
Try master branch.

**Comment by Aljutor** [comment]
Thanks for your work, updated, re added device via cloud:
```
min_humidity: 40
max_humidity: 70
available_modes:
  - 'Off'
  - Const Humidity
  - Strong
  - Sleep
humidity: 51
mode: Sleep
model: leshow.humidifier.jsq1
lan_ip: *.*.*.*
mac_address: XX:XX:XX:XX:XX:XX
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:2
humidifier.on: true
humidifier.fault: 0
humidifier.mode: 2
humidifier.target_humidity: 51
humidifier.water_level.error: '-704040003 Property does not exist'
debug.ntc_value.error: '-704040002 Service does not exist'
device.water_level: 2
device.tsms_turn_off: 0
device.turn_off_dry_turn: true
device.warm_wind_turn: true
device.mode: 2
device.turn_ovp.error: '-704040003 Property does not exist'
device.ntc_over_push.error: '-704040003 Property does not exist'
device.dry_turn.error: '-704040003 Property does not exist'
device.overwetting.error: '-704040003 Property does not exist'
screen.on.error: '-704040002 Service does not exist'
screen.brightness.error: '-704040002 Service does not exist'
alarm: true
environment.relative_humidity: 25
state_updater: cloud
device_class: humidifier
friendly_name: Mi Smart Evaporative Humidifer Pro Humidifier
supported_features: 1
sub_entities:
  - environment-3.relative_humidity-1

```

Over local wifi I have this (no updated mitt config)

```
min_humidity: 40
max_humidity: 70
available_modes:
  - 'Off'
  - Const Humidity
  - Strong
  - Sleep
humidity: 51
mode: Sleep
model: leshow.humidifier.jsq1
lan_ip: *.*.*.*
mac_address: XX:XX:XX:XX:XX:XX
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:1
humidifier.on: true
humidifier.fault: 0
humidifier.mode: 2
humidifier.target_humidity: 51
device.water_level: 2
device.tsms_turn_off: 0
device.turn_off_dry_turn: true
device.warm_wind_turn: 1
device.mode: 2
alarm: true
environment.relative_humidity: 25
state_updater: lan
device_class: humidifier
friendly_name: Mi Smart Evaporative Humidifer Pro Humidifier
supported_features: 1
```

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/cbdf7efb8db503c6a0e2e7c4f1981d321bf3cda1, try master branch.

**Comment by Aljutor** [comment]
Added this to `customize.yaml`

```
humidifier.leshow_jsq1_a25f_humidifier:
  sensor_properties: water_level
sensor.leshow_jsq1_a25f_water_level_2:
  icon: mdi:waves-arrow-up
```
And now device look like this:

<img width="309" alt="Screenshot 2022-05-15 at 02 17 02" src="https://user-images.githubusercontent.com/8752722/168451011-242c1404-0b64-497b-be1c-60c23160be62.png">

**Comment by al-one** [comment]
> screen.on.error: '-1'

`-1` is an error code returned by the device when obtaining the state.

About `warm_wind` ... :
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    leshow.humidifier.jsq1:
      miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:leshow-jsq1:2
      sensor_properties: humidifier.water_level
      switch_properties: alarm,warm_wind_turn
```
