### ISSUE TITLE
能否添加米家台式冷热净饮机的制冷保持的实体？

### ISSUE THREAD

**Issue by xiaoluozhou** [al-one/hass-xiaomi-miot#559]
[chunmi.ysj.tsj7](https://home.miot-spec.com/s/chunmi.ysj.tsj7)
相关属性如下：
```yaml
hvac_modes:
  - 'off'
min_temp: 5
max_temp: 95
target_temp_step: 1
current_temperature: 25
temperature: 25
hvac_action: 'off'
model: chunmi.ysj.tsj7
lan_ip: 
mac_address: 
entity_class: MiotClimateEntity
home_room: 
miot_type: urn:miot-spec-v2:device:water-dispenser:0000A0A1:chunmi-tsj7:1
water_dispenser.fault: 0
water_dispenser.status: 4
water_dispenser.temperature: 25
target_temperature-2-6: 25
custom.winter_mode: false
custom.boil_point: 100
custom.lock_temp: 0
custom.power_version: 8
custom.oled_close_time: 3
custom.default_mode: 2
custom.mute_mode: 0
custom.buzz_ctrl: 0
custom.cold_mode: 1
custom.home_temp: 25
custom.clean_precent: 0
custom.stew_two_hour: true
custom.cold_keep: true
filter.filter_life_level: 96
tds_sensor.tds_in: 49
tds_sensor.tds_out: 4
state_updater: cloud
sub_entities:
  - tds_sensor-3.tds_out-2
friendly_name: Mijia Smart Filtered Water Dispenser (Hot and Cold) Water Dispenser
supported_features: 1
```
十分感谢作者的付出，谢谢
