### ISSUE TITLE
威仕达窗帘电机无法正确同步当前状态

### ISSUE THREAD

**Issue by kanppa** [al-one/hass-xiaomi-miot#565]
[urn:miot-spec-v2:device:curtain:0000A00C:090615-ws9856:1](https://home.miot-spec.com/spec/090615.curtain.ws9856)
无法获取正确的current position，当窗帘已经打开时，显示的位置还是之前的位置（比如之前是关闭的0），只有再按一次打开，之后会有一个WARNING (MainThread) [homeassistant.helpers.entity] Update of cover.090615_ws9856_3a49_curtain is taking over 10 seconds。。然后current position会被更新为99，这样窗帘的状态才会变成已打开。这个电机只能用cloud 同步，不知道是否是cloud返回的问题

**Comment by al-one** [comment]
> WARNING (MainThread) [homeassistant.helpers.entity] Update of cover.090615_ws9856_3a49_curtain is taking over 10 seconds

该日志与问题无关。

请观察窗帘打开不同位置时，开发者工具中该实体的属性`curtain.current_position`的值。另外，操作设备后请等待1分钟以等待状态同步至HA。

**Comment by kanppa** [comment]
窗帘打开不同位置的时候 curtain.current_position 的值依然不会被更新，而且不管等待多久都不会被更新，我看到sync thread每次get pos得到的current position都是之前set cover的current position，即使窗帘到位数个小时之后都不会更新到之前的target position

**Comment by al-one** [comment]
你可以尝试添加`target2current_position`[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)，使用`target_position`作为`current_position`：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    090615.curtain.ws9856:
      target2current_position: true
```
