### ISSUE TITLE
Attribute value_ratio problem

### ISSUE THREAD

**Issue by goomadao** [al-one/hass-xiaomi-miot#573]
请教一下，目前我有通过hass将数据吐到InfluxDB，但是hass向InfluxDB输出属性的value_ratio却并不统一，不同型号设备的同一类型的属性数据的比例非常混乱。比如power_cost_today/month属性，`chuangmi.plug.212a01`的14184191代表14.184191 kWh，ratio为0.000001；而`lumi.acpartner.mcn02`的9326代表9.326 kWh，ratio为0.001。能否通过下面两种方法之一或者其他方法解决这个问题：

1. 在属性层级就实现单位(小数点)的统一，而不是通过value_ratio在状态层级去解决
2. 在实体中默认加上value_ratio属性（目前只有在自定义了value_ratio属性的实体中才会有value_ratio属性）

**Comment by al-one** [comment]
> 2. 在实体中默认加上value_ratio属性（目前只有在自定义了value_ratio属性的实体中才会有value_ratio属性）

我将在实体属性中提供`value_ratio`属性。

**Comment by goomadao** [comment]
> 1. 在属性层级就实现单位(小数点)的统一，而不是通过value_ratio在状态层级去解决

无法通过这个方法实现吗？

**Comment by al-one** [comment]
> 1. 在属性层级就实现单位(小数点)的统一，而不是通过value_ratio在状态层级去解决

目前主实体属性值均来自设备或者云端未经更改，如果改变了，可能导致其他用户的显示或者自动化出问题。

如果想格式化实体属性值，可以使用`attributes_template`：
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    chuangmi.plug.212a01:
      attributes_template: |-
        {{ {
          'electric_power-5-6': (data['electric_power-5-6'] | default(0)) / 1000,
        } }}
```
