### ISSUE TITLE
Enhancement: any possibility of making device offline persistent notification configurable per device?

### ISSUE THREAD

**Issue by pplucky** [al-one/hass-xiaomi-miot#574]
Hello.

Since I upgraded to latest version (0.6.2), every time I restart my HA, I get a persistent notification letting me know that one of my devices is offline.
![image](https://user-images.githubusercontent.com/16407309/167257219-cee6711a-dd59-445b-b748-a63376e557a9.png)

I looked at this repo to find out it was recently added by this [commit](https://github.com/al-one/hass-xiaomi-miot/commit/09041326e40f3b39675ea03610c2def8230bc280).

While I find this notification useful for specific devices, I don't for others (for instance, my Air Fryer is only connected to Wifi when it is actually turned on, which for sure only happens when it is going to be used for cooking). Hence, it is normal that it will be offline most of the times once I restart HA, but that's not necessarily an issue.

Would it be possible to keep this enhancement but allow it to be controlled from a global and/or device-dependent setting?

Thanks in advance.

**Comment by al-one** [comment]
Added in https://github.com/al-one/hass-xiaomi-miot/commit/5bad3800d120e36bff2cef4ea2f85d2a5a35fb20:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    careli.fryer.maf02:
      ignore_offline: true
```

**Comment by pplucky** [comment]
So this means that functionality is active by default, unless this setting is true for the specific device, and in that cade is inactive for that device only, is that it?

**Comment by al-one** [comment]
Yes, all locally connected devices are enabled by default. You can also disable it via wildcards:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    'careli.fryer.*':
      ignore_offline: true
    '*.fryer.*':
      ignore_offline: true
```
