### ISSUE TITLE
ZigBee smart plugs (identified as lumi.plug.v1) not showing Power & Consumption entities

### ISSUE THREAD

**Issue by barnabyjones** [al-one/hass-xiaomi-miot#58]
My ZigBee smart plugs not showing Power & Consumption entities via the miot integration, however they show these via the "Xiaomi Gateway 3" integration. 

A difference that I can see is that the miot integration identifies the plugs as lumi.plug.v1, where as the  "Xiaomi Gateway 3" integration identifies the plugs as lumi.plug ZNCZ02LM.

**Comment by al-one** [comment]
Power & Consumption not found in [miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:outlet:0000A002:lumi-v1:1) for `lumi.plug.v1`.

**Comment by barnabyjones** [comment]
Is there another lumi plug in the spec that does include those attributes by any chance? Just wondering if it is possible that the plug was incorrectly identified as lumi.plug.v1 instead of another model.

**Comment by barnabyjones** [comment]
I'm not sure if this helps, but zibee2mqtt has a power attribute for the lumi ZNCZ02LM smart socket. 

[](https://www.zigbee2mqtt.io/devices/ZNCZ02LM.html)

> Power (numeric) #
> Instantaneous measured power. Value can be found in the published state on the power property. To read (/get) the value publish a message to topic zigbee2mqtt/FRIENDLY_NAME/get with payload {"power": ""}. It’s not possible to write (/set) this value. The unit of this value is W.
> 
> Energy (numeric) #
> Sum of consumed energy. Value can be found in the published state on the energy property. It’s not possible to read (/get) or write (/set) this value. The unit of this value is kWh.

```
sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.power }}"
    unit_of_measurement: "W"
    device_class: "power"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.energy }}"
    unit_of_measurement: "kWh"
    device_class: "energy"
```
