### ISSUE TITLE
米家直流变频风扇1x token接入无法控制

### ISSUE THREAD

**Issue by hanley520** [al-one/hass-xiaomi-miot#580]
[`dmaker.fan.p5`](https://home.miot-spec.com/s/dmaker.fan.p5) 开发者状态：
```yaml
preset_modes:
  - 自然风
  - 直吹风
friendly_name: Xiaomi Miot Fan
supported_features: 11
percentage_step: 25
model: dmaker.fan.p5
lan_ip: 192.168.10.36
mac_address: 40:31:3C:xx:xx:xx
entity_class: MiotFanEntity
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p5:1
fan.on.error: '-4004 Other internal errors'
fan.horizontal_swing.error: '-4004 Other internal errors'
fan.mode.error: '-4004 Other internal errors'
fan.fan_level.error: '-4004 Other internal errors'
alarm.error: '-4004 Other internal errors'
indicator_light.on.error: '-4004 Other internal errors'
physical_controls_locked.error: '-4004 Other internal errors'
state_updater: lan
sub_entities:
  - physical_controls_locked-3.physical_controls_locked-1
```
Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1269
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 21:28:01 (2 occurrences)
Last logged: 21:28:13

Xiaomi Miot(dmaker.fan.p5): Got MiioException while fetching the state: {'code': -30012, 'message': 'busy.'}, mapping: {'fan.on': {'siid': 2, 'piid': 1}, 'fan.horizontal_swing': {'siid': 2, 'piid': 2}, 'fan.mode': {'siid': 2, 'piid': 3}, 'fan.fan_level': {'siid': 2, 'piid': 4}, 'alarm': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'physical_controls_locked': {'siid': 3, 'piid': 1}}, max_properties: 9/7
Xiaomi Miot(dmaker.fan.p5): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'fan.on': {'siid': 2, 'piid': 1}, 'fan.horizontal_swing': {'siid': 2, 'piid': 2}, 'fan.mode': {'siid': 2, 'piid': 3}, 'fan.fan_level': {'siid': 2, 'piid': 4}, 'alarm': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'physical_controls_locked': {'siid': 3, 'piid': 1}}, max_properties: 9/7
