### ISSUE TITLE
青萍空气检测仪只能获取到整数值温湿度数据

### ISSUE THREAD

**Issue by ChristianSwift** [al-one/hass-xiaomi-miot#591]
设备型号：[cgllc.airmonitor.s1](https://home.miot-spec.com/s/cgllc.airmonitor.s1)
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/20925565/168609729-1ad6eb97-4b3f-4c56-a13e-ae8126f2e0af.png">
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/20925565/168609847-6656f7b9-8f8e-4767-9893-09671f699c64.png">
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/20925565/168609908-34af6ade-8e9d-4807-b560-13752d34ec48.png">

**Comment by al-one** [comment]
请通过开发者工具执行下面的[服务](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)，并检查HA侧边栏通知：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.cgllc_s1_xxxx_temperature # 换成你的实体ID
  method: get_value
  params:
    - aqi
    - pm25
    - co2
    - tvoc
    - humidity
    - temperature
    - tvoc_unit
    - temperature_unit
    - battery
    - battery_state
  throw: true
```
