### ISSUE TITLE
米家智能驱蚊器2 不显示剩余使用时间等属性

### ISSUE THREAD

**Issue by dofine** [al-one/hass-xiaomi-miot#593]
https://home.miot-spec.com/spec/zimi.mosq.v2

![CleanShot 2022-05-18 at 12 32 08@2x](https://user-images.githubusercontent.com/440101/169039347-a55d5bd2-b222-4bcb-8eec-9a8988f4add6.png)

**Comment by dofine** [comment]
> 请提供开发者工具中的[实体属性](https://my.home-assistant.io/redirect/developer_states)。

```
model: zimi.mosq.v2
lan_ip: 123.119.237.150
mac_address: 5C:E5:0C:98:DF:9F
entity_class: MiotSwitchEntity
home_room: 我的家 卧室
miot_type: urn:miot-spec-v2:device:mosquito-dispeller:0000A065:zimi-v2:2:0000C81C
mosquito_dispeller.on: false
mosquito_dispeller.mode: 2
light_indicator.on: true
light_indicator.start_time: 60
light_indicator.end_time: 0
enter_app.error: -704030013 Property is not readable
user_timer.set_timer: 276792575
user_timer.timestamp: 1652877122
user_timer.del_mult_timer.error: -704030013 Property is not readable
battery_level: 97
repellent.repellent_left_level: 8
state_updater: cloud
sub_entities: battery-3.battery_level-1
device_class: switch
friendly_name: 米家智能驱蚊器2 mosquito_dispeller
supported_features: 0
```

**Comment by al-one** [comment]
上面的实体属性已包含全部属性。

**Comment by dofine** [comment]
不好意思可能之前我表达错误，问题是不显示剩余使用时间等属性的值。比如 

```yaml
service: xiaomi_miot.get_properties
data:
  entity_id: switch.zimi_v2_df9f_mosquito_dispeller
  throw: true
  mapping:
    mode:
      siid: 2
      piid: 3
    on:
      siid: 2
      piid: 1
    battery-level:
      siid: 3
      piid: 1
    repellent-left-level:
      siid: 4
      piid: 1
```

是能够知道当前状态（电池供电/c口供电）、电池剩余电量、驱蚊片剩余使用时间的 

```json
[{'did': 'mode', 'siid': 2, 'piid': 3, 'code': -704040003, 'exe_time': 0}, {'did': 'on', 'siid': 2, 'piid': 1, 'value': False, 'code': 0, 'updateTime': 1652996283, 'exe_time': 0}, {'did': 'battery-level', 'siid': 3, 'piid': 1, 'value': 97, 'code': 0, 'updateTime': 1652784872, 'exe_time': 0}, {'did': 'repellent-left-level', 'siid': 4, 'piid': 1, 'value': 10, 'code': 0, 'updateTime': 1652996811, 'exe_time': 0}]
```
