### ISSUE TITLE
宠物喂食机不可用

### ISSUE THREAD

**Issue by ChristianSwift** [al-one/hass-xiaomi-miot#596]
已更新到master版本  
<img width="1228" alt="QQ20220519-221125@2x" src="https://user-images.githubusercontent.com/20925565/169314469-133ee504-5497-4f96-aef4-09d3b4074f47.png">
<img width="1521" alt="QQ20220519-221143@2x" src="https://user-images.githubusercontent.com/20925565/169314499-9f4469ff-55bc-4f50-8d97-78383c60332d.png">

**Comment by ChristianSwift** [comment]
日志：  
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/20925565/169314969-7fa302dc-9438-48d3-b6a6-11d5557bd5c0.png">
尝试调用Action亦不可用  
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/20925565/169315177-b5d0f44e-ca68-4c5f-973c-6cfc03686317.png">

**Comment by ChristianSwift** [comment]
确认了云端模式和本地模式都不可用

**Comment by ChristianSwift** [comment]
> 请再次更新至master分支。

感谢，刚刚尝试了新版本，还有三个疑问：  

1. 能否加入一个和Reset_desiccant_life类似的button实体用于[pet-food-out](https://miot-spec.org/miot-spec-v2/spec/action?type=urn:miot-spec-v2:action:pet-food-out:0000282B) Action，当前版本下还是需要添加辅助元素并在nodered中调用command的操作方法感觉还是有些不便    
2. Pet Feeder Feeding Measure实体依旧是不可用状态，请问该实体是用于何种用途？
3. 经测试Physical_controls_locked实体的状态值好像反了，以我理解该实体打开为童锁打开，此时是无法按实体按键的，然而当前的状态是打开后可以使用设备实体按键，关闭后无法使用  
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/20925565/169541090-810e8f42-6cf1-4daa-81bd-a2bb39bceac9.png">
最后再次感谢作者的辛勤劳动和不吝回复！

**Comment by al-one** [comment]
请再次更新至master分支。

> 1. 能否加入一个和Reset_desiccant_life类似的button实体用于`pet-food-out` Action，当前版本下还是需要添加辅助元素并在nodered中调用command的操作方法感觉还是有些不便
> 2. Pet Feeder Feeding Measure实体依旧是不可用状态，请问该实体是用于何种用途？

`pet-food-out` Action 由于需要一个喂食量参数，因此不适合使用按钮实体，Pet Feeder Feeding Measure实体可以通过自定义属性`feeding_measure`来指定喂食量

> 3. 经测试Physical_controls_locked实体的状态值好像反了，以我理解该实体打开为童锁打开，此时是无法按实体按键的，然而当前的状态是打开后可以使用设备实体按键，关闭后无法使用

已修复。

**Comment by ChristianSwift** [comment]
> 请再次更新至master分支。
> 
> > 1. 能否加入一个和Reset_desiccant_life类似的button实体用于`pet-food-out` Action，当前版本下还是需要添加辅助元素并在nodered中调用command的操作方法感觉还是有些不便
> > 2. Pet Feeder Feeding Measure实体依旧是不可用状态，请问该实体是用于何种用途？
> 
> `pet-food-out` Action 由于需要一个喂食量参数，因此不适合使用按钮实体，Pet Feeder Feeding Measure实体可以通过自定义属性`feeding_measure`来指定喂食量
> 
> > 3. 经测试Physical_controls_locked实体的状态值好像反了，以我理解该实体打开为童锁打开，此时是无法按实体按键的，然而当前的状态是打开后可以使用设备实体按键，关闭后无法使用
> 
> 已修复。

理解了，建议后续是否可以加入一个number实体用于控制喂食量参数，类似WLED集成中的滑块  
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/20925565/169551152-33c1b8a2-a964-4cd8-bf95-b8136bea3eec.png">

**Comment by Wh1terat** [comment]
@ChristianSwift 

Script:
```yaml
mode: queued
alias: '[PetFeeder] - Dispense Food'
description: Dispenses food from the feeder
icon: mdi:bowl-mix
fields:
  entity_id:
    description: ID of the PetFeeder
    required: true
    example: sensor.mmgg_petfeeder_bf89_pet_feeder
    selector:
      entity:
        integration: xiaomi_miot
        domain: sensor
  units:
    name: units
    description: Number of units to dispense
    required: false
    default: 1
    example: '1'
    selector:
      number:
        min: 1
        max: 30
        step: 1
        unit_of_measurement: units(s)
        mode: slider
  units_id:
    name: units_id
    description: ID for input_number holding portion value
    example: input_number.mmgg_petfeeder_bf89_feed_amount
    required: false
    selector:
      entity:
        domain: input_number
sequence:
  - service: xiaomi_miot.send_command
    data_template:
      entity_id: '{{ entity_id }}'
      method: outfood
      params:
        - '{{ expand(units_id)[0].state | int(0) }}'
max: 10
```

Add helper:
<img width="493" alt="Screenshot 2022-05-21 at 22 58 34" src="https://user-images.githubusercontent.com/1288525/169670303-82bccd5a-e6c7-4e07-9c34-e1bd690c9388.png">

Add script call button:
<img width="681" alt="Screenshot 2022-05-21 at 22 59 35" src="https://user-images.githubusercontent.com/1288525/169670308-23cd01d5-3c43-4dba-8e77-51a690d867e9.png">

Click number helper:
<img width="408" alt="Screenshot 2022-05-21 at 22 59 05" src="https://user-images.githubusercontent.com/1288525/169670316-150ed8e1-9d9b-46ea-a280-9e8b0ec23af8.png">

Set amount:
<img width="330" alt="Screenshot 2022-05-21 at 22 58 54" src="https://user-images.githubusercontent.com/1288525/169670326-f6902550-4549-49df-ac57-d297ebad7714.png">
