### ISSUE TITLE
Please add option to call_action, -  simple "in"

### ISSUE THREAD

**Issue by dmitriytim** [al-one/hass-xiaomi-miot#618]
I want to execute a command:
```
raw_command  action '{"did":"1027278185","siid":4,"aiid":1,"in":[{"piid":1,"value":18},{"piid":10,"value":"{\"selects\":[[1,1,0,3,1]]}"}]}'
Running command raw_command
{'did': '1027278185', 'siid': 4, 'aiid': 1, 'out': [], 'code': 0}
```
but the plugin replaces, cuts, comments.
could not suggest what could be wrong.
Might be worth adding the "in" option

/usr/share/hassio/homeassistant/automations.yam
 ->
```
- id: '1653679406832'
  alias: уборка кухни
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.uborka_kukhni
  condition: []
  action:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.dreame_p2140p_c40d_robot_cleaner
      siid: 4
      aiid: 1
      params:
      - 18
      - '{"selects":[[1,1,0,3,1]]}'
  mode: single
```
tail -f home-assistant.log 
->
`2022-05-28 07:24:21 INFO (SyncWorker_2) [custom_components.xiaomi_miot.vacuum] Пылесос(dreame.vacuum.p2140p): Call miot action {'did': 'action-4-1', 'siid': 4, 'aiid': 1, 'in': [{'piid': 10, 'value': 18}]} failed: {'did': 'action-4-1', 'siid': 4, 'aiid': 1, 'out': [], 'code': -1}`

**Comment by al-one** [comment]
Call action with `force_params`:
```yaml
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.dreame_p2140p_c40d_robot_cleaner
      siid: 4
      aiid: 1
      params:
      - piid: 1
        value: 18
      - piid: 10
        value: '{"selects":[[1,1,0,3,1]]}'
      force_params: true
```

- https://github.com/al-one/hass-xiaomi-miot/issues/491#issuecomment-1100708607
