### ISSUE TITLE
小米冰箱610升

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#633]
Logger: custom_components.xiaomi_miot.sensor
Source: custom_components/xiaomi_miot/__init__.py:1298
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 16:42:46 (104 occurrences)
Last logged: 18:47:33

冰箱(midjd6.fridge.610): Got MiioException while fetching the state: Unable to discover the device 192.168.198.54, mapping: {'fridge_chamber-4.temperature': {'siid': 4, 'piid': 1}, 'target_temperature-4-2': {'siid': 4, 'piid': 2}, 'data.temperature': {'siid': 6, 'piid': 1}, 'data.compressor': {'siid': 6, 'piid': 2}, 'fault.fault_openeven': {'siid': 5, 'piid': 1}, 'fault.fault_dr': {'siid': 5, 'piid': 2}, 'fridge.fault': {'siid': 2, 'piid': 1}, 'fridge.mode': {'siid': 2, 'piid': 2}}, max_properties: 9/8
冰箱(midjd6.fridge.610): Got MiioException while fetching the state: Unable to discover the device 192.168.198.54, mapping: {'fridge_chamber.temperature': {'siid': 3, 'piid': 1}, 'target_temperature-3-2': {'siid': 3, 'piid': 2}, 'data.temperature': {'siid': 6, 'piid': 1}, 'data.compressor': {'siid': 6, 'piid': 2}, 'fault.fault_openeven': {'siid': 5, 'piid': 1}, 'fault.fault_dr': {'siid': 5, 'piid': 2}, 'fridge.fault': {'siid': 2, 'piid': 1}, 'fridge.mode': {'siid': 2, 'piid': 2}}, max_properties: 9/8

**Comment by al-one** [comment]
貌似连不上该设备。请通过以下服务命令测试：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.midjd6_610_xxxx # 你的冰箱实体ID
  method: miIO.info
  params: []
  throw: true
```
如果HA通知中出现了设备的miio信息，请再通过下面命令测试过去miot属性：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.midjd6_610_xxxx # 你的冰箱实体ID
  method: get_properties
  params:
    - did: miot
      siid: 2
      piid: 1
    - did: miot
      siid: 2
      piid: 2
  throw: true
```
