### ISSUE TITLE
apostrophes in passed variable for xiaomi_miot.call_action service

### ISSUE THREAD

**Issue by kodifan** [al-one/hass-xiaomi-miot#636]
Dear Alone
I ve got similar problem that user [antoweb](https://github.com/antoweb) in the thread:
How to launch cleaning specific room #506
And basically simply code works:
```service: xiaomi_miot.call_action
  data:
  entity_id: vacuum.viomi_v19_e351_robot_cleaner
    siid: 4
    aiid: 13
    params:
      - 0
      - 1
      - '14'
 ```
    
as stated in your comment https://github.com/al-one/hass-xiaomi-miot/issues/506#issuecomment-1094507504 room id is in apostrophes. Without those apostrophes script calls global cleaning not particular room.

My problem is that im passing this room id value as a variable from other place (popup to choose room from the list).
My script thar this popup calls looks like this:
```
vacuum_room_popuop:
  alias: Vacuum - Clean Room
  sequence:
    - service: xiaomi_miot.call_action
      data:
        entity_id: vacuum.viomi_v19_e351_robot_cleaner
        siid: 4
        aiid: 13
        params:
          - 0
          - 1
          - '{{ room }}'
``` 
And no mater what i put i the room id filed it does not work. Adding apostrophes to popup configuration also does not work.
``2022-06-06 19:31:51 DEBUG (MainThread) [custom_components.xiaomi_miot] Xiaomi Miot service handler: {'targets': ['vacuum.viomi_v19_e351_robot_cleaner'], 'method': 'async_miot_action', 'params': {'siid': 4, 'aiid': 13, 'params': [0, 1, 14], 'throw': False, 'force_params': False}}
``
Either apostrophes are missing from the logs or are added to many times when combined with quotation mark.

So how to pass those damn apostrophes to xiaomi_miot.call_action service from variable :)

**Comment by al-one** [comment]
```yaml
vacuum_room_popuop:
  alias: Vacuum - Clean Room
  sequence:
    - service: xiaomi_miot.call_action
      data:
        entity_id: vacuum.viomi_v19_e351_robot_cleaner
        siid: 4
        aiid: 13
        params: |-
          {{ [0, 1, room | string] }}
```
