### ISSUE TITLE
小米米家智能墙壁插座(ble)能否调节数据更新频率

### ISSUE THREAD

**Issue by maxmib** [al-one/hass-xiaomi-miot#665]
型号[zimi.plug.zncz01](https://home.miot-spec.com/s/zimi.plug.zncz01)
接入Hass后，设置了enable power upload ，貌似是一分钟更新一次插座功率数据，能否提高数据更新频率

**Comment by al-one** [comment]
在近期的提交(https://github.com/al-one/hass-xiaomi-miot/commit/f6b53cd44271b999d945a2c307e8af933cd06441#commitcomment-77167713 )中，本插件支持通过服务更新单个或指定的多个属性，因此可以通过自动化去主动更新指定属性。
```yaml
alias: Update the outlet power every 10s
mode: single
trigger:
  - platform: time_pattern
    seconds: /10
action:
  - service: xiaomi_miot.get_properties
    data:
      entity_id: switch.zimi_zncz01_entity_id
      mapping:
        - siid: 3
          piid: 1
      update_entity: true
      throw: false
```
> 请更新到master分支或等待下个发行版。

**Comment by maxmib** [comment]
> 在近期的提交([f6b53cd#commitcomment-77167713](https://github.com/al-one/hass-xiaomi-miot/commit/f6b53cd44271b999d945a2c307e8af933cd06441#commitcomment-77167713) )中，本插件支持通过服务更新单个或指定的多个属性，因此可以通过自动化去主动更新指定属性。
> 
> ```yaml
> alias: Update the outlet power every 10s
> mode: single
> trigger:
>   - platform: time_pattern
>     seconds: /10
> action:
>   - service: xiaomi_miot.get_properties
>     data:
>       entity_id: switch.zimi_zncz01_entity_id
>       mapping:
>         - siid: 3
>           piid: 1
>       update_entity: true
>       throw: false
> ```
> 
> > 请更新到master分支或等待下个发行版。


目前使用v0.7.1版插件，这个方法无效

**Comment by al-one** [comment]
该设备不会主动更新功率，请尝试：
```yaml
alias: Update the outlet power every 20s
mode: single
trigger:
  - platform: time_pattern
    seconds: /20
action:
  - service: xiaomi_miot.set_property
    data:
      entity_id: switch.zimi_zncz01_entity_id
      field: enable_upload_power
      value: 0 # 关闭
  - service: xiaomi_miot.set_property
    data:
      entity_id: switch.zimi_zncz01_entity_id
      field: enable_upload_power
      value: 1 # 开启
  - service: xiaomi_miot.get_properties
    data:
      entity_id: switch.zimi_zncz01_entity_id
      mapping:
        - siid: 3
          piid: 1
      update_entity: true
```
