### ISSUE TITLE
美的酷金空调（midea.aircondition.xa1）接入后显示不可用，请问该怎么解决

### ISSUE THREAD

**Issue by Wan2fly** [al-one/hass-xiaomi-miot#667]
<img width="751" alt="Snipaste_2022-06-22_10-55-11" src="https://user-images.githubusercontent.com/76058703/174933778-fd44a350-fb34-4937-82b4-2b5bf62dd8e1.png">
<img width="365" alt="Snipaste_2022-06-22_10-54-20" src="https://user-images.githubusercontent.com/76058703/174933796-ddee164f-e1e1-4cc0-8690-69c4eb753eb1.png">

**Comment by al-one** [comment]
请尝试执行以下服务，并检查HA通知：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.midea_xa1_411d_air_conditioner
  method: get_prop
  params: [power, mode, temp]
  throw: true
```
