### ISSUE TITLE
插件可以看到青萍空气检测仪，勾选后实体中不出现

### ISSUE THREAD

**Issue by googooog** [al-one/hass-xiaomi-miot#68]
如题，插件可以看到 cgllc.airmonitor.s1 但是勾选后插件中的设备数量没有增加，

实体里面找不到青萍空气检测仪。

**Comment by al-one** [comment]
请确保该设备所属的WiFi SSID/BSSID被`Include(包含)`或者未被`Exclude(排除)`，如不清楚如何配置，请将WiFi SSID/BSSID切换为`Include(排除)`并清空对应的所有勾选项。

**Comment by googooog** [comment]
大佬，我已经将WiFi SSID/BSSID切换为Include(排除)并清空对应的所有勾选项，但是依旧没有cgllc.airmonitor.s1 的实体。

**Comment by zhhp33** [comment]
和你遇到一样的问题

**Comment by al-one** [comment]
请更新master分支后再试下。

**Comment by zhhp33** [comment]
感谢大佬！新版识别到了，不过在HK里不显示PM2.5和tVOC指数

**Comment by zhhp33** [comment]
> 请更新master分支后再试下。



> 请更新master分支后再试下。

感谢大佬！新版识别到了，不过在HK里不显示PM2.5和tVOC指数

**Comment by zhhp33** [comment]
> 请更新master分支后再试下。

感谢大佬！新版识别到了，不过在HK里不显示PM2.5和tVOC指数

**Comment by al-one** [comment]
最新版可以通过自定义属性添加子实体：
> [⚙️ 配置](https://my.home-assistant.io/redirect/config) > 🖌 自定义 > 🔍 选择实体 > 选择要覆盖的属性 > 添加Other属性
```yaml
# customize.yaml
air_quality.parent_entity_id:
  sensor_properties: pm2_5_density,tvoc_density
```
