### ISSUE TITLE
Wrong vacuum status after last update

### ISSUE THREAD

**Issue by fewdji** [al-one/hass-xiaomi-miot#683]
After last update when my [Dreame D9](https://home.miot-spec.com/s/dreame.vacuum.p2009) is charging on the base - HA status is “waiting” instead of on charging or on the base. 
Fix please. It was good on prev version.
Works in local mode.

**Comment by al-one** [comment]
Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states) when it is `waiting`.

**Comment by fewdji** [comment]
> Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states) when it is `waiting`.

fan_speed_list:
  - Silent
  - Standard
  - Strong
  - Turbo
battery_level: 100
battery_icon: mdi:battery
fan_speed: Turbo
model: dreame.vacuum.p2009
lan_ip: 192.168.1.90
mac_address: D4:D2:*
entity_class: MiotVacuumEntity
exclude_miot_services:
  - consumable
  - annoy
  - remote
  - time
exclude_miot_properties:
  - delete_timer
  - clean_info
  - map_view
  - frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2009:2
vacuum.status: 2
vacuum.fault: 0
vacuum.mode: 3
clean_logs.first_clean_time: 1646907252
clean_logs.total_clean_time: 1501
clean_logs.total_clean_times: 115
clean_logs.total_clean_area: 1440
audio.volume: 100
audio.voice_packet_id: MM0
audio.voice_change_state: '{\"id\":\"\",\"state\":\"idle\",\"progress\":0}'
audio.set_voice.error: '-1'
map.map_extend_data.error: '-1'
map.mult_map_state: 0
map.mult_map_info: >-
  {"object_name":"4150955293//9","md5":"*"}
do_not_disturb.enable: false
do_not_disturb.start_time: '22:00'
do_not_disturb.end_time: '08:00'
vacuum_extend.work_mode: 14
vacuum_extend.cleaning_time: 9
vacuum_extend.cleaning_area: 7
vacuum_extend.cleaning_mode: 3
vacuum_extend.mop_mode: 3
vacuum_extend.waterbox_status: 0
vacuum_extend.task_status: 0
vacuum_extend.clean_extend_data.error: '-1'
break_point_restart-4-11: 1
vacuum_extend.carpet_press: 1
vacuum_extend.serial_number: P2009*
vacuum_extend.remote_state.error: '-1'
vacuum_extend.clean_rags_tip: 0
vacuum_extend.keep_sweeper_time: 0
vacuum_extend.faults: ''
vacuum_extend.nation_matched: unknown
vacuum_extend.relocation_status: 0
filter.filter_life_level: 28
filter.filter_left_time: 42
brush_left_time-10-1: 92
brush_life_level-10-2: 46
brush_cleaner.brush_left_time: 192
brush_cleaner.brush_life_level: 64
battery.charging_state: 1
state_updater: lan
vacuum.status_desc: 空闲
sub_entities:
  - vacuum-2.status-1
  - filter-11.filter_life_level-1
  - filter-11.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-9.brush_left_time-1
  - brush_cleaner-9.brush_life_level-2
  - brush_cleaner-10.brush_left_time-1
  - brush_cleaner-10.brush_life_level-2
miot_action_result:
  did: action-7-1
  siid: 7
  aiid: 1
  out: []
  code: 0
friendly_name: Пылесос
supported_features: 13048
icon: mdi:robot-vacuum

**Comment by al-one** [comment]
```yaml
vacuum.status: 2  # Idle
```

```javascript
{
    "iid":1,
    "type":"urn:miot-spec-v2:property:status:00000007:dreame-p2009:1",
    "description":"Status",
    "format":"uint8",
    "access":["read", "notify"],
    "unit":"none",
    "value-list":[
        {"value":1, "description":"Sweeping"},
        {"value":2, "description":"Idle"},
        {"value":3, "description":"Paused"},
        {"value":4, "description":"Error"},
        {"value":5, "description":"Go Charging"},
        {"value":6, "description":"Charging"},
        {"value":7, "description":"Mopping"}
    ]
}
```

Looks ok.

**Comment by fewdji** [comment]
There is no “docked” status.

**Comment by fewdji** [comment]
Could you replace:
`{"value":2, "description":"Idle"},`
to
`{"value":2, "description":"Docked"},`

This is correct status desc for dreame-p2009

**Comment by al-one** [comment]
Try:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    dreame.vacuum.p2009:
      extend_miot_specs:
        - iid: 2
          properties:
            iid: 1
            value-list:
              - value: 1
                description: Sweeping
              - value: 2
                description: Docked
              - value: 3
                description: Paused
              - value: 4
                description: Error
              - value: 5
                description: Go Charging
              - value: 6
                description: Charging
              - value: 7
                description: Mopping
```
