### ISSUE TITLE
Option to turn off "show devices offline"

### ISSUE THREAD

**Issue by TheLordVader** [al-one/hass-xiaomi-miot#705]
Is it possible to turn off the notification in HA when a device goes offline? Otherwise I would suggest having some option to turn this notification off. I have some fans that occasionally drops wi-fi and it always triggers a notification in home assistant.

Thanks, I really love your work! 👍

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/574#issuecomment-1121955107

```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    'careli.fryer.*':
      ignore_offline: true
    '*.fryer.*':
      ignore_offline: true
```
