### ISSUE TITLE
[question]请问大大，接入的小爱同学如何调用tts语音

### ISSUE THREAD

**Issue by cyicz123** [al-one/hass-xiaomi-miot#71]
[question]
请问大大，接入的小爱同学如何调用tts语音。我尝试用"开发者工具"->“服务”->“Xiaomi Miot Auto: intelligent_speaker”
~~~ yaml
service: xiaomi_miot.intelligent_speaker
data: 
    message: “你好，我是雷军同学”
  
~~~
并不能实现。

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.your_xiaoai_entity_id
  text: 开客厅灯
  execute: true
  slient: false
```
