### ISSUE TITLE
小米新风空调homekit无法调节风速

### ISSUE THREAD

**Issue by NicholasMing** [al-one/hass-xiaomi-miot#713]
xiaomi.aircondition.c24
xiaomi.aircondition.c17

接入homekit后只能调整温度和制暖制冷

**Comment by al-one** [comment]
在你的HA配置文件中将空调的风速模式翻译成`low`/`middle`/`high`即可在HK中控制空调风速。
```yaml
# configuration.yaml
xiaomi_miot:
  language: zh
  translations:
    fan_control.fan_level:
      level1: low
      level3: middle
      level5: medium
      level7: high
```
