### ISSUE TITLE
zhimi.heater.na1 additional features as entities?

### ISSUE THREAD

**Issue by blakadder** [al-one/hass-xiaomi-miot#74]
I have the zhimi.heater.na1 running with your excellent custom component.

It does have all the available features as listed by https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:zhimi-na1:1 extracted as entity states 

Is there currently a way inside the custom component to add control of:

indicator light:
```json
{
"iid":6,
"type":"urn:miot-spec-v2:service:indicator-light:00007803:zhimi-na1:1",
"description":"Indicator Light",
"properties":[
{
"iid":1,
"type":"urn:miot-spec-v2:property:brightness:0000000D:zhimi-na1:1",
"description":"Brightness",
"format":"uint8",
"access":[
"read",
"write",
"notify"
],
"value-range":[
0,
2,
1
]}]},
```

return to middle toggle:
```json
{
"iid":3,
"type":"urn:zhimi-spec:property:return-to-middle:00000003:zhimi-na1:1",
"description":"",
"format":"bool",
"access":[
"read",
"notify",
"write"
],
"unit":"none"
}
```

Another question while here :
Can you explain in a bit more detail how to use 
```yaml
climate.your_entity_id:
  bind_sensor: sensor.temperature_entity,sensor.humidity_entity # Sensor entities
```

I'll gladly add the expanded explanation the docs once you help me figure it out

**Comment by al-one** [comment]
Indicator is supported, please check whether there is light entity under the same HA device.

**Comment by al-one** [comment]
But the indicator light of you device have no power: `on` property, So no indicator entities are generated.

If you use it in automation, You can toggle it in HA service:
```yaml
# indicator light:
service: xiaomi_miot.set_miot_property
data:
  entity_id: climate.your_entity_id
  siid: 6
  piid: 1
  value: 2

# return to middle:
service: xiaomi_miot.set_miot_property
data:
  entity_id: climate.your_entity_id
  siid: 8
  piid: 3
  value: true
```

**Comment by al-one** [comment]
`bind_sensor` can bind a temperature / humidity sensor to the current climate entity.
[Customization Using The UI](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) is recommended:
> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > 🖌 Customize > 🔍 Select Entity > Add Other Attribute
> Attribute name: bind_sensor
> Attribute value: sensor.your_temperature_entity_id

**Comment by blakadder** [comment]
Ah ok, I was expecting it to have some logic for controlling heating modes when a external temperature sensor is defined, similar to a generic thermostat or MQTT thermostat. Currently, having a bound temperature sensor doesn't really achieve much.

As for the indicator and other functions I had to create template entities for almost every feature including the heater entity itself. Only the Child Lock function works as intended.

Here's the yaml if someone else ends up with the same problem:

switches
```yaml
- platform: template
  switches:
    smartmi_return_to_middle:
      friendly_name: "Smartmi Fan Centering"
      value_template: "{{ is_state_attr('climate.bathroom_heater','return_to_middle', true) }}"
      turn_on:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 8
          piid: 3
          value: true
      turn_off:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 8
          piid: 3
          value: false
      icon_template: >-
        {% if is_state_attr('climate.bathroom_heater','return_to_middle', true) %}
          mdi:format-horizontal-align-center
        {% else %}
          mdi:format-rotate-90
        {% endif %}
    smartmi_sound:
      friendly_name: "Smartmi Sound"
      value_template: "{{ is_state_attr('climate.bathroom_heater','alarm', true) }}"
      turn_on:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 3
          piid: 1
          value: true
      turn_off:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 3
          piid: 1
          value: false
      icon_template: >-
        {% if is_state_attr('climate.bathroom_heater','alarm', true) %}
          mdi:music-note-eighth
        {% else %}
          mdi:music-note-off
        {% endif %}     
```

lights
```yaml
- platform: template
  lights:
    smartmi_indicator:
      friendly_name: "Smartmi LED Indicator"
      unique_id: smartmi_indicator
      value_template: "{{ is_state_attr('climate.bathroom_heater', 'indicator_light.brightness', 0) or is_state_attr('climate.bathroom_heater', 'indicator_light.brightness', 1) }}"
      turn_on:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 6
          piid: 1
          value: 0
      turn_off:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 6
          piid: 1
          value: 2
      level_template: >-
          {% if is_state_attr('climate.bathroom_heater', 'indicator_light.brightness', 0) %}
            255
          {% elif is_state_attr('climate.bathroom_heater', 'indicator_light.brightness', 1) %}
            126
          {% else %}
            0 
          {% endif %}
      set_level:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 6
          piid: 1
          value: "{{ 0 if brightness > 127 else 1 }}"
```

for generic thermostat I created a switch
```yaml
    smartmi_for_generic_thermostat:
      friendly_name: "Smartmi For Generic Thermostat"
      value_template: "{{ is_state_attr('climate.bathroom_heater','heater.on', true) }}"
      turn_on:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 2
          piid: 2
          value: true
      turn_off:
        service: xiaomi_miot.set_miot_property
        data:
          entity_id: climate.bathroom_heater
          siid: 2
          piid: 2
          value: false
```
Then I used it in a generic thermostat so HA turns off the heater once it reaches target temperature
climate
```yaml
  - platform: generic_thermostat
    unique_id: smartmigeneric
    name: "SmartMi Heater"
    heater: switch.smartmi_for_generic_thermostat
    target_sensor: sensor.bathroom_temperature_sensor
    min_temp: 18
    max_temp: 28
    ac_mode: false
    initial_hvac_mode: "heat"
```
