### ISSUE TITLE
pet feeder inland model

### ISSUE THREAD

**Issue by hahchu** [al-one/hass-xiaomi-miot#743]
I have [this model](https://home.miot-spec.com/s/mmgg.feeder.inland) of the pet feeder.
I can do this control: pet_feeder.pet_food_out
but no other information from sensor, like feed total or food status

How do I integrate the other functionalities?

-  'pet_food_left_level'
- 'feed_today'

**Comment by al-one** [comment]
Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by al-one** [comment]
Run this service as a [script](https://my.home-assistant.io/redirect/scripts) to put foods.
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: sensor.mmgg_inland_xxxx_pet_feeder
  siid: 2
  aiid: 1
  params:
    - 1 # feeding-measure
```
