### ISSUE TITLE
[功能建议]门锁增加operator_id的sensor。

### ISSUE THREAD

**Issue by befantasy** [al-one/hass-xiaomi-miot#750]
问题：
从Xiaomi MIoT RAW迁移过来的用户。使用的loock智能锁，在Xiaomi MIoT RAW中可以显示operator_id，这个sensor对于开门人员的识别很有意义，但是在本插件中并没有这个sensor，只有一个Lock Operation Method lock_key_id，还总变，没找到规律，很难做人员识别。

请求：
1、可否考虑增加operator_id的sensor。
2、对sensor的状态进行汉化。虽然问题不大，但很别扭。

图示：
以下是Xiaomi MIoT RAW中门锁的设备信息，有operator_id，且状态均为中文。
![image](https://user-images.githubusercontent.com/31535803/185524995-7ae80a3f-36f2-45fa-a08c-9e09f74abd8e.png)

以下是本插件中门锁的设备信息。
![image](https://user-images.githubusercontent.com/31535803/185525536-2eee67a5-5b93-4a83-a679-7570663845c1.png)

**Comment by al-one** [comment]
![image](https://user-images.githubusercontent.com/4549099/192186076-73818131-3da6-4052-8256-a84a8c17da6d.png)

本插件会生成一个`lock_key_id`实体，不知道它能否满足你的需求。

**Comment by befantasy** [comment]
> 

我之前试过这个lock_key_id。但是在我的loock门锁上，同一个指纹同一个开锁方式，这个id有时候会变，也没找出来变化规律。

**Comment by befantasy** [comment]
刚才又在插件里启用了门锁试了几次，同一个开锁方式lock_key_id没变，我再观察观察，看是不是之前家人有时候是用密码而不是指纹开的门，让我误以为lock_key_id是随机不固定的。

另外的那个问题，门锁实体属性的汉化和图标可否完善一下。实体名和图标到还可以自己手动改，但是属性就没办法了。
我刚才自己试了试，照葫芦画瓢在core/translation_languages.py里的_globals里加了行‘biological’: '指纹'，哈哈好像不行。
还请指教一下如何汉化，我试着自己改改提个PR，多谢啦~

**Comment by befantasy** [comment]
还有一个问题，门锁只有一个“Lock Operation Method timestamp”，好像是锁有任何状态变化就记录。

而大多门锁应该是会上报两个timestamp的，一个是door，一个是lock。比如我这个，https://home.miot-spec.com/spec/loock.lock.v8
区别是无论屋内屋外开锁，反锁，都会触发door的时间属性变化。
只有屋外开锁会触发lock的时间属性变化。

这个在实际使用中是有用处的，可以区分从外开门和从内开门的时间。

**Comment by befantasy** [comment]
这个问题的优先级是否可以提升一下，实体属性的汉化和图标已经困扰半年了。自己尝试汉化也没有成功。

**Comment by al-one** [comment]
门锁实体的本地化现已支持，请更新至master分支体验。需要通过下面的配置启用：
```yaml
# configuration.yaml
xiaomi_miot:
  language: zh
```
如果想自己调整译文：
```yaml
# configuration.yaml
xiaomi_miot:
  language: zh
  translations:
    door_state:
      open: 开门
      ...
    lock_method:
      bluetooth: 蓝牙
      ...
    lock_action:
      outside_unlock: 门外开锁
      ...
```
