### ISSUE TITLE
小米智能插座2 自动模式下功耗显示异常。

### ISSUE THREAD

**Issue by tom2201** [al-one/hass-xiaomi-miot#753]
chuangmi_212a01***_power_consumption
在自动模式下和手动模式下永久只显示0.1kwh 
![20220823135853](https://user-images.githubusercontent.com/97517069/186081470-8ea5fd1a-432c-4dc5-a767-63c1a7fb6ad0.png)
![20220823135919](https://user-images.githubusercontent.com/97517069/186081496-eed39826-3e71-4ba6-ac00-d68f696d27c7.png)
设置为云端模式数字会变动 但是显示的功耗数字是异常的。
![微信截图_20220823140123](https://user-images.githubusercontent.com/97517069/186081849-2da84eb6-8083-4737-acff-5e390c61280c.png)
![微信截图_20220823140203](https://user-images.githubusercontent.com/97517069/186081873-a37256d4-8556-40df-87be-139650ea9686.png)
![微信截图_20220823140305](https://user-images.githubusercontent.com/97517069/186082583-26535f2c-4bfe-4fd0-abc3-51e07749064c.png)

通过修改配置文件 添加device_customizes 可以使功率显示正常。但是功耗数字明显还是异常。
```yaml
xiaomi_miot:
  device_customizes:
    chuangmi.plug.212a01:electric_power:
      value_ratio: 1
```
现在主要是想将功耗统计到能源 统计功耗，现在功耗数值异常无法统计，这个是有办法解决吗?
