### ISSUE TITLE
chuangmi.camera.ipc019: not work streaming

### ISSUE THREAD

**Issue by MaximkaSH74** [al-one/hass-xiaomi-miot#761]
There is no video broadcast from the [chuangmi.camera.ipc019](https://home.miot-spec.com/s/chuangmi.camera.ipc019) camera.

![Screenshot_2022-08-29-18-03-12-715_io homeassistant companion android](https://user-images.githubusercontent.com/110081832/187207487-ddfd9e3a-1f16-44b2-b60c-fc63e27f13aa.jpg)

**Config of the customize.yaml file**:
```yaml
camera.chuangmi_ipc019_0400_camera_control:
  video_attribute: 1
  keep_streaming: true
```

**Camera Attributes:**
```yaml
access_token: {token}
model_name: chuangmi.camera.ipc019
brand: chuangmi
frontend_stream_type: hls
model: chuangmi.camera.ipc019
lan_ip: 192.168.0.3
mac_address: 64:90:C1:37:04:00
entity_class: MiotCameraEntity
home_room: Я Спальня
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc019:1
miot_action_result: 
did: '323815453'
miid: 0
siid: 4
aiid: 1
code: 0
out:
  - https://cn01.livestreaming.io.mi.com/hlstranscoder/GCA4ZTQ2{....link....}65transH264/playlist.m3u8
exe_time: 0
withLatency: 0

camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: false
glimmer_full_color-2-6: true
camera_control.recording_mode: 3
camera_control.motion_tracking: false
stream_status-3-1: 1
state_updater: cloud
miot_error: null
sub_entities: camera_control-2.on-1, motion_event
stream_http_status: 403
stream_http_reason: Forbidden
stream_address: https://cn02.livestreaming.io.mi.com/hlstranscoder/GCA0ZG{....link....}ransH264/playlist.m3u8
expire_at: 2022-08-29 17:31:28.004491
entity_picture: /api/camera_proxy/camera.chuangmi_ipc019_0400_camera_control?token={token}
friendly_name: Видеокамера Camera Control
supported_features: 3
video_attribute: 1
keep_streaming: true
```
I do not know how to execute the **ffmpeg** command. I have Raspberry pi 4b and Home assistant OS.
