### ISSUE TITLE
Gosund CP5Pro 插线板接入HA后耗电统计不更新

### ISSUE THREAD

**Issue by Jeremy-Merle** [al-one/hass-xiaomi-miot#763]
如题，在插线板未接入HA前其用电量统计能够更新，但是在接入HA后用电量统计不再增长，第二天统计量固定为0.01
- 插线板固件版本 2.1.8_0007&2.1.8_0005
- HA插件版本 v0.6.11

**Comment by Jeremy-Merle** [comment]
经过测试，在HA中禁用CP5Pro后，米家APP中电量统计可继续更新。

**Comment by al-one** [comment]
请尝试添加自定义选项：`exclude_miot_properties: power_consumption`

- #600

**Comment by Jeremy-Merle** [comment]
目前尝试了一下几种方案
1. 账号集成-本地模式；添加自定义选项 ```exclude_miot_properties: power_consumption``` ——功耗统计无法更新
  添加自定义选项后的状态
    ```
    cuco.plug.cp5pro:
      sensor_properties: voltage,electric_current
      sensor_attributes: power_cost_today,power_cost_month
      main_miot_services: switch-2
      stat_power_cost_key: '10.1'
      exclude_miot_properties: power_consumption
    ```
    设备面板中 power_consumption 传感器显示被禁用（可能是自定义选项生效后未手动删除）
3. 账号集成-本地模式；手动禁用 CP5Pro 设备中的所有传感器——功耗统计无法更新
4. 账号集成-云端模式；——功耗统计正常更新
  无需其他设置，设备面板中 power_consumption 传感器未被禁用但不更新，值为0，功耗统计可以正常更新
