### ISSUE TITLE
请求添加一款米家洗衣机支持！

### ISSUE THREAD

**Issue by ichenyf** [al-one/hass-xiaomi-miot#764]
型号：米家小米滚筒洗衣机全自动 10kg尊享版（XHQG100MJ203）
想来大佬很忙，为了节省时间，能够支持状态显示就满足了，不需要控制，洗衣机控制的意义不大，毕竟洗衣服一般要现场交互的。

**Comment by ichenyf** [comment]
给出设备ID：sensor.mibx2_v7_*_washer

**Comment by al-one** [comment]
请通过账号(自动模式)接入，并提供[实体属性](https://my.home-assistant.io/redirect/developer_states)、[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by ichenyf** [comment]
目前已经是登录米家帐号的自动模式接入，除了上面提供的设备信息，只有一个传感器：”Washer Status 不可用“，日志也是空的，显示”未找到日志条目“

**Comment by ichenyf** [comment]
在开发者工具里，状态中
状态显示为: unavailable
状态属性：
friendly_name: 洗衣机 Washer Status
supported_features: 0

**Comment by al-one** [comment]
请在集成选项中确保包含了该设备，目前看起来这款设备并没有被接入。

**Comment by ichenyf** [comment]
> 请在集成选项中确保包含了该设备，目前看起来这款设备并没有被接入。

选项中选择的筛选方式是 Exclude(排除)，且并没有排除任何一款设备，也重新更新过设备列表，洗衣机状态一直是这样。

**Comment by al-one** [comment]
请在[开发者工具](https://my.home-assistant.io/redirect/developer_services)中执行下面的服务，并从HA通知中获取结果。
```yaml
service: xiaomi_miot.get_properties
data:
  entity_id: sensor.mibx2_v7_xxxx_wash_status
  mapping:
    - {siid: 2, piid: 1}
    - {siid: 2, piid: 2}
    - {siid: 2, piid: 3}
    - {siid: 2, piid: 4}
    - {siid: 2, piid: 5}
    - {siid: 2, piid: 6}
    - {siid: 2, piid: 7}
    - {siid: 2, piid: 8}
    - {siid: 2, piid: 9}
    - {siid: 2, piid: 10}
    - {siid: 3, piid: 1}
  throw: true
```

**Comment by ichenyf** [comment]
返回的结果：
Miot properties
[]

三段代码都是一样的结果。系统里只有一个不可用的实体：sensor.mibx2_v7_1231_washer，我只能指定这个实体，才能执行代码。如果使用上面代码中的名字，使用 1231 代替 xxxx，是找不到实体的，”调用服务“按钮为灰色。

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.get_properties
data:
  entity_id: sensor.mibx2_v7_1231_washer
  mapping:
    - siid: 2
      piid: 1
  throw: true
```
再试试这个
