### ISSUE TITLE
8H 智能助眠天然乳胶枕X 

### ISSUE THREAD

**Issue by wenjiavv** [al-one/hass-xiaomi-miot#783]
龙佬，这个是不是也是服务器报错，没救了......

model: [qushui.pillow.p2](https://home.miot-spec.com/s/qushui.pillow.p2)
```yaml
lan_ip: 
mac_address: B4:60:ED:AC:F5:F6
entity_class: MiotSensorEntity
home_room: 我的家 主卧
miot_type: urn:miot-spec-v2:device:pillow:0000A0A0:qushui-p2:1
state_property: sleep_monitor.sleep_state
sleep_monitor.snore_state.error: '-704010000 Unknown'
sleep_monitor.sleep_state: 0
state_updater: cloud
sleep_monitor.sleep_state_desc: Awake
friendly_name: 8h intelligent sleeping natural latex pillow x Sleep Monitor State
supported_features: 0
```
