### ISSUE TITLE
Clean Zone Viomi.V10

### ISSUE THREAD

**Issue by darcarper** [al-one/hass-xiaomi-miot#789]
I have a xiaomi mop-p vacuum cleaner:

NAME: RoboBobo
		ID: 3756...
		MAC: 5C:6B:....
		IP: 192.168.1.121
		TOKEN: 4b7841....
		MODEL: viomi.vacuum.v10

I have integrated it with mIot without problems, I can start, pause, send to docker... But the part of sending to zones or point gives me an error:

![image](https://user-images.githubusercontent.com/69854550/189721124-6514f0ee-0aba-49a8-a708-eed598f400d6.png)

when trying to call the service:

```
service: xiaomi_miot_raw.call_action
data: 
  entity_id: vacuum.v10_cloud_
  siid: 4
  aiid: 13
  inn: 
    - 0
    - 1
````
I get this error:

_Failed to call service xiaomi_miot_raw.call_action. Unknown error_

any idea what i'm doing wrong?

**Comment by al-one** [comment]
`xiaomi_miot_raw` is not this component.

**Comment by al-one** [comment]
```yaml
event_type: call_service
data:
  domain: vacuum
  service: send_command
  service_data:
    entity_id: vacuum.viomi_v10_804a_robot_cleaner
    command: app_zoned_clean
    params: [[-4.8, -7.4, -2.5, -3, 1]] # [[x1, y2, x2, y1, repeats]]
```

1. sweep:
    ```yaml
    service: xiaomi_miot.send_command
    data:
      entity_id: vacuum.viomi_v10_804a_robot_cleaner
      method: set_mode_withroom
      params: [0, 1, 0]
    ```
2. sweep mop:
    ```yaml
    service: xiaomi_miot.send_command
    data:
      entity_id: vacuum.viomi_v10_804a_robot_cleaner
      method: set_mode_withroom
      params: [1, 1, 0]
    ```
3. mop:
    ```yaml
    service: xiaomi_miot.send_command
    data:
      entity_id: vacuum.viomi_v10_804a_robot_cleaner
      method: set_mode_withroom
      params: [3, 1, 0]
    ```
