### ISSUE TITLE
Dreame D9 (dreame-p2009) clean rooms

### ISSUE THREAD

**Issue by jlssmt** [al-one/hass-xiaomi-miot#793]
Hello,
I am unable to get my D9 vacuum to clean certain rooms.

Here is my service call:
```yml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2009_7503_robot_cleaner
  siid: 2
  aiid: 3
  params:
    - 7,5
```

That's the result I can't decipher:
```yml
event_type: xiaomi_miot.call_miot_action
data:
  entity_id: vacuum.dreame_p2009_7503_robot_cleaner
  did: "383117752"
  siid: 2
  aiid: 3
  result:
    did: "383117752"
    miid: 0
    siid: 2
    aiid: 3
    code: 0
    exe_time: 0
    withLatency: 0
origin: LOCAL
time_fired: "2022-09-15T11:32:14.130914+00:00"
context:
  id: 01GD0EQXXXXXXXXXXXXN4BZT376
  parent_id: null
  user_id: null
```

Here is the documentation:
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2009:2

I don't understand why it's not working. Maybe my param room_id array is wrong syntax?

My biggest fear is, that this is the correct documentation, which has no "start-room-sweep" action:
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2009:1

What's the difference between the documentation? Seems like revision v1 and v2 or something like that? Is it about a firmware update? Or hardware differences?

Thank you very much in advance.

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/491#issuecomment-1100708607

**Comment by jlssmt** [comment]
@al-one 
Thank you so much for the input.
But it's not working for my D9:

Neither that:
```yml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2009_7503_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: "{'selects':[[5,1,2,3,2]]}"
  force_params: true
  throw: true
```

Nor that:
```yml
[...]
  siid: 3
  aiid: 2
[...]
```

And no matter if "force_params" is added.
My robot ignores the command completely and I also get no result via xiaomi_miot.call_miot_action event.
I also tried it without piid: 1 & value: 18, because I don't know what this value is doing. I think it's for work-mode (value between 1 and 50)? But what is work-mode? I can't decipher the home.miot-spec.com documentation :-(

**Comment by al-one** [comment]
```yaml
WorkMode: {
  IdleMode: 0,
  PauseAndStopMode: 1,
  AutoCleanMode: 2,
  BackHomeMode: 3,
  PartCleanMode: 4,
  FollowWallMode: 5,
  ChargingMode: 6,
  OtaModeMode: 7,
  FctModeMode: 8,
  WIFISetMode: 9,
  PowerOffMode: 10,
  FactoryMode: 11,
  ErrRepotMode: 12,
  RemoteCtrlMode: 13,
  SleepMode: 14,
  SelfTestMode: 15,
  FactoryFuncTest: 16,
  StandbyMode: 17,
  AreaClean: 18,
  CustomAreaClean: 19,
  SpotClean: 20,
  FastMapping: 21
}
```

```javascript
_this.startClean = function () {
  if (_this.showCoverLayer()) {
    return;
  }

  if (_this.statusUtil.isFastMapping()) {
    _this.showDialogWithOneButton("", _string.default.noMapChangeModeTips);

    return;
  }

  if (_this.statusUtil.isCleaning() && !_this.statusUtil.isWashingMop() || _this.statusUtil.goWashing()) {
    Vacuum.Pause(function (err, res) {
      if (!err) {
        _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
      }
    });
  } else if (_this.statusUtil.isWashingMop()) {
    if (_this.curV && _this.curV > 1037 || _this.getVersion() && _this.getVersion() > 1037) {
      VacuumExtend.startBackflush("1,0", function (err, res) {
        _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
      });
    } else {
      Vacuum.Pause(function (err, res) {
        if (!err) {
          _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
        }
      });
    }
  } else if (_this.statusUtil.goWashingPause()) {
    if (_this.curV && _this.curV > 1037 || _this.getVersion() && _this.getVersion() > 1037) {
      VacuumExtend.startBackflush("2,1", function (err, res) {
        _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
      });
    } else {
      VacuumExtend.startBackflush(null, function (err, res) {
        _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
      });
    }
  } else if (_this.statusUtil.isWashingMopPause()) {
    if (_this.curV && _this.curV > 1037 || _this.getVersion() && _this.getVersion() > 1037) {
      VacuumExtend.startBackflush("1,1", function (err, res) {
        _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
      });
    } else {
      Vacuum.startClean(function () {
        _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
      });
    }
  } else {
    if (_this.state.batteryLevel <= 15) {
      _this.showDialogWithOneButton("", _string.default.batteryLowTips);

      return;
    }

    if (_this.statusUtil.hasTask()) {
      Vacuum.startClean(function (err, res) {
        if (!err) {
          _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
        }
      });
    } else {
      if (_Const.default.mopOrWaterTank && _Const.default.showBackFlushWelcome && _this.noPrompt[_this.studyWashKey] != true) {
        _this.setState({
          showStudyPage: true,
          showStudyClean: false,
          showStudyWash: true
        });
      }

      if (_this.state.selectMapType == 2) {
        var selectArea = _this.ldsMap.getCustomArea();

        if (selectArea.length == 0) {
          _this.showMessageToast(_string.default.lessThanOneCustom);

          return;
        }

        var cleanInfo = [];

        for (var i in selectArea) {
          var item = selectArea[i];

          if (item) {
            var newInfo = [parseInt(item[0]), parseInt(item[1]), parseInt(item[2]), parseInt(item[3]), _this.state.customNum, _this.state.cleaningMode, _this.state.mopMode];
            cleanInfo.push(newInfo);
          }
        }

        var cleanData = _this.mapDataUtil.rotateViewCustomArea({
          "areas": cleanInfo
        });

        VacuumExtend.startClean(_Common.default.WorkMode.CustomAreaClean, JSON.stringify(cleanData), function (err, res) {
          if (!err) {
            if (_this.ldsMap) {
              _this.ldsMap.setState({
                cleanedAreas: _this.ldsMap.getCustomArea()
              });
            }

            _this.mapDataUtil.setCustomArea(cleanData);

            _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);

            _this.setState({
              showInfo: true
            });

            _this.showMessageToast(_string.default.customAreaMsg);
          }
        });
      } else if (_this.state.selectMapType == 0) {
        var selectAreas = _this.ldsMap.getSelectArea();

        if (selectAreas.length == 0) {
          _this.showDialogWithOneButton(null, _string.default.noSelectAreaTip, null, null);

          return;
        }

        var cleanSet = MapDataUtil.getCleanSet();
        var hasOrder = false;

        if (cleanSet) {
          Object.keys(cleanSet).map(function (key) {
            if (cleanSet[key][3] && cleanSet[key][3] != 0) {
              hasOrder = true;
            }
          });
        }

        var showMode = !(_this.state.customEnable > -1 && hasOrder);
        var selectInfo = [];

        for (var areaId in selectAreas) {
          var _item = selectAreas[areaId];

          if (_item) {
            var newData = [parseInt(_item), _this.state.selectNum, _this.state.cleaningMode, _this.state.mopMode, showMode ? Number(areaId) + 1 : 1];
            selectInfo.push(newData);
          }
        }

        var selectData = {
          "selects": selectInfo
        };
        VacuumExtend.startClean(_Common.default.WorkMode.AreaClean, JSON.stringify(selectData), function (err, res) {
          if (!err) {
            _this.mapDataUtil.setSelectArea(selectInfo);

            _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);

            if (_this.ldsMap) {
              _this.ldsMap.removeOrder();
            }

            _this.setState({
              showInfo: true
            });
          }
        });
      } else {
        Vacuum.startClean(function () {
          _this.initDeviceData(_Common.Props.PropWorkMode, _Common.Props.PropTaskStatus, _Common.Props.PropWashStation, _Common.Props.PropWarnStatus);
        });
      }
    }
  }
};
```

[dreame.vacuum.p2009.js.txt](https://github.com/al-one/hass-xiaomi-miot/files/9595877/dreame.vacuum.p2009.js.txt)

**Comment by jlssmt** [comment]
I still couldn't get it to work. @al-one do you have any more ideas why it's not working for me?

**Comment by jlssmt** [comment]
@al-one 
Thanks.
Logs show this:
`2022-10-10 15:57:28 -> {"id":8994,"method":"action","params":{"did":"383117752","siid":4,"aiid":1,"in":[{"piid":1,"value":18},{"piid":10,"value":"{\"selects\":[[5,1,2,3,1]]}"}]}}`

But this is not working:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2009_7503_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: "{\"selects\":[[5,1,2,3,1]]}"
  throw: true
```

**Comment by al-one** [comment]
Try:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2009_7503_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - piid: 1
      value: 18
    - piid: 10
      value: '{"selects":[[5,1,2,3,1]]}'
  force_params: true
  throw: true
```

**Comment by al-one** [comment]
Do not integrate the device through the cloud.

**Comment by al-one** [comment]
For this device, the action of cleaning rooms may only be done locally.

Try in cloud:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_p2009_7503_robot_cleaner
  siid: 4
  aiid: 1
  params:
    - '{"selects":[[5,1,2,3,1]]}'
  throw: true
```
