### ISSUE TITLE
dmaker.fan.p5 no speed control

### ISSUE THREAD

**Issue by Aljutor** [al-one/hass-xiaomi-miot#794]
At some update, integration lost ability for fan speed control. 
Not at, v0.6.11 it simply do not act at fan speed change. 

https://home.miot-spec.com/s/dmaker.fan.p5

**Comment by al-one** [comment]
```yaml
# configuration.yaml
logger:
  default: warning
  logs:
    custom_components.xiaomi_miot.core.miio2miot: debug
```
And show me the [logs](https://my.home-assistant.io/redirect/logs) after control fan speed.
