### ISSUE TITLE
Viomi V3 Max point/zone clean

### ISSUE THREAD

**Issue by foxymichelle** [al-one/hass-xiaomi-miot#796]
I was able to get the room clean working using the following code, where a,b,c are my room id numbers:

```yaml
service: xiaomi_miot.call_action
data:
  siid: 4
  aiid: 13
  params:
    - 0
    - 1
    - a,b,c
  entity_id: vacuum.dusty
```

For point-zone cleaning, the siid is 6 and aiid 1 (point) or 5 (zone). There's nothing on the [documentation](https://home.miot-spec.com/spec/viomi.vacuum.v23) about expected params, but it seems obvious: list x,y for point and x1,y1...x4,y4 for zone.

```yaml
service: xiaomi_miot.call_action
data:
  siid: 6
  aiid: 1
  params:
    - x,y 
  entity_id: vacuum.dusty
```

I've also tried to specify params, a second layout that also works for room cleanup, but does not work for point or zone:

```yaml
 params:
    - piid: 1
      value: x,y 
```

I am using the Xiaomi Vacuum Map card to get coordinates, and it does seem that maybe there a difference in the coordinates (a map coordinate would look like -1298, 3402, but the sample in the documentation is 3.23,6.89. I've tried using both larger and smaller numbers as my coordinates, wondering if the larger numbers were out of range.

Any direction on getting this to work?

Also, I would like to use the "Point and Go" option on the map card, but I don't see a way in the documentation to send this vacuum to a coordinate without cleanup (so sent it to the garbage can and wait there to be emptied). Let me know if there's a way to accomplish that as well.

Thank you!

**Comment by foxymichelle** [comment]
I found this, which gives a little insight. This vacuum has additional actions and parameters in its point-zone (siid 9) that allows it to first have the zone set (aiid 8 with piid 2), then start cleaning the zone (aiid 3). 

#506

**Comment by al-one** [comment]
It is recommended to obtain command parameters through MiHome APP modified by vevs.
- https://github.com/al-one/hass-xiaomi-miot/issues/114#issuecomment-868721912

**Comment by foxymichelle** [comment]
I dusted off my old android phone that I never got around to selling and loaded the apk, but can't turn on `Write custom log files` (the page just reloads with it turned back off), and I don't see `Enable apps debug mode` - maybe the verbiage changed to `Enable developers mode`? 

I did find the missing step in which I needed to first create the `vevs/logs/miio/` folders, which didn't work. I also tried `sdcard/vevs/logs/miio/`. I added the folder to `internal storage`. I've been restarting the app, deleting and reinstalling the app (ensuring that I have downloaded the most recent version), searching the web for possible solutions given my particular issue, etc., but I can't get the custom log option to turn on.

**Comment by foxymichelle** [comment]
It requires two service calls: set property, then start clean. Here's the code to get it to clean a point:

```yaml
service: xiaomi_miot.set_miot_property
data:
  entity_id: vacuum.dusty
  siid: 6
  piid: 1
  value: "x,y"

service: xiaomi_miot.call_action
data:
  siid: 6
  aiid: 1
  entity_id: vacuum.dusty
```

And here's for zone clean up:

```yaml
service: xiaomi_miot.set_miot_property
data:
  entity_id: vacuum.dusty
  siid: 6
  piid: 2
  value: “x1,y1,x2,y2,x3,y3,x4,y4”

service: xiaomi_miot.call_action
data:
  siid: 6
  aiid: 5
  entity_id: vacuum.dusty
```

I posted how to get this working with the Xiaomi Vacuum Map Card [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406).
