### ISSUE TITLE
ijai.vacuum.v2 [米家扫拖机器人2]，吸力状态如何用命令调用？

### ISSUE THREAD

**Issue by YirEnyueXia7** [al-one/hass-xiaomi-miot#798]
感谢大佬的插件帮我把扫地机接入，
请教一下，我的设备是米家扫拖机器人2=[ijai.vacuum.v2](https://home.miot-spec.com/s/ijai.vacuum.v2)，吸力状态如何调用命令去变更，实测前端点击可行(安静/标准/中档/强力)4档，但是用服务vacuum.set fan speed不管是写3还是100都没反应。

**Comment by al-one** [comment]
```yaml
service: vacuum.set_fan_speed
data:
  entity_id: vacuum.ijai_v2_xxxx_robot_cleaner
  fan_speed: 强劲
```
