### ISSUE TITLE
米家空调插座回报HomeKit温度问题

### ISSUE THREAD

**Issue by A1exMinatoooo** [al-one/hass-xiaomi-miot#800]
我使用的配件是【米家空调伴侣2】，通过 HomeAssistant 接入 HomeKit 后，在 HomeKit 首页的快捷开关上始终会显示一个【21°】，并会被纳入房间内环境传感器中统计（如下图）

![image](https://user-images.githubusercontent.com/21982749/191165309-36611bda-8bfa-4219-8852-576a951af2e2.png)

但是点开开关后里面是正常的温度控制，并没有【21°】相关的内容

![image](https://user-images.githubusercontent.com/21982749/191165390-b9bb1262-6030-4fab-972e-77135c5cf6cd.png)

同时在 HomeAssistant 中查看实体相关数据也没有找到【21°】，请问是什么原因呢？

![image](https://user-images.githubusercontent.com/21982749/191165452-b0c59cf8-cf8a-4bfc-ba77-b658ba2b930e.png)

**Comment by al-one** [comment]
https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/type_thermostats.py#L217-L219
![image](https://user-images.githubusercontent.com/4549099/191271059-c48ce646-93dd-4df9-8a52-23130d509f93.png)

由于空调伴侣没有温度传感器，无法获取当前室温，实体的`current_temperature: null`，HA的homekit集成在未获取到温控器实体的当前温度时会默认用`21.0`℃去作为默认值。推荐通过[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/100#custom)`bind_sensor`去为温控器实体绑定温度传感器。

- https://github.com/al-one/hass-xiaomi-miot/issues/686#issuecomment-1173297983

**Comment by Jack-Works** [comment]
如果没有温度传感器，可以通过 current_temp_property 使用空调的目标温度作为显示的温度，例：

```yaml
customizing_device:
  lumi.acpartner.mcn02:
    sensor_attributes: electric_power,power_cost_today,power_cost_month
    current_temp_property: target_temperature
```
