### ISSUE TITLE
how to automate for force renew devices?

### ISSUE THREAD

**Issue by lysiong** [al-one/hass-xiaomi-miot#816]
if there is a power outage occur & power coming back, some device might not get status update or becoming offline. The only way is to go integration-->Xiaomi Miot Auto-->configure-->tick force renew devices & submit, then device will online back. Is that anyway to automate this process every 30mins or longer?

**Comment by lysiong** [comment]
<img width="227" alt="image" src="https://user-images.githubusercontent.com/45681255/193713713-ce754942-d5f5-4248-860c-1eabe3cdfdc0.png">
how to use automation to "force renew devices" ? as everytime the device is off for few hours, I will need to manually force renew devices so that it will become online back.

**Comment by al-one** [comment]
```yaml
alias: renew xiaomi devices
mode: single
sequence:
  - service: xiaomi_miot.renew_devices
    data:
      username: 80001234 # Xiaomi Account ID / Email / Phone
  - service: xiaomi_miot.reload
```
