### ISSUE TITLE
小米净水器 tds-in和 tsd-out 获取参数和实际存在明显偏差问题

### ISSUE THREAD

**Issue by caoyaochong** [al-one/hass-xiaomi-miot#818]
小米净水器 型号是 

> yunmi.waterpuri.lx2

 miot-auto版本是 

> v0.6.12 - 2022-09-20

下图分别是 Home Assistant 和 米家App 净水器入水TDS 和 出水TDS截图，发现 出水TDS存在严重偏差，米家App上为19，而105。

<img width="684" alt="image" src="https://user-images.githubusercontent.com/7949891/192802740-c452b55f-2b61-479e-b6bf-5e65233ffc87.png">

![image](https://user-images.githubusercontent.com/7949891/192802562-dd9bbf03-42c2-4c6c-9222-03f14f984e99.png)

**Comment by al-one** [comment]
请在开发者工具中执行下面[服务](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)，并从HA侧边栏通知中找到结果。
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.yunmi_lx2_xxxx_water_purifier
  method: get_prop
  params: [tds_in,tds_out]
  throw: true
```
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.yunmi_lx2_xxxx_water_purifier
  method: get_prop
  params: [tds_out]
  throw: true
```
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.yunmi_lx2_xxxx_water_purifier
  method: get_prop
  params: [all]
  throw: true
```
