### ISSUE TITLE
zhimi.airfresh.va4/Xiaomi Miot Auto

### ISSUE THREAD

**Issue by Ot4eVash** [al-one/hass-xiaomi-miot#837]

**Comment by Ot4eVash** [comment]
Can you please add heater temperature sensor (ntc) for zhimi.airfresh.va4 to Xiaomi Miot Auto integration?
airfresh_ntc_temperature:

        friendly_name: AirFresh  NTC Temp
        value_template: '{{ states.fan.XiaomiAirFresh.attributes.ntc_temperature }}'
        unit_of_measurement: '°C'

**Comment by al-one** [comment]
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    zhimi.airfresh.va4:
      miio_properties: ntcT
      sensor_attributes: miio.ntcT
```
