### ISSUE TITLE
xiaomi mop 2 pro translation issue

### ISSUE THREAD

**Issue by amiraizat124** [al-one/hass-xiaomi-miot#842]
![error1](https://user-images.githubusercontent.com/44428060/195042788-0f0c6d46-0b63-4ca8-af8d-d162eab9aa03.jpg)
![error2](https://user-images.githubusercontent.com/44428060/195042816-c177b532-5719-4966-8947-0ed1afae72a8.jpg)

water state and fan speed are not in english

**Comment by al-one** [comment]
Upgrade to master branch and add configuration:
```yaml
# configuration.yaml
xiaomi_miot:
  language: en
```
