### ISSUE TITLE
Round number to 1 decimal

### ISSUE THREAD

**Issue by leroyloren** [al-one/hass-xiaomi-miot#845]
Is there a reason for the 6 int?

https://github.com/al-one/hass-xiaomi-miot/blob/89df652ca856ab6453b895325ab3572e939c0a8b/custom_components/xiaomi_miot/number.py#L98

![obrazek](https://user-images.githubusercontent.com/57643470/196033460-e39e70cf-498d-4058-bbae-04363ed324ff.png)

**Comment by al-one** [comment]
Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by leroyloren** [comment]
![obrazek](https://user-images.githubusercontent.com/57643470/196117575-ef2ccba8-ff3a-4288-ae3c-255bf8d59e34.png)

**Comment by al-one** [comment]
```yaml
# customize.yaml
sensor.zhimi_mb5_19f5_temperature:
  value_ratio: 1
```
