### ISSUE TITLE
紅外風扇控制問題

### ISSUE THREAD

**Issue by kei81131** [al-one/hass-xiaomi-miot#879]
你好
我將紅外風扇添加後, 發現只有風扇的開關實體
其他的操作, 需要點進去才能進行, 如下圖

請問有辦法把其他的操作都添加實體嗎?

![ir fan2](https://user-images.githubusercontent.com/111072203/201597239-69a47728-f02f-46e0-9bcf-0c10a1b35ef6.jpg)
![ir fan1](https://user-images.githubusercontent.com/111072203/201597245-4ef8b61a-01e6-49c3-9d72-6789bd08d474.jpg)

**Comment by al-one** [comment]
HA的风扇实体就是这样，如果你想把操作作为单独的实体，可以[自定义设备](https://github.com/al-one/hass-xiaomi-miot/issues/600)：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    miir.fan.ir01:
      button_actions: turn_on,turn_off,fan_speed_up,fan_speed_down,horizontal_swing_on,horizontal_swing_off
```
