### ISSUE TITLE
ainice.motion.bt 人体传感器

### ISSUE THREAD

**Issue by ilongjiang** [al-one/hass-xiaomi-miot#880]
[ainice.motion.bt](https://home.miot-spec.com/s/ainice.motion.bt)传感器反应比米家慢很多。有时候还没反应

**Comment by al-one** [comment]
请参考：
- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222
- https://github.com/al-one/hass-xiaomi-miot/issues/600

**Comment by al-one** [comment]
[![xiaomi miot ainice](https://user-images.githubusercontent.com/4549099/203486759-5c7eded5-a544-40d2-b331-0d4d580775b9.png)](https://github.com/al-one/hass-xiaomi-miot/issues/600)

**Comment by al-one** [comment]
添加自动化以更新设备下的指定属性：
```yaml
alias: 获取小米设备属性
description: xiaomi miot get properties
trigger:
  - platform: time_pattern
    seconds: /2
    id: s2
condition: []
action:
  - if:
      - condition: trigger
        id: s2
    then:
      - service: xiaomi_miot.get_properties
        data:
          entity_id: binary_sensor.ainice_bt_xxxx_motion_sensor
          update_entity: true
          mapping:
            - siid: 2
              piid: 21
mode: single
```
