### ISSUE TITLE
chunmi.health_pot.a1设备没有通过云端接入

### ISSUE THREAD

**Issue by shawn996** [al-one/hass-xiaomi-miot#883]
ha在家中，chunmi.health_pot.a1养生壶在公司，因此先设置了一个本地模式，接入ha网络需要本地接入的设备；其次创建了一个云端模式，用于接入chunmi.health_pot.a1和小爱音响。
但问题来了，小爱音响接入没问题，可chunmi.health_pot.a1是不可用状态。怀疑chunmi.health_pot.a1还是走了本地接入。

有没有办法在选择自动模式的情况下，设置指定设备的接入模式，解决这种跨网络的问题。

**Comment by al-one** [comment]
我印象中，该型号的养生壶在云端接入时有点问题，所以才默认本地接入了。你可以通过[自定义设备](https://github.com/al-one/hass-xiaomi-miot/issues/600)强制云端接入：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    chunmi.health_pot.a1:
      miot_cloud: true
      miot_local: false
```
