### ISSUE TITLE
空调伴侣 2 是否可以在 HA 关闭制热模式？

### ISSUE THREAD

**Issue by CheukFaiho** [al-one/hass-xiaomi-miot#886]
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/35355832/202696656-60abe441-f1de-4d33-b62d-5db396c1fe55.png">
询问了小米官方客服，表示无法去掉。是否有办法在 HA 中隐藏？

**Comment by al-one** [comment]
尝试添加下面的配置。
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    lumi.acpartner.mcn02:
      extend_miot_specs:
        - iid: 2
          properties:
            - iid: 2
              value-list:
                - value: 0
                  description: Auto
                - value: 1
                  description: Cool
                - value: 2
                  description: Dry
                - value: 4
                  description: Fan
```
