### ISSUE TITLE
Help - how to properly use actions, zones and coordinates [ijai.vacuum.v10]

### ISSUE THREAD

**Issue by paulakfleck** [al-one/hass-xiaomi-miot#889]
Hello! I'm not sure this is the correct place, but I've been trying to create zones and send my vacuum there to clean, and so far I wasn't successful.

This is my model: ijai.vacuum.v10 - https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:ijai-v10:1

This is the script I'm running. From my understanding, my model requires a zone to be set before I ask it to go there to clean it.
```yaml
alias: "Vacuum: Clean Mapped Zone"
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v10_0930_robot_cleaner
      siid: 9
      aiid: 8
      throw: true
      params: x1, y1, x2, y2, x3, y3, x4, y4
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v10_0930_robot_cleaner
      siid: 9
      aiid: 3
      throw: true
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v10_0930_robot_cleaner
      siid: 10
      aiid: 12
      params:
        - param1?
        - param2?
      throw: true
mode: single
```

I have a few questions: 

1) Is this the correct way to send my robot to clean, let's say, a zone with params `x1, y1, x2, y2, x3, y3, x4, y4`?

2) How do I determine `x1, y1, x2, y2, x3, y3, x4, y4` zone? I tried using the Map Extractor plugin, but my model is not supported, so I'm using an image on lovelace-xiaomi-vacuum-map-card.

3) After you make the fist service call (siid 9, aiid 8), how does the API should respond? Mine usually respond with: 
```json
{'code': 0, 'out': [{'piid': 7, 'value': 1}, {'piid': 8, 'value': 0}, {'piid': 9, 'value': 0}]}
```

I imagine 1, 0 and 0 are the map-id, map-type and timestamp. But I don't know if 1, 0 and 0 means it's not working.

4) In the last service, what params should go there?

Here's my vevs logs: 

[530369328.txt](https://github.com/al-one/hass-xiaomi-miot/files/10050478/530369328.txt)

Thank you so much in advance!

**Comment by al-one** [comment]
I didn't find any `"siid":9` in your logs, make sure you performed a zone cleanup in MiHome by vevs.

```javascript

  function setArea(area) {
    var va = area.points[0].x + "," + area.points[0].y + ","
           + area.points[1].x + "," + area.points[1].y + ","
           + area.points[2].x + "," + area.points[2].y + ","
           + area.points[3].x + "," + area.points[3].y;
    var ssid = _SCNetEnum.default.NetServer.S9pointZone;
    var aiid = _SCNetEnum.default.S9PointZoneAction.S9A8_setArea;

    var values = [va];

    var params = _encapDo(ssid, aiid, values);
    var matches = /function\s*(\w*)/i.exec(arguments.callee.toString());
    _WLLog.default.log(_WLDateUtils.default.nowText() + " req:", matches[1], params);

    return new Promise(function (accept, reject) {
      _doCommon(params, matches[1], 1).then(function (res) {
        var model = _SCDevice.SCDevice.mapModel.getNewMapTimeStampResult(res);
        if (model == null) {
          reject(model);
        } else {
          _SCDevice.SCDevice.mapModel.refreshArea(area);
          _updateNewestMapStamp(model);
          accept(model);
        }
      }).catch(function (error) {
        reject(error);
      });
    });
  }

  function startAreaClean() {
    var ssid = _SCNetEnum.default.NetServer.S9pointZone;
    var aiid = _SCNetEnum.default.S9PointZoneAction.S9A3_startZoneClean;
    var params = _encapDo(ssid, aiid);
    var matches = /function\s*(\w*)/i.exec(arguments.callee.toString());
    _WLLog.default.log(_WLDateUtils.default.nowText() + " req:", matches[1], params);

    return new Promise(function (accept, reject) {
      _doCommon(params, matches[1], 1).then(function (model) {
        if (model.result) {
          clearFaultCodeBeforeMove();
        }
        accept(model);
      }).catch(function (error) {
        reject(error);
      });
    });
  }
```

Try:
```yaml
alias: "Vacuum: Clean Mapped Zone"
mode: single
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v10_0930_robot_cleaner
      siid: 9
      aiid: 8
      params:
        - x1,y1,x2,y2,x3,y3,x4,y4
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v10_0930_robot_cleaner
      siid: 9
      aiid: 3
```
