### ISSUE TITLE
断网情况下无法控制Wi-Fi设备

### ISSUE THREAD

**Issue by z-jack** [al-one/hass-xiaomi-miot#896]
设备型号：[philips.light.cbulb](https://home.miot-spec.com/s/philips.light.cbulb)
报错内容：ee certificate key too weak

**Comment by al-one** [comment]
尝试添加以下配置：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    philips.light.cbulb:
      miot_cloud_write: false
```
