### ISSUE TITLE
Rooms with ijai.vacuum.v19

### ISSUE THREAD

**Issue by RaulVKoNe** [al-one/hass-xiaomi-miot#899]
https://home.miot-spec.com/s/ijai.vacuum.v19

I have a problem when I send the vacuum cleaner to clean a room exclusively.

The action is carried out but it always does it with sweep and mop, when what I want is for it to only sweep.

The script I run is the following:

```yaml
alias: Aspiradora - Aspirar baño (Duplicar)
sequence:
  - service: vacuum.set_fan_speed
    data:
      fan_speed: Slient
    target:
      entity_id: vacuum.ijai_v19_19b9_robot_cleaner
    alias: Aspiración silenciosa
  - service: xiaomi_miot.set_miot_property
    data:
      entity_id: vacuum.ijai_v19_19b9_robot_cleaner
      siid: 2
      piid: 4
      value: 0
    alias: Modo solo aspirar
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v19_19b9_robot_cleaner
      siid: 7
      aiid: 3
      throw: true
      params:
        - "10"
        - 0
        - 1
mode: single
icon: mdi:sofa-single
```

Do you know where the problem is or if something is missing??? Since in the application it shows that it is only vacuuming, but in reality it is not. Is sweep anda mop...

**Comment by al-one** [comment]
It seems that there is no problem. Is it possible to specify that the room is only sweep in the MiHome APP?
It is recommended to use [MiHome modified by vevs](https://github.com/al-one/hass-xiaomi-miot/issues/114#issuecomment-868721912) to obtain its logs.

The following is the source code of the MiHome plug-in for this device, for reference:
```javascript
  function controlClean(status) {
    var rooIds = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : [];
    var per = status == _SCPublic.SCControlParam.start ? _SCPublic.SCSetRoomCleanParam.start : _SCPublic.SCSetRoomCleanParam.pause;
    var model = _SCDevice.SCDevice.stateModel.S2P8_sweepType == _SCPublic.SCCleanModel.border ? _SCPublic.SCSetRoomModeParam.border : _SCPublic.SCSetRoomModeParam.auto;

    _WLLog.default.log('controlClean_s2p8:', _SCDevice.SCDevice.stateModel.S2P8_sweepType);

    return setRoomClean(rooIds, per, model);
  }

  function setCleanType(va) {
    var params = _encapSet(_SCNetEnum.default.NetServer.S2vacuum, _SCNetEnum.default.S2VacuumProperty.S2P4_mode, va);

    var matches = /function\s*(\w*)/i.exec(arguments.callee.toString());

    _WLLog.default.log("\u8BBE\u7F6E\u6E05\u626B\u6A21\u5F0F " + _WLDateUtils.default.nowText() + " req:", matches[1], params);

    return new Promise(function (resolve, reject) {
      _setCommon(params, matches[1], 2).then(function (res) {
        if (res.result) {
          resolve(res);
          _SCDevice.SCDevice.stateModel.S2P4_mode = va;
        } else {
          reject('设置清扫模式 error');
        }
      }).catch(function (err) {
        reject(err);
      });
    });
  }

  function setCleanModel(va) {
    var params = _encapSet(_SCNetEnum.default.NetServer.S2vacuum, _SCNetEnum.default.S2VacuumProperty.S2P8_sweepType, va);

    _WLLog.default.log("\u8BBE\u7F6E\u6E05\u626B\u6A21\u5F0F, \u8FDB\u5165\u5230\u6307\u5B9A\u7684\u7A7A\u95F2 va = " + va);

    var matches = /function\s*(\w*)/i.exec(arguments.callee.toString());

    _WLLog.default.log(_WLDateUtils.default.nowText() + " req:", matches[1], params);

    return new Promise(function (resolve, reject) {
      _setCommon(params, matches[1], 1).then(function (res) {
        _WLLog.default.log('设置清扫模式, 进入到指定的空闲成功');

        _SCDevice.SCDevice.stateModel.S2P8_sweepType = va;

        _reactNative.DeviceEventEmitter.emit(_SCPublic.ZNNOTIFY, ['S2P8_sweepType', va]);

        resolve(res);
      }).catch(function (err) {
        _WLLog.default.log('设置清扫模式, 进入到指定的空闲失败');

        reject(err);
      });
    });
  }

  function setRoomClean(ids, per, model) {
    var values = [ids.join(","), model, per];

    var params = _encapDo(_SCNetEnum.default.NetServer.S7sweep, _SCNetEnum.default.S7SweepAction.S7A3_setRoomClean, values);

    var matches = /function\s*(\w*)/i.exec(arguments.callee.toString());

    _WLLog.default.log(_WLDateUtils.default.nowText() + " \u9009\u623F\u95F4\u6E05\u626B:", matches[1], params);

    return new Promise(function (accept, reject) {
      _doCommon(params, matches[1], 1).then(function (model) {
        if (model.result) {
          clearFaultCodeBeforeMove();
        }

        accept(model);
      }).catch(function (error) {
        reject(error);
      });
    });
  }
```
[ijai.vacuum.v19.js.txt](https://github.com/al-one/hass-xiaomi-miot/files/10110645/ijai.vacuum.v19.js.txt)

**Comment by al-one** [comment]
Try:
```yaml
alias: Aspiradora - Aspirar baño (Duplicar)
sequence:
  - service: vacuum.set_fan_speed
    data:
      fan_speed: Slient
    target:
      entity_id: vacuum.ijai_v19_19b9_robot_cleaner
    alias: Aspiración silenciosa
  - service: xiaomi_miot.set_miot_property
    data:
      entity_id: vacuum.ijai_v19_19b9_robot_cleaner
      siid: 2
      piid: 4
      value: 0
    alias: Modo solo aspirar
  - service: xiaomi_miot.set_miot_property
    data:
      entity_id: vacuum.ijai_v19_19b9_robot_cleaner
      siid: 2
      piid: 8  # sweep-type
      value: 7 # Room
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v19_19b9_robot_cleaner
      siid: 7
      aiid: 3
      throw: true
      params:
        - "10"
        - 0
        - 1
mode: single
icon: mdi:sofa-single
```
