### ISSUE TITLE
水暖毯 HS2205 没有温度传感器和温度设定实体

### ISSUE THREAD

**Issue by MeowRay** [al-one/hass-xiaomi-miot#901]
https://home.miot-spec.com/s/isleep.blanket.hs2205

![image](https://user-images.githubusercontent.com/29674595/204085223-18ff290a-2faf-41d5-9f53-b01ee174137c.png)
但是在属性中有，是需要自定义实体吗？
![image](https://user-images.githubusercontent.com/29674595/204085356-b28ffc20-f979-4a65-b796-1c7d345fdb92.png)

**Comment by MeowRay** [comment]
通过设置自定义实体，可以实现
```
customizing_device:
  isleep.blanket.hs2205:
    select_properties: mode,heat_level,water_level
    sensor_properties: electric_blanket.temperature
    number_properties: target_temperature-2-5
    miot_local: true
```
