### ISSUE TITLE
能否实现创米摄像头开关的本地接入？

### ISSUE THREAD

**Issue by chenquanhao** [al-one/hass-xiaomi-miot#902]
[chuangmi.camera.ipc019](https://home.miot-spec.com/s/chuangmi.camera.ipc019)
旧版本用https://github.com/Tao173/ha-mycamera 的插件可以本地接入这个摄像头开关，好像是插件需要manifest.json这个文件之后的ha版本就不能用了，原插件作者也没再更新。现在用hass-xiaomi-miot云接入，过几天实体就不可用了。

**Comment by al-one** [comment]
请执行下面的服务并从HA侧边栏通知获取结果：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: camera.chuangmi_ipc019_xxxx
  method: get_prop
  params: [power,light,night_mode,flip,watermark,sdcard_status,motion_record,band_nearby,wdr]
  throw: true
```

```yaml
service: xiaomi_miot.send_command
data:
  entity_id: camera.chuangmi_ipc019_xxxx
  method: set_power
  params: ['off']
  throw: true
```
