### ISSUE TITLE
请问下intelligent_speaker服务要怎么读取webhook的payload

### ISSUE THREAD

**Issue by Westwall98** [al-one/hass-xiaomi-miot#907]
请问下音箱服务的intelligent_speaker要怎么获取来自自动化webhook的payload信息？这是一个webhook的示例，我在param和headers都传输了自定义内容，但是试了很多方法都不能自定义intelligent_speaker服务的text字段

```variables:
  trigger:
    platform: webhook
    webhook_id: "**************************"
    data:
      __type: <class 'multidict._multidict.MultiDictProxy'>
      repr: "<MultiDictProxy('data': 'test for Miot')>"
    query:
      __type: <class 'multidict._multidict.MultiDictProxy'>
      repr: <MultiDictProxy()>
    description: webhook
    id: "0"
    idx: "0"
    alias: null
context: null
```

这是intelligent_speaker服务的内容：
```
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaomi_lx05_a4c4_play_control
  execute: false
  silent: true
  text: "{% if data['repr']['data'] %}true{% endif %}"
```

我要怎么定义text才能从webhook中获取到相关参数？感谢您的解答！

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaomi_lx05_a4c4_play_control
  execute: false
  text: "{{ trigger.data.data }}"
```
参考：
- https://www.home-assistant.io/docs/automation/trigger/#webhook-data
- https://www.home-assistant.io/docs/automation/templating/#webhook
