### ISSUE TITLE
小米空调伴侣2（lumi.acpartner.mcn02）通过homekit自动化开关不正常

### ISSUE THREAD

**Issue by mentalfl0w** [al-one/hass-xiaomi-miot#908]
使用Siri或者手动在家庭app中开关都很正常，但涉及自动化或者场景的时候就不正常，会发出多个指令，比如关闭的时候会先发出关闭指令，后又莫名其妙开启，中间间隔2秒，日志如下：
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/30333935/204820008-ea0b9827-21cb-468f-a989-c623becab504.png">

**Comment by mentalfl0w** [comment]
> 自动化怎么写的？是HA自动化还是HomeKit自动化？

是HomeKit里面的自动化，大致是到晚上11点后就关闭空调这样子的

**Comment by jiangyiqi99** [comment]
我遇到了相同的情况，只要是场景或者自动化的关空调就不行。别的可以，如果有必要的话可以找我提供日志。

**Comment by al-one** [comment]
请提供下调试日志：
```yaml
# configuration.yaml
logger:
  default: warning
  logs:
    custom_components.xiaomi_miot.climate: debug
```

**Comment by jiangyiqi99** [comment]
我上传了日志：我使用homekit场景关闭空调，但空调反复横跳几次并未关闭。
最后我手动打开了空调。
[home-assistant.log](https://github.com/al-one/hass-xiaomi-miot/files/10167381/home-assistant.log)

**Comment by jiangyiqi99** [comment]
很高兴能看到你的回复。我想说，你所有的猜想都是完全正确的。那两次你怀疑我手动操作的开关的确是我手动操作，而且空调的打开确实也是由于设定了温度或风量。
我已经将我手动操作的日志发送给了您，为了减少您的工作量，我已经进行了简要分析。为了您的完整理解，我
[home-assistant.log](https://github.com/al-one/hass-xiaomi-miot/files/10174733/home-assistant.log)
并没有进行精简。您这边可以看一下。

**Comment by jiangyiqi99** [comment]
空调依然被打开了，日志如下。
[home-assistant.log](https://github.com/al-one/hass-xiaomi-miot/files/10185424/home-assistant.log)

**Comment by al-one** [comment]
```
2022-12-08 20:38:15.310 Got new state: {'air_conditioner.on': False, 'air_conditioner.mode': 3, 'target_temperature-2-3': 24.0, 'electric_power-5-1': 6.0, 'fan_control.fan_level': 2, 'fan_control.vertical_swing': False, 'state_updater': 'lan'}
2022-12-08 20:38:19.590 Send miio command: set_tar_temp([23])
2022-12-08 20:38:19.860 Got new state: {'air_conditioner.on': True, 'air_conditioner.mode': 3, 'target_temperature-2-3': 23.0, 'electric_power-5-1': 6.0, 'fan_control.fan_level': 2, 'fan_control.vertical_swing': False, 'state_updater': 'lan'}
```
该设备是通过`miio2miot`机制适配的本地接入，设置目标温度时发送给设备的原始命令就是`set_tar_temp`，不幸的是该设备收到这个命令后会重新打开空调。因此只能通过其他方式去解决该问题：
1. 为该设备[生成一个开关`switch`实体](https://github.com/al-one/hass-xiaomi-miot/issues/100#custom)
    ```yaml
    # configuration.yaml
    xiaomi_miot:
      device_customizes:
        lumi.acpartner.mcn02:
          switch_properties: air_conditioner.on
    ```
2. 将开关实体接入HomeKit
3. 在HomeKit自动化/场景中使用开关实体关闭空调
