### ISSUE TITLE
小米Al音箱播放器 设置音量需要5s+

### ISSUE THREAD

**Issue by zscorpio** [al-one/hass-xiaomi-miot#911]
我得自动化逻辑是这样的:

1. 设置小爱音量50
2. 询问今天天气怎么样
3. 设置小爱音量15

通过查看时间发现耗时较多, 想问问有没有什么解决方案?
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1071075/205247981-9fb6bbf9-745a-4431-a4c5-8aecb7fd8cd5.png">
这是我的配置
```
alias: 每日一次出门天气预报
description: ""
trigger:
  - type: opened
    platform: device
    device_id: c8afa88e16742280c0301a0e48d8c5af
    entity_id: binary_sensor.0x00158d0003d0a8b4_contact
    domain: binary_sensor
condition:
  - condition: numeric_state
    entity_id: counter.mei_ri_tian_qi_yu_bao_ti_xing_ci_shu
    attribute: initial
    below: 2
    enabled: false
  - condition: time
    after: "07:30:00"
    before: "10:30:00"
    enabled: false
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.xiaomi_s12_24ec_play_control
  - service: xiaomi_miot.intelligent_speaker
    data:
      entity_id: media_player.xiaomi_s12_24ec_play_control
      text: 今天天气怎么样
      execute: true
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.mei_ri_tian_qi_yu_bao_ti_xing_ci_shu
  - service: media_player.volume_set
    data:
      volume_level: 0.15
    target:
      entity_id: media_player.xiaomi_s12_24ec_play_control
mode: single

```
