### ISSUE TITLE
NWT 18L 除湿机缺少水箱状态传感器实体 

### ISSUE THREAD

**Issue by MeowRay** [al-one/hass-xiaomi-miot#912]
### Device model

nwt.derh.wdh318efw1

### Integrated mode

Automatic (自动模式)

### The problem

缺少水箱传感器实体
米家中会在上方显示水箱满水或者不存在

**Comment by al-one** [comment]
请通过开发者工具[执行服务](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)，并从侧边栏获取结果：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: humidifier_wdh318efw1_xxxx
  method: get_prop
  params: [on_off, mode, auto, defrost_status, tank_full, fan_speed, child_lock, led, buzzer, fan_st, humidity]
  throw: true
```

**Comment by MeowRay** [comment]
> ```yaml
> service: xiaomi_miot.send_command
> data:
>   entity_id: humidifier_wdh318efw1_xxxx
>   method: get_prop
>   params: [on_off, mode, auto, defrost_status, tank_full, fan_speed, child_lock, led, buzzer, fan_st, humidity]
>   throw: true
> ```
侧边栏没东西，log里有报错
`2022-12-07 23:05:21.137 ERROR (SyncWorker_2) [custom_components.xiaomi_miot.humidifier] 除湿机(nwt.derh.wdh318efw1): Send miio command: get_prop(['on_off', 'mode', 'auto', 'defrost_status', 'tank_full', 'fan_speed', 'child_lock', 'led', 'buzzer', 'fan_st', 'humidity']) failed: {'code': -5000, 'message': 'invalid operation'}`

**Comment by al-one** [comment]
再次尝试以下服务：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: humidifier_wdh318efw1_xxxx
  method: get_prop
  params: [on_off]
  throw: true
```
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: humidifier_wdh318efw1_xxxx
  method: get_prop
  params: [mode]
  throw: true
```
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: humidifier_wdh318efw1_xxxx
  method: get_prop
  params: [on_off, mode]
  throw: true
```
