### ISSUE TITLE
峰米 R1 Nano 超短焦激光投影仪 不可用

### ISSUE THREAD

**Issue by kaosheng** [al-one/hass-xiaomi-miot#915]
### Device model

fengmi.projector.055fc

### Component version

0.72

### HA core version

2022.11.5

### Integrated mode

Automatic (自动模式)

### The problem

只有音量可以顯示,其他都不可用
![Fengmi_R1nano](https://user-images.githubusercontent.com/88337367/205426088-5df724ed-b3b2-40a4-b6c6-933d26b037b0.JPG)

### Entity attributes

```yaml
media_player.fengmi_055fc_f95b_play_control
source_list: HDMI 1, LOCAL
model: fengmi.projector.055fc
lan_ip: 192.168.31.82
mac_address: dc:a3:a2:15:f9:5b
entity_class: MitvMediaPlayerEntity
miot_type: urn:miot-spec-v2:device:projector:0000A02C:fengmi-055fc:1
6095_state: false
play_control.playing_state: 0
remote_control.screen_on: true
speaker.volume: 2
speaker.mute: false
projector.input_control: 4
state_updater: cloud
sub_entities: keycodes, speaker-4.volume-1
device_class: tv
friendly_name: 客厅的峰米 R1 Nano Play Control
supported_features: 20365
select.fengmi_055fc_f95b_keycodes
options: power, home, menu, enter, back, up, down, left, right, volumeup, volumedown
entity_class: SelectSubEntity
parent_entity_id: media_player.fengmi_055fc_f95b_play_control
friendly_name: 客厅的峰米 R1 Nano Play Control keycodes
supported_features: 0
```

### Home Assistant Logs

自行安裝整合產生錯誤。

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:209
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 24:32:30 (37 occurrences)
Last logged: 12:51:03

Request xiaomi api: https://api2.mina.mi.com/remote/ubus {'deviceId': '6214312b-3fe8-495b-84fa-a858eb91524e', 'path': 'mediaplayer', 'method': 'player_get_play_status', 'message': '{}'} failed, response: None
Request xiaomi api: https://userprofile.mina.mi.com/device_profile/v2/conversation {'hardware': 'LX05A', 'timestamp': 1670042216003, 'limit': 3} failed, response: None
Request xiaomi api: https://userprofile.mina.mi.com/device_profile/v2/conversation {'hardware': 'LX05A', 'timestamp': 1670042239001, 'limit': 3} failed, response: None
Request xiaomi api: https://userprofile.mina.mi.com/device_profile/v2/conversation {'hardware': 'LX05A', 'timestamp': 1670043035001, 'limit': 3} failed, response: None
Request xiaomi api: https://userprofile.mina.mi.com/device_profile/v2/conversation {'hardware': 'LX05A', 'timestamp': 1670043053001, 'limit': 3} failed, response: None
自行安裝整合產生錯誤。

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:68
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 24:21:18 (10 occurrences)
Last logged: 12:50:47

Request xiaomi api: miotspec/prop/get {'params': [{'did': '552054363', 'siid': 3, 'piid': 1}, {'did': '552054363', 'siid': 7, 'piid': 1}, {'did': '552054363', 'siid': 4, 'piid': 1}, {'did': '552054363', 'siid': 4, 'piid': 2}, {'did': '552054363', 'siid': 2, 'piid': 1}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '108649322', 'siid': 3, 'piid': 1}, {'did': '108649322', 'siid': 5, 'piid': 3}, {'did': '108649322', 'siid': 4, 'piid': 1}, {'did': '108649322', 'siid': 2, 'piid': 1}, {'did': '108649322', 'siid': 2, 'piid': 2}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': 'miwifi.2a77c970-ae28-6c3d-24cd-292d783dbb31', 'siid': 2, 'piid': 1}, {'did': 'miwifi.2a77c970-ae28-6c3d-24cd-292d783dbb31', 'siid': 2, 'piid': 2}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': 'ir.1495737037674962944', 'siid': 2, 'piid': 1}, {'did': 'ir.1495737037674962944', 'siid': 2, 'piid': 2}]} failed, response: None
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:797
Integration: 媒體播放器 (documentation, issues)
First occurred: 12:47:06 (1 occurrences)
Last logged: 12:47:06

Updating xiaomi_miot media_player took longer than the scheduled update interval 0:00:30
自行安裝整合產生錯誤。

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:183
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 07:35:29 (1 occurrences)
Last logged: 07:35:29

Unauthorized while executing request to https://userprofile.mina.mi.com/device_profile/v2/conversation, logged out.
