### ISSUE TITLE
deerma.humidifier.jsq5 missing water tank binary sensors and sound on/off switch

### ISSUE THREAD

**Issue by melentye** [al-one/hass-xiaomi-miot#916]
### Device model

[deerma.humidifier.jsq5](https://home.miot-spec.com/s/deerma.humidifier.jsq5)

### Component version

0.7.2

### HA core version

2022.11.5

### Integrated mode

Local (本地模式)

### The problem

deerma.humidifier.jsq5 device is missing some features

* binary sensors for water tank being present/absent and empty/non-empty
* switch for turning sound on/off

I've tried some advice from https://github.com/al-one/hass-xiaomi-miot/issues/434 :

```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq5:
      binary_sensor_properties: water_status,tank_status
```

or

```yaml
# configuration.yaml
homeassistant:
  customize: !include customize.yaml

# customize.yaml
humidifier.deerma_jsq5_9ab3_humidifier:
  binary_sensor_properties: water_status,tank_status
```

doesn't seem to work.

### Entity attributes

```yaml
min_humidity: 40
max_humidity: 80
available_modes: Off, Level1, Level2, Level3, Humidity
humidity: 55
mode: Humidity
model: deerma.humidifier.jsq5
lan_ip: <redacted>
mac_address: <redacted>
entity_class: MiotHumidifierEntity
exclude_miot_services: custom
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq5:1
humidifier.on: true
humidifier.fault: 0
humidifier.fan_level: 4
humidifier.target_humidity: 55
indicator_light.on: false
alarm: false
environment.relative_humidity: 54
environment.temperature: 24
state_updater: lan
sub_entities: environment-3.relative_humidity-1, environment-3.temperature-7, indicator_light-6
device_class: humidifier
friendly_name: <redacted>
supported_features: 1
binary_sensor_properties: water_status,tank_status
```

### Home Assistant Logs

2022-12-03 14:25:24.306 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by al-one** [comment]
Your device does not have properties `water_status,tank_status` in [miot-spec](https://home.miot-spec.com/spec/deerma.humidifier.jsq5).
You can try:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq5:
      exclude_miot_services: null
      binary_sensor_properties: water_shortage_fault,the_tank_filed
```
