### ISSUE TITLE
Missing entities on Mi Smart pet feeder

### ISSUE THREAD

**Issue by quinzico** [al-one/hass-xiaomi-miot#925]
### Device model / 设备型号

mmgg.feeder.fi1

### Component version / 插件版本

0.7.2

### HA core version / HA版本

2022.11.5

### Integrated mode / 集成方式

Token

### The problem / 问题详情

A lot of attributes does not have normal values. Also, i've seen the sub-entities associated with this product, but i cannot see it mapped on HA.

One subentity that i need is to know the level of food inside the feeder, whis is the property pet-food-left-level, which you can check on

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-fi1:1

### Entity attributes / 实体属性

![image](https://user-images.githubusercontent.com/57102800/206199136-59856b0e-15ca-40e9-a7d0-9b817db6aa0c.png)

**Comment by al-one** [comment]
> pet_feeder.pet_food_left_level: -4004 Other internal errors

The error is coming from the device and I don't know why this error occurs.
Maybe you can try these configurations:

```yaml
xiaomi_miot:
  device_customizes:
    mmgg.feeder.fi1:
      chunk_properties: 1
```
```yaml
xiaomi_miot:
  device_customizes:
    mmgg.feeder.fi1:
      exclude_miot_services: feedplanserve,keyserve,devicecontrolserve
```
