### ISSUE TITLE
小爱音箱tts不正常

### ISSUE THREAD

**Issue by shupcn** [al-one/hass-xiaomi-miot#93]
服务text里填好文字，执行不是播放文本，而是执行。
比如报时，不是播放“报时”，而是真正报时，北京时间10:00。

**Comment by al-one** [comment]
请将服务参数`execute`的值设置为`false`：
```yaml
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaoai_entity_id
  text: 报时
  execute: false # false: 不执行
```
![xiaomi_miot.intelligent_speaker](https://user-images.githubusercontent.com/4549099/119458654-8ed0cc00-bd6f-11eb-93f0-1f152b648167.png)
