### ISSUE TITLE
Xiaomi Smart Humidifier 2 inaccuracy in mode selection

### ISSUE THREAD

**Issue by Alex2zl** [al-one/hass-xiaomi-miot#930]
### Device model / 设备型号

[deerma.humidifier.jsq2w](https://home.miot-spec.com/s/deerma.humidifier.jsq2w)

### Component version / 插件版本

0.7.2

### HA core version / HA版本

2022.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I integrated the Xiaomi Smart Humidifier 2 humidifier (deerma.humidifier.jsq2w) into the home assistant, but there is an inaccuracy in the mode selection.
In modes you can choose:
0 - None (nothing happens when this is selected, but it switches to this mode when you select the fan level)
1 - Constant Humidity (this mode works correctly)
A separate sub-entity is the fan level:
1-Level1
2-Level2
3-Level3
4-Level4
The first 3 levels are responsible for the fan speed, and level 4 corresponds to 1 - Constant Humidity in the mode selection.
Is it possible to transfer these 4 levels to the mode selection? Then we get more correct modes: off, level 1, level 2, level 3 and Constant Humidity.

And a separate entity, the fan level, can be generally removed from the home assistant

In the current configuration (when the fan level is set separately), it is not convenient to control the humidifier on the dashboard

Help please

### Entity attributes / 实体属性

**humidifier.deerma_jsq2w_1707_humidifier:**
```yaml
min_humidity: 40
max_humidity: 70
available_modes:
  - 'Off'
  - None
  - Constant Humidity
humidity: 70
mode: Constant Humidity
model: deerma.humidifier.jsq2w
lan_ip: 192.168.0.109
mac_address: 58:B6:23:DB:17:07
entity_class: MiotHumidifierEntity
exclude_miot_services:
  - custom
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1
humidifier.on: true
humidifier.fault: 0
humidifier.fan_level: 4
humidifier.target_humidity: 70
humidifier.status: 2
humidifier.mode: 1
indicator_light.on: true
alarm: true
environment.relative_humidity: 73
environment.temperature: 28
state_updater: lan
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-7
  - indicator_light-6
  - humidifier.fan_level
device_class: humidifier
friendly_name: Humidifier xiaomi
supported_features: 1
```
**fan.deerma_jsq2w_1707_fan_level**
```yaml
preset_modes:
  - Level 1
  - Level 2
  - Level 3
  - Level 4
preset_mode: Level 4
entity_class: MiotModesSubEntity
parent_entity_id: humidifier.deerma_jsq2w_1707_humidifier
service_description: Humidifier
property_description: Fan Level
humidifier.fan_level: 4
humidifier.fan_level_desc: Level 4
friendly_name: Humidifier xiaomi Fan Level
supported_features: 8
```
