### ISSUE TITLE
IMI Home A1 Camera doesn't work

### ISSUE THREAD

**Issue by rafalolb** [al-one/hass-xiaomi-miot#933]
### Device model / 设备型号

camera.chuangmi_ipc019e_31e1_camera_control

### Component version / 插件版本

0.7.2

### HA core version / HA版本

2022.11.4 User interface: 20221108.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Perview of camera doesn't works.
![image](https://user-images.githubusercontent.com/16741990/207382693-896cf46b-6293-4508-a11e-3cc622523ead.png)
Camera is turned on, idle and unavailable. 

### Entity attributes / 实体属性
```yaml
friendly_name: IMI Home A1 Camera Control
supported_features: 1
entity_picture: /api/camera_proxy/camera.chuangmi_ipc019e_31e1_camera_control?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
model_name: chuangmi.camera.ipc019e
brand: chuangmi
model: chuangmi.camera.ipc019e
lan_ip: 192.168.10.23
mac_address: 64:90:C1:44:31:E1
entity_class: MiotCameraEntity
home_room: Dom Rafal Salon
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc019e:1
camera_control.on: true
camera_control.image_rollover: 180
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 2
camera_control.motion_tracking: false
state_updater: cloud
sub_entities: camera_control-2.on-1
```
### Home Assistant Logs / 系统日志

IMI Home A1(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1670342215000, 'isContinue': True}, 'description': '成功', 'ts': 1670947016038}
IMI Home A1(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1670342276000, 'isContinue': True}, 'description': '成功', 'ts': 1670947077074}
IMI Home A1(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1670342336000, 'isContinue': True}, 'description': '成功', 'ts': 1670947136904}
