### ISSUE TITLE
Gosund智能排插- cuco.plug.cp5pro 的問題

### ISSUE THREAD

**Issue by ericgtx5791** [al-one/hass-xiaomi-miot#936]
### Device model / 设备型号

cuco.plug.cp5pro

### HA core version / HA版本

2022.9.7

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

可否幫忙修復 Gosund智能排插CP5 pro 的(當前功率)與(當前電流)的實體?
目前整合此排插(cuco.plug.cp5pro)後僅有
今日用電量:sensor.cuco_cp5pro_1df0_power_cost_today
與
本月用電量:sensor.cuco_cp5pro_1df0_power_cost_month
這2個實體,
其他的
sensor.cuco_cp5pro_1df0_electric_current(當前電流)
sensor.cuco_cp5pro_1df0_electric_power(當前功率)
sensor.cuco_cp5pro_1df0_power_consumption(累積功率)
sensor.cuco_cp5pro_1df0_voltage(電壓)
這4個實體都是 unavailable.可否修正能有數據?

### Entity attributes / 实体属性

sensor.cuco_cp5pro_1df0_electric_current
sensor.cuco_cp5pro_1df0_electric_power
sensor.cuco_cp5pro_1df0_power_consumption
sensor.cuco_cp5pro_1df0_voltage

### Home Assistant Logs / 系统日志

實體不可用

**Comment by alanshu8** [comment]
Same issue, the "electric_power" value was deleted in the recent update, Is there any chance to have it back for power related control ?

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/415#issuecomment-1243869508
- https://github.com/al-one/hass-xiaomi-miot/issues/763#issuecomment-1350296660

If the `power_consumption` property is read by the component, the device will reset it and will not report to Xiaomi Cloud, which makes MiHome APP unable to display the power consumption. You can try these customizations to restore power sensors.

```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    cuco.plug.cp5pro:
      exclude_miot_services: device_setting,use_ele_alert
      exclude_miot_properties: power_consumption,electric_current,voltage
```
