### ISSUE TITLE
请添加对小米猫眼的支持 谢谢

### ISSUE THREAD

**Issue by jsfer888** [al-one/hass-xiaomi-miot#94]
{"status":"released","model":"loock.cateye.v02","version":1,"type":"urn:miot-spec-v2:device:video-doorbell:0000A03A:loock-v02:1"}

**Comment by al-one** [comment]
猫眼是已经支持的设备类型，请通过账号集成，但是通常只会创建一个电量传感器，原因是本插件是通过轮询的方式获取数据，对实时性有要求的数据无法及时获取。
而猫眼/门铃类设备通过有人时才会联网，因此可以通过ping设备IP检测是否有人在门前：
```yaml
binary_sensor:
  # https://www.home-assistant.io/integrations/ping#binary-sensor
  - platform: ping
    host: 192.168.lan.ip
    name: cateye_ping
    count: 1
    scan_interval: 2
```
