### ISSUE TITLE
Integrated xiaomi.camera.c01a01

### ISSUE THREAD

**Issue by tiimsvk** [al-one/hass-xiaomi-miot#959]
### Device model / 设备型号

xiaomi.camera.c01a01

### Component version / 插件版本

0.7.4

### HA core version / HA版本

2022.12.8

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

It is possible to integrate a camera from Xiaomi, model Smart Camera C300 XMCO1.  A simple stream would be enough for me.

### Entity attributes / 实体属性
```
entity_picture: >-
  /api/camera_proxy/camera.xiaomi_c01a01_e20a_camera_control?token=61fa04f31aa7b0139af3046bfb35f0049453756b080bc382307ac8ca03055aa
friendly_name: Xiaomi Smart Camera C300 Camera Control
supported_features: 3
acces_token: xxx
model_name: xiaomi.camera.c01a01
brand: xiaomi
frontend_stream_type: hls
model: xiaomi.camera.c01a01
lan_ip: 192.168.31.169
mac_address: 20:67:E0:B9:E2:0A
entity_class: MiotCameraEntity
home_room: Ľuboš Suchý's home Exterier
miot_type: urn:miot-spec-v2:device:camera:0000A01C:xiaomi-c01a01:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 0
camera_control.motion_tracking: false
camera_control.time_watermark: true
babycry_delection.babycry_onoff: false
speaker.volume: 90
speaker.mute.error: '-704220043 Property value error'
stream_status-10-9: 1
stream_status-9-9: 1
motion_detection: true
motion_detection.alarm_interval: 3
detection_sensitivity-5-3.error: '-704220043 Property value error'
motion_detection_start_time-5-4: '00:00'
motion_detection_end_time-5-5: '23:59'
memory_card_management.status.error: '-704220043 Property value error'
storage_total_space-4-2.error: '-704220043 Property value error'
storage_free_space-4-3.error: '-704220043 Property value error'
storage_used_space-4-4.error: '-704220043 Property value error'
indicator_light.on: true
state_updater: cloud
sub_entities:
  - motion_detection-5.motion_detection-1
  - indicator_light-3
  - camera_control-2.on-1
  - motion_event
motion_video_time: '2022-12-26 23:18:11'
motion_video_type: ObjectMotion
motion_video_latest:
  startDuration: 0
  cut: false
  offset: 0
  isCloud: false
  isRead: false
  videoStoreId: >-
    CAMERA_VIDEO_GOAC-imqC_t0xTYdxTF2B4f_qUt-fnCFxAQZXp2SWGtSS_hIURM9NqgbbDLI0hodOk3HHPuqxMTQUxqaoTqsf65dYo3wTkgbC6391SIjJTxC9IAX-h_oB6HTJiECrDA2jySL3VH-jhq0MDnu3So3kiVL9Fl1KOhy1yVQ7gpaCck2FiwUiR5y74na3mDjHKD2hE0BFBJM6Xnts1bZShS1TYwwiUX8JnVd8wTn7HFwAST_CgPK0QIPpQGKCW0PtZ3uoCEmR9xUbhQxPV_zqSrZ-Ado-qH_08dPbsfh5Q1Q4thaMkj2n77mjhiWaeVosnbzu6dfOicvH3CfXOPLxbhACd-8CrXSKcTsl2CqnYQKQl7v8_F36xnIwrNMSOmKoafGfzPXFKN4Eov2eOZ9X1wB9oBkFdyF8zHAuDuPmJcgQ9URA-dW2FdwtROpag271PpLhmCjdVrevGgc2Nhms5dJcr_mvhgSeaumU3GAREqbe0IuEQ_YekoBGBDcgo15l-y47rZP3AdDzY-eGBQ_qBb0ff6mTIXK1YEcMQ8XdPvJ9AA
  eventType: ObjectMotion
  expireTime: 1672697904213
  isAlarm: true
  isShowImg: true
  imgStoreId: >-
    CAMERA_IMG_GOAC-imqC_t0xTYdxTF2B4f_qUt-fnCFxAQZXp2SWGtSS_hIURM9NqgbbDLI0hodOk3HHPuqxMTQUxqaoTqsf65dYo3wTkgbC6391SIjJTxC9IAX-h_oB6HTJiECrDA2jySL3VH-jhq0MDnu3So3kiVL9Fl1KOhy1yVQ7gpaCck2FiwUiR5y74na3mDjHKD2hE0BFBJM6Xnts1bZShS1TYwwiUX8JnVd8wTn7HFwAST_CgPK0QIPpQGKCW0PtZ3uoCEmR9xUbhQxPV_zqSrZ-Ado-qH_08dPbsfh5Q1Q4thaMkj2n77mjhiWaeVosnbzu6dfOicvH3CfXOPLxbhACd-8CrXSKcTsl2CqnYQKQl7v8_F36xnIwrNMSOmKoafGfzPXFKN4Eov2eOZ9X1wB9oBkFdyF8zHAuDuPmJcgQ9URA-dW2FdwtROpag271PpLhmCjdVrevGgc2Nhms5dJcr_mvhgSeaumU3GAREqbe0IuEQ_YekoBGBDcgo15l-y47rZP3AdDzY-eGBQ_qBb0ff6mTIXK1YEcMQ8XdPvJ9AA
  fileId: '84688496342618368'
  extraInfo: '{"ver":"1.0.0","alarmStart":true,"eventType":"ObjectMotion"}'
miot_action_result:
  did: '1037661099'
  miid: 0
  siid: 9
  aiid: 1
  code: -706010002
  exe_time: 0
  withLatency: 0
miot_action_error: '-706010002 Service does not exist'
stream_address: ''
expire_at: '2022-12-26 23:54:36.443046'
```
