### ISSUE TITLE
小米智能开关零火版不能添加到“能源”

### ISSUE THREAD

**Issue by Ryan1202** [al-one/hass-xiaomi-miot#967]
### Device model / 设备型号

[lumi.switch.acn016](https://home.miot-spec.com/s/lumi.switch.acn016)
[lumi.switch.acn017](https://home.miot-spec.com/s/lumi.switch.acn017)
[lumi.switch.acn018](https://home.miot-spec.com/s/lumi.switch.acn018)

### Component version / 插件版本

0.7.4

### HA core version / HA版本

2022.12.8

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米智能开关零火版在状态里可以看到有power consumption，但是“能源”可以添加的设备里没有，顺带一提这个单位应该是kWh

### Entity attributes / 实体属性
```yaml
entity_class: MiotSensorSubEntity
parent_entity_id: switch.lumi_acn016_42c5_switch
service_description: Power Consumption
property_description: Power Consumption
updated_time: 2022-12-26T23:00:02.556572+08:00
power_consumption: 0.486
unit_of_measurement: Wh
friendly_name: Xiaomi Smart Wall Switch (1 Gang, Neutral Wire) Power Consumption
supported_features: 0
```

**Comment by al-one** [comment]
![lumi.switch.acn016 power consumption](https://user-images.githubusercontent.com/4549099/209783828-1b48db97-6010-4c9d-80f0-acea76bbc020.png)

`power_consumption`在miot规格中的属性未定义单位，且未描述计量的时间范围。如果是历史所有的合计，可以尝试[自定义实体](https://github.com/al-one/hass-xiaomi-miot/issues/600)：

```yaml
# customize.yaml
sensor.lumi_acn016_42c5_power_consumption:
  state_class: total
  device_class: energy
  unit_of_measurement: kWh
```
