### ISSUE TITLE
The device is offline (power is cutoff), but the status is being updated continuously

### ISSUE THREAD

**Issue by dahapublic** [al-one/hass-xiaomi-miot#970]
My cooker is **chunmi.cooker.normal3**
[**米家IH电饭煲 4L**](https://home.miot-spec.com/s/chunmi.cooker.normal3)

Most of the time the device will be offline, but during that time, the status will be updated continuously as shown below.
Therefore, the logbook is very messed up
Can anyone help me fix this problem?
Thank you very much!

<img width="686" alt="Screenshot 2023-01-02 at 5 08 19 PM" src="https://user-images.githubusercontent.com/17398062/210217961-50d7c0ea-1184-4dc8-85c8-4675c9fe5bd8.png">

**Comment by al-one** [comment]
Customize this device:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    chunmi.cooker.normal3:
      check_lan: true
```

- https://github.com/al-one/hass-xiaomi-miot/issues/91#issuecomment-846492664
- https://github.com/al-one/hass-xiaomi-miot/issues/100#custom
- https://github.com/al-one/hass-xiaomi-miot/issues/600
