### ISSUE TITLE
小爱音箱-pro,静默执行取反了

### ISSUE THREAD

**Issue by vincenthsing** [al-one/hass-xiaomi-miot#973]
```yaml
service: xiaomi_miot.intelligent_speaker
data:
  entity_id: media_player.xiaomi_lx06_aaab_play_control
  execute: true
  text: 今天天气怎么样
  silent: false
```

上诉silent参数,在[小爱音箱pro](https://home.miot-spec.com/s/xiaomi.wifispeaker.lx06)上取反了,即设置为true,会发声反馈,设置为false则是静默.测试了家里的三个不同型号的小爱,分别是redmi型号,mini型号还有pro型号,其他俩型号音箱是是正常的,就pro取反了.

当前HACS最新版本(0.7.4),之前的老版本是正常的
