### ISSUE TITLE
Fix for electric floor heater cubee.airrtc.th123e with external temperature sensor (wrong temperature used)

### ISSUE THREAD

**Issue by Sol1in** [al-one/hass-xiaomi-miot#980]
Hello!

I have thermostat for electric floor heater with external temperature sensor. It is translating via **heatold.tempfloor** parameter, but thermostat is using only **current_temperature** parameter that is not actual. Maybe there is a way to fix that somehow?

```yaml
hvac_modes: auto, off
min_temp: 0
max_temp: 90
target_temp_step: 1
preset_modes: Home, Away, Smart, Sleep, off
current_temperature: 14
temperature: 27
hvac_action: idle
preset_mode: Away
model: cubee.airrtc.th123e
lan_ip: 192.168.0.137
mac_address: 54:48:E6:DE:FE:A4
entity_class: MiotClimateEntity
home_room: Savelovskiy City Туалет
exclude_miot_properties: fault, sensortype
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:cubee-th123e:1
thermostat.on: true
thermostat.status: 0
thermostat.mode: 2
thermostat.target_temperature: 27
thermostat.temperature: 14
heatold.childlock: false
heatold.tempactivate: 2
heatold.tempcomp: -9
heatold.tempfloor: 26
heatold.maxsettemp: 40
heatold.minsettemp: 5
state_updater: lan
sub_entities: heatold-4.childlock-1, heatold-4.tempactivate-3, heatold-4.tempcomp-4, heatold-4.tempfloor-5, heatold-4.maxsettemp-6, heatold-4.minsettemp-7
friendly_name: Toilet Floor Thermostat Thermostat
supported_features: 17
```
