### ISSUE TITLE
Humidifier JSQ4

### ISSUE THREAD

**Issue by SandDeath** [al-one/hass-xiaomi-miot#991]
### Device model / 设备型号

[deerma.humidifier.jsq4](https://home.miot-spec.com/s/deerma.humidifier.jsq4)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.1.2

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

deerma.humidifier.jsq4 device is missing some features

binary sensors for water tank being present/absent and empty/non-empty

I repeated the advice from https://github.com/al-one/hass-xiaomi-miot/issues/916:
this helped to get the necessary properties, can it be added to the main branch for this model as well?

### Entity attributes / 实体属性
```yaml
min_humidity: 40
max_humidity: 80
available_modes:
  - 'Off'
  - Level1
  - Level2
  - Humidity
humidity: 60
mode: Humidity
model: deerma.humidifier.jsq4
lan_ip: 192.168.31.91
mac_address: B4:60:ED:B3:9F:4D
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq4:1
humidifier.on: true
humidifier.fault: 0
humidifier.fan_level: 3
humidifier.target_humidity: 60
custom.water_shortage_fault: false
custom.the_tank_filed: false
indicator_light.on: true
alarm: true
environment.relative_humidity: 43
environment.temperature: 21
state_updater: lan
device_class: humidifier
friendly_name: deerma_humidifier_jsq4 Humidifier
supported_features: 1
```
