### ISSUE TITLE
小爱音箱HD  intelligent_speaker服务不支持

### ISSUE THREAD

**Issue by CaiNiaoLucifer** [al-one/hass-xiaomi-miot#993]
### Device model / 设备型号

[onemore.wifispeaker.sm4](https://home.miot-spec.com/s/onemore.wifispeaker.sm4)

### Component version / 插件版本

0.7.4

### HA core version / HA版本

2022.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

intelligent_speaker 调用之后，音箱没有反应
还有其他几个小爱同学，是可以正常响应的

### Entity attributes / 实体属性
```yaml
device_class: speaker
friendly_name: 小爱音箱HD Play Control
supported_features: 17413
volume_level: 0.72
model: onemore.wifispeaker.sm4
lan_ip: 192.168.55.55
mac_address: 11:22:33:44:55:66
entity_class: MiotMediaPlayerEntity
miot_type: urn:miot-spec-v2:device:speaker:0000A015:onemore-sm4:1
play_control.playing_state: 0
microphone.mute: true
speaker.volume: 72
state_updater: cloud
```

### Home Assistant Logs / 系统日志

无
