### ISSUE TITLE
add ambient light effect?

### ISSUE THREAD

**Issue by konistra** [al-one/hass-xiaomi-miot#997]
There are effects in the official yeelight integration 

> effect_list: Strobe color, Police, Christmas, RGB, Random Loop, Fast Random Loop, LSD, Slowdown, Night Mode, Date Night, Movie, Sunrise, Sunset, Romance, Happy Birthday, Disco, Strobe epilepsy!, Alarm, Police2, WhatsApp, Facebook, Twitter, Home, Candle Flicker, Slow Temp, Stop

is it possible to transfer or add your own to the Xiaomi Miot integration?

> effect_list: RGB, HSV

 do they not work.

Light https://home.miot-spec.com/spec/yeelink.light.ceilb

**Comment by al-one** [comment]
Try this [service](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command):

```yaml
service: xiaomi_miot.send_command
data:
  entity_id: light.yeelink_ceilb_xxxx
  method: start_cf
  params:
    - 0 # count: The number of times to run this flow (0 to run forever)
    - 1 # action: The action to take after the flow stops. Can be `0` to go back to the state before the flow, `1` to stay at the last state, and `2` to turn off
    - 1996, 1, 14438425, 80, 1996, 1, 14448670, 80, 1996, 1, 11153940, 80 # transitions: happy_birthday
  throw: true
```
